### ISSUE TITLE
Option to filter all objets by structure by default

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1013]
So that users from different structures can share a single instance of Geotrek, without sharing data explicitly

Related : https://github.com/makinacorpus/Geotrek/issues/1011

**Comment by camillemonchicourt** [comment]
Geotrek-admin synchronization now allows to filter datas by source or portal. 
Documentation at https://geotrek.readthedocs.io/en/master/synchronization.html#synchronization-filtered-by-source-and-portal
