### ISSUE TITLE
Allow to transform a feedback attachment into related object attachment

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1016]
If a feedback has an attachment (submitted by a Geotrek-rando or Geotrek-mobile user for example), there should a menu/button to move it to the related object (trek of POI).

This way, the editorial team can pick among user submitted content to populate trek and POIs pictures...
- [ ] Add a specific permission to do that
- [ ] Think generic : maybe, we can do a menu to copy/move an attachment to any other model (this would then be implemented in django-mapentity)

**Comment by babastienne** [comment]
@camillemonchicourt I don't think this feature is completed and currently exists in Geotrek ?

**Comment by camillemonchicourt** [comment]
Non, mais pas pertinent il m'a semblé.
Les médias des signalements n'ont pas d'intérêt à être basculés en tant qu'image de POI.
