### ISSUE TITLE
Ability to publish infrastructures on public website

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1077]
Ex: camping tables ...

**Comment by camillemonchicourt** [comment]
OK donc pour ajouter un champs ``Publié`` (oui/non) dans la table ``gestion.a_t_amenagement`` qui regroupe les aménagements et la signalétique pour pouvoir les publier sur le portail Geotrek-rando comme les POIs et objets touristiques.

Un paramètre dans Geotrek-admin permettant d'activer ou non cette publication globalement serait bien quand même, car en voyant apparaitre ce champs, il est fort possible que certains ne sachent pas à quoi il correspond et cochent ``Publié = Oui`` en pensant qu'il s'agit d'une info liée à la validation et que ça le publie sur le Geotrek-rando de la structure alors que cela n'est pas souhaité. 

Comme sur d'autres champs actuellement, ça vaudrait le coup d'ajouter un petit label du type ``Pour publier cet objet sur le portail Geotrek-rando``. 

Et si on ajoute cette possibilité de publier des aménagements, il faudrait aussi ajouter le champs ``Portail cible`` pour ceux qui publient sur différents portails depuis un même Geotrek-admin. Et du coup ``Source`` aussi ?

Penser aussi à ajouter le champs ``Publié`` dans les filtres du module, ainsi que dans les exports.

**Comment by camillemonchicourt** [comment]
Attention, aux fichiers attachés et à leur publication. 
Dans ces modules il peut y avoir des documents attachés métier qui n'ont pas vocation à être publiés sur le portail rando. 
A voir si on on peut faire en sorte de ne publier que les images, pour ne pas aussi publier les PDF, xls et autres documents métier qui pourraient être attachés à une signalétique.

**Comment by thomaspnrhj** [comment]
De mon côté, je pensais plutôt à ne pas afficher de photo car ce qui est important c'est surtout la localisation et le nom de poteau pour que le randonneur puisse se positionner, la photo n'apporte rien et alourdit l'information. Comme tu dis Camille, il faut éviter l'usine à gaz. Idem pour un aménagement, le but est de connaitre la nature de l'aménagement et son positionnement. J'imaginais plutôt un pictogramme ou une photo commune pour la signalétique et pour les aménagements.

**Comment by thomaspnrhj** [comment]
De mon côté, je pensais plutôt à ne pas afficher de photo car ce qui est important c'est surtout la localisation et le nom de poteau pour que le randonneur puisse se positionner, la photo n'apporte rien et alourdit l'information. Comme tu dis Camille, il faut éviter l'usine à gaz. Idem pour un aménagement, le but est de connaitre la nature de l'aménagement et son positionnement. J'imaginais plutôt un pictogramme ou une photo commune pour la signalétique et pour les aménagements.

**Comment by camillemonchicourt** [comment]
Oui pourquoi pas.
Dans ce cas, sur le portail Geotrek-rando, on pourrait aussi imaginer ne pas les afficher dans le bloc de droite comme les POI mais plutôt comme un couche affichable ou non sur la carte comme les Services (infos pratiques) pour ne pas alourdir le bloc de droite.

**Comment by thomaspnrhj** [comment]
Oui pourquoi pas à condition que ça soit visible et instinctif pour l'utilisateur

**Comment by jgf66** [comment]
> OK donc pour ajouter un champs `Publié` (oui/non) dans la table `gestion.a_t_amenagement` qui regroupe les aménagements et la signalétique pour pouvoir les publier sur le portail Geotrek-rando comme les POIs et objets touristiques.
> 
> Un paramètre dans Geotrek-admin permettant d'activer ou non cette publication globalement serait bien quand même, car en voyant apparaitre ce champs, il est fort possible que certains ne sachent pas à quoi il correspond et cochent `Publié = Oui` en pensant qu'il s'agit d'une info liée à la validation et que ça le publie sur le Geotrek-rando de la structure alors que cela n'est pas souhaité.
> 
> Comme sur d'autres champs actuellement, ça vaudrait le coup d'ajouter un petit label du type `Pour publier cet objet sur le portail Geotrek-rando`.
> 
> Et si on ajoute cette possibilité de publier des aménagements, il faudrait aussi ajouter le champs `Portail cible` pour ceux qui publient sur différents portails depuis un même Geotrek-admin. Et du coup `Source` aussi ?
> 
> Penser aussi à ajouter le champs `Publié` dans les filtres du module, ainsi que dans les exports.

Que pensez-vous d'ajouter un droit "can publish infrastructure" dans l'admin ?

**Comment by camillemonchicourt** [comment]
Oui en effet, il sera aussi nécessaire d'ajouter cette permission pour pouvoir autoriser ou non l'accès à la publication des aménagements et de la signalétique.
D'ailleurs les 2 sont dans une même table mais ce sont 2 objets dissociés dans l'admin. 
Du coup il faut ajouter les 2 : 
- Can publish infrastructure
- Can publish signage

**Comment by camillemonchicourt** [comment]
Voir https://github.com/GeotrekCE/Geotrek-admin/pull/1791

**Comment by camillemonchicourt** [comment]
Concernant les photos de l'aménagement, c'est dommage de ne pas en disposer quand on les publie. 

Si ce ne sont que des pictos sur la carte avec une tooltip au survol (comme les Services), ça vaudrait le coup de pouvoir y intégrer une photo de l'aménagement.

**Comment by camillemonchicourt** [comment]
OK fonctionnalité ajoutée dans la version 2.22.0.
Je pense qu'il serait bon d'améliorer le texte d'info car cette fonctionnalité porte à confusion pour ceux qui ne savent pas ce que c'est et/ou à quoi elle correspond. 
Donc je propose de remplacer le texte d'info de "Publié" à "Publié sur le portail web".

Pour les images, je ne sais pas si une image a été intégrée dans la synchro mais ça me semble utile pour l'affichage sur Geotrek-rando.

La fonction n'est pas paramétrable pour permettre de la désactiver et ainsi ne pas l'afficher. Peut-être pas essentiel. 
Mais en l'état je sais que les agents de terrain qui font l'inventaire vont se demander (ou me demander) ce qu'ils doivent faire avec ce champs.

Et la publication n'est pas définissable par Portail donc non fonctionnelle en l'état pour ceux qui synchronise par Portail.

**Comment by camillemonchicourt** [comment]
Sinon plutôt que de rendre la fonctionnalité activable ou non, @gutard propose encore plus simple et opérationnel : Masquer le champ publier si on n'a pas le droit correspondant. 
Ce serait une bonne chose et réglerait le problème de confusion pour les gestionnaires.

**Comment by gutard** [comment]
En fait c'est déjà le cas.

**Comment by camillemonchicourt** [comment]
En effet, je viens de voir ça, super

Ne resterait donc que la question de publier par Portail pour ceux qui utilisent ce filtre.

Et à ajuster aussi quand on séparera la table de la signalétique à part des aménagements https://github.com/GeotrekCE/Geotrek-mobile/releases

**Comment by camillemonchicourt** [comment]
La signalétique (ainsi que les aménagements) sont désormais publiables, présents dans l'API v2 et affichés sur la v3 de Geotrek-rando.
