### ISSUE TITLE
0.24.2 - Trek related links

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1135]
TRAIL 1 is linked to TRAIL 2 :
![1-5](https://cloud.githubusercontent.com/assets/4418840/3413687/194d4d32-fe0e-11e3-8cfe-279456e4db65.jpg)

But this link dont appear in TRAIL 2 detail page : 
![2-5](https://cloud.githubusercontent.com/assets/4418840/3413689/1aebfcb0-fe0e-11e3-9507-11a9562fab7c.jpg)

Only a display problem ?

**Comment by babastienne** [comment]
Tested. Solved.

![image](https://user-images.githubusercontent.com/16348048/227340223-c0cd5524-6d04-48ac-a12b-42a77bd0872c.png)
