### ISSUE TITLE
Bad behaviour on path split

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1153]
![geotrek pb segmentation tronon](https://cloud.githubusercontent.com/assets/546692/3643594/cb3efe08-10d5-11e4-9f7c-c1b4fd31fcfc.jpg)

un bug lors de la segmentation d'un tronçon existant en prolongeant le nouveau tronçon que l'on veut connecter au milieu du tronçon existant. Comme tu peux le voir le tronçon existant a bien été coupé mais le tronçon de gauche n'est plus jointif... et le nouveau tronçon ralongé (en jaune) pour couper n'a pas été segmenté à la jointure

**Comment by camillemonchicourt** [comment]
Yes certainly fixed since several releases as I just tested it again on a 2.18.3 and got no problem of splitting.
