### ISSUE TITLE
Preview static pages from AdminSite

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1191]
Implement a mecanism to preview from Geotrek-rando...

Among solutions : 
- POST the page to a new view in Geotrek-rando ( _what about images?_ )
- Add a view in Geotrek-rando that will temporarily pull the page and its media to show it

**Comment by camillemonchicourt** [comment]
Pas très utile selon moi, car on peut facilement visualiser une page statique sur Geotrek-rando depuis GTR v3. Il suffit de la publier, personne ne le saura tant qu'elle n'est pas associée à un élément de menu. Et on retrouve son URL facilement (https://URL-GTR3/information/ID-PAGE). En effet on renseigne seulement son identifiant et GTR3 se charge de rediriger directement vers son URL complète.

Et pas souhaitable selon moi, car GTA n'a pas à connaitre le (ou les) GTR.
