### ISSUE TITLE
Add Trek networks in PDF export

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1199]
Le renommer en BALISAGE (dans les fiches, les formulaires, le filtre et l'adminsite). 
Ça sera plus clair par rapport à l'usage fait coté GEOTREK-RANDO et ça évitera des confusions avec le champ RESEAUX des tronçons.

**Comment by babastienne** [comment]
Still not solved in 2.97.4  :facepalm:

**Comment by babastienne** [comment]
Résolu, existe déjà dans les PDF : https://github.com/GeotrekCE/Geotrek-admin/commit/48f4aed6caebeb74a3997a40b134c090cbdec087
