### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#1264]
Mainly to have : 
- Translated application labels in Adminsite
- Cleaner startup code (see https://github.com/makinacorpus/Geotrek/issues/831)
- Configuration checks

Requires https://github.com/makinacorpus/django-mapentity/pull/92

**Comment by leplatrem** [comment]
Side note: Django 1.6 and 1.7 are not supported anymore :children_crossing:

**Comment by LePetitTim** [comment]
Since 2.18. Django 1.11
