### ISSUE TITLE
Display objects from other modules

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1300]
When you are in a module (list, detail or edit), it would be useful to be able to display other modules objects on the map (it used to be possible I think).
Example if you are editing a PATH, it can be interesting to display SIGNAGES on maps.

**Comment by camillemonchicourt** [comment]
Since a few versions, it is possible to display touristic contents and events on any map : 

![image](https://user-images.githubusercontent.com/4418840/58471676-b53ddb80-8144-11e9-8de3-9eb724325580.png)

I dont know since when and why only those 2 objects, but would be good with other kind of objects. And when mouse over one object on the map, would need to display its name in tooltip or <title>.

**Comment by camillemonchicourt** [comment]
Quand on survole un objet d'un autre module sur la carte, afficher son nom et au clic, accéder à sa fiche détail.

**Comment by Chatewgne** [comment]
Ok fixé et mergé

**Comment by camillemonchicourt** [comment]
Cette fonctionnalité a été intégrée dans la 2.82.0 (uniquement l'affichage des objets sur la carte, sans afficher leur nom au survol) : 

![image](https://user-images.githubusercontent.com/4418840/165581744-1f610ff7-3b52-46ec-bcf4-e67db692411b.png)

Reste juste des traductions à faire et mettre tous les noms de couche au pluriel pour harmoniser

**Comment by camillemonchicourt** [comment]
TODO : 
- Corriger les traductions
- Ajouter une tooltip avec nom et type de l'objet
- Pouvoir afficher aussi les objets du même module (je suis sur une fiche signalétique, je peux voir les objets signalétique sur le carte) car actuellement on ne peut voir que les objets des autres modules

**Comment by camillemonchicourt** [comment]
Pour compléter les TODO, il faudrait aussi ajouter le couche du module SENTIERS dans les couches affichables dans les autres modules.
Je ne sais pas pourquoi elle n'a pas été ajoutée en même temps que les autres.

**Comment by babastienne** [comment]
TODO : 
- Corriger les traductions
- Ajouter comme couche les objets du module en cours (si je suis dans une vue détail du module intervention je veux pouvoir regarder les autres interventions)
- Ajouter les informations du module Sentiers
- Pouvoir afficher les informations (nom de l'objet) au survol
<details><summary>Details survol</summary>
<p>

> Quand on survole un objet d'un autre module sur la carte, afficher son nom et au clic, accéder à sa fiche détail.

@juggler31 essayer d'ajouter une propriété "name" dans le geojson pour voir cela affiche automatiquement au survol le nom de l'objet ?

⚠ Attention à être vigilant sur les interactions voir si c'est facile de naviguer / lisible dans l'interface si on ajoute ces étiquettes au survol

</p>
</details>

**Comment by camillemonchicourt** [comment]
Ajout d'une tooltip au clic sur les objets des autres modules sur la carto, dans la 2.121.0 : 

<img width="622" height="586" alt="Image" src="https://github.com/user-attachments/assets/b3942b3d-9848-49fa-8b7c-dfe22dcfe478" />
