### ISSUE TITLE
Landedge - Rename Foncier / statuts

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1301]
In all details pages, "FONCIER" should be renamed "STATUTS" and "Statuts" should be renamed "Types fonciers".
"Tronçons physique " should be renamed "Types de voie"
"Tronçons de compétence" should be renamed "Compétence sentiers"
"Tronçons de gestion de travaux" should be renamed "Gestionnaire travaux"
"Tronçons de gestion signalétique" should be renamed "Gestionnaire signalétique"

Same in Status module, filters, and layers selection in maps.

**Comment by Chatewgne** [comment]
> "Tronçons physique " should be renamed "Types de voie"
> "Tronçons de compétence" should be renamed "Compétence sentiers"
> "Tronçons de gestion de travaux" should be renamed "Gestionnaire travaux"
> "Tronçons de gestion signalétique" should be renamed "Gestionnaire signalétique"

-> OK in https://github.com/GeotrekCE/Geotrek-admin/pull/2832


> In all details pages, "FONCIER" should be renamed "STATUTS" and "Statuts" should be renamed "Types fonciers".

-> Est-ce que je pourrais avoir plus de précision pour identifier les chaînes de charactères stp @camillemonchicourt  (screenshots ?)

Je vois cette ligne dans le changelog, comme c'est un vieux ticket cela a peut être déjà été fait ?
https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#0241-2014-06-26

**Comment by camillemonchicourt** [comment]
OK en effet #1126 a corrigé le titre dans le sélecteur de couches des cartes.
J'imagine que le renommage dans le fichier de traduction, renommera les noms des couches dans le sélecteur : 
![image](https://user-images.githubusercontent.com/4418840/143442297-dc011e81-bbd2-4c66-8a6b-7d0cb23dda0e.png)

Idem pour les filtres : 
![image](https://user-images.githubusercontent.com/4418840/143442372-53b94c13-0c39-4189-a52e-ebbde48ee5d2.png)

Il ne resterait donc qu'à corriger dans les fiches détail de tous les objets où "Foncier" et "Statuts" sont inversés : 
![image](https://user-images.githubusercontent.com/4418840/143442498-3b606729-479c-4413-919e-88fdf98ecafc.png)

**Comment by Chatewgne** [comment]
![image](https://user-images.githubusercontent.com/26015573/143556353-5b8a3029-e3a6-41f5-a4a4-5630f1ee3dc3.png)

Comme ça pour les couches @camillemonchicourt ?

**Comment by camillemonchicourt** [comment]
Non non, c'est ce qui avait déjà été corrigé. Statuts est l'ensemble des 5 objets. Le module global.
Donc STATUTS est le titre du bloc.
J'indiquai que dans les filtres et le selecteur de couche, il n'y avait à priori rien à changer si les noms des couches utilisaient bien le fichier de langue que tu as modifié.

Dans ce cas, il n'y a que dans les fiches détails qu'il faut inverser Statuts qui est le titre global du bloc et Foncier (nommé "Type foncier") qui est le premier item.

**Comment by Chatewgne** [comment]
Ah d'accord, dans le fichier de langue j'ai changé celles qui commencent par le mot "Tronçon" donc c'est celles de la page détail

![image](https://user-images.githubusercontent.com/26015573/143558036-62ef0155-7cb2-4462-bd2f-0d7cf20e69e5.png)

Ceux là ne sont pas changés, est-ce que je reporte les mêmes dénomination que ci-dessus ?

![image](https://user-images.githubusercontent.com/26015573/143558916-b69e66b8-705d-4fdd-bbb4-15097b325509.png)

![image](https://user-images.githubusercontent.com/26015573/143558998-272e544f-59c9-4cae-9b10-47e31235e94a.png)

**Comment by camillemonchicourt** [comment]
OK dans la fiche détail, "Foncier" doit être remplacé par "Type foncier".
Et oui il faut aussi répercuter dans les filtres et dans le sélecteur de couches, pour tout mettre pareil et en cohérence.

Je vois qu'il y a aussi un mélange de termes dans le module lui-même, c'est n'importe quoi : 
![image](https://user-images.githubusercontent.com/4418840/143562309-259f0bb4-cd2f-4621-99a2-d3ab86d203ed.png)

- Renseigner la nature foncière >> Renseigner le type foncier
- Renseigner la nature physique >> Renseigner le type de voie
- Renseigner l'organisme compétent > Renseigner la compétence sentier
- Zones de compétence > Compétence sentier
- Types foncier > Types fonciers (manque le S)
- Types physique > Types de voie (manque le S)

Dans ton renommage il y a un S de trop : 
- Types de voies > Types de voie

**Comment by camillemonchicourt** [comment]
Je vois qu'il y a aussi le title dans le module qui parle de tronçon alors que ce ne sont pas des tronçons et que cela porte à confusion avec le module "Tronçons" : 
![image](https://user-images.githubusercontent.com/4418840/143565277-641eecc1-ca0a-40be-8854-2f27dfe61759.png)

Il faut le même terme partout, donc ici le title devrait être aussi "Gestionnaire signalétique".

Bref, un bon gros ménage à faire pour avoir le même vocabulaire partout.

A voir si les changements permettant aussi de mettre ça en cohérence dans les autres langues (anglais notamment)

**Comment by Chatewgne** [comment]
En regardant modèles et les dénominations anglaises

On a : 

Land : Statuts (nom du module)

Typologies dans l'Admin:
Land type : Type de voie
Physical type : Type foncier
![image](https://user-images.githubusercontent.com/26015573/143569760-912c80c1-e54d-444c-8860-aba4b5eebab3.png)
![image](https://user-images.githubusercontent.com/26015573/143569939-85d216b2-ec47-4e32-9032-bb73933a430b.png)

Objets :
Land edge : Type de voie (lié au tronçon)
Physical edge : Type foncier (lié au tronçon)
Compétence edge : Compétence sentier
Signage management edge : Gestionnaire signalétique
Work management edge : Gestionnaire travaux

Tu peux te connecter sur [test-admin.geotrek.fr](test-admin.geotrek.fr) (admin:admin) pour naviguer dans le module et me confirmer si cela te convient

**Comment by camillemonchicourt** [comment]
OK, je pense qu'en effet, il y a un soucis à la base de définition des concepts en anglais. 
On devrait parler de "Status" et pas de "Land" pour le nom du module et des tables et modèles.
Et je sais pas d'où vient ce terme "Edge" et ce qu'il veut dire mais il n'est pas adapté non plus je pense.
Mais bon, on va pas aller tout changer en anglais ni les modèles, les tables etc pour le moment je pense :-)

On va rester sur les traductions en français je pense si ça pose pas de soucis.

Sauf peut-être ici pour être cohérent, où on devrait mettre "Status" et pas "Land" dans les fiches détail, si ça met pas le bazar dans les fichiers en anglais : 

![image](https://user-images.githubusercontent.com/4418840/143582223-9dbc87dc-b774-45f5-8acf-c3fa1cc9feec.png)

Et dans le sélecteur de couches, mettre aussi "Status" au lieu de "Land edges" : 

![image](https://user-images.githubusercontent.com/4418840/143582646-03fe9582-800a-4224-8cd0-1012c8436146.png)

Ainsi que le tooltip du module qui a un T en trop ("Status" en anglais et pas "Statuts") : 
![image](https://user-images.githubusercontent.com/4418840/143582349-6f4b2feb-7e21-4bf5-a9fd-7b4949b17b8c.png)

Idem dans la liste des modules : 

![image](https://user-images.githubusercontent.com/4418840/143582402-25ea1b7e-0027-4212-affe-49bb102290d0.png)

En français, tout me semble OK, sauf le sélecteur de couche dont le bloc est nommé "Types fonciers" au lieu de "Statuts".
Et où "Signage management" et "Work management" ne sont pas traduits : 

![image](https://user-images.githubusercontent.com/4418840/143580975-d5964177-0f70-48a0-be19-d596fd9175c5.png)

Merci.

**Comment by Chatewgne** [comment]
Mis à jour sur [https://test-admin.geotrek.fr](https://test-admin.geotrek.fr), peux-tu jeter un oeil à nouveau ? :)

**Comment by camillemonchicourt** [comment]
OK c'est tout bon comme ça.
Joli nettoyage, merci.

**Comment by Chatewgne** [comment]
merged https://github.com/GeotrekCE/Geotrek-admin/pull/2832

**Comment by camillemonchicourt** [comment]
OK dans la 2.73.0.
On pourrait encore mettre un peu plus en cohérence en anglais, mais là déjà on est pas mal ! :-)
