### ISSUE TITLE
Unpublish trek in all languages when path is deleted

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1321]
Je supprime un tronçon, si un itinéraire l'utilisait, alors celui-ci est dépublié.
Cependant il n'est dépublié qu'en français et reste publié en Anglais et Italien.

**Comment by babastienne** [comment]
Still not fixed in 2.97.4 ...

**Comment by babastienne** [comment]
Finally fixed in release [2.100.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.100.0) :tada:
