### ISSUE TITLE
3D length < 2D length

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1337]
The sampling method used to drape the geometries leads to 3D linestrings that are shorter (in 2D) than original 2D ones.

**Comment by camillemonchicourt** [comment]
Le calcul des longueurs 3D est désormais cohérent avec les longueurs 2D. 
Testé avec la version 0.29.0 en place sur le serveur de test - http://geotrekdemo.ecrins-parcnational.fr/ (demo / demo).

Merci.
