### ISSUE TITLE
TRAILS in detail page are not displayed.

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1367]
I am on a TRAIL detail page, it includes many INTERVENTIONS : 

![travaux](https://cloud.githubusercontent.com/assets/4418840/6230894/6f486b40-b6c3-11e4-8229-f4bf6cba60af.jpg)

But when I go on one of the INTERVENTIONS detail page, TRAILS section is empty. 
It looks like TRAILS are not displayed in INTERVENTIONS detail page.

**Comment by babastienne** [comment]
Solved in 2.97.4
