### ISSUE TITLE
Clarify LANDEDGE module

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1404]
Les utilisateurs ont du mal à comprendre ce module qui contient 5 sous-modules. 
Il ne comprennent pas bien qu'il y a 5 sous-modules, dans quel sous-module ils arrivent etc...

Une première amélioration serait de mettre la LISTE DÉROULANTE pour basculer entre sous-module AVANT le bouton d'AJOUT.

On comprendrait ainsi mieux que l'AJOUT est lié au sous-module dans lequel on se situe.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2832

**Comment by camillemonchicourt** [comment]
OK dans la 2.73.0 : 
![Capture d’écran de 2021-12-13 19-51-49](https://user-images.githubusercontent.com/4418840/145870888-02ac7f46-4ae6-4c46-9c5a-512548b04259.png)
