### ISSUE TITLE
Change the placeholder picture from the admin

### ISSUE THREAD

**Issue by SmoothyD** [GeotrekCE/Geotrek-admin#1460]
It would be a nice feature to change this from the admin, as it would allow the user to change it easily.

**Comment by camillemonchicourt** [comment]
What is the placeholder picture ?

**Comment by SmoothyD** [comment]
It's used to fill the missing pictures, it can be used on both the mobile and rando version.

**Comment by camillemonchicourt** [comment]
Oh yes OK, the default picture when none was uploaded ! 
OK didnt knew it was called like that. I know now ! :-)
