### ISSUE TITLE
Improve altimetry computation performances

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1493]
When we save a path (or a trek with linear referencing disabled) with a lot of points, altimetry computation (expecially draping on DEM) is slow and can exceed 5 minutes (so the http request timeouts).

Some possibilities:
- rewrite SQL trigger code to make it more efficient
- compute altimetry information by aggregating information of each path instead of computing it from scratch 
- compute altimetry with python (or C) instead of postgresl
- offload computation in background
- increase DEM grid size

**Comment by LePetitTim** [comment]
#1762

**Comment by gutard** [comment]
Dans la situation actuelle, la création ou la modification d'une topologie avec N tronçons déclenche 2×N+1 drapages :
* N drapages au fur et à mesure de l'ajout des tronçons à la topologie temporaire,
* 1 drapage (création) ou 3 drapage (modification) pour la topologie finale suite à divers save() qui modifient l'offset,
* N drapages au fur et à mesure de l'ajout des tronçons à la topologie finale.

La modification d'une topologie entraîne même 2 drapages supplémentaires dus à des save().

Si on suppose que le temps de calcul du drapage d'une topologie est proportionnel au nombre de tronçons qui le compose, on a 2×(N×(N+1)/2)+1 drapages de tronçons. La complexité algorithmique est en O(N²) !!! Si on suppose que le drapage d'une topologie composée d'un seul tronçon prend environ 0,1 seconde, un calcul théorique montre que le drapage d'une topologie composée de 10 tronçons prend de l'ordre de 10 secondes, pour 100 tronçons, de l'ordre d'une demi heure, et pour 1000 tronçons, de l'ordre de 1 jour. Normal que ça explose.

La solution passe par la réécriture de l'enregistrement des topologies afin que les tronçons soient ajoutés en bloc et pas un par un et que le trigger ne se déclenche qu'une fois. La complexité sera alors ramenée à une complexité linéaire. Dans un deuxième temps, l'enregistrement direct sans passer par une topologie temporaire permettrait d'optimiser encore le temps de calcul mais sans changer la complexité.

**Comment by gutard** [comment]
PS : ce problème n'est pas vraiment lié à un bug ou à une erreur de codage mais plutôt à la complexité du système liée au découpage automatique des tronçons, à la segmentation dynamique, et à la nécessité de traiter tout cela avec des triggers plutôt qu'en python.

**Comment by gutard** [comment]
D'après des tests en local, on peut désormais enregistrer un itinéraire de 150 km en 15 sec. A confirmer de manière plus large.

**Comment by camillemonchicourt** [comment]
Super bonne nouvelle. On va voir si on peut aussi faire des tests de volumétrie de notre côté.

**Comment by camillemonchicourt** [comment]
Les premiers tests font plaisir. On passe de 4h d'enregistrement pour une rando à 10 secondes pour la même rando sur la nouvelle version... 🎉

**Comment by camillemonchicourt** [comment]
Intégré dans la version 2.33.0.
