### ISSUE TITLE
Export GPX as track

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1534]
Currently, GPX exports are routes (<rte> tag).
They probably should be tracks (<trk> tag).
https://en.wikipedia.org/wiki/GPS_Exchange_Format
@camillemonchicourt, what do you think about that ?

**Comment by camillemonchicourt** [comment]
From what I know and read in the article, a track is a record of where i went, a route is where to go using a GPS.
So it would mean that GPS exports to upload in a GPS should be routes as they actually are.
I'll talk about it with a colleague GPS specialist to confirm.

**Comment by camillemonchicourt** [comment]
After talking with our GPS specialist, i was wrong.
Route are lines between waypoints, so they are very connected to waypoints while a track is a real line. 
So indeed lines GPS exports should be tracks and not routes.

**Comment by gutard** [comment]
OK, thanks.

**Comment by submarcos** [comment]
fix in mapentity 3.0.1, commit 2fe629d
