### ISSUE TITLE
2.4.0 - Merge paths removes one

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1536]
I want 2 paths (TEST and TEST with orange arrow) that are cut by another path (TEST6, not cut as expalined at https://github.com/makinacorpus/Geotrek/issues/1535).

![merge1](https://cloud.githubusercontent.com/assets/4418840/11326514/d27b80a2-916b-11e5-804a-d857afbbac09.jpg)

OK it dont really makes sense to merge 2 paths that are cut by another one and it shouldnt work.
But when merging them, one of the merged paths is deleted. 

![merge2](https://cloud.githubusercontent.com/assets/4418840/11326532/37d6c54c-916c-11e5-99f8-49fced483ab3.jpg)

And TEST6 is now cut in 2.

**Comment by LePetitTim** [comment]
#1747

Solution :
#1748
