### ISSUE TITLE
Fix map screenshot when API does not return data

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1580]
Trying to capture map screenshot of a non-published trek fails because the API returns 404 for information desks geojson and js code does not handle this gracefully. It should set the `info_desks_loaded` class anyway.

The problem lives in `geotrek/trekking/templates/trekking/trek_detail.html`

**Comment by camillemonchicourt** [comment]
OK so it seems to explain the problem I add with generating PDF for children treks that we don't publish volontary. https://github.com/makinacorpus/Geotrek/issues/1578

**Comment by submarcos** [comment]
fixed since v2.10.1
