### ISSUE TITLE
ERROR - integrityError

### ISSUE THREAD

**Issue by celine971** [GeotrekCE/Geotrek-admin#1594]
J'ai une erreur sous Geotrek (v 2.9.2) :
dans l'admin, j'ai crée un nouveau type de zonage réglementaire.
Qd ensuite je dessine un polygone pour ajouter une nouvelle entité géographique, j'ai un msg d'erreur qui plante à l'enregistrement :  "Erreur interne IntegrityError('duplicate key value violates unique constraint "l_zonage_reglementaire_pkey"\nDETAIL: Key (id)=(9) already exists.\n',)"_
Idem en dessinant avec outil rectangles.
![bugg](https://cloud.githubusercontent.com/assets/7569517/14212401/b0bea70e-f800-11e5-80b4-3c3fa3cedef3.png)

**Comment by camillemonchicourt** [comment]
Le message indique qu'il y a déjà une zone réglementaire qui a le même ID (9). 

La contrainte `CONSTRAINT l_zonage_reglementaire_pkey PRIMARY KEY (id)` est présente dans la table `zonage.l_zonage_reglementaire` qui stocke les zonages. 

Pourtant l'ID de cette table est censé s'incrémenter automatiquement à chaque insertion d'un nouvel objet dans la table grâce à la séquence `zonage.l_zonage_reglementaire_id_seq`.

 Donc quand tu ajoutes un objet dans la table, il ne faut pas renseigner l'ID, c'est peut-être simplement ça ton problème ?

**Comment by celine971** [comment]
merci Camille pour ces éclairages.
J'ai re-testé :
1) sans remplir l'ID -> message au moment d'enregistrer : "Ajout Zonage réglementaire : corriger les erreurs suivantes : ce champs est obligatoire"
2) quand je rempli l'ID apres cette alarme -> message au moment d'enregistrer : "IntegrityError('duplicate key value violates unique constraint "l_zonage_reglementaire_pkey"\nDETAIL: Key (id)=(10) already exists.\n',)"

**Comment by camillemonchicourt** [comment]
Ah OK je comprends ! Tu dessines une ZONE REGLEMENTAIRE depuis l'adminsite de Geotrek ?!?
Je ne pense pas que ça soit fait pour ça ni que cela ait été testé. La liste des zones avait été ajouté dans l'ADMINSITE pour pouvoir supprimer certaines zones tout en supprimant bien en cascade les contenus des tables liées - https://github.com/makinacorpus/Geotrek/issues/1246
Mais une zone réglementaire ça ne se redessine pas je dirai. C'est un zonage qu'on a par ailleurs et que l'on importe. 

Mieux vaut l'importer dans la BDD directement en SQL ou sinon avec QGIS de la même manière que les tronçons (http://makina-corpus.com/blog/metier/2014/importer-une-couche-de-troncons-dans-geotrek).

Ouvre ta table `zonage.l_zonage_reglementaire` dans QGIS et passe la en mode édition, copie ta zone depuis ta table source, colle la dans la table `zonage.l_zonage_reglementaire`, renseigne les champs nécessaire (nom de la zone et id_type de la zone mais pas l'ID vu qu'il sera incrémenté directement par la BDD), sauvegarde ta modification et ça devrait être bon.
