### ISSUE TITLE
Structure related fields should be customisable ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1614]
Actually all the lists in the MANAGEMENT modules (paths, trail, landedges, infrastructures, signages, interventions and projects) are structure_related. It means that each structure in a same Geotrek has his own values for each list.
This is not the case for COMMUNICATION modules (treks, POIs, touristic contents and events...) where all structures have the same values in one Geotrek, in order to be able to publish a common Geotrek-rando portal.
This is interesting when 2 structures dont have the same types of signages or the same type of interventions. 
But it can be a problem if they want to work on the same types for some informations. 
Recently someone wanted to have to same landtypes or the same organisms...

One solution is to add CAN BYPASS STRUCTURE to some users or groups of users but it can also be a problem as it displays all values everywhere. And other users without these rights will not see the same lists...

Another idea is to be able to associate one value to 1 structure or to ALL structures. 

This structure_related fields may are to think again in the near future...

**Comment by LePetitTim** [comment]
#1744 : We can put none related Structure adding the possibility to work on the same element.
#1767 : Create a command to unset elements with structure. Check command's help.

**Comment by camillemonchicourt** [comment]
Yes, these are some great new features.

**Comment by gutard** [comment]
Fixed in v2.21.0
