### ISSUE TITLE
Landedge - Add OWNER field

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1621]
PNR Haut-Jura wants to add OWNER name and contact in LANDEDGE module. 
This is something often asked so we'll add a field `proprietaire` in `foncier.f_b_foncier` table.

**Comment by camillemonchicourt** [comment]
Also add a boolean "convention" ?

**Comment by thomaspnrhj** [comment]
Yes, Makina looks at this

**Comment by camillemonchicourt** [comment]
Done in 2.12.0 : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.12.0
