### ISSUE TITLE
Make load data and default user

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1623]
Unlike mentioned in documentation (https://geotrek.readthedocs.io/en/master/loading-data.html), `make load data` command don't create default user `admin`.

It is only done with loading development-pne datas (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/authent/fixtures/development-pne.json)

**Comment by camillemonchicourt** [comment]
Shouldn't be in PNE-datas but in make load data

**Comment by submarcos** [comment]
admin user is in PNE-datas because it is required by Geotrek tests.
It's not a good idea to make admin user available in initial fixtures, it's better to complete documentation to specify how to create first super user after installation

**Comment by submarcos** [comment]
fixed by  b6960ce

**Comment by submarcos** [comment]
fixed by a3b56e4

**Comment by camillemonchicourt** [comment]
OK yes I understand. Thanks.
