### ISSUE TITLE
Path splitting and events broken

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1625]
Quand un nouveau tronçon est créé qui vient intersecter un tronçon existant, un trigger coupe le tronçon A en 2 parties A1 et A2, l'itinéraire qui utilisait ce tronçon A n'utilise plus que le tronçons A1 (qui a conservé le même identifiant). Du coup il apparaît des "trous" dans l'itinéraire. Mais si on l'édite en conservant les mêmes départ, arrivée et points de passage, il devrait se "corriger" tout seul en empruntant A1 et A2.

Il faudrait faire un dev pour ajouter un trigger qui modifie les événements pour insérer le deuxième sous-tronçons issu du découpage.

**Comment by camillemonchicourt** [comment]
Complément MC : Après lecture du code, le trigger qui doit gérer ce problème existe bien. Et il a l'air de faire son boulot. En tout cas, là, je n'ai pas réussi à trouver de cas où ça bug. 
Le seul truc c'est que les points de passage obligatoire sont décalés et c'est peut-être ça qui pose problème dans certains cas. 

================

Donc plutôt creuser du côté de https://github.com/GeotrekCE/Geotrek-admin/issues/1214
Et approfondir les cas où un découpage de tronçons casse des évènements.

**Comment by LePetitTim** [comment]
Did it happen again ?

**Comment by camillemonchicourt** [comment]
Le problème initialement indiqué ici ne semble pas ou plus se produire.
