### ISSUE TITLE
Automatically reduce uploaded images

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1626]
Would be useful to automatically reduce size of images uploaded as attached files as users often upload huge images which make it long to download them in Geotrek-admin when we just want to watch one. 

Maybe it need a setting to be able to choose the size (1024 px by default I would say). 

Would also be useful with Slideshow display (https://github.com/GeotrekCE/Geotrek-admin/issues/1353).

**Comment by babastienne** [comment]
Linked to #3463 ?

**Comment by camillemonchicourt** [comment]
This issue is a bit different and the subject was to be able to define a maximum size where images will be resized when they are uploaded.

Done in version 2.73.0 with new settings ``PAPERCLIP_RESIZE_ATTACHMENTS_ON_UPLOAD``, ``PAPERCLIP_MAX_ATTACHMENT_WIDTH`` and ``PAPERCLIP_MAX_ATTACHMENT_HEIGHT``

Documentation : https://geotrek.readthedocs.io/en/latest/install/advanced-configuration.html#resizing-uploaded-pictures
