### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by TheoLechemia** [GeotrekCE/Geotrek-admin#1628]
Hello,
I'm trying to install Geotrek following the documentation, and I have some problems.

At the very beginnig, when I run the install.sh, the script can't find the `etc/setting.ini` file. I checked, and I have no `'etc'` folder at all... So the install aborted. 
I tried to create myself this folder and the `settings.ini` file with the variable expected (dbhost, dbname etc...). It works (the database is installed), but the install crash few step later when it try to install the python environnement. `Could not setup python environment !`

Did I miss something in the installation documentation ?
How can I fix this problem ?

Thanks for your help

**Comment by camillemonchicourt** [comment]
Which version are you using ? 
The latest stable version (2.11.3) or the master ? 
There has been some important improvment to the installation script recently (https://github.com/GeotrekCE/Geotrek-admin/pull/1617) but I didnt tested them as they are in master but not in a new stable version. 
Last version I installed on a new server is 2.11.2 and I didnt got any troubles.

**Comment by TheoLechemia** [comment]
I run `curl https://raw.githubusercontent.com/makinacorpus/Geotrek/master/install.sh > install.sh ` .. so yes I use the master.
I try with the 2.11.2, thank you

**Comment by camillemonchicourt** [comment]
Yes, didnt tested the master yet. 
And for installation, this is not the way I do : 

Log in with your linux user (not root)

- cd /home/myusername
- wget https://github.com/GeotrekCE/Geotrek-admin/archive/2.11.2.zip (number to replace with the  latest stable version : https://github.com/GeotrekCE/Geotrekadmin/releases)
- sudo apt-get install unzip
- unzip 2.11.2.zip
- cd Geotrek-admin-2.11.2/
- ./install.sh

Fullfil the settings.ini file (automatically opened during installation process) with your configuration.

**Comment by TheoLechemia** [comment]
It works fine with the 2.11.2, thank you.

**Comment by camillemonchicourt** [comment]
OK so it certainly means that there is an installation problem with actual `master` version, certainly due to evolutions in https://github.com/GeotrekCE/Geotrek-admin/pull/1617

I will also update the installation documentation to clarify to use the latest version rather than the master. 

Thanks.

**Comment by TheoLechemia** [comment]
Actually the install went to the end without showing any error, but I still can't access to the application.
When I go to my serveur URL I got a 502 bad gateway error.
I check the nginx log: 

` *1 connect() to unix:/tmp/gunicorn-geotrek.sock failed (2: No such file or directory) while connecting to upstream`

**Comment by TheoLechemia** [comment]
Ok I found the solution:
In the install.log, there is this problem:
```
sudo supervisorctl reload
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228
```
So i did
`sudo supervisord -c /etc/supervisor/supervisord.conf`
`sudo supervisorctl -c /etc/supervisor/supervisord.conf`
`sudo supervisorctl reload`

It's now working fine.

Note: I'm working on ubuntu 16.04

**Comment by camillemonchicourt** [comment]
OK thanks for the feedback. I've done a PR to clarify the installation doc : https://github.com/GeotrekCE/Geotrek-admin/pull/1629/files

For other points, I guess there are some points to check in the master installation scripts before releasing a new version.

Thanks.

**Comment by camillemonchicourt** [comment]
@gutard does 2.11.4 and 2.11.5 fixed this installation issue ?

**Comment by camillemonchicourt** [comment]
Fixed in 2.14.0 ? 
The PR https://github.com/GeotrekCE/Geotrek-admin/pull/1635 is not useful anymore ?
And 2.14.0 dont support Ubuntu 12 anymore ? If then, it should be mentioned in documentation with this PR https://github.com/GeotrekCE/Geotrek-admin/pull/1638

Thanks.

**Comment by camillemonchicourt** [comment]
Ubuntu versions supported has been updated in installation doc

**Comment by pedrogeo** [comment]
Hello,

I have an issue with the install of Geotrek (2.15.2). When I run ./install.sh (I follow the method described by @camillemonchicourt in her post of the 01242017) the install top with the following code : 

```
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install GDAL 1.10.0. Look above this message for any errors that were output by easy_install.
While:
  Installing gdal-bindings.
Error: Couldn't install: GDAL 1.10.0
Makefile:70 : la recette pour la cible « env_standalone » a échouée
make: *** [env_standalone] Erreur 1
+ success=2
+ '[' 2 -ne 0 ']'
+ exit_error 3 'Could not setup python environment !'
+ code=3
+ shift
+ echo_error 'Could not setup python environment !'
+ set +x
+ echo '(More details in install.log)'
(More details in install.log)
+ exit 3
```

I tried to install many libs of Gdal and Python but it doesn't works.

If anyone have an advice for me ?

Pierre

**Comment by camillemonchicourt** [comment]
On which OS you tried to install it ?
Was it on a new and empty server ?

**Comment by pedrogeo** [comment]
I try to install it on a Lubuntu 16.04 (Osgeo live 11).
The OS is not fully empty but I had only install Powa (dalibo.github.io/powa) And some datas on PostgreSQL.

**Comment by gutard** [comment]
The version of Gdal on Osgeo live 11 is probably different from the version on standard Ubuntu 16.04.
You can try to change Gdal version in conf/buildout.cfg or use a standard Ubuntu distribution.

**Comment by pedrogeo** [comment]
Thanks for your tip.
Ok, the error disapear when I change Gdal version in /conf/buildout.cgf (from 1.10 to 2.2).
So I don't know if this change will affect the operation of Geotrek, I will see.
