### ISSUE TITLE
Ponctual events at intersection of paths

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1644]
@thomaspnrhj mentionne : 

Nous avons soulevé un problème avec nos évènements ponctuels : en effet, lorsqu’un évènement ponctuel se situe exactement à l’intersection de plusieurs tronçons, il semble que par défaut il s’associe uniquement au tronçon supérieur. Ca nous pose pas mal de problème au niveau du G.Admin car nos Comcoms utilisent les sentiers comme référence pour leur gestion et systématiquement les aménagement/signalétiques réellement présent ne remontent pas de façon exhaustive dans les propriétés du sentier…. Il faudrait que ces évènements ponctuels situés aux intersections puissent être liés à l’ensemble des tronçons.

Je voulais savoir si des personnes avait déjà soulevé le problème ? si des solutions existent actuellement pour lier plusieurs tronçons à un évènement ponctuel ? ou si c’est un développement à prévoir ?

@gutard répond : 

Il s'associe effectivement à un seul tronçon, celui qui est le plus proche. C'est lié aux choix de conception initiaux de Geotrek.

Il n'y a pas de solution actuellement. Pour changer cela il faudra effectivement prévoir un développement. Mais avant d'être une question de mise en œuvre, c'est surtout une question de choix. Quel est le comportement souhaité ?

- association au tronçon le plus proche
- association à tous les tronçons situés à moins de x mètre ? x étant constant, ou configurable selon le type de POI, ou configurable au cas par cas ?
- association manuelle ? manuelle mais assistée ?

Autre question : comment visualise-t-on les associations ? Actuellement on peut le voir sur la fiche détail mais pas sur la carte.

@camillemonchicourt répond : 

Bizarre car justement, on a fait en sorte qu'un évènement ponctuel ne soit associé qu'à un seul tronçon SAUF quand il est exactement sur une intersection de plusieurs tronçons, auquel cas il est associé à tous les tronçons. 
Voir https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/CCTP_annexe2-diagramme-fonctionnel-evenements.pdf
Voir aussi les tests : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/core/tests/test_topology.py#L191-L206

Les développements : https://github.com/GeotrekCE/Geotrek-admin/issues/211
Une fonctionnalité pour bien visualiser quand on place un point sur une intersection a même été proposée (mais non réalisée pour le moment) : https://github.com/GeotrekCE/Geotrek-admin/issues/941
Je me souviens que cela fonctionnait bien mais je viens des tests et en effet, il semble y avoir un problème désormais. 
J'ai créé un évènement ponctuel et l'ai ensuite placé exactement sur une intersection (le marqueur passe en jaune quand il est bien snappé à un tronçons) : 
![01](https://cloud.githubusercontent.com/assets/4418840/25475847/73a42594-2b38-11e7-8c70-3638b6e91d01.png)

Mais quand je reviens sur sa fiche détail, il n'est associé qu'à un tronçon : 
![02](https://cloud.githubusercontent.com/assets/4418840/25475851/773ef076-2b38-11e7-9485-8efb2fa9bb11.png)

Et celui-ci n'est pas à 0m mais décalé à 1m sur le tronçon, donc il n'a pas été placé à l'intersection, ce qui explique le fait qu'il n'est pas associé aux 3 tronçons. 
Cela se confirme sur la carte où il n'est pas placé à l'intersection : 
![03](https://cloud.githubusercontent.com/assets/4418840/25475860/7d71c234-2b38-11e7-837f-b180b498f87c.png)

Je ne sais pas pourquoi ce décalage se produit à l'enregistrement, il faudrait voir ce qui a entrainé cette régression. 

@camillemonchicourt répond aussi : 

C'était le fonctionnement initial quand on place un événement ponctuel à une intersection et cela fonctionnait mais là je n'arrive plus à reproduire ce fonctionnement. 
Selon moi, il faut simplement pouvoir snapper un point à une intersection et idéalement le matérialiser visuellement à la saisie (https://github.com/GeotrekCE/Geotrek-admin/issues/941).

@leplatrem répond : 

Je me souviens effectivement que c'était le comportement qu'on avait implémenté à l'origine. C'est pour ça qu'on avait fait le «snapping» aussi :)
Le code qui est censé le faire est là https://github.com/GeotrekCE/Geotrek-admin/blob/2.13.0/geotrek/core/sql/30_evenements_troncons.sql#L83
Et le test qui s'assure que cela fonctionne est plutot celui-ci:
https://github.com/GeotrekCE/Geotrek-admin/blob/2.13.0/geotrek/core/tests/test_topology.py#L334-L346

**Comment by camillemonchicourt** [comment]
Fixed with 2.14.0 ?

**Comment by LePetitTim** [comment]
Yes
