### ISSUE TITLE
Import fichiers et synchronisation G.Rando

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1653]
Depuis l'installation de la nouvelle version 2.14.0, plusieurs bugs : 
-  Internal serveur error lors de l’import de fichiers attachés.
 - Lors de l’export de data et de ma synchronisation avec mon G.Rando, il semble que dans data/api/fr les fichiers  treks.geojson et POI.geojson ne se mettent pas à jour et donc l’ensemble du contenus de mes itinéraires (surement un lien avec le problème précédent…).

**Comment by gutard** [comment]
Le 1er point est corrigé par la release 2.14.2
Le 2nd point n'est pas assez précis pour pouvoir être identifié.
Merci d'ouvrir deux issues séparés lorsqu'il y a deux problèmes différents. En effet il faut pouvoir documenter et clôturer les deux issues indépendamment.

**Comment by camillemonchicourt** [comment]
Merci.
