### ISSUE TITLE
Export .ODT et .DOC

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1656]
Lorsque j'ajoute "MAPENTITY_CONFIG['MAPENTITY_WEASYPRINT'] = True" dans custom.py pour l'export de pdf, je ne peux plus depuis G.Admin exporter en odt ou doc 
![image](https://user-images.githubusercontent.com/19687397/27687430-1801491c-5cd7-11e7-8847-c3959fd133db.png)

**Comment by camillemonchicourt** [comment]
Ce paramètre n'est plus utilisé depuis la 2.10.4 : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2104-2016-05-19

`Deprecate MAPENTITY_WEASYPRINT setting. Now public PDF use Weasyprint HTML templates and private PDF use legacy ODT template.`

Il s'agit d'un reste de l'époque où on travaillait avec des templates ODT pour les PDF publics et où avait encore un système mixte. 

Désormais tout passe par Weasyprint avec des templates HTML. 
En effet ce paramètre désactivait les exports ODT et DOC. 

Supprime ce paramètre de ton `custom.py` et tout reviendra en ordre.

**Comment by thomaspnrhj** [comment]
Sans ce paramétrage, mon export pdf ne fonctionne pas (y compris vers G.Rando) : j'ai systématiquement une internal server error.

**Comment by camillemonchicourt** [comment]
OK y a un autre problème alors à investiguer. 
Mais dans tous les cas ce paramètre n'est plus à utiliser. 

Coté Geotrek-admin, il faudra qu'on le retire et qu'on mette à jour la doc en retirant la partie sur les template ODT : https://geotrek.readthedocs.io/en/master/advanced-configuration.html#override-public-document-openoffice-template

**Comment by thomaspnrhj** [comment]
Je pnses avoir trouvé l'origine de mon erreur :

**Comment by thomaspnrhj** [comment]
Oui j'avais envoyé un peu rapidement !

Je pense avoir trouvé mon problème, lors de ma synchro j'ai l'erreur suivante avec weasyprint qui rencontre un problème avec Cairo/Pango  : 
WARNING: There are known rendering problems with Cairo <= 1.14.0
WARNING 2017-07-07 10:05:35,396 weasyprint There are known rendering problems wi                                                                                                                               th Cairo <= 1.14.0
WARNING: @font-face support needs Pango >= 1.38
WARNING 2017-07-07 10:05:35,397 weasyprint @font-face support needs Pango >= 1.3                                                                                                                               8
WARNING 2017-07-07 10:05:35,396 weasyprint There are known rendering problems wi                                                                                                                               th Cairo <= 1.14.0

**Comment by thomaspnrhj** [comment]
Bug de la 2.14 ?
Il faut remettre à jour Cairo/Pango?
Après investigation, mes images treks.png dans var/media/maps ne peuvent pas s'ouvrir (erreur lors de l'ouverture du fichier). Dans la 2.13, j'avais bien mes maps.

**Comment by camillemonchicourt** [comment]
Si tu es en 2.14.0, il y a eu des corrections depuis, mais je sais pas si ça corrige ton problème. 
Je n'ai pas encore testé la 2.14, donc je ne peux pas confirmer le problème. 
En tout je sais que d'autres y ont migré et ils ont toujours leurs export PDF grand public.

**Comment by thomaspnrhj** [comment]
Après migration en 2.14, mon export PDF fonctionne finalement, mais il ne génère pas la carte + les photos ne s'affichent pas dans le PDF.

**Comment by camillemonchicourt** [comment]
@thomaspnrhj a identifié qu'il y avait un problème dans le chemin des medias : 

`
WARNING: Failed to load image at "http://localhost/mediaupload/logo-header.png" (HTTPError: HTTP Error 404: NOT FOUND)
`

Il manque un `/` dans l'URL des médias entre `media` et `upload`. 

Makina Corpus a identifié que c'était un problème du à la migration vers Django 1.8 (intégré dans la 2.14) qui ne gère plus la fonctionnalité du paramètre pareil. 

Apparemment la méthode `MEDIA_URL|add` oublie un `/` à la fin, et génère des liens `/mediaupload/` qui ne sont donc pas reconnus.

Cette fonctionnalité est utilisée dans les différents templates PDF public : https://github.com/GeotrekCE/Geotrek-admin/search?utf8=%E2%9C%93&q=MEDIA_URL&type=

Cela sera corrigé dans une prochaine version, mais en attendant vous pouvez y remplacer :

`{{ MEDIA_URL|add:'upload/mon_image.png' }}`
par `'/media/upload/mon_image.png'`

Une fois les modifications effectuées, lancez la commande `sudo supervisorctl restart all` pour relancer Geotrek. Puis relancez la synchronisation des PDFs.

Idéalement, il vaudrait mieux le faire dans la surcouche des templates HTML dans `var/media/templates` pour ne pas toucher au cœur de Geotrek-admin. 

Dans tous les cas, si vous y avez déjà surcouché les templates dans `var/media/templates`, il faudra y appliquer la modification. 

Par contre l'application n'utilisera plus le paramètre `MEDIA_URL` qui sera alors en dur dans le code et les templates, ce qui est dommage. A voir si les corrections de la prochaine version permettront de régler le problème tout en continuant à utiliser ce paramètre.

**Comment by camillemonchicourt** [comment]
La correction a été faite ici : https://github.com/GeotrekCE/Geotrek-admin/pull/1660/commits/09c7670bd388ca3ec6b83ba543a96058d1e5efc7

Elle sera disponible dans la prochaine version. 

Dans tous les cas, si vous avez surcouché les templates dans `var/media/templates`, vous devrez y faire de même.
