### ISSUE TITLE
Modification zonages reglementaires

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1667]
Je souhaite modifier/ajouter/supprimer des zonages réglementaires.
Lorsque j'enregistre ma base POSTGIS sous QGIS après modification/ajout/suppression, j'ai une erreur de commit avec le message d'erreur suivant : 
"Impossible de valider les changements pour la couche l_zonage_reglementaire
Erreurs : ERREUR : 1 attribut non-ajouté.
  Erreur du fournisseur de données :
      Erreur PostGIS lors de l'ajout d'entité : ERROR:  relation "l_t_troncon" does not exist
    LINE 1: ...i(ST_Intersection(geom, $1)))).geom AS egeom FROM l_t_tronco...
                                                               ^
    QUERY:  SELECT id, egeom AS geom, ST_Line_Locate_Point(tgeom, ST_StartPoint(egeom)) AS pk_a, ST_Line_Locate_Point(tgeom, ST_EndPoint(egeom)) AS pk_b FROM (SELECT id, geom AS tgeom, (ST_Dump(ST_Multi(ST_Intersection(geom, $1)))).geom AS egeom FROM l_t_troncon WHERE ST_Intersects(geom, $1)) AS sub
    CONTEXT:  PL/pgSQL function lien_auto_couches_sig_troncon_iu() line 25 at FOR over EXECUTE statement"

Par contre aucun soucis pour ajouter/supprimer des zonages réglementaires depuis mon interface Geotrek Admin.  Je suis sur la version 2.15.1. 
D'autres rencontrent ce problème ou est-ce qu'il s'agit d'une erreur dans ma base POSTGIS ?

**Comment by camillemonchicourt** [comment]
Oui il ne trouve pas l_t_troncons car il n'est pas dans le schéma public. 
Question de search_path, expliqué ici : https://github.com/GeotrekCE/Geotrek-admin/issues/1311

**Comment by thomaspnrhj** [comment]
Merci Camille, je vais regarder ça.
