### ISSUE TITLE
Path module - Missing filters

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1668]
Pour un tronçon, il est possible d'ajouter un critère de Confort et un critère d'Enjeu d'entretien.
Il est cependant impossible de requeter dans le filtre sur ces deux critères 
![image](https://user-images.githubusercontent.com/19687397/30686509-c7471d2a-9eb8-11e7-9b4a-4addae5c6b06.png)

**Comment by camillemonchicourt** [comment]
Oui ça fait partie des quelques filtres manquants. Il y en a quelques-uns autres dans certains modules (https://github.com/GeotrekCE/Geotrek-admin/search?q=filter&type=Issues&utf8=✓) et il y a aussi une régression sur l'affichage des filtres depuis la 2.14 ou 2.15 - https://github.com/GeotrekCE/Geotrek-admin/issues/1663

**Comment by LePetitTim** [comment]
By the way, filter display is back to normal (Geotrek 2.18.2)

**Comment by gutard** [comment]
Fixed in master

**Comment by gutard** [comment]
Fixed in v2.21.0
