### ISSUE TITLE
Bug on adding web links on trek

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [GeotrekCE/Geotrek-admin#1672]
Geotrek-admin version 2.15.1
When we add a web link on a trek, after validation the new link isn't displayed on the links list whereas it's well registered.

**Comment by babastienne** [comment]
**Still a bug in 2.95.0.**

When you create a web llink, a popup show off. When validating, the popup does not disappear and the created link does not appears in the list of web links, even if it is added to the trek. When you save the trek you can see that the link has actually been added.

![image](https://user-images.githubusercontent.com/16348048/216005252-b3569395-71e3-441a-a17d-b2183397bec3.png)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.102.2 avec https://github.com/makinacorpus/django-mapentity/pull/283
