### ISSUE TITLE
Deleting a PATH deletes attached POI

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1681]
Actuellement les POIs sont supprimés quand leur tronçon est supprimé. 
C'est assez logique vu qu'ils ne peuvent alors plus être localisés. Cependant plutôt que les supprimer complètement de la BDD (ce qui semble être le cas actuellement), on pourrait imaginer : 
- un mécanisme qui les rattache à un autre tronçon le plus proche ? 
- Ou bien les passer en "supprime = true" pour qu'ils n'apparaissent plus dans l'interface mais soient conservés dans la BDD ? 

Plus globalement, on s'interroge sur le fait de continuer à gérer les POI en segmentation dynamique : https://github.com/GeotrekCE/Geotrek-admin/issues/1680

**Comment by LePetitTim** [comment]
Actuellement, les POI sont gardé dans la BDD avec un supprime = true mais la geom est supprimé (on garde cependant la geom_3d).
