### ISSUE TITLE
BUG Event form disappears D-Day

### ISSUE THREAD

**Issue by Sandrineforge** [GeotrekCE/Geotrek-admin#1682]
The event form disappears the day of the event.
For exemple: the event is th 10 december. D-day, th 10 december this event have disappeared of result list.

We had try to input event start date, we have this bug. We had try to input event start date AND event end date, we have also this bug.

Summer, most events are the afternoon, and people take information or get listed the morning. So, it's a real problem.

**Comment by submarcos** [comment]
No problem in Geotrek-admin. Events are correctly written in synchronization process.
I tried with end_date as today, it's ok.
I tried with end_date as yesterday, event is not written.
