### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by TheoLechemia** [GeotrekCE/Geotrek-admin#1683]
Hello,
I'm trying to install Geotrek 2.16.0 since yesterday. I have the same problem on my server (Ubuntu 16.04) and on my PC (Ubuntu 16.04 also):
During the install, an empty `etc/settings.ini` file is opened, and then I got this error:
`Failed to connect to database with settings provided in 'etc/settings.ini'.
Check your postgres configuration (pg_hba.conf) : it should allow md5 identification for user '' on database ''`

Here is my log file: it looks like the `etc` folder is not created, and the `conf/settings.ini.sample` is not used.

echo_step 'Check postgres connection settings...'
+ set +x
++ ini_value etc/settings.ini dbname
+++ sed -n 's/^\s*dbname *= *\([^ ]*.*\)/\1/p'
./install.sh: ligne 176: etc/settings.ini: Aucun fichier ou dossier de ce type
++ echo
+ dbname=
++ ini_value etc/settings.ini dbhost
+++ sed -n 's/^\s*dbhost *= *\([^ ]*.*\)/\1/p'
./install.sh: ligne 176: etc/settings.ini: Aucun fichier ou dossier de ce type
++ echo
+ dbhost=
++ ini_value etc/settings.ini dbport
+++ sed -n 's/^\s*dbport *= *\([^ ]*.*\)/\1/p'
./install.sh: ligne 176: etc/settings.ini: Aucun fichier ou dossier de ce type
++ echo
+ dbport=
++ ini_value etc/settings.ini dbuser
+++ sed -n 's/^\s*dbuser *= *\([^ ]*.*\)/\1/p'
./install.sh: ligne 176: etc/settings.ini: Aucun fichier ou dossier de ce type
++ echo
+ dbuser=
++ ini_value etc/settings.ini dbpassword
+++ sed -n 's/^\s*dbpassword *= *\([^ ]*.*\)/\1/p'
./install.sh: ligne 176: etc/settings.ini: Aucun fichier ou dossier de ce type
++ echo
+ dbpassword=
+ export PGPASSWORD=
+ PGPASSWORD=
+ psql -h -p -U -c 'SELECT PostGIS_full_version();'
psql: could not translate host name "-p" to address: Nom ou service inconnu
+ result=2
+ export PGPASSWORD=
+ PGPASSWORD=
+ '[' '!' 2 -eq 0 ']'
+ echo_error 'Failed to connect to database with settings provided in '\''etc/settings.ini'\''.'
+ set +x
+ exit_error 4 'Check your postgres configuration (pg_hba.conf) : it should allow md5 identification for user '\'''\'' on database '\'''\'''
+ code=4
+ shift `

I tried to create the `etc/settings.ini` by my own from the sample one. It's resolve the database connexion error, but then i got this error: `Could not setup python environment !`

Someone has any idea ?

Thanks and merry Christmas ;)

**Comment by camillemonchicourt** [comment]
Hum, strange as I installed the 2.16.0 version of Geotrek-admin on an empty Ubuntu 16.04 server 3 days ago and it worked without any problems.

**Comment by TheoLechemia** [comment]
Okay, I was following the readthedoc and download only the `install.sh`.
 I downloaded the full project:
`wget https://github.com/GeotrekCE/Geotrek-admin/archive/2.16.0.zip` and then launch the `install.sh` and it works well.

**Comment by camillemonchicourt** [comment]
I made some changes in Installation doc. 
I wanted to do it as a PR to let maintainers check it before but I made a mistake a commited it to master :-/
https://github.com/GeotrekCE/Geotrek-admin/commit/dcfe4e190b80caef30d0aad84f105afe26b23537

Early 2018 first error ! :x: 

We can revert it if the previous way of installing Geotrek-admin was better.
