### ISSUE TITLE
Merge paths and events update

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1686]
After merging 2 paths (with Geotrek-admin UI) used by a trek, the trek geometry is OK but instead of one event on the merged path, there are now several ones : 

![event-after-fuse](https://user-images.githubusercontent.com/4418840/34720492-333083dc-f53f-11e7-90e7-6804424d5564.jpg)

**Comment by LePetitTim** [comment]
Did you check if it stills happen after : GeotrekCE/Geotrek-admin/pull/1714 ( 2.17.3)

**Comment by camillemonchicourt** [comment]
I guess it fixed the problem, but I would need to check and test again.

**Comment by LePetitTim** [comment]
It's the same problem #1723 and same solution
