### ISSUE TITLE
Accrochage extremité tronçons

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1696]
Dans la 2.17, lorsque l'on crée ou modifie un tronçon, les extrémités ne sont plus jaunes lorsque un accrochage est fait avec un tronçons alors que dans la réalité l'accrochage se fait bien.

![image](https://user-images.githubusercontent.com/19687397/35435207-15cf031a-028a-11e8-943d-313da079fd50.png)

Thomas

**Comment by thomaspnrhj** [comment]
Il semble qu'il y est quand même un problème technique pour l'accrochage après quelques essais

**Comment by gutard** [comment]
Problème introduit en 2.17.0 suite aux mises à jours des modules Leaflet nécessaires pour pouvoir dessiner les bulles (cercles) de sensibilité.

C'est l'accrochage côté navigateur qui ne fonctionne plus (30 pixels à l'écran). Par contre le snapping côté serveur fonctionne toujours (1 mètre).

**Comment by thomaspnrhj** [comment]
Je suis pas sur que ça fonctionne aussi côté serveur car dès que je veux modifier/ajouter un tronçon dans l_t_troncon sous QGIS, j'ai systématiquement l'erreur : 
Impossible de valider les changements pour la couche l_t_troncon

Erreurs : ERREUR : 1 attribut non-ajouté.
  
Erreur du fournisseur de données :
      Erreur PostGIS lors de l'ajout d'entité : ERROR:  relation "l_t_troncon" does not exist
    LINE 1: ..., linestart), geom                           FROM l_t_tronco...
                                                                 ^
    QUERY:  SELECT ST_ClosestPoint(geom, linestart), geom                           FROM l_t_troncon
          WHERE geom && ST_Buffer(NEW.geom, DISTANCE * 2)
            AND id != NEW.id
            AND ST_Distance(geom, linestart) < DISTANCE
          ORDER BY ST_Distance(geom, linestart)
          LIMIT 1
    CONTEXT:  PL/pgSQL function geotrek.troncons_snap_extremities() line 19 at SQL statement

**Comment by thomaspnrhj** [comment]
Ok, c'est résolu avec la 2.17.1

**Comment by camillemonchicourt** [comment]
Ce que tu mentionnes est autre chose : https://github.com/GeotrekCE/Geotrek-admin/issues/1311
