### ISSUE TITLE
Synchro without Sensibility module

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1699]
I installed 2.17.2 and launched a synchronization without the new module Sensibility installed and got some errors during synchronization : 

```
en api/en/treks/23/blue-mountains-peak.pdf failed (relation "s_t_zone_sensible" does not exist
LINE 1: ...."contact", "s_t_zone_sensible"."id_externe" FROM "s_t_zone_...
                                                             ^
)
```

**Comment by gutard** [comment]
Je n'arrive pas à reproduire. Es-tu sûr à 100% que le module sensitivity n'était pas activé ? Cette erreur arrive quand le module est activé mais que le make update (plus précisément le bin/django migrate) n'a pas été fait après l'activation.

**Comment by camillemonchicourt** [comment]
C'est sur un serveur où je suis passé d'un Geotrek-admin 2.11 à un 2.17.2 et je n'ai pas activer le module sensitivity, car si j'ai bien compris (https://geotrek.readthedocs.io/en/master/advanced-configuration.html#sensitive-areas), il ne l'est pas par défaut et c'est une option à ajouter dans custom.py que de l'activer. 
Je ne l'ai encore installé/activé sur aucun Geotrek.

**Comment by gutard** [comment]
OK. Pb d'import inconditionnel de sensitivity/models.py dans l'API v2 + le fait que le rendu des templates plante en cas d'exception au niveau de la bdd.

**Comment by gutard** [comment]
Fixed in version 2.18.2

**Comment by camillemonchicourt** [comment]
Thanks, I updated my Geotrek-admin from 2.17.2 to 2.18.3 and it is fixed now.
