### ISSUE TITLE
Show total length of paths

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1700]
L’onglet « Liste » en haut à gauche indique en gris le « nombre d’objets » visibles à l’écran.
Peut-on indiquer également le « kilométrage cumulé » des objets visibles à l’écran ?

**Comment by camillemonchicourt** [comment]
C'est un peu spécifique et bizarre mais je sais qu'une structure voulait ça donc ça peut. :-)

**Comment by gutard** [comment]
Fixed by #1702
