### ISSUE TITLE
Duplicated path

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#1703]
Actuellement, lorsque il y a trop de snapping et/ou d'intersections, il peut y avoir duplication de tronçon. Cela pose donc problème lors de la création de topologies, l'élément peut faire partie de 2 tronçons, durant également le calcul du nombre de km dans la sélection. Les éléments existent dans la base de donnée.

**Comment by camillemonchicourt** [comment]
S'agit-il du bug qui fait que sur un objet, un même tronçon est parfois dupliqué plusieurs fois comme on le voit ici ? 

![multiples_troncons_dans_itineraire](https://user-images.githubusercontent.com/4418840/37428281-045a9326-27cc-11e8-936d-8a0f24e74b31.PNG)

**Comment by LePetitTim** [comment]
Il y a des chances.

**Comment by DELOUSTAL** [comment]
Peux tu être plus précis dans la description du problème ; S'agit-il d'un itinéraire Geotrek ou le même tronçon, est répété plusieurs fois ? ou s'agit-il d'un autre objet Geotrek ? est-ce que tu as proposé un fix ?

**Comment by LePetitTim** [comment]
Le fix est en cours. Il s'agit d'un probleme au niveau des troncons, lors de leurs creations. Il suffit simplement de faire croiser plusieurs troncons les uns aux autres pour obtenir ce bug.

**Comment by LePetitTim** [comment]
Les éléments existant ne seront pas affecté par le fix, cela ne sert que aux nouveaux éléments lorsque les triggers sql se mettent en route. Il faut supprimer les éléments sois même.
