### ISSUE TITLE
Remove something doesn't remove it from list (top)

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#1709]
Actuellement, lorsque l'on _supprime_ un chemin, un poi ... la liste du haut de page ne fait pas disparaitre l'element. Il est donc possible toujours de cliquer dessus malgré que l'élément n'existe plus, menant a une erreur 404 : page not found.

**Comment by babastienne** [comment]
Résolu, je ne reproduits pas le bug en testant en 2.95.
