### ISSUE TITLE
Bug : Sort by Miniature in Trekking make map disapear in POI list and pois

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#1710]
Actuellement, lorsque l'on decide d'afficher les treks en fonctions de miniature, la liste des POI ne s'affiche plus ainsi que la carte. 
C'est due au fait que trekking a une colomne de plus que POI et essaye de trier en fonction d'une colonne qui n'existe pas dans POI. 
Il faut supprimer/modifier le fonctionnement des tris pour ne pas garder sur toutes la page la colonne n°x mais pour chaque Liste (poi, path, trekking ...) son numero de colonne triée.

**Comment by camillemonchicourt** [comment]
Bien vu, j'avais jamais croisé ce problème !

**Comment by LePetitTim** [comment]
makinacorpus/django-mapentity/pull/150
