### ISSUE TITLE
Can't list objects / Cannot read property 'sSortDataType' of undefined

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1728]
In Chrome and Opera, my POI, Touristic contents and Events, Signages, Trails, Landedges and Projects modules are empty as Geotrek can't get datas. 
It works in Firefox.
It is with Geotrek-admin 2.18.1.

I have this error in console : 

```
8ed29b484c10.js:1480 (http://mygeotrekadmin/static/CACHE/js/8ed29b484c10.js) Uncaught TypeError: Cannot read property 'sSortDataType' of undefined
    at _fnSort (8ed29b484c10.js:1480)
    at init.DataTable.fnSort (8ed29b484c10.js:1861)
    at Object.self.restoreFullContext (8ed29b484c10.js:639)
    at 8ed29b484c10.js:628
    at dispatch (jquery.min.js:3)
    at i (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at jquery.min.js:3
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
```

I tried to clear cache with ``sudo service memcached restart`` but still the same error.

**Comment by camillemonchicourt** [comment]
Ahhhhh OK ! c'est pour ça que ça fonctionnait dans les autres navigateurs. OK OK, vu et confirmé.

Peut-être qu'il est possible de régler ce problème selon la complexité ?

Merci.

**Comment by LePetitTim** [comment]
#1715

**Comment by LePetitTim** [comment]
makinacorpus/django-mapentity/pull/150

**Comment by camillemonchicourt** [comment]
Merci.
