### ISSUE TITLE
Logentry / Internal error

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1730]
When trying to access Logentry page from the Admin menu on Geotrek-admin 2.18.1, I get an internal error : 

```
AttributeError at /logentry/list/
'module' object has no attribute 'content_type_ids'
```

![logentry](https://user-images.githubusercontent.com/4418840/39367004-d6939a32-4a35-11e8-88e1-b4c81d1aeafd.jpg)

On Geotrek-admin 2.18.3, I also get an Internal error but without message displayed and I can't remember how to access Geotrek error logs.

**Comment by gutard** [comment]
https://github.com/makinacorpus/django-mapentity/pull/146

**Comment by camillemonchicourt** [comment]
Thanks.
