### ISSUE TITLE
1.8.x - Structure problem

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1733]
I updated my Geotrek-admin from 2.17.2 to 2.18.3. 
Some partners from another structure are working on it. 
Since I updated it, when partners create new objects, then they cant edit it as objects are attributed to default structure (PNE) and not to their structure.

It was working well on 2.17.2.

**Comment by camillemonchicourt** [comment]
I think we got the same problem earlier and it was fixed in version 2.9.0 - https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.9.0

**Comment by gutard** [comment]
Not exactly the same problem. Fixed in 2.18.5
