### ISSUE TITLE
Affichage carte export pdf grand public

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1734]
Depuis la version 2.18.3, dans l'export pdf grand public, la miniature de la carte et la carte ne s'affichent plus, il y a un rectangle gris à la place. Problème également présent dans la 2.18.4.
![image](https://user-images.githubusercontent.com/19687397/39519231-3700bd18-4e06-11e8-87e3-5b418383821e.png)

**Comment by gutard** [comment]
Ce n'est pas vraiment un problème de la version 2.18.3. Elle fonctionne parfaitement avec les templates par défaut. Par contre, si les templates ont été surchargés dans var/media/templates/ il faut les adapter lors de la mise à jour.

**Comment by camillemonchicourt** [comment]
Oui, voir les modifications récentes du template à répercuter si vous surcouchez le template, comme indique Gael : https://github.com/GeotrekCE/Geotrek-admin/commits/048106f31a9494e4da5f516f9d62d0cac72b0cc3/geotrek/trekking/templates/trekking/trek_public_pdf.html

**Comment by camillemonchicourt** [comment]
OK, j'ai modifié notre surcouche de template en repartant du fichier de base et la miniature de la carte réapparait en effet.
