### ISSUE TITLE
Update SITRA to APIDAE API URL

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1738]
PNR Vercors received this email : 

> Bonjour,
> 
> Nous avons détecté qu’un ou plusieurs de vos projets numériques connectés à Apidae utilisent encore des appels aux API construits sur le nom de domaine sitra-tourisme.com.
> 
> Comme nous l’avons annoncé plusieurs fois depuis plus d’un an sur le blog et sur le Google Group destiné aux développeurs, ce nom de domaine arrivera à expiration le 30 mai 2018 et il ne sera pas renouvelé. Passée cette date, votre projet pourrait ne plus fonctionner correctement.
> 
> Plusieurs solutions sont possibles :
> 
> - Vous ne vous servez plus de ce projet : n’hésitez pas à le supprimer ou à supprimer les technologies utilisées et la fréquence de génération dans sa configuration technique.
> 
> - Vous êtes propriétaire du projet : demandez à votre prestataire technique d’effectuer la migration du domaine sitra-tourisme.com vers apidae-tourisme.com dans ses appels aux API.
> 
> - Vous êtes en charge des développements : vérifiez les configurations de votre projet, production, pré-production, nous avons localisé des appels sur le domaine sitra-tourisme.com dans nos logs. Au passage, jetez aussi un oeil au protocole utilisé et profitez-en pour passer en https si ce n’est pas déjà le cas. Si vous avez un doute, n'hésitez pas à demander plus d'information à la hotline dédiée aux développeurs
> 
> En espérant que cet e-mail vous permette d’éviter le pire (ou de faire un peu de ménage),
> Bien cordialement,
> Serge
> 
> Serge Bregliano
> Coordination développeurs - Réseau Apidae
> 
> Tél : +33 (0)4 73 29 49 95 - Mob : +33 (0)6 63 01 42 49

It would need to test if it just needs to change
http://api.sitra-tourisme.com/api/v002/recherche/list-objets-touristiques/
to 
http://api.apidae-tourisme.com/api/v002/recherche/list-objets-touristiques/
in file `geotrek/tourism/parser.py`.

It looks like it is : http://dev.apidae-tourisme.com/fr/documentation-technique/v2/api-de-diffusion/format-des-recherches

It could also be the occasion to rename SITRA into APIDAE into Tourism parsers : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/tourism/parsers.py

**Comment by camillemonchicourt** [comment]
Done (https://github.com/GeotrekCE/Geotrek-admin/commit/2c98cdc89eac58d97f58f20a35b7fc97a8347b69) and available in 2.19.1.

**Comment by camillemonchicourt** [comment]
Also done in parser name and documentation now : https://github.com/GeotrekCE/Geotrek-admin/commit/56dbedc92840a3ad1653c56de2518e126e084429
Available in next release. 
When updating to this next release, you'll have to update your ``parsers.py`` if you use the ``HebergementsSitraParser`` class to rename it ``HebergementsApidaeParser``.
And eventually ``TouristicContentSitraParser`` to rename ``TouristicContentApidaeParser``.

Reminder to mention it also in Release notes in Changelog.

**Comment by gutard** [comment]
> you'll have to update

You should, but if you don't it will still work.

https://github.com/GeotrekCE/Geotrek-admin/commit/56dbedc92840a3ad1653c56de2518e126e084429#diff-1e434b66b83bb25bd1bbca06d0a6b822R361

**Comment by camillemonchicourt** [comment]
Oh OK, nice !
