### ISSUE TITLE
API V2 - Add models, filters and fields

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1740]
We would need some additional filters for treks, such as Structure, Portal, Source.
And maybe it would deserve to include some more to have most of the fields as parameters.

For paths, we would need Structure, Network and maybe some more.

**Comment by camillemonchicourt** [comment]
Lors de la conception de Geotrek-rando v1, le choix avait été fait de ne pas le connecter directement à la BDD de Geotrek-admin, ni même son API dynamique, pour que les 2 soient indépendants, mais aussi pour des raisons de performance. 
C'est ainsi qu'un mécanisme de synchronisation des données a été mis en place au niveau de Geotrek-admin. Il permet de générer à plat tous les fichiers à plat ensuite utilisés par Geotrek-rando (geojson, json, PDF, KML, GPX...).

Ce fonctionnement a été conservé pour Geotrek-rando v2. Cependant nous initions maintenant une refonte de Geotrek-rando en v3. Les volumes de données ont beaucoup augmenté depuis le début du projet et il devient lourd et peu optimal de télécharger et lire des gros fichiers geojson au niveau de Geotrek-rando.

C'est pourquoi il a été retenu d'interroger dynamiquement l'API de Geotrek-admin, en s'appuyant sur l'API v2 existante (``[URL_GEOTREK-ADMIN]/api/v2/``) et en l'enrichissant).

**Liste des objets nécessaires :**

- Randos
- POIs
- Contenus touristique
- Événements touristique
- Services
- Signalements
- Zones sensibles
- Aménagements et signalétique
- Pages statiques (par portail éventuellement)
- Réservation
- Structures

**Première analyse des éléments à ajouter à l'API v2 actuelle :**

- Ajout de filtres sur les itinéraires :
  - durée min et max
  - distance min et max
  - difficulté min et max
  - D+ min et max
  - commune
  - district (= massif)
  - structure
  - parcours
  - accessibilités
- Ajout de endpoints :
  - liste des communes (all/used)
  - liste des districts (all/used)
  - Événements touristique
  - Services
  - Aménagements
  - Signalétique
  - Pages statiques
- POIs liés à un trek précis. 3 possibilité au choix :
  - Ajout d'un endpoint /api/v2/trek/<id>/poi/
  - Ajout d'un filtre par itinéraire dans le endpoint /api/v2/poi/ existant
  - Imbrication des données des POI dans le endpoint du détail d'un itinéraire
- Ajout de l'attribut photo sur la liste des contenus touristiques
- Ajout d'attributs sur la liste des itinéraires :
  - photo
- Ajout d'attributs sur le détail des itinéraires
  - Accessibilité
  - Informations pratiques
  - Profil altimétrique (format à définir, a priori en PNG)
  - Enfants (liste des étapes en cas d'itinérance)
  - Transports en commun
  - Cœur de parc
  - Recommandations
  - Documents joints
  - Liens vers PDF, GPX, KML
  - Système et id de réservation
- 1er passage pour analyser/améliorer les perfs. Ce travail sera potentiellement à poursuivre en fonction de ce 1er résultat.

**Objets et questions complémentaires :**

- Parkings
- Points de référence
- Lieux de renseignement (avec infos et photos) / Liste + par rando ?
- Liens "En savoir plus"
- Photos avec légende et auteurs (itinéraires, mais aussi POI, CT. ET, aménagements...)
- Génération des PDF, KML, GPX, DEM...
- Plongée (à mettre de côté en attendant son remplacement par module OUTDOOR ?)
- Avoir des filtres par type aussi sur les POI, CT etc...
- CT et ET d'une rando
- Filtrer par source, par portail
- Metas par portail ? SEO
- PDF par source ou portail ?
- Authentification ?
- Ajouter éléments de gestion ? Seulement les publiés ?

**Comment by gutard** [comment]
@camillemonchicourt, dans Geotrek-rando et mobile il y a toujours eu une certaine ambiguïté pour savoir si la liste des communes, difficultés, pratiques, thèmes etc. présentés dans les filtres devaient refléter l'ensemble des données dans Geotrek-admin ou seulement celles utilisée par au moins un itinéraire. A ton avis l'API v2 doit-elle privilégier la 1ère solution (la - chère) ou la 2ème (plus chère), ou bien donner la possibilité de faire les deux (encore plus chère).

**Comment by camillemonchicourt** [comment]
Oui d'autant plus que les typologies utilisées par au moins un itinéraire peuvent aussi dépendre du contexte et des filtres du Geotrek-rando, notamment quand on filtre par portail ou source.
C'est peu souhaitable de proposer des typologies qui n'ont aucun contenu associé, mais si c'est trop complexe, on peut considérer que c'est à Geotrek-rando et Geotrek-mobile de filtrer pour ne proposer que ce qui a du contenu.

Mais c'est peut-etre encore plus complexe de déporter ce filtrage au niveau client...

A discuter.

**Comment by camillemonchicourt** [comment]
Pour le moment on filtre les contenus par portail, mais pas les typologies selon les contenus, ni par portail.

**Comment by gutard** [comment]
Première PR centrée sur les treks à faire avec :
- [ ] Ajout de filtres sur les itinéraires : durée min et max, distance min et max, difficulté min et max, D+ min et max, commune (par id), district (= massif, par id), structure (par id), parcours (par id), accessibilités (par id), portail (par id)
- [ ] Ajout des endpoints pour lister toutes les typologies : communes, districts, structure, parcours, accessibilité, portails
- [ ] Ajout d'un attribut pour la vignette (photo principale) sur la liste des treks
- [ ] Ajout des attributs manquants par rapport à l'API v1 sur le détail des itinéraires : Accessibilité, Informations pratiques, Profil altimétrique (format à définir, a priori en PNG), Enfants (liste des étapes en cas d'itinérance), Transports en commun, Cœur de parc, Recommandations, Documents joints, Liens vers PDF, GPX, KML, Système et id de réservation
- [ ] Vérifier qu'on peut accéder à tous les itinéraires publiés, ainsi que les ressources associées (images, PDF, GPX, KML, profil alti) sans être authentifié
- [ ] Vérifier qu'on ne peut pas accéder aux itinéraires non publiés

**Comment by camillemonchicourt** [comment]
- Concernant les liens vers les fichiers, inclure aussi le lien vers le MNT 3D (dem.json) de chaque rando
- Concernant "en coeur de parc", à replacer par les étiquettes (labels) plus génériques en cours d'implémentation (une ou plusieurs étiquettes pour chaque trek, avec titre, description, picto...)
- Concernant les profils, si on les a aussi en SVG ou JSON, ça vaut certainement le coup de les fournir pas seulement en PNG

**Comment by babastienne** [comment]
Travail en cours sur l'API, visible dans la PR #2371 

Les filtres sur les itinéraires sont ajoutés
Les endpoints suivants ont étés ajoutés : 
- communes
- districts
- structures
- parcours
- accessibilites
- portails
- themes

Certains attributs sur le détail des itinéraires ont étés ajoutés (reste certains à faire) : 
- accessibilité
- informations pratiques (advice)
- Profil altimétrique (svg & json)
- MNT 3D
- Enfants
- Transports en commun
- Label
- Fichiers GPX & KML
- Système de réservation (id & nom)

**Comment by gutard** [comment]
J'anticipe sur la suite. Seconde PR centrée sur les POI :
- [ ] Sortir le endpoint des types de POI pour le mettre à la racine
- [ ] Ajouter un filtre par trek

J'ai de plus en plus de doutes sur l'intérêt de la distinction liste/détail. L'idéal serait de rendre dispo tous les champs pour les deux mais de faire un "only" par défaut sur la liste avec un ensemble restreint de champs.

**Comment by babastienne** [comment]
Oui moi aussi j'ai le sentiment que faire la distinction list/detail est assez lourde dans le code pour un intérêt faible en réalité. On en reparle tout à l'heure sur la manière de faire pour alléger ça.

**Comment by camillemonchicourt** [comment]
OK pourquoi pas si cela simplifie en effet. 

Sinon, Lise a fait une analyse complémentaire et il semble aussi manquer : 
- Les itinéraires liés d'un trek
- La notion de publication par langue
- Pour les médias, il les faut tous, pas seulement les photos (documents, audios, vidéos youtube etc...)

**Comment by babastienne** [comment]
Ok. Pour les itinéraires liés c'est corrigé depuis. Pas encore mis à jour sur la PR. Idem pour les médias.

Pour la notion de publication par langue il faut que je regarde.

**Comment by camillemonchicourt** [comment]
La première PR centrée sur les treks et enrichissant ces derniers en champs et en filtres a été intégrée dans la version 2.39.0.

Les données publiées sont désormais accessibles dans l'API v2 sans authentification, pour faciliter leur diffusion et leur publication dans le futur Geotrek-rando v3 ou vers d'autres outils.

Aperçu de ce premier enrichissement de l'API v2 sur le serveur de DEMO où a été installée la version 2.39.0 : http://geotrekdemo.ecrins-parcnational.fr/api/v2/

**Comment by gutard** [comment]
- [ ] Supprimer les filtres géographiques (dim, format, in_bbox, dist, point) des endpoints accessibility, network, portal, practice, route, theme et difficulty
- [ ] Supprimer le filtre published  de tous les endpoints
- [ ] Supprimer systématiquement les éléments non publiés des endpoints city et district
- [ ] Tenir compte de la langue si elle est précisée pour supprimer les treks non publiés
- [ ] Fixer le crash "parse error: Invalid numeric literal" dans les endpoints city et district au format geojson
- [ ] Ajouter le champ description et les 4 champs facebook au endpoint portal
- [ ] Ajouter les paramètres communs (fields, only, pagination) au endpoint structure
- [ ] Supprimer les sous-endpoint difficulties, networks et practices du endpoint trek
- [ ] Supprimer la sérialisation imbriquée dans les endpoints
- [ ] Filtre portal incohérent avec la v1
- [ ] Corriger la description des champs difficulty, themes, networks, practice, accessibility, theme et portal sur le endpoint trek
- [ ] Double filtre theme et themes sur le endpoint trek (a priori c'est le pluriel qui est le bon)
- [ ] Champ thumbnail à null -> il faut une erreur explicite à la place
- [ ] Ajouter médias, PDF, GPX, DEM 3D... au endpoint trek

Questions :
- sérialisation imbriquée ?
- geojson pour city et district ?
- trier les media (images, vidéo, sons, autres à télécharger ?)
- nom de domaine dans les URL ?
- est-ce qu'on propose la geometry au format json (non geojson) ?
- la distinction liste/détail est-elle pertinente ?
- si non, essaie-t-on de différencier la liste des champs par défaut (sans préciser only ou fields) ?
- publie-t-on les path ? Si oui à quelle(s) condition(s) ?
- répartir les routes par module ?
- endpoint de config générale avec les settings ? Avec toutes les listes comme pour le mobile ?
- peut-on toucher à tour (Alliance réseaux) et sensitive areas ?
- sémantique de l'absence de portal ? Implication du changement sur les déploiements actuels ?
- « Mieux ordonner les filtres » ? Quel est le bon ordre ? Est-ce possible de les ordonner ? Quelle pertinence ?

**Comment by gutard** [comment]
- [ ] Ajouter le filtre route sur le endpoint trek
- [ ] Ajouter le filtre label sur le endpoint trek
- [ ] Ajouter le filtre q sur le endpoint trek (recherche "fulltext", un simple icontains sur name, ambiance, description et description_teaser pour commencer, on verra après pour faire un vrai index fulltext)
- [ ] Utiliser id partout (y compris dans la documentation) en remplacement de pk et de code (pour le endpoint city)
- [ ] Renommer labeltrek par treklabel ? (y compris dans le code)
- [ ] Supprimer l'attribut category du endpoint trek (le front se débrouillera comme il veut avec les données brutes)
- [ ] Supprimer l'attribut duration_pretty du endpoint trek (le front se débrouillera comme il veut avec les données brutes)
- [ ] Supprimer la sérialisation imbriquée de l'attribut treks du endpoint trek (le supprimer complètement au profit d'un filtre trek ?)
- [ ] Revoir la sérialisation de fichiers attachés : renommer le endpoint pictures en attachments, mettre le type mime (ou à défaut une identification image/vidéo/son/autre), pas le content type qui n'a aucun intérêt, supprimer les attributs video et files
- [ ] Supprimer la sérialisation imbriquée de l'attribut source du endpoint trek
- [ ] Supprimer l'attribut relationships ?

Question : comment gérer les élément "A proximité" ? Attributs de trek, ou bien requête sur les autres éléments avec un filtre trek ? Quid des relations explicites ?

**Comment by camillemonchicourt** [comment]
Concernant les éléments à proximité c'est en effet à préciser.
Le besoin principal pour commencer sera de pouvoir lister les Contenus touristiques associés à une rando.
Un peu de la même manière que les POI je dirai. 

Donc comme on a un filtre des POI par trek, pouvoir filtrer les CT par trek je dirai.

Mais peut-être à affiner ?

Concernant la liste des randos liées en dur à une autre rando, je ne sais pas si il faut conserver cette info et ce champs. 
Surtout si on garde la liste des randos autour d'une autre rando par buffer.
A discuter, affiner je pense.

**Comment by gutard** [comment]
OK, donc on ajoutera un filtre `near_trek=` sur les contenus touristiques. Cela peut se généraliser de n'importe quel contenu vers n'importe que autre. Concernant les rando liées, ça fait longtemps que je pense qu'il faut effectivement l'enlever. Pour l'instant on ne met pas dans l'API v2.

Concernant les fichiers attachés, je pense à truc comme :
```json
"attachments": [
    {
        "url": "https://…",
        "author": "…",
        "title": "…",
        "legend": "…",
        "type": "picture" or "video" or "other",
        "backend": as detected by django-embed-video (only when type=video),
        "thumbnail" ? (taille et type de découpage à définir),
    },
    …
],
```

**Comment by gutard** [comment]
Il y a un truc qu'on a un peu oublié, c'est l'affichage des objets sur la carte de la page de résultats. Déjà, il manque un attribut pour récupérer le point de départ plutôt que la géométrie complète. Ensuite, si on pagine la requête, on ne verra que les résultats de la 1ère page de la liste sur la carte. Du coup qu'est-ce qu'on fait pour la carte ? On peut imaginer faire une requête séparée, pour récupérer uniquement les points, et non paginée. Côté perf, même si il en a plusieurs milliers, je pense que ça passe bien et que la clusterisation éventuelle peut se faire côté client.

**Comment by camillemonchicourt** [comment]
OK pour moi pour ces 2 points.

**Comment by thomaspnrhj** [comment]
Pour les POIS, quelle solution a été retenu pour avoir l'info du ou des treks associés ?

"POIs liés à un trek précis. 3 possibilité au choix :
    Ajout d'un endpoint /api/v2/trek//poi/
    Ajout d'un filtre par itinéraire dans le endpoint /api/v2/poi/ existant
    Imbrication des données des POI dans le endpoint du détail d'un itinéraire"

En tout cas, au top cette nouvelle API, bravo à vous !

**Comment by gutard** [comment]
> Pour les POIS, quelle solution a été retenu pour avoir l'info du ou des treks associés ?

Ajout d'un filtre par itinéraire dans le endpoint /api/v2/poi/ existant

**Comment by camillemonchicourt** [comment]
Par contre sur la page de recherche des randos, à partir d'un certain niveau de zoom, on affiche les tracés complets des randos. 
Cela restera possible si on a que les points de départ dans la route générale ?

**Comment by babastienne** [comment]
Si on ne récupère que les points de départ non ça ne sera pas possible en l'état. Pour pouvoir afficher les tracés il faudrait obligatoirement les géométries mais ca augmente pas mal le poids de la requête si on doit les envoyer.
Ou alors on simplifie les géométries avant envoi @gutard ?

Sinon on reste sur l'idée d'un endpoint `/trekroute` qui renvoi de manière non paginée les infos suivantes : id / point de départ / géométrie du tracé.
Ensuite charge au front de choisir s'il ne souhaite obtenir que les points de départ (lorsque le zoom est large) ou tout (comprenant donc les géométries lorsque le zoom est plus fin mais alourdissant la requête s'il y a beaucoup d'éléments).

**Comment by gutard** [comment]
> Par contre sur la page de recherche des randos, à partir d'un certain niveau de zoom, on affiche les tracés complets des randos. Cela restera possible si on a que les points de départ dans la route générale ?

Bien sûr. L'idée est de rappeler l'API à chaque fois que tu en as besoin. Si le niveau de zoom atteint un certain seuil, tu peux demander les géométries complètes mais uniquement dans la bbox qui correspond à la carte. Chaque action de l'utilisateur (zoom, déplacement) va potentiellement déclencher un nouvel appel à l'API. C'est justement ça l'idée de l'API « dynamique » par rapport à l'API « statique ». Le souci, c'est que tu perds en temps réactivité à chaque action utilisateur ce que tu gagnes en temps de chargement au démarrage. Mais l'avantage, c'est que ça passe à l'échelle quand tu augmentes le nombre de randos.

> l'idée d'un endpoint `/trekroute`

Le endpoint s'appelle `trek`. Et ensuite tu choisis les champs et la taille de la page que tu veux avec des paramètres GET. En quoi est-il nécessaire de créer un nouveau endpoint `trekroute` ?

**Comment by camillemonchicourt** [comment]
OK donc pour interroger la route plus précise avec les géométries précises quand on est à un zoom élevé.
Donc on reste comme ça.
Merci.

**Comment by gutard** [comment]
On devrait être bon pour les treks et POI dans la release https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.40.0 qui vient d'être déployée sur https://demo-admin.geotrek.fr

**Comment by camillemonchicourt** [comment]
Ajouter un paramètre pour activer ou non l'API. (true par défaut).
En effet comme elle est désormais ouverte sans authentification, certaines structures peuvent souhaiter ne pas l'activer.

**Comment by thomaspnrhj** [comment]
Ahah c'est génial cette nouvelle API.
Je sais pas si c'est prévu pour la suite mais ce serait bien de pouvoir ajouter le filtre portal pour l'API touristicscontents
Est-il également prévu une API pour les services ?

**Comment by gutard** [comment]
Oui, mais chaque chose en son temps. Déjà on essaye de finaliser trek et poi avant de faire la suite.

**Comment by camillemonchicourt** [comment]
API en version 2.40.1 testable sur http://geotrekdemo.ecrins-parcnational.fr/api/v2/

**Comment by gutard** [comment]
- [ ] Ajouter l'attribut id au endpoint informationdesktop
- [ ] Sérialiser TouristicContent et TouristicEvent de la même manière que les treks

- L'attribut type du endpoint informationdesktop est une sérialisation imbriquée. Mais ici je ne pense pas nécessaire de faire un endpoint spécifique pour les types d'informationdesktop. Soit on laisse tel quel soit on met à plat type (=type.label) et pictogram (=type.pictogram) en enlevant l'id qui ne sera à rien.

**Comment by camillemonchicourt** [comment]
Reste à compléter la partie "Contenus touristiques".
Quelques points identifiés : 
- Ajouter une route pour la liste des catégories de contenu touristique (avec leur ID, label, pictos, ordre, labels de leurs types, ...)
- Ajouter une route pour la liste des types de contenus touristiques (avec leur ID, label, ordre, picto, le type auquel ils se rattachent et la catégorie de contenu touristique à laquelle ils se rattachent, ...)
- Sur la route des contenus tourstiques, ajouter les filtres par catégorie de contenu touristique et par type de contenu touristiques, ainsi que par thème, commune et district)

**Comment by camillemonchicourt** [comment]
Sur la route des treks, il manque : 
- La possibilité de filtrer par pratique
- Les communes dans laquelle passe la rando
- La géométrie du point de départ de chaque rando

A voir aussi : 
- Fonctionnement des filtres par difficulté
