### ISSUE TITLE
Internal Server Error: affichage de la liste des evenements touristiques

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#1752]
La liste des événéments touristiques ne se charge pas et retourne une erreur 500 de l'API.

Le soucis est lié au paramètre completed (Terminé) qui prend la valeur 3 par défaut. Pour le contourner il faut changer la valeur du filtre Terminé et recharger la page.

**Comment by camillemonchicourt** [comment]
Ah OK, j'ai eu le même problème.

**Comment by camillemonchicourt** [comment]
Fixed in 2.20.1 : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.20.1

**Comment by camillemonchicourt** [comment]
Corrigé mais par défaut le filtre affiche "Non" mais n’apparaît pas comme activé.
