### ISSUE TITLE
Geometry modification are not correctly canceled

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-admin#1761]
If I open an entity edition page, I modify geometry object wih leaflet, and click on 'cancel', then save, my geometry modification are saved. Geometry value are not correctly reseted when click on lealfet cancel button

tested on geotrek 2.19.1

**Comment by LePetitTim** [comment]
https://github.com/GeotrekCE/django-leaflet/pull/1

**Comment by gutard** [comment]
Fixed in v2.21.0
