### ISSUE TITLE
Add a draft layer for paths to validate

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1774]
Ajouter une fonction de validation entre les administrateurs sur une même instance Geotrek-admin pour maîtriser la qualité des tronçons et éviter la perte de données. 

Pour cela il est envisagé de pouvoir ajouter une fonction de proposition de tronçons (optionnelle lors de l’installation) à savoir la création d’une nouvelle table « Brouillon » qui permettrait de créer/importer des tronçons par les utilisateurs afin de permettre uniquement à l’administrateur d’afficher ces propositions en fond pour créer/modifier le tronçon dans la BDD de Geotrek.

**Comment by camillemonchicourt** [comment]
Implémenté dans la 2.22.0.
C'est un champs ``Brouillon`` (booleen) qui a été ajouté dans la table ``geotrek.l_t_troncons`` avec la possibilité de le cocher dans l'interface de saisie d'un tronçon. 

Pour qu'un agent ou partenaire puisse proposer des tronçons mais seulement des tronçons Brouillons, il faut lui donner (ou à son groupe) la permission ``Can add draft path`` mais pas ``Can add path``.

Le champs n'est pas disponible quand on modifie un tronçon qui n'est pas en mode Brouillon. Donc une fois basculé de "Brouillon" à "Non brouillon" on ne peut pas le repasser en "Brouillon" (https://github.com/GeotrekCE/Geotrek-admin/commit/9371131a110e2c0bc87598e3ddb7fa8d03a6f09a)

Sur la carte des tronçons, ceux en "brouillon" sont affichés en pointillé (pas en mode EDITION par contre).

Les tronçons "brouillon" ne sont pas visibles dans les autres modules.

Les tronçons "brouillon" ne s'intersectent pas automatiquement entre eux, ni avec les tronçons existants. 

Par contre les éventuelles intersections sont lancées quand un tronçon est basculé de "Brouillon" à "Non brouillon".

**Comment by GuillaumeBoitel** [comment]
>  Donc une fois basculé de "Brouillon" à "Non brouillon" on ne peut pas le repasser en "Brouillon"

Je suppose que c'est pour éviter les soucis de topologie (ne pas avoir deux tronçons successif sans intersection par exemple) ? Mais alors pourquoi ça ne pose pas de problème avec le champ valide (normalement on devrait avoir les mêmes soucis) ?


Au PNPC il a été décidé de garder la trace de tous les sentiers y compris les sentiers qui n'existe plus ou que l'on ne souhaite pas valoriser (les sentiers privées et/ou militaires). Tous ces sentiers ont été mis en brouillon, ainsi qu'en "non valide" pour les sentiers qui n'existe plus. Cependant la valorisation ou non des sentiers peut changer avec le temps. Comment gérer ces changements si il n'est pas possible de changer le statut brouillon dans les deux sens dans l'interface ? Directement dans la base ? Mais est-ce que ça ne va pas produire des effets de bord ?

**Comment by camillemonchicourt** [comment]
En effet passer un tronçon du statut "Brouillon" à "Non brouillon" l'active réellement dans Geotrek-admin, lance les intersections etc... Cela est irréversible à ma connaissance et c'est assez logique. 
Le statut "Brouillon" correspond à un stade avant insertion, il n'y a ensuite plus de raison de repasser un tronçon en "Brouillon".

La champ ``Valide`` n'a aucune conséquence sur l'affichage ou non, les intersections etc... c'est juste un attribut booléen indicatif qu'on avait intégré initialement pour permettre à un référent de passer en revue les tronçons, de les vérifier et les identifier comme OK après vérification.

Un autre champs booléen me semble plus correspondre à ton besoin. Il s'agit du champs ``Visible``, intégré par le PnCevennes il y a quelques temps. Il permet d'avoir des tronçons présents dans la BDD Geotrek, mais de ne pas les afficher dans l'interface Geotrek-admin pour ne pas alourdir l'interface, le chargement des données et la saisie d'objets sur les tronçons. 

Mais sinon, plus globalement, je me demande pourquoi tu ne veux garder que les tronçons sur lesquels vous valorisez des randonnées. 
Notre couche de tronçon est bien plus large que ceux pour lesquels on a des randos.

**Comment by GuillaumeBoitel** [comment]
Oui je vais regarder le champs visible. Il me semblait qu'il était utilisé lorsque l'on supprimait des données dans l'interface (les données restaient dans la base mais n'était plus prise en compte) du coup j'ai peur que l'on ait aussi des tronçons mal numérisés que l'on a voulu effacer (ce qui est différent d'anciens sentiers qui se sont refermés).

L'idée de ne garder que les tronçons que l'on souhaite valoriser c'est pour éviter que les gens qui créent les itinéraires les fassent passer sur des tronçons qui n'existe plus ou sur des zones militaires.

----- Mail original -----
De: "Camille Monchicourt" <notifications@github.com>
À: "GeotrekCE/Geotrek-admin" <Geotrek-admin@noreply.github.com>
Cc: "GuillaumeBoitel" <guillaume.boitel@portcros-parcnational.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Mercredi 5 Juin 2019 22:20:40
Objet: Re: [GeotrekCE/Geotrek-admin] Add a draft layer for paths to validate (#1774)

En effet passer un tronçon du statut "Brouillon" à "Non brouillon" l'active réellement dans Geotrek-admin, lance les intersections etc... Cela est irréversible à ma connaissance et c'est assez logique. 

Le statut "Brouillon" correspond à un stade avant insertion, il n'y a ensuite plus de raison de repasser un tronçon en "Brouillon".



La champ ``Valide`` n'a aucune conséquence sur l'affichage ou non, les intersections etc... c'est juste un attribut booléen indicatif qu'on avait intégré initialement pour permettre à un référent de passer en revue les tronçons, de les vérifier et les identifier comme OK après vérification.



Un autre champs booléen me semble plus correspondre à ton besoin. Il s'agit du champs ``Visible``, intégré par le PnCevennes il y a quelques temps. Il permet d'avoir des tronçons présents dans la BDD Geotrek, mais de ne pas les afficher dans l'interface Geotrek-admin pour ne pas alourdir l'interface, le chargement des données et la saisie d'objets sur les tronçons. 



Mais sinon, plus globalement, je me demande pourquoi tu ne veux garder que les tronçons sur lesquels vous valorisez des randonnées. 

Notre couche de tronçon est bien plus large que ceux pour lesquels on a des randos.

**Comment by camillemonchicourt** [comment]
Le champs quand on supprime des données est le champs booléen ``supprime``. Dans ce cas, cela fait comme une corbeille. Le tronçon n'est plus du tout pris en compte par l'application, mais reste dans la BDD par sécurité. 
Tout ça est à remettre à plat, on pourrait au moins supprimer le champs ``valide``.

**Comment by GuillaumeBoitel** [comment]
Ok, j'avais confondu visible et supprime. Donc en effet les champs valide et visible pour me convenir... à) condition que le champ valide ne soit pas supprimé ;-)



----- Mail original -----
De: "Camille Monchicourt" <notifications@github.com>
À: "GeotrekCE/Geotrek-admin" <Geotrek-admin@noreply.github.com>
Cc: "GuillaumeBoitel" <guillaume.boitel@portcros-parcnational.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Jeudi 6 Juin 2019 11:19:13
Objet: Re: [GeotrekCE/Geotrek-admin] Add a draft layer for paths to validate (#1774)

Le champs quand on supprime des données est le champs booléen ``supprime``. Dans ce cas, cela fait comme une corbeille. Le tronçon n'est plus du tout pris en compte par l'application, mais reste dans la BDD par sécurité. 

Tout ça est à remettre à plat, on pourrait au moins supprimer le champs ``valide``.

**Comment by camillemonchicourt** [comment]
OK
