### ISSUE TITLE
Global layout and scroll

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1781]
I updated to 2.21.0 and it seems to be a CSS problem as there is a vertical and horizontal scroll and a big blank area below the page : 

![gta-scroll](https://user-images.githubusercontent.com/4418840/45157499-a93e7200-b1e1-11e8-9b76-c209671193a9.jpg)

**Comment by camillemonchicourt** [comment]
Since a few versions, the vertical scroll is even bigger : 

![image](https://user-images.githubusercontent.com/4418840/58179482-91901680-7ca8-11e9-8b32-b0269afce459.png)

It only happens when there are a lot of objects in the list. As I dont have the problem in our demo version which has just a few objects / http://geotrekdemo.ecrins-parcnational.fr (demo / demo)

**Comment by babastienne** [comment]
I can't reproduce this problem anymore.
