### ISSUE TITLE
Be able to manage signage orders

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1782]
Actually the signage module is simple, just to inventory signages with general informations. 
For details about a signage, managers can add attached files (photo, PDF, ODS...). 

But it has often been discussed to be able to include more fields in the signage database such as : 
- blade code
- direction of the arrow
- length information
- pictograms
- pole material
- diameter
- type of attachment
- orientation cone status

And certainly a table with orders.

It would require to separate signages and infrastructures as they are actually in the same table. See https://github.com/GeotrekCE/Geotrek-admin/issues/763

**Comment by camillemonchicourt** [comment]
A articuler avec la réflexion sur le fait de séparer Signalétique et Aménagements dans 2 tables séparées : https://github.com/GeotrekCE/Geotrek-admin/issues/261

**Comment by camillemonchicourt** [comment]
Complément avec les évolutions souhaitées par le Département du Gard pour avoir plus de détail sur la signalétique, les poteaux, leurs lames et les lignes de chaque lame et pouvoir faire des commandes de lames à partir d'exports de Geotrek-admin.

Pour cela, il est nécessaire de séparer la signalétique dans une table dédiée. 

**Table a_b_amenagement (existante) ou plutôt créer une table a_b_signalétique**
_Liste des types de signalétiques (par ex. les types de poteaux)_
* Label (alphanumérique)

**Table m_b_organisme (existante)**
_Lister des organismes gestionnaires_

* Nom (alphanumérique)

**Table a_b_scellement (à créer)**
_Liste des types de scellements_

* Label (alphanumérique)

**Table a_b_etat (existante)**
_Liste des états_

* Label (alphanumérique)

**Table a_t_signaletique (à créer à partir de la table a_t_amenagement existante)**
_Liste des poteaux_

* Géométrie (point) calculée à partir de la segmentation dynamique
* Code (numéro de série dans la commune, alphanumérique)
* Nom (alphanumérique) à ajouter pour la bague de lieu-dit
* Type (liste déroulante depuis la table a_b_signaletique)
* Description (= commentaires, alphanumérique sur plusieurs lignes)
* Gestionnaire (liste déroulante depuis la table m_b_organisme)
* Scellement (liste déroulante depuis la table a_b_scellement)
* État (liste déroulante depuis la table a_b_etat)
* Altitude retenue (ou saisie) manuelle pour le 

A voir si on profite pour y ajouter dimension, quantité, diamètre et matériel du poteau, demandé par ailleurs ? Et autres ?

Les champs suivants seront automatiquement calculés : 

* Commune et code INSEE
* Altitude
* Code poteau complet (code commune + code poteau)

**Table fl_t_fichier (existante)**
_Liste des fichiers attachés, en particulier les photos_

* Signalétique (lien automatique)
* Fichier (upload)
* Type de fichier (liste déroulante)
* Légende (alphanumérique)
* Auteur (alphanumérique)
* Date de création (date) → champ à créer
* Etoile (pour photo principale)

**Table a_t_lame (à créer)**
_Liste des lames_

* Signalétique (lien automatique)
* Numéro de lame (alphanumérique)
* Direction (liste déroulante basée sur a_b_direction_lame)
* Type (liste déroulante basée sur a_b_type_lame)
* Couleur (liste déroulante basée sur a_b_couleur_lame)
* État (liste déroulante depuis la table a_b_etat, à confirmer qu'on peut utiliser la même liste)

**Table a_t_ligne (à créer)**
_Liste des lignes d'une lame_

* Code lame (lien automatique)
* Numéro ligne (entier)
* Texte (alphanumérique)
* Distance (alphanumérique)
* Temps (alphanumérique)
* Picto (alphanumérique)

**Table m_t_intervention (pas de modification mais rattachable a la nouvelle table de signalétique)**
_Liste les visites/interventions/remplacements de lames_

* Signalétique (lien automatique)
* Date (date)
* Type d’intervention (liste déroulante)
* Description (observation)
* ...

Geotrek-admin dispose déjà d'exports par objet (ODT, DOC, PDF) ou par listes d'objets après éventuels filtres (CSV, SHP, GPX). 
Ainsi il sera possible d'exporter des fiches SIGNALETIQUE ou des listes de SIGNALETIQUES. 
Les listes exportés ne contiendront pas le détail des lames et de leurs lignes. 
Il est souhaité pouvoir faire un export Tableur de toutes les lames d'un état particulier pour pouvoir en faire la commande. 
A préciser et trouver un emplacement.

**Comment by camillemonchicourt** [comment]
Exemple d'export des lames souhaité pour pouvoir déclencher des commandes de remplacement : 

Code Lame | Ligne | Couleur | TEXTE | altitude | Picto / Temps | Sens | Longueur
-- | -- | -- | -- | -- | -- | -- | --
30004/02/C | LD3-1 | Jaune | AUBAIS |   |   | D | 4.7
30004/02/C | LD3-2 | Jaune | MOULIN DE CARRIÈRE |   |   | D | 4.2
30004/02/C | LD3-3 | Jaune | Garrigouille |   |   | D | 1.7
30004/06/C | LD2-1 | Jaune | AIGUES-VIVES |   |   | G | 0.8
30004/06/C | LD2-2 | Jaune | Le Temple |   |   | G | 0.7
30019/03/A | LD2-1 | Jaune | AIGUES-VIVES |   |   | G | 2.4
30019/03/A | LD2-2 | Jaune | Cros de Nadal |   |   | G | 1.7
30019/27/C | LD2-1 | Jaune | AUBAIS |   |   | D | 1.8
30019/27/C | LD2-2 | Jaune | MOULIN À VENT |   |   | D | 0.5
30083/03/A | LD1-1 | Jaune | CODOGNAN |   |   | D | 0.6
30083/03/B | LD2-1 | Jaune | VERGÈZE - Pic du Rhôny |   |   | G | 3.8
30083/03/B | LD2-2 | Jaune | MUS |   |   | G | 3.0
30083/03/C | LD2-1 | Jaune | VERGÈZE ESPACE |   |   | G | 2.7
30083/03/C | LD2-2 | Jaune | Le Grand Noyer |   |   | G | 0.7
30083/03/BL | BL | Vert | Parcours sportif | 20 |   | BL |  
30123/09/B | LD2-1 | Jaune | LE PONT ROMAIN |   | GR653 | D | 1.9
30123/09/B | LD2-2 | Jaune | Moulin de Vendran |   |   | D | 0.9
30123/17/A3 | LD3-1 | Jaune | GALLARGUES-LE-MONTUEUX |   | GR653 | G | 3.2

**Comment by camillemonchicourt** [comment]
Retour du CD04 : 

> Pour le développement concernant la signalétique, il me semble que le travail est complet (pas de besoin concernant "dimension, quantité, diamètre et matériel du poteau...", peut se mettre éventuellement dans commentaires).
> 
> Juste pour préciser que plusieurs territoires (dont les départements des Alpes de Haute-Provence et des Hautes-Alpes) mettent également les coordonnées GPS sur les bagues de lieu-dit (en UTM WGS84).
> A voir si à côté du champ "Altitude" il est possible de rajouter un champ "coordonnées GPS" (automatisé ou saisie manuelle).

Ajouter les X et Y dans l'export CSV ?

**Comment by camillemonchicourt** [comment]
Retour du département de l'Ardèche : 

> Pour notre part, le travail est très complet, nous avons juste un manque avec la nouvelle charte départementale de la signalétique ardéchoise, qui affecte des pictogrammes sur une lame, et non sur une ligne. Nous en avons ainsi 4 possibles par lames, permettant de faire le tour des différentes activités qui prennent la même direction.
> 
> Dans l'exemple du Gard, un seul picto est possible, et est associé à la ligne (carrefour intermédiaire ou direction lointaine). Si quelques lignes peuvent être ajoutées pour les picto dans la table lame, ce serait génial pour notre part
> 
> Enfin, même si c'est plus du détail, un export sur excel serait bien en + du CSV, tout le monde n'ayant pas la possibilité de lire ce format, notamment pour les envois de corrections aux différents partenaires.

CSV est un format Tableur ouvert qui peut être ouvert avec Excel ou Calc (LibreOffice).

**Comment by jgf66** [comment]
Je rejoins les commentaires du CD04 et du collègue de l'Ardèche. 
Travail très complet et développements qui améliorent considérablement l'outil de gestion. Voir s'il serait possible d'ajouter un champs coordonnées GPS (de préférence automatisé, en UTM WGS84) et si quelques lignes pourraient être ajoutés pour les pictos dans la table lame.

**Comment by LePetitTim** [comment]
Bonjour,
Que voulez vous dire par :

> quelques lignes pourraient être ajoutés pour les pictos dans la table lame.

Concernant le fichier csv, il n'y a rien par rapport a la valeur de ces lignes sont elles stockées quelque part ? Ou faut il remplacer chaque ligne par la valeur de la ligne (texte).

**Comment by camillemonchicourt** [comment]
De ce que je comprends, certains associent les pictos aux niveaux des lames (en en mettant potentiellement plusieurs par lame), alors que le GARD ne les affecte qu'aux lignes des lames en en ayant qu'un seul par ligne de lame. 
Du coup je vois pas bien comment on pourrait répondre proprement aux 2 besoins.

**Comment by jgf66** [comment]
Bonjour, 
C'est effectivement ça. Voir exemples en pièce jointe : 

1.Tableur pictos attachés à la lame 
2. BAT pictos attachés à la ligne 
3. BAT pictos attachés à la lame 

Ça paraît effectivement compliqué d'adapter le format de tableau CSV aux 2 modèles. 

Josselin Garau-Figuères 
Responsable de la mission "Randonnée et Activités de Pleine Nature" 
Département des Pyrénées-Orientales 
24 quai Sadi Carnot B.P. 906 
66906 PERPIGNAN CEDEX 
Tél. : 04 68 85 82 15 
" Le Département des Pyrénées-Orientales innove et met à votre disposition un système dématérialisé de dépôt de demande de subvention des associations. La demande doit donc être réalisée en ligne depuis le site du Départemen t Pass66 dès lors qu'elle est supérie ure ou égale à 500 €. 


De: "Camille Monchicourt" <notifications@github.com> 
À: "GeotrekCE/Geotrek-admin" <Geotrek-admin@noreply.github.com> 
Cc: "jgf66" <josselin.garau-figueres@cd66.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Lundi 21 Janvier 2019 15:36:45 
Objet: Re: [GeotrekCE/Geotrek-admin] Be able to manage signage orders (#1782) 



De ce que je comprends, certains associent les pictos aux niveaux des lames (en en mettant potentiellement plusieurs par lame), alors que le GARD ne les affecte qu'aux lignes des lames en en ayant qu'un seul par ligne de lame. 
Du coup je vois pas bien comment on pourrait répondre proprement aux 2 besoins.

**Comment by camillemonchicourt** [comment]
Done in 2.23.0.

Video DEMO : http://geotrek.ecrins-parcnational.fr/articles/images/2019-02-signage-module.gif

**Comment by camillemonchicourt** [comment]
Pour la charte signalétique des parcs nationaux, il semblerait que la différence est que les pictos sont associées aux lignes et non pas aux lames. 
Donc en l'état, il faudrait des compléments pour pouvoir être utilisé par les parcs nationaux. 
A creuser.

**Comment by GuillaumeBoitel** [comment]
> Pour la charte signalétique des parcs nationaux, il semblerait que la différence est que les pictos sont associées aux lignes et non pas aux lames.
> Donc en l'état, il faudrait des compléments pour pouvoir être utilisé par les parcs nationaux.
> A creuser.

Je suis en train de regarder comment importer les données signalétiques du parc national de Port-Cros. En effet, les pictogrammes sont bien associés aux lignes et il peut avoir parfois plusieurs pictogrammes par lignes.

Ce serait bien d'avoir un table pictogrammes pour éviter les erreurs de saisies plutôt 
**Table a_b_pictogramme (à créer)**
_Liste des types de scellements_

- Code  (alphanumérique)
- Label (alphanumérique)
- Fichier (upload)

Puis dans la ligne pouvoir les insérer comme cela est fait dans le module intervention avec le champs "désordres".

Il faudrait aussi pouvoir rendre optionnel le champ texte de la ligne car parfois on a juste un pictogramme sur la ligne et pas de texte (ou mieux rendre obligatoire au moins un texte ou un pictogramme).

**Comment by GuillaumeBoitel** [comment]
> **Table m_t_intervention (pas de modification mais rattachable a la nouvelle table de signalétique)**
> _Liste les visites/interventions/remplacements de lames_
> 
> * Signalétique (lien automatique)
> * Date (date)
> * Type d’intervention (liste déroulante)
> * Description (observation)
> * ...

Cela a-t-il été implémenté dans la version 2.24.7 car je n'arrive pas à trouver de lien vers la signalétique dans le formulaire d'édition d'intervention ?

**Comment by camillemonchicourt** [comment]
Concernant le fait de pouvoir associer les pictos aux lames ou aux lignes, il faut trouver comment gérer ça proprement pour ne pas proposer les 2 en même temps à la saisie et l'export, mais l'un ou l'autre. Voir https://github.com/GeotrekCE/Geotrek-admin/issues/1903

Pour le fait de gérer les pictos sous forme de liste plutôt que de texte, ça me parait plus cohérent, mais à voir pourquoi un champs texte a été favorisé par le CD30. 
A discuter aussi pour le fait d'avoir une relation N-N avec une table de correspondance pour pouvoir associer plusieurs pictos par ligne.

> Cela a-t-il été implémenté dans la version 2.24.7 car je n'arrive pas à trouver de lien vers la signalétique dans le formulaire d'édition d'intervention ?

Concernant le fait d'associer une intervention à une signalétique (ou un aménagement) ça existe depuis le début de Geotrek-admin, mais pour faire cela il ne faut pas passer par le module Interventions, mais passer par la fiche de la signalétique ou de l’aménagement sur laquelle on veut ajouter une intervention. 
Sur la fiche quand on survole la partie Travaux / Interventions, un bouton "Ajouter une intervention" apparaît. En cliquant dessus cela ouvre le formulaire d'Intervention qui sera associé à l'objet depuis lequel on arrive.
Oui je sais, c'est pas très visible mais c'est indiqué ici : https://geotrek.readthedocs.io/en/master/user-manual.html#gestion-des-sentiers

**Comment by GuillaumeBoitel** [comment]
> Concernant le fait d'associer une intervention à une signalétique (ou un aménagement) ça existe depuis le début de Geotrek-admin, mais pour faire cela il ne faut pas passer par le module Interventions, mais passer par la fiche de la signalétique ou de l’aménagement sur laquelle on veut ajouter une intervention.
> Sur la fiche quand on survole la partie Travaux / Interventions, un bouton "Ajouter une intervention" apparaît. En cliquant dessus cela ouvre le formulaire d'Intervention qui sera associé à l'objet depuis lequel on arrive.
> Oui je sais, c'est pas très visible mais c'est indiqué ici : https://geotrek.readthedocs.io/en/master/user-manual.html#gestion-des-sentiers

Effectivement j'étais passé un peu trop vite sur ce passage de la doc. Ca marche nickel pour les signalétiques, mais pas pour les lames (cf  #1905).

**Comment by camillemonchicourt** [comment]
A noter que 3 paramètres permettent de définir le format des codes des lames et des lignes : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L649-L651

**Comment by camillemonchicourt** [comment]
Dans la version 2.89.0 de Geotrek-admin, il est possible de paramétrer si on souhaite avoir le champs DIRECTION sur les LAMES ou sur les LIGNES - https://github.com/GeotrekCE/Geotrek-admin/issues/3178
