### ISSUE TITLE
Export interventions - Détailler les coûts par fonction

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1798]
Actuellement dans les exports Listes des Interventions, on n'a que le nombre total et le coût total des journées/homme. Elles sont saisies par Fonctions. 

Il serait nécessaire de disposer aussi du détail par intervention par fonction dans les exports : 
- Coût par fonction par intervention + Nb jours par fonction
- Ces infos sont dans une table n-n donc il faudrait boucler pour générer dynamiquement les colonnes.
- Dans l'export, on peut avoir des fonctions qui n'ont pas d'interventions associées, il faudrait lister que celles qui ont des données pour l'export en question

**Comment by gutard** [comment]
> il faudrait boucler pour générer dynamiquement les colonnes

C'est pas trop prévu pour mais on doit pouvoir s'en sortir en modifiant l'attribut `columns` dans le `__init__()` et en définissant la méthode `__getattr__()` sur le modèle.

**Comment by Chatewgne** [comment]
Exporter les colonnes vides ? Ou les choisir dynamiquement ?

**Comment by Chatewgne** [comment]
Quel nom pour chaque colonne de coûts par fonctions ? (en anglais et en français)

Idées :

"Mandays cost of Plumber"
"Cost of job: Plumber"
"Total cost of job: Plumber"

"Coûts Pombier"
"Coût total Plombier"

**Comment by camillemonchicourt** [comment]
OK bien vu.
Je dirai le plus simple et le plus court : 
FR : "Coût Nomfonction"
EN : "Cost Funtionname"

**Comment by Chatewgne** [comment]
Création d'un setting pour activer ou non l'export des coûts pour chaque fonction :
```
ENABLE_JOBS_COSTS_DETAILED_EXPORT = True
```
Par défaut : le settings est à `False` pour assurer la rétrocompatibilité

Ces colonnes étant construites de manière dynamique, dépendante du contenu de la base de Fonctions, on ne peut pas les configurer pas "une par une" comme on avait fait pour les autres colonnes (fonctionnalité 1 de ce projet). On se contente d'activer ou de désactiver leur construction automatique.

**Comment by camillemonchicourt** [comment]
Merci, est-ce que les colonnes dynamiques dépendent des fonctions présentes dans les données exportées, ou alors cela prend automatiquement toutes les fonctions présentes dans la BDD ?

**Comment by Chatewgne** [comment]
On exporte uniquement les fonctions présentes dans les interventions.
Il y [a un test ](https://github.com/GeotrekCE/Geotrek-admin/pull/2715/commits/dfb68ba464526ce04bc580ef83d2525c4fbfd2ff#diff-7d42fd8090baba7563c4633e746e6c467c92a5d31d55085d3fd58957fb2ba408R642) pour vérifier cela.
Par contre actuellement, à cause de la manière dont les exports sont implémentés, j'ai un problème pour enlever les colonnes des fonctions qui étaient utilisées avant mais on été supprimées. De manière générale la suppressions des Journées-Hommes est un peu bancale et ça pose soucis ([en lien avec ce bug](https://github.com/GeotrekCE/Geotrek-admin/issues/2693)) . Je vois ça avec @submarcos la semaine prochaine.

**Comment by Chatewgne** [comment]
PR pour cette fonctionnalité https://github.com/GeotrekCE/Geotrek-admin/pull/2715

**Comment by camillemonchicourt** [comment]
Ok très bien, merci pour les précisions et les colonnes dynamiques

**Comment by Chatewgne** [comment]
- Nous avons trouvé une solution pour mon problème de colonnes, maintenant, pour les fonctions qui sont supprimées de la base de données (par exemple, depuis l'admin), on supprime en cascade les Journées-Hommes et on n'exporte plus de colonnes de coûts (comportement Django classique).

- En pratique, à cause du à cause du bug mentionné : https://github.com/GeotrekCE/Geotrek-admin/issues/2693 les utilisateurs ne peuvent pas (a priori, n'ont jamais pu)  supprimer ou modifier de Journées-Hommes **_depuis la page d'édition des interventions_**.
Malheureusement la résolution du bug ne rentre pas dans le cadre de ces travaux.

En conclusion la fonctionalité marche, mais lorsque l'on s'attelera à la résolution du bug il sera temps de s'assurer que les Journées-Hommes soit correctement supprimées et éditées (et symétriquement pour les lames de signalétique).

**Comment by Chatewgne** [comment]
Faut-il le faire aussi pour les export Shapefile ou seulement les CSV ? (ne pas rajouter ce calcul favorise les performances)

**Comment by camillemonchicourt** [comment]
OK pour la suppression des fonctions.
Par contre si on veut supprimer une fonction depuis l'AdminSite, on a un message qui indique des objets liés qui seront supprimés ?

A mon avis c'est bien d'avoir une cohérence entre les exports, et d'avoir la même logique et les mêmes colonnes.
Donc je trouve ça bien de l'activer si le paramètre est passé à ``true``.
Mais si vraiment ça pète les performances et que les exports SHP n'aboutissent plus dans la majorité des cas, alors il faut peut-être le faire qu'en CSV ?

**Comment by Chatewgne** [comment]
Ok pour les SHP, la durée d'export est raisonnable.
Oui pour l'adminsite on a ce genre d'information quand on veut supprimer une fonction :

![image](https://user-images.githubusercontent.com/26015573/125749236-518bfb62-6ea1-4275-bba6-2de358fcf00f.png)

**Comment by camillemonchicourt** [comment]
OK très bien

**Comment by camillemonchicourt** [comment]
OK testé sur la 2.73.0.
Les coûts par fonction sont bien présents dans l'export CSV.
Par contre quand je passe le paramètre ``ENABLE_JOBS_COSTS_DETAILED_EXPORT`` à ``True`` j'ai une INTERNAL SERVER ERROR, et l'URL indiquée est https://geotrekdemo.ecrins-parcnational.fr/intervention/list/export/?subcontracting=1&on=&bbox=POLYGON((5.678558349609375+44.49552576372451%2C5.678558349609375+45.29034662473613%2C6.947479248046875+45.29034662473613%2C6.947479248046875+44.49552576372451%2C5.678558349609375+44.49552576372451))&format=shp

Alors que les exports SHP des interventions fonctionnent quand ``ENABLE_JOBS_COSTS_DETAILED_EXPORT`` est à ``False``.

Les seuls logs que j'ai trouvé avec la commande ``sudo journalctl -eu geotrek-ui`` sont : 

```
Dec 13 20:50:23 geotrek-test gunicorn[21968]: /opt/geotrek-admin/lib/python3.6/site-packages/compressor/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely 
Dec 13 20:50:23 geotrek-test gunicorn[21968]:   post_compress = django.dispatch.Signal(providing_args=['type', 'mode', 'context'])
Dec 13 20:50:23 geotrek-test gunicorn[21968]: /opt/geotrek-admin/lib/python3.6/site-packages/compressor/parser/default_htmlparser.py:77: RemovedInDjango40Warning: smart_text() is deprecated in favor of s
Dec 13 20:50:23 geotrek-test gunicorn[21968]:   return smart_text(elem['text'])
Dec 13 20:50:23 geotrek-test gunicorn[21968]: /opt/geotrek-admin/lib/python3.6/site-packages/compressor/cache.py:29: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
Dec 13 20:50:23 geotrek-test gunicorn[21968]:   return 'django_compressor.%s' % force_text(key)
Dec 13 20:50:23 geotrek-test gunicorn[21968]: ERROR 2021-12-13 21:50:23,165 fiona._env /tmp/f5c62d83-a9d8-49a4-a858-470bdf433d6d: Is a directory
```

**Comment by LePetitTim** [comment]
C'est une erreur qui a rien a voir avec cette modification.
Je ne sais pas quand est ce que cette erreur apparait :
``/tmp/f5c62d83-a9d8-49a4-a858-470bdf433d6d: Is a directory``

**Comment by camillemonchicourt** [comment]
OK l'erreur remontée n'a donc rien à voir avec le soucis.
J'ai cette erreur qui remonte régulièrement dans les logs, mais c'est donc autre chose.

Par contre concernant le problème d'export en SHP quand j'active le détail des coûts par fonction, tu le reproduis ?

**Comment by LePetitTim** [comment]
Non justement je le reproduis pas et le problème doit venir de cette erreur

**Comment by submarcos** [comment]
@LePetitTim l'erreur "is a directory" est une erreur non bloquante provoquée par fiona ou la classe qui créé le zip, car on itere sur les fichiers et dossiers pour ajouter dans le zip, alors qu'on en devrait qu'ajouter les fichiers

**Comment by LePetitTim** [comment]
J'ai pas l'erreur de mon côté. Il me faudrait la liste des interventions avec tous les champs.

**Comment by camillemonchicourt** [comment]
Le soucis est présent sur notre serveur de DEMO : https://geotrekdemo.ecrins-parcnational.fr/intervention/list/ (admin / admin)
Avec le paramètre : 
```
# Enable cost export by function
ENABLE_JOBS_COSTS_DETAILED_EXPORT = True
```

**Comment by camillemonchicourt** [comment]
J'ai aussi le bug sur mon serveur en production.

**Comment by LePetitTim** [comment]
geotrek ./manage.py dumpdata maintenance > test.json

**Comment by camillemonchicourt** [comment]
OK les esports SHP des interventions fonctionnent avec ``ENABLE_JOBS_COSTS_DETAILED_EXPORT`` à ``true`` sur la 2.75.0.
