### ISSUE TITLE
Configuration Geotrek Admin

### ISSUE THREAD

**Issue by MROALI** [GeotrekCE/Geotrek-admin#1858]
Bonjour, 
Nous avons installé geotrek-admin et geotrek rando. Et nous avons un peu de mal pour configurer geotrek Admin et en particulier pour l'importation des données. 
1- Comment peut on importer la listes des communes ?
2- Notre SIG est basée sur ARCGIS (GEOMAP) : Comment peut on importer les infos dans Geotrek (itiniraires randonnée etc..) ?  Autrement dit, c'est quoi la procédure à suivre pour importer les fichiers shapes de randonnée dans Geotrek?

Avez-vous un document précis qui décrit la procédure à suivre pour la configuration/ importation des données dans Geotrek admin. 

Merci d'avance

**Comment by camillemonchicourt** [comment]
Bonjour,

Pour les données à intégrer vous pouvez déjà vous reporter à ce document : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/integration-fr.rst

Il faut savoir que la base de données de Geotrek se base sur un mécanisme de segmentation dynamique où quasiment tous les contenus sont stockés de manière relative aux tronçons (https://geotrek.readthedocs.io/en/master/user-manual.html#gestion-des-sentiers). 

Les données de base sont ainsi : 
- Les communes (zonage.l_commune)
- Les zonages (zonage.l_zonage_reglementaire)
- Les tronçons ( geotrek.l_t_troncon)

Il y a différentes manières pour importer vos données SIG dans ces 3 tables. La plus simple étant peut-être de faire des copier-coller depuis QGIS comme indiqué dans ce tuto : http://geotrek.ecrins-parcnational.fr/articles/en/2018-02-geotrek-jamaica.html#data

Aussi détaillé pour l'import de tronçons depuis QGIS (qui date un peu donc il y a quelques champs en plus) : https://makina-corpus.com/blog/metier/2014/importer-une-couche-de-troncons-dans-geotrek

Pour les objets relatifs aux tronçons en segmentation dynamique (signalétique, aménagements, itinéraires, POI...), c'est plus complexe car leur géométrie est relative aux tronçons existants. 

Il existe des fonctionnalités d'import en ligne de commande ou en SQL pour faire cela.

**Comment by MROALI** [comment]
merci :)
