### ISSUE TITLE
Module Signalétique CD30 - export CSV

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1871]
Caler l'export CSV en fonction du fichier excel fourni au mois de décembre.
[lames_a_commander.xlsx](https://github.com/GeotrekCE/Geotrek-admin/files/2919899/lames_a_commander.xlsx)

**Comment by camillemonchicourt** [comment]
De mémoire, on avait dit que cet export était assez spécifique et qu'on restait sur un export générique, qui inclut tous les champs à plat, libre à chacun ensuite de supprimer des colonnes ou en concaténer. 
https://github.com/GeotrekCE/Geotrek-admin/issues/1782

Par exemple, le fait d'ajouter le code commune dans le code lame est spécifique. Mieux vaut avoir le code lame dans une colonne, le code INSEE dans une autre et si le CD30 souhaite il concatène ces 2 colonnes, pour ne pas l'imposer à tous.
