### ISSUE TITLE
Module Signalétique CD30 - export poteau pdf

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1872]
Il manque une photo et les informations des lames sur le PDF d'un poteau

**Comment by camillemonchicourt** [comment]
Les exports PDF n'intègrent pas les photos attachés aux objets. Il s'agit d'une fonctionnalité non existante à développer. 

Pour le fait d'intégrer dans les PDF des signaltiques, les infos sur les lames et leurs lignes, en effet ce serait cohérent.

**Comment by lblum30** [comment]
[2019030116040938163.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/2919924/2019030116040938163.pdf)

**Comment by gutard** [comment]
@lblum30, merci pour l'exemple.

**Comment by camillemonchicourt** [comment]
Là aussi, rester générique en intégrant toutes les infos présentes dans la fiche WEB comme actuellement.
Mais pourquoi pas y ajouter les photos ainsi que les listes des lames et lignes.

**Comment by gutard** [comment]
Fixé dans la [2.24.6](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.24.6) pour la partie description des lames et des lignes.

Concernant la photo, le template du PDF est configurable.
