### ISSUE TITLE
Module Signalétique CD30 - Doublons

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1873]
Il y a des doublons dans le filtre Année sur les interventions,

**Comment by camillemonchicourt** [comment]
Exact, le filtre duplique les années par autant d'interventions qu'il y a eu chaque année.

**Comment by camillemonchicourt** [comment]
Idem dans le filtre Année du module Interventions.

**Comment by gutard** [comment]
Fixé dans la [2.24.6](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.24.6)

**Comment by camillemonchicourt** [comment]
De mémoire c'était aussi le cas dans le filtre "Année d'intervention" du module Signalétique (et Aménagements ?). 
Réglé là aussi ?
