### ISSUE TITLE
Module Signalétique CD30 - enjeux

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1874]
Le champ Enjeu sur les interventions devrait être optionnel

**Comment by gutard** [comment]
Effectivement, il est optionnel lors de la création car il est sensé se calculer tout seul à partir des l'enjeux des tronçons liés à cette intervention. Le souci c'est que l'enjeu n'est pas obligatoire sur les tronçons et que si aucun tronçon n'a d'enjeu, l'enjeu calculé reste NULL. Du coup quand on va le modifier et qu'il devient obligatoire, ça force à choisir une valeur à ce moment là.

@camillemonchicourt, est-ce que cela pose un problème de rendre le champ Enjeu optionnel sur les interventions ?

**Comment by camillemonchicourt** [comment]
Non en effet, ça serait mieux de le rendre totalement optionnel sur les interventions.
Je pense que ce champs était une vue de l'esprit peu ou pas utilisé.

**Comment by gutard** [comment]
OK merci. Adjugé.

**Comment by gutard** [comment]
Fixé dans la [2.24.6](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.24.6)
