### ISSUE TITLE
Module Signalétique CD30 - Filtre

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1875]
Il manque un filtre pour sélectionner les poteaux/lames dans les interventions

**Comment by camillemonchicourt** [comment]
Je ne comprends pas bien. 
Dans le module Interventions, tu voudrais un filtre qui liste les poteaux et les lames pour pouvoir filtrer sur un poteau ou une lame ?

Ca ne me parait pas possible ni pertinent, car le module Interventions est globale et pas lié uniquement à la Signalétique.

**Comment by lblum30** [comment]
Quel est le mode opératoire pour avoir la liste des lames cassées?

**Comment by camillemonchicourt** [comment]
Rends toi sur la liste des signalétie : <URL_GEOTREK_ADMIN>/blade/list/ puis utilise le filtre ETAT.

**Comment by gutard** [comment]
Le souci c'est pour avoir la liste des interventions sur tous les (ou un ensemble de) signalétiques.

**Comment by gutard** [comment]
Fixé dans la [2.24.6](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.24.6)
