### ISSUE TITLE
Module signalétique - lenteur

### ISSUE THREAD

**Issue by lblum30** [GeotrekCE/Geotrek-admin#1876]
![image](https://user-images.githubusercontent.com/48129850/53647424-d6725700-3c3d-11e9-8446-7cc91717ea48.png)
Pourquoi ce message qui me fige l'appli?

**Comment by camillemonchicourt** [comment]
On dirait un problème de droits. 
Il faudrait plus de précisions sur le contexte.

**Comment by lblum30** [comment]
Je consulte un poteau après avoir fait un filtre sur les poteaux d'une commune.

**Comment by lblum30** [comment]
Ca plante en permanence avec ce message. Très difficile de tester!
de plus, pas accès l'admin en haut à droite pour paramétrer les listes de choix.
Le rafraichissement permanent de la carte en fonction de la liste fait mouliner l'appli en permanence.

**Comment by camillemonchicourt** [comment]
C'est la liste qui rafraichit en fonction de la zone de carte affichée. C'est un fonctionnement souhaité.
Si tu as ce message liés aux droits et n'a pas accès à l'Admin des listes, c'est que ton compte n'a pas été configuré avec les droits suffisants.

**Comment by lblum30** [comment]
C'est pourtant le compte dpt30 du département. Il est sensé être au top!

**Comment by camillemonchicourt** [comment]
Je ne sais pas de quoi il s'agit.

**Comment by gutard** [comment]
Je viens de modifier le compte pour qu'il ait tous les droits.
