### ISSUE TITLE
Static pages creation with just one language

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#1879]
Geotrek-admin 2.24.1
When there is just one language in settings.ini, creating a static page return an internal server error.
Adding the "en" language in settings.ini solve the problem.

Attached the log file from /var/log/supervisor/geotrek.log
[geotrek.log](https://github.com/GeotrekCE/Geotrek-admin/files/2935476/geotrek.log)

**Comment by gutard** [comment]
Removing a langage after the initial installation is not possible. Adding a new language is possible. Just run "make update" after the change.

**Comment by gutard** [comment]
If you want you can manually remove all fields suffixed by `_en`
