### ISSUE TITLE
Interventions - Add category field

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1880]
Actually the interventions type field is used in PNE for a very detailed information. 
We would need a global field that could be called Category.
Each intervention type would be related to an intervention category. 
In the form, when selecting a category, the intervention values would be filtered to display only those related to the selected category.

**Comment by gutard** [comment]
On peut s'inspirer des contenus touristiques pour l'implémentation.
@camillemonchicourt, comment doit-on gérer la migration des données ? Les anciens types dans la base deviennent des catégories (renommage de la table existante en conservant les données) et on recrée une table pour les types ?

**Comment by camillemonchicourt** [comment]
Les anciens types restent les types. On ajoute juste un champ Catégories qui est un niveau plus haut et plus général. 
Une fois qu'on a renseigné les catégories, on peut y associer les types existants.

**Comment by gutard** [comment]
OK. Du coup, lors de la migration de données, ça oblige a créer une catégorie en lui donnant un nom arbitraire et à y associer tous les types existant. Quel serait ce nom arbitraire ?

Pour une nouvelle instance, aujourd'hui, les types par défaut sont :
* "Entretien"
* "Travaux d'ouvrages"
* "Travaux d'urgence"
* "Suppression"
* "Création"

Quelles seraient les catégories par défaut et comment seraient répartis ces types par défaut dans les catégories par défaut ?

**Comment by camillemonchicourt** [comment]
OK OK. 
Désormais nous avons beaucoup beaucoup plus de types et ces 5 types par défaut seraient plutôt ce que l'on mettrait dans CATEGORIES. 
Mais c'est peut-être pas la bonne manière de faire et imposer 2 niveaux à tout le monde n'est certainement pas souhaitable. 
On va creuser ça de notre côté.

**Comment by gutard** [comment]
OK, je vais reformuler ma proposition :
* on garde le champ type tel quel avec ses valeurs,
* on ajoute un champ sous-type optionnel sans valeurs par défaut.
Du coup ça ne force aucun changement.
Pour le PNE il faudra juste bricoler les données pour déplacer les types vers les sous-type et créer les types. On peut faire un commande pour automatiser ça. Ou bien ça peut se faire à la main directement en base.

**Comment by camillemonchicourt** [comment]
OK ouais ça correspond à ça. 
Et ça n'imposerait pas à tous de gérer des sous-types, en rendant ce champ Non obligatoire.

**Comment by babastienne** [comment]
@camillemonchicourt toujours un besoin de votre côté ?

**Comment by camillemonchicourt** [comment]
A priori non, je pense que ça complique d'avoir 2 niveaux de catégorisation des interventions.
C'est seulement notre contexte où on a trop de types différents, mais on fait avec.
