### ISSUE TITLE
tronçon non couvert par le MNT

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1894]
Lors d'un tracé d'un tronçon entièrement non couvert par un MNT (dans l'emprise du MNT mais sans donnée dans la bande en tout point du tronçon) cela déclenché une erreur qui ne permettait pas d'enregistré le tronçon soit par l'interface web (internal server error) soit lors du commit dans qgis.

Cette erreur ne se déclenchait pas si il y avait au moins une partie du tronçon intersecté un pixel avec valeur du MNT.

Manipulation effectué avec la version 2.24.4 de geotrek-admin installé sur un ubuntu server 16.04 et sur qgis 2.18 et qgis 3.4. Le MNT avait été pris sur SRTM DATA : http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_38_04.zip (le tronçon avait été tracé sur l'ile de porquerolles, sur la pointe de l'Alycastre, non couverte par le MNT).

**Comment by Cynthia-Borot-PNE** [comment]
Ainsi il serait intéressant d'afficher un message d'erreur compréhensible à l'utilisateur dans les 2 cas : entièrement et partiellement couvert par le MNT (car dans ce dernier cas le calcul des dénivelés sera faux). Un message du type "Votre MNT ne couvre pas la totalité de votre tronçon, il est ainsi impossible de le sauvegarder, charger un nouveau MNT".

**Comment by babastienne** [comment]
Il est à présent tout à fait possible de créer un tronçon n'étant pas couvert par le MNT.
