### ISSUE TITLE
 CRITICAL: Failed to install custom SQL file 50_troncons_split.sql': column "brouillon" of relation "l_t_troncon" does not exist

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#1895]
Lors de la migration de geotrek 2.21.0 à 2.24.8 geotrek envoi par mail un rapport d'erreur concernant l'execution d'un script sql (50_troncons_split.sql).
Par ailleur la migration se passe bien

Report
Failed to install custom SQL file '/opt/geotrek_app/Geotrek/geotrek/core/sql/50_troncons_split.sql': column "brouillon" of relation "l_t_troncon" does not exist

**Comment by camillemonchicourt** [comment]
Je crois que le PnCalanques a rencontré le même problème mais je ne sais pas quelle a été l'issue. 
Je dirai que c'est lié à la migration en 2.22.0 qui ajoute la colonne BROUILLON à la table des tronçons : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.22.0

Détaillé ici : https://github.com/GeotrekCE/Geotrek-admin/issues/1774

Il y a peut-etre un problème de migration ?

**Comment by camillemonchicourt** [comment]
@amandine-sahl, du coup tu n'as pas le champs ``brouillon`` dans la table ``geotrek.l_t_troncon`` ?
aurais-tu les éventuelles erreurs dans le fichier ``install.log`` ?

**Comment by amandine-sahl** [comment]
Le champ brouillon est bien présent dans la table l_t_troncon

Message d'erreur de install.log
```

CRITICAL 2019-03-22 16:51:50,941 geotrek.common.utils.postgresql Failed to install custom SQL file '/opt/geotrek_app/Geotrek/geotrek/core/sql/50_troncons_split.sql': column "brouillon" of relation "l_t_troncon" does not exist


Traceback (most recent call last):
  File "/opt/geotrek_app/Geotrek/geotrek/common/utils/postgresql.py", line 97, in load_sql_files
    cursor.execute(sql)
  File "/opt/geotrek_app/Geotrek/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek_app/Geotrek/lib/eggs/Django-1.11.14-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/geotrek_app/Geotrek/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
ProgrammingError: column "brouillon" of relation "l_t_troncon" does not exist

```

**Comment by camillemonchicourt** [comment]
OK j'espère que cette migration a pu passer dans une migration suivante.

**Comment by amandine-sahl** [comment]
Si je fait une migration de 2.24.8 vers 2.24.8, il n'y a plus de message d'erreur. Il y a surement un soucis dans l'ordre d'execution des scripts

**Comment by gutard** [comment]
Il faudrait regarder le install.log complet pour comprendre l’enchaînement des opérations mais je pense qu'au final tout est OK.
