### ISSUE TITLE
Black maps in public print PDF exports

### ISSUE THREAD

**Issue by xavyeah39** [GeotrekCE/Geotrek-admin#1900]
Hi,

I dig up issue #979. We get the same behaviour described in 2014 by @camillemonchicourt.

In several treks created in a previous version (and not updated from there) maps are correctly displayed when we doing a public print in PDF. But others display a map with black tiles as background (by the way, all the WMTS layers sets are correctly displayed in the admin GUI).

When I edit a trek from admin GUI (with black map in the print) and just save it without updating anything, the map screenshot is regenerated and public printing in PDF is finally OK with the correct background.

Note : we just updated Geotrek-admin to 2.25.2 release (but problem seems to be older) and we don't have custom template for public print like in #1734

So I try :

1. Using the command found in #1331 (thanks @camillemonchicourt)

        cd Geotrek
        bin/django prepare_map_images --url=http://XX.XX.XXX.XXX

    but it raise an python error :

    `/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/cryptography-2.6.1-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
      utils.PersistentlyDeprecated2018,
    /home/geotrek/Geotrek-admin-2.25.2/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
      """)
    Traceback (most recent call last):
      File "bin/django", line 127, in <module>
        sys.exit(djangorecipe.binscripts.manage('geotrek.settings.custom'))
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/djangorecipe-2.2.1-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
        management.execute_from_command_line(sys.argv)
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 206, in fetch_command
        klass = load_command_class(app_name, subcommand)
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 40, in load_command_class
        module = import_module('%s.management.commands.%s' % (app_name, name))
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/geotrek/Geotrek-admin-2.25.2/lib/eggs/mapentity-4.4.13-py2.7.egg/mapentity/management/commands/prepare_map_images.py", line 5, in <module>
        from django.core.management.base import NoArgsCommand
    ImportError: cannot import name NoArgsCommand`

2. Truncate contents in the maps folder with `rm -rf var/media/maps/*` then, launch a new sync with Geotrek-rando to rebuild images and PDF sheets (with `sync_rando.sh`)

Results : all new maps PNG files still display black backgrounds and all the touristic-content PNG files are empty (0kb)

Thanks in advanced to help us understanding !

**Comment by camillemonchicourt** [comment]
Strange that when you edit and save a tek, the map capture generated is OK, but when you launch the synchronisation, the images are black...

**Comment by xavyeah39** [comment]
Yes strange... I confirm this behavior after multiple tests

**Comment by gutard** [comment]
If you use a tiles source with a key linked to a referer (eg. géoportail) you have to set the --url option of the sync_rando command with this referer. Not doing so could explain your problem.

Try to truncate again var/media/maps/ without running sync_rando or running it with --url. I should work.

**Comment by xavyeah39** [comment]
Thank you for your reply Gaël. 
Yes I use Géoportail tiles source with referer. I will try with --url option and I keep you in touch.

**Comment by camillemonchicourt** [comment]
Oh OK I never knew the use of the --url option in sync_rando command.
Now I understand !

**Comment by xavyeah39** [comment]
Thanks Gaël !
I added the --url option in the sync_rando command in the `sync_rando.sh` file like this : 

	/home/`whoami`/Geotrek/bin/django sync_rando -v2 -l fr -t /home/geotrek/data --url http://XXX.XXX.XXX.XXX

Then, I launched the command manually and it works but not for all treks... 
For some of them, map PNG file generated is now empty (0kb).

**Comment by xavyeah39** [comment]
To sum up : 
I launched a first time `sync_rando` command and get 88 empty files out of 346 files.
I deleted the empty ones, then launched the command again and only had 24 0kb files.
After a third time, only 8 files, and it's finally OK at the fourth ! 
Thank you for your help @gutard !
An explanation about these random failures ?
