### ISSUE TITLE
Module Signalétique - champs direction sur les lignes des lames

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1903]
Serait-il possible de rajouter un champ direction sur les lignes des lames car la direction est indiquée au niveau de la ligne et non au niveau de la lame (cf. photos) ?
![iles_20180916_1435471824186266](https://user-images.githubusercontent.com/48252187/55176119-d30cb580-5180-11e9-9ea9-3a3115d9f4ad.jpg).
La direction pourrait provenir, comme pour les lames, de la table s_b_direction.

**Comment by camillemonchicourt** [comment]
OK sujet évoqué aussi ici : https://github.com/GeotrekCE/Geotrek-admin/issues/1782#issuecomment-477673029

Il s'agit en effet d'une particularité des parcs nationaux. 
Le module a été conçu sur la base des signalétiques départementales où il y a un picto par lame. 

Il me semble dangereux d'avoir une même information dans la BDD définissable à 2 niveaux différents. Soit au niveau de la lame, soit au niveau de la ligne. Pour la saisie, pour les exports, ça va poser problème.
Mais je ne vois pas comment modéliser ça plus proprement pour que certains puissent fonctionner avec les pictos sur la lame et d'autres sur la ligne.

**Comment by GuillaumeBoitel** [comment]
Je ne parle pas des pictogrammes mais de la direction (sens de la flèche sur les 2 lames du haut). A moins qu'il faille considérer la flèche non pas comme une direction mais comme un pictogramme. Mais pour moi c'est différent : je considère que la direction est une information comme la distance ou la durée et je la distingue du pictogramme qui a plus une mission d'information (interdiction, service, balisage de sentier).

Pour les pictogrammes, ils sont de toutes façon défini actuellement sur les lignes et non sur les lames.

**Comment by camillemonchicourt** [comment]
OK je me suis embrouillé en effet.

**Comment by geofffl** [comment]
Je me permets une autre remarque concernant le sujet : nos lames (charte Savoie) peuvent comporter plusieurs pictos par ligne (exemple : GR + refuge). Peut-on imaginer uen système d'ajout de picto pour une même ligne (à l'image de la possibilité d'ajouter plusieurs lignes pour une même lame) ?

**Comment by camillemonchicourt** [comment]
Le module Signalétique était très basique jusqu'à récemment. 
Fin 2018, le CD30 a souhaité le faire évoluer pour pouvoir gérer les lames et les lignes et ainsi pouvoir gérer les commandes de signalétique à partir des données présentes dans Geotrek-admin, besoin partagé depuis un bon moment.
Un travail de modélisation a ainsi été réalisé, puis a été partagé à l'ensemble de la communauté ici : https://github.com/GeotrekCE/Geotrek-admin/issues/1782
et ici : https://groups.google.com/forum/#!searchin/geotrek-fr/signal%C3%A9tique%7Csort:date/geotrek-fr/69HrJITTuL0/SEQa02qiBQAJ

Il est ensuite apparu que toutes les structures ne géraient pas les pictos et direction au même niveau (lame ou ligne). 

Du coup pour le moment, je ne vois pas comment on pourrait gérer correctement le fait que certains les associent aux lames et d'autres aux lignes.

**Comment by gutard** [comment]
On peut imaginer une évolution qui rendrait le champ direction sur la lame optionnel. Dans le cas où celui-ci n'est pas renseigné, le champ direction serait ajouté pour chaque lignes de cette lame.
