### ISSUE TITLE
Problème d'affichage du texte Picto dans la fiche lame

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1904]
Les pictogrammes ne s'affichent pas dans la fiche lame alors qu'ils s'affichent dans la fiche signalétique qui contient la lame (et aussi dans le formulaire d'édition de la lame).
Fiche lame :
![image](https://user-images.githubusercontent.com/48252187/55177619-ecfbc780-5183-11e9-81c3-d49323ce805a.png)
Fiche signalétique : 
![image](https://user-images.githubusercontent.com/48252187/55177667-0b61c300-5184-11e9-8ca7-600e3054976d.png)

**Comment by camillemonchicourt** [comment]
Exact ! Bien vu, merci.

**Comment by LePetitTim** [comment]
Je ne vois pas au niveau de formulaire d'edition.

**Comment by LePetitTim** [comment]
#1909

**Comment by LePetitTim** [comment]
Version 2.26.1
