### ISSUE TITLE
Load and display additional layers

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1915]
Depuis la version 2.25.0, les couches géographiques additionnelles ne sont plus chargées et affichées par défaut pour de meilleures performances : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.25.0

Mais du coup je ne vois pas comment les afficher ?

On a mis à jour notre Geotrek-admin et elles ont logiquement disparues.

**Comment by camillemonchicourt** [comment]
Je ne vois pas de paramètre dans la PR qui ajoute cette fonctionnalité ? 
https://github.com/GeotrekCE/Geotrek-admin/pull/1890

**Comment by gutard** [comment]
Qu'est ce qui a disparu exactement ? Je ne comprends pas bien. La PR #1890 ne change rien fonctionnellement. Les couches qui ne sont pas sélectionnées dans le sélecteur de couches ne sont plus chargées systématiquement sur le réseau mais à la demande.

**Comment by camillemonchicourt** [comment]
Dans l'arbre des couches, toutes les zonages réglementaires (coeur du parc, réserves...) ne sont plus affichés.
Seules communes et secteurs sont toujours présentes : 

![image](https://user-images.githubusercontent.com/4418840/55562743-e07fed80-56f4-11e9-8819-fd83f8f6d8d2.png)

**Comment by gutard** [comment]
OK, je comprends mieux. C'est probablement un effet collatéral non voulu. @LePetitTim, tu peux regarder stp ?

**Comment by camillemonchicourt** [comment]
OK merci.
Mais sinon je comprends mieux. 
Et c'est une très bonne chose que de charger ces couches seulement quand on demande de les afficher.

**Comment by LePetitTim** [comment]
Version 2.26.2 resoud le problème

**Comment by camillemonchicourt** [comment]
On est passé en 2.26.4 et on a toujours le même problème.

**Comment by camillemonchicourt** [comment]
En fait c'est un problème de notre côté. 
On avait déplacé le répertoire ``var`` à la racine du ``home`` et fait un lien symbolique après coup, donc il ne devait plus trouver le cache. 

Désolé.
