### ISSUE TITLE
Import Apidae data issue

### ISSUE THREAD

**Issue by geofffl** [GeotrekCE/Geotrek-admin#1919]
We are facing a problem while trying to import data from Apidae. Firstly, by running `./bin/django import bulkimport.parsers.HebergementParser`, there was this message : 

> CommandError: Le type de fichier 'Photographie' n'existe pas dans Geotrek-Admin. Merci de l'ajouter

But, indeed, the "Photographie" type is present... Then, we have tried to start import from the GUI, and, this time, the green progression bar appeared (telling us everything is fine) with this information :

> 2/28 lignes importées.
> 1 enregistrement non modifié.
> 27 avertissements:
>  Line 18:
> - tuple index out of range,
>  Line 19:
> - tuple index out of range,
>  Line 12:
> - tuple index out of range,
>  Line 13:
> - tuple index out of range,
>  Line 10:
> - tuple index out of range,
>  Line 11:
> - tuple index out of range,
>  Line 16:
> - tuple index out of range,
>  Line 17:
> - tuple index out of range,
>  Line 14:
> - tuple index out of range,
>  Line 15:
> - tuple index out of range,
>  Line 23:
> - tuple index out of range,
>  Line 22:
> - tuple index out of range,
>  Line 20:
> - tuple index out of range,
>  Line 27:
> - tuple index out of range,
>  Line 26:
> - tuple index out of range,
>  Line 25:
> - tuple index out of range,
>  Line 24:
> - tuple index out of range,
>  Line 28:
> - tuple index out of range,
>  Line 8:
> - tuple index out of range,
>  Line 9:
> - Le champ required 'localisation.geolocalisation.geoJson.coordinates' est manquant,
>  Line 1:
> - tuple index out of range,
>  Line 2:
> - tuple index out of range,
>  Line 3:
> - tuple index out of range,
>  Line 4:
> - tuple index out of range,
>  Line 5:
> - tuple index out of range,
>  Line 6:
> - tuple index out of range,
>  Line 7:
> - tuple index out of range,

But, when we check the touristic content, no modifications have been made to the list. We even tried to delete 4 objects, then start again import from gui : same result, like no update nor new object imported following the 4 deletions.

Secondly, when we tried again from the command line, we find exactly the same message as above from the gui. Then, a new import started from the gui lead to this message : 

> OperationalError : SSL SYSCALL error: Bad file descriptor 

The behavior seems to be erratic, as sometimes it fails from the command line and works with the gui import, sometimes vice versa. Anyway, the result is the same : no update and new object are imported.

For the record, we are running the latest version (2.26.1) since friday (we were running 2.19.1).
Until now, everything was fine, and we did not make any change.

Here is the parsers file :

> from geotrek.tourism.parsers import TouristicContentApidaeParser
> 
> class HebergementParser(TouristicContentApidaeParser):
>     label = u"AEM"
>     api_key = 'XXXXXX'
>     project_id = XXXX
>     selection_id = XXXXX
>     category = u"Sortie accompagnée"
>     type1 = [u"Accompagnateur randonnée pédestre"]

**Comment by geofffl** [comment]
Version 2.26.3 solves the issue !

**Comment by camillemonchicourt** [comment]
OK super. 
Car nous n'avions pas ces erreurs lors d'imports Apidae dans les versions précédentes.

On a bien quelques erreurs à chaque imports mais elles sont liés à des données incomplètes au niveau d'APIDAE, ou à 2 catégories APIDAE qu'on n'a pas souhaité ajouté au niveau de Geotrek :

```
398/398 lignes importées.
13 enregistrements mis à jour.
0 enregistrement supprimé.
383 enregistrements non modifiés.
10 avertissements:
# Line 56:
- Le champ required 'localisation.geolocalisation.geoJson.coordinates' est manquant,
# Line 265:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_6721.html',
# Line 393:
- Le champ required 'localisation.geolocalisation.geoJson.coordinates' est manquant,
# Line 259:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_9311.html',
# Line 288:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_6704.html',
# Line 274:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_2071.html',
# Line 269:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_9963.html',
# Line 348:
- Type1 'Centre de vacances' n'existe pas dans Geotrek-Admin. Merci de l'ajouter,
# Line 162:
- Type1 'Maison familiale de vacances' n'existe pas dans Geotrek-Admin. Merci de l'ajouter,
# Line 283:
- Impossible de télécharger 'http://www.gites-de-france-hautes-alpes.com/album-photos_6741.html',
```

**Comment by amandine-sahl** [comment]
Cette erreur semble toujours présente dans la version 2.38.2

```
$ sudo geotrek import PNCHebergementsGeneralEspritParcParser
CommandError: Le type de fichier 'Photographie' n'existe pas dans Geotrek-Admin. Merci de l'ajouter
```
Le type photographie est bien présent dans la liste des Types de fichier 


Fichier parsers.py
```
from geotrek.tourism.parsers import EspritParcParser


class PNCHebergementsGeneralEspritParcParser(EspritParcParser):
    delete = False
    label = u"Hébergements Marqués Esprit Parc - HEB"
    url = u"http://gestion.espritparcnational.com/ws/?f=getProduitsSelonParc&codeParc=PNC&typologie=HEB"
    constant_fields = {
        'category': u"Hébergement",
        'published': True,
        'approved': True,
        'deleted': False,
    }
```

**Comment by gutard** [comment]
Est-ce que la structure liée au type de fichiers "Photographie" est bien vide ou correspond bien à la structure par défaut déclarée dans les settings ?

**Comment by amandine-sahl** [comment]
Effectivement il y a un soucis de ce coté là. 
Le problème est que le paramètre `geotrek-admin/DEFAULT_STRUCTURE` n'est configurable que lors de l'installation et dans la mesure ou nous utilisons une authentification externe nous n'avons pas accès à admin (authent/structure).

Lorsque nous appellons la route  : `http://geotrek-admin.cevennes-parcnational.net/admin/common/filetype/?q=photo`

```
oct. 05 07:41:16 geotrekadmin gunicorn[11648]: ERROR 2020-10-05 09:41:16,530 django.request Internal Server Error: /admin/common/filetype/
oct. 05 07:41:16 geotrekadmin gunicorn[11648]: Traceback (most recent call last):
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = get_response(request)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = self.process_exception_by_middleware(e, request)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     return self.admin_site.admin_view(view)(*args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = view_func(request, *args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = view_func(request, *args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     return view(request, *args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     return bound_method(*args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     response = view_func(request, *args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1685, in changelist_view
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     cl = self.get_changelist_instance(request)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/options.py", line 744, in get_changelist_instance
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     sortable_by,
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 81, in __init__
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     self.queryset = self.get_queryset(request)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 439, in get_queryset
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1023, in get_search_results
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     queryset = queryset.filter(reduce(operator.or_, or_queries))
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     return self._filter_or_exclude(False, *args, **kwargs)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     clone.query.add_q(Q(*args, **kwargs))
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     clause, _ = self._add_q(q_object, self.used_aliases)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1312, in _add_q
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     current_negated, allow_joins, split_subq, simple_col)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     split_subq=split_subq, simple_col=simple_col,
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     condition = self.build_lookup(lookups, col, value)
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1107, in build_lookup
oct. 05 07:41:16 geotrekadmin gunicorn[11648]:     raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
oct. 05 07:41:16 geotrekadmin gunicorn[11648]: django.core.exceptions.FieldError: Related Field got invalid lookup: icontains

```

**Comment by gutard** [comment]
Ce dernier bug n'a rien à voir. Je viens de le corriger dans https://github.com/GeotrekCE/Geotrek-admin/pull/2347

Pour contourner ce bug tu peux éditer la structure associée au type de fichier en cliquant Sur Photographie dans liste sans faire de recherche textuelle : http://geotrek-admin.cevennes-parcnational.net/admin/common/filetype/11/change/

Mais j'ai l'impression que les types de fichiers et les structures sont tous associés à PNC. Si le setting DEFAULT_STRUCTURE est différent de "PNC" je pense que c'est lui qu'il faut changer, pas la structure associée au type de fichier.

**Comment by amandine-sahl** [comment]
Merci pour la réponse. 
Justement j'aimerais savoir comment changer le paramètre DEFAULT_STRUCTURE

**Comment by gutard** [comment]
Il s'appelle précisément `DEFAULT_STRUCTURE_NAME` et il est défini dans le fichier `/opt/geotrek-admin/var/conf/custom.py`. Je pense qu'il est déjà présent; Sinon il faut le rajouter :

```python
DEFAULT_STRUCTURE_NAME = "PNC"
```

**Comment by amandine-sahl** [comment]
Quel est le lien avec le paramètre défini dans la configuration du packet geotrek-admin? Il n'y a pas de risque d'incohérence si je change le fichier custom.py et pas dans la config globale?

```
$ sudo debconf-show geotrek-admin
* geotrek-admin/POSTGRES_PASSWORD: (password omitted)
* geotrek-admin/LANGUAGES: fr en
* geotrek-admin/DEFAULT_STRUCTURE: Parc national des Cévennes
* geotrek-admin/POSTGRES_HOST: db_host
* geotrek-admin/POSTGRES_USER: db_user
* geotrek-admin/TIME_ZONE: Europe/Paris
* geotrek-admin/SERVER_NAME: geotrek-admin.cevennes-parcnational.net
* geotrek-admin/RANDO_SERVER_NAME: *
* geotrek-admin/WORKERS: 4
  geotrek-admin/MANAGE_DB: false
* geotrek-admin/TIMEOUT: 1200
* geotrek-admin/SRID: 2154
* geotrek-admin/POSTGRES_PORT: 5432
* geotrek-admin/POSTGRES_DB: geotrekdb

```

**Comment by gutard** [comment]
Ah oui j'avais oublié que ça faisait partie des questions posées à la configuration du paquet. Du coup, oublie mon commentaire précédent. Ça marcherait mais l'info donnée à la configuration du paquet ne serait plus prise en compte. Il faut plutôt faire un `dpkg-reconfigure geotrek-admin` en modifiant la réponse pour le nom de la structure par défaut. Pour le mot de passe de la base, il faut laisser le champ vide ce qui revient à garder le mot de passe actuel.

**Comment by amandine-sahl** [comment]
`dpkg-reconfigure geotrek-admin` ne permet pas de modifier geotrek-admin/DEFAULT_STRUCTURE. Il  n'est configurable que lors de l'installation et dans la mesure ou nous utilisons une authentification externe nous n'avons pas accès à admin (authent/structure).
Donc ne nous ne pouvons pas réaliser la manipulation indiquée dans la documentation
```
DEFAULT_STRUCTURE_NAME = "GEOTEAM"
Name for your default structure.

    This one can be changed, except it’s tricky.

        First change the name in the admin (authent/structure),
        Stop your instance admin.
        Change in the settings
        Re-run the server.


```

**Comment by gutard** [comment]
Ah ok, je vois. Effectivement, On va y arriver ;) Ce qui m'étonne ce que la procédure de migration récupère l'ancienne valeur qui était sensée être la bonne. Et si c'est une install neuve peu importe ce qu'on choisit ça le créé et on ne peut plus changer après.

Du coup je vois 3 solutions :
- modifier la valeur directement dans debconf avec la commande `debconf-set-selections` avant de faire un `dpkg-reconfigure`,
- faire ce que je disais plus haut dans le fichier custom.py
- modifier le fichier `/opt/geotrek-admin/var/conf/env.in` pour mettre `DEFAULT_STRUCTURE="PNC"`

Le fonctionnement c'est que dpkg-reconfigure génère le fichier `/opt/geotrek-admin/var/conf/env` à partir des données de debconf et du template `/opt/geotrek-admin/var/conf/env.in`. Ce fichier `env` est ensuite lu par Geotrek au démarrage. Et le custom.py permet de surcharger. Modifier `/opt/geotrek-admin/var/conf/env` fonctionnerait mais la modif sera écrasée lors du prochain depkg-reconfigure.

**Comment by gutard** [comment]
Bon je viens de tester et je crois que c'est toujours pas ça. En fait tu peux modifier `/opt/geotrek-admin/var/conf/env` manuellement et redémarrer le service geotrek. Le prochain dpkg-reconfigure tiendra compte de la modif.

**Comment by amandine-sahl** [comment]
Ok j'ai déjà réalisé des opérations suivante dans l'ordre :
 1 - modification de /opt/geotrek-admin/var/conf/env.in
 2 - ajouter DEFAULT_STRUCTURE_NAME = "PNC" à /opt/geotrek-admin/var/conf/custom.py
 3 - modifier la base debconf via debconf-set-selections

Maintenant je pense que toutes mes valeurs de configuration sont exactes. et je peux revenir en arrière sur la modification de env.in 

Le seul soucis c'est qu'il me reste Parc national des Cévennes dans structure liée.

**Comment by gutard** [comment]
> Le seul soucis c'est qu'il me reste Parc national des Cévennes dans structure liée.

Là je vois pas d'autre solution que de faire des UPDATE en SQL pour mettre à jour toutes les FK vers authent_structure. Le souci c'est qu'il y a beaucoup de tables qui pointent vers les structures. Ce setting default_structure date du début du projet et ce n'était pas une bonne idée. Il vaudrait mieux s'appuyer uniquement sur la base.

**Comment by amandine-sahl** [comment]
Ok merci. Pour résumé si par hasard j'ai l'idée de changer l'orthographe (ou autre) de ma structure par défaut il faut changer base debconf  et mettre à jour la base de données.


Ci dessous une requête qui génère les requêtes de mise à jour de la base de données.
```
WITH params AS (
	SELECT 2 AS id_to_find, 1 AS id_to_replace -- Paramètres à changer en fonction
)
SELECT
	CONCAT('UPDATE ', tc.table_name, ' SET ',  kcu.column_name , ' = ', id_to_replace, ' WHERE ', kcu.column_name , ' = ', id_to_find, ';') AS sql
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage 
        AS kcu ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.constraint_column_usage 
        AS ccu ON ccu.constraint_name = tc.constraint_name
     JOIN params ON true
WHERE constraint_type = 'FOREIGN KEY' AND ccu.table_name = 'authent_structure';

```
