### ISSUE TITLE
Problème upgrade 2.26.0

### ISSUE THREAD

**Issue by alizeelamarque** [GeotrekCE/Geotrek-admin#1921]
Bonjour,

Je remplace Thomas durant son absence au PNR du Haut-Jura.

J'ai effectué les mises à jour jusqu'à la 2.25.3 sans soucis mais à la 2.26.0 j'obtiens l'erreur "Could not update data !".
J'ai regardé dans les logs d'installation et j'ai le message suivant :

`
File "/home/adminsig/Geotrek-admin-2.26.1/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist`

J'ai pu redémarrer sur la 2.25.3 qui semble fonctionnelle.

Quelqu'un d'autre a eu ce soucis et sait comment le résoudre ?

Merci.

Alizée

**Comment by gutard** [comment]
Problème a priori fixé dans la release https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.26.4

**Comment by camillemonchicourt** [comment]
Merci.

**Comment by alizeelamarque** [comment]
Merci !
Ça a fonctionné.
