### ISSUE TITLE
Import signalétique

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1926]
Bonjour,

Je viens de finir le relevé près de 600 poteaux de signalétique sur le coeur de parc, j'aurais donc besoin d'importer leurs localisations dans Geotrek-admin. 

Il ne semble pas possible des les importer aussi facilement que les tronçons mais j'ai vu dans le [billet 1858]( https://github.com/GeotrekCE/Geotrek-admin/issues/1858#issuecomment-460784788) :

`Il existe des fonctionnalités d'import en ligne de commande ou en SQL pour faire cela.
`

Cela se trouve où ? Il y a de la doc quelque part sur ce sujet, jai rien trouvé dans la documentation officiel.

Merci d'avance.

Guillaume Boitel

**Comment by camillemonchicourt** [comment]
En effet il y a désormais des commandes permettant d'importer des aménagements, de la signalétique etc...

De la doc est disponible ici, mais pas encore intégrée dans la documentation officielle : https://github.com/GeotrekCE/Geotrek-admin/pull/1833/files

En effet, importer des éléments de signalétique, aménagements, itinéraires, POIs... est plus complexe qu'importer des tronçons, car ces objets sont stockés en segmentation dynamique, relativement aux tronçons. Voir https://makina-corpus.com/blog/metier/2014/la-segmentation-dynamique

Voir aussi les discussions comme https://github.com/GeotrekCE/Geotrek-admin/issues/952, avant que les commandes soient améliorées et complétées.

**Comment by babastienne** [comment]
Bonjour,

Il existe à présent une commande `loadsignage` dans Geotrek, permettant d'ajouter des signalétiques. Pour cela il suffit de passer à la commande un fichier regroupant les objets à importer (type shapefile, ou geojson). 

Pour plus d'informations sur cette commande, vous pouvez trouver les arguments à passer en paramètre en exécutant `geotrek loadsignage --help`.

Ce ticket ne semble plus être actif, je vais donc le fermer. N'hésitez pas à le ré-ouvrir si vous rencontrez toujours ce problème.
