### ISSUE TITLE
Duplicated imported images

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1931]
Un problème identifié dans des versions précédentes faisait que les images des objets importées avec des PARSERS étaient dupliquées à chaque import.
Nous avions vidé les répertoires avec les images des contenus touristiques importés puis relancé les imports.

Le problème semblait corrigé mais en fait nous l'avons toujours. 
Les images des contenus touristiques continuent à être dupliquées à chaque import.

**Comment by LePetitTim** [comment]
Vous utilisez quel parsers ?

**Comment by camillemonchicourt** [comment]
Hébergement APIDAE 
Et Esprit Parc national.

**Comment by camillemonchicourt** [comment]
Les medias importés de Esprit Parc national continuent à s'empiler chaque jour et à grossir les répertoires mais aussi la BDD. 

La dernière fois on avait vidé les répertoires des médias importés mais on avait aussi essayé de nettoyer la BDD et sur cette partie ça avait été un peu compliqué.

**Comment by camillemonchicourt** [comment]
Après investigations, le problème semble subsister uniquement sur le parser EspritParc et être bien corrigé pour le parser Apidae.

**Comment by camillemonchicourt** [comment]
Du coup certains de nos Contenus touristiques importés d'EPN avaient leurs photos dupliquées plus de 800 fois. Sur le serveur, dans la BDD mais aussi dans les data copiées sur nos Geotrek-rando. 

Pour commencer et limiter cela et réduire l'espace disque au niveau des synchros, Geotrek-rando et Geotrek-mobile, je les ai au moins supprimé de la BDD. 

Il faudrait aussi supprimer les fichiers du serveur Geotrek-admin et les duplications vont reprendre dès la prochaine synchronisation, mais ça fait déjà un coup de ménage partiel.

```SQL
-- Compter le nombre de fichiers par catégorie de Contenu touristique
SELECT count(*), ctc.nom, ct.categorie, fl.filetype_id FROM geotrek.fl_t_fichier fl
JOIN tourisme.t_t_contenu_touristique ct ON ct.id = fl.object_id
JOIN tourisme.t_b_contenu_touristique_categorie ctc ON ctc.id = ct.categorie
WHERE fl.content_type_id = 73
GROUP BY ctc.nom, ct.categorie, fl.filetype_id
;

-- Supprimer les fichiers d'une catégorie de CT
-- Produits du terroir dans notre cas (categorie = 6)
-- Les fichiers seront aussi à supprimer physiquement dans var/media/paperclip...
DELETE FROM geotrek.fl_t_fichier fl
USING tourisme.t_t_contenu_touristique ct
WHERE ct.id = fl.object_id AND ct.categorie = 6;

-- Compter le nombre de vignettes concernant des fichiers qui ne sont plus dans geotrek.fl_t_fichier (donc supprimés à priori)
-- A supprimer de django.easy_thumbnails_thumbnail puis django.easy_thumbnails_source
SELECT count(*) FROM django.easy_thumbnails_thumbnail tht
JOIN django.easy_thumbnails_source ths ON ths.id = tht.source_id
WHERE ths.name NOT IN (SELECT attachment_file FROM geotrek.fl_t_fichier);

-- Compter le nombre de fichiers par objet
SELECT count(*) as nb_fichiers, object_id FROM geotrek.fl_t_fichier 
GROUP BY object_id
ORDER by nb_fichiers DESC;
```

**Comment by LePetitTim** [comment]
Est ce que tu as des contenus touristiques qui ne sont pas dans les flux ?

**Comment by camillemonchicourt** [comment]
Le problème venait du fait que les URL distantes des images étaient renvoyées à l'API avec des URL en http, alors que le serveur EPN redirige en https. 

L'interrogation de l'info ``content-length`` dans le header des images distantes, utilisé pour identifier si l'image distante a changé, ne fonctionnait pas correctement en https. 

Corrigé ici : https://github.com/GeotrekCE/Geotrek-admin/pull/2047

**Comment by LePetitTim** [comment]
Passer a la version 2.29.1 !

**Comment by camillemonchicourt** [comment]
Une fois la mise à jour corrective installée, voici ce qui a été fait pour faire le ménage dans les images. 

La méthode consiste à supprimer toutes les images des contenus touristiques puis relancer tous les imports. 

Il a d'abord fallu identifier si il y avait des contenus touristiques qui n'avaient pas été importés automatiquement mais avaient été saisis et qui contenaient des photos, pour ne pas les perdre. Dans notre cas, il n'y en avait que deux qui ont été mis de côté.

Ensuite tout le contenu du répertoire ``var/media/paperclip/tourism_touristiccontent/`` a été supprimé et les deux photos sus-citées ont été restaurées.

Puis la requête SQL de suppression des fichiers dans la BDD a été exécutée ``DELETE FROM geotrek.fl_t_fichier WHERE content_type_id=73 AND object_id NOT IN (190, 1009);``

Attention le 73 correspond aux contenus touristiques sur l'instance du PNE, cette valeur est variable d'un Geotrek à l'autre et il ne faut pas se tromper de numéro.

Pour le trouver on peut faire par exemple ``SELECT id from django_content_type WHERE model='touristiccontent';``
Les numéros 190 et 1009 étaient les deux contenus touristiques avec des photos ajoutés manuellement.

Après cela, plus de 170.000 vignettes d'images étaient listées dans la table ``django.easy_thumbnails_thumbnail``, identifiées avec la requête : 

```SQL
-- Compter le nombre de vignettes concernant des fichiers qui ne sont plus dans geotrek.fl_t_fichier
SELECT count(*) FROM django.easy_thumbnails_thumbnail tht
JOIN django.easy_thumbnails_source ths ON ths.id = tht.source_id
WHERE ths.name NOT IN (SELECT attachment_file FROM geotrek.fl_t_fichier);
```

L’exécution de la commande ``./bin/django thumbnail_cleanup`` (https://sorl-thumbnail.readthedocs.io/en/latest/management.html#thumbnail-cleanup) a permis de faire le ménage dans les vignettes, au niveau des fichiers inutiles et des enregistrements dans la base de données.

Résultat dans notre cas : 

```
Sources checked:                           82547
Source references deleted from DB:         73224
Thumbnails deleted from disk:             173377
(Completed in 123.0 seconds)
```

Ces opérations sont assez dangereuses. Il faut comprendre ce qu'on fait pour ne pas risquer de perdre des données et bien faire une sauvegarde avant de lancer de telles opérations.
