### ISSUE TITLE
Message d'erreur export PDF, erreur légende

### ISSUE THREAD

**Issue by alizeelamarque** [GeotrekCE/Geotrek-admin#1932]
Bonjour,

Depuis les mises à jour, nous n'arrivons plus à exporter des PDF depuis GeoAdmin. L'url proposée finit en .odt.
Ex : http://randoadmin.parc-haut-jura.fr/convert/?url=/document/trek-180405.odt

Et nous recevons le message :
`ERROR: Request on http://127.0.0.1:6543/?url=http%3A//randoadmin.parc-haut-jura.fr/document/infrastructure-210961.odt&to=application/pdf failed (status=500)`

Nous avons également remarqué que sur la carte, les zones réglementaires s'affichent correctement mais dans la légende elles apparaissent toutes en rouge.
![erreur_legende_Geotrek](https://user-images.githubusercontent.com/49558245/56643719-723aa500-667a-11e9-8c1f-b9c81e251140.png)

**Comment by camillemonchicourt** [comment]
Même problème pour nous et sur le serveur de démo (http://geotrekdemo.ecrins-parcnational.fr/) depuis plusieurs versions, tous les exports PDF métier ne fonctionnent plus. 

Pour les couleurs de la légende, j'ai constaté pareil depuis la mise à jour en 2.26.x mais il vaut mieux ouvrir 2 tickets différents dans ce cas, car cela n'a rien à voir avec le premier sujet.
C'est surement un autre effet de bord des évolutions de performance apportés au niveau du chargement des zonages réglementaires : https://github.com/GeotrekCE/Geotrek-admin/issues/1915

**Comment by LePetitTim** [comment]
#1933

**Comment by LePetitTim** [comment]
Concernant les pdf depuis quand il y a le problème ?

**Comment by camillemonchicourt** [comment]
Merci pour les couleurs.
Pour le PDF je ne saurai pas dire.
C'est pas nouveau.

**Comment by alizeelamarque** [comment]
Merci.
Idem pour les PDF, je ne sais pas non plus à partir de quand on a eu le souci...

**Comment by LePetitTim** [comment]
Concernant les pdf c'est normal il va tout d'abord creer un fichier odt puis un docx et enfin le transformer en pdf. Donc c'est tout a fait normal d'avoir une url en http://domain:8000/convert/?url=/document/trek-474260.odt pa exemple. Cependant l'erreur 500 est plus étrange.
