### ISSUE TITLE
Sync_mobile - Partial portal filter

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1941]
Quand on fait une synchro mobile, filtrée par portail, le filtre n'est pas appliqué sur le treks.geojson global qui prend toutes les randos = NOK
Par contre le filtre est appliqué au niveau du détail des randos, il ne génère un dossier par rando que pour celles correspondant au filtre = OK

**Comment by camillemonchicourt** [comment]
Il me semble aussi qu'il récupère les contenus des Contenus touristiques associés aux itinéraires même si ces contenus touristiques ne sont pas associés au portail ciblé.

**Comment by LePetitTim** [comment]
#1942

**Comment by camillemonchicourt** [comment]
J'ai migré en version 2.27.1 puis relancé une sync_mobile.
J'ai toujours toutes les randos dans le treks.geojson et pas seulement celles du portail cible.
Et il y a aussi toujours tous les contenus touristiques associés aux randos, mais pas au portail cible. De ce fait, ils ne devraient pas être remontés.

**Comment by camillemonchicourt** [comment]
Je suis passé en 2.27.6 puis j'ai relancé une synchro : 

```
./bin/django sync_mobile -v2 --portal="Rando Ecrins" /home/myuser/datamobile/
```

Après les corrections de la 2.27.4, mon fichier ``datamobile/fr/treks.geojson`` ne contient bien plus que les randos associées au portail souhaité. Merci.

Il me reste à re-tester le comportement pour les contenus touristiques qui n'étaient pas filtrés par portail non plus.

**Comment by camillemonchicourt** [comment]
Testé, c'est OK désormais pour la liste des randos filtrées par portail. 
Mais pas les contenus touristiques qui ne sont pas filtrés par portail

**Comment by LePetitTim** [comment]
Version 2.26.0 fix the bug

**Comment by camillemonchicourt** [comment]
Pour les randos oui, elles sont maintenant bien filtrées par portail. 
Mais d'après mes tests, pas au niveau des contenus touristiques associés aux randos. 
On est en 2.27.9 et on a toujours tous les contenus touristiques de tous les portails dans la synchro mobile.

**Comment by camillemonchicourt** [comment]
OK dans la 2.75.0.
