### ISSUE TITLE
Image watermark

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1945]
La version 2.27.0 ajoute la possibilité d'ajouter un watermark automatiquement sur les photos uploadés : https://github.com/GeotrekCE/Geotrek-admin/pull/1930/files

Ce que je comprends du code est que ce Watermark est généré à partir du titre et de l'auteur de la photo qui sont ajoutés en texte sur celle-ci, avec 2 paramètres ``THUMBNAIL_COPYRIGHT_FORMAT`` et ``THUMBNAIL_COPYRIGHT_SIZE``. 

Cela n'ajoute pas un logo ou visuel sur les photos ?
Et je ne comprends pas comment on active/désactive ce watermark sur les médias uploadés ?

**Comment by LePetitTim** [comment]
Ca n'ajoute par default que le titre et l'auteur. Il est possible de le désactiver en ne mettant rien dans Format (chaîne vide).

**Comment by camillemonchicourt** [comment]
OK pas vu lors de mes tests sur http://geotrekdemo.ecrins-parcnational.fr

**Comment by camillemonchicourt** [comment]
Je viens de passer mon serveur de prod en 2.27.1 puis j'ai lancé un sync_mobile.

Au bout d'une moment, j'ai cette erreur que je n'avais pas en 2.26 : 

```
OSError: [Errno 36] File name too long: '/home/geotrek/Geotrek-admin-2.27.1/var/media/paperclip/trekking_poi/903925/la-pyramide-de-laurichard-et-la-reserve-naturelle-du-combeynot-avant-le-demantelement-des-teleskis.jpg.800x800_q85_size_watermark-15_text-La Pyramide de Laurichard et la r\xc3\xa9serve naturelle du Combeynot avant le d\xc3\xa9mantelement des t\xc3\xa9l\xc3\xa9skis Eric Vannard - PNE.jpg'
```

De ce que je comprends, c'est du au watermark ?
Et du coup, j'en comprends que le watermark est inséré au moment de la synchro, pas à l'upload ? C'est pour ça que je le voyais pas sur les images après les avoir uploadé ?

**Comment by camillemonchicourt** [comment]
Pour les noms de fichiers trop longs, en cours de correction : https://github.com/GeotrekCE/Geotrek-admin/pull/1965

**Comment by LePetitTim** [comment]
Par défault plus de watermark sur : #1961

**Comment by camillemonchicourt** [comment]
Après passage en 2.27.6, j'ai relancé une synchro_mobile, à priori je n'ai plus de nom trop long qui bloque.

Les noms des fichiers ont évolué depuis la 2.27.3 (``Replace text by an id in url of pictures with watermarks``). Exemple : 

```
--AVANT
data/nolang/955154/media/paperclip/tourism_touristiccontent/1600/5043886.jpg.800x800_q85_size_watermark-15.jpg
data/nolang/962542/media/paperclip/tourism_touristiccontent/1745/sortie_chamois_en_raquette-5.jpg.800x800_q85_size_watermark-15.jpg

--APRES
data/nolang/955154/media/paperclip/tourism_touristiccontent/1600/5043886.jpg.800x800_q85_watermark-d41d8cd98f00b204e9800998ecf8427e.jpg
data/nolang/962542/media/paperclip/tourism_touristiccontent/1745/sortie_chamois_en_raquette-5.jpg.800x800_q85_watermark-d41d8cd98f00b204e9800998ecf8427e.jpg
```

Et le watermark sur les images n'est donc plus activé par défaut, mais à ajouter en conf avancée si on le souhaite (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L654-L658)

**Comment by camillemonchicourt** [comment]
Pour revenir sur ce sujet ancien.

La possibilité d'ajouter des watermarks sur les images utilisant leurs titres, auteurs et/ou légende, a été intégrée en 2019.
Documentation : https://geotrek.readthedocs.io/en/master/advanced-configuration.html#copyright-on-pictures

Par défaut, aucun watermark n'est appliqué sur les images : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L752

Le système est utilisé par les commandes de synchronisation des contenus vers Geotrek-rando v2 et Geotrek-mobile. 
Même si aucune watermark n'est configuré, les images ont quand même un nom ajoutant la mention ``watermark`` suivi d'un UUID, car c'est uniquement qu'il y a un watermark mais qu'il est vide.

Les images avec un watermark sont aussi utilisées par l'API XML Cirkwi, corrigé en décembre 2021 par https://github.com/GeotrekCE/Geotrek-admin/pull/2850.

Je pensais que le système de watermark n'était utilisé que par les mécanismes de synchronisation (#1945).
OK donc il est aussi utilisé sur les images servis dans l'API Cirkwi.
Les images watermarkées ne sont pas utilisées actuellement dans l'API v2.

Ça serait intéressant de pouvoir les utiliser dans l'API v2, mais avant cela, je pense qu'il faut revoir la manière dont on l'active ou non, avec un paramètre dédié.
Et ainsi ne pas fournir des noms de fichiers rallongé avec ...watermark... quand il n'est pas utilisé.
