### ISSUE TITLE
Smaller zoom level

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1953]
Il serait utile de pouvoir plus zoomer dans Geotrek-admin. 
Le niveau maximum actuel est souvent insuffisant pour localiser un objet précisément. 
Idéalement définir ce niveau de zoom max dans la configuration si certains souhaitent l'ajuster.

**Comment by jeromesourdin** [comment]
Je suis d'accord ! J'étais en train de chercher comment faire, mais si je comprends bien, c'est une demande d'évolution ?

**Comment by camillemonchicourt** [comment]
Oui mais à priori c'est déjà possible avec le paramètre LEAFLET_CONFIG['MAX_ZOOM'].

Voir la liste des paramètres sur https://geotrek.readthedocs.io/en/master/advanced-configuration.html#global-settings

**Comment by gutard** [comment]
Oui, le souci c'est que certains fonds ne s'affichent plus lorsqu'on dépasse un certain zoom et les gens pensent qu'il y a un bug. Mais je crois qu'il y a une astuce pour dire à Leaflet d'upscaler.

**Comment by camillemonchicourt** [comment]
Oui, je confirme, je viens de passer le paramètre ``LEAFLET_CONFIG['MAX_ZOOM']=20`` dans le fichier ``geotrek/settings/custom.py``, puis lancé un ``sudo supervisorctl restart all`` pour appliquer le changement, sur le serveur de démo http://geotrekdemo.ecrins-parcnational.fr (demo / demo).

On peut y zoomer plus, mais ni les flux des fonds IGN, ni les fonds OSM ne sont disponibles à ces niveaux de zoom.

**Comment by jeromesourdin** [comment]
Oui, j'avais fait ça, mais on ne peut pas dépasser le zoom 18 alors que les fonds IGN peuvent aller à jusqu'à 21 (si j'ai bien compris)

**Comment by gutard** [comment]
Il y a aussi un zoom max individuel pour chaque fond :

```
LEAFLET_CONFIG['TILES'] = [
    ('IGN'), '//wxs.ign.fr/…', {'attribution': '© IGN', 'maxZoom': 21}),
]
```

**Comment by jeromesourdin** [comment]
J'ai trouvé : {'attribution': '© IGN Geoportail', 'maxZoom': 21, 'maxNativeZoom':19}
ça reste jusque au zoom 21 mais c'est flou !
