### ISSUE TITLE
Could not update data error

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#1957]
Echec de mise à jour Geotrek-admin version 2.21.0
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/3192003/install.log)
 vers la 2.27.1

AttributeError: SMTP instance has no attribute 'sock'
Makefile:99: recipe for target 'update' failed

install.log en pj. Est-ce qu'il s'agit du fait qu'il y a eu trop de changements de l'admin entre ces deux versions et que je dois faire des mises à jours intermédiaires ?

**Comment by camillemonchicourt** [comment]
Hormis certains cas particuliers identifiés et indiqués dans les notes de version, il n'est pas utile de passer par les versions intermédiaires. 
Django s'occupe des évolutions de BDD en identifiant les évolutions successives à y apporter. 
Mais là, tu as un problème de BDD à identifier.

**Comment by gutard** [comment]
J'ai peut-être pas regardé très attentivement mais je vois pas d'erreur dans le install.log. Je ne pense pas que ce install.log corresponde à la tentative qui a affiché "Could not update data".

AttributeError: SMTP instance has no attribute 'sock' signifie que Geotrek n'a pas réussi à envoyer un mail. Il faut installer un serveur SMTP local ou configurer un SMTP externe dans etc/settings.ini

**Comment by camillemonchicourt** [comment]
Le log dit aussi : 
```
+ psql geotrekdb -h localhost -p 5432 -U geotrek -c 'SELECT * FROM django.south_migrationhistory;'
ERROR:  relation "django.south_migrationhistory" does not exist
```

**Comment by gutard** [comment]
Oui. Et ?

**Comment by camillemonchicourt** [comment]
Je pensai que c'était peut-être ça son problème...

**Comment by gutard** [comment]
Une erreur n'est pas forcément une erreur. Ici on teste la présence d'une table pour savoir si il est nécessaire de faire une opération spéciale lors de la mise à jour. Comme la table n'existe pas c'est que tout va bien et qu'il n'y a rien à faire.

**Comment by camillemonchicourt** [comment]
OK ! merci pour l'info
