### ISSUE TITLE
Related treks displays deleted treks

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1964]
In TREK form, in the related treks field, the list displays Deleted treks (``supprime=true``).

![image](https://user-images.githubusercontent.com/4418840/58151859-43a8ed80-7c6b-11e9-8661-d984eeb02026.png)

**Comment by LePetitTim** [comment]
Fixed in version 2.27.11

**Comment by camillemonchicourt** [comment]
Thanks
