### ISSUE TITLE
Fuse paths broken ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1967]
Since a few versions, when trying to fuse 2 paths, we get this message : "Vous ne pouvez pas fusionner deux tronçons qui intersectent un troisième tronçon".

However I am just trying to fuse 2 connected paths : 
![image](https://user-images.githubusercontent.com/4418840/58207904-e8ffa800-7ce3-11e9-9f8e-28d4e01ab07e.png)

**Comment by camillemonchicourt** [comment]
En continuant les tests, il me semble que la fusion fonctionne uniquement quand les 2 tronçons sont en bout de ligne. Pas quand les 2 tronçons à fusionner sont entre d'autres tronçons. 

Car dans cet exemple, je peux fusionner B et C avec Geotrek-admin, mais j'ai le message évoqué ci-dessus si j'essaie de fusionner A et B : 

![image](https://user-images.githubusercontent.com/4418840/58211517-721add00-7cec-11e9-9115-f5b782f8bf8a.png)

Par contre une fois que j'ai fusionné B avec C, alors je peux fusionner le tronçon résultant avec A.

Ce fonctionnement a été ajouté il y a quelques versions (https://github.com/GeotrekCE/Geotrek-admin/commit/8725ef24bd0bd49aa0bf3f19b0e21b7511565c27) mais cela semble un effet de bord car on devrait toujours pouvoir fusionner A et B.

**Comment by LePetitTim** [comment]
Version 2.28.0
