### ISSUE TITLE
Delete attached file dont remove it from host

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1968]
When removing an attached file from an object with Geotrek-admin UI, the file is no more listed in attached file, but the file is still in the folder ``/home/myuser/Geotrek-admin/var/media/paperclip``.

**Comment by Cynthia-Borot-PNE** [comment]
It's very important to destroy the file saved on the server however, the synchronization task will take more and more time, and data more and more space on the Geotrek-rando server !!

**Comment by camillemonchicourt** [comment]
These files are removed from database so they are not included in the synchronization process nor in the data sent to Geotrek-rando

**Comment by babastienne** [comment]
The command `clean_attachments` has been developed to fix this problem. It is recommended to run this command regularly. 

[Documentation](https://geotrek.readthedocs.io/en/2.101.4/install/import.html#delete-attachment-from-disk)
