### ISSUE TITLE
Fix order Logentry

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#1973]
![Capture d’écran de 2019-05-28 11-10-01](https://user-images.githubusercontent.com/26329336/58466035-31cabd00-8139-11e9-965c-4f162d8138f4.png)

**Comment by camillemonchicourt** [comment]
Yes date is in text so it is alphabetical order. 
Would be great to have a real DESC DATE order.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.82.0.
Il serait certainement plus pertinent de les ordonner dans l'autre sens, avec les événements les plus récents en haut de liste sur la première page.
