### ISSUE TITLE
Droit export

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1977]
J'ai ajouté des utilisateurs en leur donnant le droit de faire des exports, mais les boutons le permettant ne s'affiche pas dans l'interface sur l'écran de la liste paginée (mais il est possible de faire l'export individuel sur chaque fiche). Entre autre j'ai créé un utilisateur qui faisait parti du groupe "REFERENT COMMUNICATION" (sans modification de droit pour ce groupe et donc qui dispose en particulier du droits "trekking | itinéraires | can export trek"). Ce dernier ne dispose pas des boutons pour faire l'export de la liste, par contre si je rentre manuellement le lien (je le copie à partir d'un autre navigateur où je suis connecté en tant que super utilisateur), le téléchargement se fait sans soucis.

Du coup comment afficher les boutons d'export dans la liste paginée pour un utilisateur "lambda" ?

**Comment by GuillaumeBoitel** [comment]
En fait il y a un petit soucis de mise en page. Les boutons sont bien présent mais sous le niveau de la carte. Il faut donc utiliser l’ascenseur pour les voir.

**Comment by camillemonchicourt** [comment]
Une capture écran du problème de mise en page ?

**Comment by GuillaumeBoitel** [comment]
L'écran tel qu'on le voit :
![Capture01](https://user-images.githubusercontent.com/48252187/59020926-3125db00-884b-11e9-9d13-8d5e2da4af7f.PNG)
L'écran avec un petit coup d'ascenceur :
![Capture02](https://user-images.githubusercontent.com/48252187/59020924-3125db00-884b-11e9-8692-bc7be1fefac0.PNG)

**Comment by camillemonchicourt** [comment]
Ah OK, sur un petit écran la pagination / export / recherche passe sur 3 lignes, ce qui doit entrainer cela. 
Le responsive serait à améliorer du coup.
En lien avec d'autres tickets remontés sur des problèmes de scroll.
