### ISSUE TITLE
non affichage de boutons sur la carte ajout d'itinéraire sur IE

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1978]
Sous IE (version 11) les boutons d'ajout de point de références ou d'emplacement de parking lors de l'ajout ou de la modification d'itinéraires n'apparaissent pas sur la carte. Ça marche par contre sans soucis sous Firefox et Chrome.

**Comment by camillemonchicourt** [comment]
OK en effet, j'ai reproduit. 
J'avoue que ça fait longtemps qu'on n'a pas testé Geotrek-admin sous IE, car on n'a pas d'utilisateurs et les performances sont vraiment atroces avec IE.

**Comment by babastienne** [comment]
IE version 11 n'est plus supporté et la migration sous Edge est recommandée. Nous ne supportons donc plus ce navigateur. Il semble d'après mes tests que de toute manière l'essentiel de la navigation ne fonctionne pas sous IE.
Cependant sous la dernière version de Edge cela fonctionne correctement.
