### ISSUE TITLE
filtre contenu touristique

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1979]
Sur la liste paginée du contenu touristique, si on filtre sur une catégorie à partir du bouton filtre, la barre d’icônes des catégories (sur son côté gauche) ne se met pas à jour. Du coup on a pu filtrer sur une catégorie mais c'est une autre catégorie qui est en surbrillance dans cette barre. Le contenu lui est bien filtré mais ça peut engendrer de la confusion pour l'utilisateur. 

Par contre l'inverse marche bien, si je sélectionne une autre catégorie dans la barre d'icône, alors la catégorie dans le bouton filtre se met bien à jour.

Version Geotrek-rando 2.24.7

**Comment by camillemonchicourt** [comment]
Oui, reproduit sur Geotrek-admin 2.27.1.
Doit-on garder ces filtres de catégorie présents en haut de liste ?
Pratique mais redondant avec le filtre Catégorie dans le menu Filtre, et donc incomplet.

**Comment by LePetitTim** [comment]
#1981

**Comment by LePetitTim** [comment]
Ca n'existait pas avant, je viens de verifier.

**Comment by camillemonchicourt** [comment]
Fixed in 2.27.7
