### ISSUE TITLE
contenu touristique sous chrome

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1980]
Depuis que j'ai importé des données Esprit Parc, la liste paginée du contenu touristique a du mal à s'afficher sous chrome (74.0.3729.169). La carte ne s'affiche pas et j'ai le "témoin" de chargement qui tourne dans le vide. Si je sélectionne une commune ou un secteur, la carte s'affiche (avec des points indiquant les contenus) mais la liste reste vide.

Avant l'import Esprit parc, j'avais importé des données d'Apidae et je n'avais pas de soucis d'affichage. 
Pas de soucis sous Firefox ou IE11 avant ou après l'import Esprit Parc.

Version geotrek-admin 2.24.7

**Comment by GuillaumeBoitel** [comment]
En regardant dans la console javascript de Chrome j'ai cet erreur, je ne sais pas si c'est lié et si ça peut aider :

```
Uncaught TypeError: Cannot read property 'sSortDataType' of undefined
    at _fnSort (88eff922f27a.js:1490)
    at init.DataTable.fnSort (88eff922f27a.js:1871)
    at Object.self.restoreFullContext (88eff922f27a.js:648)
    at 88eff922f27a.js:637
    at dispatch (jquery.min.js:3)
    at i (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at jquery.min.js:3
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
```

**Comment by camillemonchicourt** [comment]
On importe des données Esprit parc depuis longtemps et on n'a pas ce problème. 
Tu dois avoir importé un ou plusieurs produits pour lesquels il manque une info (le type ?) qui empêche le tri de la liste ?

**Comment by GuillaumeBoitel** [comment]
Ce qui m'étonne c'est que le soucis ne se produit que sous chrome. Sous firefox tout va bien. Du coup je pense que le problème n'est pas côté serveur mais plutôt dans du code javascript mal interprété par chrome.

----- Mail original -----
De: "Camille Monchicourt" <notifications@github.com>
À: "GeotrekCE/Geotrek-admin" <Geotrek-admin@noreply.github.com>
Cc: "GuillaumeBoitel" <guillaume.boitel@portcros-parcnational.fr>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 5 Juin 2019 21:33:07
Objet: Re: [GeotrekCE/Geotrek-admin] contenu touristique sous chrome (#1980)

On importe des données Esprit parc depuis longtemps et on n'a pas ce problème. 

Tu dois avoir importé un ou plusieurs produits pour lesquels il manque une info (le type ?) qui empêche le tri de la liste ?

**Comment by camillemonchicourt** [comment]
Oui mais dans tous les cas, il faut regarder si il n'y a pas un truc qui cloche avec certains contenus qui seraient incomplets (type manquant notamment ?)

**Comment by GuillaumeBoitel** [comment]
J'ai bien des catégories pour chaque contenu mais pas forcément de type d'usage et type2. Cependant je n'avais pas non plus ces deux types pour les imports apidae (mais toujours une catégorie) et ça fonctionnait sous chrome.

**Comment by camillemonchicourt** [comment]
OK, je sais pas alors.

**Comment by babastienne** [comment]
@GuillaumeBoitel est-ce que ce bug est toujours d'actualité ? Si non comment a-t-il été résolu ? Merci d'avance pour votre retour.
