### ISSUE TITLE
Problème de synchronisation 2.27.1

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#1987]
Bonjour,

J'ai un erreur récurrente qui empêche la synchronisation de certains itinéraires sur plusieurs Geotrek-admin synchronisant sur un portail rando de version 2.20.0-ux3.

Voici une exemple l'erreur (le fichier log est en pj) : 

WARNING 2019-06-12 10:49:05,082 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/32724/24096.png

[synch_rando.log](https://github.com/GeotrekCE/Geotrek-admin/files/3280676/synch_rando.log)

**Comment by gutard** [comment]
C'est un problème de téléchargement des tuiles pour le fonctionnement offline de l'app mobile.
Ça peut être :
- absence ou mauvaise valeur pour l'option --url de sync_rando
- problème de clé IGN (si tuiles IGN)
- mauvais paramétrage de MOBILE_TILES_URL (le paramétrage par défaut est OSM et semble poser problème depuis quelques temps car il détecte un téléchargement depuis un serveur et non un navigateur et le refuse)
- tuile non disponible (par ex. en dehors de la France pour l'IGN)

**Comment by camillemonchicourt** [comment]
J'ai aussi pas mal de messages de ce type depuis quelques temps, en Geotrek-admin 2.27.1.

```
...
** zip/tiles/965963.zip unchanged
** zip/tiles/966026.zip ...WARNING 2019-06-23 22:06:28,843 geotrek.trekking.management.commands.sync_rando Failed to download tile 15/16979/11808.png
WARNING 2019-06-23 22:06:28,878 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33958/23617.png
WARNING 2019-06-23 22:06:28,911 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33959/23617.png
unchanged
** zip/tiles/966622.zip ...WARNING 2019-06-23 22:06:29,018 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33950/23623.png
WARNING 2019-06-23 22:06:29,056 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33949/23622.png
WARNING 2019-06-23 22:06:29,084 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33949/23623.png
WARNING 2019-06-23 22:06:29,115 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33951/23625.png
WARNING 2019-06-23 22:06:29,153 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33950/23624.png
WARNING 2019-06-23 22:06:29,180 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33948/23623.png
unchanged
** zip/tiles/966624.zip ...WARNING 2019-06-23 22:06:29,322 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33949/23623.png
WARNING 2019-06-23 22:06:29,361 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33949/23622.png
WARNING 2019-06-23 22:06:29,393 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33950/23623.png
WARNING 2019-06-23 22:06:29,429 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33950/23624.png
WARNING 2019-06-23 22:06:29,456 geotrek.trekking.management.commands.sync_rando Failed to download tile 16/33948/23623.png
unchanged
** zip/tiles/966626.zip unchanged
...
```

Dans mon ``custom.py`` : 

```
MOBILE_TILES_URL = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
```

En effet en passant sur OpenTopoMap, je n'ai plus le problème (``MOBILE_TILES_URL = 'http://a.tile.opentopomap.org/{z}/{x}/{y}.png'`` dans ``custom.py``.

Ce fond OSM incluant le relief est d'ailleurs plus adapté en montagne notamment comme évoque ici : https://github.com/GeotrekCE/Geotrek-mobile/issues/191

Le problème semble donc bien venir du serveur de base OSM qui bloque les appels de tuile depuis un serveur.

Modifier le paramètre ``MOBILE_TILES_URL`` par défaut en passant de OSM à OTM ?

**Comment by mviadere-openig** [comment]
Bonjour, la solution apportée par camille semble fonctionner, merci.
