### ISSUE TITLE
Echec d'import d'aménagement avec la commande loadinfrastructure et l'argument --structure_field

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1994]
Lors d'une tentative d'import d'aménagement avec la commande django loadinfrastructure :
` ./bin/django loadinfrastructure -n nom -t type -c etat -d descriptio -s struct ../data/shp/amenagement.shp`

 j'obtiens une erreur lorsque j'utilise le paramètre  --structure-field : 
`Structure None set in options doesn't exist`

J'utilise en entrée un shapefile qui contient bien un champ les champs etat, descriptio et struct.

J'ai fait quelques tests sur le fichier  Geotrek-admin/geotrek/infrastructure/management/commands/loadinfrastructure.py.
A priori c'est l'appel à ` Structure.objects.get(name=structure_default)` (ligne 102) qui pose soucis car dans mon cas puisque j'ai les informations concernant la structure dans le shapefile je n'ai pas précisé de structure par défaut donc structure_default est non renseigné.
Si on modifie le else de la ligne 100 par "`elif not field_structure_type and structure_default", alors ça fonctionne.

**Comment by GuillaumeBoitel** [comment]
On a bien entendu le même soucis avec la commande loadsignage.

**Comment by gutard** [comment]
Merci @GuillaumeBoitel. Tu as fait l'essentiel du travail. Il ne te reste plus qu'à proposer une pull request (en adaptant les tests automatisés). Si c'est OK on intégrera ton fix dans le prochaine release.

**Comment by LePetitTim** [comment]
J'ai commencé à modifier les tests sur la pull request on voit bien qu'il y a une erreur :)
https://github.com/GeotrekCE/Geotrek-admin/pull/1997

**Comment by LePetitTim** [comment]
Version 2.28.0
