### ISSUE TITLE
Création en doublon des types d'infrastructure lors de l'import par loadinfrastructure

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#1996]
Comme pour les conditions (#1995), on a une création en doublon des types lors de l'import d'aménagement par la commande loadinfrastructure.

Il faut non seulement faire la même genre de modification que celle proposée pour les conditions (voir #1995) mais aussi bien gérer la catégorie (Equipement ou Ouvrage) d'aménagement. Dans le fichier geotrek/infrastructure/management/commands/loadinfrastructure.py la catégorie d'aménagement est fixé à 'B' (ligne 166) d'office. 
Il faudrait pouvoir disposer d'option supplémentaire pour la commande pour signaler la catégorie par défaut et le champs qui l'indique dans la base afin de fixer ce champs à 'A' (ouvrage) ou 'E' (equipement) en fonction de la catégorie d'aménagement.

**Comment by gutard** [comment]
Merci @GuillaumeBoitel. Tu as fait l'essentiel du travail. Il ne te reste plus qu'à proposer une pull request (en adaptant les tests automatisés). Si c'est OK on intégrera ton fix dans le prochaine release.

**Comment by babastienne** [comment]
Ok à priori problème résolu via la PR proposée. Je clôture.
