### ISSUE TITLE
Question : comment ne pas afficher les signalétiques sur les pdf

### ISSUE THREAD

**Issue by GuillaumeBoitel** [GeotrekCE/Geotrek-admin#2008]
J'aimerais ne pas afficher les signalétiques sur les cartes des itinéraires.

J'ai mis dans custom.py la variable SHOW_SIGNAGES_ON_MAP_SCREENSHOT à False, mais de toute évidence ça ne suffit pas.
 
Avant de faire la synchro j'ai vidé le répertoire var/media/maps/ des fichiers trek-*.png pour être sur qu'il ne garde pas les anciennes images. Les nouvelles ont également la présence des étiquettes de signalétiques :
![trek-14978-fr](https://user-images.githubusercontent.com/48252187/60601009-9b319180-9db1-11e9-9811-ef3664c75aa0.png)

Des idées ?

**Comment by gutard** [comment]
Il manque un redémarrage du serveur. Sinon les changements dans custom.py ne sont pas pris en compte (ils le sont dans la commande sync_rando car c'est un nouveau démarrage mais les screenshots sont fait par le serveur principal). Et il faut effectivement vider le cache manuellement.

**Comment by GuillaumeBoitel** [comment]
J'avais bien fait la relance du serveur avec 
`sudo supervisorctl restart all`
J'ai même été jusqu'à redeployer l'application avec ` make env_standalone deploy`
