### ISSUE TITLE
Zones sensibles et pdf

### ISSUE THREAD

**Issue by alizeelamarque** [GeotrekCE/Geotrek-admin#2010]
Bonjour,

Nous avons ajouté des zones sensibles via Biodiv'Sports. Elles s'affichent bien sur G.Admin et G.Rando mais lors de l'export du pdf, elles ne figurent pas sur la carte (la variable SHOW_SENSITIVE_AREAS_ON_MAP_SCREENSHOT est bien sur true) et dans certains itinéraires ([Varambon et grand Crêt d'Eau par exemple](http://randonature.parc-haut-jura.fr/randonnee/varambon-et-grand-cret-deau/)), les informations sur la zone sensible apparaissent plusieurs fois dans la fiche (23 fois pour cet exemple).

**Comment by gutard** [comment]
Il faut peut-être vider le cache car les cartes ne se régénèrent pas automatiquement lorsqu'on change un paramètre de configuration. Pour cela, de mémoire, il faut tout simplement supprimer le contenu du répertoire var/media/maps/

**Comment by alizeelamarque** [comment]
Après avoir vidé le cache, j'ai bien les zones sensibles qui s'affichent. Par contre, les informations sur la zone sensible sont toujours en une vingtaine d'exemplaires.

**Comment by LePetitTim** [comment]
Depuis la version 2.29.12, les zones devraient ne plus s'afficher en beaucoup d'exemplaire.

Je te conseille donc de passer en version 2.29.12.
