### ISSUE TITLE
META - Use summary as trek description

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2016]
It would be more relevant to use Summary field as ``description`` instead of ``ambiance`` field as actually (view-source:https://rando.ecrins-parcnational.fr/meta/fr/a-pied/de-chabourneou-a-vallonpierre-par-le-sentier-du-ministre/).

On its side Geotrek-rando uses Summary as ``description``.

**Comment by babastienne** [comment]
@camillemonchicourt I'm not sure to understand this issue. Is it still relevant ? If so can you add more information ? Is it a suggestion to rename the field "ambiance" into "summary" ?

**Comment by camillemonchicourt** [comment]
No it was in metadata files for SEO generated during synchronization for Geotrek-rando V2.
Not relevant anymore.

In Geotrek-rando V3, meta informations for SEO are managed on Geotrek-rando side.
