### ISSUE TITLE
Meta - Title in Flatpages

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2017]
``{{ object.name }}`` seems to dont work in Flatpages templates (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/flatpages/templates/flatpages/flatpage_meta.html) as it is always empty : view-source:https://rando.ecrins-parcnational.fr/meta/fr/informations/transport/

**Comment by LePetitTim** [comment]
Yes indeed, it should be : {{ object.title }}
In the model, there are : title, external_url, content, target, source, portal, order, published, publication_date, date_insert and date_update. No object.name here.

**Comment by camillemonchicourt** [comment]
See https://github.com/GeotrekCE/Geotrek-admin/pull/2083
