### ISSUE TITLE
Problème de fond de carte lors de la récupération de fiche d'itinéraires

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2022]
Geotrek-admin : 2.27.10
Geotrek-rando : 2.20.0-ux3

Depuis la mise à jour vers la 2.27.10, lorsqu'un itinéraire a été créé et publié, le fond de carte ign s'affiche correctement au niveaux de l'admin et du rando, mais ne s'affiche pas lorsque l'ont télécharge le pdf, que ce soit sur l'admin où le rando.

[les-corniches-du-mejean.pdf](https://github.com/GeotrekCE/Geotrek-rando/files/3400885/les-corniches-du-mejean.pdf)

**Comment by camillemonchicourt** [comment]
Problème côté Geotrek-admin, j'y ai transféré l'issue. 
En effet la génération des PDF et des images de carte dans les PDF sont faits au niveau de Geotrek-admin, au moment de la synchronisation. 

Il y a un ticket assez similaire ici qui donne des informations sur le sujet : https://github.com/GeotrekCE/Geotrek-admin/issues/1900

Cependant nous avons le même problème depuis quelques versions de Geotrek-admin et le problème semble différent. 
Car vider le répertoire ``var/media/maps/``en règle pas le problème, l'URL est bien définie dans notre synchronisation et en basculant sur OpenTopoMaps à la place d'IGN on a toujours le même problème.

**Comment by LePetitTim** [comment]
@camillemonchicourt  si tu mets openstreetmap ca va fonctionner.
 Prise sur ton instance : (973768)
![20190717-151023](https://user-images.githubusercontent.com/26329336/61378205-27a97d00-a8a5-11e9-96f5-8a7b31daf0ee.png)

**Comment by camillemonchicourt** [comment]
OK donc ce serait un problème avec les fonds IGN. 

J'avais testé avec OpenTopoMap mais ça ne m'avait pas semblé fonctionner. Je n'avais peut-être pas appliqué le changement comme il faut. 

Pour faire ce changement, il suffit bien de changer l'ordre des couches du paramètre ``LEAFLET_CONFIG['TILES']`` dans le fichier ``geotrek/settings/custom.py`` puis d'appliquer le changement avec ``sudo supervisorctl restart all`` ?

**Comment by LePetitTim** [comment]
Pour le screenshot que tu vois la, j'ai juste choisis OSM et j'ai fait un screenshot avec l'appareil photo. De la meme manière pour les pdfs il utilise l'appareil photo mais toujours avec la première.

De mon côté, j'essaye de trouver pourquoi les fonds IGN et autres ne fonctionne pas.

**Comment by Cynthia-Borot-PNE** [comment]
Est-ce que cela pourrait venir du fait que notre admin n'est pas en https alors que l'IGN oui ? OSM et OpenTopoMap étant en http ...

**Comment by Cynthia-Borot-PNE** [comment]
Je confirme que la génération des cartes pour les exports PDF fonctionne bien avec 
- OSM. 
Cependant elle disfonctionne avec :
- les fonds IGN
- OpenTopoMap

**Comment by LePetitTim** [comment]
Alors non pour https car nous sommes en https et nous avons le meme probleme.

**Comment by LePetitTim** [comment]
#1938

**Comment by camillemonchicourt** [comment]
OK merci. 
Je suis passé en 2.29.1 et cela règle bien le problème pour les différents fonds (OSM, IGN, OpenTopoMap)
