### ISSUE TITLE
Impression PDF public - A5 livret

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2050]
Dans la V1 de Geotrek-rando, le PDF généré automatiquement par Geotrek-admin était au format A5, sur la base d'un gabarit ODT. 
Exemple :  http://rando1.ecrins-parcnational.com/fr/files/api/trek/trek-903486.pdf

Le format avait notamment été discuté ici :  https://github.com/GeotrekCE/Geotrek-admin/issues/1163

Lors de la V2, la génération automatique des PDF publics est passée sur un mécanisme plus souple, basé sur des gabarits HTML, plus facilement personnalisables. A cette occasion ils sont aussi passés sur un format A4.

Même si l'utilisateur final peut décider de ne pas imprimer toutes les pages (pages POI par exemple) ou d'imprimer son PDF en livret A5, peu d'utilisateurs maîtrisent ces fonctionnalités de leurs imprimantes. 

Proposer une version plus compacte et plus légère est donc un besoin qui a déjà été évoqué.

La Communauté de Communes Cœur et Coteaux Comminges qui a lancé son Geotrek-rando récemment (https://rando.coeurcoteaux-comminges.fr) propose de travailler sur une format plus condensé pour l'impression PDF : 

[PDF-Geotrek-CCCCC.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/3545626/PDF-Geotrek-CCCCC.pdf)

Malgré tout la question des PDF reste complexe, car ils sont générés automatiquement. 
C'est une vraie plus-value, mais cela a aussi des limites par rapport à des PDF qui seraient fait sur mesure, à la main, rando par rando.
Notamment du fait que les contenus sont variables d'une rando à une autre, mais doivent rentrer dans un gabarit commun. 

A noter que depuis la version 2.28.0 (https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.28.0), il est possible de forcer un PDF chargé manuellement au niveau d'une rando poru proposer un PDF sur mesure, au lieu de celui généré automatiquement. 

Je vois plusieurs possibilités : 

- Remplacer le gabarit actuel par un gabarit A5 livret mais avec toutes les infos comme actuellement
- Garder le gabarit actuel et en ajouter un autre A5 et plus léger, avec moins de contenu. Ajouter une option au niveau de Geotrek-admin définissant quel gabarit utiliser pour les PDF
- Garder le gabarit actuel et en ajouter un autre A5 et plus léger, avec moins de contenu. Proposer les 2 PDF à l'internaute final

Il y en a peut-être d'autres ?

**Comment by JonathanALLAIN** [comment]
Bonjour à tous,

Je relance ce sujet après avoir consulté la CCCCC qui l'avait amorcé. Visiblement ils n'ont pas été au bout de la démarche. De notre côté le besoin de pouvoir télécharger un PDF sur une seule et unique feuille A4 (en format livret A5 recto-verso) pour avoir un petit topo papier complet s'est fait très fortement ressentir notamment chez les OT, les hébergeurs, les pro en général à destination du randonneur occasionnel qui est un public très important chez nous. Le papier reste très demandé.

L'export actuel par défaut propose un pdf avec la plupart du temps trop de pages en A4 portrait (dès lors que la rando est un minimum renseignée avec un "pas à pas" complet, des POI... il peut y avoir 5, 6 pages) : pas ergonomique, pas écologique du tout, trop hétérogène en fonction des randos.

**Objectifs :**
- pouvoir imprimer un topo papier, compact proposant les infos essentielles pour le randonneur dans un format unique quelle que soit la rando en livret recto-verso A5.
- D'un point de vue du développement, que ce gabarit ne soit pas personnalisé "PNR du Perche" mais qu'il reprenne l'esprit du pdf actuel mais compacté et que toutes structures puissent l'utiliser.

**Dans l'idée :**
° page 1 : la photo vignette principale et les infos/cotations principales de l'itinéraire (durée, difficulté, longueur, départ, déniv, thème....) ainsi que sa description de présentation
° page 2 et 3 en double page : en page 2 la carte en pleine page avec le tracé, les numéros du "pas à pas", les POI (A, B, C...etc) + sous la carte les pictos et titres des POI (sans leur détail ni photo) 
et en page 3 en face, tout le "pas à pas".
° page 4 : Recommandations, profil alti, accès routier/parking conseillé... infos touristiques, contacts.

**Voir exemple de maquette rapide (non aboutie) ici :** _https://perche.evaparc.net/clients/pnrperche/attachments/project-entity-project/32854/maquette_pdf_A5.pdf_

**Comment by JonathanALLAIN** [comment]
Ce projet peut être porté et financé par le PNR du Perche avec la collaboration de ces Communautés de Communes. Le but est de pouvoir faire quelque chose d'utilisable pour tous et pas un dév "Perche". C'est pourquoi on peut en discuter en amont.

La possibilité pour chaque OT ou autres pros de facturer (<1€?) ces livrets aux touristes (prix de l'encre/papier) n'est pas absurde.

D'un point de vue technique nous travaillons avec Makina. Sur ce principe, ils visualisent très bien le projet, le trouvent pertinent et peuvent le développer.

Enfin, comme évoqué par Camille , proposer ce nouvel export sans supprimer la possibilité de faire l'actuel par défaut est une option intéressante. En effet, ce nouveau support nécessite à l'utilisateur d'imprimer RECTO-VERSO ce qui "impose" une contrainte technique à l'utilisateurs. Selon moi pour les pros, OT notamment ou toutes collectivités ce n'est pas un souci. Pour le particulier qui ne pourrait imprimer recto/verso, au pire cela fera max deux A4 (facilement pliable en 1 livret).

**Comment by thomaspnrhj** [comment]
Salut Jonathan !
De notre côté, on est bien intéressé par ce développement, ça fait depuis quelques temps que les OT nous demandent cette possibilité. Ce que tu proposes semble tout à fait pertinent. 
A plus,
Thomas

**Comment by camillemonchicourt** [comment]
Oui c'est intéressant d'avoir une mise en page compactée et formatée en livret A5. C'est un besoin souvent remonté.

Néanmoins je pense qu'il est pertinent de garder le template actuel et d'en ajouter un autre plus compactée, avec un paramètre permettant de définir au niveau d'une instance Geotrek-admin si on souhaite utiliser un template ou l'autre. On pourra ainsi en prévoir d'autres par la suite. 

De mon côté, je trouve que les POI sans leur description perdent beaucoup de leur intérêt et un export PDF n'induit pas forcément une impression. Sans application mobile, il m'est déjà arrivé de télécharger un PDF sur mon smartphone pour en disposer ensuite hors ligne sur le terrain.
De plus, avec le gabarit actuel, les gens peuvent télécharger le PDF complet mais choisir de n'imprimer que les 4 ou 5 premières pages en mode livret sur 2 ou 3 pages. Exemple https://rando.ecrins-parcnational.fr/api/fr/treks/962594/autour-des-vigneaux-et-de-grand-parcher.pdf
 
Par rapport à l'exemple proposé, il faut vérifier sur différentes randonnées, notamment les plus complètes. Parfois on a aussi des infos sur la source, les transports, plus de POI, des textes plus longs etc... et pas sur que ça rentre forcément dans le gabarit proposé. Il faut voir aussi ce qu'on fait quand on a des randonnées itinérantes. Là il peut y avoir un nombre énorme de POI sur la fiche mère. Et on avait fait un développement permettant de lister les étapes d'une itinérance.

**Comment by JonathanALLAIN** [comment]
Garder le template actuel de pdf me semble aussi nécessaire comme je le précise. En effet pour pouvoir l'embarquer hors ligne sur un tél sans impression et avoir tout. Mais ce besoin repose sur une demande de randonneurs voulant un topo papier ergonomique que leur délivrent facilement les OT ou d'autres pros à qui ils s'adressent.

"_De plus, avec le gabarit actuel, les gens peuvent télécharger le PDF complet mais choisir de n'imprimer que les 4 ou 5 premières pages en mode livret sur 2 ou 3 pages. Exemple https://rando.ecrins-parcnational.fr/api/fr/treks/962594/autour-des-vigneaux-et-de-grand-parcher.pdf_" : là en revanche je pense que le public dont je parle ne va pas faire ça et surtout les pros (OT, hébergeurs) non plus car ce n'est pas du tout efficace. Cela induit, en plus d'un choix de quelle page on garde, des paramétrages imprimante qui sont à mon sens à limiter au max. Et le rendu final n'est pas homogène et simple.

A mon sens il faut garder l'export actuel qui permet d'avoir toutes les infos, mais son usage est clairement numérique en off line sur le tél car sa finalité papier n'est pas du tout qualitative.
Et il faut proposer en plus ce genre de gabarit A5 compact.
Bien évidemment il faut faire du test avec toutes sorte de rando pour voir si ça peut passer. Améliorer la maquette proposée. Mais il est évident que pour la description des POI ça ne colle pas. Pour les infos liées à la mise en tourisme à proximité non plus. Mais ce n'est pas le but il me semble d'un topo compacté.

**Comment by JonathanALLAIN** [comment]
**Pour l'itinérance j'imaginais un livret A5 par étapes** et un livret A5 pour la rando mère (pas forcément utile?) sur laquelle la carte (vu l'échelle) n'a d'intérêt uniquement que le profil géographique général et l’enchaînement des différentes étapes.

**Comment by camillemonchicourt** [comment]
Oui n'imprimer que les premières pages en livret de l'export actuel n'est pas forcément simple pour tout le monde. C'est une demi-réponse. 

J'imaginai qu'il y ait plusieurs templates disponibles mais qu'on n'en selectionne qu'un seul au niveau d'une instance de GeoNature. Sinon ça va être plus complexe, plus long à générer, plus lourd à stocker et complexe pour l'utilisateur de comprendre lequel il veut télécharger. Donc je ne pensai pas pouvoir en activer et proposer plusieurs en même temps sur un même Geotrek.

Pour l'itinérance, si il faut faire des templates spécifiques, c'est surement idéal mais peut-être complexe ?

**Comment by thomaspnrhj** [comment]
Jonathan je sais pas si c'est le cas pour toi mais nous les OT ont accès à G.Admin. De notre côté, on imaginais plus que cette template allégée soit uniquement accessible depuis G.Admin pour que les OT puissent les exporter. Pour le G.Rando, c'est le pdf classique qui remonte.

**Comment by JonathanALLAIN** [comment]
Dans mon idée, il y aurait deux idées de développement : 

**- OPTION 1** : (plus chère, plus complexe notamment au niveau génération et stockage pdf) on développe le template pdf livret A5 allégé et sur Geotrek-admin on permet la possibilité de faire remonter dans Geotrek-rando soit les deux soit un des deux. Dans Geotrek-rando, à l'image de l'onglet "télécharger" qui propose deux possibilité (GPX ou KML), l'onglet "Imprimer la fiche" proposerai deux possibilité (standard ou livret).

**- OPTION 2** : (plus simple) on développe le template pdf livret A5 allégé et sur Geotrek-admin on choisit un des deux qui remontent sur Geotrek-rando (peut-être plus simple comme dit Camille).

Dans les deux cas on offre la possibilité de garder l'actuel PDF.

Nos OT n'ont pas accès à Geotrek-admin. Ici, ce n'est pas un territoire où la randonnée à une place qui permet d'avoir des postes spécifiques dans les collectivités liés à la rando à part les Départements et les PNR. Du coup, nous allons nommer des personnes ressources dans un premier temps qui auront accès à Geotrek-admin pour un travail de veille sur les contenus dans un premier temps mais pas de réelle administration. C'est la prochaine étape. 

Les OT pour nous doivent avoir le template livret PDF A5 actif dans Geotrek-rando et selon moi, les internautes utilisateurs voulant le papier préféreront ce format. En revanche pour ceux désirant embarquer un PDF complet standard en numérique off-line dans leur tél, l'option 1 semble quand même répondre à toutes les demandes.

**Comment by camillemonchicourt** [comment]
Je préfère l'option 2. Choisir c'est renoncer. 😀
Et il ne faut pas trop proposer de choix peu compréhensibles aux utilisateurs.

**Comment by JonathanALLAIN** [comment]
Après si dans Geotrek-admin on peut proposer de faire remonter en front soit :
- pdf actuel standard
- pdf livret A5
- soit les deux

Chacun s'y retrouve. Ceux qui pensent que choisir c'est renoncer ! ne font remonter qu'un seul.
Si le dév peut être pris en charge par Makina et financé par nos CdC ça vaut p'tet le coup de proposer cette option en admin ? 

Je fais un point avec Makina et vous redis.

**Comment by JonathanALLAIN** [comment]
Bonjour,

Makina m'a relancé. Je lui propose l'option 2 avec la possibilité depuis Geotrek Admin de faire remonter soit :
- pdf actuel
- pdf livret A5 allégé
- soit les deux (option 1 mais plus chère et lourde en dév sans doute...)

**Comment by camillemonchicourt** [comment]
OK, testé en 2.38.1 : 
[col-de-font-froide.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/5263943/col-de-font-froide.pdf)

**Comment by camillemonchicourt** [comment]
Testé en 2.38.6. Le document en rentre pas dans un recto verso (2 pages) mais sort sur 4 pages. Avec une page incluant les POI. Et une autre avec les lieux de renseignement : 
[col-de-font-froide_booklet.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/5415009/col-de-font-froide_booklet.pdf)

J'avais pourtant compris que la version livret n'incluait pas les POI pour tenter de rentrer sur 4 pages A5, non ?

**Comment by gutard** [comment]
Il suffit de mettre TREK_EXPORT_POI_LIST_LIMIT = 0 dans les settings

C'est plus souple, ça permet de faire une version livret avec les POI ou une version normale sans. Pour moi il n'y a pas de raison de lier les deux.

**Comment by gutard** [comment]
Par contre dans ton exemple il y a aussi la page "Toutes les infos pratiques" qui déborde. Comme on l'a toujours dit, comme la quantité de texte varie d'une fiche à l'autre, il n'y aura jamais de solution automatique qui permet à tous les coups de ne pas laisser de blanc et de ne pas créer de pages supplémentaires. Le problème est moins présent si on se donne des règles éditoriales du type : entre 500 et 600 caractères pour la descriptions, etc.

**Comment by camillemonchicourt** [comment]
OK je ne me souvenais plus du paramètre ``TREK_EXPORT_POI_LIST_LIMIT``, en effet c'est bien comme ça on peut définir si on intègre des POI ou non.
Et oui pour la page "Toutes les infos pratiques" qui déborde dans mon exemple, pas de solution miracle, c'est normal.
OK donc. Merci pour ce développement et pour les précisions.

**Comment by JonathanALLAIN** [comment]
Salut à tous,

Pour clore sur ce sujet je vous fais le retour des discussions que j'ai eues avec MAKINA CORPUS avec qui nous travaillons sur ce dév.

Pour résumer :
- PDF A5 (A4 recto verso) actif sur notre portail rando. Ca fonctionne très bien.
- PDF standard conservé via l'Admin ce qui était le souhait initial vu avec Camille notamment. Cependant sur le rando un seul sera dispo. Pour nous c'est le format livret A5.
- Possibilité dans les settings de customiser soi-même le PDF A5 (garder la description des POI, le profil alti...) - Nous avons fait le choix de ne pas montrer le profil alti (qui n'apporte rien pour nous) et de n'avoir que les noms des POI sous la carte (géolocalisés avec les lettres A, B, C,... et pas leur description sinon ça ne passe pas.

Après le premier dév, la taille de "police" que nous avions arrêtée pour faire passer un max de nos rando sur le format A5 (c'est souvent le "pas à pas" qui est long et qui fait déborder du format A5) apparaît trop petite (limite de la lisibilité par les utilisateurs). Donc nous refaisons un petit retour en arrière pour caler la taille de "police" à celle du chapeau qui semble acceptable et lisible.

Aussi, nous aurons automatiquement (et malheureusement) davantage de randos qui ne passeront pas dans le format A5. Mais il est clair que si ce format est vraiment satisfaisant niveau gabarit, il n'y a en revanche pas de solutions techniques magiques ou miracles pour que toutes les randos aux tailles de textes très hétérogènes passent toutes. Il est alors important, à partir d'une taille de texte minimale acceptable, de revoir la taille de nos descriptifs et "pas à pas".
