### ISSUE TITLE
Filter list does not keep selected multi-select items after visiting another page

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2068]
Version Geotrek-admin : 2.29.8

I've tested on diving and trekking : the liste is still filtered, but the filter multi-select themes for exemple is no more selected.

How to reproduce:

- I filter on theme (or technic level in diving)
- I visit one of the objects
- I come back by clicking on list link on top left

I've tested with another field type in filter and there it seems to be ok.

(Bug highlighted by CD83)

**Comment by LePetitTim** [comment]
Corrected in 2.29.11

**Comment by camillemonchicourt** [comment]
Thanks.
