### ISSUE TITLE
solution pour les mises à jour de geotrek-admin sur systeme debian

### ISSUE THREAD

**Issue by ybuthion** [GeotrekCE/Geotrek-admin#2069]
_je ne sais pas si je dois mettre cette info ici ou sur le google group, ... je tente ici :
suite à une galère de mise à jour de geotrek-admin en 2.29.5, probesys a rédigé un pas à pas pour les structures qui ont installé leur admin sur une débian plutôt que sur un ubuntu.
bonne lecture
yann_

**_Mise à jour Geotrek-Admin : prise en compte des particularités de Debian_**

Geotrek-admin est développé pour une utilisation sur un serveur Ubuntu.
Ubuntu étant basé sur Debian, la compatibilité ne pose pas de problème
particulier mais demande quelques adaptations.

**Procédure de mise à jour standard**
Disponible sur le[ readthedocs Geotrek](https://geotrek.readthedocs.io/en/master/installation.html#software-update).

La procédure sur Debian est identique, la seule différence est que nous allons éditer le script install.sh
pour le rendre compatible avec un système non-Ubuntu.

**install.sh**
_comprendre le script_

install.sh est un script bash qui réalise les opérations suivantes :
1. vérifie que l’utilisateur n’est pas root (devrait être geotrekadmin ou équivalent)
2. se place dans le dossier où se trouve install.sh
3. définit les variables nécessaires à l’install (n° de version, type de version, emplacement de la config, …)
4. parse les éventuelles options
5. place les logs d’install dans install.log
6. définit les fonctions d’aide et de gestion des erreurs
7. définit les fonctions qui gèreront les différentes étapes de l’install
8. définit la fonction de déroulement du scénario d’install : geotrek_setup
9. Après tout ce travail préparatoire, l’installation à proprement parler :
- détermination de la version du système
- détermination des versions de postgresql et de postgis à utiliser selon la version du système
- exécution de geotrek_setup si le système est compatible

**editer le script et les fichiers de configuration**
Toutes les fonctions intermédiaires du script sont compatibles avec Debian.
On va donc supprimer toute la partie 9 d’install.sh, de :

```
precise=$(grep "Ubuntu 12.04" /etc/issue | wc -l)
trusty=$(grep "Ubuntu 14.04" /etc/issue | wc -l)
[...]
```

à la fin.

On remplace par le code suivant, qui consiste en un petit mensonge (“on est à la dernière version d’Ubuntu”), la définition des versions de postgresql et postgis à utiliser, et l’exécution de geotrek_setup :

```
# nécessaire de préciser la version bionic pour un traitement des
# dépendances python lors de l'install
precise=0
trusty=0
vivid=0
xenial=0
bionic=1

# versions validées sur Ubuntu.
# vérifier la présence sur le système avec :
# apt policy postgresql
# apt policy postgis
psql_version=10
pgis_version=2.4

# lancer l'installation / l'upgrade
geotrek_setup
```

**Gestions des erreurs GDAL**
Lors de l’installation de la 2.29.5 nous avons rencontré des erreurs avec la librairie GDAL v. 2.2.4.
Ces erreurs ont été contournées en installant la librairie depuis la source.
Pour forcer l’utilisation de la version compilée depuis la source, il faut s’assurer de deux choses dans Geotrek-admin-v.x.y.z/conf/buildout.cfg :

- dans la section [versions] : on a bien GDAL=2.2.4
- dans la section [gdal-bindings] assigner à include-dirs et include-libs les valeurs suivantes :
include-dirs = /home/geoadmin/downloads/gdal-2.2.4,/usr/include/gdal   library-dirs = /home/geoadmin/downloads/lib,/usr/lib

**Comment by camillemonchicourt** [comment]
Merci pour ce partage intéressant. 
En effet le script ``install.sh`` vérifie l'OS sur lequel l'installation est lancée pour adapter certaines commandes, notamment les version de PostgreSQL et PostGIS à installer : https://github.com/GeotrekCE/Geotrek-admin/blob/2.29.9/install.sh#L611-L637

Actuellement seules les versions d'Ubuntu sont prévues. 

Pour être réellement opérationnel sur Debian, il pourrait être envisagé d'intégrer cette contribution directement dans le script ``install.sh``, car sinon il va falloir refaire ce même bidouillage de script à chaque fois que vous faites une mise à jour. N'hésitez pas à faire une proposition d'évolution du script sous forme de Pull request.

Sinon, à noter aussi, un travail est en cours pour permettre de déployer Geotrek avec Docker : https://github.com/GeotrekCE/Geotrek-admin/tree/docker-integration

Cela permet de déployer Geotrek sous n'importe quel OS qui supporte Docker (la plupart des distributuons Linux et même Windows et MaxOS), voir la documentation associée à la version Docker : https://geotrek.readthedocs.io/en/docker-integration/

**Comment by camillemonchicourt** [comment]
La méthode d'installation de Geotrek-admin a été complètement revue depuis la version 2.33. 
Elle inclut aussi la possibilité de déployer Geotrek-admin avec Docker, sans branche à part. 
Voir https://github.com/GeotrekCE/Geotrek-admin/issues/2135#issuecomment-597662308
