### ISSUE TITLE
non prise en compte de la locale pour traduction du mail feedback de signalement

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2076]
Geotrek-admin : 2.29.2
Geotrek-rando : 2.20.0-ux3

Lorsqu'un utilisateur fait un signalement sur un itinéraire sur le Geotrek-rando, il reçoit un mail faisant accusé de réception à son signalement.

cette locale est configuré dans Geotrek-admin/geotrek/feedback/locale/fr/LC_MESSAGES/django.po qui contient ceci : 

`msgid ""
"Hello,\n"
"\n"
"We acknowledge receipt of your feedback, thank you for your interest in Geotrek.\n"
"\n"
"Best regards,\n"
"The Geotrek Team\n"
"http://www.geotrek.fr"
msgstr ""
"Bonjour,\n"
"\n"
"Nous accusons réception de votre signalement, merci de votre intérêt pour "
"Geotrek.\n"
"\n"
"Cordialement,\n"
"\n"
"L'équipe Geotrek\n"
"http://www.geotrek.fr"`

J'ai copié ce contenu dans Geotrek-admin/geotrek/locale/fr/LC_MESSAGES/django.po

puis j'ai fait ces commande à  la racine du répertoire de Geotrek admin :

`make all_compilemessages`
`sudo spervisorctl restart all`

[fr_django.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3730011/fr_django.txt)
[feedback_django.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3730012/feedback_django.txt)

Mais aucun changement n'est pris en compte. 

Est-ce qu'il y a une erreur dans ma manipulation ? 
Je précise qu'il y a aucune customisation dans le custom.py

**Comment by camillemonchicourt** [comment]
Voir la doc dédié pour surcoucher des éléments de la traduction : https://geotrek.readthedocs.io/en/master/advanced-configuration.html#override-translations

**Comment by gutard** [comment]
Quand une configuration ne marche pas, il est recommandé de joindre le fichier complet en question.
De même, quand une commande ne marche, il est recommandé de copier/coller la commande et la réponse complètes. Sinon, c'est difficile de répondre rapidement et précisément.

Avec le peu d'informations que tu donnes voici deux pistes :
1. Les fichiers .po doivent contenir une entête. Ou bien tu peux copier/coller celle d'un autre fichier .po. Ou prendre l'exemple de la doc pointé par @camillemonchicourt 
2. La commande pour redémarrer est "sudo supervisorctl restart all" et non "sudo spervisorctl restart all"

**Comment by mviadere-openig** [comment]
Merci Gaël pour ta réponse.

j'ai copié les fichiers, mais effectivement je n'ai pas précisé exactement leur provenance.

Le premier fichier ([fr_django.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3733452/fr_django.txt)) de mon post précédent est le fichier django.po situé ici : Geotrek-admin/geotrek/locale/fr/LC_MESSAGES/django.po

C'est le fichier de customisation de la traduction pour la langue fr.

Le deuxième fichier ([feedback_django.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3733454/feedback_django.txt)) est le fichier par défaut de traduction situé ici : 
Geotrek-admin/geotrek/feedback/locale/fr/LC_MESSAGES/django.po

C'est le fichier par défaut que la documentation précise qu'il ne faut pas modifier.

Oui, la commande est bien supervisorctl restart all, c'est une coquille de ma part de mon message précédent.

Voici ce que retourne la commande make all_compilemessages : [commande.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3733512/commande.txt)

Et ce que retourne sudo supervisorctl restart all :[commande2.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3733569/commande2.txt)


L'en-tête est bien présente dans les deux fichiers, mais je viens de voir qu'il y a une légère modification entre celles dans mes fichiers et celle dans la doc. Je vais appliquer le changement et retenter la manipulation.

**Comment by gutard** [comment]
Pardon, j'avais pas vu les fichiers joint au départ. Comme ils n'ont pas leur vrais noms de fichier j'ai pas percuté.

En fait la traduction est déjà dans `geotrek/feedback/locale/fr/LC_MESSAGES/django.po` donc ça n'a aucun intérêt de la recopier dans `geotrek/locale/fr/LC_MESSAGES/django.po`. Ça revient au même et ça ne marchera pas mieux.

C'est juste qu'il y a une erreur dans la chaîne à traduire. Il manque une ligne vide. C'est corrigé à partir de la version 2.29.5. Mais si tu ne veux pas mettre à jour tu peux effectivement corriger dans `geotrek/locale/fr/LC_MESSAGES/django.po` en rajoutant la ligne vide qui manque entre `Best regards,` et `The Geotrek Team`.

**Comment by mviadere-openig** [comment]
Merci, j'ai fait ce que tu as recommandé.
