### ISSUE TITLE
Contenu touristique et POI

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-admin#2085]
Bonjour, 

Certains contenus touristiques peuvent être également considérés comme des POIs (Château qui se visite, ..). Est-il possible de déclarer facilement un contenu touristique en POI afin d'éviter d'avoir une ressaisie ?

Cordialement,

**Comment by LePetitTim** [comment]
L'objectif est de dupliquer l'information ?

**Comment by eprouteau** [comment]
L'objectif serait de pouvoir déclarer du contenus touristique en tant que POI afin d'éviter de saisir un contenu touristique et un POI qui correspondent au même élément et du coup d'avoir deux fois la même information.

**Comment by camillemonchicourt** [comment]
Les contenus touristiques et les POI ont des champs assez différents et un fonctionnement bien à part (segmentation dynamique liée aux tronçons pour les POI, couche spatiale classique pour les Contenus touristiques). 
Par ailleurs, hormis quelques exception comme vous indiquez, ce sont des objets bien différents (patrimoines d'un côté, hébergements, restaurations, services pour l'autre).
Enfin, au niveau de Geotrek-rando, ils ont un comportement bien dissocié. 

Du coup, il n'est pas possible de transformer un Contenu touristique en POI ni inversement. Et je ne suis pas sur que cela soit souhaitable ?

**Comment by eprouteau** [comment]
Merci pour le retour. Effectivement les comportements sont différents. Je vais du coup essayer de créer une routine FME basée sur un message précédent.
