### ISSUE TITLE
Contenus touristiques et portails

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2091]
Lorsque l'on définie des sélections Apidae à importer dans Geotrek-admin en spécifiant un portail de destination à l'aide du paramètre "portal" dans le fichier "parsers.py" :

Si des objets Apidae présents dans la sélection à destination du portail "A" sont également présents dans la sélection à destination du portail "B", les ids de portails ne sont pas concaténés dans le champs "portail" de l'objet et seul un des deux portails est enregistré. En conséquence la sélection pour un des portails n'est pas complète.

Exemple de parsers.py

```
class HebergementPortailA(TouristicContentApidaeParser):
        label = u"Hébergements - Portail A"
        api_key = 'xxxxxxx'
        project_id = 888
        selection_id = 555
        category = u"Hébergements"
        delete = True
        portal = [u"Portail A"]

class HebergementPortailB(TouristicContentApidaeParser):
        label = u"Hébergements - Portail B"
        api_key = 'xxxxxxx'
        project_id = 999
        selection_id = 444
        category = u"Hébergements"
        delete = True
        portal = [u"Portail B"]
```

**Comment by pnrma** [comment]
Même s'ils ont des objets apidae en commun, les différents portails ont des api_key, project_id et sélections Apidae distinctes.
Comment faire un seul parser avec plusieurs sélections Apidae et potentiellement plusieurs api_key et project_id ?

**Comment by gutard** [comment]
> Même s'ils ont des objets apidae en commun, les différents portails ont des api_key, project_id et sélections Apidae distinctes.

Pourquoi ne serait-il pas possible de faire une sélection unique pour ces objets ? C'est la voie la plus simple à suivre à mon avis.

> Comment faire un seul parser avec plusieurs sélections Apidae et potentiellement plusieurs api_key et project_id ?

C'est faisable, mais ça n'existe pas pour l'instant. Il faudrait envisager un peu de dev pour faire ça et je ne suis pas sûr que ce soit une bonne idée.

La troisième solution est effectivement de garder 2 parsers mais avec un mécanisme de suppression particulier qui enlève le portail de la liste et ne supprime réellement que si la liste des portails est vide. Là c'est la méthode end() qu'il faudra adapter, ainsi que prévoir l'addition et non le remplacement du champ portail. Mais là aussi c'est une mécanique un peu complexe et du dev à prévoir.

**Comment by pnrma** [comment]
> Pourquoi ne serait-il pas possible de faire une sélection unique pour ces objets ? C'est la voie la plus simple à suivre à mon avis.

Effectivement mais dans le cas d'une sélection regroupant les objets à destination de tous les portails, comment attribuer tel objet à tel portail ? Car c'est justement les sélections qui permettent de sélectionner les objets que l'on souhaite attribuer à un portail en particulier.

> La troisième solution est effectivement de garder 2 parsers mais avec un mécanisme de suppression particulier qui enlève le portail de la liste et ne supprime réellement que si la liste des portails est vide. Là c'est la méthode end() qu'il faudra adapter, ainsi que prévoir l'addition et non le remplacement du champ portail. Mais là aussi c'est une mécanique un peu complexe et du dev à prévoir.

Je pense que c'est la solution la plus adaptée et je note que cela demande du dev spécifique.

Merci pour vos réponses.

**Comment by camillemonchicourt** [comment]
Nous avons un contexte similaire. 
Nous avons 2 sélections APIDAE différentes qui alimentent les hébergements de 2 portails différents (GTE et PDE). Mais il y a des objets communs entre ces 2 sélections...

Du coup on a pensé à faire : 
- Import APIDAE sélection GTE
- Synchro DATA portail GTE
- Import APIDAE sélection PDE
- Synchro DATA portail PDE

Le fichier ``parsers.py`` : 
```
from geotrek.tourism.parsers import HebergementsApidaeParser

class HebergementParserGTE(HebergementsApidaeParser):
    label = u"Hebergements GTE APIDAE"
    api_key = 'abcdefg'
    project_id = xxxx
    selection_id = yyyyy
    source = ['Apidae']
    portal = ['Grand Tour des Ecrins']
    # To delete all Geotrek objects already destroyed in Apidae
    delete = True

    # Override this method to don't publish unpublished objects
    def parse_obj(self, row, operation):
        if not self.obj.pk:
            self.obj.published = True
        super(HebergementParserGTE, self).parse_obj(row, operation)

class HebergementParserPDE(HebergementsApidaeParser):
    label = u"Hebergements PDE APIDAE"
    api_key = 'ghijkl'
    project_id = zzzz
    selection_id = wwwww
    source = ['Apidae']
    portal = ['Rando Pays des Ecrins']
    # To delete all Geotrek objects already destroyed in Apidae
    delete = True

    # Override this method to don't publish unpublished objects
    def parse_obj(self, row, operation):
        if not self.obj.pk:
            self.obj.published = True
        super(HebergementParserPDE, self).parse_obj(row, operation)
```

J'ai testé et on a bien le comportement attendu.

Quand je lance l'importe de ma première sélection (GTE), il m'importe 389 hébergements et leurs médias et les associe bien au portail "Grand Tour des Ecrins".

Puis quand je lance la seconde sélection (PDE), il m'importe les 8 refuges correspondants et les associe bien au portail "Rando Pays des Ecrins". En fait il m'en importe 2 nouveaux et pour les 6 autres en commun qui existaient déjà du fait de l'import de la sélection GTE, il m'a seulement modifié le portail cible de "Grand Tour des Ecrins" en "Rando Pays des Ecrins".
Il n'a pas supprimé les autres hébergements de la sélection précédente, ni les photos attachés. 

Quand je relance ensuite l'import GTE, il me rebascule bien les 6 hébergements communs aux 2 sélections vers le portail "Grand Tour des Ecrins". Et il garde les 2 autres hébergements spécifiques au portail "Rando Pays des Ecrins". 

Donc c'est bien OK par rapport à la piste d'alterner un import GTE, une synchro GTE, un import PDE, une synchro PDE.
Comme ces 2 imports ont des paramètres différents (le portail cible notamment), il bascule bien le portail cible des objets communs à chaque import, et il ne touche pas les autres objets spécifiques à un portail. 

A noter, il supprime les objets existants quand je lance 2 imports de suite qui ont les mêmes paramètres (même portail cible notamment) mais des contenus différents. Dans ce cas, il supprime les objets de l'import précédent et leurs photos associés.

**Comment by pnrma** [comment]
The original message was received at Wed, 1 Jul 2020 13:29:02 +0200
from vsmtp16.inforoutes.fr [46.18.231.66]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by pnrma** [comment]
C'est effectivement la procédure que nous utilisons pour les différents portails alimentés par notre admin et cela n'a pas posé de problème jusqu'à présent (hormis le temps supplémentaire nécessaire aux imports Apidae à chaque synchro).

**Comment by camillemonchicourt** [comment]
Ce fonctionnement n'est plus possible avec la v3 de Geotrek-rando car on importe plus les objets à un instant T, mais on les interroge en continu par l'API v2.

Autre possibilité envisagée : Ajouter la possibilité au parser (si ce n'est pas déjà le cas) quand on lui passe une constante, de ne pas écraser celle déjà éventuellement renseignée, mais d'ajouter la valeur fournie

**Comment by pnrma** [comment]
> Autre possibilité envisagée : Ajouter la possibilité au parser (si ce n'est pas déjà le cas) quand on lui passe une constante, de ne pas écraser celle déjà éventuellement renseignée, mais d'ajouter la valeur fournie

Je plussoie pour cette possibilité qui sera indispensable dans notre cas de figure.

**Comment by camillemonchicourt** [comment]
Cela a été mis en place dans la version 2.80.0 avec l'ajout du paramètre ``m2m_aggregate_fields`` utilisable dans les parsers. 
Voir la documentation ajoutée sur celui-ci.
