### ISSUE TITLE
Docker integrations : test utilisateurs

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2092]

**Comment by camillemonchicourt** [comment]
@lelannl, voir la doc sur la branche dédiée : https://geotrek.readthedocs.io/en/docker-integration/

Tester : 
- Une nouvelle installation (https://geotrek.readthedocs.io/en/docker-integration/installation.html)
- Une mise à jour de version de Geotrek-admin depuis un Docker existant
- Une migration vers Docker depuis une version classique (https://geotrek.readthedocs.io/en/docker-integration/change-to-docker.html)

**Comment by lelannl** [comment]
Au lancement de la commande docker-compose up dans le dossier comprenant le fichier docker-compose.yml. On obtient l'erreur ` nginx_1          | envsubst: error while reading "standard input": Is a directory`
On constate qu'un dossier a été créé geotrek-nginx.conf. Est ce normal? Ca ne devrait pas être un fichier? 

Dans docker-compose.yml, on a les lignes:
```
  volumes:
      - ./geotrek-nginx.conf:/geotrek.conf
```
puis la ligne 
` command: /bin/bash -c "envsubst '$$DOMAIN_NAME' < /geotrek.conf > /etc/nginx/conf.d/geotrek.conf && nginx -g 'daemon off;'"`
Est ce que ça n'indique pas que geotrek.conf devrait être un fichier?

**Comment by lelannl** [comment]
Amelioration de la documentation:

 dans la partie CREATE THE VAR FOLDER :
`mkdir -p var
docker-compose run web /bin/sh -c exit`
in manque la création de /conf

Si l'on installe docker en localhost et que l'on a déjà postgers il apparaît des conflits de ports

**Comment by camillemonchicourt** [comment]
La méthode d'installation de Geotrek-admin a été complètement revue depuis la version 2.33. 
Elle inclut aussi la possibilité de déployer Geotrek-admin avec Docker, sans branche à part. 
Voir https://github.com/GeotrekCE/Geotrek-admin/issues/2135#issuecomment-597662308
