### ISSUE TITLE
pb maj Geotrek-admin 2.29.2 à 2.29.3

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2093]
Geotrek-admin : 2.29.2

lors de la tentative de mise à jour pour vers la 2.29.3 pour que le PNRGC puisse avoir accès à  la V3 du Geotrek-mobile. j'ai ce message d'erreur : 

![erreur](https://user-images.githubusercontent.com/45095227/68681071-ff840f00-0562-11ea-8a09-97ab5fb9f6fd.png)

Je précise que pour mettre à jour, j'ai utilisé git. 

Voici le fichier install.log où est l'erreur : 

[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/3836654/install.log)

**Comment by camillemonchicourt** [comment]
Je suis passé de la 2.29.0 à la 2.29.13 la semaine dernière sans soucis, sur le serveur de démo (http://geotrekdemo.ecrins-parcnational.fr).

Je ne suis pas expert, mais il semblerait que tu aies un problème lors de l'installation d'une des dépendances Python.

PS : Pourquoi passer en 2.29.3 alors qu'on en est à la 2.29.14 ?

**Comment by mviadere-openig** [comment]
J'ai tenté de passé de la 2.29.10 sur mon serveur dev à la 2.29.14 et j'ai eu le même problème.

Le seul post que j'ai vu qui parlait de cet erreur : https://github.com/GeotrekCE/Geotrek-admin/issues/1936

Comme je ne sais pas ce que ce message signifie et que je ne sais pas si c'est en lien, j'ai préféré faire la montée de version strictement nécessaire.

**Comment by gutard** [comment]
C'est Python 3 qui nous rattrape ;) Une dépendance de dépendance a été mise à jour et ne supporte plus Python 2.

Bon, du coup, plus aucune version de Geotrek-admin ne s'installe.

Le fix est en cours. Le workaround c'est d'ajouter la ligne `venusian = 1.2.0` dans la section `[versions]` du fichier `conf/buildout.cfg`

**Comment by mviadere-openig** [comment]
Merci Gaël, je fais ça.

**Comment by camillemonchicourt** [comment]
La nouvelle version 2.29.15 règle ce problème de dépendance.
