### ISSUE TITLE
Erreur création superuser 

### ISSUE THREAD

**Issue by chanteclair12** [GeotrekCE/Geotrek-admin#2095]
Bonjour,
Je tente de finaliser l'installation de Geotrek-admin-2.29.15 sur un VM Ubuntu 18.04 LTS.
Cependant quand je lance la commande `bin/django createsuperuser`, j'ai le retour : `-bash: bin/djnago: No such file or directory`
Je ne sais où chercher. Pourriez-vous éclairer ma lanterne svp ?
En vous remerciant par avance.

PS : message également posté sur https://groups.google.com/forum/#!forum/geotrek-fr

**Comment by camillemonchicourt** [comment]
Le message d'erreur indique que c'est certainement car vous n'avez pas lancé la commande depuis le bon répertoire. 
Elle doit être lancée depuis la racine du répertoire de Geotrek-admin, qui contient notamment le dossier ``bin``.
Selon votre organisation du serveur, à lancer depuis un répertoire comme ``/home/monuserlinux/Geotrek-admin/``

**Comment by chanteclair12** [comment]
Effectivement, cela venait bien de cela.
Comme je suis encore novice par rapport au monde Linux, j'en découvre tous les jours.
Merci de votre aide.

**Comment by camillemonchicourt** [comment]
Pas de soucis, c'est classique, tout le monde l'a faite celle-là ! :-)
Le message ``No such file or directory`` oriente sur la piste qu'on n'est pas au bon endroit.
Bonne découverte.

**Comment by mviadere-openig** [comment]
Je confirme :)

**Comment by chanteclair12** [comment]
Je l'ai plus pris comme une installation non faite que comme un mauvais emplacement pour lancer la commande.
Mais je la note pour plus tard, cela m'arrivera encore je pense :-)
