### ISSUE TITLE
PWD PGSQL

### ISSUE THREAD

**Issue by chanteclair12** [GeotrekCE/Geotrek-admin#2097]
Bonjour,
J'ai avancé dans la finalisation de l'installation de Geotrek-admin.
Je souhaite maintenant réinstaller un dump dans PGSQL.
Je suis donc la procédure de réinstallation d'une BDD sur un nouveau serveur (https://geotrek.readthedocs.io/en/master/installation.html#server-migration).
Cependant, après avoir arrêté les services, quand je veux effacer la BDD créée à l'installation, j'ai le message :`postgres is not in the sudoers file.  This incident will be reported.`
De même quand le compte "postgres" lme demande un mot de passe et que je saisis "postgres" (théoriquement mot de passe par défaut de l'utilisateur postgres), j'ai une retour comme quoi ce n'est pas le bon. Je n'ai rien trouvé dans la documentation qui indique que ce mot de passe par défaut soit changé.
Merci de votre aide.

**Comment by chanteclair12** [comment]
Encore une fois, la découverte de Linux me joue des tours ! Je n'étais pas en root pour lancer les commandes ! Désolé pour le parasitage.

**Comment by gutard** [comment]
En principe il ne faut jamais être logué en root pour administrer Geotrek. Les commandes préfixées par sudo permettent de passer temporairement root uniquement aux moments où c'est nécessaire.

**Comment by chanteclair12** [comment]
C'est noté merci.
J'ai réussi à supprimer à la base Geotrek existante pour la recréer avec la commande `sudo -u postgres psql -c "create database geotrekdb owner geotrek;`.
Une chose me bloque : la commande pour lancer la restauration de mon dump au format .sql et non .backup. La commande pg_restore ne fonctionne pas. Quelle ligne de commande utiliser alors ?
Deuxième chose, j'ai une session ouverte avec putty en ssh. Je pensais donc que je pouvais en parallèle utiliser PgAdmin pour me connecter à cette base et avoir une visualisation de celle-ci. Or, quand j'utilise les paramètres standard que je n'ai pas encore personnalisés (hôte : localhost, port : 5432, base : geotrekdb, login : geotrek, pwd : geotrek) je ne parviens à me connecter.

**Comment by camillemonchicourt** [comment]
En effet, attention à ne jamais travailler sur un serveur linux avec l'utilisateur ``root`` et à ne faire que le nécessaire en sudo, sinon votre utilisateur courant (``geotrek`` par exemple) n'aura pas les droits sur les dossiers et fichiers. 
Idem sur la BDD, il faut que le nécessaire avec l'utilisateur ``postgres``, sinon votre utilisateur courant de BDD (``geotrek`` n'aura pas les droits sur les tables).

Plus globalement vos problèmes mentionnés ci-dessus ne concernent pas Geotrek, mais l'administration de serveur Linux et surtout de BDD PostgreSQL, donc c'est plutôt vers là qu'il faut chercher.

**Comment by chanteclair12** [comment]
J'ai réglé pas mal de choses.
Néanmoins, après avoir suivi toute cette procédure
`sudo supervisorctl stop all
sudo -u postgres psql -c "drop database geotrekdb;"
sudo -u postgres psql -c "create database geotrekdb owner geotrek;"
sudo -u postgres pg_restore -d geotrekdb geotrekdb.backup
make update
sudo supervisorctl start all`
et n'avoir eu auncun message d'erreur, quand je me connecte à l'appli, je n'ai rien aucune donnée dans les différents menus (tronçons, sentiers...).
Que faire de plus svp ?

**Comment by camillemonchicourt** [comment]
Vérifier la base de données, voir si il y a les contenus dans les tables etc...

**Comment by chanteclair12** [comment]
J'ai enfin pu me connecter avec PgAdmin et mes tables sont bien remplies avec les données sauvegardées.
Pour autant, rien ne s'affiche dans Geotrek-Admin...

**Comment by camillemonchicourt** [comment]
Il faudrait beaucoup plus d'infos pour identifier les problèmes.

Mais le problème ne vient pas de Geotrek de ce que j'en comprends.
Mais plutôt du fait d'avoir sauvegardé puis restauré, peut-être avec des problèmes de droits d'utilisateur PostgreSQL ou plein d'autres problèmes possibles decorreles de Geotrek.
Donc je vous invite à chercher des informations sur vos problèmes PostgreSQL (logs notamment) ou sinon à reinstaller proprement Geotrek.

**Comment by chanteclair12** [comment]
J'ai recommencé la procédure à l'identique et cette fois, les données s'affichent.
Mystère! Mais l'essentiel est bien là.
Merci de vos réponses.
