### ISSUE TITLE
API Cirkwi

### ISSUE THREAD

**Issue by thomasmagninfeysot** [GeotrekCE/Geotrek-admin#2125]
Bonjour à tous,
Dans le cadre d'un projet touristique, on souhaite récupérer des itinéraires et POI de certains itinéraires depuis l'API qui est généré automatiquement pour l'IGN Rando dans le référentiel CIRKWI.
Je n'arrive cependant pas à filtrer sur un critère, dans mon cas locomotion nom="Velo_vtc".
J'ai essayé http://randoadmin.parc-haut-jura.fr/api/cirkwi/circuits.xml/locomotion=Velo_vtc
ou encore http://randoadmin.parc-haut-jura.fr/api/cirkwi/circuits.xml/locomotion/Velo_vtc mais rien n'y fait, j'ai tout qui remonte. J'ai bien fait la correspondance dans les tables, dans la table pratiques dans mon cas. Est que certaines personnes ont réussi à filtrer ces paramètres ou connaissent la bonne façon de faire ?

Merci d'avance pour votre coup de main,
Thomas

**Comment by gutard** [comment]
L'API cirkwi est conçue pour les besoin de cirkwi qui ne nécessite pas de filtrage donc le filtrage n'est pas implémenté sur cette API.

Il vaut mieux utiliser l'API v2 : http://randoadmin.parc-haut-jura.fr/api/v2/trek.geojson?practice=7
Le format de sortie est différent mais il est plus compact et plus standard (geojson plutôt que XML).

**Comment by thomaspnrhj** [comment]
Merci Gaël pour ces infos, et pour les POI on passe par http://randoadmin.parc-haut-jura.fr/api/v2/poi.geojson. 
Par contre est ce qu'il y'a la possibilité d'avoir une API avec les itinéraires et les pois qui sont concernées, un peu comme l'API Cirkwi ?

**Comment by gutard** [comment]
A vérifier mais je pense que tu peux récupérer l'id du trek, et faire une deuxième requête sur http://randoadmin.parc-haut-jura.fr/api/v2/poi.geojson?trek=233503

**Comment by gutard** [comment]
Autre chose, par défaut tu récupères toutes les langues sous la forme "name": {"fr": …, "en": …}. Si tu veux te limiter à une langue il faut ajouter le paramètre language=fr

**Comment by camillemonchicourt** [comment]
Oui l'API v2 dynamique offre plus de possibilités. 
Une troisième possibilité est l'API dynamique au niveau de Geotrek-rando qui offre une forme assez complète et déjà mis en forme des contenus. 

Voir les URL dans le schéma des interfaces des rencontres 2019 : https://geotrek.ecrins-parcnational.fr/rencontres/2019/presentations/08-geotrek-interfacages.pdf

**Comment by thomaspnrhj** [comment]
Alors depuis l'API v2 de G.ADMIN j'arrive bien à requêter sur practice pour avoir mes itinéraires souhaitées. Par contre http://randoadmin.parc-haut-jura.fr/api/v2/poi.geojson?trek=233503 ne fonctionne pas pour récupérer les POIs mais je pense pas que ça m'aidera pas car je dois récupérer les POIs de mes treks avec practice=x donc je vois pas comment c'est possible de faire remonter ça... 
J'ai tester plusieurs requêtes aussi sur l'API depuis G.RANDO mais j'arrive à rien non plus.
Merci quand même,
Thomas
