### ISSUE TITLE
Erreur de synchro "Type Error : 'float' object is not iterable"

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2126]
Bonjour,

Geotrek-admin : 2.29.2
Geotrek-rando : 2.21.0-ux.zip

La synchro s'arrête avec l'erreur dans le titre.

Voici les logs de la synchro [synch_rando.log](https://github.com/GeotrekCE/Geotrek-admin/files/4058178/synch_rando.log)

je ne sais pas à quoi correspond cette erreur. Quelqu'un parmi vous l'aurait déjà croisé ?

**Comment by gutard** [comment]
A priori la géométrie d'un des itinéraires n'est pas bonne (n'est pas une LineString). Il y a moyen de corriger le bug avec un peu de TMA. Sinon, il suffit de corriger la géométrie qui pose problème pour qu'il ne se déclenche plus.

**Comment by mviadere-openig** [comment]
Merci pour ton retour, je regarde ça.

**Comment by mviadere-openig** [comment]
J'ai résolu le problème en supprimant les tronçons dans la bdd qui n'étaient pas en LineString, je clos l'issue.
