### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2132]
Bonjour,

J'ai un **504 Gateway Time-out** qui s'affiche après un certains temps de chargement lorsque je souhaite sauvegarder des modifications faites sur le tracé d'un itinéraire conséquent. 

**Proccess**
Redémarrage du serveur /ouverture en mode édition de la fiche de l'itinéraire /modification du tracé /sauvegarde ->  erreur 504 au bout de 4h env.

L'itinéraire a actuellement une longueur de 2000km, il manque environ 1000km de chemin à créer. Il intègre 53 étapes, il devrait en intégrer une 100aine.

Je n'ai pas l'impression que ce type de calcul nécessite beaucoup de ressources. Le htop indique une RAM à environ 3Go et un seul processeur d'actif sur 4.

**Configuration**
4 vCore / 24 Go de RAM
Ubuntu 16.04.6
GTA v. 2.32.2

**Log /var/log/postgresql/postgresql-9.5-main.log après redémarrage serveur :**
2020-01-28 23:37:30 CET [1579-1] postgres@postgres FATAL:  the database system is starting up
2020-01-28 23:37:30 CET [1612-1] postgres@postgres FATAL:  the database system is starting up
2020-01-28 23:37:30 CET [1570-2] LOG:  MultiXact member wraparound protections are now enabled
2020-01-28 23:37:30 CET [1514-1] LOG:  database system is ready to accept connections
2020-01-28 23:37:30 CET [1616-1] LOG:  autovacuum launcher started
2020-01-29 02:39:43 CET [2707-1] geotrek@geotrekdb LOG:  could not receive data from client: Connection reset by peer
2020-01-29 02:39:43 CET [2707-2] geotrek@geotrekdb LOG:  unexpected EOF on client connection with an open transaction
2020-01-29 03:26:04 CET [4156-1] [unknown]@[unknown] LOG:  could not receive data from client: Connection reset by peer
2020-01-29 03:26:04 CET [4156-2] [unknown]@[unknown] LOG:  incomplete startup packet

**Log /var/log/supervisor/geotrek.log après redemarrage serveur :**
[2020-01-28 23:37:33 +0100] [1500] [INFO] Starting gunicorn 19.6.0
[2020-01-28 23:37:33 +0100] [1500] [INFO] Listening at: unix:/tmp/gunicorn-geotrek.sock (1500)
[2020-01-28 23:37:33 +0100] [1500] [INFO] Using worker: sync
[2020-01-28 23:37:33 +0100] [1719] [INFO] Booting worker with pid: 1719
[2020-01-28 23:37:33 +0100] [1725] [INFO] Booting worker with pid: 1725
[2020-01-28 23:37:33 +0100] [1731] [INFO] Booting worker with pid: 1731
[2020-01-28 23:37:33 +0100] [1734] [INFO] Booting worker with pid: 1734
/home/colomban/Geotrek-admin/lib/eggs/psycopg2-2.7.4-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/colomban/Geotrek-admin/lib/eggs/WeasyPrint-51-py3.5.egg/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
ERROR 2020-01-29 00:50:04,681 django.security.DisallowedHost Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
ERROR 2020-01-29 01:02:54,098 django.security.DisallowedHost Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
[2020-01-29 02:37:31 +0100] [1500] [CRITICAL] WORKER TIMEOUT (pid:1731)
[2020-01-29 02:37:32 +0100] [3846] [INFO] Booting worker with pid: 3846
ERROR 2020-01-29 05:48:39,074 django.security.DisallowedHost Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
ERROR 2020-01-29 07:18:42,201 django.security.DisallowedHost Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
/home/colomban/Geotrek-admin/lib/eggs/psycopg2-2.7.4-py3.5-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/colomban/Geotrek-admin/lib/eggs/WeasyPrint-51-py3.5.egg/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
ERROR 2020-01-29 10:20:22,024 django.security.DisallowedHost Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.

**Log /var/log/nginx/geotrek_error.log.1 :**
2020/01/29 02:37:30 [error] 1521#1521: *362 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 176.180.90.200, server: admin.servername.com, request: "POST /trek/edit/824/ HTTP/1.1", up$

R.A.S dans var/log/nginx/geotrek_error.log
R.A.S dans /home/monuser/Geotrek-admin/var/log/geotrek.log

Merci pour votre aide,

Jean

**Comment by gutard** [comment]
Le problème est connu et affecte de nombreux utilisateurs de Geotrek. Ce sont les calculs de drapage (affectation de l'altitude à partir du MNT sur tous les points du parcours) qui sont peu efficaces. Diverses solutions possibles sont détaillées dans le ticket #1493. Les travaux sur ce point avaient été programmés pour démarrer cette semaine dans le cadre du groupement de commande mais @camillemonchicourt a suspendu cette décision prise la semaine dernière.

**Comment by JeanLenormand** [comment]
Ok, merci.

**Comment by gutard** [comment]
La version 2.33.3 corrige ce problème. Attention ! La procédure d'installation a changé.

**Comment by JeanLenormand** [comment]
En effet, nette améliorations des performances (version GTA 2.33.11) :
-> Modification sur un itinéraire de 1121km
-> Sauvegarde de l'itinéraire : 1min05 de chargement contre env.30min avec l'ancienne version.
Bravo et merci @gutard et toute l'équipe !
