### ISSUE TITLE
Integrate Django-Mapentity into Geotrek-admin

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2133]
Django-Mapentity was created to factor the global geographical CRUD outside of Geotrek-admin, to be able to use it in some other projects.

But after a few years it was finally not used for other projects than Geotrek-admin. And then is costing when developing Geotrek-admin. 

So it would be easier to integrate Django-Mapentity into Geotrek-admin code, with keeping a good separation of code parts.

**Comment by gutard** [comment]
Wating for #2135 to be merged.

**Comment by gutard** [comment]
Superseded by #2193
