### ISSUE TITLE
Erreur Could not update data ! à l'installation version 3.32.3

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2134]
Lors de l'installation de la version 3.32.3, j'ai constaté l'erreur `Could not update data !` qui venait d'un caractère `%` dans la valeur du paramètre `dbpassword `du fichier settings.ini.

J'ai modifié le password et relancé l'installation sans problème mais je n'avais jamais eu le problème avec des versions antérieures.

Résolu donc pour ma part mais je le signale si ça peut servir à d'autres.

**Comment by camillemonchicourt** [comment]
La version 2.30.0 a intégré le passage de Python 2 à Python 3 (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2300-2019-11-26). 
Ta version précédente était antérieure ?

Car la gestion des caractères spéciaux est différente dans Python 3 de ce que j'ai compris. 
Sujet assez proche : https://github.com/GeotrekCE/Geotrek-admin/issues/2114

**Comment by pnrma** [comment]
The original message was received at Mon, 3 Feb 2020 15:44:49 +0100
from hebersmi.inforoutes.fr [46.18.231.80]

   ----- The following addresses had permanent fatal errors -----
<jferreira@alia8.inforoutes.fr>
    (reason: 550 Host unknown)

   ----- Transcript of session follows -----
550 5.1.2 <jferreira@alia8.inforoutes.fr>... Host unknown (Name server: alia8.inforoutes.fr: host not found)

**Comment by pnrma** [comment]
Le version précédemment installée était la 2.29.15 donc effectivement cela doit être lié à la différence de Python 2 et Python 3 sur la gestion des caractères spéciaux.
