### ISSUE TITLE
Add an install script to docker-integration branch

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2135]
* Then merge docker-integration into master to allow two installation methods : install.sh and Docker
* Interactive dialog to ask for basic configuration (SRID, domain, postgresql credentials)
* Separate targets to install, update, restart…

**Comment by camillemonchicourt** [comment]
In the ``docker-integration`` branch, the installation documentation has been well rewritten (https://geotrek.readthedocs.io/en/docker-integration/advanced-configuration.html). But only for a Docker instance.
As we choose to keep both ways to install Geotrek-admin (with Docker or without), it will need to merge but keep both documentations, I think.

**Comment by gutard** [comment]
> As we choose to keep both ways to install Geotrek-admin (with Docker or without), it will need to merge but keep both documentations, I think.

Yes, of course.

**Comment by camillemonchicourt** [comment]
La méthode d'installation a été largement revue. 
Elle s'appuie maintenant sur un paquet Debian (``.deb``) et Geotrek-admin s'installe maintenant au niveau du système avec une commande ``sudo apt install -y geotrek-admin``. 
Pour commencer le paquet Debian est fonctionnel sur Ubuntu 18.04. 
Le package est disponible sur un dépôt Geotrek dédié https://packages.geotrek.fr qu'il faut donc ajouter aux sources listes.
Pour faciliter cela un script SH (https://github.com/GeotrekCE/Geotrek-admin/blob/packaging/install.sh) a été écrit et il suffit de le lancer vec une commande ``curl https://packages.geotrek.fr/install.sh`` pour lancer l'installation globale de Geotrek-admin. Les paramètres seront demandés lors de cette procédure au niveau de l'interface, et non plus à remplir dans un fichier de configuration préalable. 
Les mises à jour de Geotrek-admin seront aussi automatiques avec la commande ``sudo apt-get upgrade``.
Pour éviter d'éclater les fichiers de Geotrek-admin au niveau du système, ils ont été regroupés dans le répertoire ``opt``.

A faire : 
- Compléter la documentation d'installation
- Intégrer ou faire une doc séparée avec les parties liées à une installation Docker
- Faire une documentation sur la mise à jour de Geotrek-admin (automatique, manuelle, figée...)
- Documentation de migration
- Revoir la documentation de configuration de Geotrek-admin car les fichiers ne sont plus les mêmes et ne sont plus au même endroit. Les commandes à lancer après modification de la config ont peut-être évolué aussi ?
- Compléter la documentation "Développement" sur la partie "Release" (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/development.rst#release), avec la méthode de déploiement/publication du package ?
