### ISSUE TITLE
Let Django name tables and fields

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2137]
Passer les noms des champs en anglais dans la base comme dans le code.

- [x] Remove db_column= in model field properties
- [x] Remove db_table= in model Meta properties
- [x] Rename fields and tables in SQL code
- [x] Create migrations

**Comment by gutard** [comment]
@camillemonchicourt, what should we do with views like o_v_itineraire ?

**Comment by camillemonchicourt** [comment]
I think it is useful to have a view for each object (treks, signages...) in order to export them or to open them directly in a GIS tool. 
But we can use the same names for these objects as those from the model objects. 
So it would be something like v_treks, v_signages...
What do you think ?

**Comment by gutard** [comment]
Yes, perfect.

**Comment by LePetitTim** [comment]
#2140

**Comment by gutard** [comment]
Il reste des problèmes :
- [ ] geotrek/common/mixins.py a été oublié,
- [ ] des colonnes avec le nouveau nom sont bien créées pour les traductions mais elles sont vide,
- [ ] Failed to install custom SQL file '/app/src/geotrek/core/sql/30_evenements_troncons.sql': ERREUR:  ne peut pas modifier le nom du paramètre en entrée « troncon »
HINT:  Utilisez tout d'abord DROP FUNCTION ft_troncon_interpolate(integer,geometry). Du coup une partie des trigger n'a pas l'air d'être mis à jour

**Comment by camillemonchicourt** [comment]
OK, intégré dans la version 2.32.7, déployée sur http://geotrekdemo.ecrins-parcnational.fr. 
J'ai fait des tests rapides des différents modules et tout semble OK.

Au niveau de la BDD, les noms des tables et des champs ont donc été migrées en anglais, automatiquement nommés par le nom retenu dans les modèles python Django. 

Quelques exemples principaux : 
- geotrek.l_t_troncons > geotrek.core_path
- geotrek.e_t_evenement > geotrek.core_topology
- geotrek.e_r_evenement_troncon > geotrek.core_pathaggregation
- rando.o_t_itineraire > rando.trekking_trek
- ....

Dans chaque schéma, il y a toujours des vues qui permettent de faciliter la récupération des objets (rando.v_treks pour les randos, gestion.v_interventions pour les interventions...)

**Comment by camillemonchicourt** [comment]
Pour faciliter la compréhension de la BDD, un outil de génération automatique du modèle de donnée a été intégré et un PDF de chaque modèle a été généré et intégré dans la doc : https://github.com/GeotrekCE/Geotrek-admin/pull/2174

Même si cela sera peu lisible et pas imprimable, je me dis que finalement ça vaudrait le coup de générer en plus un MCD global de toute la BDD pour ceux qui veulent identifier les liens entre les modèles.

**Comment by camillemonchicourt** [comment]
Renommer aussi les contraintes en correspondance ? 
Par exemple l_t_troncon_geom_isvalid sur https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/core/sql/40_troncons.sql#L137

Idem pour les triggers, les index ... ?

**Comment by gutard** [comment]
Il y a effectivement pas mal de choses qui n'ont pas été renommées :
* les fonctions et triggers déclarés dans les fichiers SQL
* les relation many2many, cela semble lié à un bug du système de migration
* les séquence et index, non renommés par les migrations

**Comment by gutard** [comment]
En fait ça a l'air OK pour les Many2Many. Les séquences et index ne sont effectivement pas renommés par Django (cf. https://code.djangoproject.com/ticket/23577)

**Comment by gutard** [comment]
Les séquences sont renommées par #2198. Je laisse tomber (au moins provisoirement) pour les index. Il y a un hash à la fin du nom et je ne sais pas si celui-ci est identique partout.

**Comment by camillemonchicourt** [comment]
OK merci pour ce gros travail de renommage !
