### ISSUE TITLE
Update Leaflet and plugins

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2138]
- [x] [django-leaflet](https://github.com/makinacorpus/django-leaflet) **Version 0.27.0** qui contient [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) **Version 0.4.9**
- [x] [Leaflet.FileLayer](https://github.com/makinacorpus/Leaflet.FileLayer) **Version 1.2.0**
- [x] [leaflet.fullscreen](https://github.com/brunob/leaflet.fullscreen) **Version 1.6.0**
- [x] [Leaflet.GeometryUtil](https://github.com/makinacorpus/Leaflet.GeometryUtil) **Version 0.9.3**
- [x] [Leaflet.groupedlayercontrol](https://github.com/ismyrnow/leaflet-groupedlayercontrol) **Version 0.6.1**
- [x] [Leaflet.label](https://github.com/Leaflet/Leaflet.label) à supprimer (intégré au cœur de Leaflet)
par un équivalent
- [x] [Leaflet.OverIntent](https://github.com/makinacorpus/Leaflet.OverIntent) **Version 1.0.0**
- [x] [Leaflet.Snap](https://github.com/makinacorpus/Leaflet.Snap) -> à releaser sur npm
- [x] [Leaflet.Spin](https://github.com/makinacorpus/Leaflet.Spin) **Version 1.1.2**
- [x] [Leaflet.TextPath](https://github.com/makinacorpus/Leaflet.TextPath) **Version 1.2.3**
- [x] [django-tinymce](https://github.com/aljosa/django-tinymce) -> **Version 3.1.0** Fix le crash quand on clique sur un élément SVG
- [ ] Pb d'écrasement de la valeur du champ dans leaflet.form.js (django-leaflet) ligne 86 proposition de fix https://github.com/makinacorpus/django-leaflet/pull/302
- [ ] Snapping non initialisé : https://github.com/makinacorpus/Leaflet.Snap/issues/48 et https://github.com/Leaflet/Leaflet.draw/pull/858
- [ ] réintégrer le circlemarker à rayon en mètres (pour les bulles de sensibilité) à partir de https://github.com/GeotrekCE/django-leaflet/
- [ ] réintégrer le fix https://github.com/GeotrekCE/django-leaflet/pull/1 ?
- [ ] réintégrer https://github.com/makinacorpus/Leaflet.Snap/commit/d6893828eb1c07f0362cd72e207a363d029bc051
- [x] cadre autour des icônes de début/fin de tronçon (pas toujours, c'est étrange)
- [ ] refaire proprement les icônes -x2
- [ ] ne zoome plus sur la géométrie lors de la modification des path
- [ ] [Leaflet.MeasureControl ](https://github.com/makinacorpus/Leaflet.MeasureControl) -> marche pas, à corriger ou remplacer 
- [x] les icône des outils Leaflet et les poignées pour dessin ont l'air d'avoir pris de l'embonpoint
- [ ] Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead
- [ ] [Leaflet.LayerIndex](https://github.com/makinacorpus/Leaflet.LayerIndex) -> ok mais regarder pourquoi les latlng ne sont pas des vrais latlng de Leaflet

Changements :
* Control.removeFrom() -> Control.remove()
* includes : L.Mixin.Events -> L.Evented
* Polygon.getLatLngs -> returns array of array of LatLng instead of array of LatLng
* Retina icons
* z-index sur le profil alti
* Suppression de L.MultiPolyline -> remplacé par une L.Polyline avec un tableau de tableaux

**Comment by camillemonchicourt** [comment]
Including checking PR in all plugins and release each plugin used in Geotrek-admin

**Comment by gutard** [comment]
Travail en cours de @LePetitTim : #2190

**Comment by gutard** [comment]
> django-tinymce -> crash quand on clique sur un élément SVG

La PR que j'ai proposé (https://github.com/jazzband/django-tinymce/pull/276) vient d'être mergée.

**Comment by gutard** [comment]
https://leafletjs.com/2020/09/04/leaflet-1.7.1.html
