### ISSUE TITLE
Erreur update geotrek admin 2.32.3 "Could not setup Python Environment"

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2142]
Os: ubuntu Xenial : 16.4
Geotrek-admin actuel  : 2.29.10

Tentative d'upgrade vers la dernière version. Erreur suivante vers l'installation du package zipp.
Voici l'install.log : 
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4193059/install.log)

J'en profite pour signaler le poste de Relaire ici #2114 d'aujourd'hui où il rencontre exactement le même problème que moi. J'ai essayé de changé la version de plusieurs packages (dont zipp) pour voir si ça correspondait avec le passage à Python3 mais ça n'a rien donné.

Installation faite en utilisant Git.

**Comment by gutard** [comment]
Fixed in https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.32.4
