### ISSUE TITLE
Problème Synchro Geotrek-mobile par portail

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2144]
J'ai rattaché certains itinéraires à un portail en vu de faire une synchronisation mobile.

Voici la commande exécutée :
./bin/django sync_mobile -v2 -t --portal="mobile" /home/projet/datamobile/
-> Le filtrage par portail n'est pas pris en compte car tout les itinéraires sont synchronisés...

Dans GTA, lorsque je filtre la liste de résultats des itinéraires par portail, celle-ci se met bien à jour.

J'ai fais un test de synchro pour GTR avec le même filtre par portail :
./bin/django sync_rando -v2 -t --portal="mobile" /home/colomban/datamobile2/
->Même problème, le filtre par portail n’est pas pris en compte, tout les itinéraires sont synchronisés..

(Conf. GTA v. 2.32.2)

Merci pour votre aide.

**Comment by gutard** [comment]
Les itinéraires pour lesquels **aucun** portail n'est spécifié sont synchronisés sur **tous** les portails. En effet, la demande initiale était plutôt de désactiver quelques itinéraires sur un portail et non de n'en activer que quelques uns. D'où ce choix discutable, mais qui n'est pas totalement illogique.

Il faut donc créer un autre portail dans Geotrek-admin et l'affecter à tous les itinéraires sauf ceux que l'on veut voir sur le mobile.

**Comment by camillemonchicourt** [comment]
Ah info importante pour moi aussi ! 
Je ne me souvenais pas du tout qu'on avait ce comportement et je comprends mieux certaines choses ! Merci.

**Comment by camillemonchicourt** [comment]
Ah info importante pour moi aussi ! 
Je ne me souvenais pas du tout qu'on avait ce comportement et je comprends mieux certaines choses ! Merci.

**Comment by JeanLenormand** [comment]
Ok super, merci pour l'info !
