### ISSUE TITLE
Erreur update geotrek admin 2.32.4"Could not setup Python Environment"

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2148]
Os: 16.04.6 LTS (Xenial Xerus)
Geotrek-admin actuel : 2.29.3

Tentative d'upgrade vers la dernière version. Erreur suivante vers l'installation du package tinycss2.
Voici l'install.log :
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4212853/install.log)

**Comment by gutard** [comment]
`Download error on https://pypi.python.org/simple/tinycss2/: [Errno -3] Temporary failure in name resolution`

C'est juste un problème de DNS pendant un téléchargement. Comme indiqué c'est `Temporary` donc il faut juste relancer et ne s'inquiéter que si ça se reproduit systématiquement.

**Comment by gutard** [comment]
PS : un travail est en cours pour fiabiliser l'install et avoir juste à installer/mettre à jour un paquet Ubuntu.

**Comment by mviadere-openig** [comment]
Merci Gaël, je prends note.
