### ISSUE TITLE
Migration de la BDD et ajout d'itinéraires

### ISSUE THREAD

**Issue by Max-le64** [GeotrekCE/Geotrek-admin#2149]

**Comment by camillemonchicourt** [comment]
Il faudrait savoir quelle version vous utilisez et avoir des logs.
Le problème est nouveau sur votre Geotrek-admin ou vous venez d'installer l'outil ? Car nous n'avons pas ce problème et il n'est pas non plus présent sur le serveur de démo http://geotrekdemo.ecrins-parcnational.fr (admin/admin).

**Comment by Max-le64** [comment]
Bonjour,

Nous utilisons la version 2.32.1, nous avons fait une installation de zéro sur VM Azure (Ubuntu 18.043 LTS) et une restauration de la base via un dump.

Je vous met ci-joint le fichiers de logs : 
[postgresql-10-main.log](https://github.com/GeotrekCE/Geotrek-admin/files/4223698/postgresql-10-main.log)

**Comment by camillemonchicourt** [comment]
OK il faudrait certainement voir le log de Geotrek (dans ``/home/myuser/Geotrek-admin/var/log/geotrek.log``) mais déjà les logs de PostgreSQL remontent des erreurs qui indiquent certainement le problème en question. Il manque différentes tables dans la BDD. 

Sans certitude, je pense que vous avez fait une backup de votre BDD Geotrek sur le serveur initial qui était dans une version de Geotrek-admin différente de celle que vous avez installé sur le nouveau serveur. Du coup il y a une incohérence dans la structure de votre BDD qui a évolué entre les 2 versions.

**Comment by Max-le64** [comment]
D'accord.
Y'a-t-il un moyen de remonter un dump d'une base plus ancienne que la version actuelle utilisée et si on peut, comment devons nous faire ?

**Comment by camillemonchicourt** [comment]
Sauf erreur de ma part, quand on migre un Geotrek-admin d'un serveur à l'autre, il faut que la BDD soit sur la même version sur le serveur A et le serveur B.
Donc il suffit d'installer la même version de Geotrek-admin, pour que la structure de la BDD soit la même. 
Si votre Geotrek-admin sur le serveur A est sur une ancienne version, commencez par le mettre à jour sur le serveur A, avant de migrer sa BDD sur le serveur B où vous aurez installer la même version.

Sinon l'inverse. Vous installez l'ancienne version de Geotrek-admin sur la serveur B, vous y migrez la BDD du serveur A, puis vous mettez à jour Geotrek-admin sur le serveur B. Mais je déconseille cette deuxième méthode car des évolutions récentes des dépendances (hors Geotrek) posent des problèmes d'installation des anciennes versions de Geotrek.

Il y a peut-être une troisième méthode qui permet de lancer les migrations d'une BDD Geotrek pour la mettre à jour mais je ne maitrise pas ce sujet.

**Comment by gutard** [comment]
Quel est la versions de Geotrek avec laquelle le dump a été effectué ? Pouvez vous relancer ./install.sh et nous envoyer le fichier install.log ? Attention ! Il contient le mot de passe de la base de données. Pensez à l'effacer du fichier avant de le transmettre.

**Comment by Max-le64** [comment]
Bonjour,

Nous allons revenir sur la 2.24 car le dump est fonctionnel sur celui-ci (du fait que le dump a été crée sur la version 2.24), mais y a t-il un moyen simple de migrer notre base (dump) vers une version actuelle ?

Et préconiser vous  une version sur laquelle s'appuyer ?

Merci d'avance

**Comment by camillemonchicourt** [comment]
Quand on met à jour Geotrek-admin d'une version à une autre, lors de l’exécution du script ``install.sh``, celui-ci vérifie la version en cours et la version cible pour identifier les migrations éventuelles à appliquer au niveau de la BDD. 
Pour appliquer les migrations, le plus simple et la seule méthode que je connaisse est de mettre à jour votre Geotrek-admin. 
Donc si vous avez un Geotrek-admin en version 2.24, mettez le à jour puis faites un dump et ensuite importer ce dump sur une installation nouvelle de la version vers laquelle vous avez mis à jour le serveur initial.

**Comment by camillemonchicourt** [comment]
J'ai pu réaliser des tests de migration et j'ai indiqué une erreur précédemment. 
Quand on migre un Geotrek-admin d'un serveur à un autre, il n'est pas nécessaire que ceux-ci soient dans la même version. 

En suivant la procédure de migration (https://geotrek.readthedocs.io/en/2.22.1/installation.html#server-migration), à la fin on exécute la commande ``make update``. Celle-ci permet justement d'appliquer les scripts de migration si la BDD existante est plus ancienne que la version installée de Geotrek-admin.

Ainsi j'avais un Geotrek-admin 2.29 sur mon serveur initial. J'ai sauvegardé sa BDD. J'ai installé Geotrek-admin 2.32 sur le nouveau serveur. Puis j'ai restauré ma BDD du serveur initial en version 2.29. La commande ``make update`` a alors mis à jour la BDD pour la mettre en version 2.32.
