### ISSUE TITLE
[2.32.4]Problème de coordonnées lors de la génération du mail de signalement pour le mailadmin

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2151]
Version Geotrek-Admin : 2.32.4

Depuis l'installation de cette version, lorsqu'un utilisateur envoie un signalement sur un itinéraire depuis Geotrek-rando, les coordonnées du mail reçu par l'admin ressemble à ceci : 

> ssds(mviadere@openig.org) a signalé un problème.
> Catégorie : Arbre renversé
> Commentaire : dqdq
> 
> Lat : 44,262997 / Lon : 2,983850
> http://www.openstreetmap.org/?mlat=44,262997&mlon=2,983850

Or sur les versions précédentes, il ressemble a ceci : 

> -----Message d'origine-----
> De : info@parc-grands-causses.fr [mailto:info@parc-grands-causses.fr] 
> Envoyé : lundi 10 février 2020 19:30
> À : xxxxxxx;
> Objet : [Geotrek] Signalement de xxxxxxxxx (xxxxxxx)
> 
> 
> xxxxxxxxxxxxx a signalé un problème.
> Catégorie : Arbre renversé
> Commentaire : 3 petits arbres groupés  en travers du chemin
> 
> Lat : 43.8710259256 / Lon : 2.83421516418
> http://www.openstreetmap.org/?mlat=43.8710259256&mlon=2.83421516418

Les coordonnées récupérées sont écrites avec des virgules et non des points, ce qui donne une localisation erronée avec le lien OSM.

**Comment by gutard** [comment]
Il faut corriger le template `geotrek/feedback/templates/feedback/report_email.html`. https://stackoverflow.com/a/58756203 explique que ça ne marche pas et donne une solution. Par ça n'aurait pas dû marcher avant. Mystère.

**Comment by gutard** [comment]
@mviadere-openig, n'hésite pas à proposer une pull request ;)

**Comment by mviadere-openig** [comment]
C'est fait, à mon avis ce n'est pas la bonne solution, mais ça  ne coûte rien d'essayer :D

**Comment by camillemonchicourt** [comment]
@mviadere-openig , à priori fixé dans la 2.33.12 ?

**Comment by mviadere-openig** [comment]
Merci, je vérifierai cela lorsque je ferai la maj de Geotrek.

**Comment by mviadere-openig** [comment]
Le problème a été corrigé avec la 2.33.12
