### ISSUE TITLE
Problème lors de l'install

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2154]
Bonjour,
Actuellement en 2.29.9, j'essaye d'upgrader ma version mais pendant l’installation j'ai systématiquement un "Could not setup Python Environment" peu importe vers quelle version j'upgrade. 
Voici mon log d'install :
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4226270/install.log)
Ça me retourne l'erreur suivante : ValueError: need more than 0 values to unpack
Une piste sur la signification de cette erreur pour m'éclairer ?
Merci d'avance,
Thomas

**Comment by gutard** [comment]
Il faut upgrader avec la dernière version (2.32.5). D'après le log l'install est faite en 2.29.9. Il y a des problèmes d'installation pour toutes les versions <= 2.32.3.

**Comment by thomaspnrhj** [comment]
Merci @gutard, il va falloir que je me lance sérieusement dans l'upgrade d'ubuntu alors...

**Comment by camillemonchicourt** [comment]
Ah oui, le support d'Ubuntu 14 est arrêté depuis Geotrek-admin 2.30.0. 
C'est l'occasion de passer sur un Ubuntu plus récent en effet :-)
De notre côté, quand on change de version d'Ubuntu, on monte un nouveau serveur plutôt que de mettre à jour la version d'Ubuntu sur le serveur. Mais c'est peut-être faisable sur le même serveur
