### ISSUE TITLE
Purge status

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2155]
Je voudrais supprimer les statuts physique et fonciers de mon Géotrek. Quelle est la bonne méthode pour le faire ?

**Comment by camillemonchicourt** [comment]
Tu veux supprimer les données ou bien les typologies de statut ?

**Comment by jeromesourdin** [comment]
Tout !

**Comment by camillemonchicourt** [comment]
A vérifier mais je dirai pour les statuts fonciers : 
- Supprimer de la table ``geotrek.e_t_evenement`` les événements de segmentation dynamique de type ``LANDEDGE``
- Les supprimer ensuite de la table ``foncier.f_t_foncier`` en la vidant
- Vider la table des types de statut foncier ``foncier.f_b_foncier``

Idem pour les statuts physique avec le type d'événement ``PHYSICALEDGE`` et les tables ``foncier.f_t_nature`` et ``foncier.f_b_nature``.

**Comment by gutard** [comment]
Attention à l'intégrité référentielle. A priori il faut inverser les deux premiers points. ou alors faire le 1er avec un CASCADE et du coup le 2ème se fait tout seul avec le 1er.

**Comment by camillemonchicourt** [comment]
OK, comme il y a bien une contrainte entre les 2 tables mais pas de suppression en cascade entre les 2, je pensais que leur suppression était indépendante.

```
CREATE TABLE foncier.f_t_foncier
(
    [...]
    CONSTRAINT f_t_foncier_pkey PRIMARY KEY (evenement),
    CONSTRAINT evenement_refs_id_2891e21b54018747 FOREIGN KEY (evenement)
        REFERENCES geotrek.e_t_evenement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
    [...]
)
```

En effet, c'est plus logique de faire ``foncier.f_t_foncier`` en premier. Merci.
