### ISSUE TITLE
Could not update data

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2158]
Encore une erreur lors de .install.sh lors de la migration de serveur : "Could not update data !"

Dans le log d'install, l'erreur est la suivante : 
pkg_resources.DistributionNotFound: The 'mr.developer' distribution was not found and is required by the application
Makefile:99: recipe for target 'update' failed
make: *** [update] Error 1
+ '[' 2 -ne 0 ']'
+ exit_error 11 'Could not update data !'
+ code=11
+ shift
+ echo_error 'Could not update data !'
+ set +x
+ echo '(More details in install.log)'
(More details in install.log)
+ exit 11

C'est quoi au juste ce mr.developer ? 
Pour rappel je tente une migration sur un serveur Ubuntu 18.04 avec passage d'une version 2.29.9 vers 2.34.5

**Comment by gutard** [comment]
Essaie de supprimer bin/python et de relancer l'install. Si ça ne marche toujours pas, envoie moi le fichier install.log.

**Comment by thomaspnrhj** [comment]
Ca ne fonctionne toujours pas !
Voici le log
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4256386/install.log)

**Comment by relaire** [comment]
Bonjour,
J'ai la même erreur que Thomas, avec un install.log un peu différend. 
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4256680/install.log)
2.29.15 -> 2.32.5 (Ubuntu 16.04.6)

**Comment by LePetitTim** [comment]
Normalement ça refonctionne (sans changement de version de Geotrek). On va devoir épingler une dependance pour ne plus avoir de problèmes.

**Comment by thomaspnrhj** [comment]
Ca marche de mon côté ! Un grand merci pour votre rapidité !
