### ISSUE TITLE
Update DEM / MAJ MNT

### ISSUE THREAD

**Issue by pnrm** [GeotrekCE/Geotrek-admin#2161]
Dans GeotrekAdmin 2.29.15 serveur ubuntu 18.04.3 
Nous devons élargir l'emprise de notre mnt. 

Nous avons utilisé la commande
`./bin/django loaddem --replace ./mnt.tif`
Sans problème par contre

nous avons l'erreur suivante concernant la mise à jour des tronçons au niveau de la base de données
`geotrekdb=# UPDATE geotrek.l_t_troncon SET geom = geom ;
ERROR:  relation "f_t_zonage" does not exist
LINE 1: DELETE FROM e_r_evenement_troncon et USING f_t_zonage z WHER...
                                                   ^
QUERY:  DELETE FROM e_r_evenement_troncon et USING f_t_zonage z WHERE et.troncon = OLD.id AND et.evenement = z.evenement
CONTEXT:  PL/pgSQL function lien_auto_troncon_couches_sig_iu() line 10 at SQL statement
`

**Comment by gutard** [comment]
Il faut régler `search_path=public,django,geotrek,gestion,rando,zonage,foncier,tourisme;`

Cf. issue #1311

**Comment by pnrm** [comment]
Merci

**Comment by pnrm** [comment]
Bonjour,
Je n'ai plus les messages d'erreur lors des commandes
`./bin/django loaddem --replace ./mnt.tif`
`geotrekdb=# UPDATE geotrek.l_t_troncon SET geom = geom ;`
`geotrekdb=#UPDATE geotrek.e_t_evenement SET geom = geom ; `
Mais je me suis rendu compte que les tronçons n'étaient pas à jour pour les altitudes (max min) sur la partie couverte par le nouveau MNT (basé sur la BD ALTI) que j'ai importé, c'est comme si j'étais encore sur l'ancien. Les valeurs lié à l'altitude sont à 0. 
L'itinéraire fait 120 km ce qui rend le tracé compliqué avec les tronçons dont les valeurs de l'altitude sont à zéro. Le navigateur ne répond plus pendant quelques secondes et ça revient. 
Lorsque j'arrive à poser le point d'arrivée au bon endroit, l’enregistrement échoue avec un 504 gateway timeout.
Par contre ca fonctionne bien tant que je suis sur la partie ou les données d'altitude sont à jour.

**Comment by pnrm** [comment]
Bonjour,
Suite au passage à la version 2.33.8. J'ai chargé à nouveau mon mnt et j'ai eu un message d'erreur avec la commande
`sudo geotrek loaddem --replace ./mnt.tif`
J'ai utilisé une autre source pour le mnt ce qui a corrigé le problème d'altitude à 0 sur la nouvelle emprise.
Le problème provenait de mon mnt de départ.
