### ISSUE TITLE
https

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2170]
Bonjour, 
Quelqu'un aurait un exemple de conf nginx pour le ssl ?
Merci :)

**Comment by JeanLenormand** [comment]
Bonjour Jérôme, pour ma part j'ai utilisé Certbot (infos ici : https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx.html). 
Par contre la commande sudo certbot --nginx est refaite après chaque mise à jour...
En espérant que ça pourra aider.
Jean

**Comment by jeromesourdin** [comment]
Bonjour et merci Jean,
Pour ce qui est du certificat, j'ai ce qu'il faut. Par contre, je me demandais comment c'est prévu dans le cadre du l'utilisation de Géotrek. J'ai remarqué la présence d'un dossier `etc/nginx.d/ ` dans le dossier d'install. Est-ce la qu'il faut déposer sa configuration ? Et les certificats ?
Jérôme

**Comment by jeromesourdin** [comment]
Ou je modifie directement le fichier `etc/nginx.conf` ? 
Quelle est la bonne pratique ?

**Comment by camillemonchicourt** [comment]
Il ne faut pas modifier le fichier ``etc/nginx.conf`` qui est le template de configuration NGINX, utilisée pour automatiser la conf NGINX à chaque installation, et qui est refaite à zéro à chaque installation, mise à jour. 
Il y a un fichier pour la surcoucher mais elle a un petit problème depuis quelques temps : https://github.com/GeotrekCE/Geotrek-admin/issues/1878

Je crois qu'il y a désormais une partie du fichier ``settings.ini`` dédiée à la surcouche maison de la configuration NGINX (à la fin du fichier, voir https://github.com/GeotrekCE/Geotrek-admin/blob/master/conf/settings.ini.sample#L55) mais je ne l'ai jamais testée et n'ai pas de retour dessus, si quelqu'un teste ou en sait plus ?

**Comment by camillemonchicourt** [comment]
La surcouche de la configuration NGINX a été revue et corrigée dans la version 2.33 à venir de Geotrek-admin : https://github.com/GeotrekCE/Geotrek-admin/issues/1878
Par contre pour la partie HTTPS, il faut toujours relancer la commande Certbot à chaque mise à jour comme indiqué par @JeanLenormand.

**Comment by camillemonchicourt** [comment]
En effet à chaque mise à jour de Geotrek-admin, ou à chaque relance de la configuration (``sudo dpkg-reconfigure geotrek-admin``), le fichier de configuration NGINX est regénérée à partir du template de base.

Cependant il est possible de surcoucher ce template de base par son propre template de configuration dans le fichier ``/opt/geotrek-admin/var/conf/nginx.conf.in`` (https://geotrek.readthedocs.io/en/master/configuration.html#nginx-configuration).

Du coup, il est possible d'ajouter la surcouche HTTPS dans ce fichier pour qu'elle soit reprise à chaque mise à jour ou regénération de la configuration.

Exemple du fichier ``/opt/geotrek-admin/var/conf/nginx.conf.in`` fourni et testé par @amandine-sahl : 

```
upstream ui_server {
    server unix:/tmp/gunicorn-geotrek.sock fail_timeout=0;
}

upstream api_server {
    server unix:/tmp/gunicorn-geotrek_api.sock fail_timeout=0;
}

add_header Access-Control-Allow-Origin ${RANDO_SERVER_NAME};

server {
    server_name ${SERVER_NAME};
    server_name_in_redirect on;

    access_log /var/log/nginx/geotrek_access.log;
    error_log /var/log/nginx/geotrek_error.log;

    client_max_body_size 10M;

    location /static {
        expires 1d;
        alias /opt/geotrek-admin/var/static;
    }

    location /media/upload {
        expires 1d;
        alias /opt/geotrek-admin/var/media/upload;
    }

    location /media_secure {
        internal;
        expires 1d;
        alias /opt/geotrek-admin/var/media;
    }

    location / {
        proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
        proxy_set_header X-Forwarded-Host ${DOLLAR}host;
        proxy_set_header X-Forwarded-Server ${DOLLAR}host;
        proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;

        proxy_set_header Host ${DOLLAR}http_host;
        proxy_redirect off;

        keepalive_timeout 0;

        location ~ ^/api {
            proxy_pass http://api_server;
            proxy_read_timeout ${TIMEOUT}s;
        }

        proxy_pass http://ui_server;
        proxy_read_timeout ${TIMEOUT}s;
    }
    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/${SERVER_NAME}/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if (${DOLLAR}host = ${SERVER_NAME}) {
        return 301 https://${DOLLAR}host${DOLLAR}request_uri;
    } # managed by Certbot


    listen ${NGINX_PORT};
    server_name ${SERVER_NAME};
    return 404; # managed by Certbot


}
```

En passant, la méthode que l'on a utilisé pour mettre en place le HTTPS sur notre serveur avec Certbot : 

- Au préalable bien avoir renseigné le servername avec son URL (``geotrekdemo.ecrins-parcnational.fr`` par exemple)
- Puis exécuter les commandes : 

```
## Installer Certbot
sudo apt install certbot
sudo apt install python3-certbot-nginx

## Lancer la commande permettant de mettre en place le certificat sur ce domaine et suivre les instructions
sudo certbot --nginx
```

**Comment by camillemonchicourt** [comment]
Attention cependant, si le template fourni par défaut (comme c'est dans le cas dans la 2.46.0 - https://github.com/GeotrekCE/Geotrek-admin/commit/1aee5818b85e15d888d639749e32aaf7966dd900#diff-6da4201f4fd3a350c4b37134b8e875df4624b8ca92c9091d5f0e839aedba2b8d) il vaut mieux répercuter ces évolutions lors de la mise à jour.

C'est le défaut de la solution actuelle ou l'on surcouche tout le template.
