### ISSUE TITLE
RGPD compatibilité sur le module feedback (signalement)

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2183]
Pour rendre Geotrek compatible RGPD, le module feedback doit être remanié.

- Le nom de la personne (champs name) n'est pas indispensable, le champs va être supprimé.
- Le mail est nécessaire (champs email), mais il ne faut pas le garder indéfiniment

Côté Geotrek-rando, nous rajouterons un texte indiquant l'usage de l'email dans le formulaire.

Côté Geotrek-admin, en plus de supprimer le nom, une commande pour supprimer le contenu du champs email des reports de plus de 365 jours (modifiable par une option) est prévue.

**Comment by babastienne** [comment]
Les travaux ont étés réalisés. Le commande Geotrek "erase_emails" existe, supprime les adresses mails associées à des signalements de plus d'un an d'ancienneté, et doit être configurée pour chaque instance via CRON afin de respecter la compatibilité RGPD. Le nom des utilisateurs n'est plus collecté et un encart dans Geotrek-Rando V3 permet de spécifier l'utilisation de l'adresse mail et les conditions de rétractation. Tout semble donc être en place pour rentrer dans le cadre légal côté Geotrek-Admin.

Côté GTR3 il y a toujours cette PR en cours pour rentrer en conformité : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/746
