### ISSUE TITLE
Compatibilité avec l'API Suricate

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2184]
Nous sommes en train de travailler sur la transmission des rapports de signalement à l'API Suricate, avec les données dont nous disposons.

Dans Suricate, le champs "name" n'est plus utilisé, et nous allons le supprimer (cf #2183 ).

Viennent deux informations supplémentaires : l'activité concernée et l'ampleur du problème. Ce seront deux nouveaux modèles.

Par défaut, aucun signalement n'est envoyé à l'API : ce comportement sera modifiable dans les paramètres, ainsi que les paramètres d'authentification, permettant d'envoyer des signalements à Suricate.

**Comment by JoelAtche** [comment]
Il y aura la possibilité d'avoir les flux entre Geotrek-Admin et Suricate dans les deux sens?
Si oui est-ce une demande côté Suricate pour que l'on mette à jour le statut des signalements fait sur Suricate à partir de Geotrek?
Dans le cas de notre plateforme Geotrek des Grands Causses il ne faut pas que nos signalements fait sur notre Geotrek (Rando et admin) remontent sur Suricate! J'ai juste besoin de récupérer ceux fait sur Suricate pour qu'ils soient traité sur le terrain correctement par les gestionnaires du territoire (Asso, Com Com, PNRGC,...) utilisateurs de geotrek-admin Aubrac-Grands Causses. Et s'il le faut je peux me connecter à Suricate pour mettre à jour le statut des signalements quand ils seront traité!

**Comment by camillemonchicourt** [comment]
OK merci pour les précisions. 
@JoelAtche, actuellement l'API Suricate permet uniquement de poster des Signalements depuis un site tiers vers Suricate. C'est donc cette première fonctionnalité (optionnelle) qui est en cours de développement.

**Comment by camillemonchicourt** [comment]
OK, Geotrek-admin peut désormais poster des signalements à Suricate.

Voir le message de @numahell sur la liste de diffusion (https://groups.google.com/g/geotrek-fr/c/47Tj3-T7EK8) : 

> Dans les versions 2.33.13 de Geotrek-admin et 2.24.1 de Geotrek-rando nous avons introduit la possibilité pour Geotrek-admin d'envoyer des signalements reçus depuis Geotrek-rando vers la plateforme Suricate.
> 
> Cette fonctionnalité est optionnelle, pour l'activer, vous aurez besoin d'un identifiant et de clés à demander auprès du Pôle ressources national sports de nature.
> 
> Le fonctionnement est le suivant : côté Geotrek-admin, il faut ajouter les paramètres de clé API décrits dans la documentation, et importer les listes par défaut utilisées par Suricate en ligne de commande.
> Côté Geotrek-rando, il n'y a rien à faire si ce n'est le mettre à jour.
> 
> Lorsque la synchronisation vers Suricate est activée dans Geotrek-admin, les informations demandées par Geotrek-rando évoluent afin de tenir compte des spécificités de Suricate :
> 
> - Activité (activité sportive concernée)
> - Catégorie (type du problème)
> - Ampleur du problème
> - Commentaires
> - Email
> - Géométrie (POINT)
> - Photos
> 
> Cette nouvelle fonctionnalité a été demandée et financée par le département du Gard. D'autres évolutions sont prévues par la suite afin de permettre de récupérer et gérer dans Geotrek-admin les signalements effectués directement sur la plateforme Suricate et non via Geotrek-rando.
> 
> En savoir plus :
> 
> - la plateforme Suricate (https://sentinelles.sportsdenature.fr/)
> - la documentation Geotrek-admin sur le paramétrage de Suricate (https://geotrek.readthedocs.io/en/master/advanced-configuration.html#suricate-support)
