### ISSUE TITLE
Geotrek-Admin-2.32.11 Installation error : Could not setup python environment !

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2187]
Bpnjour à tous !

os : Ubuntu 18.04.4 LTS (Bionic Beaver)

Tentative d'installation de la dernière release : Geotrek-Admin-2.32.11

Message  d'erreur : Error: Referenced option does not exist: django mediaroot

L'install.log en Pj

[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4382108/install.log)

**Comment by mviadere-openig** [comment]
J'ai installé la version 2.32.10 en attendant, ça fonctionne.

**Comment by gutard** [comment]
Pourtant, rien n'a changé dans les versions de paquet ou la procédure d'installation entre la 2.32.10 et la 2.32.11

**Comment by camillemonchicourt** [comment]
@mviadere-openig, si pas plus d'éléments, on ferme ce ticket ?
