### ISSUE TITLE
Erreur lors de l'importation de tronçon dans la bdd

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2189]
os : ubuntu bionic LTS
Geotrek-admin-2.32.10

La ligne de commande dans la bdd : 

INSERT INTO "geotrek"."core_path" ("id","structure_id","draft",geom) VALUES ('1','1','false','01020000206A08000005000000B407D29816F425419CE9B3574D555841836F7B712BF42541E1B3761B3D5558414E824C1133F425417A3E9F73325558418F039FFA36F42541392D38C9285558413B67227D2EF425414DC586D814555841');

Le message d'erreur : 

ERROR:  relation "zoning_city" does not exist
LINE 1: ...ti(ST_Intersection(geom, $1)))).geom AS geom FROM zoning_cit...
                                                             ^
QUERY:  SELECT id, ST_LineLocatePoint($1, COALESCE(ST_StartPoint(geom), geom)) as pk_a, ST_LineLocatePoint($1, COALESCE(ST_EndPoint(geom), geom)) as pk_b FROM (SELECT code AS id, (ST_Dump(ST_Multi(ST_Intersection(geom, $1)))).geom AS geom FROM zoning_city WHERE ST_Intersects(geom, $1)) AS sub
CONTEXT:  PL/pgSQL function lien_auto_troncon_couches_sig_iu() line 19 at FOR over EXECUTE statement

J'ai regardé, il s'agit de la fonction trigger lien_auto_troncon_couches_sig.iu() dans le schéma public à la ligne 18, dans la boucle de la requête sql : 

FOR rec IN EXECUTE 'SELECT id, ST_LineLocatePoint($1, COALESCE(ST_StartPoint(geom), geom)) as pk_a, ST_LineLocatePoint($1, COALESCE(ST_EndPoint(geom), geom)) as pk_b FROM (SELECT code AS id, (ST_Dump(ST_Multi(ST_Intersection(geom, $1)))).geom AS geom FROM zoning_city WHERE ST_Intersects(geom, $1)) AS sub' USING NEW.geom

il faut changer zoning_city par zonage."zoning_city", comme expliqué dans ce post : https://stackoverflow.com/questions/36753568/postgresql-tables-exists-but-getting-relation-does-not-exist-when-querying

J'aurai bien aimé faire une pull request mais malheureusement je n'ai pas trouvé où faire la modification. J'ai réussi à trouvé les différents models utilisés pour faire les migrations mais pas celui du schéma public.

**Comment by camillemonchicourt** [comment]
Non, ce n'est pas ça. C'est toujours le même sujet, il faut bien élargir le search_path de l'utilisateur PostgreSQL quand on manipule la BDD de Geotrek directement, sans passer par l'application.
Voir https://github.com/GeotrekCE/Geotrek-admin/issues/1311

**Comment by mviadere-openig** [comment]
Ok Merci Camille pour l'info.
