### ISSUE TITLE
Logger dans /opt/geotrek-admin/var/log

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2205]
Actuellement il faut faire `sudo journalctl` avec les bonnes options pour récupérer les logs faits par systemd

**Comment by gutard** [comment]
En fait les logs vont bien dans /opt/geotrek-admin/var/log sauf qu'il n'y a souvent rien a logguer.

Par contre, les problèmes de démarrage ne vont pas dans le log de Geotrek vu… qu'il n'a pas encore démarré. C'est systemd qui loggue ces problème. J'ai mis à jour la doc pour indiquer comment regarder les logs en question.

**Comment by camillemonchicourt** [comment]
Thanks (https://github.com/GeotrekCE/Geotrek-admin/commit/792ea63ec1435930c261dec286acbd6512e587c8)
