### ISSUE TITLE
module Sync_rando / Erreur génération certaines fiches rando 

### ISSUE THREAD

**Issue by relaire** [GeotrekCE/Geotrek-admin#2206]
Bonjour,
Je viens de m'apercevoir d"erreurs pour la génération de certaines fiches rando : _31mfailed('tuple' object has no attribute 'width')_ à l'éxécution du module sync_rando
Cette erreur ne se produit pas sur tous les circuits (24 circuits sur les 120 présents)

Vous avez déjà eu un problème similaire ?

Je suis en 2.32.11

Renaud LAIRE / PNR Livradois Forez

**Comment by gutard** [comment]
C'est un bug dans une dépendance de Geotrek (cf. https://github.com/Kozea/WeasyPrint/issues/1050). Pour contourner le problème, il faut ajouter l'attribut `width` à la balise `<svg>` dans le fichier SVG du picto de la pratique. Pour le corriger il faut attendre que la version 52 de WeasyPrint soit sortie et qu'elle soit intégrée à Geotrek.

**Comment by relaire** [comment]
Super ca marche en en modifiant la balise `<svg>`
Merci

**Comment by gutard** [comment]
> Pour le corriger il faut attendre que la version 52 de WeasyPrint soit sortie et qu'elle soit intégrée à Geotrek.

Elle est sortie : https://github.com/Kozea/WeasyPrint/releases/tag/v52
