### ISSUE TITLE
Bad performances when creating a path that intersects a long trek

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2221]

**Comment by camillemonchicourt** [comment]
Le problème a été identifié sur la nouvelle version 2.33. Mais en testant, le problème était déjà présent dans les versions précédentes. Problème similaire en testant sur une version 2.32.5. 
Quand je créé un tronçon coupant un tronçon existant qui n'est utilisé par aucun événement, alors pas de soucis. Quand je créé un tronçon qui coupe un tronçon utilisé par des événements, alors c'est très long, voire ça n'aboutit pas et finit en Timeout. Je n'y vois pas forcément clair si c'est le cas uniquement quand les événements rattachés au tronçon intersecté sont nombreux et longs ou pas. 
A creuser/investiguer.

**Comment by JeanLenormand** [comment]
Même problème sur la version 2.33.7, en voulant raccorder un nouveau tronçon à un tronçon existant qui contient plusieurs événements (Itinéraires parents, étapes, POIs, Contenus Touristiques). 

Après un certains temps de chargement le navigateur affiche une erreur 500 (avec un timeout mis à 7200 au lieu de 300).

La commande htop exécutée sur le serveur lors de l'opération montre que la ram est peu sollicitée, idem pour les processeurs (1 sur 4 à 100%, les autres proche du 0).

Le log geotrek-ui affiche le message suivant :
Jun 06 15:20:59 vps650123 gunicorn[6857]:     num = len(clone)
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self._fetch_all()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self._result_cache = list(self._iterable_class(self))
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
Jun 06 15:20:59 vps650123 gunicorn[6857]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
Jun 06 15:20:59 vps650123 gunicorn[6857]:     cursor = self.connection.cursor()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
Jun 06 15:20:59 vps650123 gunicorn[6857]:     return self._cursor()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self.ensure_connection()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connec
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self.connect()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
Jun 06 15:20:59 vps650123 gunicorn[6857]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connec
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self.connect()
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
Jun 06 15:20:59 vps650123 gunicorn[6857]:     self.connection = self.get_new_connection(conn_params)
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new
Jun 06 15:20:59 vps650123 gunicorn[6857]:     connection = Database.connect(**conn_params)
Jun 06 15:20:59 vps650123 gunicorn[6857]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Jun 06 15:20:59 vps650123 gunicorn[6857]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jun 06 15:20:59 vps650123 gunicorn[6857]: django.db.utils.OperationalError: FATAL:  the database system is in recovery mode
Jun 06 15:20:59 vps650123 gunicorn[6857]: FATAL:  the database system is in recovery mode

Comment puis je solutionner le fait d'avoir la databse en recovery mode ? A savoir qu'il m'est toujours possible de créer de nouveaux objets.

Merci,

Jean

**Comment by gutard** [comment]
D'après ce que je lis le recovery mode se déclenche entre autres si un des processus de postgresql crashe et il se termine tout seul quand le recovery est fini. Il faudrait regarder les logs de postgresql pour en savoir plus. Une cause possible de crash de postgresql peut être le OOM killer. Un coup d'oeil au log système permettrait de valider ou pas cette hypothèse.

**Comment by JeanLenormand** [comment]
Merci @gutard pour ton retour.

Je ne suis pas expert en la matière, mais je n'ai pas su trouver si un process avait été arrêté par le OOM Killer. Je n'ai pas de kern.log lié à la période, ni d'info en exécutant $dmesg | less dans la console.

Néanmoins, voici les logs qui correspondent à la période durant laquelle l'ajout de tronçon a été effectué. Je peux toujours rajouter un tronçon, mais lorsque je veux le raccorder à un tronçon existant le problème se pose à nouveau.

[geotrek_error.log](https://github.com/GeotrekCE/Geotrek-admin/files/4750783/geotrek_error.log)
[geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/4750785/geotrek-ui.log)
[postgresql.log](https://github.com/GeotrekCE/Geotrek-admin/files/4750786/postgresql.log)
[sys.log](https://github.com/GeotrekCE/Geotrek-admin/files/4750787/sys.log)

**Comment by gutard** [comment]
- Topologies inutiles qui traînent dans la base ?
- Nécessité de draper les edges ?

**Comment by camillemonchicourt** [comment]
Dans le cas identifié initialement sur le test sur les données PNE, ça tombait en timeout en enregistrant un nouveau tronçon coupant un tronçon utilisé par de longs événements (à priori). Je ne sais pas si le problème de @JeanLenormand est la même chose avec sa BDD qui tombe en recovery mode.

**Comment by gutard** [comment]
Le problème est que quand le serveur timeoute sur la création ou l'édition d'une topologie, il laisse une topologie temporaire (kind='TMP'). Ces topologies sont recalculées qaund on édite un de leurs tronçons et si il y a beaucoup de topologies temporaires (plusieurs dizaines en l'occurrence) ça prend beaucoup de temps.

Fix rapide (à appliquer avec précaution, après backup, je décline toute responsabilité en cas de perte de données) pour ceux qui le souhaitent :
```
DELETE FROM core_pathaggregation USING core_topology \
       WHERE core_topology.id=topo_object_id AND kind IN ('TMP', 'TOPOLOGY');

DELETE FROM core_topology \
       WHERE kind IN ('TMP', 'TOPOLOGY');
```

Cependant, tout nouveau timeout à l'édition d'un tronçon recréera des nouvelles topologies temporaire, même si c'est beaucoup moins probable depuis la version 2.33 qui améliore les performances.

Fix définitif prévu :
* Faire le nettoyage dans une migration ?
* Encadrer la création/édition d'une topologie dans une transaction SQL

Piste pour aller plus loin :
* Ne pas créer de topologies temporaires en base ?
* Ne pas drapper les CityEdge/DistrictEdge ?

**Comment by camillemonchicourt** [comment]
OK merci pour ces éléments et débuts de résolution.
Du coup je comprends la suppression des évènements de type TMP mais pourquoi aussi ceux de type TOPOLOGY ?

En effet encapsuler les insertion et modification dans une transaction annulée globalement en cas de timeout ou de plantage me semble le mieux.

**Comment by gutard** [comment]
> pourquoi aussi ceux de type TOPOLOGY

TOPOLOGY est devenu TMP quand on a amélioré les perfs sur l'édition des topologies. Les événements qui ont été créés avant la 2.33 sont de type TOPOLOGY et après de type TMP. Les topologies non temporaires sont de type TREK, POI, etc.

**Comment by camillemonchicourt** [comment]
OK, merci pour les précisions.

**Comment by camillemonchicourt** [comment]
Le soucis des topologies temporaires est corrigé dans la version 2.48.0, et ainsi il n'en sera plus créées de nouvelles.
Est-il par contre conseillé de supprimé manuellement celles qui se seraient accumulées dans la BDD auparavant ?
Ou c'est géré par les migrations automatiquement ?
Si il faut le faire manuellement, le SQL indiqué plus haut est celui à appliquer ?

Merci.

**Comment by gutard** [comment]
> Est-il par contre conseillé de supprimé manuellement celles qui se seraient accumulées dans la BDD auparavant ?
> Ou c'est géré par les migrations automatiquement ?

La PR https://github.com/GeotrekCE/Geotrek-admin/pull/2487 le fait automatiquement. J'ai pris un peu de temps pour regarder ça de près car on avait un autre souci avec les intervention qui aurait pu conduire à supprimer des données utiles. C'est toujours assez flippant de faire une migration qui supprime des données.

**Comment by camillemonchicourt** [comment]
Oui c'est clair, avec tout l'historique et les différents contextes, c'est complexe en effet.
Merci d'avoir néanmoins automatisé le nettoyage pour tous.

**Comment by camillemonchicourt** [comment]
OK j'ai installé la 2.50.0 sur notre serveur de DEMO.
Cette version fait le ménage dans les topologies temporaires éventuellement présentes dans la BDD.

Au moment de la migration, j'ai eu ce message : 

```
Migrate database

  WARNING! Updated 4 topologies directly linked to interventions with a wrong kind
```

Mais là j'ai pas bien compris ce que ça a fait ? Et si il faut reprendre ces 4 topologies ?

Sur la production PNE, j'en avais 46 : 

```
Migrate database

  WARNING! Updated 46 topologies directly linked to interventions with a wrong kind
```

**Comment by gutard** [comment]
> Mais là j'ai pas bien compris ce que ça a fait ?

Ça change le champ kind de la table core_topology de "TOPOLOGY" vers "INTERVENTION" pour toutes les interventions définie sur le réseau (et non en référence sur une autre topologie existante).

> Et si il faut reprendre ces 4 topologies ?

Non, rien à faire. Ça marchait avant et ça continue à marcher au moins aussi bien. C'est juste pour faire le tri entre les topologies avec kind="TOPOLOGY" à supprimer (temporaires) et celles à garder (interventions).
