### ISSUE TITLE
Suppresion dans la table trekking_trek_portal

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2245]
Lorsqu'on supprime un trek, si on a définit un portal pour ce trek, la suppression ne se fait pas dans la table trekking_trek_portal, problème de trigger ?

**Comment by gutard** [comment]
Non, quand on supprime un trek, ça passe juste le champ deleted à True. Ça masque le trek dans l'interface web de Geotrek-admin mais il n'est pas réellement supprimé de la base. Donc le lien dans la table trekking_trek_portal est également conservé.

Il est question de supprimer ce fonctionnement.
