### ISSUE TITLE
Problème filtre 2.33.5

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2246]
Je suis passé dans la dernière version, les filtres ne semblent pas fonctionné pour les modules valorisation (itinéraires, Pois, infos touristiques..) 
![image](https://user-images.githubusercontent.com/19687397/81935613-34941b80-95f1-11ea-93eb-c4432c0f8476.png)

**Comment by camillemonchicourt** [comment]
Je viens de tester et j'ai le même problème en version 2.33.4.

**Comment by gutard** [comment]
Pb qui concerne effectivement les itinéraires et les POI, introduit dans la version 2.33.4 et présent également en 2.33.5

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.33.7.
