### ISSUE TITLE
Problème catégorie/type 2.33.5

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2247]
Je suis passé dans la dernière version, les type de mes POIs et les catégories de mes contenus touristiques ont été complétement mélangés. 
Exemple : mes Pois de type "Flore" sont passés dans le type "Point de vue", les "Restaurants" sont passés en "Activités de pleine nature". Après ce qui est bizarre, c'est que j'ai des types qui sont toujours bons (Les Pois "Faune" restent "Faune")
Une explication ? 
C'est vraiment problématique, est-ce que je dois tout modifié dans la base ou est-ce qu'une prochaine version peut corriger ça ?

**Comment by thomaspnrhj** [comment]
Les types/catégories ne sont en fait pas les nôtres, la migration n'a pas du reprendre les nôtres

**Comment by camillemonchicourt** [comment]
Aille, je viens de regarder sur mon instance de test en 2.33.4. Pas de soucis pour les POI mais j'avais gardé les typologies de POI par défaut. 

Pas de gros soucis au niveau des contenus touristiques, par contre j'avais une catégorie "Produits du terroir" avec 75 contenus touristiques avant la migration. Après migration, j'ai encore cette catégorie mais avec plus qu'un seul contenu. Et une catégorie "Produits" a été créée et mes 73 autres contenus touristiques y ont été basculés. Il semble me manquer un contenu touristique de type produit en passant, mais ça il faut que je vérifie.

**Comment by gutard** [comment]
Gros gros bug effectivement. As-tu bien fait un backup comme le propose le script (_"You should backup your database before."_) ?

Si oui, il faudrait :
- restaurer ce backup (les modifications faites depuis seront évidemment perdues si il y en a eu)
- puis lancer `sudo geotrek migrate`

Si non, il faut effectivement tout corriger à la main.

La version 2.33.6 qui va sortir d'ici peu corrigera le problème mais pour ceux qui ont installé les versions 2.33.3, 2.33.4 ou 2.33.5 avec une base de donnée existante c'est malheureusement trop tard.

**Comment by thomaspnrhj** [comment]
J'avais fait un snapshot mais je l'ai remplacé depuis... Bon je vais faire à la main, j'ai encore mon ancienne instance avant migration sur mon nouveau serveur donc ça devrait aller vite.
Il y a également les thèmes des itinéraires qui ont été impactés. 
Je vais modifier tourisme_touristiccontenttype, trekking_poitype, trekking_trek_theme. Il y a eu d'autres tables impactés ?

**Comment by gutard** [comment]
trekking_trek_theme n'est pas impactée. C'est common_theme qui l'est.

Seuls les éléments qui avaient été modifiés sont impactés. Les éléments ajoutés ne l'ont a priori pas été.

La liste complète des tables impactées:

- auth_group
- common_filetype
- common_organism
- common_theme
- core_comfort
- core_network
- core_pathsource
- core_stake
- core_usage
- diving_difficulty
- diving_level
- diving_practice
- feedback_reportcategory
- feedback_reportstatus
- infrastructure_infrastructurecondition 
- infrastructure_infrastructuretype
- land_landtype
- land_physicaltype
- maintenance_contractor
- maintenance_interventiondisorder
- maintenance_interventionjob
- maintenance_interventionstatus
- maintenance_interventiontype
- maintenance_projectdomain
- maintenance_projecttype
- sensitivity_sportpractice
- signage_bladetype
- signage_color
- signage_direction
- signage_sealing
- signage_signagetype
- tourism_informationdesktype
- tourism_reservationsystem
- tourism_touristiccontentcategory
- tourism_touristiccontenttype
- tourism_touristiceventtype
- trekking_accessibility
- trekking_difficultylevel
- trekking_poitype
- trekking_practice
- trekking_route
- trekking_servicetype
- trekking_treknetwork
- trekking_weblinkcategory
- zoning_restrictedareatype

**Comment by camillemonchicourt** [comment]
OK je n'avais pas du tout identifié ce soucis de migration des données car on était pas mal resté sur les catégories de base. :-/
Pourtant on a fait pas mal de tests et de corrections avant la sortie de la 2.33.
Merci d'avoir testé et remonté ce bug. 
La marche étant haute entre la version précédente et celle-ci, il est important de bien sauvegarder la BDD + snapshot si possible et de tout vérifier après migration.

Après ça, je pense qu'on a fait bien le tour des corrections de cette migration, mais là en effet l'idéal serait de remonter la BDD avant migration (https://geotrek.readthedocs.io/en/master/maintenance.html#application-backup)

**Comment by thomaspnrhj** [comment]
Ouf j'ai retrouvé un backup de fin avril, je vais pouvoir remonter ma BDD. Je teste demain la manip donnée par Gaël.
