### ISSUE TITLE
Tri dans le journal

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2253]
Lorsqu'on réalise un tri sur la colonne date dans le journal, le tri se fait uniquement sur le numéro du jour, indépendamment du mois et de l'année : 
![image](https://user-images.githubusercontent.com/19687397/82095410-41069a00-96ff-11ea-8a47-07b47c727884.png)

**Comment by camillemonchicourt** [comment]
Oui similaire à https://github.com/GeotrekCE/Geotrek-admin/issues/1973

**Comment by thomaspnrhj** [comment]
Ok j'avais pas vu, desolé
