### ISSUE TITLE
Upgrade Geotrek admin depuis version 2.29.15

### ISSUE THREAD

**Issue by pnrm** [GeotrekCE/Geotrek-admin#2265]
Bonjour,
os Ubuntu server 18.04
J'ai suivi la nouvelle méthode pour mettre à jour Geotrek-Admin à partir d'une version inférieur à la 2.32
En exécutant `./install.sh`  dans le répertoire de ma version actuelle 2.29.15
j'ai le message d'erreur 
`'Could not setup python environment !'`
Voir mon install.log
[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/4683457/install.log)

**Comment by gutard** [comment]
Je dirais qu'il faut installer la version 2.32.2 avec l'ancienne méthode et après ça devrait passer.

Autre solution (en shell, depuis le répertoire de l'install actuelle) :
```
sudo rm -f /etc/nginx/sites-enabled/geotrek
sudo rm -f /etc/nginx/sites-available/geotrek
sudo rm -f /etc/supervisor/conf.d/supervisor-convertit.conf
sudo rm -f /etc/supervisor/conf.d/supervisor-geotrek-api.conf
sudo rm -f /etc/supervisor/conf.d/supervisor-geotrek-celery.conf
sudo rm -f /etc/supervisor/conf.d/supervisor-geotrek.conf
sudo rm -f /etc/supervisor/conf.d/supervisor-screamshotter.conf
sudo supervisorctl reload
sudo mkdir -p /opt/geotrek-admin/var/media
sudo cp -r --preserve=mode,timestamp var/media/* /opt/geotrek-admin/var/media/
sudo mkdir -p /opt/geotrek-admin/var/conf/extra_locale /opt/geotrek-admin/var/conf/extra_templates
sudo cp geotrek/settings/custom.py /opt/geotrek-admin/var/conf/
sudo sed -i 's/^from \.prod import \*$/# from .prod import */' /opt/geotrek-admin/var/conf/custom.py
sudo cp bulkimport/parsers.py /opt/geotrek-admin/var/conf/
sudo cp -r geotrek/locale/* /opt/geotrek-admin/var/conf/extra_locale/
sudo cp -r var/media/templates/* /opt/geotrek-admin/var/conf/extra_templates/
curl https://packages.geotrek.fr/install.sh | bash
```

Par contre, ça va poser des questions pendant l'installation et il faudra savoir répondre exactement la même chose que dans l'installation actuelle (mot de passe de la base, etc.)

Tout ça est un mauvais moment à passer mais après c'est prévu pour que les mises à jour soient beaucoup plus simples.

Dans tous les cas : faire une sauvegarde de la base de données avant la manip.

**Comment by camillemonchicourt** [comment]
A noter cependant que tu dois exécuter un ``./install.sh`` uniquement si tu as mis à jour ta version d'Ubuntu (de la version 16 à 18 par exemple) avant de faire la mise à jour de Geotrek-admin.
Si ton Geotrek-admin tournait déjà sur un Ubuntu 18, alors tu peux lancer directement la migration ``curl https://packages.geotrek.fr/migrate.sh | bash`` sans rencontrer ce soucis. 

A noter aussi une fois que tu auras fait ta migration vers la version 2.33, quelques points éléments à prendre en compte : https://github.com/GeotrekCE/Geotrek-admin/pull/2241/files#diff-548eb9ce4cac8e13a1238ad703272931R122-R134

**Comment by gutard** [comment]
> uniquement si tu as mis à jour ta version d'Ubuntu

D'après le install.log fourni c'est le cas.

**Comment by pnrm** [comment]
Merci pour votre retour.
Je n'étais pas en version 16 avant, mon serveur a été installé avec une version 18. 
Mais si je lance la ligne de commande
`curl https://packages.geotrek.fr/migrate.sh | bash`
Voici les logs
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/4687338/systemd-geotrek-ui.log)

**Comment by gutard** [comment]
> Je n'étais pas en version 16 avant, mon serveur a été installé avec une version 18.

OK. Dans ce cas, comme le dit Camille il ne fallait effectivement pas lancer le ./install.sh. La doc dit juste qu'il faut s'assurer que Geotrek fonctionne avant de lancer la mise à jour. C'est uniquement dans le cas contraire, et en particulier quand on vient de mettre à jour la distribution qu'il est utile de lancer ./install.sh. Là ça a fait plus de mal que de bien.

Il faudrait enlever la ligne `from .prod import *` du fichier `/opt/geotrek-admin/var/conf/custom.py` et relancer.

**Comment by pnrm** [comment]
J'avais fait un snapshot de ma vm avant de lancer la mise à jour.
J'ai pu mettre à jour geotrek-admin vers la version 2.32.11 avec l'ancienne méthode sans problèmes.
Lorsque je lance la ligne de commande  avec la version 2.32.11 installée
`curl https://packages.geotrek.fr/migrate.sh | bash`
ça me donne les logs ci-dessous, 
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/4690883/systemd-geotrek-ui.log)

**Comment by camillemonchicourt** [comment]
Si tu étais déjà en Ubuntu 18 avec un Geotrek-admin, il n'était pas nécessaire de passer par la version 2.32, tu pouvais lancer directement la migration en 2.33, mais c'est pas grave.

Le petit soucis que tu rencontres est celui indiqué par Gaël plus haut. Le script ``migrate.sh`` est censé commenter la première ligne ``from .prod import *`` du fichier de configuration avancée ``custom.py``, mais il n'a pas du réussir le faire. J'ai rencontré ce même problème dans une de mes migrations.

Donc supprime la première ligne du fichier ``/opt/geotrek-admin/var/conf/custom.py`` à la main (``from .prod import *``) puis relance la mise à jour de la configuration avec la commande ``sudo dpkg-reconfigure geotrek-admin``.

**Comment by gutard** [comment]
> Si tu étais déjà en Ubuntu 18 avec un Geotrek-admin, il n'était pas nécessaire de passer par la version 2.32

Sauf que `./install.sh` a été lancé, ce qui a cassé l'installation actuelle et c'est ça qui a obligé à passer en 2.32.

**Comment by pnrm** [comment]
J'avais réalisé un snapshot avant de lancer `./install.sh`. Donc je suis reparti d'une installation propre. En effet j'aurais pu me passer de la version 2.32.
Finalement l'information qui me manquait pour la migration était la commande :
puis relance la mise à jour de la configuration avec la commande `sudo dpkg-reconfigure geotrek-admin`
Merci à vous deux

**Comment by camillemonchicourt** [comment]
Problème de la ligne ``from .prod import *`` non supprimée dans certains cas lors du ``migrate.sh`` réglé par https://github.com/GeotrekCE/Geotrek-admin/pull/2295
