### ISSUE TITLE
[Question]Problème pratique signalement

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2272]
Bonjour,

Depuis la version 2.33, le champ nom n'existe plus dans le signalement ce qui est une bonne chose niveau RGPD, mais qui est moins pratique lors de son utilisation.

Comme me l'a précisé Joël Atché, le seul moyen pour parler d'un signalement, c'est d'utiliser l'adresse mail ou bien son numéro qui s'affiche dans l'url.

Est-ce qu'il serait envisageable de mettre un champ avec le numéro du signalement (comme c'est le cas avec les tronçons par exemple) ?

**Comment by camillemonchicourt** [comment]
Et aussi vu qu'il n'y a plus de nom aux signalements, dans la liste des signalements, on ne peut plus cliquer sur l'objet pour afficher sa fiche détail ?

**Comment by camillemonchicourt** [comment]
Corrigé, on clique désormais sur l'adresse email
