### ISSUE TITLE
Erreur de génération des pdf

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2277]
Bonjour,
J'ai un soucis de génération des pdf sur mon serveur de Prod (pas sur celui de Test...). Erreur 500.
Le log me dis un timeout : 
`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`
Auriez-vous une idée ?

**Comment by jeromesourdin** [comment]
Je suspect un problème de parefeu... Auriez-vous une idée sur comment je pourrais voir ou cela bloque précisément ?

**Comment by jeromesourdin** [comment]
J'ai évolué, maintenant j'ai ça :
`Request on http://localhost:8000/?url=https%3A//geotrek.cotesdarmor.fr/trek/197077/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520636%252C%2520%2522height%2522%253A%2520636.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Scan%2520Express%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content

AssertionError
Request on http://localhost:8000/?url=https%3A//geotrek.cotesdarmor.fr/trek/197077/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520636%252C%2520%2522height%2522%253A%2520636.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Scan%2520Express%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content

Django Version: 2.2.12
Python Executable: /opt/geotrek-admin/bin/python Python Version: 3.6.9 Python Path: ['/', '/', '/opt/geotrek-admin/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/opt/geotrek-admin/lib/python3.6/site-packages']
Server time: ven, 12 Jui 2020 14:05:33 +0200 Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.gis',
 'crispy_forms',
 'compressor',
 'djgeojson',
 'django_filters',
 'tinymce',
 'easy_thumbnails',
 'mapentity',
 'paperclip',
 'leaflet',
 'rest_framework',
 'rest_framework_gis',
 'rest_framework_swagger',
 'embed_video',
 'django_celery_results',
 'colorfield',
 'geotrek.cirkwi',
 'geotrek.authent',
 'geotrek.common',
 'geotrek.altimetry',
 'geotrek.core',
 'geotrek.infrastructure',
 'geotrek.signage',
 'geotrek.maintenance',
 'geotrek.zoning',
 'geotrek.land',
 'geotrek.trekking',
 'geotrek.tourism',
 'geotrek.flatpages',
 'geotrek.feedback',
 'geotrek.api',
 'geotrek.sensitivity',
 'raven.contrib.django.raven_compat')
Installed Middleware:
('raven.contrib.django.middleware.DjangoRestFrameworkCompatMiddleware',
 'raven.contrib.django.middleware.SentryMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'geotrek.authent.middleware.LocaleForcedMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'geotrek.common.middleware.APILocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'geotrek.authent.middleware.CorsMiddleware',
 'mapentity.middleware.AutoLoginMiddleware')


Traceback:

File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py" in download_to_stream
  139.             source = get_source(url, headers)

File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py" in get_source
  127.     assert len(source.content) > 0, content_error

Exception Type: AssertionError
Exception Value: Request on http://localhost:8000/?url=https%3A//geotrek.cotesdarmor.fr/trek/197077/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520636%252C%2520%2522height%2522%253A%2520636.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Scan%2520Express%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content Request data not supplied
`

**Comment by camillemonchicourt** [comment]
Les messages ressemblent à https://github.com/GeotrekCE/Geotrek-admin/issues/1578

**Comment by jeromesourdin** [comment]
Après trois jours à chercher dans tout les sens... Nous avons trouvé la solution ! Merci @LePetitTim ! 
J'avais essayé toutes les modification dans le /etc/hosts sauf celle-ci : 
`127.0.0.1   geotrek.cotesdarmor.fr`

**Comment by pierreloicq** [comment]
Bonjour Jérôme,
J'ai le même bug que toi mais la solution que tu donnes n'est pas effective chez moi. 
Pourrais-tu me dire quels paramètres tu as dans le fichier /opt/geotrek-admin/var/conf/env ?
POSTGRES_HOST
SERVER_NAME
RANDO_SERVER_NAME
CONVERSION_HOST
CAPTURE_HOST

Et les contenus de tes fichiers
/etc/hosts 
/etc/hostname
/etc/hosts.allow

Merci d'avance
