### ISSUE TITLE
Problème nginx geotrek 2.33 (NameError: name 'gettext_noop' is not defined)

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2278]
Bonjour, le boulet de service est de retour, ça devait forcément arriver ! :)

Geotrek-admin =>2.33

J'ai fait l'upgrade d'un serveur Geotrek-Admin < 2.33. J'ai passé l'ubuntu en 18.04, et suivi toutes les manipulations à faire, aucun problème.Par contre error 500 quand je veux affihcer la page du Geotrek-admin.

C'est au niveau de nginx le souci, voici le message (fichier joint ci-dessous) quand je fais la commande sudo dpkg-reconfigure geotrek-admin et que j'ai fini de remplir le formulaire : 

[log_erreur.txt](https://github.com/GeotrekCE/Geotrek-admin/files/4765100/log_erreur.txt)

J'en profite pour mettre aussi les fichiers : 

/var/log/nginx/geotrek_access.log 
[geotrek_access.log](https://github.com/GeotrekCE/Geotrek-admin/files/4765124/geotrek_access.log)

/var/log/nginx/geotrek_error.log
[geotrek_error.log](https://github.com/GeotrekCE/Geotrek-admin/files/4765127/geotrek_error.log)

J'ai vérifié au niveau des fichiers nginx, tout est clean. à part une erreur de remplissage de formulaire je ne vois pas d'où ça peut venir. 

Si vous avez besoin d'autres fichiers n'hésitez pas. Merci encore !

**Comment by camillemonchicourt** [comment]
Sans certitude, il me semble que tu as des problèmes dans ta configuration. Dans ton fichier de configuration avancée ``/opt/geotrek-admin/var/conf/custom.py`` je dirai. Ou sinon dans le fichier de configuration avancée ``/opt/geotrek-admin/var/conf/env``.

Tu peux joindre ces fichiers (en masquant bien les infos de connexion à la BDD avant de le publier ici) ?

**Comment by mviadere-openig** [comment]
Alors, j'ai fouillé un peu de mon côté, ce 'gettext_noop' me disait quelque chose, et effectivement il était bien dans le custom.py : 
[custom.py.old.txt](https://github.com/GeotrekCE/Geotrek-admin/files/4770239/custom.py.old.txt)

C'est une vieille configuration des fond de cartes récupéré du serveur des Grands Causses que je n'avais jamais pris le temps de changer car ça fonctionnait jusqu'à maintenant.

Du coup j'ai remis l'affichage des fonds de cartes correctement : 
[custom.py.txt](https://github.com/GeotrekCE/Geotrek-admin/files/4770250/custom.py.txt)

Ce qui m'amène sur une nouvelle erreur : 
[error_2.txt](https://github.com/GeotrekCE/Geotrek-admin/files/4770256/error_2.txt)

J'ai donc regardé le fichier /opt/geotrek-admin/var/conf/env pour voir si l'erreur ne viendrait pas de là, là seule chose que j'ai vu c'est que le mot de passe de la bdd est complètement différent. J'ai compris après coup que pendant la configuration, le mot de passe ne s'affiche pas (par sécurité) même si on l'écrit, (ce qui porte un peu à confusion au début). J'ai donc relancé la configuration, modifié le mot de passe, mais toujours la même erreur. 


Voici le /opt/geotrek-admin/var/conf/env :
[env.txt](https://github.com/GeotrekCE/Geotrek-admin/files/4770376/env.txt)

Le mot de passe est bien modifié, je suppose donc que ça vient d'ailleurs.

**Comment by mviadere-openig** [comment]
Le problème semble venir pour le moment d'un problème d'installation, j'ai décidé de faire un backup de la machine et de rententer l'installation au propre.
