### ISSUE TITLE
[Questions] Ajouter des secteurs de balisages sur un itinéraire ?

### ISSUE THREAD

**Issue by Max-le64** [GeotrekCE/Geotrek-admin#2279]
Bonjour,

Je voulais savoir dans quel module de Geotrek admin, pouvons nous ajouter des secteurs de balisages ?

Dans notre cas ce serait par exemple intégrer au GR10 des secteurs de balisages (GR10 A, B, C, ...) avec le nom des personnes ou structures qui s'occupent des balisages.

J'ai aussi une deuxième question, qu'elle est la différence entre le module Sentiers et itinéraires ?

Merci d'avance pour vos réponses

**Comment by camillemonchicourt** [comment]
Bonjour, il n'y a pas de module dédié au balisage dans Geotrek-admin.
Par contre il est possible d'associer un "RESEAU" tronçon par tronçon. 
Et il est possible d'affecter des STATUTS (foncier, physique, gestionnaire, compétence) dans le module STATUTS. Vous pouvez peut-être répondre à votre besoin par le module STATUT dans gestionnaire, mais c'est en lien avec des organismes, pas des personnes. Il est possible de réfléchir à des développements complémentaires pour pouvoir gérer le balisage.

Plus de détails sur les modules : https://geotrek.readthedocs.io/en/latest/user-manual.html#gestion-des-sentiers

Les itinéraires sont les randonnées que l'on valorise au public. Plusieurs itinéraires peuvent avoir des tronçons communs.
Les sentiers sont une notion de gestionnaire pour identifier des ensembles de tronçons. Un tronçon n'appartient qu'à un seul sentier (de gestion) donc dans la pratique.

**Comment by Max-le64** [comment]
D'accord je comprend mieux et je vais voir ce que je peux faire avec le module "STATUTS".

Merci pour votre réponse
