### ISSUE TITLE
[QUESTIONS] Erreurs 504 Gateway Time Out

### ISSUE THREAD

**Issue by Max-le64** [GeotrekCE/Geotrek-admin#2281]
Bonjour,

Je voulais savoir si il y avait la possibilité d'augmenter le temps de Time out sur Geotrek ? 
Car le soucis que je rencontre actuellement, c'est que je crée un itinéraire qui est très long donc beaucoup de données et à chaque fois que je veux sauvegarder ça charge et j'ai une erreur "504 Gateway Time code".

Autre chose, est-il possible d’intégrer un flux WMS provenant de l'IGN de l'urbanisme et si oui est-ce que ça transfère les infos sur Geotrek ( infos sur les zones) ?

Je vous remercie d'avance pour votre réponse

**Comment by camillemonchicourt** [comment]
Depuis la version 2.33, le timeout est défini dans la configuration basique, éditée avec la commande ``sudo dpkg-reconfigure geotrek-admin`` (voir https://geotrek.readthedocs.io/en/master/configuration.html).
Quelques compléments dans https://github.com/GeotrekCE/Geotrek-admin/blob/c05523f3fd7b56921c5fb4cf1a29a0d48f1c566e/docs/configuration.rst

Les fonds de carte affichés dans Geotrek-admin sont paramlétrables dans la configuration avancée (fichier custom.py), voir https://geotrek.readthedocs.io/en/master/advanced-configuration.html#options-admin

Pour le "transfert des infos sur Geotrek" je ne comprends ce que vous entendez ?
Si on ajoute un flux carto, alors on peut afficher le fond de carte sous forme d'image sur les cartes.

**Comment by Max-le64** [comment]
D'accord je vais voir ça.

Excusez moi je reformule ma question : Si on déclare un flux provenant, par exemple, du Géoportail de l'urbanisme, outre l'affichage du plan (zones du PLU, servitudes…) est-il possible soit de l'interroger, soit d'avoir accès par un biais quelconque, au règlement des zones ?
Sinon que conseillez vous pour afficher un PLU ou un zonage ZNIEFF ET avoir accès au règlement associé ?

Merci d'avance

**Comment by camillemonchicourt** [comment]
OK dans ce cas, c'est en effet différent. Il s'agit d'accéder aux données vectorielles et attributaires d'urbanisme. A voir au niveau IGN ce qui est possible. 
Ensuite au niveau de Geotrek-admin, il est possible d'ajouter autant de zonages que l'on souhaite, avec tous les types de zonage souhaités dans les tables ``zoning_restrictedarea`` et ``zoning_restrictedareatype``.
Voir https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/data-model/zoning.pdf
Chaque zonage a un type et un nom. Tous les objets de Geotrek-admin (tronçons, itinéraires, signalétique, POI, interventions....) sont intersectés automatiquement avec les zonages et cette informations calculée est affichée sur les fiches de chaque objet. 

Autre possibilité, si on est dans une problématique foncière, utiliser le module Statut foncier. Il permet de définir en segmentation dynamique (ensembles de tronçons complets ou partiels) le type foncier de tronçons (privé, communal, domanial...), et d'y renseigner éventuellement le propriétaire et si il est conventionné ou non.
Voir la table ``land_landedge`` (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/data-model/land.pdf).

Si le besoin est plus spécifique, il est possible de l'envisager par ailleurs (QGIS, PostGIS ou autre), ou d'envisager un développement dédié.

**Comment by gutard** [comment]
> Car le soucis que je rencontre actuellement, c'est que je crée un itinéraire qui est très long donc beaucoup de données et à chaque fois que je veux sauvegarder ça charge et j'ai une erreur "504 Gateway Time code".

Ce problème est corrigé depuis la version https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.33.3
