### ISSUE TITLE
Nom des communes absent de l'export CSV des Treks

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2286]
Tout est dans le titre :).
Dans la colonne Communes, j'ai : 

Communes
--
[, , , , , , , ]
[, ]
[]
[, ]
[, , , , , , , ]
[, , , , , , , , ]
[, ]
[, , , , , ]
[, , , , , ]
[, ]

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
up :)

**Comment by jeromesourdin** [comment]
Bonjour,
Est-ce que vous avez pu voir ce problème ?

**Comment by camillemonchicourt** [comment]
Oui confirmé.
Ca doit être un petit soucis dans la définition des exports des randos.
Vous pouvez corriger le bug si vous le souhaitez ou financer sa correction.

**Comment by LePetitTim** [comment]
Version 2.38.3 disponible résolvant le problème.

**Comment by camillemonchicourt** [comment]
Je ré-ouvre car il y a le même soucis dans les exports CSV des POI. Testé en 2.39.0.
Et idem dans d'autres exports d'autres modules ?

**Comment by camillemonchicourt** [comment]
Même soucis dans l'export CSV des POI pour la liste des itinéraires, des secteurs et des zonages qui sont vides.

**Comment by camillemonchicourt** [comment]
OK pour les exports POI dans la 2.80.0
