### ISSUE TITLE
Synchro / Revoir filtres par portail

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2288]
Fonctionnement actuel : 
- Si je lance une synchro en filtrant sur un portail, cela remonte aussi les objets pour lesquels aucun portail n'est défini (voir https://github.com/GeotrekCE/Geotrek-admin/issues/2144#issuecomment-586346338)
- Si je ne filtre sur aucun portail, alors cela ne remonte pas les objets associés à un portail (https://github.com/GeotrekCE/Geotrek-rando/issues/757#issuecomment-647538745).

Ces 2 comportements posent souvent des soucis.

Je propose donc un fonctionnement inverse : 

- Si je lance une synchro en filtrant sur un portail, en remonter que les objets associés à ce portail
- Si je ne filtre sur aucun portail, alors remonter tous les objets publiés

**Comment by gutard** [comment]
> Si je ne filtre sur aucun portail, alors cela ne remonte pas les objets associés à un portail
Non. Dans #2144 la synchro ne marchait simplement pas et c'est une mauvais interprétation qui a été faite.

> Si je ne filtre sur aucun portail, alors remonter tous les objets publiés
C'est déjà le cas.

**Comment by camillemonchicourt** [comment]
OK merci. Alors seulement l'autre point pourrait être une évolution.

**Comment by LePetitTim** [comment]
Il faudrait voir avec la communauté qu'est ce qui est le plus logique selon chacun.

**Comment by camillemonchicourt** [comment]
J'ai seulement des retours d'utilisateurs à qui cela posait problème.
Quand on a un champs pour spécifier un portail cible, la logique des utilisateurs semble être que c'est une information explicite.
Donc que si on filtre sur ce champs, cela ne renvoie que les objets associés explicitement à ce portail.
Je pense que c'est une incompréhension initiale sur la fonctionnalité.

Mais cela peut poser soucis à certains si on change maintenant la logique de synchronisation par portail.

Dans tous les cas, au niveau de l'API v2 de Geotrek-admin, et donc de Geotrek-rando v3, on a utilisé ce fonctionnement explicite. Si on filtre une route sur un portail, alors cela ne renvoie que les objets associés à ce portail.
Et il est préférable de garder ce fonctionnement explicite pour l'API et donc pour les futurs usages.

**Comment by babastienne** [comment]
La synchro Geotrek-Rando V2 n'est plus maintenue et en effet le filtre par portail était un peu trompeur. 

Pour l'API V2 utilisée par GTR3 le fonctionnement est devenu plus explicite.
