### ISSUE TITLE
Bug sur le filtrage d'itinéraires

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2290]
Nous avons des itinéraires où la durée n'est pas renseignée.

On peut filtrer sur une durée de 0 pour sélectionner uniquement ces itinéraires ; Ok.

Lorsqu'on réinitialise le filtre, la durée à 0 disparaît mais le champ durée reste encadré et le bouton filtre reste orangé alors même que les itinéraires avec une durée non nulle réapparaissent dans la liste et sur la carte après un deuxième clic sur le bouton "Réinitialiser".

**Comment by marcantoinedupre** [comment]
Reproduit sur [la démo de Geotrek Admin](https://demo-admin.geotrek.fr/trek/list/#) en version `2.101.5`.

Étapes :

- sur la vue liste des Itinéraires, saisir la valeur 0 dans le filtre Durée, cliquer le bouton Filtre, la liste est filtrée.
- Cliquer sur bouton Effacer, la valeur 0 disparaît, la liste n'est plus filtrée mais le filtre Durée reste encadré.

![screenshot bug reset trek duration filter](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/b03a0e3b-45e8-4e45-b9bc-6f03b6a28295)

- Fermer le panneau des filtres, le tooltip sur le bouton Filtre indique que le filtre Durée est actif avec une durée de 0.

![screenshot bug reset trek duration filter 2](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/035b8d7e-120a-4097-b1c7-7fbc0747b704)

**Comment by marcantoinedupre** [comment]
Pas reproduit le bouton Filtre qui reste en couleur orange alors que les filtres ont été effacés.

**Comment by marcantoinedupre** [comment]
Apparemment le champ filtre durée n'est pas couvert par la fonction : `L.MapListSync._formClear`

**Comment by justinefricou** [comment]
Le problème venait de la dépendance `django-mapentity` dont la méthode `L.MapListSync._formClear` ne gérait pas les `inputs` de type `number`.
Le bug est réglé via cette PR : https://github.com/makinacorpus/django-mapentity/pull/296
