### ISSUE TITLE
Use pagination in DataTable

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2292]

**Comment by gutard** [comment]
PR #2266

**Comment by camillemonchicourt** [comment]
Le travail sur les performances de navigation n'est pas terminé et encore dans une branche/PR à part.
@babastienne tu as fermé ce ticket car cette partie a été terminée et intégrée ?

**Comment by babastienne** [comment]
My bad, il me semblait que la MR avait été mergée.
En fait la partie pagination pour datatable est codée depuis longtemps, c'est pour ça que j'avais fermé l'issue. Mais comme celle-ci n'est toujours pas intégrée à master car la MR embarque d'autres grosses modifs de perf je ré-ouvre.
