### ISSUE TITLE
Problème d'affichage de données sur VM prod

### ISSUE THREAD

**Issue by Max-le64** [GeotrekCE/Geotrek-admin#2293]
Bonjour,

Nous rencontrons un problème concernant l'affichage des données sur notre nouvelle VM prod
Nous avons une VM de test en 2.32.1 et un VM de prod dans la même version et notre dump fait sur la test et installé sur la prod n'affiche pas les données, seulement celles des contenus touristiques et pas des itinéraires. 

Est-ce qu'il y a une commande à faire pour obtenir l'affichage des données ou pour les faire remonter ?

Merci d'avance

**Comment by gutard** [comment]
Il manque les données dans la liste à gauche ou bien sur la carte à droite ou bien sur les deux ? Y a-t-il un cadre rouge autour de la carte ? La console affiche-t-elle des messages d'erreur ? Que dit le fichier de log /var/log/supervisor/geotrek-api.log ? N'y a-t-il pas un filtre appliqué (bouton « Filtrer » en orange et non en bleu) ?

**Comment by Max-le64** [comment]
Alors non il y n'y a pas aucune donnée qui s'affiche à gauche comme à droite de l'interface, ni de cadre rouge. Les seules données qui s'affichent sont celles du module ''Contenus touristiques"

Je vais voir avec mon collègue pour le fichier log
