### ISSUE TITLE
Migration <= 2.32 to packaged version 2.33 error `No module named 'geotrek.settings.prod'`

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2294]
Distro : Ubuntu 18.04
Migration from 2.32.11 to .2.33 with migration script

**Comment by numahell** [comment]
Actually it is a regex error with sed in `migrate.sh`

**Comment by gutard** [comment]
To be exact, this problem occur only if the file custom.py is modified on Windows (with CR+LF ends of line). Actually the regex is correct. This is the ends of line wich are not. If we modify the regexp, the purpose is only to tolerate the error from the user that do not configure its text editor correctly.
