### ISSUE TITLE
Export fichiers pour synchronisation Geotrek-rando

### ISSUE THREAD

**Issue by chanteclair12** [GeotrekCE/Geotrek-admin#2298]
Bonjour,
Suite à l'installation de Geotrek-rando, je cherche à le "remplir" avec les données de Geotrek-admin.
J'ai d'abord essayé en mode manuel avec la commande `sudo geotrek sync_rando /mon/repertoire/de/destination`
mais ai eu le retour : "sudo : geotrek : command not found".
J'ai donc lancé la synchronisation depuis l'interface de Geotrek-admin, mais la barre d'avancement n'a pas bougé depuis plus d'une heure, bloqué sur "Trek tiles syncing". Est-ce normal en terme de temps (nous avons moins de 200 tronçons pour le moment) ? Où seront générés par défaut les fichiers à plat ?
Merci.

**Comment by chanteclair12** [comment]
Bonjour,
Je relance ce post. 
J'ai trouvé sur le serveur un répertoire "data" contenant des répertoires api, media, meta, static et zip.
Le zip contient des répertoires tiles et treks contenant eux des répertoires des différents langues et/ou des fichiers zip, dont un global.zip
Est-ce l'ensemble de ces répertoires (ou un seul) qu'il faut récupérer pour les déposer sur le serveur geotrek-rando ?
Merci.

**Comment by camillemonchicourt** [comment]
Ce n'est pas normal d'avoir ce message d'erreur. Vous avez un problème sur l'installation si la commande ``geotrek`` n'est pas connue, mais ça me semble étonnant. 
Le temps n'est pas lié au nombre de tronçons, mais au nombre de randos et de patrimoines publiés.

Les fichiers sont générés dans le dossier passé en paramètre dans la commande ``/mon/repertoire/de/destination``. 
Il faut que l'utilisateur Linux ``geotrek`` ait les droits dans le dossier en question.
C'est pour ça que la doc (https://geotrek.readthedocs.io/en/master/synchronization.html) indique de les créer dans le dossier ``/opt/geotrek-admin/var/data``.

Les zip et les tuiles ne sont pas utilisés du tout par Geotrek-rando, mais uniquement pour Geotrek-mobile version 2. 
La version 3 de Geotrek-mobile ne les utilise pas non plus, donc il est conseillé de ne pas les générer lors de la synchronisation si vous n'utilisez par Geotrek-mobile 2.x, en ajoutant l'option ``-t`` dans la commande ``sync_rando``.

C'est tout le dossier ``data`` qu'il faut mettre à disposition de Geotrek-rando, mais les zip et tiles ne lui sont pas utiles.

**Comment by gutard** [comment]
> sudo : geotrek : command not found

Êtes-vous en version <= 2.32 ou >= 2.33 ?

> bloqué sur "Trek tiles syncing"

La première synchro (ensuite c'est en cache) télécharge les tuiles sur l'ensemble de la France ce qui est très très très long pour pouvoir les proposer en offline sur l'app mobile v2. Il faut réduire l'étendue géographique ou bien passer l'option ---skip-tiles si vous n'avez pas de mobile v2.

**Comment by chanteclair12** [comment]
Merci pour ces retours.

Nous sommes en version 2.32.1.

> Les fichiers sont générés dans le dossier passé en paramètre dans la commande /mon/repertoire/de/destination.

Où la fonction de synchronisation de l'interface Administrateur génère-t-elle par défaut les fichiers du coup ?

**Comment by gutard** [comment]
> Nous sommes en version 2.32.1.

Du coup il faut regarder la doc qui correspond aux anciennes version : https://geotrek.readthedocs.io/en/2.22.1/ (c'est pas tout à fait la bonne mais ça sera beaucoup mieux déjà). la commande est `./bin/django sync_rando` (en étant placé dans le répertoire d'installation).

**Comment by gutard** [comment]
> Où la fonction de synchronisation de l'interface Administrateur génère-t-elle par défaut les fichiers du coup ?

Dans le sous répertoire data du répertoire d'installation (pour les versions <= 2.32)

**Comment by chanteclair12** [comment]
Merci pour ces informations, je vais tester avec cette commande.
Cordialement.
