### ISSUE TITLE
Problème valeur dans core_stake

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2300]
Dans la table core_stake, il reste des valeurs par défaut en plus de celles ajoutées (depuis la 2.33 je pense) : 
![image](https://user-images.githubusercontent.com/19687397/87547729-ced51600-c6ab-11ea-8234-608fe77c9f7e.png)
 Impossible de les supprimer depuis G.Admin (Internal server error) ou depuis PGAdmin ou autres gestionnaires.

Il y a également des valeurs par défaut dans core_comfort mais j'ai réussi à les supprimer, à voir par contre pour les enlever dans une prochaine version.

**Comment by camillemonchicourt** [comment]
Ah OK mince. Je n'ai pas le cas à priori mais on n'avait pas touché aux enjeux donc c'est surement la raison.
Si tu ne peux pas les supprimer il faudrait voir quelle est l'erreur associée ? 
Voir dans les logs (https://geotrek.readthedocs.io/en/master/installation.html#troubleshooting), l'erreur indiquée ?
Et si tu ne peux pas les supprimer dans la BDD, c'est peut-être car tes données sont liées à ces valeurs ? 
Que dis l'erreur de PG quand tu essaies de modifier directement dans la BDD ?

**Comment by LePetitTim** [comment]
Il doit aussi y avoir des valeurs par default dans : core_pathsource.

**Comment by LePetitTim** [comment]
Il faut mettre a jour en 2.33.12 pour eviter la création de troncons, comfort, pathsource et stake

**Comment by camillemonchicourt** [comment]
Réglé avec la version 2.38.0 ?

**Comment by LePetitTim** [comment]
> Réglé avec la version 2.38.0 ?

Oui :+1:
