### ISSUE TITLE
FLux Cirkwi / IGN Rando - Paramétrage Difficulté

### ISSUE THREAD

**Issue by PierreLABADIE** [GeotrekCE/Geotrek-admin#2301]
Bonjour, 
Les itinéraires créés dans Geotrek Admin ne remontent ni vers Cirkwi, ni vers IGN Rando.
J'avais fait une modif des valeurs dans l'admin qui sont celles-ci : 
![image](https://user-images.githubusercontent.com/67275105/87565037-685af280-c6c1-11ea-9aff-952ff9f5f975.png)

Le souci vient-il de là ?
Le cas échéant, je n'ai plus les valeurs par défaut. Quelqu'un saurait-il partager sa config ?

Merci d'avance !
Pierre

PS : les valeurs du groupe "Cirkwi" présentées ici ( https://geotrek.readthedocs.io/en/master/user-manual.html#geotrek-et-espace-loisir-ign ) n'ont pas été modifiées.

**Comment by camillemonchicourt** [comment]
Peux-tu préciser le contexte ?
Cela fonctionnait avant mais ne fonctionne plus ? Suite à quelle modification exactement ?
Tu as bien connecté IGN rando à ton Geotrek-admin ? 
Tu as bien relancé un import des données Geotrek-admin depuis IGN rando ?
Il faut certainement regarder plutôt du côté d'IGN rando que Geotrek-admin si cela fonctionnait auparavant.

Il faut bien que tes typologies Geotrek-admin soient mises en correspondance avec les typologies d'IGN rando mais ça semble être le cas dans ce que tu indiques.

Chez nous on a ça : 

![image](https://user-images.githubusercontent.com/4418840/87903701-ea01a600-ca5c-11ea-94b3-bc2f0215d53b.png)

Et en vérifiant ton flux (https://geotrek-champagne-ardenne.makina-corpus.net/api/cirkwi/circuits.xml), celui-ci semble bien complet et il y a bien un niveau de difficulté indiqué pour les randonnées, selon les typologies d'IGN rando (Cirkwi).
