### ISSUE TITLE
Erreur création pdf itinérances : failed ('tuple' object has no attribute 'width')

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2311]
Geotrek-rando : 2.26.1-ux
Geotrek-admin : 2.32.4

Bonjour,
sur ce Geotrek-rando, lorsque l'on souhaite télécharger la fiche des itinérances, une erreur 404 se produit (sur plusieurs navigateurs : Firefox, Chrome, etc). Même chose pour chacune des étapes liées à l'itinérance.

Sur le Geotrek-Admin, lorsque l'on clique sur le bouton "impression grand public" une erreur 500 se produit, avec la réception d'un mail d'erreur (voir fichier joint).

En regardant sur le serveur  dans ce répertoire (par exemple) `data/api/fr/treks/26893/` je me suis rendu compte qu'effectivement le pdf n'existait pas. 

Pendant la synchronisation, j'ai remarqué ce message d'erreur (le même que dans le fichier joint) lors de la synchronisation des itinérances : `failed ('tuple' object has no attribute 'width')`

Pourriez-vous me guider sur la marche à suivre ? 

En vous remerciant.

[mail_error_Geotrek_admin_190820.docx](https://github.com/GeotrekCE/Geotrek-rando/files/5095027/mail_error_Geotrek_admin_190820.docx)

**Comment by mviadere-openig** [comment]
Merci Gaël pour ton retour.

Concernant le fichier SVG, on parle bien d'un des fichiers qui constitue le pdf ? c'est à dire un fichier image qui est dans le template ?

**Comment by gutard** [comment]
> Concernant le fichier SVG, on parle bien d'un des fichiers qui constitue le pdf ? c'est à dire un fichier image qui est dans le template ?

Ça peut effectivement venir d'un fichier SVG référencé dans le template. Mais ça peut aussi venir des données en base, par exemple le picto de la pratique ou de la catégorie de contenu touristique. Ou bien un picto de service, de réseau (balisage)…

**Comment by mviadere-openig** [comment]
Ok, dans tous les cas c'est un picto qui n'affecte que les itinérances. Je vais chercher ceux concernés. Merci encore.

**Comment by mviadere-openig** [comment]
J'ai pensé en premier lieu au picto utilisé pour la pratique. Bonne pioche du premier coup, c'était lui qui faisait planter la génération des pdf pour la pratique "itinérance". Merci pour l'aide, je clos l'issue.
