### ISSUE TITLE
Fresh installation Libssl1.1

### ISSUE THREAD

**Issue by relaire** [GeotrekCE/Geotrek-admin#2314]
Bonjour,
Lors de l'installation de la dernière version, (`curl https://packages.geotrek.fr/install.sh | bash`), la configuration de libssl1.1 ouvre une fenêtre interactive (faut répondre par yes/no). Hors, le script d'installation semble bloquer la possibilité de faire ce choix pour l'installation de ce module (cf [](https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1833013))
J'ai contourné le pb en mettant à jour libssl1.1 (`sudo apt-get install libssl1.1`)  avant de lancer le script d'installation de geotrek-Admin

Renaud

**Comment by relaire** [comment]
lien vers le bug ubuntu : https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1833013

**Comment by camillemonchicourt** [comment]
OK, merci pour cette remontée, on n'avait pas rencontré ce soucis auparavant.
Tu étais bien en Ubuntu 18 ?

**Comment by relaire** [comment]
Oui, en 18.04.2, montée toute fraiche pour faire la migration de mon serveur de prod actuellement en Geotrek 2.32.11 sur une Ubuntu 16. 
Je préfère changer de serveur plutôt que faire la montée de version de Ubuntu 16->18

**Comment by camillemonchicourt** [comment]
> Je préfère changer de serveur plutôt que faire la montée de version de Ubuntu 16->18

Oui tu fais bien !

**Comment by gutard** [comment]
Il est normal que, parfois, l'installation du paquet geotrek-admin provoque la mise à jour d'autres paquets. Y compris si on est déjà en 18.04. Et il est normal que ça puisse réclamer une saisie. Le problème vient plutôt du pipe dans la commande `curl https://packages.geotrek.fr/install.sh | bash`. L'entrée standard est le script bash et non de la console. Il faudrait faire trois commandes : 1) ` wget https://packages.geotrek.fr/install.sh`,  2) `bash install.sh` et 3) `rm install.sh`. Mais j'aimais bien la solution avec un one-liner. Il faut que je vois si il existe une solution avec un one liner. De toute façon il faut changer la doc d'installation.
