### ISSUE TITLE
Update 2.35.1 - Migrations - Error 500

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2315]
Bonjour,

Sur un VPS (2 vCPU 4 GB / Ubuntu 18.04.5) qui héberge GTA et GTR (2.27), je viens de mettre à jour GTA de la version 2.33 vers 2.35.1 en effectuant :
sudo apt-get update
sudo apt-get upgrade

L'application semble avoir été bien mise à jour. La page du module tronçons s'affiche, mais le volet de gauche mouline dans le vide, la carte affiche bien les tronçons saisis. La console de l'inspecteur du navigateur affiche le message d'erreur suivant ->
13:22:40.221 /api/path/paths.json?structure=&valid=1&length_min=&length_max=&comfort=&stake=&draft=1&name=&comments=&trail=&city=&district=&physical_type=&land_type=&competence=&signage=&work=&bbox=POLYGON((-4.74609375+46.68713141244413%2C-4.74609375+50.65294336725709%2C2.197265625+50.65294336725709%2C2.197265625+46.68713141244413%2C-4.74609375+46.68713141244413)):1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Idem pour les modules Sentiers, Statuts, Aménagements, Signalétiques, Interventions, Chantiers, Services, Événements, Signalements.

Les autres modules affichent (Iti, POI, CT) -> Server Error (500)

Dès que je veux créer un objet dans n'importe quel module -> Server Error (500)

######## Erreurs relevées dans les logs ########

**systemd-geotrek-api.log**
Aug 24 22:20:23 vps-af970042 gunicorn[4566]: /opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/base.py:316: RuntimeWarning: Model 'mapentity.modelname' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
Aug 24 22:20:23 vps-af970042 gunicorn[4566]:   new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
Aug 24 22:20:23 vps-af970042 gunicorn[4566]: ERROR 2020-08-24 22:20:23,478 django.request Internal Server Error: /api/path/paths.json

Aug 24 22:20:23 vps-af970042 gunicorn[4566]: TypeError: type NoneType doesn't define __round__ method
Aug 25 09:26:27 vps-af970042 gunicorn[4566]: ERROR 2020-08-25 09:26:27,699 django.request Internal Server Error: /api/path/paths.json

**systemd-geotrek-ui.log**
Aug 24 21:16:32 vps-af970042 gunicorn[25977]: psycopg2.errors.InvalidCursorName: cursor "_django_curs_140279436265280_10" does not exist
Aug 24 21:16:36 vps-af970042 gunicorn[25977]: ERROR 2020-08-24 21:16:36,933 django.request Internal Server Error: /trek/list/
Aug 24 21:16:36 vps-af970042 gunicorn[25977]: Traceback (most recent call last):
Aug 24 21:16:36 vps-af970042 gunicorn[25977]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
Aug 24 21:16:36 vps-af970042 gunicorn[25977]:     return self.cursor.execute(sql, params)
Aug 24 21:16:36 vps-af970042 gunicorn[25977]: psycopg2.errors.UndefinedTable: relation "common_reservationsystem" does not exist
Aug 24 21:16:36 vps-af970042 gunicorn[25977]: LINE 1: ...tem"."id", "common_reservationsystem"."name" FROM "common_re...

Aug 24 21:31:04 vps-af970042 gunicorn[2405]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/forms/forms.py", line 304, in as_p
Aug 24 21:31:04 vps-af970042 gunicorn[2405]:     errors_on_separate_row=True,

Aug 24 21:45:51 vps-af970042 gunicorn[4564]: ERROR 2020-08-24 21:45:51,594 django.request Internal Server Error: /poi/list/
Aug 24 21:45:51 vps-af970042 gunicorn[4564]: Traceback (most recent call last):
Aug 24 21:45:51 vps-af970042 gunicorn[4564]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
Aug 24 21:45:51 vps-af970042 gunicorn[4564]:     return self.cursor.execute(sql, params)
Aug 24 21:45:51 vps-af970042 gunicorn[4564]: psycopg2.errors.UndefinedColumn: column trekking_trek.reservation_system_id does not exist
Aug 24 21:45:51 vps-af970042 gunicorn[4564]: LINE 1: ...a, "trekking_trek"."eid", "trekking_trek"."eid2", "trekking_...

Aug 25 11:30:17 vps-af970042 gunicorn[4564]:   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/forms/forms.py", line 304, in as_p
Aug 25 11:30:17 vps-af970042 gunicorn[4564]:     errors_on_separate_row=True,

Aug 25 11:30:18 vps-af970042 gunicorn[4564]: psycopg2.errors.InvalidCursorName: cursor "_django_curs_139914032932672_199" does not exist

**systemd-geotrek-celery.log**
May 02 21:56:14 vps-af970042 systemd[1]: Started Geotrek-admin asynchronous tasks.
Aug 24 21:10:41 vps-af970042 systemd[1]: Stopping Geotrek-admin asynchronous tasks...
Aug 24 21:10:43 vps-af970042 celery[27973]: worker: Warm shutdown (MainProcess)
Aug 24 21:10:43 vps-af970042 celery[27973]: [2020-08-24 21:10:43,051: WARNING/MainProcess] Traceback (most recent call last):
Aug 24 21:10:43 vps-af970042 celery[27973]: [2020-08-24 21:10:43,057: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
Aug 24 21:10:43 vps-af970042 celery[27973]:     finalizer()
Aug 24 21:10:43 vps-af970042 celery[27973]: [2020-08-24 21:10:43,057: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
Aug 24 21:10:43 vps-af970042 celery[27973]:     res = self._callback(*self._args, **self._kwargs)
Aug 24 21:10:43 vps-af970042 celery[27973]: [2020-08-24 21:10:43,057: WARNING/MainProcess] File "/opt/geotrek-admin/lib/python3.6/site-packages/billiard/pool.py", line 1697, in _terminate_pool
Aug 24 21:10:43 vps-af970042 celery[27973]:     if inqueue:
Aug 24 21:10:43 vps-af970042 celery[27973]: [2020-08-24 21:10:43,058: WARNING/MainProcess] AttributeError: 'NoneType' object has no attribute 'close'
Aug 24 21:10:43 vps-af970042 celery[27973]:

Si quelqu'un a des pistes, je suis preneur. Merci !

**Comment by gutard** [comment]
Il semble y avoir eu un problème avec les migrations Django lors de l'upgrade. Que donne la commande `geotrek migrate` (en root) ?

**Comment by JeanLenormand** [comment]
@gutard merci pour ton retour. La cmd sudo geotrek migrate donne -> 

Operations to perform:
  Apply all migrations: admin, auth, authent, cirkwi, common, contenttypes, core, django_celery_results, easy_thumbnails, feedback, flatpages, infrastructure, land, maintenance, mapentity, sessions, signage, tourism, trekking, zoning
Running migrations:
  Applying signage.0016_auto_20200512_0805...Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "deleted" of relation "signage_blade" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/migrate.py", line 25, in handle
    super().handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 178, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 487, in remove_field
    self.execute(sql)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "deleted" of relation "signage_blade" does not exist

**Comment by gutard** [comment]
OK. Il y a eu effectivement quelques soucis de migration au niveau de la signalétique. Il faudrait tenter :
```
geotrek migrate --fake signage 0016
geotrek migrate
```
Et voir si ça passe sans autres erreurs.

**Comment by JeanLenormand** [comment]
Super. Merci Gaël, efficace -> Problème réglé.

$ sudo geotrek migrate --fake signage 0016 ->
Operations to perform:
  Target specific migration: 0016_auto_20200512_0805, from signage
Running migrations:
  Applying signage.0016_auto_20200512_0805... FAKED

$ sudo geotrek migrate ->
Operations to perform:
  Apply all migrations: admin, auth, authent, cirkwi, common, contenttypes, core, django_celery_results, easy_thumbnails, feedback, flatpages, infrastructure, land, maintenance, mapentity, sessions, signage, tourism, trekking, zoning
Running migrations:
  Applying signage.0017_auto_20200708_1455... OK
  Applying tourism.0012_auto_20200708_1448... OK
  Applying trekking.0016_auto_20200708_1608... OK
