### ISSUE TITLE
Problème synchronisation avec --with-signages et --with-infrastructures

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2316]
Les options --with-signages et  --with-infrastructures pour la synchro ne semblent plus fonctionnés
Voici ma commande dans mon crontab : 
sudo geotrek sync_rando --url http://randoadmin.parc-haut-jura.fr --rando-url https://randonature.parc-haut-jura.fr --portal hautjurarando --with-signages /opt/geotrek-admin/var/data
J'ai cependant aucune signalétique qui remontent sur mon Geotrek Rando
D'autres ont le même problème ? (version 2.33.12)

**Comment by camillemonchicourt** [comment]
Regarde déjà dans ton dossier /data/api... si les fichiers geojson des signalétiques et aménagements sont générés. Et aussi si tu as des messages d'erreur lors de la synchronisation.
Mais comme tu es le seul (à ma connaissance) à utiliser la publication de la signalétique et des aménagements pour le moment, difficile à dire.

**Comment by thomaspnrhj** [comment]
Dans le dossier /data/api, aucun fichier geojson générés pour la signalétique et les aménagements. Et pour la synchro, pas de messages d’erreur liés à cela à priori, j'ai uniquement de nombreuses erreurs weasyprint mais pas en lien avec ça.
C'est comme ci les options  --with-signages et --with-infrastructures ne fonctionnaient plus...

**Comment by camillemonchicourt** [comment]
En lien avec https://github.com/GeotrekCE/Geotrek-rando/issues/698 ?

**Comment by thomaspnrhj** [comment]
J'avais complétement oublié  de repasser SIGNAGES_TILELAYER en true sur mon G.RANDO, merci Camille ! 
Thomas
