### ISSUE TITLE
Apply translation override

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2317]
Bonjour,

je souhaite modifier le message que reçois sur sa boite mail l'utilisateur qui a signalé un problème dans GTR (GTA 2.34 / GTR 2.27)

En me basant sur le fichier source suivant : 
/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/feedback/locale/fr/LC_MESSAGES/django.po

Je renseigne ma nouvelle traduction dans en respectant la source msgid et en mettant les modifs dans msgstr :
/opt/geotrek-admin/var/conf/extra_locale/fr/LC_MESSAGES/django.po

Dans la version de GTA < 2.32, il fallait lancer la commande suivante pour que ces modifications soient prises en comptes : 
make env_standalone deploy

Dans la version de GTA > 2.33 cette commande ne semble plus fonctionner.

Comment faut-il faire pour que les changements soient pris en comptes ?

J'ai essayé sans succès : 
sudo service geotrek restart
sudo dpkg-reconfigure geotrek-admin

Merci pour votre aide.

**Comment by gutard** [comment]
Il faut compiler le fichier .po en fichier .mo. Ça ne se fait effectivement pas tout seul à la mise à jour ou au redémarrage. Je ne m'étais pas encore posé le problème. Je dirais que les commandes suivantes devraient faire l'affaire :
```
cd /opt/geotrek-admin/var/conf/extra_locale
sudo chown geotrek. fr/LC_MESSAGES/
sudo geotrek compilemessages
sudo service geotrek restart
```

**Comment by JeanLenormand** [comment]
Ok parfait, problème réglé. Les modifications ont bien été prises en comptes dans les différentes langues surcouchées. Merci @gutard

**Comment by camillemonchicourt** [comment]
OK merci, j'ai proposé la mise à jour de la doc dans ma branche de compléments de la doc actuelle : https://github.com/GeotrekCE/Geotrek-admin/commit/4ee578fb684d92b0b97da4eb10b66a8b0f44a670
