### ISSUE TITLE
Configuration parsers sensivity area

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2319]
Suite au passage à la 2.33, je souhaite reconfigure mon API dans mon parser pour importer uniquement les zones sensibles de Biodiv'Sport qui me concerne en filtrant sur structure=4
Du coup, j'ai créé un fichier parser.py dans /opt/geotrek-admin/var/conf avec geotrek comme propriétaire.
Dans mon fichier j'ai indiqué : 
class BiodivParser(Parser):
    url = 'https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4'
J'ai lancé ensuite sudo service geotrek restart
En lançant l'import depuis G.Admin, je me retrouve cependant avec l'ensemble des zones sensibles de biodiv'sport.
Est-ce que j'ai un erreur de syntaxe dans parsers.py? Il faut utiliser une autre commande pour la prise en compte des modif ?
Merci d'avance pour le coup de main.
Thomas

**Comment by gutard** [comment]
Il y a de l'idée mais il faut faire un peu différemment. C'est une question d'héritage en programmation objet. Pour écrire ton propre parser qui surcharge BiodivParser il faut plutôt écrire :
```
class PNRHJBiodivParser(BiodivParser):
    url = 'https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4'
    label = "Biodiv'Sports PNRHJ"
```
Et choisir de lancer "Biodiv'Sports PNRHJ" plutôt que "Biodiv'Sports" depuis Geotrek-admin.

Sinon, tu définis un deuxième parser avec le même nom et tu as une chance sur deux que ça lance le tien plutôt que celui par défaut. De plus, le parser que tu as défini se base sur Parser et donc, à part l'URL que tu as précisé, il n'a aucune connaissance de comment interpréter le flux Biodiv'sports.

**Comment by thomaspnrhj** [comment]
Merci @gutard, je vois mieux comment ça fonctionne, j'ai fait comme t'as dit en personnalisant mon Parser
Par contre, j'ai toujours que mon parser Biodiv'Sport qui s'affiche dans mon G.Admin. C'est bien avec sudo service geotrek restart qu'on recharge ?

**Comment by gutard** [comment]
> C'est bien avec sudo service geotrek restart qu'on recharge ?
Oui (en version >= 2.33)

**Comment by thomaspnrhj** [comment]
Bizarre, le parser ne remonte pas

**Comment by gutard** [comment]
Il est placé où ? Dans /opt/geotrek-admin/var/conf/parsers.py ?

Qu'indique la commande `sudo geotrek import PNRHJBiodivParser` ?

**Comment by thomaspnrhj** [comment]
Oui il est bien placé dans /opt/geotrek-admin/var/conf/parsers.py

Voilà ce que donne sudo geotrek import PNRHJBiodivParser

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/import.py", line 37, in handle
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geotrek-admin/var/conf/parsers.py", line 9, in <module>
    from .models import SensitiveArea, Species, SportPractice
ImportError: attempted relative import with no known parent package

**Comment by camillemonchicourt** [comment]
J'ai l'impression que tu as un soucis dans la manière dont tu as écrit ton parser.
Tu peux en indiquer le contenu ?

**Comment by thomaspnrhj** [comment]
Alors j'ai fait une copie du parser existant et j'ai personnalisé avec mon nouveau parser : 
`import requests
import unicodedata

from django.conf import settings
from django.contrib.gis.geos import Point, Polygon, MultiPolygon
from django.utils.translation import ugettext as _

from geotrek.common.parsers import Parser, ShapeParser, GlobalImportError, RowImportError, ValueImportError
from .models import SensitiveArea, Species, SportPractice

class PNRHJBiodivParser(BiodivParser):
    model = SensitiveArea
    label = "Biodiv'Sports PNRHJ"
    url = 'https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4'
    eid = 'eid'
    separator = None
    delete = True
    practices = None
    fields = {
        'eid': 'id',
        'geom': 'geometry',
        'contact': 'contact',
        'species': (
            'species_id',
            'name',
            'period',
            'practices',
            'info_url',
            'radius',
        )
    }
    constant_fields = {
        'published': True,
        'deleted': False,
    }

    def __init__(self, *args, **kwargs):
        super(PNRHJBiodivParser, self).__init__(*args, **kwargs)
        for lang in settings.MODELTRANSLATION_LANGUAGES:
            self.fields['description_' + lang] = 'description.' + lang

    @property
    def items(self):
        return self.root['results']

    def get_to_delete_kwargs(self):
        kwargs = super(PNRHJBiodivParser, self).get_to_delete_kwargs()
        kwargs['eid__isnull'] = False
        return kwargs

    def next_row(self):
        response = requests.get('https://biodiv-sports.fr/api/v2/sportpractice/')
        if response.status_code != 200:
            msg = _("Failed to download https://biodiv-sports.fr/api/v2/sportpractice/. HTTP status code {status_code}")
            raise GlobalImportError(msg.format(url=response.url, status_code=response.status_code))
        for practice in response.json()['results']:
            defaults = {'name_' + lang: practice['name'][lang] for lang in practice['name'].keys() if lang in settings.MODELTRANSLATION_LANGUAGES}
            SportPractice.objects.get_or_create(id=practice['id'], defaults=defaults)
        bbox = Polygon.from_bbox(settings.SPATIAL_EXTENT)
        bbox.srid = settings.SRID
        bbox.transform(4326)  # WGS84
        url = self.url
        url += '&in_bbox={}'.format(','.join([str(coord) for coord in bbox.extent]))
        if self.practices:
            url += '&practices={}'.format(','.join([str(practice) for practice in self.practices]))
        response = requests.get(url)
        if response.status_code != 200:
            msg = _("Failed to download {url}. HTTP status code {status_code}")
            raise GlobalImportError(msg.format(url=response.url, status_code=response.status_code))

        self.root = response.json()
        self.nb = int(self.root['count'])

        for row in self.items:
            yield row

    def normalize_field_name(self, name):
        return name

    def filter_eid(self, src, val):
        return str(val)

    def filter_geom(self, src, val):
        if val['type'] == "Point":
            geom = Point(val['coordinates'], srid=4326)  # WGS84
        elif val['type'] == "Polygon":
            geom = Polygon(*val['coordinates'], srid=4326)  # WGS84
        elif val['type'] == "MultiPolygon":
            polygons = []
            for polygon in val['coordinates']:
                polygons.append(Polygon(*polygon, srid=4326))
            geom = MultiPolygon(polygons, srid=4326)
        else:
            raise ValueImportError("This object is neither a point, nor a polygon, nor a multipolygon")
        geom.transform(settings.SRID)
        return geom

    def filter_species(self, src, val):
        (eid, names, period, practice_ids, url, radius) = val
        need_save = False
        if eid is None:  # Regulatory area
            try:
                species = self.obj.species
            except Species.DoesNotExist:
                species = Species(category=Species.REGULATORY)
        else:  # Species area
            try:
                species = Species.objects.get(eid=eid)
            except Species.DoesNotExist:
                species = Species(category=Species.SPECIES, eid=eid)
        for lang, translation in names.items():
            if lang in settings.MODELTRANSLATION_LANGUAGES and translation != getattr(species, 'name_' + lang):
                setattr(species, 'name_' + lang, translation)
                need_save = True
        for i in range(12):
            if period[i] != getattr(species, 'period{:02}'.format(i + 1)):
                setattr(species, 'period{:02}'.format(i + 1), period[i])
                need_save = True
        practices = [SportPractice.objects.get(id=id) for id in practice_ids]
        if url != species.url:
            species.url = url
            need_save = True
        if radius != species.radius:
            species.radius = radius
            need_save = True
        if need_save:
            species.save()
        if set(practices) != set(species.practices.all()):
            species.practices.add(*practices)
        return species
`

**Comment by gutard** [comment]
Houlà non ! Copier/coller c'est « mal ». La programmation informatique c'est un vrai métier ;) Et un des préceptes c'est de ne pas dupliquer de code. En plus là, tu as un problème d'import relatif. Tu lui demandes des trouver le module python appelé models dans le même répertoire que ton code et il n'existe pas (alors qu'il existe à l'endroit d'où tu as copié).

Pour faire un héritage et une surcharge, il suffit que ton fichier complet contienne juste :

```python
from geotrek.sensitivity.parsers import BiodivParser

class PNRHJBiodivParser(BiodivParser):
    url = 'https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4'
    label = "Biodiv'Sports PNRHJ"
```

La première ligne te permet d'importer le parser existant BiodivParser. La deuxième permet de créer une nouvelle classe qui hérite de tout le code et paramètres de BiodivParser. Et les 2 dernières lignes te permette de surcharger juste les deux éléments qui t'intéressent : l'URL du flux et l'étiquette associée au parser pour qu'il apparaisse distinctement dans la liste des parsers affichés dans Geotrek-admin.

**Comment by gutard** [comment]
> Copier/coller c'est « mal »
La raison principale : si on corrige un bug dans le code de BiodivParser, ta copie va conserver le bug. Idem si on fait une amélioration.

**Comment by thomaspnrhj** [comment]
Merci @gutard, 
On est bien d'accord que c'est un métier à part entière :-) 
En tout cas je te remercie pour ton explication, j'y vois plus clair et comprends mieux le fonctionnement.
J'avais au départ copier uniquement les trois lignes pour personnaliser mais j'avais pas mis la première ligne donc ça ne pouvait pas fonctionner. j'avais donc recopier l’ensemble du code pour tester....

**Comment by camillemonchicourt** [comment]
En effet, c'est plus simple que prévu. :-)
