### ISSUE TITLE
Compatibilité avec ubuntu 20.04

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2321]
Bonjour,

Au parc de la Vanoise on pense mettre à jour notre serveur GT vers ubuntu 20.04 LTS.
Est-ce que quelqu'un a déjà testé GT sur cette version d'ubuntu ?
Si quelqu'un voit des raisons pour lesquelles GT ne marcherait pas, cela nous intéresse.

Merci

**Comment by camillemonchicourt** [comment]
Oui depuis la version 2.33 la méthode d'installation et de mise à jour a été entièrement revue (https://github.com/GeotrekCE/Geotrek-admin/issues/2135) pour être plus simple, standarde et industrialisable, avec une commande ``sudo apt install -y geotrek-admin``. 

Pour faciliter encore plus l'installation, un script d'installation a été mise en place (https://github.com/GeotrekCE/Geotrek-admin/blob/master/tools/install.sh), ensuite déployé à l'URL https://packages.geotrek.fr/install.sh.

Il est prévu de supporter les 2 dernières versions LTR d'Ubuntu. La révision de la méthode d'installation a été faite au moment où la version 18 d'Ubuntu était la LTR. Depuis la version 20 est sortie. Donc il faut désormais travailler et tester l'installation en version 20, tout en conservant le fonctionnement en version 18.

Donc il faudrait revoir ce script https://github.com/GeotrekCE/Geotrek-admin/blob/master/tools/install.sh, et éventuellement celui de migration pour ceux qui sont dans une version inférieure à la 2.33 (https://github.com/GeotrekCE/Geotrek-admin/blob/master/tools/migrate.sh). 
Et certainement les versions des dépendances (https://github.com/GeotrekCE/Geotrek-admin/blob/master/requirements.txt) et certainement d'autres points que je ne maitrise pas (versions de PostgreSQL, etc...)

**Comment by pierreloicq** [comment]
Tentative d'install sur ubuntu 2020 : 

> The following packages have unmet dependencies:
>  geotrek-admin : Depends: gdal-abi-2-2-3 but it is not installable
>                  Depends: libgdal20 (>= 2.2.1) but it is not installable
>                  Depends: convertit but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Si je mentionne [libgdal26](https://packages.ubuntu.com/focal/libgdal26), la ligne correspondante disparaît, mais pour les autres, je suppose qu'il faut modifier le coeur de convertit...

Je vais rester sur 18.04 pour le moment.

**Comment by gutard** [comment]
Oui on a pas encore bossé sur le portage du paquet Ubuntu en 20.04. Si ça ne râle que sur gdal (ça on s'en doutait, il est chatouilleux au sujet du versionning) et convertit (c'est aussi un paquet développé pour Geotrek) c'est plutôt une bonne nouvelle.

**Comment by gutard** [comment]
@camillemonchicourt, la compatibilité ascendante fait que ce qui marche en 18.04 peut généralement marcher en 20.04. Il y a surtout GDAL qui met le bazar car il exige (exigeait ?) une correspondance précise de version entre la lib binaire et le binding python. 2 solutions :
1) on arrive à faire un paquet unique qui fonctionne à la fois  en 18.04 et en 20.04
2) on fait deux paquets et dans ce cas il faut gérer subtilement la  numérotation des version pour que la migration de 18.04 à 20.04 se passe bien (il faut probablement numéroter les paquets 2.38.0~ubuntu18.04 et 2.38.0~ubuntu20.04) et il faut modifier la CI qui génère les paquets.

**Comment by camillemonchicourt** [comment]
Un seul paquet semble idéal pour éviter des releases pour chaque OS si j'ai compris.

**Comment by gutard** [comment]
Il faudrait voir si la simple suppression de la ligne `libgdal-dev (<< 2.3),` dans le fichier `debian/control` rend le paquet installable sur Ubuntu 20.04. Si le binding Python de GDAL est tolérant, et sauf autre surprise, ça devrait passer.

**Comment by camillemonchicourt** [comment]
Fait avec la release 2.41.

Info de @gutard :

La dernière version de Geotrek-admin est disponible à la fois pour
Ubuntu 18.04 et Ubuntu 20.04.

Pour ce faire nous avons dû changer la configuration du dépôt de paquets.
Pour ceux qui ont déjà installé le paquet précédemment, Il est donc nécessaire de lancer ``sudo apt-get update --allow-releaseinfo-change`` avant faire la mise à jour afin d'accepter ces changements.

Si vous faites une nouvelle installation, ou si vous déplacez une installation sur un nouveau serveur, il est désormais conseillé de le faire avec Ubuntu 20.04 LTS.

Il est possible de mettre à jour un serveur Ubuntu 18.04 existant en Ubuntu 20.04 mais cela nécessite probablement quelques opérations manuelles au niveau de la base postgresl/postgis qui n'ont pas été testées et documentées pour l'instant.

**Comment by pierreloicq** [comment]
Hello,
Je tente une fresh install de la 2.42 sur ubuntu 2020.
Lors de l'install, j'ai des 

>  FATAL:  database "geotrekdb" does not exist

C'est normal ?
Ensuite j'ai des erreurs liées aux tables de mnt lors de l'import de ma BBD, que ça soit une BDD de GT en versions 2.42 ou 2.39 qui marchent bien toutes les deux (log en pj)

Ca commence comme ça :

> pg_restore: error: could not execute query: ERROR:  schema "public" already exists
> Command was: CREATE SCHEMA public;

Au final le GT semble fonctionner sauf quand je veux créer une nouvelle rando ou j'ai une erreur 500 après la création.
Ca pourrait être lié au passage de postgres 10 à 12 ?

[errors import.log](https://github.com/GeotrekCE/Geotrek-admin/files/5659271/errors.import.log)

Merci

**Comment by gutard** [comment]
> Je tente une fresh install

C'est une nouvelle install, mais tu veux récupérer une base existante, c'est bien ça ? Dans ce cas tu as a priori répondu non à la question « Create a PostgreSQL database? ». Et donc tu es sensé donner les accès qui vont bien pour accéder à la base geotrekdb qui existe déjà. C'est à toi de gérer la création de la base. Geotrek ne gère la création d'une base vide que si tu le lui demandes en répondant oui à la question sus-mentionnée.

> pg_restore: error: could not execute query: ERROR: schema "public" already exists

Idem, ça n'a pas vraiment de rapport avec Geotrek. Ce sont des problématiques de SQL. L'erreur sur le schema public n'est pas grave. Si vraiment tu veux éviter l'erreur tu fais un `DROP SCHEMA public;` entre la création de la base et la restauration. Les autres problèmes viennent non pas du passage de postgresql 10 à 12 mais du passage de postgis 2.5 à 3.0. Il faut que tu fasses un `CREATE EXTENSION postgis_raster;` avant l'import car désormais les extension postgis et postgis_raster sont séparées.

**Comment by pierreloicq** [comment]
Merci, ça marche :-)

`sudo -u postgres psql -d geotrekdb -c "CREATE EXTENSION postgis_raster CASCADE;"`
