### ISSUE TITLE
API v2 - Ajouter infrastructures (signalétique / aménagement)

### ISSUE THREAD

**Issue by mchourot** [GeotrekCE/Geotrek-admin#2325]
Bonjour,

J'utilise les API afin de récupérer les données de geotrek admin et les infrastructures ne sont pas exposées via l'api v2.
Est-il prévu de les ajouter ?

Merci,

Bien à tous,

**Comment by camillemonchicourt** [comment]
Bonjour, dans le cadre de la refonte de Geotrek-rando initiée récemment, nous devons faire évoluer l'API v2 pour l'enrichir.
Nous n'avons pas encore la liste complète de ce qui doit y être ajouté. 
Mais la signalétique et les aménagements pouvant être publiés sur Geotrek-rando, il est possible qu'on les ajoute à l'API v2 de Geotrek-admin.

Cependant j'ai l'impression que vous avez besoin de tous les aménagements, pas seulement ceux publiés, est-ce exact ? Pouvez-vous préciser le besoin ou l'usage ?

**Comment by mchourot** [comment]
Bonjour,
S'il faut les publier cela ne pose pas de soucis, en fait je souhaitais saisir des aménagements pour en récupérer uniquement certains type afin d'alimenter une source de données pour ajouter sur un fond de carte. Pour le moment je vais devoir passer par les POIs qui eux remontent via l'API.

**Comment by gutard** [comment]
Geotrek est un logiciel libre. Vous pouvez contribuer en proposant des améliorations du code source via une Pull Request sur github.

**Comment by camillemonchicourt** [comment]
Un travail est en cours pour enrichir l'API v2 de Geotrek-admin : https://github.com/GeotrekCE/Geotrek-admin/issues/1740
Dans celle-ci il est prévu d'ajouter les aménagements publiés à l'API de Geotrek-admin.

**Comment by camillemonchicourt** [comment]
Les routes des aménagements et des services n'ont pas été intégré dans les évolutions initiales de l'API v2 (https://github.com/GeotrekCE/Geotrek-admin/issues/1740).

Il faudrait les ajouter. 
Pour Geotrek-rando, on ne veut que les objets publiés, avec leur nom, leur description, leur localisation, leurs médias, leur type (avec la route des typologies associées).

A voir pour des usages de gestion si on a besoin à terme aussi de pouvoir récupérer les objets non publiés.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2748

**Comment by camillemonchicourt** [comment]
Cette PR inclut seulement les aménagements ? Ou aussi les signalétiques ?

**Comment by pyrog** [comment]
Je ne suis pas encore familier avec la structure de données de GeoTrek.

Les données publiées concernent : 
* Les infrastructures : [test_v2.py#L168-L186](https://github.com/GeotrekCE/Geotrek-admin/blob/c74c7f09a6f3cf7b6ab2c9d5a45b23ad6255c7df/geotrek/api/tests/test_v2.py#L168-L186)
* La signalétique : [test_v2.py#L200-L224](https://github.com/GeotrekCE/Geotrek-admin/blob/c74c7f09a6f3cf7b6ab2c9d5a45b23ad6255c7df/geotrek/api/tests/test_v2.py#L200-L224)

**Comment by camillemonchicourt** [comment]
Oui en effet, la PR a commencé par les aménagements (infrastructures) puis la signalétique (signages) y a été ajoutée.

**Comment by camillemonchicourt** [comment]
OK dans la 2.64.0.

Exemple sur notre serveur de DEMO : 
- Renvoyer toutes les signalétiques publiées : https://geotrekdemo.ecrins-parcnational.fr/api/v2/signage/
- Renvoyer les signalétiques liées à l'itinéraire 849 : https://geotrekdemo.ecrins-parcnational.fr/api/v2/signage/?near_trek=849
- Renvoyer les signalétiques liées à un site outdoor : https://geotrekdemo.ecrins-parcnational.fr/api/v2/signage/?near_outdoorsite=54
- Renvoyer tous les aménagements publiés : https://geotrekdemo.ecrins-parcnational.fr/api/v2/infrastructure/

**Comment by thomaspnrhj** [comment]
De notre côté, on a ouvert l'API (API_IS_PUBLIC = True) pour diffuser des données issues des modules de valorisation sur d'autres outils. Par contre pour le volet gestion, on a des données issues des PDIPRs ou autres et donc sans forcément être le propriétaire des données et pour des questions de gouvernance/de droits, il nous apparait sensible dans un premier temps de diffuser certaines données de gestion via l'API... L'ouverture de l'API est paramétrable uniquement à l'instance ou est-ce qu'on peut faire une différenciation entre le volet valorisation/gestion ???

**Comment by camillemonchicourt** [comment]
Dans l'API il n'y a que les objets publiés.
Donc si tes aménagements et tes signalétiques ne sont pas publiés, ils ne remontent pas dans l'API.

On a justement ajouté la signalétique et les aménagements à l'API pour vous car vous en publiez certains sur votre Geotrek-rando et donc pouvoir porter cela sur Geotrek-rando V3 qui est basée sur l'API.

**Comment by thomaspnrhj** [comment]
ok ok je comprends mieux, je pensais que l'API diffusait la totalité des aménagements et signalétique de l'Admin ! Parfait alors
Merci ;-)

**Comment by pyrog** [comment]
Comment obtenir les libellés correspondant aux champs codés ?

`condition`, `sealing`, `type`, `direction`

type | libellé
--|--
1|Porte d'entrée du Parc (PNE)
2 | Directionelle (PNE)
3|Situation (PNE)
4|Réglementaire (PNE)
5|Service (PNE)
6|Appartenance (PNE
7|Limite Cœur (PNE)
8|Information (PNE)
9|Temporaire (PNE)

**Comment by camillemonchicourt** [comment]
Toutes les routes sont documentées sur le Swagger de l'API : https://geotrekdemo.ecrins-parcnational.fr/api/v2/

- infrastructure_condition
- signage_sealing
- signage_type
- signage_direction

Il est aussi possible de ce connecter au Geotrek-admin de démonstration (https://geotrekdemo.ecrins-parcnational.fr) avec le compte admin / admin
