### ISSUE TITLE
Probleme d'install sur ubuntu 16.04LTS

### ISSUE THREAD

**Issue by MelanieMichel** [GeotrekCE/Geotrek-admin#2328]
Bonjour,
Nouvelle utilisatrice de Geotrek, je rencontre un soucis suite à une tentative d'install before upgrading...

- Serveur Ubuntu 16.04 LTS
- Geotrek-admin 2.32.3
- La synchronisation des données vers Geotrek-rando ne fonctionnant pas, j'ai voulu faire une mise à jour de Geotrek-admin et lu sur la doc que pour une version <= 2.32 il etait préférable de lancer au préalable ./install.sh
- install a généré une erreur 
Install Geotrek python dependencies...
Could not setup python environment !
- Depuis nous n'avons plus accès à Geotrek-admin

J'ai tenté un update vers 2.32.4 mais j'ai de nouveau une erreur (voir log ci-joint)[install.log](https://github.com/GeotrekCE/Geotrek-admin/files/5231810/install.log)
Est ce que le log vous inspire une action à faire pour rétablir notre Geotrek-admin ?

Est-ce que ca vaut le coup de debugger ou vous me conseillez de partir sur un serveur 18.04 et une version Geotrek plus récente directement ?
Merci d'avance pour vos conseils
Mélanie Michel - Parc national de Port-Cros

**Comment by camillemonchicourt** [comment]
Pour passer à la nouvelle version de Geotrek-admin (2.33 et plus) il faut un serveur en Ubuntu 18.
Avant cela il est indiqué d'exécuter le script ``install.sh`` si on a mis à jour sa distribution Ubuntu, ou si on a migré de serveur, sinon pas utile.

Comme évoqué la version 2.32.3 a un soucis de dépendance sur Ubuntu 16 donc en relançant une installation sur la même version, cela l'a certainement cassé.

Dans tous les cas, il n'est pas nécessaire de passer par la 2.32.4. Tu peux passer directement en 2.36... avec le script ``migrate.sh``.
Mais il faut être sur un Ubuntu 18. Donc soit migrer sur un nouveau serveur, soit monter ton serveur de la version 16 à 18 de Ubuntu.

En complément de la documentation actuelle (https://geotrek.readthedocs.io/), quelques précisions de la doc d'installation/mise à jour, en cours de relecture dans cette PR : https://github.com/GeotrekCE/Geotrek-admin/pull/2241/files

**Comment by gutard** [comment]
Pour réparer l'install existante tu peux tenter de télécharger https://raw.githubusercontent.com/GeotrekCE/Geotrek-admin/f602a695c4727bc4011d06125e38630152311456/conf/buildout.cfg et remplacer le fichier conf/buildout.cfg puis faire le install.sh

Pour passer à la dernière version il faut effectivement au préalable passer à Ubuntu 18.04.

**Comment by gutard** [comment]
Euh non en fait. La correction ci dessus marcherait pour les versions < 2.30, pas pour une 2.32.x

Il faudrait plutôt tenter de rajouter une ligne `vine = 1.3.0` dans la section `[versions]` du fichier `conf/buildout.cfg` puis relancer install.sh et nous redonner le install.log si ça ne marche toujours pas.

**Comment by MelanieMichel** [comment]
Merci pour le retour !  Geotrek-admin fonctionne de nouveau, génial.
La bonne solution était d'ajouter une ligne vine = 1.3.0 dans la section [versions] du fichier conf/buildout.cfg d'origine.
Super, je vais pouvoir reprendre mes tests de synchronisation et voir tranquillement pour passer à Ubuntu 18.04 sur un autre serveur .

**Comment by camillemonchicourt** [comment]
Merci @gutard pour l'aide.
@MelanieMichel, attention à bien faire tout ça sur des serveurs de tests/pre-prod avant.
Ou à minima faire des bonnes sauvegardes et si possible un snapshot avant toute opération pour pouvoir revenir en arrière en cas de problème.

**Comment by MelanieMichel** [comment]
Je m'apercois que Geotrek-rando n'est plus accessible. Ai-je raté un point dans la mise à jour ?

**Comment by camillemonchicourt** [comment]
Geotrek-rando ? Quel rapport ?

**Comment by MelanieMichel** [comment]
Geotrek -rando n'est-il pas la partie publique de l'appli ?
Elle est restée accessible le temps des manip et maintenant quand je vais sur l'url rando... j'arrive sur l'admin

**Comment by camillemonchicourt** [comment]
OK donc si tu as les 2 sur le même serveur, tu dois avoir un conflit dans tes configurations NGINX des 2 outils.
Mais rien à voir au niveau des installations des 2 outils qui sont indépendantes.
La plupart du temps les 2 outils sont sur 2 serveurs différents.

**Comment by MelanieMichel** [comment]
ha ok je comprends mieux ton étonnement ! Oui on a les 2 sur le même serveur effectivement.
Bon heureusement j'ai un snapshot sous le coude ... Je vais arrêter les frais !
