### ISSUE TITLE
Options pour la synchronisation via l'espace web

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2344]
Je souhaite paramétrer la commande de synchro accessible via le portail web de GTA (v. 2.35.1).

Lorsque que je clique sur le bouton "sync" puis lance la synchro du site, la commande génère les tuiles du fond de carte ("Synchro des tuiles globales..." affichée).

Pour désactiver cela j'ai renseigné la ligne suivante dans le fichier custom.py : 
SYNC_RANDO_OPTIONS = {"skip-tiles" }
Puis $ sudo service geotrek restart

Maintenant lorsque je clique sur "sync" puis "lancer la synchro", "une erreur est survenue" s'affiche dans la barre de chargement et le fichier "tmp_sync_rando" n'est pas généré.

Quelqu'un saurait il me dire si la syntaxe des options de SYNC_RANDO_OPTIONS est bien la bonne ?

Par ailleurs, est il possible d'indiquer avec cette option la génération d'un log lorsque la commande de synchro est lancée ?

Merci pour vos retours !

**Comment by camillemonchicourt** [comment]
Je n'ai jamais utilisé le bouton, mais je me demandais et je viens de trouver quelques exemples : 
https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/tests/test_views.py#L1588
https://github.com/GeotrekCE/Geotrek-admin-starter/blob/master/var/conf/custom.py#L68

Ca vaudrait le coup de mettre un exemple similaire directement dans la doc.

**Comment by JeanLenormand** [comment]
En effet, la bonne syntaxe est la suivante pour enlever la génération des tuiles : 

SYNC_RANDO_OPTIONS = {'skip_tiles': True}

Merci @camillemonchicourt
