### ISSUE TITLE
Fix 'ManyToManyField' serializer 

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2350]
PR : https://github.com/GeotrekCE/Geotrek-admin/pull/2342/files

Serializer for ManyToManyField doesn't work.
![image](https://user-images.githubusercontent.com/26329336/95088290-0a1f3800-0723-11eb-954b-0af3b3d65999.png)

We should try to find a solution to make it works (again ?), and do not forget to remove every ..._display that might be remove.

**Comment by submarcos** [comment]
fixed by https://github.com/GeotrekCE/Geotrek-admin/pull/2342/files
