### ISSUE TITLE
Tache cron geotrek : command not found (v3.38.2)

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#2352]
Lorsque l'on crée une tache cron dans /etc/cron.d la commande geotrek n'est pas reconnue. Il faut mettre /usr/sbin/geotrek pour que ça fonctionne

**Comment by gutard** [comment]
Oui. Mais je ne vois pas vraiment en quoi c'est un problème et en quoi ça concerne Geotrek. Par défaut, dans cron `PATH=/usr/bin:/bin`.

Cf. encadré jaune sur https://doc.ubuntu-fr.org/cron#autres_considerations

**Comment by camillemonchicourt** [comment]
Peut-être la partie de la documentation sur le sujet à modifier : https://geotrek.readthedocs.io/en/master/synchronization.html#automatic-synchronization ?

**Comment by gutard** [comment]
Ah ! OK. C'est pas un réflexe pour moi de penser à la doc ;)

**Comment by gutard** [comment]
https://github.com/GeotrekCE/Geotrek-admin/commit/177d64c55eb5e39c138dc84b9a7b7ea0858de7f9
