### ISSUE TITLE
Geotrek 2.38.3 server error 500

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2357]
Geotrek admin version : 2.38.3

Bonjour,

Lorsque l'on tente de regarder un chantier ou une intervention déjà crée, on a une erreur 500.

Voici le message d'erreur qu'affiche la console du navigateur (ici Firefox) lorsque l'on clique sur un chantier ou une intervention : 

`L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert.`

Pareil lorsque l'on tente d'en créer une.

Voici les logs de ces différentes commandes : 

**sudo journalctl -eu geotrek-ui**

[geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/5353785/geotrek-ui.log)

**sudo journalctl -eu geotrek-api**

[geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/5353778/geotrek-api.log)

**sudo journalctl -eu geotrek-celery**

[geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/5353783/geotrek-celery.log)

**Comment by gutard** [comment]
`sudo geotrek remove_stale_contenttypes`

Cf. https://github.com/GeotrekCE/Geotrek-admin/issues/2323#issuecomment-705392242

**Comment by gutard** [comment]
Et probablement des permissions à redonner sur les fichiers attachés, les aménagements, les signalétiques.

**Comment by mviadere-openig** [comment]
Ok, j'ai lu la suite du ticket #2323, si je comprends bien il s'agit juste de nettoyage dans la BDD. 

Quand tu parles de permissions à redonner, il s'agit de permissions utilisateurs dans l'interface de Geotrek-admin ? Où bien de permissions sur des dossiers spécifiques en CLI ?

**Comment by gutard** [comment]
Les permissions utilisateurs.

**Comment by mviadere-openig** [comment]
Merci pour les infos Gaël, ça refonctionne.
