### ISSUE TITLE
Erreur génération pdf

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2358]
Bonjour,

Quand je vais sur la page détail d'un itinéraire et que je clique sur le bouton "impr" (logo pdf), j'obtiens une erreur 500. Je pense que cela ne marchait déjà pas avant ma [mise à jour](https://github.com/GeotrekCE/Geotrek-admin/issues/2323).

On est d'accord que cela devrait fonctionner indépendamment des synchronisations ? Le pdf est généré à la volée puis enregistré pour les prochains appels ? (dans /api/fr/treks/numDeLaRando/nomDeLaRando.pdf )

Les messages d'erreur
[log_bug_getPdf.txt](https://github.com/GeotrekCE/Geotrek-admin/files/5364485/log_bug_getPdf.txt)
[log_bug_getPdf_from_debugueur.txt](https://github.com/GeotrekCE/Geotrek-admin/files/5364486/log_bug_getPdf_from_debugueur.txt)
sont similaires à [ici](https://github.com/GeotrekCE/Geotrek-admin/issues/2277) et [ici](https://github.com/GeotrekCE/Geotrek-admin/issues/1578).

J'ai essayé d'ajouter 
`127.0.0.1 adminrando.vanoise.com`
dans le /etc/hosts puis redémarré nginx et geotrek mais ça ne change rien.
Mon fichier host actuel : 

> 127.0.0.1       localhost
> 127.0.1.1       geotrek2020dev
> // The following lines are desirable for IPv6 capable hosts
> ::1     localhost ip6-localhost ip6-loopback
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters

D'autre part, j'ai un message type pare-feu qui n'est cependant pas tagué aux mêmes moments que mon bug de pdf
>  GeotrekAdminU18 gunicorn[23031]: ERROR 2020-10-12 10:57:59,529 django.security.DisallowedHost Invalid HTTP_HOST header: '5.196.111.114'. You may need to add '5.196.111.114' to ALLOWED_HOSTS.

Est-ce que 
`w3m http://localhost`
devrait donner autre chose que "bad request" ?

Merci pour vos indices éventuels

**Comment by gutard** [comment]
Sur l'instance de test en allant sur http://localhost il y a aucune chance que ça marche (on peut y arriver avec Docker mais c'est un peu complexe à configurer).
Sur l'instance de prod avec le paquet Ubuntu, il faut que :
- le nom de domaine ait été correctement configuré à l'installation (et ne soit pas localhost),
- bien utiliser ce même nom de domaine et pas un autre dans le navigateur,
- avoir configuré une clé IGN qui fonctionne pour ce domaine (ou utiliser OpenTopoMap, OSM semble refuser les requêtes provenant d'une machine).

**Comment by pierreloicq** [comment]
Merci.
Je suis bien sur l'instance de prod.
Tout me semble ok sur ces points: 

> PostgreSQL host : localhost
> GTA domain name : adminrando.vanoise.com
> Domain name(s) of Geotrek-rando web server(s) : *

Notre clé est valide sur l'IP du serveur et son nom de domaine

**Comment by pierreloicq** [comment]
J'ai un doute sur le SERVER_NAME. Doit-ce correspondre plutôt au contenu de /etc/hostname (GeotrekAdminU18 en l'occurrence) ? Sur l'écran d'install il est mentionné à la fois nom du serveur et nom de domaine.

POSTGRES_HOST="localhost"
SERVER_NAME="adminrando.vanoise.com"
RANDO_SERVER_NAME="*"
CONVERSION_HOST="localhost"
CONVERSION_PORT="6543"
CAPTURE_HOST="localhost"
CAPTURE_PORT="8000"

Merci

**Comment by pierreloicq** [comment]
A ma question de ci-dessus, SERVER_NAME="adminrando.vanoise.com" est la seule solution, le reste ne marche pas. 
Problème toujours présent avec TREK_POINTS_OF_REFERENCE_ENABLED = False dans /opt/geotrek-admin/var/conf/custom.py
Le message apparait aussi pendant la synchro. 

Le message 

> GeotrekAdminU18 gunicorn[23031]: ERROR 2020-10-12 10:57:59,529 django.security.DisallowedHost Invalid HTTP_HOST header: '5.196.111.114'. You may need to add '5.196.111.114' to ALLOWED_HOSTS.

apparait quand je tape l'IP dans le navigateur, mais aussi la nuit, ce que je n'explique pas.

**Comment by pierreloicq** [comment]
En version 2.34 dev, installé via [docker ](https://geotrek.readthedocs.io/en/master/development.html) sans la ligne load_data et avec une rando exemple que je fais moi-même, j'ai la même erreur, que je mette des points de référence ou pas.

**Comment by numahell** [comment]
> On est d'accord que cela devrait fonctionner indépendamment des synchronisations ? Le pdf est généré à la volée puis enregistré pour les prochains appels ? (dans /api/fr/treks/numDeLaRando/nomDeLaRando.pdf )

oui tout à fait

Sur le serveur de produdction, c'est installé via les paquet ? 
quel est le résultat de la commande `service screamshotter status` et `sudo journalctl -eu screamshotter` ?

**Comment by pierreloicq** [comment]
Oui c'est installé avec la méthode normale (pas docker)

`service screamshotter status`

>  screamshotter.service - Microservice to capture screenshots of web pages
>    Loaded: loaded (/lib/systemd/system/screamshotter.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2020-09-23 16:19:06 CEST; 3 weeks 1 days ago
>  Main PID: 9672 (gunicorn)
>     Tasks: 2 (limit: 2318)
>    CGroup: /system.slice/screamshotter.service
>            ├─9672 /opt/screamshotter/bin/python /opt/screamshotter/bin/gunicorn --pid /var/run/screamshotter/creamshotter.pid screamshotter.wsgi
>            └─9704 /opt/screamshotter/bin/python /opt/screamshotter/bin/gunicorn --pid /var/run/screamshotter/creamshotter.pid screamshotter.wsgi
> 
> sept. 23 16:19:06 geotrek2020dev systemd[1]: Started Microservice to capture screenshots of web pages.
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Starting gunicorn 20.0.4
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Listening at: http://127.0.0.1:8000 (9672)
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Using worker: sync
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9704] [INFO] Booting worker with pid: 9704

`sudo journalctl -eu screamshotter`

> -- Logs begin at Mon 2020-09-14 14:47:30 CEST, end at Thu 2020-10-15 17:04:30 CEST. --
> sept. 23 16:19:06 geotrek2020dev systemd[1]: Started Microservice to capture screenshots of web pages.
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Starting gunicorn 20.0.4
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Listening at: http://127.0.0.1:8000 (9672)
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9672] [INFO] Using worker: sync
> sept. 23 16:19:07 geotrek2020dev gunicorn[9672]: [2020-09-23 16:19:07 +0200] [9704] [INFO] Booting worker with pid: 9704

**Comment by pierreloicq** [comment]
J'ai redémarré le service et j'obtiens des beaux pdfs :-)

> sudo service screamshotter restart

Merci pour les pistes
