### ISSUE TITLE
ÉTIQUETTE - Randonner avec un chien (et autres)

### ISSUE THREAD

**Issue by samuelpriou** [GeotrekCE/Geotrek-admin#2362]
Au sein du parc national du Mercantour, nous souhaitons ajouter un critère pour afficher les randonnées possibles avec un chien. Dans un parc national les randonneurs n'ont pas la possibilité de randonner avec un chien en cœur de parc pour autant cela est possible dans l'aire d'adhésion d'un parc national. 

Nous souhaitons donc réfléchir à la possibilité d'ajouter dans l'admin de Geotrek et sur le portail grand public un moyen de publier des itinéraire de randonnée avec un chien.

Actuellement seuls les filtres "thèmes" et "accessibilité" permettraient de distinguer des itinéraires où les chiens sont autorisés mais ce n'est pas la vocation initiale de. ces champs
Il y a également dans Geotrek admin un champ booléen "en coeur de parc" qui permettrait d'afficher une information mais sans pour filtrer sur ce champ.

D'autres structures sont elles intéressées par ce besoin ? Comment pourrions nous intégrer cette information supplémentaire dans l'administration et la bdd de Geotrek sans utiliser les champs "thèmes" et "accessibilités".

Bonne soirée à tous.

**Comment by camillemonchicourt** [comment]
Issue déplacée Geotrek-admin car avant tout lié à des évolutions dans Geotrek-admin, à répercuter dans Geotrek-rando.
Voir https://github.com/GeotrekCE/Geotrek-admin/pull/2361

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.38.5. 
Il est désormais possible de définir différentes étiquettes (labels) que l'on peut ensuite associer aux randonnées.
Une étiquette a un nom, une recommandation, un pictogramme et est utilisée en tant que filtre ou non (dans Geotrek-rando) : 
![image](https://user-images.githubusercontent.com/4418840/96637804-7dc66500-131f-11eb-8639-61a6b9eef3fa.png)

Ensuite on peut associer une ou plusieurs étiquettes à chaque rando : 
![image](https://user-images.githubusercontent.com/4418840/96637937-aea69a00-131f-11eb-8de2-17f730fa1bea.png)

Dans Geotrek-rando (à partir de sa version 2.29.0), les étiquettes qui ont été définies comme utilisables en filtres, sont affichées en tant que filtre, dans un bloc "Autre" : 
![image](https://user-images.githubusercontent.com/4418840/96638547-98e5a480-1320-11eb-9616-d8cbabda7d14.png)

Sur la fiche détail d'une rando, le (ou les) étiquette(s) associée(s) à la rando sont affichées avec leur titre, leur recommandation et leur pictogramme : 
![image](https://user-images.githubusercontent.com/4418840/96638672-cd596080-1320-11eb-8963-297eb0c8d4fc.png)

Les étiquettes remplacent aussi le champs spécifique "en coeur de parc" (is_park_centered) avec un mécanisme plus souple, plus riche et générique.

**Comment by camillemonchicourt** [comment]
OK testé en passant en version 2.38.6 de Geotrek-admin sur le serveur de démo (http://geotrekdemo.ecrins-parcnational.fr).
OK les données du champs booléen "En coeur de parc" ont bien été migrées en étiquette "En coeur de parc".
Dans la fiche détail d'une rando, chaque étiquette est affichée comme un champs booléen, ce qui les rendent bien lisibles.
OK aussi dans les filtres, ainsi que dans les exports tableurs et les exports des fiches des randos.
