### ISSUE TITLE
A black / white checkerboard on pictogram

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2364]
It would be better to use checkerboard behind pictogram. Sometime, the pictogram is white. 
When the pictogram is white, in Geotrek Rando it will be white around the pictogram which is not good.

Example :
![Capture d’écran de 2020-10-14 14-06-28](https://user-images.githubusercontent.com/26329336/95986554-7f2af580-0e26-11eb-9a74-4b704a63abc0.png)

**Comment by LePetitTim** [comment]
https://github.com/GeotrekCE/Geotrek-admin/pull/2363

**Comment by gutard** [comment]
mergé dans master
