### ISSUE TITLE
[Remarque] Champs en Fr et En dans les signalements

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2367]
Geotrek-admin version 2.38.3

Bonjour,

L'un des utilisateurs de Geotrek m'a fait remarqué que lorsque l'on sélectionne un signalement, certains champs sont en français et d'autres en anglais (voir pj)

<img width="822" alt="image" src="https://user-images.githubusercontent.com/45095227/96105516-69770800-0eda-11eb-82e7-7d6073d46213.png">

Je suppose qu'il s'agit juste d'un oubli et que l'on peut faire soi-même la traduction comme le précise la documentation mis à jour ?

**Comment by gutard** [comment]
@babastienne est-ce que la PR #2356 ne corrigerait pas ce problème par hasard ?

**Comment by babastienne** [comment]
En effet, les traductions fr sont mises à jour avec la PR #2356. Il s'agissait effectivement d'un oubli.
@mviadere-openig La modification a été prise en charge avec la release 2.38.4
