### ISSUE TITLE
erreur commande loaddem mnt.tif 

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2368]
Geotrek 2.38.3

Bonjour,

lorsque je fais la commande :

'sudo geotrek loaddem mnt.tif'

J'ai ce message d'erreur qui apparaît 

`ERROR 3: Free disk space available is 43801710592 bytes, whereas 79600000000 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE.`

J'ai tenté de récupérer le script python de la commande pour entrer le paramètre recommandé, mais je tombe sur d'autres erreurs python (qui est un langage que je ne maîtrise pas).

Je précise qu'il y a assez d'espace de stockage sur le serveur distant.

**Comment by gutard** [comment]
44 Go libres, 80 Go requis. La commande Geotrek sous-traite à GDAL et c'est GDAL qui envoie ce message. Pour faire un traitement il faut souvent, au moins temporairement, le double de taille, une fois pour la source et une fois pour la destination.

Quelle est la taille du fichier du MNT ? Son pas ? Son étendue géographique ?

**Comment by mviadere-openig** [comment]
Le MNT fait 2,9 Go, il a un pas de 5 m et  il est constitué de 3 départements (Hérault, Aude, Pyrénées-Orientales)
Voici ce que me donne le début de la commande : 

'gdalwarp -t_srs EPSG:2154 -te 105000.000000 6150000.000000 1100000.000000 7150000.000000 mnt.tif /tmp/tmpooddss_v'

Comme j'étais tombé sur ce [post ](https://trac.osgeo.org/gdal/ticket/6750)en cherchant une solution, je pensais que le souci venait de la commande GDAL.

Si jamais il faut effectivement plus d'espace disque je clos le ticket et je contacte mon hébergeur.

**Comment by gutard** [comment]
OK un MNT à 5 m sur 3 départements c'est plutôt gros et je pense qu'on a jamais essayé.

Tu peux tenter de faire `export CHECK_DISK_FREE_SPACE=FALSE` et de relancer la commande. mais si gdal_warp te dit qu'il a besoin d'espace je pense qu'il ne le fait pas pour rien.

Sinon, il faut trouver un MNT au pas de 20 ou 25 m, ou bien transformer le MNT avant de la passer à Geotrek.

**Comment by mviadere-openig** [comment]
Ok, j'ai tenté la commande que tu m'as montré, j'ai toujours le même soucis. Je pensais pas avoir de soucis par rapport à la taille du mnt. Je vais le réduire ou augmenter l'espace disque.

**Comment by gutard** [comment]
Il faudrait probablement faire un dev pour supprimer l'utilisation de gdal_warp, ou bien le rendre optionnel. Je pense que ça réglerait pas mal de soucis d'import de MNT. Ça sert juste à redécouper le MNT selon l'étendue géographique (setting SPATIAL_EXTENT).

**Comment by mviadere-openig** [comment]
Ah d'accord ! Je comprends mieux maintenant, c'est un oubli de ma part, je vais paramétrer le spatial_extent et retenter.

**Comment by gutard** [comment]
Si il est nettement plus petit que la surface des 3 départements ça peut effectivement aider.

**Comment by mviadere-openig** [comment]
Je confirme, il vaut mieux d'abord paramétrer le SPATIAL_EXTENT dans le custom.py puis importer le mnt pour éviter ce problème. Merci Gaël, je clos l'issue.
