### ISSUE TITLE
Profil altimétrique incohérent

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2370]
Pour certains itinéraires le profil altimétrique est erroné avec un graphique dans ce genre 

![image](https://user-images.githubusercontent.com/44799642/96425759-a99cfa00-11fc-11eb-9abf-2059a55c3183.png)

La solution qui semble fonctionner est de retracer l'itinéraire en repartant de zéro mais c'est assez chronophage et n'explique pas la génération du profil initial erroné.

Cela ne semble pas lié à la longueur de l'itinéraire ni au MNT étant donné qu'après un retracage le profil est correct.

**Comment by camillemonchicourt** [comment]
Le profil est cassé quand il y a un problème sur l'itinéraire.
Cela peut se produire si il y a des modifications non conformes sur les tronçons utilisés par l'itinéraire.
Dans ce cas cela peut arriver que cela "casse" les itinéraires utilisant ces tronçons modifiés.

Suite à cela, en effet il faut modifier l'itinéraire, l'ajuster si il a cassé à certaines intersections puis le ré-enregistrer.
Attention il s'agit d'une image, donc ton navigateur la garde souvent en cache. Il est alors possible que la rando soit réparée mais que le profil te soit toujours affiché cassé. Il faut alors rafraîchir en vidant le cache de ton navigateur (CTRL + F5) pour afficher l'image du profil mis à jour.

**Comment by pnrma** [comment]
Merci Camille pour la réponse.
Je confirme que le cache navigateur était bien vidé.

Je ne crois pas que ce soit lié à un problème de tronçons car lorsque c'est le cas on ne peut tout simplement pas faire passer l'itinéraire par les intersections problématiques.

Par ailleurs, je viens d'avoir deux cas de profils incohérents sur des itinéraires que j'ai résolu simplement en supprimant un point de passage "inutile" (c'est à dire qui pouvait être supprimé sans que l'itinéraire ne soit modifié) et en sauvegardant. Peut-être que la sauvegarde après une modification, même mineure, permet un recalcul du profil.

**Comment by camillemonchicourt** [comment]
Oui ça a été corrigé car en modifiant (ou supprimant) un des points de passage puis en enregistrant, cela a relancé la calcul de la géométrie de l'itinéraire, ainsi que ses infos d'altimétrie et son profil.

**Comment by pnrma** [comment]
Ok du coup est-ce que c'est considéré comme un bug ou on ferme cette issue ?

**Comment by camillemonchicourt** [comment]
Si il y a des soucis d'itinéraires cassés alors il faut identifier bien plus précisément dans quel cas, quel contexte.
Donc à moins d'analyser cela en détail, sinon on peut fermer l'issue.

**Comment by pnrma** [comment]
Ok je rouvrirai si j'arrive à avoir plus d'éléments et à identifier dans quel cas précis cela se produit.
