### ISSUE TITLE
Intégration du format d'export OpenAir au module de sensibilité

### ISSUE THREAD

**Issue by lpofredc** [GeotrekCE/Geotrek-admin#2372]
Le format [OpenAir](http://www.winpilot.com/UsersGuide/UserAirspace.asp) est généralement utilisé par les pratiquants de vol libre pour réaliser des cartographies spécifiques au domaine aérien, notamment pour matérialiser les zones d’exclusion aériennes et les intégrer dans des dispositifs de guidage en capacité de reconnaître les altitudes terrain.

Depuis quelques années un important travail bénévole est réalisé pour convertir des zones de sensibilité pour les rapaces rupestres ou les zones d’exclusion de pratiques liées à des réglementations environnementales en format OpenAir.

Ce format permet aux pilotes de vol libre d'être avertis lors de leur vol (grâce à un signal sonore) de la proximité de ces zones. ils peuvent ainsi adapter leur plan de vol au plus juste par rapport aux zones à éviter.

De nombreuses démarches de concertation entre pratiquants et gestionnaires d’espaces protégés ou associations environnementales permettent de mettre en place ces zones de « sensibilité » pour certaines espèces à enjeux au regard de la pratique du vol libre. Néanmoins, il est parfois difficile de communiquer au plus juste sur ces zones, du fait de leur représentation en trois dimensions (notion de bulle de quiétude avec une représentation sphérique ou cylindrique), de l’impossibilité de matérialiser ces zones, et de la difficulté pour un pilote de vol libre, qui peut parcourir une distance importante lors de son vol, de mémoriser et prendre en compte ces informations en plus des paramètres inhérents à son activité.

**Automatiser la conversion des zones de sensibilité renseignées dans Biodiv’sports en format OpenAir** permettra ainsi de faciliter la diffusion et la conversion de ces zones dans le format correspondant à celui déjà utilisé par les pratiquants de vol libre. Grâce au format OpenAir les pratiquants de vol libre pourront intégrer directement à leur dispositifs de guidage les informations relatives à ces zones de sensibilité pour la faune dans les secteurs de vol prévu.

_Diffuser au plus large l’information dans le format adéquat renforcera la possibilité de prise en compte de la faune dans la pratique du vol libre._

La LPO Auvergne-Rhône-Alpes prévoit d'intégrer ce format d'export au module `sensitivity` pour le rendre aussi disponible sur le widget de consultation de biodiv-sport https://biodivsports-widget.lpo-aura.org/. Un premier développement en cours consiste à développer une librairie python permettant de générer de l'openair à partir de wkt: https://github.com/lpoaura/pyopenair/

Some examples of uses:

  - http://pascal.bazile.free.fr/paraglidingFolder/divers/GPS/OpenAir-Format/
  - https://www.data.gouv.fr/en/datasets/cartographies-aeriennes-dediees-a-la-pratique-du-vol-libre/

**Comment by camillemonchicourt** [comment]
OK intéressant si ça ajoute une diffusion à ces données tout en restant générique et ouvert.

**Comment by camillemonchicourt** [comment]
Intégré dans la version 2.101.0
