### ISSUE TITLE
Pictogrammes "Types de service" non présents dans les données API

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2376]
Les pictogrammes ajoutés dans `Itinéraire › Types de service` et que l'on peut utiliser dans la partie `Description `des itinéraires ne sont pas inclus lors de la synchronisation des données API mobile ou Rando.
Cela occasionne des images manquantes côté site Rando et application mobile.
Par ailleurs, le chemin vers l'image utilisé dans l'appli mobile est un chemin relatif du type :` /media/upload/picto_poteau.png`
contrairement aux autres images qui font appel au chemin absolu du type : `https://www.monsiteweb.fr/mobile/media/upload/monimage.png`

**Comment by gutard** [comment]
Concernant Geotrek-rando, je pense que le problème est ailleurs. Essayez de changer `"API_URL"` par `""` au lieu de `"/data"` dans les settings, modifiez la configuration nginx en conséquence (selon cet [exemple](https://github.com/GeotrekCE/Geotrek-rando/blob/master/docs/http-server.md)) et dites nous si ça corrige le problème.

Concernant Geotrek-mobile, là aussi c'est un peu plus subtil. Les URL avec un nom de domaine ne sont pas accessibles en mode déconnecté donc c'est plutôt une bonne chose qu'il ne soit pas présent. Par contre, c'est possible effectivement que les pictos des services ne soient pas synchronisés. Geotrek étant un logiciel libre qui est la somme des contributions des ses utilisateurs, n'hésitez pas à proposer vous-même un correctif sous forme d'une pull request sur Github, ou à financer ce correctif.

**Comment by pnrma** [comment]
modifier le paramètre `API_URL` corrige le problème pour Geotrek-rando, je n'ai pas touché à la configuration nginx qui était déjà correcte.

Contrairement à ce que j'ai mentionné, les pictos `Types de service` sont pris en compte lors de la synchro rando.

En revanche pour Geotrek-mobile, dans la mesure où ces images sont appelées directement depuis un dossier `/media/upload/` qui n'existe pas en local dans l'application mobile, cela ne change pas le problème.

Pour être plus précis, les balises `img` pour ces images sont directement intégrées dans l'item `description` des fichiers `trek.geojson` de l'API mobile et le paramètre `src `de l'image n'intègre pas l'url de l'api. Exemple : `<img src=\"/media/upload/monpicto.png\" alt=\"Mon picto\" />`.

Par ailleurs, la synchronisation mobile ne semble effectivement pas prendre pas en compte les pictos de `Types de services`.

**Comment by gutard** [comment]
La release 2.50.0 corrige la synchronisation des pictogrammes des types de services pour le mobile.
