### ISSUE TITLE
sensitivity_sensitivearea does not exist

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2378]
Bonjour,

Je n'arrive pas à faire marcher le module sensitivity.
Je n'ai pas la table sensitivity_sensitivearea : 
> ProgrammingError : relation "sensitivity_sensitivearea" does not exist LINE 1: SELECT "sensitivity_sensitivearea"."id" FROM "sensitivity_se... ^
> ERROR:  relation "sensitivity_sensitivearea" does not exist at character 46
> STATEMENT:  SELECT "sensitivity_sensitivearea"."id" FROM "sensitivity_sensitivearea" WHERE ("sensitivity_sensitivearea"."deleted" = false AND "sensitivity_sensitivearea"."eid" IS NOT NULL AND "sensitivity_sensitivearea"."published" = true)

Ce qui est bizarre c'est que cette fois j'ai le même problème avec une install neuve (sur docker)
Cette table est-elle créée lors de l'initialisation du module ou à l'installation ?
Puis-je la créer à la main ? où pourrais-je trouver le code SQL de création ? 

En pratique je fais : 
```
vi /opt/geotrek-admin/var/conf/custom.py
      "INSTALLED_APPS += ('geotrek.sensitivity', )"
vi /opt/geotrek-admin/var/conf/parsers.py
     "from geotrek.sensitivity.parsers import BiodivParser"
sudo service geotrek restart
sudo geotrek import BiodivParser
```

Merci

**Comment by camillemonchicourt** [comment]
En effet je ne sais pas pourquoi ces tables ne sont pas installées chez toi.
J'avais testé l'installation du module sur le serveur de DEMO et c'est OK à l'époque, mais là je ne l'ai pas installé ni testé depuis un moment.

Pour la documentation, il y en a 
- ici concernant l'installation : https://geotrek.readthedocs.io/en/master/sensitivity.html
- ici concernant la configuration du module : https://geotrek.readthedocs.io/en/master/advanced-configuration.html#sensitive-areas
- ici concernant l'import : https://geotrek.readthedocs.io/en/master/import.html#sensitive-areas-import

Et il y a aussi une doc de l'API : https://geotrek.ecrins-parcnational.fr/ressources/gt/01-zones-sensibilite/doc-api.pdf
Et une de l'import fichier : https://geotrek.ecrins-parcnational.fr/ressources/gt/01-zones-sensibilite/doc-import.pdf

Certainement à nettoyer, regrouper car il y a des redondances et des compléments, et certaines peut-être plus à jour. Mais comme ça tu as tout.

**Comment by gutard** [comment]
@camillemonchicourt, seules les migration qui concerne les apps Django activées se font à l'installation. Donc si on active une app après coup il faut passer les migrations. Je ne suis pas sûr sur la doc soit bonne.

Après tout changement de conf, même si c'est pas systématiquement nécessaire, il faut faire :
* Docker : `docker-compose run --rm web update.sh`
* Paquet Ubuntu : `sudo dpkg-reconfigure -u geotrek-admin`

**Comment by pierreloicq** [comment]
Merci ça marche beaucoup mieux comme ça :-)
