### ISSUE TITLE
installation via docker

### ISSUE THREAD

**Issue by mougetann** [GeotrekCE/Geotrek-admin#2380]
Bonjour,

J’ai commencé l’installation de geotrek-admin sur une Debian 10, via docker.
J’ai suivi la documentation d’installation pour un environnement de production https://geotrek.readthedocs.io/en/master/docker.html.
Cependant, il me semble qu’il me manque un composant, ou qu’un élément m’échappe.

Comment se fait l’accès au site ?
En tapant l’URL SERVER_NAME:WEB_PORT en remplaçant SERVER_NAME et WEB_PORT par les valeurs définies dans le .env, je suis redirigée vers la page de login, mais les différents fichiers du dossier static ne sont pas trouvés (erreur 404).
Le dossier var et ses sous-dossiers est bien existant sur l’host et dans le container web.

Cordialement

**Comment by gutard** [comment]
La doc est incomplète. Pour finaliser l'installation, il faut installer nginx (ou apache) et configurer un reverse proxy qui sert également les URL /static/ et /media/ depuis le dossier /var du répertoire d'installation.

Vous pouvez vous inspirer de https://github.com/GeotrekCE/Geotrek-admin/blob/master/conf/nginx.conf.in en replaçant /opt/geotrek-admin par le répertoire d'installation et ${…} par les valeurs correspondantes.

N'hésitez pas à contribuer en proposant une pull request GitHub pour compléter la documentation.

**Comment by gutard** [comment]
Je rajoute que les paquets Debian et Ubuntu étant très proches, il devrait être possible d'adapter le packaging pour que la méthode d'installation par paquet plus automatisée soit également disponible sous Debian. Toute contribution dans ce sens est également bienvenue.

**Comment by mougetann** [comment]
Merci pour votre réponse, c'est désormais fonctionnel. #2384
