### ISSUE TITLE
mise à jour poi en masse

### ISSUE THREAD

**Issue by pnrm** [GeotrekCE/Geotrek-admin#2383]
Bonjour,
J'ai une base externe à Geotrek Admin d'environ 1500 poi que j'ai chargé dans Geotrek admin par le biais d'un fichier csv.
Je voudrais mettre à jour cette base de poi sur geotrek admin avec un nouveau fichier csv.
Est ce que je dois supprimer ces pois et faire un nouvel import, si c'est le cas comment supprimer les pois en masse dans geotrekadmin ? (je pensais pouvoir le faire à partir de qgis mais je n'ai pas accès à la couche poi)
Merci

**Comment by camillemonchicourt** [comment]
Attention, les POI ne sont pas une couche de géométrie à plat classique, mais en segmentation dynamique de manière relative aux tronçons (https://makina-corpus.com/blog/metier/2014/la-segmentation-dynamique).

Du coup on ne peut pas les importer directement dans la BDD à plat. Voir le sujet sur les fonctions d'import, il y en a une spécifique pour les POI : https://github.com/GeotrekCE/Geotrek-admin/issues/952

Voir la doc sur les fonctions d'import depuis un fichier : https://geotrek.readthedocs.io/en/master/import.html#import-from-a-file

**Comment by pnrm** [comment]
Mon premier import a été réalisé a partir d'un fichier csv que j'avais converti en shape. Mes 1500 éléments de départ sont bien intégrés dans geotrek admin avec la commande geotrek loadpoi patrimoine.shp
![image](https://user-images.githubusercontent.com/18323883/97587062-4597e400-19fb-11eb-8436-b6d46a530c77.png)
J'ai un fichier de mise à jour de ces 1500 éléments dont un champ correspond a l'url de la photo de l'élément. 
Est ce cette url peut etre utilisée pour afficher une image personnalisé plutôt que celle par défaut ? Comment faire cette mise à jour massive ?
Merci

**Comment by camillemonchicourt** [comment]
OK c'est plus clair. Donc tu avais bien utilisé la fonction dédié à l'import de POI, super.
Il est possible de faire une mise à jour de ces POI si tu as un champs commun permettant de faire la jointure entre ta table source et la table des POI dans Geotrek. C'est plus compliqué si tu veux modifier leur géométrie du fait de la segmentation dynamique, mais ça semble pas être ton cas.

Les images des POI (et de tous les autres objets) sont stockés dans une table dédiée : ``public.common_attachment``. 
Les fichiers liés à un objets (images ou autre) peuvent être uploadés sur le serveur depuis l'interface de Geotrek-admin (onglet "Fichiers liés" d'un objet, POI ou autre) ou alors il est possible de renseigner l'URL d'un fichier (champs ``public.common_attachment.attachment_link``).

Tu peux donc remplir cette table depuis ton fichier source, mais il faut arriver à refaire le lien entre ton fichier source, les POI et leur référence dans la table des fichiers liés. Assez costaud à faire, mais tiens nous au courant.

Pour voir le détail du modèle de données : https://github.com/GeotrekCE/Geotrek-admin/tree/master/docs/data-model

**Comment by pnrm** [comment]
Merci Camille 
je n'ai pas de champs de commun, est ce qu'il y a une solution pour supprimer les pois en masse et les réimporter avec la commande
`sudo geotrek loadpoi patrimoine.shp` ?
Si je peux réimporter mes poi, les urls de mes photos peuvent elles être prise en compte avec la commande d'import (je crois comprendre que non)?

**Comment by camillemonchicourt** [comment]
> je n'ai pas de champs commun

C'est le problème. Pourtant le chamsp "ID externe" (``public.trekking_poi.eid``) dans la table des POI est fait pour ça. Stocker l'ID de la source des données pour pouvoir faire un lien en cas de mise à jour. Ce champs existe aussi dans les itinéraires, les contenus touristiques etc... pour ce même usage de mise à jour.

> est ce qu'il y a une solution pour supprimer les pois en masse

Pas à ma connaissance. A faire directement dans la BDD mais en connaissance de cause. Il faut supprimer les POI dans la table ``public.trekking_poi.eid``, mais aussi leur équivalent dans la table des événements de segmentation dynamique ``public.core_topology`` (avec une jointure entre ``core_topology.id`` et ``trekking_poi.topo_object_id``). Et la table de lien de segmentation dynamique entre les événements et les tronçons ``public.core_pathaggregation``.

Je te dis ça de mémoire, à tester et regarder de plus prêt en analysant la BDD. Il devrait y avoir des contraintes d'intégrité et des clés étrangères qui font que si tu supprimes un POI, ça supprime ses objets liés en cascade dans les autres tables, mais je suis pas sur que ce soit le cas, du moins pas partout. Je te laisse analyser et creuser ça. Éventuellement nous faire un retour sur ta méthode si tu t'y lances.

> Si je peux réimporter mes POI, les URLs de mes photos peuvent elles être prise en compte avec la commande d'import

Non, du moins je vois pas comment. Comme évoqué, les médias sont dans une autre table à part. 
Il doit être possible d'enrichir les fonctions d'import de POI pour gérer aussi des médias, mais ça demande des développements à réaliser ou financer si tu le souhaites.
