### ISSUE TITLE
Menu latéral - Scroll horizontal et tooltips

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2389]
Bonjour,
J'ai fais la migration en 2.38.6 sur mon serveur de test. Tout fonctionne correctement sauf le menu de gauche qui laisse apparaitre des barres de défilement. En plus, les infos bulles des menu n'apparaissent plus. Je suis sur FF 60.9.0 esr.
![2020-11-03 18_42_31-Tronçons _ Geotrek](https://user-images.githubusercontent.com/33490969/98021910-33f07b00-1e05-11eb-81f1-032c6a063bab.png)

**Comment by jeromesourdin** [comment]
Selon le temps nécessaire, nous pouvons utiliser notre TMA.

**Comment by gutard** [comment]
Bonjour Jérôme,

> Tout fonctionne correctement sauf le menu de gauche qui laisse apparaitre des barres de défilement.

C'est volontaire, si la barre est plus grande que la hauteur de la fenêtre. Cela évite d'autres effets de scroll encore plus indésirables sur la carte et le sélecteur de couches. Par contre, on doit pouvoir améliorer le responsive pour que la taille des icônes diminue selon l'espace disponible.

Nous avons l'habitude de travailler avec des écrans de 1920x1080 pixels. Quelle est ta taille d'écran ?

> En plus, les infos bulles des menu n'apparaissent plus.

Ça, par contre, c'est plus gênant.

> Selon le temps nécessaire, nous pouvons utiliser notre TMA.

Dans ce cas, il faut envoyer un mail à Makina Corpus. Github sert pour le support communautaire, pas pour le support commercial.

**Comment by camillemonchicourt** [comment]
Oui le scroll vertical sur le menu c'est bien et utile.
Mais en effet un scroll horizontal est aussi apparu dans les dernières versions quand on survole le menu : 

![image](https://user-images.githubusercontent.com/4418840/98084961-e6175980-1e7c-11eb-9548-acf234c28df0.png)

Pas très grave mais pas idéal ni utile me semble t-il ?

**Comment by jeromesourdin** [comment]
Je comprends l'utilité, mais dans mon cas, elle n'a pas a s'afficher, car le menu rentre en pleine page. Des que je déplace ma souris sur le menu zone sensible dans le coin en bas a droite (quand les icônes sont "petites") la barre apparait alors qu'il n'y en a pas besoin. 
Pour les infos bulles, elle sont dessous la liste.

**Comment by gutard** [comment]
OK. Avec cette description plus précise je comprends mieux. En fait c'est quand le tooltip s'active (il est masqué mais il s'active quand même) que ça élargit la taille de la barre et que ça crée une barre de scroll. Donc résoudre le problème des tooltips résoudra automatiquement le problème de scroll.

**Comment by numahell** [comment]
Corrigé dans la PR #2397

**Comment by numahell** [comment]
Le correctif est désormais disponible dans la version [2.40.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.40.0). Je ferme donc cette issue.
