### ISSUE TITLE
Création d'une bdd Geotrek locale

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-admin#2390]
Bonjour,

Je transfert mon message issue du googlegroup

Je souhaites créer une base de données locale geotrek (structure --> schema, tables, trigger, fonction, ...) sans passer par l'installation. Savez vous ou je pourrais trouver les scripts permettant sa création ?

Bonne journée,

Cordialement,

-----------------------

Réponse de Camille Monchicourt : 

Bonjour,

Pour les sujets et échanges techniques, privilégiez l'utilisation de tickets sur les dépôts Github liés au sujet, Geotrek-admin dans ce cas : https://github.com/GeotrekCE/Geotrek-admin/issues 

Sauf erreur de ma part, la BDD est créée majoritairement par l'applicatif Python (Django) à partir des modèles des différents modules. 
Par exemple pour le modules des randonnées : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/models.py 
Dans chaque module, il y a une partie SQL complémentaire pour les spécificités de la BDD qui ne peuvent pas être créées par les modèles Django (trigger, fonctions ...), par exemple pour les randos : https://github.com/GeotrekCE/Geotrek-admin/tree/master/geotrek/trekking/sql 

Depuis peu le MCD est disponible en PDF, par module ou complet (global.pdf) : https://github.com/GeotrekCE/Geotrek-admin/tree/master/docs/data-model 

Du coup si vous voulez une BDD sans installer l'applicatif Geotrek-admin, le mieux est de faire un dump d'une BDD Geotrek existante et de la remonter sur un autre PostgreSQL.
Je peux vous faire un dump de la BDD du Geotrek-admin de notre serveur de démo (http://geotrek-admin.ecrins-parcnational.fr/) si besoin.

Bonne journée.

**Comment by eprouteau** [comment]
Je vais du coup faire une installation rapide de Geotrek pour récupérer un DUMP

Bonne journée,

**Comment by camillemonchicourt** [comment]
OK merci, tenez nous au courant si vous avez pu réaliser cela ?

**Comment by eprouteau** [comment]
Je viens d'intégrer le dump sans soucis. Par contre lors de la saisie d'un tronçon dans Qgis j'ai ce type de soucis ?

![image](https://user-images.githubusercontent.com/1401902/98366117-beb6bd00-2033-11eb-861f-32a383a76798.png)

Pourtant les fonctions sont bien toutes présentes

**Comment by camillemonchicourt** [comment]
OK vous êtes sur une ancienne version de la BDD où les tables étaient encore en français et dans des schémas séparés.
Depuis la version 2.32.7, cela a été revu pour simplifier les développements et la maintenance : https://github.com/GeotrekCE/Geotrek-admin/issues/2137

Les tables sont en anglais et regroupées dans le schéma ``public`` (par défaut car cela reste paramétrable).

Si vos tables et fonctions sont encore dans des schémas distinctes, il faut étendre votre utilisateur de BDD pour qu'il puisse directement rechercher les tables et fonctions dans l'ensemble des schémas. Sinon il ne trouve pas les tables et fonctions qui sont dans d'autres schémas mais dont ceux-ci ne sont pas spécifiés dans les fonctions et triggers.

Voir https://github.com/GeotrekCE/Geotrek-admin/issues/1311

**Comment by eprouteau** [comment]
J'étais rester sur une ancienne version de geotrek admin. Je test avec la dernière version

**Comment by eprouteau** [comment]
J'ai installé la dernière version de geotrek-admin sur un vps. Par contre, je n'arrive pas à connaitre le login par défaut pour se connecter à la base avant on était sur geotrek/geotrek

**Comment by camillemonchicourt** [comment]
Un mot de passe est généré automatiquement par défaut. 
Il est indiqué dans la configuration du paquet, dans le fichier ``/opt/geotrek-admin/var/conf/env``.
C'est indiqué dans la doc de configuration (https://geotrek.readthedocs.io/en/master/configuration.html), mais peut-être à indiquer ailleurs dans la doc en plus ?

**Comment by eprouteau** [comment]
Un renvoi dans la section d'installation pourrai être pas mal effectivement.

Une autre question, comment connait-on le mot de passe de l'utilisateur linux geotrek créé ?

Bonne journée,

**Comment by gutard** [comment]
> Un renvoi dans la section d'installation pourrai être pas mal effectivement.

N'hésitez pas à proposer cette modification à l'aide d'une Pull Request sur GitHub.

> comment connait-on le mot de passe de l'utilisateur linux geotrek créé ?

L'utilisateur Linux geotrek n'a pas de mot de passe.
