### ISSUE TITLE
Problème avec sudo dpkg-reconfigure geotrek-admin

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2391]
Bonjour à tous,
J'ai passé mon G.Admin en >2.33 et je souhaite configurer via sudo dpkg-reconfigure geotrek-admin l'adresse de mon serveur rando et l'adresse de mon admin. 
Par défaut j'ai '_' pour mon nom de serveur et j'ai '*' pour mon serveur rando.
Dès que je veux modifier avec http://randoadmin.parc-haut-jura.fr et https://randonature.parc-haut-jura.fr, dès que je vais au bout de la conf, j'ai mon serveur qui tombe en rade, même en remettant les valeurs par défaut, rien n'y fait, je suis obligé de restaurer mon snapshot.
Une idée du problème ?

**Comment by camillemonchicourt** [comment]
Pas certain, mais pour le server_name au moins je pense qu'il faut pas le http:// devant l'URL.
Sinon il faudrait des logs pour voir l’éventuel soucis.

**Comment by thomaspnrhj** [comment]
Effectivement c'était juste ça! Merci Camille !
