### ISSUE TITLE
Paramétrage envoi mail version >2.33

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2393]
Dans les versions <2.33, on pouvait configurer dans /home/adminsig/Geotrek-admin/etc/settings.ini les différents paramètres pour l'envoi de mails : 
mailfrom = *****
mailhost = ****
mailuser = *****
mailpassword = ******
mailport = 25
mailtls = False
mailalertsubject = Haut-Jura, Rando et pleine nature : Signalement
mailalertmessage = Bonjour,

                    Nous avons bien reçu votre signalement. Celui-ci va être transféré au service concerné. 

                    Merci pour votre collaboration,

                    Cordialement
                    PNR du Haut-Jura - https://randonature.parc-haut-jura.fr
	
De ce que j'ai compris, dans les version >2.33, les configs de settings.ini doivent être positionnés dans /opt/geotrek-admin/var/conf/env
Pourtant dans la doc (https://geotrek.readthedocs.io/en/master/advanced-configuration.html#email-settings), il est mentionné : Email configuration takes place in /opt/geotrek-admin/var/conf/custom.py, where you control recipients emails (ADMINS, MAIL_MANAGERS) and email server configuration.
Je ne retrouve pas ces paramètres dans la doc par contre, est-ce que quelqu'un peut m'en dire plus ? J'ai loupé quelques chose dans la doc ?

Merci,
Thomas

**Comment by camillemonchicourt** [comment]
Les paramètres de l'ancien fichier ``settings.ini`` ne sont pas forcément les mêmes que ceux de la configuration du base du paquet présentes dans la fichier ``/opt/geotrek-admin/var/conf/env`` (définis avec la commande ``sudo dpkg-reconfigure geotrek-admin``).

La documentation indique en effet que les paramètres des emails sont désormais dans la configuration avancée (``/opt/geotrek-admin/var/conf/custom.py``). 
La phrase suivante indique que l'exemple de cette configuration se trouve dans le fichier d'exemple https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/custom.py.dist

Et qu'une fois renseignés ces paramètres, tu peux vérifier le fonctionnement avec la commande ``sudo geotrek test_managers_emails``.

**Comment by thomaspnrhj** [comment]
Top, j'étais passé à côté, encore merci Camille, !

**Comment by thomaspnrhj** [comment]
Deux questions complémentaires : 
> Je rentre mes confs pour mon smtp.orange.fr qui marchait jusqu'à maintenant, mais ça ne fonctionne plus. J'ai testé avec gmail aussi mais ça fonctionne pas non plus : 
Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/test_managers_emails.py", line 12, in handle
    mail_managers(subject, message, fail_silently=False)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/mail/__init__.py", line 116, in mail_managers
    mail.send(fail_silently=fail_silently)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/mail/message.py", line 306, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 126, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.6/smtplib.py", line 867, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError r9sm11880143wrg.59 - gsmtp', 'pnrhautjura39@gmail.com')

Camille, il me semble que tu utilises gmail pour l'envoi des mails c'est bien ça ? Tu pourrais me montrer ta conf pour comparer ?

> On pouvait également auparavant personnaliser le message pour les signalements avec mailalertsubject et mailalertmessage, c'est encore possible ? 

Merci d'avance,
Thomas

**Comment by gutard** [comment]
La réponse de gmail est assez claire :
> Authentication Required
>  https://support.google.com/mail/?p=WantAuthError

Le souci avec gmail c'est qu'il y a une sécurité renforcée par rapport au standard SMTP. Les solutions sont décrites dans le lien ci-dessus : il faut configurer le mode moins sécurisé. Ou bien créer un mot de passe spécifique à l'usage de Geotrek.

> On pouvait également auparavant personnaliser le message pour les signalements avec mailalertsubject et mailalertmessage, c'est encore possible ?

Oui. En surchargeant les traductions de
```
"Geotrek : Signal a mistake"
```
et de
```
"Hello,

We acknowledge receipt of your feedback, thank you for your interest in Geotrek.

Best regards,

The Geotrek Team
http://www.geotrek.fr"
```

Cf. https://geotrek.readthedocs.io/en/master/advanced-configuration.html?highlight=translat#override-translations

**Comment by thomaspnrhj** [comment]
Merci c'est tout bon de mon côté !
