### ISSUE TITLE
Définition du spatial extent

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-admin#2394]
Bonjour,

Dans les anciennes méthode d'installation, on pouvait définir un spatial extent lors de l'installation. Dans la nouvelle version d'installation on ne le définit pas. Du coup lorsque j'ai intégré le MNT celui-ci se basait sur l'extent france. DU coup faut-il modifier l'extent juste après l'installation via le fichier custom.py et intégrer le MNT ensuite ? ou y a t-il une manip pour modifier l'extent autrement ?

Bonne journée,

**Comment by gutard** [comment]
> Faut-il modifier l'extent juste après l'installation via le fichier custom.py ?

Oui.

> et intégrer le MNT ensuite ?

Si vous être en France métropolitaine et que vous chargez le MNT avant de changer l'extent, ce n'est pas grave. L'éventuelle partie du MNT située en dehors de l'extent sera quand chargée mais cela n'a pas grande conséquence.
