### ISSUE TITLE
Intervention ne s'affiche pas sur la carte après sa création

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2396]
Geotrek-admin 2.38.3

L'intervention se crée et est listée, mais ne s'affiche pas sur la carte à côté. 

Voici les logs : 

[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/5529432/systemd-geotrek-ui.log)

**Comment by gutard** [comment]
Il faudrait plutôt regarder le log de API plutôt que UI. C'est peut-être #2357 que tu avais déjà eu et qui est fixé en 2.38.4.

**Comment by mviadere-openig** [comment]
Ok, je poste toujours le log api au cas où :

[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/5529520/systemd-geotrek-api.log)

**Comment by mviadere-openig** [comment]
La commande sudo geotrek remove_stale_contenttypes n'affiche rien, comparé à la dernière fois où je l'ai utilisé. 

Pour info l'intervention s'affiche bien, mais à l'autre bout de la carte (elle est créée dans l'Aveyron et on voit sa position en Afrique : 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/45095227/99066931-18763480-25aa-11eb-8866-809f6692084d.png">

Je suis passé en Geotrek-admin 2.39.1, aucun changement. De plus, quand je retourne à la liste des interventions, l'intervention créée précédemment..disparaît de la carte, et de la liste.

**Comment by gutard** [comment]
OK, j'ai reproduit. Cela concerne les interventions qui créent des nouvelles topologies, pas celle qui référencent des topologies existantes. Probablement en rapport avec #2275.

**Comment by mviadere-openig** [comment]
D'accord, Gaël du coup quelle est la solution pour le moment ?

**Comment by gutard** [comment]
C'est corrigé à partir de la version 2.43.0
