### ISSUE TITLE
ERROR: No anchor #_msocom_1 for internal URI reference

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2402]
Bonjour à tous,
Lors de ma sync rando, je reçois une vingtaine de messages d'erreur suivants : 

ERROR: No anchor #_msocom_1 for internal URI reference
No anchor #_msocom_1 for internal URI reference
Report
No anchor #_msocom_1 for internal URI reference

Et 

ERROR: No anchor #_msocom_2 for internal URI reference
No anchor #_msocom_1 for internal URI reference
Report
No anchor #_msocom_1 for internal URI reference

Je ne retrouve aucune référence à une erreur similaire ou une conf et dans les logs j'ai rien, une idée du problème ?

Merci,
Thomas

**Comment by gutard** [comment]
Concrètement, il y a un problème sur les PDF générés ou pas ?

**Comment by thomaspnrhj** [comment]
A priori aucun problème, tout est bon pour mes pdf !

**Comment by gutard** [comment]
OK. A mon avis il y a suffisamment de problèmes à régler pour ne pas en chercher là où il n'y en a pas ;)

C'est probablement lié à un copier/coller depuis Word dans le descriptif des itinéraire (mso -> MicroSoft Office). Pour trouver où il faut faire une recherche sur `msocom` dans la base SQL ou dans le fichier `treks.geojson` et corriger. Aucune conséquence, sauf peut-être des liens cassés dans certains PDF. Pour moi ça devrait être un avertissement, pas une erreur.

Avec un dev on pourrait probablement filtrer le markup HTML pourri envoyé par Word mais est-ce prioritaire ?

**Comment by thomaspnrhj** [comment]
Ok étant donné le nombre de retour d'erreur, je voulais juste m'assurer que ça ne soit pas un problème impactant, mais si ce n'est que ça c'est effectivement pas prioritaire !

**Comment by thomaspnrhj** [comment]
Résolu : il s'agit bien d'un codage Word suite à des copier/coller réalisés par un partenaire : recherche du terme mso dans mes tables treks, pois, touristicscontents et nettoyage des html.

**Comment by camillemonchicourt** [comment]
Quelques exemples de requêtes pour retrouver ces bouts de copié/collé depuis Word dans les champs texte : 

```SQL
SELECT * FROM trekking_poi 
WHERE description ILIKE '%msocom%';

SELECT * FROM trekking_trek
WHERE description_teaser ILIKE '%msocom%';

SELECT * FROM trekking_trek
WHERE description ILIKE '%msocom%';

SELECT * FROM trekking_trek
WHERE ambiance ILIKE '%msocom%';

SELECT * FROM trekking_trek
WHERE public_transport ILIKE '%msocom%';

SELECT * FROM trekking_trek
WHERE access ILIKE '%msocom%';
```
