### ISSUE TITLE
Pratique outdoor

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2407]
- [x] Lien avec les sites
- [x] Cases à cocher pour choisir les pratiques dans le 1er onglet du site
- [x] champ étiquettes
- [x] champ thèmes
- [x] champ lieux de renseignement
- [x] champ type de site (liste selon la pratique)
- [x] champ portails
- [x] champ brouillon/publié
- [x] champs source
- [x] champ liens web

**Comment by gutard** [comment]
Concernant le champ usage proposé dans le MCD pour répondre au besoin de noter des choses du genre « site école » ou « site sportif », je propose de le remplacer par des labels sur le même modèle que ce qui a été fait pour les itinéraires. @camillemonchicourt, ton avis ?

**Comment by camillemonchicourt** [comment]
Je viens de regarder la description du MCD (https://geotrek.ecrins-parcnational.fr/ressources/gt/07-geotrek-apn/2019-08-23-Presentation-MCD-outdoor.pdf) et celle-ci indique pour ce champs de la table ``site_pratique`` : 

> “usage”  est un champs spécifique à la pratique de l’escalade, il permet d'indiquer s’ils'agit d’un site école, d’un site sportif ou d’un terrain d’aventure. 

Mais en effet autant en faire un champs générique et élargir les possibilité. Dans tous les cas, il s'appuie sur une liste de valeurs. Il faut pouvoir filtrer les sites en fonction de ce champs. A voir si les valeurs proposées dépendent de la pratique. 

Même si le champs est rendu plus générique, je ne sais pas si il faut lui garder une dénomination précise (``usage``) ou plus générale (``étiquette``). Je me renseigne pour essayer de voir plus clair sur son utilisation.

**Comment by camillemonchicourt** [comment]
Vu avec @lelannl, la notion d'usage avait été mise de côté lorsque les besoins ont été précisés cet été. 
Voir ce document qui m'avait échappé : https://geotrek.ecrins-parcnational.fr/ressources/gt/07-geotrek-apn/2020-08-besoins-outdoor.pdf

Mais il semblerait que la notion d'étiquette générique pourrait avoir sa place sur les sites, pour éviter de retomber dans le champs spécifique "coeur de parc" et que pour la table des pratiques d'un site, on remplace l'usage par une notion de type de site dont la liste serait définie par pratique.

A murir, affiner pour un prochain sprint.

**Comment by camillemonchicourt** [comment]
### Choix de champs : 
- Etiquettes sur le site (même table que la rando)
- Thèmes sur le site (même table que la rando)
- Lieux de renseignement sur le site (même table que la rando)
- Type sur Site_pratique (liste des types définie par pratique)

### A discuter : 
- Portail sur le site ou site_pratique
- Publié sur le site ou site_pratique
- Source sur le site ou site_pratique (même table que la rando)
- Liens web sur le site ou site_pratique

**Comment by camillemonchicourt** [comment]
Après discussion on a retenu le fait que les sites soient mono-pratiques et non plus multi-pratiques. Cela simplifie donc le modèle de données avec suppression du niveau site_pratique. On associe une pratique au site mais aussi les autres informations.

Le fait qu'un site ait plusieurs pratiques sera géré par les possibilités de lier les sites entre eux et de les hiérarchiser (site, sous-site, sous-sous-site...) déjà prévu par ailleurs pour gérer les sites et leurs secteurs ainsi que l'itinérance.

**Comment by camillemonchicourt** [comment]
Le module Outdoor s'enrichit dans la version 2.44.0 avec plus de champs, directement associés au site, la notion de Site_pratique ayant été écartée : 

![image](https://user-images.githubusercontent.com/4418840/102685202-4240fd80-41df-11eb-9c5c-7a8181c9423c.png)

Champs ajoutés : 

- brouillon/publié
- site parent
- période
- orientation
- vent
- étiquettes (déplacées du module trek au module common)
- thèmes
- lieux d'information
- portail
- source
- liens web
- type de site (spécifiques à la pratique, à définir dans l'admin)
