### ISSUE TITLE
Outdoor - Orientations

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2409]
- [x] Ajouter les noms des champs dans les filtres

**Comment by camillemonchicourt** [comment]
OK, intégré dans la 2.44.0 : 

![image](https://user-images.githubusercontent.com/4418840/102685416-ad3f0400-41e0-11eb-873a-b139cd8b75fe.png)

Mais dans les filtres de la liste des sites, le champs de l'orientation et du vent ne sont pas nommés, du coup on ne peut pas les distinguer : 

![image](https://user-images.githubusercontent.com/4418840/102685442-dd86a280-41e0-11eb-9f6c-16d4c17e8ecf.png)
