### ISSUE TITLE
Outdoor - Site parent

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2410]
- [x] Éviter les boucles

**Comment by camillemonchicourt** [comment]
Première intégration dans la version 2.44.0 et retour de @gutard : 

Quelques exemples concrets de hiérarchie de sites :
* Un secteur de via ferrata : on crée un seul site.
* Plusieurs secteurs d'escalade : on crée un site global, puis des sous-sites correspondant à chacun des secteurs.
* Trois secteurs d'escalade et un secteur de via ferrata, au choix :
    - comme précédemment, on crée un site global, puis des sous-sites correspondant à chacun des secteurs.
    - ou, on créé un site global, puis deux sous-sites (un pour l'escalade et un pour la via ferrata), puis des sous-sous sites pour les secteurs d'escalade.

Contrairement à la 1ère, la 2ème solution permet d'attacher des informations de valorisation ou de gestion communes aux différents secteurs d'escalade.

La subtilité c'est la manière dont on va calculer les valeurs de chacun des champs en agglomérant les informations des descendants (enfants et petits-enfants), ou des ascendants (parent et grand-parent). 

Je propose le mécanisme général suivant :
- on prend la valeur saisie dans le champ
- si c'est vide, on agrège les informations des descendants,
- si c'est toujours vide, on récupère l'information du parent.

Cas particuliers :
- le nom et la publication échappent au mécanisme,
- si un site est multi-pratiques, il n'a pas de cotation, ni de type (car ces éléments sont spécifiques à la pratique),
- on agrège pas les champs textuels (description, recommandations…), on récupère uniquement la valeur du parent.
