### ISSUE TITLE
Install Docker Descktop on Windows 10 - POSTGRES_HOST

### ISSUE THREAD

**Issue by ThomasIdgeo** [GeotrekCE/Geotrek-admin#2424]
Trying to deploy the docker composition from windows10, I was bloqued on the postgres_host configuration.
The docker doesn't find the db server on localhost (alrready install on the system). 
When you modify the .env file, specify the "POSTGRES_HOST=docker-compose up"

Regards

**Comment by camillemonchicourt** [comment]
So you could make it work on Windows 10 ?
I think you are the first to run it on Windows so interested by feedbacks.
