### ISSUE TITLE
2 questions liées à modif de BDD (via COPY)

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2428]
Bonjour,
Ceci n'est pas un bug mais de simples questions techniques.
J'ai intégré des données (liées à la signalétique) dans geotrek-admin avec la commande COPY. Les données contiennent des champs geom, et maintenant j'ai une erreur 500 quand je veux éditer (via GT admin) les objets que j’ai introduit dans la BDD. Le message d’erreur n’est pas clair mais je suppose que c’est parce qu’il n’a pas calculé la segmentation dynamique, car je n’ai pas de bug sur un objet que j’introduis manuellement via GT admin. Dans core_topology, j’ai des triggers de calcul que j’aimerais exécuter. D’après google, je peux le faire en updatant les lignes par elles-mêmes (comme le trigger est activé sur les updates): UPDATE core_topology SET geom = geom;
Mais ça ne change rien. Suis-je obligé d'utiliser `loadsignage ` ?

Question 2: puis-je modifier les longueur des champs dans la BDD geotrek sans que ça risque de poser problème dans le futur lors de mises à jour de GT-admin ?

Merci
Pierre

**Comment by camillemonchicourt** [comment]
Oui les champs geom sont des champs calculés à partir de la segmentation dynamique (https://makina-corpus.com/blog/metier/2014/la-segmentation-dynamique). Il ne faut surtout pas les utiliser pour importer directement la géométrie des objets. Il faut passer par la topologie.

Voir sur le sujet https://github.com/GeotrekCE/Geotrek-admin/issues/952

Par contre, des commandes d'import de POI, de signalétique et autres ont été créés pour faciliter cela.
Voir https://geotrek.readthedocs.io/en/master/import.html#import-from-a-file

**Comment by pierreloicq** [comment]
Merci.
J'essaie d'appliquer la fonction mais ça bugue : 
`sudo geotrek loadsignage --name-field name --type-field type_id --condition-field condition_ --structure-field structure_ --description-field descriptio --year-field impantatio --eid-field eid -v 3 signage_signage.shp`
Ca fait pareil si j'inclus les options --use-structure et --structure-field

> Layer 'signage_signage' with 498 objects found
> An error occured, rolling back operations.
> Traceback (most recent call last):
>   File "/usr/sbin/geotrek", line 20, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/signage/management/commands/loadsignage.py", line 149, in handle
>     if field_structure_type in available_fields else structure
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
>     self.model._meta.object_name
> geotrek.authent.models.DoesNotExist: Structure matching query does not exist.

**Comment by gutard** [comment]
> Structure matching query does not exist.

Toutes les valeurs dans le champ structure_ ou bien la valeur passée à l'option --use-structure sont bien strictement (en respectant la casse…) des noms de structure qui existent déjà dans la base ?

> Ca fait pareil si j'inclus les options --use-structure et --structure-field

En en mettant ni l'un ni l'autre ?

**Comment by pierreloicq** [comment]
> En en mettant ni l'un ni l'autre ?
Ha, ça marche ! Je mettais l'id de la structure plutôt que le nom réel
Merci pour ta rapidité
