### ISSUE TITLE
Position de la direction de la signalétique dans la BDD

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2432]
Il me semble qu'il serait plus judicieux de placer `direction_id `sur `signage_line `plutôt que sur `signage_blade` car il peut y avoir plusieurs directions sur une même lame. C'est le cas au PNV en tout cas. 
https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/data-model/signage.pdf
En attendant, puis-je créer ce champs moi-même sans risque de le perdre durant les mises à jour ? Est-il plus sûr de le nommer `direction_id `ou un nom alternatif ?
Merci

**Comment by camillemonchicourt** [comment]
Ah les lames, les lignes, vaste sujet :-) 

Le module Lames et lignes a été discuté initialement et travaillé dans ce ticket : https://github.com/GeotrekCE/Geotrek-admin/issues/1782
Des reflexions sont en effet en cours pour élargir le fonctionnement et que le module puisse fonctionner pour la signalétique des départements (comme actuellement) mais aussi celles parcs nationaux. Un retour similaire : https://github.com/GeotrekCE/Geotrek-admin/issues/1903

**Comment by pierreloicq** [comment]
Merci pour ta réponse.
Si je rajoute un champ "direction_id_notOfficial" sans aucune contrainte dans signage_line, j'obtiens un GT admin onglet "lames" qui tourne dans le vide, est-ce attendu ?
Merci

**Comment by pierreloicq** [comment]
Peut-être plus lié au fait que j'ai autorisé les valeurs nulles pour signage_blade.direction_id du coup

**Comment by camillemonchicourt** [comment]
Dans la version 2.89.0 de Geotrek-admin, il est possible de configurer si on veut le champs DIRECTION sur les lignes ou sur les LAMES - https://github.com/GeotrekCE/Geotrek-admin/issues/3178
