### ISSUE TITLE
bug lors sync_mobile

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2441]
Hello,

J'ai un bug lors de ma synchro mobile sur GT-admin 2.42 alors que ça marchait bien en 2.39 sur ubuntu 2018.
`sudo /usr/sbin/geotrek sync_mobile -v 3 --url http://adminrando.vanoise.com /home/geotrek/dataMobile`

> ERROR 2020-12-14 12:27:54,333 mapentity.helpers HTTPConnectionPool(host='localhost', port=6543): Max retries exceeded with url: /?url=http%3A//adminrando.vanoise.com/api/fr/treks/2692/profile.svg&from=image/svg%2Bxml&to=image/png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f100e493f40>: Failed to establish a new connection: [Errno 111] Connection refused'))

J'arrive à avoir http%3A//adminrando.vanoise.com/api/fr/treks/2692/profile.svg
J'ai redémarré le serveur, les services convertit et screamshotter , modifié le /etc/hosts, remis le vieux custom.py, ça ne change rien.
Cette requête comportant une conversion ne donne rien non plus http://adminrando.vanoise.com/convert/?url=/document/trek-2667.odt&to=doc

Merci

**Comment by pierreloicq** [comment]
Je vois que sur l'ancien serveur:

tcp        0      0 127.0.0.1:**6543**          0.0.0.0:*               LISTEN      844/python3`

alors que sur le nouveau serveur, personne n'écoute sur 6543 et python/convertit écoute sur 8000 bien que j'aie port = 6543 dans /etc/convertit/convertit.ini
Les  /opt/geotrek-admin/var/conf/env sont similaires à l'IP près.

**Comment by gutard** [comment]
Tu es sûr que ce n'est pas plutôt screamshotter qui est sur le port 8000 ? Tu as regardé les logs de convertit (`sudo journalctl -eu convertit`) ?

**Comment by pierreloicq** [comment]
Convertit : Listening at: http://127.0.0.1:8000 (20822)
Et rien de spécial dans le log.
screamshotter ne démarre pas en fait:

> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: Started Microservice to capture screenshots of web pages.
> Dec 15 18:37:39 geotrekadmin2020 gunicorn[1471]: Traceback (most recent call last):
> Dec 15 18:37:39 geotrekadmin2020 gunicorn[1471]:   File "/opt/screamshotter/bin/gunicorn", line 7, in <module>
> Dec 15 18:37:39 geotrekadmin2020 gunicorn[1471]:     from gunicorn.app.wsgiapp import run
> Dec 15 18:37:39 geotrekadmin2020 gunicorn[1471]: ModuleNotFoundError: No module named 'gunicorn'
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: screamshotter.service: Main process exited, code=exited, status=1/FAILURE
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: screamshotter.service: Failed with result 'exit-code'.
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: screamshotter.service: Scheduled restart job, restart counter is at 5.
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: Stopped Microservice to capture screenshots of web pages.
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: screamshotter.service: Start request repeated too quickly.
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: screamshotter.service: Failed with result 'exit-code'.
> Dec 15 18:37:39 geotrekadmin2020 systemd[1]: Failed to start Microservice to capture screenshots of web pages.

**Comment by gutard** [comment]
> `ModuleNotFoundError: No module named 'gunicorn'`

Personnellement j'appelle ça « quelque chose de spécial » ;)

Tu avais Geotrek-admin 2.39.1 sur Ubuntu 18.04. Peux-tu nous préciser ce que tu as fait ensuite ? Une upgrade d'Ubuntu en 20.04 sur le même serveur ou bien une installation sur un nouveau serveur en Ubuntu 20.04 ?

**Comment by pierreloicq** [comment]
J'ai mis à jour l'ancien serveur vers 2.42 avant de sauver sa BDD, puis une fresh install sur le nouveau ubuntu 2020, avec création de la BDD initiale, que j'ai droppée ensuite pour migrer la BDD et les fichiers custom.py etc

**Comment by gutard** [comment]
OK merci. J'ai reproduit. Je confirme qu'il y a un bug.

**Comment by submarcos** [comment]
il y avait un problème avec les premieres versions de screamshotter / convertit publiées pour ubuntu focal 20.04. C'est désormais résolu dans les dernières versions.

**Comment by Chrispnv** [comment]
Bonjour,
Je reprends ce qu'à fait Pierre sur la partie mobile pour essayer de comprendre avant une potentielle prestation.
J'ai installé screamshotter sur Ubuntu 20.04 et j'ai relancé la commande 
sudo /usr/sbin/geotrek sync_mobile -v 3 --url http://adminrando.vanoise.com /home/geotrek/dataMobile
Mais sans succès, j'ai toujours la même erreur
Merci.

**Comment by camillemonchicourt** [comment]
Hum, il n'y a pas besoin d'installer screamshotter, il est déjà installé avec Geotrek-admin.
Mais par contre, ton Geotrek-admin est bien à jour ?
Comme dit @submarcos, le problème est corrigé dans les dernières versions.
