### ISSUE TITLE
Erreur lors de la génération des pdf

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2442]
Geotrek-admin : 2.43.1

Bonjour, j'ai eu cette erreur lors de la génération des pdf pendant la synchro  (voir fichier).

[error_synchro_pdf.txt](https://github.com/GeotrekCE/Geotrek-admin/files/5695210/error_synchro_pdf.txt)

Du coup aucun pdf ne s'est généré.

**Comment by gutard** [comment]
Suite au passage à Django 3.1 (Geotrek-admin 2.41.0), dans les templates HTML personnalisés (dans `/opt/geotrek-admin/var/conf/extra_templates/`) il faut remplacer `{% load staticfiles %}` par `{% load static %}`.

**Comment by mviadere-openig** [comment]
Ok, j'ai modifié la ligne `{% load i18n mapentity_tags staticfiles %}` par `{% load i18n mapentity_tags static %}` dans `/opt/geotrek-admin/var/conf/extra_templates/trek_public_pdf.html` et j'ai relancé une synchro, cela semble fonctionner, merci.

**Comment by gutard** [comment]
Il faut aussi faire la même chose pour les templates des contenus et des événements touristiques.
