### ISSUE TITLE
Screenshot sur les listes

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2443]
Nous avons un problème avec la capture d'écran sur les listes complétes (itinéraires, tronçons...). Sur les vues "objets", ça fonctionne.

Le message indique :

> Request on http://localhost:8000/?url=https%3A//geotrek.cotesdarmor.fr/trek/list/%3Fcontext%3D%257B%2522mapview%2522%253A%2520%257B%2522lat%2522%253A%252048.53854543392957%252C%2520%2522lng%2522%253A%2520-2.8530120849609375%252C%2520%2522zoom%2522%253A%252012%257D%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Scan%2522%252C%2520%2522%255Cu25a3%255Cu00a0Itin%255Cu00e9raires%2522%255D%252C%2520%2522filter%2522%253A%2520%2522published%253D1%2526difficulty%253D%2526duration%253D%2526practice%253D%2526route%253D%2526structure%253D%2526reservation_system%253D%2526city%253D%2526district%253D%2526physical_type%253D%2526land_type%253D%2526competence%253D%2526signage%253D%2526work%253D%2522%252C%2520%2522sortcolumns%2522%253A%2520%257B%2522path%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522trek%2522%253A%2520%255B%255B1%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522service%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522infrastructure%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522project%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522intervention%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522sensitivearea%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%252C%2520%2522landedge%2522%253A%2520%255B%255B0%252C%2520%2522asc%2522%252C%25200%255D%255D%257D%252C%2520%2522fullurl%2522%253A%2520%2522https%253A//geotrek.cotesdarmor.fr/trek/list/%2522%252C%2520%2522viewport%2522%253A%2520%257B%2522width%2522%253A%25201920%252C%2520%2522height%2522%253A%2520929%257D%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520960%252C%2520%2522height%2522%253A%25200%257D%252C%2520%2522timestamp%2522%253A%25201608032545480%252C%2520%2522print%2522%253A%2520true%257D&width=1920&height=929&selector=%23mainmap returned empty content

Les impressions pdf, odt, doc, fonctionnent correctement.
[screenshot.txt](https://github.com/GeotrekCE/Geotrek-admin/files/5695572/screenshot.txt)

**Comment by gutard** [comment]
Screamshotter (la partie qui gère les extraits de cartes) a toujours été un peu chatouilleux et difficile à déboguer. Ça va être compliqué  ) déboguer sans avoir l'accès au serveur. le fait que ça marche certaines fois et pas d'autre peut s'expliquer par le fait que l'extrait de carte est parfois déjà en cache. Pour commencer, quelle est ta version de Geotrek-admin ?

**Comment by jeromesourdin** [comment]
Version 2.43.1.
Pour la prise de contrôle, ça peux se faire en passant par mon pc...

**Comment by jeromesourdin** [comment]
Je ne pense pas que cela vienne du cache... Si je fais le screenshot depuis l'itinéraire ça marche, mais pas depuis la vue liste tout en étant zoomé sur la même portion de carte avec le même fond de carte.

**Comment by jeromesourdin** [comment]
Autre précision j'ai le problème sur mes deux environnements (test et prod)

**Comment by gutard** [comment]
OK merci. Ça précise les choses. Je reproduis effectivement le problème sur https://demo-admin.geotrek.fr/trek/list/.

**Comment by submarcos** [comment]
Bonjour.
Le bug a été corrigé par la publication d'une mise à jour de screamshotter, l'outil utilisé par geotrek pour réaliser les captures de carte.
Vous pouvez dès à présent mettre à jour ce service de cette façon : 

**installation standard de geotrek (avec paquets debian)**
```
sudo apt update
sudo apt upgrade screamshotter
```
Ces commandes ne mettront à jour que screamshotter, pas votre Geotrek

**installation docker de geotrek**
```
docker pull makinacorpus/screamshotter
docker-compose down
docker-compose start
```

Dans le cas d'une installation standard, screamshotter sera mis à jour automatiquement lors de la prochaine mise à jour de geotrek. Seuls les utilisateurs de l'installation docker seront obligés de mettre à jour manuellement.
