### ISSUE TITLE
Fixer la migration vers la 2.44.0

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2453]
- [x] champs de traductions _xx créés avec NOT NULL et donc impossible à créer
- [x] géométries des sites à transformer en geometrycollection

**Comment by gutard** [comment]
Concernant les traductions, c'est un cas particulier des champs booléens non nuls ajoutés alors qu'il y a déjà des données dans la base. On utilise django_modeltranslation. Celui-ci est prévu pour faire un fallback sur la valeur de la langue par défaut quand la valeur de la langue active est nulle. Actuellement, pour la publication on limite à oui/non sans valeur nulle et sans fallback. Du coup ça ne marche pas bien avec django-modeltranslation. Je ne vois pas comment contourner le problème. 3 solutions :
* Ne rien faire. Ça veut dire que la migration entre 2.42.0 et 2.44.0 plante si on a activé le module outdoor et qu'on a saisi des données entre les deux. Je ne pense pas que ça concerne grand monde.
* Autoriser la valeur nulle pour la publication. Par ex. si on a le français par défaut et qu'on choisi publié=null pour l'anglais, la publication en anglais dépendra de la publication en français.
* Supprimer la fonctionnalité de pouvoir publier par langue.

@camillemonchicourt, tu en penses quoi ?

**Comment by camillemonchicourt** [comment]
OK, cela ne concerne personne, donc je penche pour ne rien faire.
