### ISSUE TITLE
Activation du module diving

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2456]
Bonjour, 

J'ai voulu activer le module diving sur notre serveur de test. J'ai passé les commandes indiquées dans la doc sans soucis. 

![geotrek2020-12-21 10_41_22-mRemoteNG - SQL Server - V011038_TEST_GEOTRECK](https://user-images.githubusercontent.com/33490969/102762862-2a04e600-4379-11eb-8969-9f4202c0e96e.png)

Le menu apparait bien mais quand je clique dessus, j'ai un message d'erreur :

![geotrek-2020-12-21 10_32_31-InvalidCursorName at _dive_list_](https://user-images.githubusercontent.com/33490969/102761982-f1b0d800-4377-11eb-99ee-e5147f229954.png)

Idem dans l'admin quand je clique sur un des trois menus :

![geotrek-2020-12-21 10_34_21-ProgrammingError at _admin_diving_practice_](https://user-images.githubusercontent.com/33490969/102762151-27ee5780-4378-11eb-801a-9ed26cc39380.png)

Aussi, quand j'ai voulu intégrer les fixtures il semble qu'il manque des colonnes dans la bdd :

![geotrek-2020-12-21 10_36_18-mRemoteNG - SQL Server - V011038_TEST_GEOTRECK](https://user-images.githubusercontent.com/33490969/102762339-6f74e380-4378-11eb-88d8-668b819b7553.png)

Nous sommes en Geotrek v2.43.1 sur un Ubuntu 18.04.5 LTS

Merci :-)

**Comment by gutard** [comment]
La doc n'est peut être pas tout à fait complète effectivement. Essaye de faire `sudo geotrek update_translation_fields`. Ça devrait créer les champs xxx_fr, xxx_en, etc. qui manquent.

**Comment by jeromesourdin** [comment]
J'ai un autre message d'erreur :
`Updating data of model '<class 'geotrek.diving.models.Dive'>'
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column diving_dive.disabled_sport_fr does not exist
LINE 1: ...sport_fr" = "diving_dive"."disabled_sport" WHERE ("diving_di...
                                                             ^
HINT:  Perhaps you meant to reference the column "diving_dive.disabled_sport".
`

**Comment by gutard** [comment]
J'ai peut-être répondu trop vite (je suis en congés). Voici la séquence complète de mise à jour de la base :
```
sudo geotrek migrate --noinput
sudo geotrek sync_translation_fields --noinput
sudo geotrek update_translation_fields
sudo geotrek update_geotrek_permissions
geotrek update_post_migration_languages
```

Sinon, tu peux tenter de relancer `sudo dpkg-reconfigure geotrek-admin` qui devrait entre autres faire tout ça.

**Comment by jeromesourdin** [comment]
Super ! Merci bcp !
Bonne vacances :)
