### ISSUE TITLE
cirkwi_id

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2459]
Bonjour,
Je suis en train d'importer le flux de circuits geotrek dans cirkwi mais je finis avec les mauvaises catégories : 
D'après le support cirkwi, cette page est toujours d'actualité : https://ws.cirkwi.com/tuto/categories.php
La pratique VTT possède l’ID 4 dans la colonne « cirkwi_id » de ma BDD geotrek-admin (trekking_practice) et aussi dans la page d’administration django mais elle obtient la classification équestre sur cirkwi (catégorie 5).
La marche et le trail ont cirkwi_id = 2 mais deviennent du vélo (catégorie 3).
Ai-je loupé un truc ou bien il y a un bug ?

Merci

**Comment by camillemonchicourt** [comment]
On a mis en place l'export Cirkwi vers IGN rando dans la version 0.32.0 de Geotrek-admin en 2015, on n'avait que des randonnées pédestres.
Depuis il est possible que des choses aient changé au niveau de Cirkwi et/ou au niveau de la BDD de Geotrek-admin.

Par contre je n'ai pas bien compris où est ton décalage d'identifiants ?

Tu peux vérifier le flux générer sur l'URL [URL_GEOTREK-ADMIN]/api/cirkwi/circuits.xml

**Comment by pierreloicq** [comment]
Merci Camille.
Le décalage est présent dans le flux : http://adminrando.vanoise.com/api/cirkwi/circuits.xml
Il n'y a que des id_locomotion="5" ou "3"

**Comment by gutard** [comment]
> La pratique VTT possède l’ID 4 dans la colonne « cirkwi_id » de ma BDD geotrek-admin (trekking_practice)

Quelle pratique VTT ? Tu en as deux dans ta base : "Rando VTT" et "Rando VTT (électrique)". Sur http://adminrando.vanoise.com/admin/trekking/practice/1/change/ on voit qu'il y a la bonne valeur dans la liste déroulante du champ "Locomotion Cirkwi" pour la pratique "Rando VTT". Mais il n'y a aucune rando publiée avec cette pratique. Et sur http://adminrando.vanoise.com/admin/trekking/practice/5/change/ on voit que c'est la locomotion "Cheval" qui est associée à la pratique "Rando VTT (électrique)" Donc a priori Geotrek fait bien ce que tu lui demandes : il associe le cheval aux randos VTT.

La colonne cirkwi_id de la table trekking_practice fait référence au champ id de la table cirkwi_cirkwilocomotion et c'est le champ eid de cette dernière qui correspond à l'identifiant utilisé par cirkwi. Connaître Django et lire le code python de Geotrek aide à comprendre comment est structurée la base.

**Comment by pierreloicq** [comment]
Dacc, merci. C'est vrai que c'était trop simple comme ça :-)
