### ISSUE TITLE
Projects - 'NoneType' object has no attribute 'paths'

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2460]
Quand j'essaie d'accéder à la fiche détail des chantiers, j'ai une erreur "Server Error (500)".

Je reçois un message d'erreur contenant notamment : 

```
Exception Type: AttributeError at /project/12/
Exception Value: 'NoneType' object has no attribute 'paths'
```

Et :  

```
Template error:
In template /opt/geotrek-admin/lib/python3.6/site-packages/geotrek/core/templates/core/core_detail_fragment.html, error at line 35
   'NoneType' object has no attribute 'paths'
   25 :     &lt;tr&gt;
   26 :         &lt;th&gt;{% trans &quot;Trails&quot; %}&lt;/th&gt;
   27 :         &lt;td&gt;
   28 :             {% if perms.core.add_trail %}
   29 :                 {% is_topology_model model as is_topology_model %}
   30 :                 &lt;p class=&quot;autohide&quot;&gt;&lt;a href=&quot;{% url &#39;core:trail_add&#39; %}{% if is_topology_model %}?topology={{ object.pk}}{% endif %}&quot; class=&quot;btn btn-mini btn-success&quot;&gt;
   31 :                     &lt;i class=&quot;icon-plus icon-white&quot;&gt;&lt;/i&gt; {% trans &quot;Add a new trail&quot; %}&lt;/a&gt;
   32 :                 &lt;/p&gt;
   33 :             {% endif %}
   34 :
   35 :              {% valuelist object.trails field=&#39;name&#39; %}
   36 :         &lt;/td&gt;
   37 :     &lt;/tr&gt;
   38 :   {% endif %}
   39 :
   40 : &lt;/table&gt;
   41 :
```

**Comment by gutard** [comment]
J'étais justement en train de regarder ce problème au moment où tu as ouvert l'issue. Le problème n'est pas sur le chantier mais sur une des interventions qui le compose (id=57). Le souci est que la cible (qui peut être une topologie existante par ailleurs ou bien une topologie propre à cette intervention) est nulle. Ça ne devrait pas pouvoir être le cas.

**Comment by camillemonchicourt** [comment]
OK merci pour les précisions.
Je ne sais pas comment cela est arrivé.
Pour le moment, je ne retrouve pas cette intervention dans l'interface, mais c'est logique si elle n'a pas de topologie.
L'intervention est bien dans la BDD, je vais voir comment la supprimer ou la remettre sur pied.

**Comment by camillemonchicourt** [comment]
Corrigé localement dans notre BDD par @gutard, spécifique et lié à une migration de 2013 : 

La topologie de quelques interventions étaient nulles, ce qui ne devrait pas être possible et ce qui signifie que la géométrie est perdue.
Au PNE, il y avait 81 interventions dans ce cas. Elle sont toutes anciennes (id<=121, date<=2014-01-02).
Pas identifié sur d'autres Geotrek-admin.

Mis en évidence suite à la migration vers la 2.33.0.
A nécessité de récupérer les données dans une sauvegarde de la BDD d'avant la 2.33.0.

Dans celle-ci les topologies qui posent problème ont bien une topologie mais avec ``kind=TOPOLOGY`` au lieu de ``kind=INTERVENTION``.

Après une petite recherche il s'avère que ça provient d'un bug corrigé en 2013. Le commit en question :
https://github.com/GeotrekCE/Geotrek-admin/commit/afbf0c07be546631b2fb13e7d291213a82a332a5
Il aurait fallu également faire la correction dans la base pour les interventions déjà saisies mais ça n'a visiblement pas été fait.
