### ISSUE TITLE
"La géométrie en superpose une autre"

### ISSUE THREAD

**Issue by pierreloicq** [GeotrekCE/Geotrek-admin#2465]
Bonjour,
J'ai ce message d'erreur quand j'essaie d'ajouter un tracé manuel à 2-3 points sur GT-admin 2.42.0 installé sur ubuntu 2020. 
As-tu le même problème Camille ?
Merci

**Comment by camillemonchicourt** [comment]
Je ne comprends pas à quel moment, dans quel contexte, quel module ?
Tu peux tester sur notre serveur de test/demo : http://geotrekdemo.ecrins-parcnational.fr/ (admin / admin) qui est en version 2.44.0.

**Comment by camillemonchicourt** [comment]
Oui vérifie que tu as pas un tronçon existant dans la BDD, mais supprimé donc toujours présent dans la BDD mais non affiché sur l'interface (DELETED = true)

**Comment by gutard** [comment]
Bien vu, j'avais pas pensé aux tronçons supprimés. Pour le coup ça vaudrait peut-être le coup de modifier le code pour le pas prendre en compte les tronçons supprimés dans cette vérification.

**Comment by pierreloicq** [comment]
Merc. Chez Camille ça marche bien.
Chez moi pas, malgré la mise à jour vers 2.44.0
J'ai bien des tronçons en deleted=true mais le message s'affiche quelle que soit la localisation du nouveau tronçon.

**Comment by gutard** [comment]
OK j'ai reproduit. Ça ne le fait que pour les version >= 2.41.0, avec le paquet Ubuntu 20.04 (pas avec le paquet Ubuntu 18.04, ni avec docker). C'est lié au passage à PostGIS 3. Avec Postgis 2, dans la fonction SQL check_path_not_overlap(), ST_Intersects() renvoyait GEOMETRYCOLLECTION(EMPTY). Avec Postgis 3, il renvoie LINESTRING(EMPTY).

**Comment by pierreloicq** [comment]
Super merci

**Comment by gutard** [comment]
C'est fixé dans la version https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.45.0
