### ISSUE TITLE
API V2 - Add duration_pretty

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2483]
Les durées des randonnées sont saisies et stockées en numérique, en heure et doivent ensuite être décodées pour être affichées de manière plus compréhensible. 
De plus pour les itinéraires sur plusieurs jours, on considère 24 = 1 jour. 

Voir les exemples d'aide à la saisie : En heures (1.5 = 1 h 30, 24 = 1 jour, 48 = 2 jours)

Actuellement l'API ne fournit que la valeur numérique brute de la durée au format numérique. Celle-ci est nécessaire pour ordonner et filtrer les randonnées. 
Mais pour l'affichage des infos d'une rando, il faut les décoder. 

On pourrait laisser Geotrek-rando s'en charger, mais cette info décodée pourrait avoir d'autres usages se basant sur l'API.

Il serait donc utile d'ajouter le champs ``duration_pretty`` dans la route ``/trek`` de l'API.

**Comment by gutard** [comment]
Pour moi ce n'est pas une bonne chose car :
- chacun son job : fournir les données brutes (à un autre logiciel) pour l'admin et faire la présentation de ces données (à un humain) pour rando,
- l'idée était de rendre l'API plus performante et plus légère.

C'était donc volontaire de ne pas avoir repris ce point de la v1. Ce n'était pas un oubli.

**Comment by camillemonchicourt** [comment]
OK, en effet au départ je pensais effectivement le gérer au niveau de Geotrek-rando, mais en réflechissant à d'autres usages de l'API, j'ai imaginé que certains risquaient de faire n'importe quoi en récupérer une durée de 48h.
Mais à discuter en effet pour les raisons que tu évoques.

**Comment by gutard** [comment]
> j'ai imaginé que certains risquaient de faire n'importe quoi en récupérer une durée de 48h

Ça c'est un autre problème. Il s'agit de la modélisation de l'information et on peut effectivement l'améliorer. On peut par exemple imaginer ajouter un champ qui précise l'unité utilisée dans le champ durée (jour ou heure). Ou alors prévoir deux champs : l'un pour le nombre d'heures de marche et l'autre pour le nombre d'étapes prévues.

**Comment by camillemonchicourt** [comment]
OK pour le moment on garde seulement la donnée brute dans l'API, à chacun de l'interpréter correctement.
