### ISSUE TITLE
Erreur synchro pdf 

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2490]
Version GTK-admin : 2.45.0

Bonjour, je suis en train de finaliser la maj d'un Geotrek qui était d'une version <= à la 2.32. 
Lorsque je lance la synchro des rando vers le nouveau dossier de synchro j'ai cette erreur qui revient assez souvent : 

`fr api/fr/treks/10130/le-belvedere-daoumede-et-la-ferme-basque.pdf failed (Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.)`
`fr api/fr/treks/10130/profile.json ...generated`
`fr api/fr/treks/10130/profile.png failed (Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.)`

Pourtant les pdf se génèrent bien sur Geotrek-admin. 

Est-ce que ça a un lien avec https://github.com/GeotrekCE/Geotrek-admin/issues/2358 ?

**Comment by gutard** [comment]
Quand tu lances la commande `sync_rando` tu précise bien l'URL publique avec l'option `--url` ?

**Comment by mviadere-openig** [comment]
Un oubli de ma part, c'était bien ça, merci.
