### ISSUE TITLE
Erreur WeasyPrint pendant la synchro

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2492]
Gtk-admin version 2.45.0

Bonjour, lors de la synchro du Geotrek-admin j'ai ce message qui s'affiche. J'ai fouillé les issues concernant les problèmes de génération de pdf, mais aucunes de parlaient de ce message :

`fr api/fr/touristiccontents/47168/gite-namaste.pdf ...WARNING 2021-01-19 13:41:38,233 weasyprint Deprecated `-weasy-hyphens: manual` at 14:3, prefixes on unstable attributes are deprecated, use `hyphens` instead.
WARNING 2021-01-19 13:41:38,233 weasyprint Deprecated `-weasy-bookmark-level: none` at 19:3, prefixes on unstable attributes are deprecated, use `bookmark-level` instead.
WARNING 2021-01-19 13:41:38,252 weasyprint Ignored `caret-color: rgb(51, 51, 51)` at 1:1, unknown property.
ERROR 2021-01-19 13:41:38,894 weasyprint Failed to load image at "https://siglr-geotrek-pnrgca.ataraxie.fr/media/paperclip/tourism_touristiccontent/47168/f1000018.jpg.1000x500_q85_crop-smart.jpg" (HTTPError: HTTP Error 404: Not Found)
ERROR 2021-01-19 13:41:41,130 weasyprint Failed to load image at "https://siglr-geotrek-pnrgca.ataraxie.fr/" (Pixbuf error: Unrecognized image file format)
generated`

**Comment by gutard** [comment]
Deprecated -weasy-hyphens et Deprecated-weasy-bookmark-level c'est parce qu'il  faut reprendre les templates PDF customisés. La modif dans les templates de base a été faite dans ce commit https://github.com/GeotrekCE/Geotrek-admin/commit/1598fd0f332dd165959f67a10a1502bb7fce156f mais les templates cutom sont à mettre à jour manuellement. De toute façon ce ne sont que des warnings, pas des erreurs.

caret-color je ne sais pas ce que c'est. Là encore c'est peut être dans la custo spécifique au PNRGC.

Et pour le "Failed to load image" c'est parce qu'il y a une image corrompue sur le contenu touristique #47168. Là encore c'est pas un bug de Geotrek mais c'est le SIT qui fournit cette image corrompue.

**Comment by mviadere-openig** [comment]
Oui C'était surtout le message  `Pixbuf error: Unrecognized image file format`, je me demandais s'il n'y avait pas un souci avec WeasyPrint. Merci pour tes informations, je clos l'issue.

**Comment by gutard** [comment]
Tu as peut-être raison. Quand je réponds sur github je ne peux pas me permettre d'y passer du temps donc je lance des hypothèses. Est-ce que tu as ça sur un seul PDF ou sur tous ?

**Comment by mviadere-openig** [comment]
Je ne sais pas si c'est sur tous, je te link le fichier de log de la synchro.  Mais je dirais que c'est sur presque tous.
[synch_rando.log](https://github.com/GeotrekCE/Geotrek-admin/files/5836907/synch_rando.log)

**Comment by submarcos** [comment]
D'apres le log, les pixbuf error ne se produisent que quand weasyprint essaie d'evaluer une image et que celle ci n'est pas accessible (erreur 404 précédent tous les pixbuf error). Je présumerai plutot que ces images sont référencées en base de données mais qu'elles ne sont plus présentes dans le dossier media
