### ISSUE TITLE
Parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2496]
Champs partagés avec les sites :
* id (auto)
* géométrie (type ?)
* nom
* description
* recommandation
* cotation ?
* labels ?
* brouillon/publié ?
* site (quel rattachement ? manuel ? buffer ? départ/arrivée ou site complet)

Champs spécifiques :
* durée
* dénivelé (auto ?)
* longueur (auto ?)
* profondeur (auto ?)
* matériel (type ?)
* équipement (type ?)
* retour (type)

**Comment by camillemonchicourt** [comment]
OK.
- Le site est rattaché manuellement, même si les sites à proximité sont aussi listés dans une autre partie de la fiche détail d'un parcours
- La cotation est disponible en saisie, uniquement dans un second temps, après avoir associé le parcours à un site qui a une pratique pour laquelle des cotations sont définis. Il faut associer le parcours à un site qui a une pratique, l'enregistrer puis modifier le parcours pour avoir accès à la saisie de la cotation (étant donné que celle-ci dépend de la pratique)
- Tous les champs spécifiques listés ici n'ont pas été implémentés (comme durée, profondeur, matériel, équipement)
- Les champs "longueur" et "pente" sont calculés automatiquement, seulement si le parcours est de type ligne
