### ISSUE TITLE
Proposer la couche des sites

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2501]
- Lors de l'ajout d'un nouveau site (avec snapping ?)
- Lors de l'ajout d'un nouveau parcours
- Sur la liste des autres modules
- Idem pour la couche des parcours

**Comment by camillemonchicourt** [comment]
Fait dans le formulaire d'ajout de site et de parcours, sans snapping.

![Capture d’écran de 2021-05-03 12-26-26](https://user-images.githubusercontent.com/4418840/116866060-0ac17380-ac0b-11eb-8046-8d195eaa7b63.png)
