### ISSUE TITLE
Afficher publié/nom/pratique/niveau/date modif dans la liste

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2502]
Il est prévu que cela devienne configurable à terme.

**Comment by camillemonchicourt** [comment]
A voir si cela rentre en largeur, même sur un PC portable.
Je crois qu'on avait pas prévu de mettre "niveau" dans la liste des sites Outdoor.

**Comment by gutard** [comment]
> Je crois qu'on avait pas prévu de mettre "niveau" dans la liste des sites Outdoor.

Par niveau je veux dire juste un chiffre 1 pour le site, 2 pour le sous site, 3 pour le secteur…

**Comment by camillemonchicourt** [comment]
Ah OK, bien vu.
