### ISSUE TITLE
API V2 - Treks et fichiers liés

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2512]
Dans la route des treks, on a l'URL des fichiers GPX et KML mais pas celle des PDF de la rando.
A priori je pense qu'il faut l'ajouter.
Avec les 2 URL (PDF de base, ou PDF livret)

**Comment by camillemonchicourt** [comment]
Idem pour les contenus touristiques et à terme les autres objets contenant des PDF (evenements touristiques, sites outdoor...)

**Comment by camillemonchicourt** [comment]
La propriété "pdf" a été ajoutée dans l'API de la version 2.47.0. 
Mais son chemin est relatif, alors que pour les autres fichiers (gpx, kml, images...), les URL sont en absolu.
En absolu serait mieux pour homogénéiser et c'est plus simple à utiliser.

**Comment by gutard** [comment]
> Avec les 2 URL (PDF de base, ou PDF livret)

C'est la même URL mais ça dépend du setting USE_BOOKLET_PDF.
