### ISSUE TITLE
API V2 - Typologies selon le contenu et par portail

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2514]
Actuellement les routes des typologies utilisées notamment pour les filtres (/accessibility, /difficulty, /network, /theme, /treklabel) renvoient toutes les valeurs présentes dans la BDD.

Néanmoins certaines typologies peuvent ne pas avoir de contenu associé, ou pas encore publié, et renvoient donc des valeurs de filtres sans contenu correspondant.

Même si quand on publie sur seulement un Geotrek-rando, les typologies sont censées être les mêmes ou quasiment que celles utilisées par les contenus publiés, on pourrait imaginer filtrer les valeurs en fonction des contenus, pour ne remonter une typologie seulement si au moins un contenu publié l'utilise.

Cela devient bien plus fréquent et problématique quand les contenus sont publiés sur différentes portails Geotrek-rando. 
Dans ce cas, on aura la plupart du temps des pratiques, des thèmes etc.. qui seront utilisés par un portail mais pas un autre (voir https://github.com/GeotrekCE/Geotrek-rando-v3/issues/60).

Dans ce cas, il semble important de pouvoir filtrer les routes des typologies en pouvant leur passer un paramètre de portail, et en ne renvoyant alors que les valeurs pour lesquels on a au moins un contenu publié destiné au portail indiqué.

Idem pour /touristiccontentcategory en cours d'ajout.

Faire pareil pour les routes /city, /district, /structure... ?

**Comment by camillemonchicourt** [comment]
A réaliser pour les typologies liées aux treks, et aux contenus touristiques en ajoutant la possibilité de les filtrer par portail.
Si je ne renseigne pas de filtre par portail quand j'appelle ces listes, alors je les limite quand même par rapport aux contenus publiés.

On ne le fait pas pour les listes de communes et de secteurs car ça serait lourd et ces éléments sont publiables ou non.

A faire aussi sur les typologies liées aux evenements touristiques quand leurs routes seront ajoutées.

Idem pour les typologies liées aux sites et parcours outdoor à terme, mais moins urgent.

**Comment by gutard** [comment]
https://github.com/GeotrekCE/Geotrek-admin/pull/2608

**Comment by camillemonchicourt** [comment]
Fait dans la 2.53.0.
Mais la comparaison avec le contenu ne se fait que si on passe un paramètre de portail sur la route d'une typologie.
Actuellement si on ne passe pas de filtre par portail, cela renvoie toutes les valeurs, mêmes celles qui n'ont pas de contenus associés.

A noter aussi, d'après mes tests sur la route des accessibilités (https://geotrekdemo.ecrins-parcnational.fr/api/v2/trek_accessibility/?portals=1), cela renvoie aussi les valeurs des typologies pour lesquels il y a des contenus non publiés. Cela ne devrait comparer qu'avec les données publiées je pense ?

**Comment by gutard** [comment]
> Cela ne devrait comparer qu'avec les données publiées je pense ?
OK. J'ai mis un peu de temps à comprendre. Et en plus il faudrait tenir compte de la la langue car la publication en dépend.

**Comment by camillemonchicourt** [comment]
Les points listés ont été corrigés dans la 2.53.1, merci.
Un dernier point identifié sur le sujet : 
La liste des thèmes ne semble regarder que par rapport aux thèmes associés à des treks publiés, il faudrait aussi comparer avec les thèmes associés à des contenus touristiques publiés.
C'est la somme des thèmes associés à des treks et des touristiccontents qu'il faut renvoyer.

**Comment by camillemonchicourt** [comment]
Alors je suis passé en 2.55.1 sur le serveur de DEMO.
Sur cette instance, je n'ai aucun itinéraire associé au thème "Lac et glacier", mais j'ai 2 contenus touristiques qui sont associés à ce thème. Jusqu'à présent il ne remontait pas dans la route des thèmes.
Un des CT associé à ce thème n'est associé à aucun portail, le second est associé au portail 2

- Maintenant quand j'appelle la route sans filtre de portail, ce thème remonte bien : https://geotrekdemo.ecrins-parcnational.fr/api/v2/theme/
- Le thème "Lac et glacier" remonte bien que je filtre sur le portail 2 : https://geotrekdemo.ecrins-parcnational.fr/api/v2/theme/?portals=2
- Mais il remonte aussi quand je filtre sur la portail 1, alors qu'aucun CT avec ce thème n'est associé au portail 1 : https://geotrekdemo.ecrins-parcnational.fr/api/v2/theme/?portals=1

Un peu complexe mon affaire, j'espère avoir bien regardé, mais il me semble qu'il reste un soucis sur les filtres des thèmes par rapport au filtre par portail et les contenus touristiques ?

**Comment by gutard** [comment]
Je crois que ça a un lien avec les objets supprimés mais quand même conservés dans la base.

**Comment by camillemonchicourt** [comment]
Ah bien vu !

**Comment by babastienne** [comment]
@camillemonchicourt issue toujours valable ?

**Comment by camillemonchicourt** [comment]
Oui le dernier problème identifié est toujours présent.
A priori car quand on liste les valeurs d'un filtre en fonction du contenu, il prend aussi les contenus supprimés. 
Il ne faudrait pas prendre en compte les randos et les contenus touristiques dont le champs "supprime=true" quand on construit la liste des valeurs d'un filtre.

**Comment by babastienne** [comment]
@camillemonchicourt en effectuant des tests j'ai réalisé un problème.
Il semblerait que si on filtre une typologie par portail, on ne tienne pas compte du statut (publie / non publié) des éléments associés.

Par exemple :
- J'ai 2 itinéraires associés à un portail test (identifiant du portail =2). 
- Ces deux itinéraires possèdes des labels mais ne sont pas publiés.
- Si je vais sur `http://localhost:8000/api/v2/label/?portal=2` alors les labels des itinéraires sont visibles.

On est bien d'accord qu'en théorie l'api ne devrait renvoyer aucun label puisque les deux itinéraires associés ne sont pas publiés ?

**Comment by camillemonchicourt** [comment]
Oui OK, donc cela doit être le soucis.
En effet, les listes des valeurs renvoyées (en filtrant par portail ou non) ne doivent s'appuyer que sur les objets (randos ou contenus touristiques) publiés.

**Comment by babastienne** [comment]
Ok, c'est bien ce qu'il me semblait. 
En fait les deux problèmes étaient présents : les contenus non publiés ET les contenus supprimés étaient pris en compte dans le filtre portail.

Les deux problème sont corrigés dans https://github.com/GeotrekCE/Geotrek-admin/pull/2680/

**Comment by camillemonchicourt** [comment]
OK mais contrairement à ce que dit le changelog, c'est pas uniquement quand on filtre par portail qu'il faut faire ça.
Même quand on ne filtre pas par portail, il faut que les listes de valeur soient conditionnées par les contenus publiés et non supprimés.

**Comment by babastienne** [comment]
Oui bien vu. En pratique c'est bien ce qui se passe, les valeurs sont conditionnées de cette manière même quand on ne filtre pas par portail. C'est une erreur dans le changelog. Je viens de corriger.

**Comment by camillemonchicourt** [comment]
Fixé dans la 2.60.0
