### ISSUE TITLE
Question SEO Geotrek-Admin avec Rando multi portail

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2519]
Geotrek-admin : 2.45.0

Bonjour,

j'ai un Geotrek-admin qui sert deux portail rando, le Parc des Grands Causses(1) et le Parc de L'Aubrac (2). Les deux portails sont paramétrés dans l'onglet admin > Accueil > Commune > Portails cibles.

Voici ce qui se passe lorsque l'on fait une recherche de ces sites sur un navigateur : 

1. Sur le portail Rando du **Parc des Grands Causses** : 

Google : Le site apparaît avec la bonne meta-description 

Qwant, DuckDuckGo : le site apparaît mais pas avec la bonne meta-description :

<img width="618" alt="image" src="https://user-images.githubusercontent.com/45095227/106010448-bf527300-60b9-11eb-80da-b3299d7329bb.png">

2. Sur le portail Rando du **Parc de l'aubrac**

Google : le site n'apparaît pas dans les résultats de recherches

Qwant, DuckDuckGo : il apparaît mais sans la bonne meta description.

La meta description dans le fichier /opt/geotrek-admin/var/conf/extra_locale/fr/LC_MESSAGES/django.po est paramétré pour celle du portail des Grands Causses : 

```
msgid "Geotrek is a web app allowing you to prepare your next trekking trip !"
msgstr "Découvrez les paysages exceptionnels du Larzac à Roquefort"
```
En vue de ce post: https://github.com/GeotrekCE/Geotrek-admin/issues/2003 et de ce post : https://github.com/GeotrekCE/Geotrek-rando/issues/806

Est-ce que pour gérer le référencement multi portail il faut toujours passer par le "bricolage" proposé par @camillemonchicourt  en #2003 ? Est-ce que l'option graphique suffit a elle même ou faut-il toujours passer par le fichier django.po ?

**Comment by camillemonchicourt** [comment]
Non justement la fin du ticket 2003 indique que ce n'est plus le cas grâce à l'ajout de champs dédiés aux métas dans la table des portails.

**Comment by gutard** [comment]
Tu peux essayer de rajouter DuckDuckGo et Qwantify dans la liste des chaînes qui identifient les crawlers dans la conf nginx pour corriger la description.

Concernant l'indexation de https://www.rando-aubrac.fr, apparaît-il en lien dans un autre site bien référencé ? Google ne peut pas deviner l'existence d'un site et estimer sa réputation sans trouver des liens vers ce site. Si tu veux des retours de la part de Google, tu peux utiliser https://search.google.com/search-console/about

**Comment by mviadere-openig** [comment]
Merci Camille et Gaël pour ces infos. 

Si j'ai bien compris maintenant il suffit d'enregistrer le paramétrage dans l'admin pour que ça fonctionne. 

Je vais mettre à jour Geotrek-rando avec les updates que tu as faite et vais me renseigner sur la solution de Google, je te tiens au courant.
