### ISSUE TITLE
API V2 - Filtrer sur plusieurs structures

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2522]
Actuellement on ne renseigne qu'une seule structure à chaque objet (rando, contenu touristiques...).
Du coup dans les filtres de l'API V2, on ne peut filtrer la liste des randos en passant qu'un seul ID de structure.
Mais le filtre devrait être indépendant de la typologique Simple ou Multiple d'un champs.

Donc il faudrait plutôt basculer le filtre des routes /trek, /touristiccontent (et autres ?) en permettant de passer une liste de structures.
Idem sur d'autres filtres ?

**Comment by gutard** [comment]
> Idem sur d'autres filtres ?

Je vois aussi type (POI) et route (Trek). Autre « souci » mineur : il y a un mélange de singulier et de pluriel dans les noms des filtres.

**Comment by camillemonchicourt** [comment]
OK pour les autres filtres et l'harmonisation de leur nommage.
