### ISSUE TITLE
Données itinéraires et POI ne remontent pas

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#2533]
Bonjour,

Après avoir fait un dump de notre machine de prod pour réinstaller sur la machine test. 
Tout remonte sauf les itinéraires (ça mouline avec le cadre rouge autour de la carte) et la table POI génère une erreur 500.
Les 2 VM ont la même version de PGSQL (PGSQL 10) et de GA (2.34 ou peut-être 2.33)
Les 2 VM ont été installées le même jour avec l'aide du support Makina.
Il y a visiblement des erreurs dans le fichier de logs de PostgreSQL (fichier joint).
Savez-vous d'où peut venir le problème ?
Merci d'avance pour vos retours.
Bonne fin de journée.

[postgresql-10-main.log](https://github.com/GeotrekCE/Geotrek-admin/files/5933037/postgresql-10-main.log)

**Comment by camillemonchicourt** [comment]
Je maîtrise pas bien le sujet, mais je vois qu'il y a une erreur claire sur un champs ``column trekking_trek.is_park_centered does not exist``.
Dans la version 2.38, ce champs a été remplacé par une table plus générique (https://github.com/GeotrekCE/Geotrek-admin/issues/2362), mais à priori vous êtes sur une version bien antérieure...
Il y a eu des erreurs lors de la restauration du DUMP de la BDD sur la machine de test ?

Et que disent les logs de l'application quand vous accédez au module Itinéraires, ou au module POI ?
Pour les logs, voir https://geotrek.readthedocs.io/en/master/installation.html#troubleshooting

**Comment by AudreyRemy** [comment]
Merci Camille pour ton retour.
Ci-joint les retours des différentes commandes citées 
[logs_geotrek.docx](https://github.com/GeotrekCE/Geotrek-admin/files/5933557/logs_geotrek.docx)

**Comment by gutard** [comment]
Vous pouvez tenter de faire :
```
sudo geotrek migrate --noinput
sudo geotrek sync_translation_fields --noinput
sudo geotrek update_translation_fields
```

* Avez-vous fait un transfert complet (structure + données) ou uniquement des données ?
* Est-ce que la variable LANGUAGES a la même valeur sur les deux VM dans le fichier /opt/geotrek-admin/var/conf/env ?

**Comment by AudreyRemy** [comment]
Bonjour 
Merci pour votre retour.
Les 2 fichiers sont identiques hormis le SERVEUR NAME adapté au nom de domaine que chaque VM.
Un dump avec pg_dump a été fait sur la vm de prod (sudo -u postgres pg_dump -Fc geotrekdb > /tmp/database.backup).
La base de la VM de test a été supprimée (sudo -u postgres psql -c "DROP DATABASE geotrekdb;" ), recréée (sudo -u postgres psql -c "CREATE DATABASE geotrekdb OWNER geotrek ENCODING 'UTF8' TEMPLATE template0;" ; sudo -u postgres psql -d geotrekdb -c "CREATE EXTENSION postgis;" )
et rempli avec pg_restore (sudo -u postgres pg_restore -d geotrekdb /tmp/database.backup )
On lancera les commandes lundi.
Bon week-end

**Comment by gutard** [comment]
Pouvez vous également lancer `dpkg -l | grep geotrek` sur chacun des serveurs pour vérifier les versions ? Une mise jour d'Ubuntu met également à jour Geotrek. Il donc est possible que vous ayez fait une mise à jour de Geotrek sans vous en rendre compte. Pour faire en sorte que Geotrek ne soit mis à jour que si vous le demandez explicitement, faites `sudo apt-mark hold geotrek-admin` comme l'indique la [documentation](https://geotrek.readthedocs.io/en/master/installation.html#from-geotrek-admin-2-33).

**Comment by AudreyRemy** [comment]
Bonjour,
Merci pour tous ces conseils.
Effectivement il y a eu des mises à jour tant niveau système que version de GA !
La question est maintenant, en faisant (et comment) la mise à jour pour passer la test en 2.39.1 est-ce que cela suffira à résoudre les problèmes de restauration de dump ?
Bonne journée.

![2021-02-08_105143](https://user-images.githubusercontent.com/78603108/107203427-b9368d80-69fb-11eb-99ba-258a223f9f81.png)

**Comment by camillemonchicourt** [comment]
Il faut appliquer les migrations automatiques de la BDD comme indiqué par @gutard plus haut ``sudo geotrek migrate.......``

**Comment by gutard** [comment]
> Il faut appliquer les migrations automatiques de la BDD comme indiqué par @gutard plus haut sudo geotrek migrate.......

???

le VM de test est en retard par rapport au dump. Il n'y a donc cuaune migration à passer. Ou alors à l'envers ;)

**Comment by gutard** [comment]
Donc il faut commencer par mettre à jour la VM. En 2.39.1 ce n'est pas évident car cette version n'est plus disponible dans le dépôt de paquets. On a gardé le paquet en archive mais il n'est pas disponible publiquement. Sinon il faut faire la mise à jour à la dernière version  et ensuite seulement passer les migrations.

**Comment by gutard** [comment]
> ce n'est pas évident car cette version n'est plus disponible dans le dépôt de paquets

Je viens de rendre disponibles les anciennes versions sur https://packages.geotrek.fr/attic/. Pour en installer une il suffit de la télécharger et de l'installer avec `sudo dpkg -i geotrek-admin_x.y.z.ubuntu18.04_amd64.deb`.

ATTENTION! Cette manipulation est réservée aux experts. Le retour en arrière a peu de chances de fonctionner.

**Comment by camillemonchicourt** [comment]
C'est vrai que je ne vois pas trop l'intérêt de faire tout ça et galérer avec des anciennes versions, des versions différentes, etc...
Il faudrait mieux être à jour et ensuite faire l'environnement de test etc... 
Mais peut-être que quelque chose m'a échappé.

**Comment by AudreyRemy** [comment]
Bonjour
la VM de test Geotrek Admin a pu être mise à jour dans la même version que la VM de production.
Le dump de la base de prod a également pu être restauré sur la VM de test.
Merci à vous deux.
Bonne journée.
