### ISSUE TITLE
Parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2546]
Créer au moins le noyau du modèle parcours afin d'étudier l'articulation avec les sites.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.51.0 puis complété dans les versions suivantes.

![Capture d’écran de 2021-05-03 12-21-13](https://user-images.githubusercontent.com/4418840/116865582-2f691b80-ac0a-11eb-986a-56d8f17e63b3.png)

![Capture d’écran de 2021-05-03 12-21-48](https://user-images.githubusercontent.com/4418840/116865589-33953900-ac0a-11eb-80be-991b541de76c.png)
