### ISSUE TITLE
Afficher l'arborescence site/parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2547]
L'idée est d'avoir deux icônes et deux vues liste site et parcours dans le module outdoor afin de ne pas trop casser l'architecture prévue par mapentity. Mais afin de pouvoir naviguer facilement dans les sites des les parcours il est prévu d'afficher en tête de chacune des vues liste (et pourquoi pas détail également) une représentation de l'arborescence permettant :
* de savoir exactement où on se situe
* de naviguer vers les parents ou enfants
* d'insérer directement un site ou un parcours au bon endroit.

**Comment by camillemonchicourt** [comment]
Quand on est sur un site, on voit ses sites parents et/ou enfants, ainsi que ses parcours.
Sur un parcours, on voit son site.

![Capture d’écran de 2021-05-03 12-23-14](https://user-images.githubusercontent.com/4418840/116865708-70f9c680-ac0a-11eb-8ab8-b3e2d212ac40.png)
