### ISSUE TITLE
API V2 - PDF multilangue

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2552]
Je viens de me rendre compte que quand on interroge l'API par langue, ici en anglais, les PDF sont quand même renvoyés en anglais : https://geotrekdemo.ecrins-parcnational.fr/api/v2/touristiccontent/?language=en&omit=attachments%2C%20geometry

Ici : https://geotrekdemo.ecrins-parcnational.fr/api/fr/touristiccontents/257/auberge-gaillard_booklet.pdf

Alors qu'il devrait renvoyer https://geotrekdemo.ecrins-parcnational.fr/api/en/touristiccontents/257/auberge-gaillard_booklet.pdf

Certainement idem sur les PDF des randos.

**Comment by gutard** [comment]
C'est corrigé dans la release 2.50.0. Le principe est le même qu'avec les textes traduits (dictionnaire lorsque la langue n'est pas précisée).

**Comment by camillemonchicourt** [comment]
Merci
