### ISSUE TITLE
Prise en compte MAPENTITY_CONFIG['MAP_STYLES']

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2554]
En 2.49.0, j'ai modifier mon custom.py avec les nouveaux paramétrages pour MAPENTITY_CONFIG['MAP_STYLES'].
Par contre quand je lance sudo systemctl restart geotrek (comme indiqué dans la doc) ou sudo dpkg-reconfigure geotrek-admin
, mes confs ne sont pas prises en compte, je garde mon ancien paramétrage. Il faut lancer une autre commande ?

Voici mes nouvelles confs : 
MAPENTITY_CONFIG['MAP_STYLES']['path'] = {'color': 'yellow', 'weight': 4}
MAPENTITY_CONFIG['MAP_STYLES']['trek'] = {'color': 'red', 'weight': 4}
MAPENTITY_CONFIG['MAP_STYLES']['restrictedarea']['opacity'] = 0.5

Mais ça me garde mon ancienne conf à savoir une opacité sur 'path'

Merci,
Thomas

**Comment by gutard** [comment]
Peut-être un simple problème de cache ?

**Comment by thomaspnrhj** [comment]
Non j'ai vidé et tester sur plusieurs navigateurs

**Comment by submarcos** [comment]
Juste pour savoir, on a gardé une compat avec l'ancien MAP_STYLES. as-tu enlevé ce settings ? si il existe toujours, il prendra le pas sur MAPENTITY_CONFIG['MAP_STYLES']

**Comment by thomaspnrhj** [comment]
oui oui j'ai enlevé !

**Comment by submarcos** [comment]
Par contre dans ton réglage 'path' je ne vois pas de changement d'opacité

**Comment by thomaspnrhj** [comment]
Oui je l'ai enlevé pour voir si il y avait un changement avec ma conf initial, mais rien ne change. J'ai également essayer de modifier la couleur mais ça change rien. Effectivement on dirait qu'il garde les valeurs par défaut et pas ce qui est surcouché. 

Par contre si je laisse l'ancien MAP_STYLES, ça me fait tout planté !

**Comment by submarcos** [comment]
tu peux nous communiquer ton MAP_STYLES original que je fasse des tests ? c'est étrange on utilise ce nouveau réglage dans georiviere sans problème. il y a peut être un cas spécial qu'on avait pas anticipé

**Comment by thomaspnrhj** [comment]
Alors j'avais : 
MAP_STYLES['path'] = {'color': 'yellow', 'weight': 4}
MAP_STYLES['restrictedarea'] = {'opacity' : 0.5}
MAP_STYLES['filelayer'] = {'color': 'yellow', 'opacity': 1.0, 'fillOpacity': 0.9, 'weight': 4, 'radius': 5}

**Comment by submarcos** [comment]
ok. je suis en train de regarder. Ce que je peux déjà dire :

- j'ai oublié le cas ou on manipule MAP_STYLES['xxx']. la variable n'existant plus dans les settings de base, çà explique pourquoi çà casse tout si on la laisse dans le fichier custom.py. çà marche bien si on la définit entièrement : MAP_STYLE = {xxx}. je vais faire un fix pour ce cas de figure.

- il y a bien un cache. Quand je modifie des valeurs de MAPENTITY_CONFIG['MAP_STYLES'] dans custom.py, il faut que je relance l'instance pour que çà arrive jusqu'au navigateur, et que je vide le navbi

Si je deroule ces étapes, la configuration arrive bien jusqu'à leaflet. En vidant le cache les nouvelles valeurs sont bien interprétées et affichées.

**Comment by submarcos** [comment]
captures pour illustrer : 

- depuis la vue liste des tronçons

![vue_liste](https://user-images.githubusercontent.com/7448208/108532094-c004b080-72d7-11eb-92c7-0a4793d7a438.png)

- depuis la vue detail d'un tronçon

![vue_detail](https://user-images.githubusercontent.com/7448208/108532105-c3983780-72d7-11eb-97cf-640d1d1b7029.png)

-  depuis la couche itinéraire

![affichage_troncons_depuis_itineraires](https://user-images.githubusercontent.com/7448208/108532116-c5fa9180-72d7-11eb-9cbc-034936acada4.png)

**Comment by submarcos** [comment]
avec le rélgage :

```python
MAPENTITY_CONFIG['MAP_STYLES']['path'] = {'color': 'purple', 'weight': 4, 'opacity': 0.5}
```

**Comment by thomaspnrhj** [comment]
@submarcos merci de ton retour, effectivement dans les modules annexes, la conf est bien prise en compte de mon côté également, mais pas dans le module concerné.

**Comment by submarcos** [comment]
Du coup je me demande si çà a vraiment fonctionné sur le module pricnipal, car on a pas touché le code à ce niveau (uniquement au niveau de MAP_STYLES -> MAPENTITY_CONFIG['MAP_STLYES']). De plus, en regardant le code, il faudrait effectuer des modifications pour que ce soit visible sur le module principal (voir https://github.com/GeotrekCE/Geotrek-admin/pull/2556/files). ENfin, j'ai testé sur des versions précédentes aux modifications, et j'ai le même comportement

**Comment by Chatewgne** [comment]
A reprendre : https://github.com/GeotrekCE/Geotrek-admin/pull/2556

**Comment by camillemonchicourt** [comment]
OK avec la 2.73.0, les styles customisés sont bien appliqués sur tous les objets sur toutes les pages.
Je me suis basé sur les styles définis par défaut (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L390-L410) pour en surcoucher certains : 
```
MAPENTITY_CONFIG['MAP_STYLES']['detail'] = {'color': 'purple', 'weight': 4, 'opacity': 0.7}
MAPENTITY_CONFIG['MAP_STYLES']['others'] = {'color': 'purple', 'weight': 4, 'opacity': 0.7}
MAPENTITY_CONFIG['MAP_STYLES']['district'] = {'weight': 6, 'color': '#995d07', 'opacity': 0.3, 'fillOpacity': 0.0, 'dashArray': '12, 12'}
```

J'ai utilisé l'objet ``others`` qui s'applique à tous les objets sauf les tronçons qui sont ainsi resté distincts, en rouge avec leur style par défaut.

**Comment by thomaspnrhj** [comment]
Parfait, par contre de mon côté la customisation de "draftpath" ne fonctionne pas, les tronçons en "brouillon" sont customiser avec MAPENTITY_CONFIG['MAP_STYLES']['path']  et pas MAPENTITY_CONFIG['MAP_STYLES']['draftpath'] !
