### ISSUE TITLE
Bug affichage intervention selon niveau de zoom

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2557]
Bonjour, sur la 2.49.0 selon le niveau de zoom sélectionné, certaines interventions apparaissent et disparaissent. Faire glisser la carte provoque aussi ce comportement :

https://user-images.githubusercontent.com/45095227/108825316-2719b200-75c3-11eb-8406-11d57bcd2531.mov

J'en profite pour dire que je n'ai pas pu changer l'opacité des linéaires pour qu'ils soient plus visibles ( voir : https://github.com/GeotrekCE/Geotrek-admin/issues/2554)

**Comment by camillemonchicourt** [comment]
En effet je viens de constater un soucis similaire sur ma production en 2.51.1.
Quand j'arrive sur le module Interventions, parfois les interventions s'affichent sur la carte mais pas dans la liste. Parfois elles disparaissent aussi de la carte.

![image](https://user-images.githubusercontent.com/4418840/110763644-68ac8d00-8252-11eb-936f-0e0f06ab7e60.png)

**Comment by pnrma** [comment]
Constaté aussi de notre côté. Version 2.51.1 également.

**Comment by gutard** [comment]
Bug introduit dans la version 2.49.0 à cause des modifications sur le filtrage (valeurs multiples). Seules les interventions qui intersectent le bord de la carte sont affichées, pas celles qui sont entièrement dedans.
