### ISSUE TITLE
Erreur API V2

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2558]
En 2.50, nouvelle erreur de l'API lors de la consultation via https://randoadmin.parc-haut-jura.fr/api/v2/trek/, j'ai un server error 500 et je reçois l'erreur suivante par mail : 

[Geotrek] ERROR (EXTERNAL IP): Internal Server Error: /api/v2/trek/

Internal Server Error: /api/v2/trek/

TypeError at /api/v2/trek/
Object of type 'LineString' is not JSON serializable

Request Method: GET
Request URL: https://randoadmin.parc-haut-jura.fr/api/v2/trek/
Django Version: 3.1.7
Python Executable: /opt/geotrek-admin/bin/python Python Version: 3.6.9 Python Path: ['/', '/', '/opt/geotrek-admin/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/opt/geotrek-admin/lib/python3.6/site-packages']
Server time: Wed, 24 Feb 2021 16:02:24 +0100 Installed Applications:
('modeltranslation',
 'django.contrib.auth',

**Comment by camillemonchicourt** [comment]
OK tu dois avoir une rando qui a un problème de géométrie.
Car il est installé en 2.50.0 sur le démo (https://geotrekdemo.ecrins-parcnational.fr/api/v2/) et aussi sur notre serveur de production, sans erreur.

**Comment by thomaspnrhj** [comment]
Ok je regarde d'où ca vient alors merci !

**Comment by thomaspnrhj** [comment]
Effectivement un itinéraire avec une géométrie invalide faisait bugué l'API, c'est résolu, désolé du dérangement ! 
Thomas

**Comment by camillemonchicourt** [comment]
OK c'est cependant pas dérangeant car ça nous indique si une rando a un problème de géométrie, cela ne devrait pas faire péter l'API, mais soit lever une erreur sur la rando concernée, soit l'exclure.

Bon du coup si tu as un Geotrek-admin 2.50.0, tu vas pouvoir tester le déploiement de la V3 de Geotrek-rando que l'on finalise cette semaine. 
Je suis en train de tester et compléter la documentation aujourd'hui : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/installation.md
Avec aussi un premier aperçu du Changelog : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/changelog.md

**Comment by gutard** [comment]
Fixé (réellement cette fois-ci, et avec des tests ;) par https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.51.1
