### ISSUE TITLE
API V2 - Treks fields languages

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2575]
Quand on interroge l'API dans une langue différente de celle par défaut, certains contenus de champs sont quand même renvoyés  dans la langue par défaut.

Exemple : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/903303/?language=en&omit=geometry
Les champs "access" et "ambiance" sont renvoyés en français, alors qu'ils ont été traduits en anglais.

Idem sur d'autres champs de treks et/ou de touristic_contents ?

**Comment by gutard** [comment]
Il manque aussi disabled_infrastructure. Pour le reste ça a l'air OK pour tout ce qui concerne trek & tourism.
