### ISSUE TITLE
Outdoor - API v2 pour les parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2577]

**Comment by camillemonchicourt** [comment]
Vérifier les champs, car il semble manquer l'altitude, l'itinérance, les médias.

**Comment by Chatewgne** [comment]
Ajout de champs manquants PR https://github.com/GeotrekCE/Geotrek-admin/pull/2756

**Comment by camillemonchicourt** [comment]
OK dans la 2.65.0
