### ISSUE TITLE
Outdoor - Afficher le champ cotation dynamiquement sur le formulaire des parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2586]
Quand on choisit le site (et donc la pratique) ou quand le site est précisé par un paramètre GET.

**Comment by camillemonchicourt** [comment]
En effet, actuellement, il faut créer le parcours en le rattachant à un site, l'enregistrer, et c'est seulement à ce moment-là le champs "Cotation" est affiché.
Il faudrait qu'il soit affiché directement et dynamiquement dès que l'on choisit un site de rattachement du parcours.

**Comment by Chatewgne** [comment]
PR (mergée) https://github.com/GeotrekCE/Geotrek-admin/pull/2760

**Comment by Chatewgne** [comment]
Champ cotation dynamique sur les parcours :  https://github.com/GeotrekCE/Geotrek-admin/pull/2760 (mergé)
Champ cotation dynamique sur les sites :  https://github.com/GeotrekCE/Geotrek-admin/pull/2761

**Comment by Chatewgne** [comment]
Aïe, je reprends tout ça dans une PR : https://github.com/GeotrekCE/Geotrek-admin/pull/2765

- Les champs de cotations multiples ne sont pas affichés sous forme de liste 

Je ne reproduis pas cet affichage, ni sous Chromium ni sous Firefox. Quel navigateur utilise-tu ? En quelle version ? Ce phénonème est-il présent sur d'autres champs à sélection multiple ?

- Je créé un nouveau site, je chois une pratique, cela m'affiche ses champs de cotation. Je ne termine pas la saisie, je retourne sur la liste des sites et je créé un nouveau site. Toutes les cotations de toutes les pratiques sont alors affichées

Désolée pour ça, j'aurais dû remarquer que la sélection vide n'était pas toujours bien prise en charge

- Quand je modifie un site qui a déjà une pratique, ses cotations sont bien affichées, mais le champs est affiché sous le chapeau, alors qu'en création il est affiché au-dessus. Le laisser au-dessus du chapeau en création et édition

Bien vu, cela n'arrive que sur les sites publiés pour lesquels le champ "en attente de publication" disparaît, ce qui cause un décalage dans le formulaire. J'ai changé pour bien caler le champ cotation juste après le combo pratique+type, sans se baser sur le nombre de champs présents dans le formulaire.

- En édition, les champs de cotation sont affichés de manière trop large, même si leurs textes ne sont pas longs

Ok, ça doit dépendre de la taille de l'écran puisque je n'avais pas ce problème, j'ai essayé de remplacer par quelque chose qui ne dépends plus de la taille de l'écran.

- Idem sur les champs Thèmes, Lieux et Liens qui sont affichés trop larges, avec même parfois le texte d'aide à droite du champs et non pas en dessous

Ca c'était depuis la mise à jour boostrap, on l'a changé.


Il faudrait faire le même travail de dynamisation pour le Type de Parcours, qui pour l'instant ne peut être sélectionné qu'après une première sauvegarde.

**Comment by camillemonchicourt** [comment]
> > Les champs de cotations multiples ne sont pas affichés sous forme de liste

> Je ne reproduis pas cet affichage, ni sous Chromium ni sous Firefox. Quel navigateur utilise-tu ? En quelle version ? Ce phénomène est-il présent sur d'autres champs à sélection multiple ?

Je suis sur Chromium sur Ubuntu.
Idem après vidé le cache. Et je viens de tester sur Firefox et pareil.
J'ai des erreurs dans la console, je sais pas si ça peut aider.
Tu peux tester ça sur notre Geotrek-admin de DEMO sur https://geotrekdemo.ecrins-parcnational.fr (admin / admin)

OK merci pour les autres points, je suis preneur d'une release corrective quand c'est bon pour vous.

Et oui, je suis favorable à ce que ce soit fait aussi sur "TYPE DE PARCOURS" dans la foulée, maintenant que le mécanisme est bien calé pour les cotations.

**Comment by Chatewgne** [comment]
Ok, en me connectant sur votre admin je cerne mieux, en fait les points 1 et 2 ont la même origine, c'est la pratique vide qui cause le mauvais affichage.

Quand je modifie un site ayant déjà une pratique, alors l'affichage est bon (en tout cas pour ma taille d'écran).

![image](https://user-images.githubusercontent.com/26015573/134359549-608bc71c-7c92-49b8-9c3e-a885a858124f.png)

Je ferais une release avec le fix dès que possible.

**Comment by camillemonchicourt** [comment]
OK super, merci.

**Comment by camillemonchicourt** [comment]
OK tout est corrigé dans la 2.66.0.
