### ISSUE TITLE
Itinérance sur les parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2587]
Sur le même modèle que pour la randonnée (un seul niveau de hiérarchie, ordonnancement des étapes). Permet entre autres de créer des longues voies d'escalade.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.52.0.
Quand on créé un parcours, on peut y associer les parcours enfants.

![Capture d’écran de 2021-05-03 14-20-42](https://user-images.githubusercontent.com/4418840/116875235-db1a6780-ac1a-11eb-890f-9bd82f38607e.png)
