### ISSUE TITLE
Outdoor - Rattachement des aménagements aux sites/parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2588]
- Et indirectement via les aménagements ?
- En proposer la liste dans l'API v2 pour la valorisation

**Comment by camillemonchicourt** [comment]
Sur un site ou un parcours, les aménagements sont associés par un buffer.

Il reste à ajouter les aménagements publiés dans l'API V2 avec une route dédiée, filtrable par site ou parcours.

**Comment by Chatewgne** [comment]
Filtre ajouté au à la création la route `infrastructure` : PR https://github.com/GeotrekCE/Geotrek-admin/pull/2748

Le filtre `NearbyContentFilter` https://github.com/GeotrekCE/Geotrek-admin/blob/327effe3c89121be48068f733b7d4249010bcdef/geotrek/api/v2/filters.py#L234 permet d'ajouter les filtres `near_trek`, `near_touristicevent`, `near_touristiccontent`, `near_outdoorcourse`, `near_outdoorsite` comme un "package" sur les routes où on l'active
