### ISSUE TITLE
Outdoor - Rattachement des interventions aux sites/parcours

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2589]
Et indirectement via les aménagements ?

**Comment by camillemonchicourt** [comment]
3 possibilités : 
- Je créé une intervention indépendamment de tout objet, celle-ci peut être associée aux sites ou parcours à proximité par buffer
- Je créé une intervention directement associée à un parcours ou un site en passant par sa fiche (sans le localiser car dans ce cas elle prendra la géométrie de l'objet lié)
- Je créé une intervention sur un aménagement lui-même associé à un aménagement associé au site ou parcours (par buffer)
