### ISSUE TITLE
Rayon signalétique/tronçon

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2590]
Lorsqu'on créé une signalétique, elle est automatiquement rattachée aux tronçons à proximité immédiate.
Existe t-il un paramètre pour augmenter le rayon permettant le rattachement des signalétique aux tronçons un peu plus éloignés ?

**Comment by camillemonchicourt** [comment]
La signalétique est rattachée aux tronçons par segmentation dynamique, donc il n'y a pas de logique de buffer ou de distance.
Elle est rattachée en segmentation dynamique au tronçon le plus proche, peu importe la distance.
Voir https://geotrek.readthedocs.io/en/master/user-manual.html#edition-d-un-objet

**Comment by pnrma** [comment]
Merci Camille pour ces éclaircissements.
