### ISSUE TITLE
MAJ Ubuntu 20.04

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2602]
Je viens de mettre à jour un VPS  en Ubuntu 18.04 vers 20.04 avec dessus GTA en 2.52.1 et GTRv2.

J'ai bien accès à GTR par contre GTA est indisponible.

L'installation d'Ubuntu 20.04 m'a imposée de supprimer Postgres11 et PGis2.5 qui ont été réinstallés après l'installation. Une nouvelle bdd a donc aussi été créée et les anciennes données restaurées.

La cmd suivante me renvoie : 
 sudo dpkg-reconfigure geotrek-admin
-> /usr/sbin/dpkg-reconfigure: geotrek-admin est cassé ou partiellement installé

La cmd suivante me renvoie : 
sudo service geotrek restart
-> Failed to restart geotrek.service: Unit geotrek.service is masked

Ci joint le log d'erreur de GTA.

Quelqu'un aurait-il des pistes ? 

Merci !

[geotrek_error.log](https://github.com/GeotrekCE/Geotrek-admin/files/6172482/geotrek_error.log)

**Comment by gutard** [comment]
Il faudrait essayer `sudo apt install -f`. Et regarder le log `/var/log/apt/term.log`

**Comment by JeanLenormand** [comment]
Ok merci Gael.

Voici le retour de la commande : sudo apt install -f
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
libgeos-3.7.1 postgis-doc python3-scour scour screamshotter
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 5 non mis à jour.

Le log ci dessous : 
[term.log](https://github.com/GeotrekCE/Geotrek-admin/files/6172856/term.log)

Merci !

**Comment by gutard** [comment]
Essaye d'ajouter l'option `--force` à la commande `sudo dpkg-reconfigure geotrek-admin`.

> L'installation d'Ubuntu 20.04 m'a imposée de supprimer Postgres11 et PGis2.5

Oui c'est normal, vu que sur le 20.04 c'est postgres 12 et postgis 3.0

> qui ont été réinstallés après l'installation

Pourquoi ne pas partir sur les versions "standards" d'Ubuntu 20.04 ?

**Comment by JeanLenormand** [comment]
J'ai lancé la commande suivante mais rien ne se passe : 
sudo dpkg-reconfigure geotrek-admin --force

/var/log/nginx/geotrek_error.log me renvoie ->
2021/03/19 20:21:47 [crit] 12171#12171: *123 connect() to unix:/tmp/gunicorn-geotrek.sock failed (2: No such file or directory) while connecting to upstream>

Pourquoi ne pas partir sur les versions "standards" d'Ubuntu 20.04 ? -> en effet, mais je suis bloqué sur l'update de postgis 2.5 à 3 pour restaurer ma bdd ... :/

**Comment by claudep** [comment]
À mon avis, vous aurez besoin d'aide avec quelques compétences sysadmin. Je peux peut-être aider, vous pouvez me contacter à claude at 2xlibre.net.

**Comment by gutard** [comment]
> je suis bloqué sur l'update de postgis 2.5 à 3 

https://github.com/GeotrekCE/Geotrek-admin/issues/2600#issuecomment-803263084

**Comment by JeanLenormand** [comment]
L'update de Postgis 2.5 à 3 n'a pas changé grand chose. Je reviens au même problème.

Par contre, comme suggéré par @gutard j'ai suivi la doc des problèmes liés au gestionnaire de paquet ->  https://doc.ubuntu-fr.org/probleme_apt

Et effectué la cmd suivante : 
sudo dpkg -P --force-all geotrek-admin (purge des fichiers de configuration de geotrek-admin)

Puis j'ai restauré GTA et mes données, tout est maintenant ok.


@claudep, je note, merci pour l'info et pour vos travaux effectués sur GTA !
