### ISSUE TITLE
Étudier la possibilité de tracer un parcours par routage sur le site

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2614]
Dans le cas où la géométrie du site est linéraire

**Comment by gutard** [comment]
La proposition est plutôt de considérer le site comme une vallée ou un bassin versant complet, ou un buffer autour du cours d'eau. la problématique du dessin des cours d'eau peut-être résolue par un import des géométries (via QGIS ou un parser).

**Comment by camillemonchicourt** [comment]
En effet, pour le moment, on n'a pas jugé pertinent de pouvoir tracer un parcours en utilisant la géométrie de son site.
