### ISSUE TITLE
Lien entre site/parcours outdoor et POI.

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#2616]

**Comment by gutard** [comment]
Par buffer. Le buffer pour lier les POI aux sites et parcours est réglable avec OUTDOOR_INTERSECTION_MARGIN et le buffer pour lier les sites et parcours aux POI est réglable avec TOURISM_INTERSECTION_MARGIN.

@camillemonchicourt, il faudrait probablement remettre de l'ordre dans ces réglages. Est-ce un buffer commun pour toute l'application ? Ou par app ? Ou par type d'objet ? Ou pour chaque relation possible entre chaque type d'objet ?

**Comment by camillemonchicourt** [comment]
C'est vrai que là c'est pas très implicite. Il faudrait à minima les préciser dans la doc qui détaille les paramètres ?

Pour moi c'est utile que la taille du buffer entre les contenus touristiques et les randos puisse être différent de celui qui associe les POI avec les sites outdoor, car c'est 2 choses qui peuvent avoir une logique différente.

Donc pourquoi pas mettre de l'ordre dans ces paramètres et ne pas en faire qu'un seul.

**Comment by camillemonchicourt** [comment]
Par défaut, le buffer fait 500m : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L547
Cette valeur par défaut est surcouchable dans la configuration avancée (`custom.py`).
A voir par ailleurs si il faut réorganiser, séparer ces valeurs de buffers de manière différente.
