### ISSUE TITLE
ERROR (EXTERNAL IP): Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by relaire** [GeotrekCE/Geotrek-admin#2623]
Bonjour,
J'ai plusieurs fois par jour une erreur ": _ERROR (EXTERNAL IP): Invalid HTTP_HOST header: 'XXXX'. You may need to add 'xxx' to ALLOWED_HOSTS._" envoyé par mail par le serveur GA.
XXXX correspond à l'IP ou l'URL de mon serveur Rando, ca dépend des fois.
De ce que j'ai compris, il s'agit d'une variable django (ALLOWED_HOSTS) à renseigner dans le setting.py. A priori je dirais dans /opt/geotrek-admin/lib/python3.6/site-packages/django/conf/global_settings.py.
Existe t il un moyen de sur-coucher ce fichier ?
Si je mets la variable dans mon var/conf/custom.py, cela me fait planter le server GA
Merci,
Renaud LAIRE (PNR LF)

**Comment by JeanLenormand** [comment]
Bonjour, je rebondi sur ce post car j'ai aussi ce problème.

D'après la doc, la valeur de la variable ALLOWED_HOSTS. est renseignée dans le fichier /opt/geotrek-admin/var/conf/nginx.conf
 soit via le champ "Geotrek-rando server name(s)" demandé lorsqu'un "sudo dpkg-reconfigure geotrek-admin" est effectué, soit en modifiant la conf nginx dans /opt/geotrek-admin/var/conf/nginx.conf.in

cf. add_header Access-Control-Allow-Origin ${RANDO_SERVER_NAME};

Lors du dpkg-reconfigure, j'ai indiqué Geotrek-rando server name(s) = * pour autoriser l'accès multisites mais cela n'a pas réglé le problème.

Faut-il en plus de la valeur "*"  pour le partage de ressources entre origines multiples rajouter "localhost" ? Dans ce cas, qu'elle est la bonne syntaxe dans le champ Geotrek-rando server name(s) ?

Merci.

**Comment by gutard** [comment]
@relaire, il ne faut pas mettre la variable ALLOWED_HOSTS manuellement mais faire `sudo dpkg-reconfigure` et répondre à la question "Server name" avec ton nom de domaine. Cela va automatiquement configurer la directive "server_name" pour nginx et "ALLOWED_HOSTS" pour Django. Si les deux sont cohérents tu ne devrait pas avoir ce message. Par contre, tu as ce message si nginx est configuré pour envoyer un autre domaine que celui configuré dans ALLOWED_HOSTS. C'est un mécanisme de sécurité.

As tu un fichier /etc/nginx/sites-enabled/default ou bien est-ce qu'il n'y a que /etc/nginx/sites-enabled/geotrek/geotrek.conf dans /etc/nginx/sites-enabled/ ? Dans ce dernier cas, il se peut que nginx laisse passer des requêtes vers Django avec le mauvais domaine.

**Comment by gutard** [comment]
@JeanLenormand tu mélanges deux choses qui n'ont pas de rapport (à part le fait d'être des noms de domaine). ALLOWED_HOSTS est un vérification faite par le serveur Django de Geotrek-rando alors que Access-Control-Allow-Origin est une vérification faite par le navigateur. Et cela concerne deux domaines différents, le premier celui de l'admin et le deuxième celui de rando.

Par contre, il faut évidemment mettre le bon nom de domaine (le même que ALLOWED_HOSTS) dans le setting API_URL côté rando. mais il s'agit de la destination et non de l'origine donc à ne pas confondre avec le problème de CORS.

**Comment by relaire** [comment]
Bonjour Gaël, j'ai bien le fichier default dans /etc/nginx/sites-enabled/ et l'ALLOWED_HOSTS défini via `dpkg-reconfigure`.
Je pense que cela vient plus de scanner de port et autre attaque sur cette IP (visible via le HTTP_X_FORWARDED_FOR dans le contenu du message d'alerte). Je vais plutôt chercher de ce coté là ...
Merci pour les indications.

**Comment by gutard** [comment]
> cela vient plus de scanner de port et autre attaque sur cette IP

Oui et non. Si nginx est bien configuré, il bloque ces "attaques" et n'envoie que les requêtes avec la bonne en-tête Host à Django. Donc il ne devrait pas y avoir ce message dans les logs, même en cas d'attaque.

**Comment by camillemonchicourt** [comment]
De mon côté, j'avais aussi beaucoup d'alertes similaires.

La conf NGINX ``default`` se charge de filtrer les requêtes sur le mauvais domaine avec :
```
server {
    listen      80 default_server;
    server_name _;
    ...
}
```
Cf. http://nginx.org/en/docs/http/request_processing.html. 
Sur Ubuntu, on a cela automatiquement dans la configuration NGINX par défault (``/etc/nginx/sites-enabled/default`` qui récupère tout ce qui ne va pas dans les autres confs NGINX (celle de Geotrek-admin par exemple qui indique le bon domaine de Geotrek).

En effet ma conf NGINX ``default`` n'était pas activée.
Malgré le fait de l'avoir réactivée, je continuai à avoir pas mal d'alertes.
En creusant avec @gutard et @amandine-sahl, on a identifié que celles-ci étaient liés à des appels de l'adresse IP de mon serveur mais en HTTPS.
Et en effet la conf ``default`` de NGINX exclut par défaut les appels sur le mauvais domaine, seulement en HTTP (port 80).
Pour exclure aussi celles en HTTPS, il faut l'indiquer en plus dans la configuration NGINX par défaut.

Si NGINX inférieur à la version 1.19 (le cas sur Ubuntu 18) :

```
# Prevent SSL connexion
# Voir https://serverfault.com/questions/578648/properly-setting-up-a-default-nginx-server-for-https#
server {
    listen 443 ssl default_server;
    server_name _;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    return       404;
}
```

Pour NGINX 1.19 et + :

```
# Voir https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake
server {
    listen               443 ssl default_server;
    ssl_reject_handshake on;
}
```
