### ISSUE TITLE
Error 500 - relation "altimetry_dem" does not exist

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2642]
Geotrek-admin Version 2.57.0

Bonjour,

Suite à une migration de serveur et une mise à jour d'une version <= 2.32, on a une erreur 500 lors de la création d'un tronçon. Idem lorsque l'on veut afficher le spatial extent avec server/tools/extents.

En regardant les logs je vois cette erreur : 

`django.db.utils.ProgrammingError: relation "altimetry_dem" does not exist`

Je comprends qu'il y a eu un gros soucis avec la BDD lors de sa restauration. Ma question est : est-ce que je dois refaire un dump et un restore, où est-ce qu'il existe une solution pour régler ce problème plus rapidement ? 

Les logs ici : 

sudo journalctl -eu geotrek-ui

[geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/6397659/geotrek-ui.log)

sudo journalctl -eu geotrek-api

[geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/6397661/geotrek-api.log)

sudo journalctl -eu geotrek-celery

[geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/6397662/geotrek-celery.log)

**Comment by gutard** [comment]
Il faut probablement faire un `CREATE EXTENSION postgis_raster` avant la restauration de la DB.

**Comment by mviadere-openig** [comment]
Hm, j'étais sûr de l'avoir fait, je vais retenter.
