### ISSUE TITLE
Interventions - calcul des coûts

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2643]
Dans le module intervention, il y a un truc que je comprends pas trop sur le calcul des coûts, en effet les coûts ne se cumulent pas, on dirait qu'il privilégie certains postes.
Par exemple si j'ajoute que la sous-traitance c'est bon : 
![image](https://user-images.githubusercontent.com/19687397/116561824-f297de80-a902-11eb-945f-7bcb3b79fb24.png)
 
Si je viens à ajouter du matériel en même temps, ça ne prend plus en compte la sous-traitance 
![image](https://user-images.githubusercontent.com/19687397/116562030-1e1ac900-a903-11eb-90ea-0de6c84ccf2d.png)

Et si j’ajoute tout, ça prend en compte que le coût matériel et homme 
![image](https://user-images.githubusercontent.com/19687397/116562916-e19b9d00-a903-11eb-9248-00ca11934e22.png)

Je peux comprendre la logique de départ en se disant c'est soit une intervention par un sous traitant ou soit une intervention interne, mais il peut y avoir des cas où il y a un coût matériel en plus d'une sous-traitance ou même une intervention d'un technicien. Du coup dans un soucis de compréhension et pour éviter des erreurs de suivi, est-ce que ce serait pas mieux de cumuler l'ensemble des coûts dans le coût total ?

**Comment by camillemonchicourt** [comment]
Normalement le fonctionnement prévu est que le total est le total de tous les autres coûts.
Il y a donc bien un soucis.

**Comment by gutard** [comment]
Je confirme que c'est un bug.

**Comment by gutard** [comment]
@thomaspnrhj, le fix sera dans la prochaine release.

**Comment by thomaspnrhj** [comment]
Super, merci @gutard !
