### ISSUE TITLE
API V2 - Ordre des photos et image favorite

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2650]
Dans Geotrek-admin, il est possible de choisir la photo à mettre en avant pour un objet en cliquant sur l'étoile pour la marquer.
Dans l'API V2, quand on renvoie les images d'un objet (rando, objet touristique,...), il faudrait renvoyer l'image marquée en premier pour qu'elle soit utilisée comme photo principale.

Les suivantes pourraient être affichées par "date_insert" pour apparaître dans l'ordre avec lequel elles ont été associées à l'objet.

**Comment by babastienne** [comment]
Aujourd'hu les "attachments" dans le json d'un itinéraire renvoi l'ensemble des fichiers attachés, pas uniquement les images. 
Est-ce que qu'on conserve tel quel ou on modifie pour ne renvoyer via l'api que les images ?

**Comment by camillemonchicourt** [comment]
Non, il faut bien renvoyer tous les fichiers attachés comme actuellement.
On aura aussi besoin à terme des vidéos, audios, PDF...
Il faut juste revoir l'ordre dans lequel elles sont renvoyées (commencer par le fichier étoilé, puis par date d'insertion).

**Comment by babastienne** [comment]
Résolu dans https://github.com/GeotrekCE/Geotrek-admin/pull/2680

**Comment by camillemonchicourt** [comment]
Fait dans la 2.60.0
