### ISSUE TITLE
API V2 - POI exclus et filtre par rando

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2651]
Quand on appelle la route des POI en filtrant en passant l'id d'une rando, les POI exclus de cette randonnée sont présents dans la réponse listant les POI de la rando.

**Comment by babastienne** [comment]
Je ne suis pas sur de bien comprendre la problème. J'ai essayé de reproduire sur votre instance démo. 
Quand j'appelle la route https://geotrekdemo.ecrins-parcnational.fr/api/v2/poi/?trek=748 je me retrouve bien avec les 6 POIs présents sur la randonnée associée.

**Comment by camillemonchicourt** [comment]
Oui car cette rando n'avait aucun POI exclus : 

![Capture d’écran de 2021-05-29 12-03-05](https://user-images.githubusercontent.com/4418840/120066259-1c653200-c076-11eb-9e0b-05fe8763e57f.png)

Je viens d'en exclure un des 6 (col escalier) : 

![Capture d’écran de 2021-05-29 12-03-38](https://user-images.githubusercontent.com/4418840/120066267-25ee9a00-c076-11eb-8b5b-e621345571ce.png)

La rando ne liste désormais plus que 5 POI : 

![Capture d’écran de 2021-05-29 12-03-56](https://user-images.githubusercontent.com/4418840/120066279-37d03d00-c076-11eb-8b41-186d1a2520af.png)

Mais la route renvoie toujours les 6 POI, il ne prend pas en compte le fait que l'un d'eux est exclus de cette rando : https://geotrekdemo.ecrins-parcnational.fr/api/v2/poi/?trek=748

**Comment by babastienne** [comment]
Ok c'est plus clair. Merci pour les précisions

**Comment by babastienne** [comment]
Corrigé par https://github.com/GeotrekCE/Geotrek-admin/pull/2680

**Comment by camillemonchicourt** [comment]
OK dans la 2.60.0
