### ISSUE TITLE
Comment exécuter "python manage.py clearsessions" ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2659]
Avec le temps, la table ``public.django_session`` de notre Geotrek-admin contient plus de 3 millions de lignes et pèse plus de 800 Mo.
En recherchant (https://docs.djangoproject.com/en/dev/topics/http/sessions/#clearing-the-session-store) j'ai identifié qu'il existait une commande Django pour supprimer les enregistrements de sessions expirées pour faire du ménage dans cette table : ``python manage.py clearsessions``.

Mais je ne trouve pas où et comment exécuter cette commande ?

**Comment by numahell** [comment]
Salut, si ton installation a été faite via les paquets, tu peux utiliser la commande `geotrek <commande django>` qui va lancer `python manage.py <commande django>`. Donc si tu veux lancer `python manage.py clearsessions`, tu lances à la place 

```
sudo geotrek clearsessions
```

Et pour une installation via Docker, il faut utiliser la commande `docker-compose` depuis le dossier où est situé le code source (et donc le fichier `docker-compose.yml` que cette commande utilisera implicitement) : 

```
docker-compose run --rm web ./manage.py <command django>
```

**Comment by camillemonchicourt** [comment]
OK super, je suis avec installation avec les paquets.
Ça a fonctionné parfaitement avec ``sudo geotrek clearsessions`` et c'est bien efficace et utile.
La table est passée de 800 Mo à 80 ko.
Il a fallu faire un ``VACUUM`` pour que la taille de la table soit recalculée.

```SQL
SELECT pg_size_pretty( pg_total_relation_size('django_session') );
-- Avant : 821 MB
-- Après : 80 kB

SELECT count(*) FROM django_session;
-- Avant : 3048209
-- Après : 105

VACUUM (FULL, VERBOSE) public.django_session;
```

**Comment by camillemonchicourt** [comment]
Oui je pense aussi que ça n'a pas d'intérêt de garder les sessions expirés, et ceux qui ne seront pas au courant verront leur table grossir sans cesse, sans usage.
Donc je trouve que c'est une bonne idée de l’exécuter automatiquement à chaque migration.

**Comment by babastienne** [comment]
Pour ma part je pense également que c'est bien de faire ça automatiquement en effet. Autant éviter d'accumuler des données pour rien.

**Comment by submarcos** [comment]
https://github.com/GeotrekCE/Geotrek-admin/issues/2664
