### ISSUE TITLE
2.58.0 - Critères du filtre "topologie valide" ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2663]
Dans la version 2.58.0, un filtre intéressant permettant de rechercher les topologies invalides a été ajouté.
Mais je viens de le tester et sur mes 556 randos, il m'en renvoie 215 : 

![Capture d’écran de 2021-05-20 17-59-47](https://user-images.githubusercontent.com/4418840/119011571-7a6a8900-b995-11eb-804d-a35d1f0c8c80.png)

Et pour la plupart, je ne vois pas quels problèmes de topologie elles ont.
Quel est le critère de ce filtre "topologie invalide" pour remonter ces 215 randos ?

**Comment by LePetitTim** [comment]
Les topologies sont invalides dès lors que l'on a potentiellement un problème lorsqu'on essaye de les modifier.

Les topologies, c'est n PathAggregations avec un ordre, 1 tronçon, un point de depart, un point d'arrivé. 
Si parmis ces n pathaggregations il y a un problème d'ordre, il remonte dans la liste des topologies invalides. 

Pour eviter que la topologie remonte dans les topologies invalides, il suffit de modifier un peu la geometrie pour recalculer l'ordre des pathaggregations de la topologie.

**Comment by camillemonchicourt** [comment]
OK merci pour ces précisions. 
J'étais étonné d'en avoir 215 sur 556 qui étaient invalides alors que la plupart n'ont pas de problème apparent.
Mais beaucoup doivent donc avoir un problème non bloquant ni visuel d'ordre.
Je vais creuser, merci pour cette nouvelle fonctionnalité et pour les précisions.

**Comment by jeromesourdin** [comment]
C'est en lien avec #2515

**Comment by camillemonchicourt** [comment]
Par contre @jeromesourdin, je ne vois pas le lien entre les topologies invalides, et le fait que le tracé est recalculé lors de la modification d'une topologie quand on l'édite et que des tronçons ont été ajoutés entre temps, prenant alors un chemin le plus court différent ?

**Comment by jeromesourdin** [comment]
@camillemonchicourt  C'est le dernier commentaire  @gutard  sur le post.
L’étendu des dégâts au CD22 : 552 défectueux sur 1042 !

**Comment by amandine-sahl** [comment]
Nous n'avons aucune topologie invalide via le filtre de la liste, alors que certains itinéraires ne sont pas valides.

**Comment by amandine-sahl** [comment]
Après avoir refait quelques tests tous les itinéraires concernés avait une géométrie de type multipolygone
