### ISSUE TITLE
Erreur nginx quand plusieurs RANDO_SERVER_NAME spécifié

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#2670]
Il y a un soucis avec le Access-Control-Allow-Origin quand il y a plusieurs valeurs spécifiées.
A priori il faut avoir une ligne par valeur

**Comment by LePetitTim** [comment]
Est ce que c'est possible de changer la ligne qui ne fonctionne pas en mettant les urls rando sur la même ligne ?
-> add_header Access-Control-Allow-Origin rando_url_1, rando_url_2;
C'est pas sure que cela fonctionne.

**Comment by amandine-sahl** [comment]
Avec des virgules comme séparateur ça ne fonctionne pas. 
On peut les mettre sur une ligne entouré de double quote ça ne lance pas d'erreur nginx mais ça n'est pas fonctionnel : le deuxième site retourne une erreur CORS.

**Comment by LePetitTim** [comment]
Dernière solution qui doit fonctionner :
En haut du fichier :
map $http_origin $allow_origin {
    "~^https://```url```$" $http_origin;
    "~^https://```url```$" $http_origin;
    default "";
}

Dans la partie api :
Ajouter :
``` 
add_header Access-Control-Allow-Origin $allow_origin;
```

**Comment by amandine-sahl** [comment]
Ca fonctionne. Merci

Par contre si on modifie le template de configuration nginx attention aux personnes ayant surchargés le template pour le https  (cf #2170)

**Comment by LePetitTim** [comment]
> Par contre si on modifie le template de configuration nginx attention aux personnes ayant surchargés le template pour le https (cf #2170)

En effet.

**Comment by LePetitTim** [comment]
https://github.com/GeotrekCE/Geotrek-admin/pull/2672

**Comment by camillemonchicourt** [comment]
Comme modifié dans la 2.59.0, j'ai modifié mon fichier ``conf/nginx.conf.in`` en remplaçant : 

```
add_header Access-Control-Allow-Origin ${RANDO_SERVER_NAME};
```
par 
```
map ${DOLLAR}http_origin ${DOLLAR}allow_origin {
    "~${RANDO_SERVER_NAME_PIPE}" ${DOLLAR}http_origin;
    default "";
}
```

Mais depuis mon Rando Ecrins v3 ne peut plus accéder aux pictos, par exemple : 
```
Access to fetch at 'https://geotrek-admin.ecrins-parcnational.fr/media/upload/network-VTT_iti.svg' from origin 'https://rando.ecrins-parcnational.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

L'accès à l'API est OK grace à l'ajout de la ligne ``add_header Access-Control-Allow-Origin ${DOLLAR}allow_origin;`` dans ``location ~ ^/api {``.

Ma variable est à ``RANDO_SERVER_NAME="*"``.

Je ne suis pas certain que cette configuration fonctionne si on ne spécifie pas un nom de domaine et que l'on veut les accepter tous (``*``).

Je vais continuer les tests.

**Comment by amandine-sahl** [comment]
Placer le cross origin uniquement au niveau de l'api est trop restrictif d'autre routes sont utilisées de façon publique comme les médias téléchargés (media/upload) et les signalements.
A voir si c'est pertinent de le défiir globalement pour le server ou de dupliquer les autorisations au niveau de chaque route ouverte vers l'extérieur.

**Comment by camillemonchicourt** [comment]
OK, en effet, j'ai remis la proposition de @LePetitTim avec le mapping, mais j'ai déplacé l'ajout du header au niveau global, pas seulement dans la localtion ``/api``, donc en début de fichier (ou au début dans ``server``) : 

```
map ${DOLLAR}http_origin ${DOLLAR}allow_origin {
    "~${RANDO_SERVER_NAME_PIPE}" ${DOLLAR}http_origin;
    default "";
}

add_header Access-Control-Allow-Origin ${DOLLAR}allow_origin;
```

Comme cela ça fonctionne bien, mais uniquement quand mon paramètre ``RANDO_SERVER_NAME`` a pour valeur ``*``. Si renseigne mon nom de domaine précis (``rando.ecrins-parcnational.fr``), j'ai des problèmes de CORS.

Je ne comprends pas pourquoi cela fonctionne avec ALL (``*``), mais pas avec mon nom de domaine.

**Comment by mviadere-openig** [comment]
J'ai le même problème que toi @camillemonchicourt sur ce [Geotrek_rando_V3](https://rando-ccpvg-dev.openig.org/). Les pictos ne s'affichent pas dans les filtre de recherche, et dès que l'on tente de faire une recherche par secteur ou par commune j'ai des problèmes de CORS. J'ai tenté de déplacer le header au niveau global, cela n'a rien changé.

**Comment by camillemonchicourt** [comment]
C'est car la conf NGINX par défaut n'autorise le CORS que sur les URL /api alors que les pictos sont sur /medias
Par contre si tu déplaces la règle au niveau global alors tu accederas bien aux pictos.
Si ce n'est pas le cas, c'est que ta modification n'a pas été prise en compte, soit que tu as du cache navigateur.

**Comment by submarcos** [comment]
on va essayer de voir pour fixer les CORS, mais normalement il n' y a aucun CORS à configurer pour des images venant de sites externes, et les signalement sont deja configurés car ils fonctionnent pour rando v2 ( url /api/fr/reports/report -> cors activés derriere /api)

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour.
Avec nos tests, les pictos des pratiques ainsi que les signalements sont bloqués par le CORS quand la ligne ``add_header Access-Control-Allow-Origin...``est seulement dans la location ``/api`` mais je n'ai pas bien compris pourquoi, et encore pourquoi ça fonctionnait avec Geotrek-rando v2 mais pas v3.

**Comment by submarcos** [comment]
pour les picto il peut avoir du code qui ajoute les images avec du code js, et qui peut etre declenche des requetes ajax... ceci explique cela. pour les signalements par contre aucune raison que çà marche sur l'un et pas sur l'autre. l'url a bien été configurée coté admin ?

**Comment by camillemonchicourt** [comment]
De ce que j'ai compris, il prend la valeur du paramètre ``apiUrl`` (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L8) et enlève le ``/api/v2``.
Mais si il n'y a pas de raison que ça bloque au niveau de Geotrek-admin, alors on rebouclera avec les développeurs de Geotrek-rando en septembre.

**Comment by submarcos** [comment]
çà doit venir de là, il faut garder /api et enlever que le v2, l'url du post etant  /api/fr/reports/report

**Comment by submarcos** [comment]
en tous cas les signalements marche depuis votre instance rando v3.

**Comment by camillemonchicourt** [comment]
Oui car sur mon Geotrek-admin de production, j'ai changé le ``nginx.conf.in`` en mettant le ``add_header`` au niveau global, sinon ça ne passait pas : 

```
upstream ui_server {
    server unix:/tmp/gunicorn-geotrek.sock fail_timeout=0;
}

upstream api_server {
    server unix:/tmp/gunicorn-geotrek_api.sock fail_timeout=0;
}

map ${DOLLAR}http_origin ${DOLLAR}allow_origin {
    "~${RANDO_SERVER_NAME_PIPE}" ${DOLLAR}http_origin;
    default "";
}

add_header Access-Control-Allow-Origin ${DOLLAR}allow_origin;

server {
    server_name ${SERVER_NAME};
    server_name_in_redirect on;
    server_tokens off;

    access_log /var/log/nginx/geotrek_access.log;
    error_log /var/log/nginx/geotrek_error.log;

    client_max_body_size 10M;

    location /static {
        expires 1d;
        alias /opt/geotrek-admin/var/static;
    }

    location /media/upload {
        expires 1d;
        alias /opt/geotrek-admin/var/media/upload;
    }

    location /media_secure {
        internal;
        expires 1d;
        alias /opt/geotrek-admin/var/media;
    }

    location / {
        proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
        proxy_set_header X-Forwarded-Host ${DOLLAR}host;
        proxy_set_header X-Forwarded-Server ${DOLLAR}host;
        proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
        proxy_set_header Host ${DOLLAR}http_host;
        proxy_redirect off;

        keepalive_timeout 0;

        location ~ ^/api {
            proxy_pass http://api_server;
            proxy_read_timeout ${TIMEOUT}s;
        }

        proxy_pass http://ui_server;
        proxy_read_timeout ${TIMEOUT}s;
     }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/${SERVER_NAME}/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if (${DOLLAR}host = ${SERVER_NAME}) {
        return 301 https://${DOLLAR}host${DOLLAR}request_uri;
    } # managed by Certbot

    listen ${NGINX_PORT};
    server_name ${SERVER_NAME};
    return 404; # managed by Certbot

}

# Add redirection FROM IP to domain - Camille
server {
    server_name monip;
    return 301 https://${SERVER_NAME};
}
```

**Comment by submarcos** [comment]
Hum... on va tester sur notre rando v3 mais il doit y avoir un probleme ailleurs dans ce cas.

**Comment by camillemonchicourt** [comment]
OK super, merci pour les tests et précisions.

**Comment by Chatewgne** [comment]
Ajout de la règle CORS dans `/media` : PR https://github.com/GeotrekCE/Geotrek-admin/pull/2732
