### ISSUE TITLE
Upgrade to Bootstrap 4 : some little bugs

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2673]
- [ ] Scroll on layer box on map will zoom or unzoom map  : **minor**

- [x] required "*geom" label on "+" zoom button  : **minor**

- [x] check if CSS for altimetry profile are in altimetry app

- [x] Fix overflow in list (when list is full)   : **minor**
 
- [x] Fix confirm delete attachment modal   : **major**

**Comment by submarcos** [comment]
altimetry css is ok

**Comment by babastienne** [comment]
Bug when trying to delete an attached file on a Trek. The modal window seems to be broken : 

![image](https://user-images.githubusercontent.com/16348048/120800526-5768d900-c540-11eb-8a79-7c6b65a6a27b.png)

**Comment by numahell** [comment]
See PR #2683

**Comment by numahell** [comment]
> Scroll on layer box on map will zoom or unzoom map

This problem exists in previous versions (before upgrading to Bootstrap4)
