### ISSUE TITLE
Ajouter des informations aux portails dans l'admin de Geotrek-admin

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2685]
Dans un contexte de faciliter la gestion des portails rando Geotrek, nous cherchons à ajouter des fonctionnalités et de la configuration dans l'admin de Geotrek-admin.

Pour le moment, dans l'admin de Geotrek, nous pouvons mettre :
- l'url du portail rando
- ID Facebook
- Url de l'image Facebook (/!\ pas directement l'image, mais l'adresse sur le rando)
- Largeur de l'image facebook
- Hauteur de l'image facebook
SEO :
- le titre de rando dans chaque langue 
- la description du portail rando

Il y a des pistes d'améliorations pour la V2 (V3 ?) :

- Permettre d'ajouter les couleurs des catégories
- Permettre de gérer la customisation du portail rando : 
   * ficher settings.custom.json (V2) / global.json (V3)
   * fichiers html (footer, home ...) 
   * fichiers css

**Comment by camillemonchicourt** [comment]
OK cela serait certainement utile pour Geotrek-rando v2.

Par contre, au niveau de Geotrek-rando v3, on a fait en sorte que les éléments de SEO et des réseaux sociaux soient gérés au niveau de Geotrek-rando lui-même et de son contenu (titre et photo de la rando, ou du portail pour la page d'accueil), en intégrant les balises opengraph et les cards Twitter.
- Exemple sur la Home : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/components/PageHead.tsx#L26-L44
- On a aussi les balises "title" et "description" dynamiques pour chaque page, en fonction du contenu : https://github.com/GeotrekCE/Geotrek-rando-v3/commit/2327386e700dd21a9765527ce69571a745340c99
- Et un sitemaps.xml qui est généré dynamiquement pour optimiser l'indexation par les moteurs de recherche : https://github.com/GeotrekCE/Geotrek-rando-v3/commit/3b2fc535885b9789a9945479502972fe7f311bbb

Au niveau de la customisation (https://github.com/GeotrekCE/Geotrek-rando-v3/issues/7) et de la configuration (https://github.com/GeotrekCE/Geotrek-rando-v3/issues/8), on a fait assez simple au niveau de Geotrek-rando lui-même (blocs HTML pour la Home, variable de couleurs principales, surcouche CSS, surcouche de langues et fichiers JSON de configuration).

C'est assez simple en l'état et j'aime bien le fait de pouvoir gérer ça directement au niveau du (ou des) portail(s) Geotrek-rando, mais pourquoi pas permettre de gérer une partie de la customisation et de la configuration au niveau de Geotrek-admin.

A voir si c'est utile de le faire maintenant pour la V2 de Geotrek-rando, alors qu'on va petit à petit basculer sur la V3.

Dans tous les cas, les éléments définis pour la V2 ne seraient pas les mêmes que pour la V3, donc ça serait à préciser, et cela rendrait les outils plus dépendants. 

A noter aussi que depuis un Geotrek-admin, on peut publier sur différents portails Geotrek-rando.

**Comment by LePetitTim** [comment]
En effet si c'est géré sur Geotrek-rando v3. On peut voir si la proposition est si importante avec l'utilisation de Geotrek-rando V3.

Concernant la V2, c'est beaucoup de travail pour quelque chose qui risque de disparaitre assez rapidement, et qui n'est pas primordial.
