### ISSUE TITLE
Listes et exports - Pouvoir paramétrer les colonnes

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2688]
Ajouter un paramètre par module, pour pouvoir définir les champs présents dans les exports des listes (CSV et SHP).

- Par défaut, exporter toutes les colonnes des objets de chaque module. En renseignant par défaut le paramètre avec tous les champs disponibles ? Ou en laissant le paramètre vide si on veut tous les champs ?
- Identifier les champs qui sont disponibles pour chaque module
- A voir si cela n'est pas trop contraignant quand on ajoute un champs dans un module

**Comment by Chatewgne** [comment]
- Par défaut avec le paramètre vide : on

**Comment by Chatewgne** [comment]
Création d'un setting pour customiser les colonnes à l'affichage :

```
COLUMNS_LISTS["poi_view"] = [
    ["structure", "description", "type", "min_elevation", "date_update", "date_insert"],
]
```
Et pour customiser les colonnes à l'export :
```
COLUMNS_LISTS["poi_export"] = [
    ["structure", "description", "type", "min_elevation", "date_update", "date_insert"],
]
```

- Par défaut (pas de setting) : on affiche / exporte les mêmes champs qu'avant

- Avec l'ajout d'un setting : on écrase les colonnes par défaut 

La liste de champs disponibles sera disponible dans la documentation.

Il y a beaucoup de champs utilisables, surtout sur certains modules, attention à ne pas surcharger l'interface en colonnes car cela a un impact sur les performances.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2695

**Comment by camillemonchicourt** [comment]
OK merci. 
Concernant les exports, cela concerne uniquement ceux au format CSV, ou aussi ceux au format SHP ?
Merci.

**Comment by Chatewgne** [comment]
Ça concerne bien les deux 🙂

**Comment by camillemonchicourt** [comment]
OK super, je te laisse l'indiquer dans la documentation qui indique que le CSV. Merci.

**Comment by Chatewgne** [comment]
https://github.com/GeotrekCE/Geotrek-admin/pull/2695/ Mergée

**Comment by camillemonchicourt** [comment]
OK testé dans la 2.73.0.

Test sur le module Interventions : 
- On peut bien afficher les différents champs listés dans la documentation
- Seul le champs multiple "Désordres" a un problème d'affichage et ne remonte pas bien l'info du champs : 
![image](https://user-images.githubusercontent.com/4418840/145896985-fa17f52c-d15f-47d8-80a6-d7c62984ced3.png)
- Pas de soucis par contre avec les champs multiples comme "themes" et "portal" de la propriété ``COLUMNS_LISTS["trek_view"]`` qui remontent bien dans la liste : 
![Capture d’écran de 2021-12-13 23-31-29](https://user-images.githubusercontent.com/4418840/145899454-580e1a74-9b06-40e5-aa8c-9e6b2a0a9296.png)

----------------------

Pour les exports, j'ai tenté un export allégé des itinéraires : 
```
# Export fields
COLUMNS_LISTS["trek_export"] = [
        "structure",
        "name",
        "duration",
        "duration_pretty",
        "networks",
        "advice",
        "ambiance",
        "difficulty",
        "information_desks"
    ]
```
Mais j'ai quand même tous les champs dans le CSV exporté : 
![Capture d’écran de 2021-12-13 23-46-50](https://user-images.githubusercontent.com/4418840/145901291-8f86b810-8d32-4a4e-ae09-d775bf2f23dd.png)

Par contre en testant sur les interventions : 
```
COLUMNS_LISTS["intervention_export"] = [
        "name",
        "type",
        "status"
    ]
```
Là le paramètre des colonnes est bien pris en compte : 
![Capture d’écran de 2021-12-13 23-55-06](https://user-images.githubusercontent.com/4418840/145902156-d16b5388-1392-48cd-b208-7b3d6a2d1c17.png)

Idem pour les exports signalétique (CSV et SHP) où la configuration des champs des exports est bien pris en compte.

A voir donc si il n'y a que pour les randonnées, que le paramètre des colonnes n'est pas pris en compte ?

**Comment by camillemonchicourt** [comment]
A noter aussi que l'export des itinéraires ne contient pas l'ID de chaque rando. Il faudrait l'ajouter dans l'export par défaut.

Et les UUID ne sont présents dans aucun export alors qu'ils sont un élément important des exports et échanges de fichiers.
Il faudrait les ajouter par défaut dans tous les exports, et pouvoir les ajouter/enlever des exports.
Penser alors à ajouter les UUID dans la documentation avancée (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/advanced-configuration.rst) dans les champs affichables dans les listes et les exports.

**Comment by LePetitTim** [comment]
> A noter aussi que l'export des itinéraires ne contient pas l'ID de chaque rando. Il faudrait l'ajouter dans l'export par défaut.
> 
> Et les UUID ne sont présents dans aucun export alors qu'ils sont un élément important des exports et échanges de fichiers. Il faudrait les ajouter par défaut dans tous les exports, et pouvoir les ajouter/enlever des exports. Penser alors à ajouter les UUID dans la documentation avancée (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/advanced-configuration.rst) dans les champs affichables dans les listes et les exports.

J'ai ajouté uuid dans les exports.
Je vais ajouter dans la doc uuid.

Il n'y a pas d'uuid sur les interventions + projets + zones sensibles

**Comment by LePetitTim** [comment]
@camillemonchicourt 
Est ce qu'on clot

**Comment by camillemonchicourt** [comment]
OK dans la 2.75.0 : 
- Les ID ont été ajoutés aux exports des randos
- Les UUID ont été ajoutés dans les exports des objets qui ont des UUID
- Les désordres sont bien affichés dans la liste des interventions si cette colonne a été ajoutée dans la conf des champs du module à lister
- Le paramètre ``COLUMNS_LISTS["trek_export"]`` est bien pris en compte désormais pour les exports des randos
- Des tests automatisés ont été ajoutés

**Comment by camillemonchicourt** [comment]
Reste juste ce petit effet de bord à corriger : https://github.com/GeotrekCE/Geotrek-admin/issues/2893
