### ISSUE TITLE
Question sur customisation pdf multi-portail

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2691]
GTK-ADMIN : 2.59.0

Bonjour,

J'ai un serveur Geotrek qui alimente deux Geotrek-Rando V3. Mon souhait serait que pour chacun des portails le logo du pdf correspondent à sa structure. 

Dans /opt/geotrek-admin/var/conf/extra_templates/trekking/trek_public_pdf.html j'ai tenté de faire ce genre de modification  :

`{% if targetportal_id.pk == 2 %}
          <img src="file://{% media_static_fallback_path "upload/Logo_PNR_Aubrac_-_Copie_-_LR.png" "images/Logo_PNR_Aubrac_-_Copie_-_LR.png" %}" alt="">
          {% else %}
          <img src="file://{% media_static_fallback_path "upload/logo-parc.jpg" "images/logo-parc.jpg" %}" alt="">
          {% endif %}`

Le tag portal_id.pk n'existant pas j'ai tenté de chercher où sont listés les différents tag utilisés. En lisant la doc des templates Django, j'ai compris que `{% load i18n mapentity_tags static %}` au début du fichier permet de charger des librairies de tag customisés et qu'à chacun des paramètres correspondait un fichier .py

j'ai cherché où étaient positionnés les différents fichiers et j'ai trouvé que le geotrek-tags.py : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/common/templatetags/geotrek_tags.py

N'étant pas développeur Pyhton, ma question est : existe-il dans les librairies utilisées actuellement dans le pdf un tag "portail" qui permet de faire une condition sur le logo que l'on souhaite afficher ? Si ce n'est pas le cas, peut-on me dire où doit être faite la modification ? C'est un besoin vraiment urgent de mon côté chez OPenIG car de plus en plus d'adhérents qui vont nous rejoindre auront leur propre portail GTK-rando sur la même base GTK-Admin. 

Merci à vous.

**Comment by submarcos** [comment]
Bonjour.
Il n'est actuellement pas possible de générer des pdfs différents par portail.

Le seul moyen serait de dupliquer les itinéraires pour chacun des portails, et de n'affecter qu'un seul portail à chaque itinéraire. Dans ce cas, le portail serait accessible dans le template, avec {{ object.portal.0.id }}.

Il serait necessaire de faire un chiffrage poussé pour pouvoir réaliser cette opération sans bidouille, car dans l'admin la génération des pdfs n'est pas du tout contrainte au lien potentiel avec un portail, et l'utilisation des portails est facultative. Pour faire simple, il n'y a pas de moyen de différencier le portail et de passer cette information au template du pdf dan développement consequent.

**Comment by camillemonchicourt** [comment]
Oui dans ce cas là, il n'y a justement qu'un seul portail par rando, donc ça peut fonctionner pour ce cas précis.
Mais pour que cela soit dynamique, un développement permettant de contextualiser le PDF selon des paramètres passés à la volée serait en effet intéressant.

**Comment by mviadere-openig** [comment]
Ok, sachant que sur notre Geotrek-admin chaque itinéraire possède son propre portail spécifique, ceci devrait marcher  : 


`{% if object.portal.0.id == 2 %}
          <img src="file://{% media_static_fallback_path "upload/logo-parc.jpg" "images/logo-parc.jpg" %}" alt="">
          {% else %}
          <img src="file://{% media_static_fallback_path "upload/Logo_PNR_Aubrac.png" "images/Logo_PNR_Aubrac.png" %}" alt="">{% endif %}`

Mais je ne vois pas de changement, j'ai dû faire une erreur de syntaxe ?

**Comment by submarcos** [comment]
Non théoriquement c'est çà

- essaie d'afficher {{ object.portal }} / {{ object.portal.0 }} et {{ object.portal.0.id }} directement dans le template pour vérifier que la donnée et bien accessible (çà ne marchera que si il y en a un seul )
- verifie que ton logo est bien au bon endroit (tu references 2 paths là, il est dans images ou dans upload ?) https://github.com/GeotrekCE/Geotrek-admin/blob/master/mapentity/templatetags/mapentity_tags.py#L77

**Comment by submarcos** [comment]
je decouvre media_static_fallback_path -> d'apres le code si tu l'as mis dans un dossier static de geotrek (par exemple extra_static) tu dois t'assurer qu'un collectstatic ait été effectué (le code regarde dans le dossier de collecte, pas dans le dossier original). C'est effectué normalement apres un dpkg-reconfigure / mise a jour / update.sh sur docker

**Comment by camillemonchicourt** [comment]
Solution mise en place dans la version 2.78.0 avec la possibilité de customiser les PDF par portail.

Exemple ici en passant dans l'URL du PDF le portail souhaité : https://geotrekdemo.ecrins-parcnational.fr/api/fr/treks/2/col-de-font-froide.pdf?portal=2

Le logo a été customisé en créant un fichier de customisant pour le portail 2 (``/opt/geotrek-admin/var/conf/extra_templates/trekking/portail_2/trek_public_pdf.html``) avec ce contenu : 

```
{% extends "trekking/trek_public_pdf.html" %}

          {% block logo %}
            <img src="https://monimage.jpg" alt="">
          {% endblock %}
```

Cela a aussi été précisé dans la documentation : https://geotrek.readthedocs.io/en/latest/advanced-configuration.html#override-public-pdf-templates

L'URL du PDF customisé par portail est renvoyé par l'API quand on filtre la route /trek par portail.
Il ne reste plus qu'à faire en sorte que Geotrek-rando-v3 filtre les routes par portail quand on affiche la fiche détail d'un objet.

**Comment by camillemonchicourt** [comment]
1 Geotrek-rando = 1 portail, donc ce cas d'usage n'est pas prévu.
Là tu ouvres un autre sujet.
Tu ne devrais pas utiliser le champs portail pour cela.

D'autant plus qu'au niveau de Geotrek-rando, quand on va être sur une fiche rando et devoir appeler le PDF avec le paramètre de son paramètre, on va utiliser son paramètre ``portalIds`` et comme tu en as défini plusieurs dans le paramètre de Geotrek-rando, alors cela ne fonctionnera pas non plus.
On ne peut pas utiliser le champs "portail" de chaque rando pour savoir qu'elle PDF interroger, justement car on en saisit souvent plusieurs pour une même rando. 
Donc c'est le contexte dans lequel l'objet est affiché qui nous intéresse, pas la liste des portails associée à chaque objet.

Ce que tu veux indiquer n'est pas la destination, mais la source.
Il y a un champs dans Geotrek pour cela, avec une source unique sur les randos, etc...

Et un logo associé à la source est déjà affiché dans les PDF.

Et dans le template de surcouche de ton PDF, tu peux surcoucher la partie du logo si tu veux avec un truc du genre : 

```
{% if source.pk == 1 %}<img src="logo-source1.jpg">{% if source.pk == 2 %}<img src="logo-source2.jpg">{% endif %}
```

Mais bon, normalement on a un logo par portail.
Et la source est affichée plus bas dans la fiche.

**Comment by IdrissaD** [comment]
Ta solution est 1000 fois plus simple et a bien plus de sens, merci !

La surcharge sur laquelle je me suis arrêté :

``` html
{% extends "trekking/trek_public_pdf.html" %}

          {% block logo %}
              {% if object.structure.name == 'PNC' %}<img src="url" alt="">{% elif object.structure.name == 'CD48' %}<img src="url" alt="">{% elif object.structure.name == 'PNRGCA' %}<img src="url" alt="">{% endif %}
          {% endblock %}
```

**Comment by camillemonchicourt** [comment]
Depuis la version 3.8.1 de Geotrek-rando qui vient de sortir (https://github.com/GeotrekCE/Geotrek-rando-v3/releases), les pages détail de Geotrek-rando interrogent maintenant l'API en passant le paramètre de portail (si il est défini dans la conf de Geotrek-rando) et ainsi en récupérant l'URL du PDF avec le paramètre du portail (utilisant l'éventuelle customisation du template de PDF par portail).
