### ISSUE TITLE
API v2 - trek - Manque les liens "En savoir plus"

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2692]
Exemple : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/370
Les liens "en savoir plus" ne sont pas présents dans la route /trek

**Comment by babastienne** [comment]
Ok en effet je confirme que les liens ne sont pas présents. A ajouter de note côté donc.

**Comment by Chatewgne** [comment]
Spécifications pour ce développement

[APIv2-spec-ajouts-weblinks.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/6702122/APIv2-spec-ajouts-weblinks.pdf)

**Comment by camillemonchicourt** [comment]
Ajouté dans la 2.61.0
