### ISSUE TITLE
Bug : Impossible de supprimer une ligne d'une lame ou un financement d'un projet.

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2693]
Il est impossible de supprimer une ligne d'une lame :

![2021-06-14_15-49](https://user-images.githubusercontent.com/26329336/121903453-9c52f380-cd28-11eb-89db-016606ebd31f.png)

1- Blade 1 de demo-admin.geotrek.fr
-----------------------------
![2021-06-14_15-50](https://user-images.githubusercontent.com/26329336/121903457-9e1cb700-cd28-11eb-8789-50aa30ba90c6.png)

2- Supprimer la deuxième ligne de la lame 1 de demo-admin.geotrek.fr

-----------------------------
![2021-06-14_15-50_1](https://user-images.githubusercontent.com/26329336/121903464-9fe67a80-cd28-11eb-8abb-b064aa82a911.png)
3 - Sauvegarder
-----------------------------
![2021-06-14_15-50_2](https://user-images.githubusercontent.com/26329336/121903468-a1b03e00-cd28-11eb-8a35-1f14cf65203d.png)
4 - Le champ est obligatoire alors que la ligne devrait etre supprimé

Techniquement, le problème vient des formsets, il y a plusieurs choses qui ont pu engendre le problème :
- Monter de version de Django
- JS qui ne fait pas le necessaire pour supprimer l'element.

**Comment by numahell** [comment]
`jquery.formset.js` a évolué par rapport à la version est actuellement dans Geotrek-admin/mapentity : à voir si en mettant à jour on résout des problèmes

https://github.com/elo80ka/django-dynamic-formset/blob/master/src/jquery.formset.js

**Comment by Chatewgne** [comment]
Attention on a le même problème au niveau des Journées-Hommes (ManDay) dans le module Intervention.
A résoudre en s'assurant que l'on fait bien un `manday.delete()` quand on supprime un manday (nécessaire pour conserver la cohérence des exports de coûts).

**Comment by numahell** [comment]
Il semble que le formulaire supprimé soit retiré du DOM au lieu d'être marqué comme "à supprimer" : mettre à jour django dynamic formset pourrait corriger ce problème, mais il semble rester un autre bug lié : https://github.com/elo80ka/django-dynamic-formset/issues/161

**Comment by camillemonchicourt** [comment]
OK je peux supprimer les lignes des lames dans la 2.73.0.

Mais une par une.
J'ajoute 2 lignes à une lame, je sauvegarde.
Je modifie la lame, je supprime les 2 lignes, je sauvegarde.
Seulement une des 2 lignes est supprimée.
Je modifie la lame et supprime la 2° ligne, je sauvegarde.
La seconde ligne est bien supprimée.

Idem sur les Jours/Homme sur les interventions.

**Comment by LePetitTim** [comment]
J'ai ajouté un test sur les lignes dans la partie django, je ne vois pas de problème côté django. Le problème serait côté Javascript, ou le lien entre le javascript et django.

Techniquement :
- Les formulaires supprimés avec django-formset-dynamic ne sont pas envoyés vers le formset. Il n'y a qu'un seul formset qui est envoyé.

**Comment by LePetitTim** [comment]
https://github.com/elo80ka/django-dynamic-formset/issues/180

**Comment by camillemonchicourt** [comment]
OK dans la 2.74.0
