### ISSUE TITLE
Gestion des portails et de la publication dans le cas de Geotrek-rando V2

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2694]
Nous avons notés une incomprehension fréquente sur la publication par portails.

Avec une randonnée dans le portail A (rando A), une randonnée dans le portail B (rando B) et une randonnée dans aucun portail (rando Z)

Si je fais une synchro filtrer sur le portail A:
rando A et Z vont remonter.
et si je ne filtre sur aucun portail :
rando A, B et Z vont remonter.

Dans tous les cas la rando sans portail remonte, pourtant ce n'est pas toujours voulu.

Il faudrait peut être un settings pour choisir si on veut prendre en compte les randos sans portails.

A noter :
- Dans la version Geotrek-rando V3, lorsqu'on filtre sur un portail, les randos, ... les éléments sans portails ne remontent pas.

Il faudrait un fonctionnement identique tout d'abord entre la version V2 et V3 de Geotrek-rando et ensuite imaginer un fonctionnement pour soit garder les éléments sans portails, soit ne pas les garder (paramètre).

**Comment by camillemonchicourt** [comment]
Oui en effet. 
Dans tous les cas que j'ai vu, quand les gens filtraient sur un portail, ils ne s'attendaient à ce que remontent aussi les objet sans aucun portail.
Ça a posé pas mal de soucis ou de surprises dans différents cas.

Je garderai uniquement le fonctionnement, où quand je filtre sur un portail, cela ne remonte que mes objets associés au portail.
C'est pour ça qu'on a pris ce chois sur l'API v2 (et donc dans Geotrek-rando V3).
Voir un autre ticket lié où ce sujet est discuté.

**Comment by LePetitTim** [comment]
Nous pensions mettre en place un booléen sur les portails pour choisir si on prend ou non les randonnées sans portails. 

![Capture d’écran de 2021-06-15 15-20-54](https://user-images.githubusercontent.com/26329336/122059868-5744c500-cded-11eb-9309-602e9f4e33bf.png)

- > Ca permet de ne pas être obligé de mettre un portail sur toutes les randonnées. 

Et de notre côté on a entendu les 2 :  _si je filtre sur un portail je m'attend a avoir les éléments sans portails et avec le portail_
 mais aussi : pourquoi cette randonnée remonte dans mon portail rando ?

**Comment by babastienne** [comment]
Sync_rando est maintenant déprécié, ce ticket ne me semble plus pertinent. Le système de portail a été homogénéisé dans GTR3 et les autres apps :
- Le brique appelant GTA (ca peut-être un GTR3, un widget, ou autre), choisi si elle veut filtrer les contenus par portail ou non.
- S'il y a un filtre par portail alors seuls les contenus associés à ce portail sont remontés
- Dans le cas où aucun filtre n'est posé, tous les contenus sont remontés sans distinction.
