### ISSUE TITLE
Nom de fichiers dans les légendes des images venant d'Apidae

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#2698]
Il faudrait adapter la fonction suivante pour compenser la présence occasionelle de noms de fichiers dans les données retournées par Apidae:

https://github.com/GeotrekCE/Geotrek-admin/blob/9e8165755cdb447289f0ae3492d7590157f80570/geotrek/tourism/parsers.py#L373

Cette fonction doit renvoyer dans l'ordre  `url, legend, author`, en l'état elle renvoie `url, name, None` 
https://github.com/GeotrekCE/Geotrek-admin/blob/9e8165755cdb447289f0ae3492d7590157f80570/geotrek/common/parsers.py#L628

Le problème est que le champ "nom.libelleFr" ne contient pas toujours des légendes d'image mais des fois des noms de fichiers.
Conséquence : on trouve parfois des noms comme "13GIT009620_1_WEB.jpg" en légende des images.

Dans l'idéal il faudrait plutôt utiliser le champ champ "legende.libelleFr" en tant que légende, MAIS il n'est pas toujours présent.

Il faudrait donc récupérer le champ `legende.libelleFr ` quand il existe, et sinon utiliser le champ `nom.libelleFr ` SEULEMENT si sa valeur ne finis pas par ".jpg" ou ".png" etc.

Pseudocode d'amélioration à tester 
```
    def filter_attachments(self, src, val):
        result = []   
        for subval in val or []:         
            if 'legende' in subval:
                legend = subval['legende'].get('libelleFr')
            else:
                legend = None

            if 'nom' in subval:
                name = subval['nom'].get('libelleFr')
            else:
                name = None

            if legend and (legend[:4] == ".jpg" or legend[:4]) == ".png":
               legend = None

            if legend is None:
               legend = name
            result.append((subval['traductionFichiers'][0]['url'], legend, name))
        return result
```

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.83.0, en même temps que des améliorations de la récupérations des images depuis Apidae et de la récupération de l'auteur.

Testé et ça fonctionne bien : 
![Capture d’écran de 2022-06-01 18-16-04](https://user-images.githubusercontent.com/4418840/171452563-45065cda-7360-47bc-973f-c7f909c09399.png)
