### ISSUE TITLE
API v2 / Filtre in_bbox

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2700]
La route /trek dispose d'un filtre ``in_bbox``.
On souhaiterait utiliser celui-ci dans Geotrek-rando v3.
Mais en le testant, il semble que ce filtre n'a pas d'effet.
Il a un soucis ?

Idem sur la route /touristiccontent ?

**Comment by submarcos** [comment]
C'est le meme problème qu'il y avait sur le filtre distance to point. Il avait été mis en place sans jamais avoir été fonctionnel.
Je suis en train de fixer, par contre ce filtre à deux options : overlapping ou contains. C'est à dire que l'on doit définir si ce filtre bbox ne doit garder que les éléments à l'intérieur exclusivement de la bbox ou tous les éléments qui traversent la bbox. tu as une préférence ?

**Comment by camillemonchicourt** [comment]
Oui OK, en voyant ça, j'ai pensé au soucis de "DistanceToPoint".
Je pense qu'il vaut mieux prendre tous les éléments qui traversent la bbox, pas uniquement ceux qui sont exclusivement dedans.
Merci.

**Comment by submarcos** [comment]
fixé dans la 2.61.1
