### ISSUE TITLE
API v2 - Problème de filtre par difficulté / Utilise les cirkwi_level

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2702]
J'ai 4 niveaux de difficulté : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek_difficulty/
- 56 randos très faciles
- 94 randos faciles
- 113 randos moyennes
- 91 randos difficiles

L'API renvoie bien les 56 randos très faciles : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Cdifficulty&difficulty_min=1&difficulty_max=1&page=1&page_size=150
Mais pas les randos faciles : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Cdifficulty&difficulty_min=2&difficulty_max=2&page=1&page_size=150

Si je ne demande que les très faciles et faciles, elle ne renvoie aussi que les très faciles : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Cdifficulty&difficulty_min=1&difficulty_max=2&page=1&page_size=150

Si je demande les très faciles, faciles et moyennes, elle ne renvoie que les très faciles et faciles : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Cdifficulty&difficulty_min=1&difficulty_max=3&page=1&page_size=150

En creusant je me suis demandé si l'API n'utilisait pas les cirkwi_level à la place des id.
Et en interrogeant les difficultés de niveau 7, cela se confirme : https://geotrek-admin.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Cdifficulty&difficulty_min=7&difficulty_max=7&page=1&page_size=150

Je n'ai pas de difficulté ayant un id=7, mais ma difficulté difficile (id=4) a le cirkwi_level=7

**Comment by submarcos** [comment]
effectivement c'est bien l'id cirkwi qui est utilisé pour le filtre (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/api/v2/filters.py#L339)

**Comment by Chatewgne** [comment]
PR fix et tests https://github.com/GeotrekCE/Geotrek-admin/pull/2706

**Comment by camillemonchicourt** [comment]
Merci.

**Comment by Chatewgne** [comment]
PR mergée

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.62.0. Merci.
