### ISSUE TITLE
Interventions / Fonctions et coûts - Pouvoir les activer/désactiver

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2709]
On peut définir différentes fonctions et leur associer un coût.
On peut ensuite associer du temps/agent par fonction sur des interventions et le coût est calculé automatiquement en multipliant le nombre de jour par fonction à leur coût journalier.

Néanmoins les coûts journaliers d'une même fonction peuvent évoluer dans le temps.
Dans notre cas, on a du décliner les fonctions par agent (ouvrir_2018, ouvrier_2019, ouvrier 2020, technicien_2018, technicien_2019...) car ils ont des coûts différents.

On se retrouve donc avec une liste de fonctions assez longue et pour laquelle on peut saisir des erreurs.

Il est donc souhaité de pouvoir garder ces fonctions des années précédentes car elles ont pu être associées à des interventions des années passées où les coûts journaliers étaient différents, mais de pouvoir les désactiver pour ne plus les lister dans les fonctions lorsque l'on saisit une nouvelle intervention.

- Ajouter un champs booléen ``active`` dans la table des fonctions, à ``true`` par défaut
- Passer à ``true`` par défaut toutes les fonctions existantes dans la BDD lors de la prochaine migration
- Dans l'adminsite, dans la liste des fonctions, afficher la valeur de ce champs
- Pouvoir filtrer les fonctions dans l'Adminsite site elles sont actives ou non
- Quand on créé une nouvelle intervention, ne proposer que les fonctions actives dans la liste déroulante des fonctions
- Quand on modifie une intervention pour laquelle une fonction désormais désactivée était associée, permettre cela sans changer la fonction par une active.  Donc afficher la fonction désactivée utilisée + les fonctions actives

**Comment by Chatewgne** [comment]
PR pour cette fonctionnalité    https://github.com/GeotrekCE/Geotrek-admin/pull/2721

   - [X] Ajouter un champs booléen active dans la table des fonctions, à true par défaut
   
   - [X] Passer à true par défaut toutes les fonctions existantes dans la BDD lors de la prochaine migration
   - [X] Dans l'adminsite, dans la liste des fonctions, afficher la valeur de ce champs
   - [X] Pouvoir filtrer les fonctions dans l'Adminsite site elles sont actives ou non
   - [X] Quand on créé une nouvelle intervention, ne proposer que les fonctions actives dans la liste déroulante des fonctions
   - [ ] Quand on modifie une intervention pour laquelle une fonction désormais désactivée était associée, permettre cela sans changer la fonction par une active. Donc afficher la fonction désactivée utilisée + les fonctions actives
   
   A faire
   - [ ] Analyser l'impact [du bug des formset](https://github.com/GeotrekCE/Geotrek-admin/issues/2693) sur le point ci-dessus
   - [ ] Ecrire des tests

**Comment by Chatewgne** [comment]
mergé

**Comment by camillemonchicourt** [comment]
OK dans la 2.63.0
