### ISSUE TITLE
Aménagements - Ajouter champs Niveau intervention et Niveau usager

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2710]
Il s'agit d'ajouter 2 champs non obligatoires sur les aménagements, tous deux sous forme de liste déroulante, permettant de renseigner le niveau de dangerosité potentielle des interventions sur un aménagement pour les agents qui les réalisent et le niveau de difficulté d’utilisation pour les usagers finaux.

- Niveau des interventions
Info saisie : Niveau de dangerosité potentielle des interventions sur l'aménagement par les agents
- Niveau des usagers
Info saisie : Niveau de dangerosité potentielle de l'aménagements pour les usagers randonneurs

### Typologies par défaut (fixtures) : 

 Niveau des interventions : 
- Niveau 1 : Prudence habituelle mais sans mesures de protection nécessaire
- Niveau 2 : Prudence renforcée avec mesures de protection recommandée mais sans obligation
- Niveau 3 : Mesures de protection obligatoires avec uniquement des agents formés

Niveau des usagers : 
- Niveau 1 : Familial
- Niveau 2 : Randonneurs moyens
- Niveau 3 : Randonneurs sportifs signalétique de prudence au besoin

### A faire : 

- [x] Ajout des typologies administrables dans l'Administe
- [x] Ajout des valeurs proposés par défaut pour ces 2 champs dans les fixtures déployés lors de la prochaine migration
- [x] Saisie des 2 champs dans le formulaire "Aménagement"
- [x] Texte d'aide à la saisie sous le champs
- [x] Ajout de la possibilité de masquer ces champs dans le formulaire et mention dans la documentation liée
- [x] Affichage des champs dans les fiches détail des aménagements et les exports PDF et ODT/DOC
- [x] Ajout des 2 champs en tant que filtre au niveau de la liste des aménagements
- [x] Ajout par défaut de ces 2 champs dans les exports des aménagements (CSV et SHP)
- [x] Ajout de la possibilité d'afficher ou non ces champs dans la liste des aménagements et de les inclure ou non dans les exports CSV et SHP, et mention dans la doc liée

**Comment by Chatewgne** [comment]
PR pour cette fonctionnalité https://github.com/GeotrekCE/Geotrek-admin/pull/2724

**Comment by Chatewgne** [comment]
Afin de favoriser la lisibilité dans les formulaires et dans les exports, je suggère d'utiliser des labels plus cours pour les niveau des interventions, par exemple :

- Prudence habituelle
- Prudence renforcée
- Agents habilités seulement

ou

- Prudence habituelle
- Protection recommandée
- Agents habilités seulement

En l'état actuel les longs labels étendent le widget du formulaire et ne sont plus alignés avec le reste

![image](https://user-images.githubusercontent.com/26015573/125912034-bd2d9690-e378-4bac-947e-25bb42b95e2f.png)

**Comment by camillemonchicourt** [comment]
Oui je suis d'accord avec cela.

Avec le mot "formé" plutôt que "habilité", donc "Agents formés seulement".

Merci

**Comment by camillemonchicourt** [comment]
Non traduits dans l'Adminsite : 

![Capture d’écran de 2021-09-05 23-47-16](https://user-images.githubusercontent.com/4418840/132142339-76df6a7c-bb58-408b-8dc1-2bfd2d544059.png)

Même avec des items de liste courts, les widgets passent sur 2 lignes chez moi : 

![Capture d’écran de 2021-09-05 23-49-50](https://user-images.githubusercontent.com/4418840/132142343-a0b8361b-eb16-484b-bf57-3ede76250600.png)

**Comment by Chatewgne** [comment]
Désolée pour l'oubli des traductions.

Pour les widget c'est la longueur des descriptions en gris clair qui cause cela, je les ai raccourcies :

https://github.com/GeotrekCE/Geotrek-admin/pull/2747

**Comment by camillemonchicourt** [comment]
OK merci.

**Comment by camillemonchicourt** [comment]
OK dans la 2.64.0
