### ISSUE TITLE
Export interventions / Champs "sur" à clarifier pour les tronçons

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2711]
Dans les exports CSV et SHP des interventions, la colonne ``sur`` indique bien si ils ont été fait sur des aménagements ou de la signalétique.
Exemple : "Aménagement: Passerelle des Tourettes (922823)"

Par contre si ils ont été fait sur des tronçons : "Topologie: Topologie (974611) (974611)"

Il faudrait plutôt afficher "Tronçon: Nom du tronçon (id du tronçon)"

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2828

**Comment by camillemonchicourt** [comment]
OK dans la 2.73.0.
Bon si l'intervention est sur plusieurs tronçons, alors cela n'affiche quand même qu'un seul identifiant le tronçon (le premier ?). Donc ce n'est pas tout a fait correct. A voir si on laisse comme ça pour faire simple, ou si il vaut mieux lister tous les tronçons empruntés par l'intervention ?

**Comment by camillemonchicourt** [comment]
OK dans la 2.74.0 où la liste des tronçons est complète.
