### ISSUE TITLE
Interventions / Supprimer onglets du formulaire

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2712]
Le formulaire des interventions est séparé en 2 onglets "Basique" et "Avancé".
C'est pas très explicite, donc on avait initialement penser renommer ces 2 onglets en "Informations" et "Coûts".

Mais ce formulaire n'étant pas très long, on privilégié de le passer sur une seule page, en supprimant son fonctionnement en 2 onglets.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2831

**Comment by camillemonchicourt** [comment]
L'onglet a bien été supprimé dans la 2.73.0, mais il y a un soucis avec le scroll qui est sur toute la page, au lieu d'être seulement sur la partie attributaire comme c'est le cas pour les autres formulaires : 

![Capture d’écran de 2021-12-13 19-49-07](https://user-images.githubusercontent.com/4418840/145870689-b53e35cb-21e2-4be6-9104-8200e801f00e.png)

**Comment by camillemonchicourt** [comment]
OK dans la 2.74.0
