### ISSUE TITLE
Problème d'affichage des résultats au zoom sur la carte

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#2714]
Bonjour, depuis la mise à jour de mon GTA de la v2.57.0 vers la v2.61.1, j'ai un problème d'affichage des données sur la carte et dans la liste de résultats : 
- ouverture de la page d'un module -> les objets sont bien affichés sur la carte et dans la liste de résultats
- je zoom d'une valeur - > une parties des objets de la carte disparaissent, et par la même disparaissent aussi de la liste de résultats et ne sont donc plus accessibles.
- j'actualise la page -> les données réapparaissent
- je zoom d'une valeur -> les données disparaissent à nouveau
- etc.

La console du nav ne me renvoi pas d'erreur particulière si ce n'est ceci : 
```
DevTools failed to load source map: Could not load content for https://myadmin.com/static/CACHE/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
87[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
jquery-1.9.1.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Coté log des erreurs de HostHeader et pas grand chose de convaincant (``sudo journalctl -eu geotrek-ui``) :
```
Jul 08 09:15:46 vps650123 gunicorn[1298608]: ERROR 2021-07-08 09:15:46,594 django.security.DisallowedHost Invalid HTTP_HOST header: '217.182.253.79:443'. You may need to add '217.182.254.69>
Jul 08 09:15:46 vps650123 gunicorn[1298591]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As >
Jul 08 09:15:46 vps650123 gunicorn[1298591]:   post_compress = django.dispatch.Signal(providing_args=['type', 'mode', 'context'])
Jul 08 09:15:46 vps650123 gunicorn[1298591]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/parser/default_htmlparser.py:77: RemovedInDjango40Warning: smart_text() is deprecated >
Jul 08 09:15:46 vps650123 gunicorn[1298591]:   return smart_text(elem['text'])
Jul 08 09:15:46 vps650123 gunicorn[1298591]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/cache.py:29: RemovedInDjango40Warning: force_text() is deprecated in favor of force_st>
Jul 08 09:15:46 vps650123 gunicorn[1298591]:   return 'django_compressor.%s' % force_text(key)
Jul 08 09:15:46 vps650123 gunicorn[1298591]: ERROR 2021-07-08 09:15:46,722 django.security.DisallowedHost Invalid HTTP_HOST header: '217.182.253.79:443'. You may need to add '217.182.254.69>
Jul 08 09:34:13 vps650123 gunicorn[1298612]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As >
Jul 08 09:34:13 vps650123 gunicorn[1298612]:   post_compress = django.dispatch.Signal(providing_args=['type', 'mode', 'context'])
Jul 08 09:34:13 vps650123 gunicorn[1298612]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/parser/default_htmlparser.py:77: RemovedInDjango40Warning: smart_text() is deprecated >
Jul 08 09:34:13 vps650123 gunicorn[1298612]:   return smart_text(elem['text'])
Jul 08 09:34:13 vps650123 gunicorn[1298612]: /opt/geotrek-admin/lib/python3.8/site-packages/compressor/cache.py:29: RemovedInDjango40Warning: force_text() is deprecated in favor of force_st>
Jul 08 09:34:13 vps650123 gunicorn[1298612]:   return 'django_compressor.%s' % force_text(key)
Jul 08 09:34:13 vps650123 gunicorn[1298612]: ERROR 2021-07-08 09:34:13,862 django.security.DisallowedHost Invalid HTTP_HOST header: '217.182.253.79'. You may need to add '217.182.254.69' to>
~
```

![Itinéraires-Geotrek (3)](https://user-images.githubusercontent.com/33653562/124886576-ab019300-dfd4-11eb-8e9f-8e4661553312.jpg)
![Itinéraires-Geotrek (2)](https://user-images.githubusercontent.com/33653562/124886608-b3f26480-dfd4-11eb-8b1d-f56382939b97.jpg)

Quelqu'un aurait-il des pistes ? Merci !

**Comment by camillemonchicourt** [comment]
Ça ressemble aussi un peu au soucis que l'on a eu sur l'affichage des interventions (https://github.com/GeotrekCE/Geotrek-admin/issues/2557) mais là c'était le filtre avec la BBOX qui avait un soucis et la liste se vidait en même temps, ce qui ne semble pas être le cas ici.

Donc c'est peut-être plutôt un soucis de géométries de certaines randos qui ne s'afficherait donc pas à certains niveaux de zoom ?

**Comment by JeanLenormand** [comment]
Bonjour, je reviens sur ce post car maintenant la carte est grisée et aucune donnée ne s'affiche dans la liste de résultats. 
Le GTA a été mis à jour vers la version 2.62.0, ce qui n'a rien changé.
La console du navigateur me renvoie l'erreur suivante :
GET https://admin.viacolumbani.com/api/settings.json?callback=window.SETTINGS%3D net::ERR_ABORTED 502 (Bad Gateway)

Si quelqu'un a une piste je suis preneur.

Merci.

**Comment by JeanLenormand** [comment]
Je viens de régénérer les geom 3d en lançant la commande suivante : 
sudo -u postgres psql -d mydb -c "UPDATE core_path SET geom=geom;"

J'ai eu en retour le message d'erreur suivant : 
ERREUR:  line_interpolate_point: 3rd arg isn't within [0,1]CONTEXTE : fonction PL/pgSQL paths_topology_intersect_split(), ligne 167 à affectation

Sauf erreur de ma part, j'en déduis que j'ai des erreurs de tronçons.

Y'aurait-il un moyen d'identifier les tronçons qui posent problème ?

**Comment by JeanLenormand** [comment]
Le problème a disparu après avoir mis à jour GTA de la v2.62.0 vers la v2.64.0
Difficile d'expliquer le pourquoi du comment, peut-être la migration de la bdd lors de la maj ...
