### ISSUE TITLE
API v2 / Ajouter les évènements touristiques

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2718]
Ajouter les évenements touristiques à l'API V2 : 

- Ajouter la route générale /touristicevent avec ses différents champs et filtres (incluant la possibilité de filtre par date_min et/ou date_max)
- Ajouter la route des types d’événements /touristicevent_type
- Filtrer leurs typologies liées en fonction des objets publiés et non supprimés, pouvoir filtrer leurs typologies par portail, et ajouter leurs objets pour vérifier les thèmes à lister (voir https://github.com/GeotrekCE/Geotrek-admin/issues/2514)
- Inclure les filtres "near_trek", "near_touristiccontent" et "near_touristicevent"

**Comment by Chatewgne** [comment]
Reprise des développements sur la branche `dev_api_v2` - PR https://github.com/GeotrekCE/Geotrek-admin/pull/2733

- [X] Ajouter la route générale /touristicevent avec ses différents champs et filtres 
- [ ] inclure la possibilité de filtre par date_min et/ou date_max)
- [X] Ajouter la route des types d’événements /touristicevent_type
- [ ]  Filtrer leurs typologies liées en fonction des objets publiés et non supprimés 
- [ ] pouvoir filtrer leurs typologies par portail
- [ ] ajouter leurs objets pour vérifier les thèmes à lister (voir
API V2 - Typologies selon le contenu et par portail #2514)
- [ ] Inclure les filtres "near_trek",
- [ ] "near_touristiccontent" et 
- [ ] "near_touristicevent"
- [ ] écrire les tests correspondants

**Comment by Chatewgne** [comment]
PR mergée
