### ISSUE TITLE
API v2 / Généraliser les filtres "near"

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2719]
Actuellement on ne peut filtrer dans l'API que les contenus touristiques à proximité d'une rando. On aurait besoin de généraliser ces filtres et de les étendre aux contenus et événements touristiques, ainsi qu'aux sites et parcours Outdoor.

Inclure les filtres "near_trek", "near_touristiccontent" et "near_touristicevent" sur les routes /trek, /touristiccontent, /outdoor_site, /outdoor_course et /touristicevent (à venir - https://github.com/GeotrekCE/Geotrek-admin/issues/2718).

De la même manière, ajouter les filtres "near_outdoorsite" et "near_outdoorcourse" dans toutes les routes renvoyant des objets.

**Comment by Chatewgne** [comment]
"near_trek", "near_touristiccontent" et "near_touristicevent"
 - [ ] /trek, 
- [ ] /touristiccontent, 
- [ ] /outdoor_site, 
- [ ] /outdoor_course et 
- [ ] /touristicevent

"near_outdoorsite" et "near_outdoorcourse"
- à lister

**Comment by camillemonchicourt** [comment]
OK dans la 2.63.0
- https://geotrekdemo.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Cname%2Ccreate_datetime%2Cupdate_datetime&near_outdoorsite=50
- https://geotrekdemo.ecrins-parcnational.fr/api/v2/touristiccontent/?near_outdoorsite=50
- https://geotrekdemo.ecrins-parcnational.fr/api/v2/outdoor_site/?omit=geometry&near_touristiccontent=194
