### ISSUE TITLE
API v2 - Ajouter route des services

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2720]
Ajouter la route des services. Si possible en profiter pour anticiper le renommage du module (https://github.com/GeotrekCE/Geotrek-admin/issues/1475) en nommant la route /route_info, car /service porte à confusion avec d'autres objets.

Ajouter le route associée des types.

Ajouter aussi le filtres par type, bbox, near_trek.

**Comment by Chatewgne** [comment]
PR: https://github.com/GeotrekCE/Geotrek-admin/pull/2742

**Comment by camillemonchicourt** [comment]
OK dans la 2.63.0 : https://geotrekdemo.ecrins-parcnational.fr/api/v2/service/
Avec les filtres associés : https://geotrekdemo.ecrins-parcnational.fr/api/v2/service/?near_trek=501&types=2
