### ISSUE TITLE
Synchro - Erreurs sur la génération de PDF et PNG profil

### ISSUE THREAD

**Issue by CGuillaume** [GeotrekCE/Geotrek-admin#2734]
Bonjour à tous,

Depuis quelques jours, après des modifications sur nos itinéraires et POI, j'ai des erreurs qui remontent lors de la synchro que je n'arrive pas à résoudre.

**1 - Sur la génération de PDF**

Sur plusieurs itinéraires qui existaient déjà et sur lesquels il n'y avait pas d'erreur, j'ai ce message qui remonte.
Ce que j'ai a touché à ce niveau : 
- J'avais créé et publié un POI de test à proximité de ces itinéraires que j'ai supprimer depuis geotrek-admin.
   --> Je me dis que le **empty content** peut venir d'une liaison c'est mal supprimé et traine quelque part...
- On a aussi déplacer certains POI pour les "accrocher" aux tronçons.

J'ai vu un post de Camille qui y ressemble mais ça ne m'a pas trop aidé...

```
fr api/fr/treks/118/la-grande-boucle-des-lacs-danterne-et-de-pormenaz.pdf ...ERROR 2021-08-20 10:13:18,372 mapentity.helpers Request on http://127.0.0.1:8001/?url=http%3A//localhost/trek/118/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%25201128%252C%2520%2522height%2522%253A%25201128.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Plan%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content
Traceback (most recent call last):
  File "/home/geotrek/Geotrek-admin/lib/eggs/mapentity-6.0.5-py3.6.egg/mapentity/helpers.py", line 162, in download_to_stream
    source = get_source(url, headers)
  File "/home/geotrek/Geotrek-admin/lib/eggs/mapentity-6.0.5-py3.6.egg/mapentity/helpers.py", line 150, in get_source
    assert len(source.content) > 0, content_error
AssertionError: Request on http://127.0.0.1:8001/?url=http%3A//localhost/trek/118/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%25201128%252C%2520%2522height%2522%253A%25201128.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522IGN%2520Plan%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content
failed (string index out of range)
```

**2 - Sur la génération d'un PNG de profil**

Là c'est sur un nouvel itinéraire que je n'ai pas créé moi. Du coup j'ai tenté de refaire les tronçons et le tracé de l'itinéraire mais ça ne change rien. J'hésite à tout supprimer pour refaire. Bonne ou mauvaise idée ?

```
fr api/fr/treks/834/profile.png ...ERROR 2021-08-20 10:15:59,509 mapentity.helpers Request on http://127.0.0.1:6543/?url=http%3A//localhost/api/fr/treks/834/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=404)
Traceback (most recent call last):
  File "/home/geotrek/Geotrek-admin/lib/eggs/mapentity-6.0.5-py3.6.egg/mapentity/helpers.py", line 162, in download_to_stream
    source = get_source(url, headers)
  File "/home/geotrek/Geotrek-admin/lib/eggs/mapentity-6.0.5-py3.6.egg/mapentity/helpers.py", line 147, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://127.0.0.1:6543/?url=http%3A//localhost/api/fr/treks/834/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=404)
failed (string index out of range)
```
La dernière est un peu plus bloquante puisqu'elle empêche la synchro mobile de se terminer et donc d'ajouter de nouveaux itinéraire sur l'appli mobile...

Merci d'avance pour votre aide.
Version geotrek-admin : 2.32.2 (je tente les maj une fois ces erreurs résolues...)

**Comment by camillemonchicourt** [comment]
Il y a eu pas mal de choses corrigées depuis donc il est possible qu'une mise à jour règle cela ?

**Comment by CGuillaume** [comment]
Ok je tente de faire des mises à jour lundi. Vu que ça fonctionnait avant je ne voulais pas les faire avant de résoudre le soucis.
Merci

**Comment by CGuillaume** [comment]
Salut,

Après màj les erreurs n’étaient pas résolues du coup j’ai un peu fouiller dans les issues et en fait c’était le même souci que #2662.

Tout est rentré dans l’ordre en en plus j’ai un geotrek-admin à jour !
