### ISSUE TITLE
Public PDF export / Max height size for maps

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2746]
La carte exportée et intégrée dans l'export PDF public est parfois trop haute pour rentrer dans sa page avec le titre "Sur votre chemin", et bascule donc sur la page suivante, créant une page vide.
Exemple de cette rando : https://siglr-geotrek-pnrgca.ataraxie.fr/api/fr/treks/50209/trail-n4-creissels-le-larzac.pdf
Ce n'est pas le cas sur cette autre rando, qui est pourtant plus grande et mieux centrée : https://siglr-geotrek-pnrgca.ataraxie.fr/api/fr/treks/50221/trail-n7-la-cresse-le-causse-de-sauveterre.pdf

A voir si on peut définir un ratio maximum pour que la carte ne soit pas trop rectangulaire, ou une hauteur minimum pour la carte ?

**Comment by JoelAtche** [comment]
Le problème est de plus en plus présent de façon aléatoire, et c'est pour nous une forte contrainte qui oblige à modifier les PDF avant de les imprimer au format livré dans le point d'accueil touristique!
Je me demande si d'autres utilisateurs de Geotrek ont se problème?

**Comment by JoelAtche** [comment]
Pour exemple, voici un début de liste des fiches qui présentent le décalage avec 
-	la carte est en page 3 et la liste des pois qui sont en principe sous la carte basculent en page 4 
ou alors
-	 la carte est en page 4, et la liste des pois en page 5
- 
Ce n'est que un échantillon sur une partie du territoire fourni par un OT:
RANDONNEES PEDESTRES
-	A LA DÉCOUVERTE DU LARZAC À PIED : https://siglr-geotrek-pnrgca.ataraxie.fr/api/fr/treks/6106/a-la-decouverte-du-larzac-a-pied.pdf 
-	DE L'HOSPITALET-DU-LARZAC AU VIALA-DU PAS-DE-JAUX À PIED : de-lhospitalet-du-larzac-au-viala-du-pas-de-jaux-a-pied.pdf (ataraxie.fr) 
-	DE CORNUS À LA COUVERTOIRADE À PIED de-cornus-a-la-couvertoirade-a-pied.pdf (ataraxie.fr) 
-	ENTRE CAUSSE DU LARZAC ET VALLÉE DE LA DOURBIE (carte décalée en page 4) entre-causse-du-larzac-et-vallee-de-la-dourbie.pdf (ataraxie.fr)
-	DE LA COUVERTOIRADE À LA CAVALERIE (carte décalée en page 4) de-la-couvertoirade-a-la-cavalerie.pdf (ataraxie.fr)
-	DE LAPANOUSE A ST- EULALIE de-lapanouse-a-sainte-eulalie-de-cernon.pdf (ataraxie.fr) 
-	AUTOUR DE LA COUVERTOIRADE (CARTE DECALEE EN PAGE 4) autour-de-la-couvertoirade.pdf (ataraxie.fr) 
-	LES CANOLES PAR LA SOURCE DU DURZON les-canoles-par-la-source-du-durzon.pdf (ataraxie.fr)
-	ALGUES PAR FOUGAYROLLES algues-par-fougayrolles.pdf (ataraxie.fr) 
-	CIRCUIT DE ST-JEAN-D'ALCAS circuit-de-st-jean-dalcas.pdf (ataraxie.fr)
-	DE ST-JEAN D'ALCAS AU PLATEAU DE MASCOURBE de-st-jean-dalcas-au-plateau-de-mascourbe.pdf (ataraxie.fr) 
TRAIL :
-	CIRCUIT DES MAQUISARDS (N°15) trail-n15-circuit-des-maquisards.pdf (ataraxie.fr) 
-	ST-GUIRAL VERTICAL N°22 trail-n22-st-guiral-vertical.pdf (ataraxie.fr)
-	ST-GUIRAL CIRCUS  N°20 trail-n20-st-guiral-circus.pdf (ataraxie.fr) 
VTT : 
-	LES FALAISES DU GUILHAUMARD vtt-n12-les-falaises-du-guilhaumard.pdf (ataraxie.fr)
-	DE LA BARAQUE FROIDE A LA BLAQUERERIE N°14 vtt-n14-de-la-baraque-froide-a-la-blaquererie.pdf (ataraxie.fr) 
-	DE LA BARAQUE FROIDE A FONTVIVE N°15 : vtt-n15-de-la-baraque-froide-a-fontvive.pdf (ataraxie.fr) 
-	DE LA DOURBIE AU CAUSSE DU LARZAC N°16  vtt-n16-de-la-dourbie-au-causse-du-larzac.pdf (ataraxie.fr)

**Comment by JoelAtche** [comment]
Je vais solliciter le support Geotrek chez Makina Corpus pour travailler sur le sujet en finançant le travail nécessaire.

**Comment by LePetitTim** [comment]
Explication du problème : Generation of pdfs and maps : #2844

**Comment by camillemonchicourt** [comment]
Retour de @LePetitTim : 

> Une modification a été faite sur Geotrek-admin, plus particulièrement sur django-mapentity qui a supprimé un caractère caché dans la page d'accueil causant parfois un scroll de la carte, pouvant causer une carte trop grande qui déborde dans les pdfs.
> La version qui supprime le caractère est Geotrek-admin 2.74.1.

-------------------------------------------------

Le problème semble réglé suite au passage à la version 2.75.0 de Geotrek-admin : https://openig-geotrek-pnrgca.ataraxie.fr/api/fr/treks/6106/a-la-decouverte-du-larzac-a-pied.pdf
Tu confirmes @JoelAtche ?

**Comment by JoelAtche** [comment]
Non au contraire je ne confirme pas @camillemonchicourt , le problème est toujours là! Je n'ai pas pu répondre à @LePetitTim avec des exemple car pour le moment j'ai un autre pb sur mes fiches PDF. Mais je vais vous transmettre un mail que j'ai fait d'un autre côté pour illustrer mon propos...

**Comment by camillemonchicourt** [comment]
OK toujours le même soucis chez nous en 2.75.0.
Exemple : https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/920686/aiguilles-de-chabrieres.pdf

**Comment by camillemonchicourt** [comment]
En attendant de trouver comment faire en sorte que les images des cartes soient toujours carrées (https://github.com/GeotrekCE/Geotrek-admin/issues/2844), une solution a été mise en place pour fixer une hauteur maximale des images des cartes dans la page (20cm de haut) : https://github.com/GeotrekCE/Geotrek-admin/pull/3027

Cela permet de s'assurer que la carte sera toujours dans la même page que le titre "Sur votre chemin" en gardant de la place pour afficher une liste de POI sous la carte.

Cela fonctionne sur le PDF A4 (https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/920686/aiguilles-de-chabrieres.pdf) : 
![Capture d’écran de 2022-03-23 13-36-56](https://user-images.githubusercontent.com/4418840/159701622-1494f26f-a6cc-4578-968e-66551ced8d67.png)

Mais aussi sur le PDF livret (https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/920686/aiguilles-de-chabrieres_booklet.pdf) qui s'appuie sur le même template : 
![Capture d’écran de 2022-03-23 13-37-22](https://user-images.githubusercontent.com/4418840/159701655-c503ec74-0bfa-4c90-94d3-cbc0a28faa45.png)

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.79.0.
Le fait que l'image n'est pas toujours carrée reste un sujet, traité dans l'autre ticket dédié.
