### ISSUE TITLE
Objets touristiques dans le pdf d'impression Trek

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#2751]
Nous souhaiterions afficher les objets touristiques liés à un itinéraire dans le PDF d'impression (le PDFaccessible depuis Geotrek-rando, dans la fiche itinéraire).
Les POI sont bien affichés lorsqu'on utilise le template de base mais je n'ai pas trouvé s'il y avait la possibilité d'ajouter les objets touristiques. Est-ce possible?

**Comment by babastienne** [comment]
Bonjour,
En effet les contenus touristiques ne sont pas rattachés aux itinéraires dans les fiches pdf publiques car ces contenus touristiques ont leur propre fiche pdf dédiée.
Si toutefois vous souhaitez pouvoir donner le détail des contenus touristiques sur la fiche pdf d'un itinéraire c'est possible. Pour cela il vous faut surcharger le fichier de template de la fiche pdf d'un itinéraire.
Je vous invite à suivre la procédure disponible sur la documentation Geotrek : https://geotrek.readthedocs.io/en/master/advanced-configuration.html?highlight=pdf#override-public-pdf-templates
