### ISSUE TITLE
Itinéraires / Ajouter des types de cotations dynamiques

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2755]
- Ajouter un mécanisme de cotations par pratique sur les randos, en plus de l'actuel niveau de difficulté, sur la base de ce qui a été fait dans le module Outdoor
- Une pratique peut avoir plusieurs types de cotation ("engagement" et "portage" pour VTT)
- Ajouter un champs texte "Commentaire cotation"

**Comment by camillemonchicourt** [comment]
- Intégrer des typologies et cotations, pour les pratiques VTT, Trail, Alpinisme, pour que tout le monde ait les mêmes par défaut.
- Supprimer la pratique Alpinisme et ses cotations du module Outdoor car on va plutôt les saisir dans Itinéraires.

**Comment by LePetitTim** [comment]
Il faut mettre mle systeme de cotation et niveau de cotation ?

**Comment by camillemonchicourt** [comment]
- Supprimer la pratique "Alpinisme" de Outdoor et la basculer dans Trekking
- Ajouter logo pour pratique "Alpinisme" : https://thenounproject.com/icon/mountain-climbing-45240/
- Basculer les cotations et échelles de cotation de Outdoor vers Rando (https://github.com/GeotrekCE/Geotrek-admin/commit/1cb95430b17661a687cfe59fc79b092a91618f8f#commitcomment-63338329)
- Proposer une commande pour intégrer les fixtures des cotations de rando pour ceux qui ont un Geotrek-admin déjà installé

### RANDO PEDESTRE

- Remplacer le picto par défaut par : https://geotrek-admin.ecrins-parcnational.fr/media/upload/picto-pedestre_2_aJzXGXX.svg

EFFORT :
- 1 - Facile
- 2 - Assez facile
- 3 - Peu difficile
- 4 - Assez difficile
- 5 - Difficile

TECHNICITE : 
- 1 - Facile
- 2 - Assez facile
- 3 - Peu difficile
- 4 - Assez difficile
- 5 - Difficile

RISQUE
- 1 - Faible
- 2 - Assez Faible
- 3 - Peu Elevé
- 4 - Assez élevé
- 5 - Elevé

### VTT

Remplacer le picto par défaut par https://geotrek-admin.ecrins-parcnational.fr/media/upload/pratique-vtt.svg

TYPE DE VOIE :
- Voie ou piste en stabilisé ou goudron
- Piste en terre ou herbe carrossable
- Sentier monotrace ou voie étroite

TECHNIQUE :
- 1 - Facile
- 2 - Peu difficile
- 3 - Assez difficile
- 4 - Difficile
- 5 - très difficile

### VVTAE

Utiliser l'icone : https://geotrek-admin.ecrins-parcnational.fr/media/upload/picto-vttae_KdahUW5.svg

TYPE DE VOIE :
- Voie ou piste en stabilisé ou goudron
- Piste en terre ou herbe carrossable
- Sentier monotrace ou voie étroite

TECHNIQUE :
- 1 - Facile
- 2 - Peu difficile
- 3 - Assez difficile
- 4 - Difficile
- 5 - très difficile

### TRAIL

Ajouter cette pratique par défaut, avec ce picto : https://geotrek-admin.ecrins-parcnational.fr/media/upload/picto-trail.svg

Pas de cotation par défaut pour le TRAIL

### VELO

PENTE : 
- 1 - 3 à 5 %
- 2 - 5 à 7 %
- 3 - 8 à 9 %
- 4 - > ou = 10 %

### EQUESTRE

RAS - On garde le picto actuel, il n'y a pas de cotation qui fasse référence au niveau de la fédération.

**Comment by camillemonchicourt** [comment]
Ces nouveaux champs ont été intégrés dans la version 2.76.0.

Il est désormais possible d'ajouter une plusieurs cotations spécifiques à chaque pratique. 
Si des échelles de cotation sont associées à la pratique, quand on renseigne la pratique d'une randonnée dans le formulaire, les échelles de cotation sont alors proposés dynamiquement à la saisie : 

![Capture d’écran de 2022-02-03 15-27-27](https://user-images.githubusercontent.com/4418840/152362286-bcae19b6-d8df-4dbb-8e89-ee5991620e5e.png)

Mes retours de tests : 

- Les cotations sont en multiselect... Ils devraient être un 1-n. Une seule valeur de cotation par échelle de cotation et par itinéraire
- Le champs "Description des cotations" est très lié à ces cotations, donc je pense qu'il faut le mettre juste en dessous du champs avec les différentes cotations dynamiques.
- Pour bien le dissocier et car il est plus global, je basculerai le champs "Difficulté" juste avant le champs "Pratique" et je laisserai bien les échelles de cotation sous la "Pratique"
- Fixtures (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/fixtures/basic.json#L408-L1462) / Possible de les séparer dans un fichier dédié ? Pour pouvoir les intégrer si on met à jour Geotrek-admin.
- Dans les exports, les cotations sont mises les unes après les autres, dans un seul champs. Comme il peuvent être différent selon la pratique, c'est une solution simple et qui permet d'avoir la cohérence peu importe les pratiques. La limite est que l'on ne peut pas les filtrer facilement. Pas très grave. Par contre on a la valeur de la cotation, mais on ne sait pas à quelle échelle elle correspond, donc ça c'est plus gênant car c'est peu utilisable, même si je vois pas de solution idéale. Ou alors afficher dans ce champs "Nom-Echelle-1 : Nom-Cotation-2 / Nom-Echelle-3- : Nom-Cotation-18". A noter aussi que le champs est nommé "ratings" dans les exports, au lieu de "Cotations"
- Dans les valeurs par défaut fournies dans les fixtures, laisser les chiffres devant chaque label comme défini plus haut ("1 - Facile"). A confirmer.

Doublon identifié dans les fixtures : 
{
    "model": "trekking.ratingscale",
    "pk": 7,
    "fields": {
      "name": "Technique",
      "name_fr": "Technique",
      "name_en": null,
      "order": 2,
      "practice": 1
    }
  },
  {
    "model": "trekking.ratingscale",
    "pk": 7,
    "fields": {
      "name": "Technique",
      "name_fr": "Technique",
      "name_en": null,
      "order": 2,
      "practice": 1
    }
  },

**Comment by camillemonchicourt** [comment]
- [ ] Dans la fiche détail d'une randonnée, le champs "Description de cotation" n'est pas affiché

**Comment by camillemonchicourt** [comment]
👍 OK les retours ont été intégrés dans la version 2.76.4 et fait au niveau des sites et parcours Outdoor en même temps.

⚠️ En complément j'ai identifié ce dernier soucis : Le champs "Description de cotations" n'est pas présent dans les exports des itinéraires ni des parcours Outdoor.

🧐 Pour l'affichage et l'ordre des champs dans les formulaires et les fiches détails, il y aurait potentiellement une réorganisation globale à faire pour plus d'homogénéité et de cohérence, mais à voir dans un ticket dédié et plus global.

**Comment by camillemonchicourt** [comment]
Dernier retour OK dans la 2.77.
