### ISSUE TITLE
Erreur Synchro mobile : No such file or directory

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2758]
Bonjour,

Geotrek-admin : 2.62.0

On s'est rendu compte que depuis plus d'un mois la synchronisation mobile ne fonctionnait plus. Voici le message d'erreur : 
FileNotFoundError: [Errno 2] No such file or directory: '/opt/geotrek-admin/var/media/upload/23E2EA48.png'

Le message d'erreur complet :
[error.log](https://github.com/GeotrekCE/Geotrek-admin/files/7154814/error.log)

Je comprends bien le message d'erreur, mais je m'aperçois que la synchronisation veut à tout prix charger un fichier qui n'existe pas dans le /opt/geotrek-admin/var/media/upload/ . Il a d'ailleurs un nom bien particulier, comme s'il i lavait été modifié ou ré-enregistré. Comment faire pour supprimer son appel par la synchro ?

**Comment by camillemonchicourt** [comment]
Je pense qu'il faut que tu regardes dans ta BDD, notamment dans la table ``common_attachment``à quoi correspond cet objet et à quel objet il est rattaché.
Une fois qu'il sera supprimé de cette table (si il n'a plus lieu d'y être) la synchro ne cherchera plus ce fichier à priori supprimé su serveur.

On peut aussi retrouver les fichiers attachés dans l'Adminsite (URL-GEOTREK-ADMIN/admin/common/attachment/)

**Comment by mviadere-openig** [comment]
Le problème a été contourné en prenant une image quelconque , en la renommant et en al mettant dans /opt/geotrek-admin/var/media/upload/

Je sais bien que ce n'est pas une résolution de bug mais je clos l'issue.
