### ISSUE TITLE
Cotation des sites : Remplacer min/max par une liste multiple des cotations disponibles sur le site

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#2759]

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2760

**Comment by camillemonchicourt** [comment]
OK merci. On pourra donc désormais associer une ou plusieurs cotations à chaque site.
Est-ce que la migration gère les éventuelles cotations min et max déjà saisies ?

**Comment by Chatewgne** [comment]
Oui, je fait en sorte de migrer les anciennes valeurs vers le nouveau champ `ratings`

**Comment by camillemonchicourt** [comment]
OK dans la 2.65.0 pour le passage en champs multiple.
Par contre je n'ai plus de cotation sur les quelques sites où j'ai vérifié, donc ce n'a pas été migré.
Pas très grave car je comprends que cela soit complexe. 
On va voir pour les ressaisir.
Mais à vérifier si l'échec de la migration des cotations des sites n'a pas eu d'effet de bord ?

**Comment by Chatewgne** [comment]
Mince, je suis désolée pour les cotations (et déçue) je pensais avoir correctement prévu le coup
Effectivement c'est une procédure un peu délicate
Non il n'y aura pas d'effet de bord, au contraire j'avais rajouté une ligne de vérification pour éviter que la migration cause des exceptions, mais cette vérification n'était pas compatible avec la deuxième étape de la copie ce qui l'a annulé...
