### ISSUE TITLE
Sites / Pouvoir exclure des POI, comme on a pour les randos

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2763]

**Comment by camillemonchicourt** [comment]
OK dans la 2.65.0 au niveau de l'API qui ne renvoie par les POI exclus d'un site.
Par contre dans la fiche d'un site, dans la bloc POI, on ne doit pas afficher les POI qui sont exclus. Cela fonctionne déjà dans les fiches des randos où on ne liste pas les POI exclus.
Idem sur la fiche des parcours.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2770/files

**Comment by camillemonchicourt** [comment]
OK dans la 2.66.0.
