### ISSUE TITLE
API v2 trek : Le filtrage sur les étiquettes ne fonctionne pas

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2764]
Cette requête ne retourne rien : https://geotrek.cotesdarmor.fr/api/v2/trek/?fields=id%2Cupdate_datetime%2Curl%2Clabels&labels=1%2C2%2C3%2C4

Alors que l'application retourne 515 itinéraires

**Comment by camillemonchicourt** [comment]
En effet bien vu sur ton Geotrek-admin en version 2.62.0.

https://geotrek.cotesdarmor.fr/api/v2/trek/?fields=id%2Curl%2Clabels&page=1&page_size=1 renvoie bien 522 itinéraires et on voit que plusieurs ont bien des étiquettes
Dès qu'on passe un label en filtre, l'API ne renvoie plus rien : https://geotrek.cotesdarmor.fr/api/v2/trek/?fields=id%2Curl%2Clabels&labels=1&page=1&page_size=1

J'ai testé sur notre serveur de DEMO en 2.65.0 et là quand je filtre sur le label 1, ça me renvoie quand même des itinéraires mais dont certains n'ont pas l'étiquette filtrée (https://geotrekdemo.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Clabels&labels=1&page=1&page_size=20)
En filtrant sur l'étiquette 2, cela ne me renvoie qu'une seule rando qui n'a pas cette étiquette associée : https://geotrekdemo.ecrins-parcnational.fr/api/v2/trek/?fields=id%2Clabels&labels=2&page=1&page_size=20

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.77.
En même temps les filtres par étiquette ont été ajoutés sur les sites Outdoor.
