### ISSUE TITLE
Pouvoir filtrer par zonage et par seulement par type de zonage

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2766]
Actuellement on peut filtrer les contenus sur une commune précise, sur un secteur précis ou sur un type de zonage réglementaire :

![Capture d’écran de 2021-09-22 17-22-20](https://user-images.githubusercontent.com/4418840/134372898-0e49ed76-cbc7-4c8d-a9df-653a03e5cb0a.png)

Il serait utile de pouvoir filtrer en plus sur un zonage réglementaire précis.

Donc renommer le filtre "Zonage réglementaire" en "Type de zonage" et rajouter en dessous un filtre "Zonage".
Si aucun type de zonage n'est sélectionné, cette liste affiche tous les zonages (avec leur type entre parenthèse). Et idéalement si un type de zonage est sélectionné, alors limiter la liste des zonages au type de zonage sélectionné.

En profiter pour lister les "Types de zonages" par ordre alphabétique.
Et se pose aussi la question de renommer globalement ce champs "zonage réglementaire" en "zonage" car on l'utilise déjà pour y mettre les forêts domaniales et communales, les communautés de communes...
Le terme "réglementaire" est donc trop restrictif.

**Comment by JonathanALLAIN** [comment]
Salut à tous,

Tout à fait ok avec cette évolution des requêtes spatiales ou attributaires dans geotrek-admin. Il s'agit là donc plutôt de requêtes spatiales de type zonage intersectant des éléments dans les modules de Geotrek-admin (je veux les itinéraires dans telle forêt domaniale...). Aujourd'hui sur ma version 2.38.3 je n'ai que les filtres "communes" et "secteurs" dispos et pas les zonages... Avez-vous ce même souci ?

Enlever le terme "réglementaire" et renommer les tables "Type de zonage" et "zonage" est pertinent. 

Si je comprends bien cela ferait donc deux filtres de plus pour ma part : 
- type de zonage
- zonage
Le premier conditionnant le second.

Pour le moment je me sers de "secteurs" pour les Communautés de Communes.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2846
- Zonage réglementaire -> Zonage
- Type de zonage réglementaire -> Type de zonage
- Filter par Zonage
- Filter les propositions de Zonage dans le sélecteur par les Type de zonage sélectionnés
- Bug fix sur une exception causée en filtrant par plusieurs types de zonage

**Comment by camillemonchicourt** [comment]
OK dans la 2.73.0, les zonages s'affichent bien dans les filtres et leur liste est filtrée si on choisit un type de zonage.
Les filtres fonctionnent bien dans tous les modules, sauf dans le module "Interventions" où la recherche tourne sans fin si je filtre avec un zonage précis.

Dans la console : 
GET https://geotrekdemo.ecrins-parcnational.fr/api/intervention/interventions.json?subcontracting=1&on=&area=31&bbox=POLYGON((5.68267822265625+44.642276976185016%2C5.68267822265625+45.14524196975275%2C6.941986083984375+45.14524196975275%2C6.941986083984375+44.642276976185016%2C5.68267822265625+44.642276976185016)) - 500 (Internal Server Error)

Mais c'est pas forcément nouveau, car même problème quand je filtre sur un "Type de zonage" dans le module Interventions.

Pas pu tester dans le module "Chantiers" cependant car les filtres "Type de zonage" et "Zonage" ne sont pas présents dans ce module.

**Comment by camillemonchicourt** [comment]
OK pour l'ajout des filtres dans le module Chantiers dans la 2.74.0.
Par contre dans la 2.74.0, les filtres par zonage ne fonctionnent toujours pas dans le module Interventions.
Testable sur https://geotrekdemo.ecrins-parcnational.fr/intervention/list/# (admin / admin)

**Comment by camillemonchicourt** [comment]
OK dans la 2.75.0
