### ISSUE TITLE
[INFO] Erreur 500 à la création d'itinéraire : null value in column "published_es" violates not-null constraint (résolu)

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2776]
Version de Geotrek : 2.66.0

Suite à une erreur 500 lors de création d'itinéraire, voici ce que me retourne `sudo journalctl -eu geotrek-ui` :

`django.db.utils.IntegrityError: null value in column "published_es" violates not-null constraint`

J'en déduis que la langue espagnole n'est pas activé sur le Geotrek-admin

un `sudo dpkg-reconfigure geotrek-admin` me confirme bien que c'est uniquement la langue en et fr qui était activé. Après modification, j'ai le même souci pour la langue it.

Il faut donc avoir obligatoirement les 4 langues d'activés sur Geotrek pour éviter cette erreur.

**Comment by camillemonchicourt** [comment]
A creuser, car il n'est pas obligatoire d'activer des langues pour que Geotrek-admin fonctionne, hormis l'anglais de mémoire.
On n'a pas activé l'espagnol sur notre Geotrek-admin et on n'a pas de soucis.

Par contre, à creuser car si on a activé une langue, cela va créer les champs pour la langue dans la BDD, puis si on la désactive, alors là c'est possible que cela entraîne des soucis.

A creuser et préciser.

**Comment by babastienne** [comment]
D'accord avec l'analyse de Camille. Ce genre d'erreur arrive par exemple lorsqu'on restaure une base de données qui contenait une langue d'installée et que la nouvelle configuration ne contient pas cette langue. 

Aujourd'hui il n'est pas possible de désactiver une langue une fois installée. L'erreur indiquant qu'il existe une colonne "published_es" et "published_it" me laisse penser que soit :
- la configuration a été modifiée, les deux langues ont étés installées puis finalement la configuration a été re modifiée pour enlever les langues
- une partie ou toute la base de données a été restaurée depuis une installation précédente où les deux langues étaient configurées

**Comment by mviadere-openig** [comment]
Merci pour vos retours. 


>     la configuration a été modifiée, les deux langues ont étés installées puis finalement la configuration a été re modifiée pour enlever les langues

Honnêtement je ne me souviens pas des manipulations effectuées sur ce serveur, mais il  y a de forte chance que ce soit ça .
