### ISSUE TITLE
Pouvoir associer un parcours à plusieurs sites.

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#2786]
- [x]  BDD + migration des anciennes infos
- [x] Formulaire ajout de sites parents
- [x] Page détail des parcours
- [x] Page liste des parcours
- [x] Re-dynamisation des formulaires de parcours (cotations, types)
- [x] Exports
- [x] Recherche
- [x] API : serialiser 
- [x]  API : filtres par pratique
- [x] Affichage de l'arborescence
- [x] Champs de formulaires customisables
- [x] Colonnes customisables
- [x] Adapter les tests unitaires existant
- [x] Ajouter des tests unitaires

**Comment by babastienne** [comment]
Plusieurs points à lever :
- Quel affichage faire dans la vue arborescente ? 
    - Naif : pour chaque lien site/parent on affiche tout l'arborescence associée
    - Complexe : On detecte si un parcours appartient à plusieurs sites d'une même arborescence et on adapte l'affichage (plus complexe algorithmiquement)
- Recherche ?

**Comment by Chatewgne** [comment]
>     * Quel affichage faire dans la vue arborescente ?
>       
>       * Naif : pour chaque lien site/parent on affiche toute l'arborescence associée
>       * Complexe : On detecte si un parcours appartient à plusieurs sites d'une même arborescence et on adapte l'affichage (plus complexe algorithmiquement)


Le nouvel affichage récursif est facile à adapter pour obtenir l'affichage de toutes les arborescence. Sur la page du parcours concerné, c'est assez lisible :

![image](https://user-images.githubusercontent.com/26015573/136549548-2f0c98e8-3d25-422a-a303-6b9829031271.png)

Par contre sur la page des autres éléments de sa famille, il n'est pas visuellement évident que le même parcours revient plusieurs fois :

![image](https://user-images.githubusercontent.com/26015573/136550043-9727b18e-99d3-468e-924b-38024ed078ff.png)


Si l'on décide de passer sur un affichage plus complexe, il va falloir songer à ne plus utiliser une liste à bulles, mais commencer à tracer des traits entre les élements. En effet, associer un parcours à plusieurs sites change assez drastiquement la structure de données : avant on avait un arbre, maintenant on a un graphe.
