### ISSUE TITLE
Problème CORS / apiv2 / sensitive area

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2792]
Geotrek-admin :  2.67.0 (nouvelle installation)

Si le module sensitive area n'est pas activé, on aura une erreur sur le Geotrek-Rando (V3) lorsqu'on voudra afficher une randonnée. 

voici l'erreur : 

`Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://5.135.42.177/api/v2/sensitivearea_practice?language=fr. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.`

L'api v2 va chercher obligatoirement des données sur les zones sensibles.

Il faut donc, lors d'une nouvelle installation activer le module et ajouter les paramètres (voir ici : https://geotrek.readthedocs.io/en/master/advanced-configuration.html#sensitive-areas)

**Comment by camillemonchicourt** [comment]
Pas d'après mes tests.
Si le module Sensitive area n'est pas activé au niveau de Geotrek-admin, il faut par contre le désactiver au niveau de Geotrek-rando v3 où il est activé par défaut : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/global.json#L6

On pourrait le désactiver par défaut dans Geotrek-rando v3, mais je me suis dit que la plupart l'utiliserait.
En tout cas, ça a été prévu et pas de soucis au niveau de Geotrek-admin.

**Comment by camillemonchicourt** [comment]
Oui c'est plus logique, et c'est ce qui était censé être le cas.
Mais il y avait encore un couac entre la configuration par défaut et la customisation par défaut qui était incohérente.
Ce sera revu dans la prochaine release : https://github.com/GeotrekCE/Geotrek-rando-v3/pull/488

Va se poser la même question avec le module Outdoor, qui n'est pas installé par défaut actuellement dans Geotrek-admin, et pourrait désormais l'être pour l'activer par défaut dans Geotrek-rando v3.
