### ISSUE TITLE
Migration Ubuntu 16 / Geotrek-admin 2.x

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2798]
Voici un retour de méthode pour migrer un Geotrek-admin sur un vieux serveur (Ubuntu 16) et dans une vieille version (2.2x).

Le principe initial est de disposer d'un Geotrek-admin fonctionnel inférieur à la 2.32 sur un OS récent (https://geotrek.readthedocs.io/en/master/installation.html#from-geotrek-admin-2-32).
La difficulté désormais peut être d'installer un Geotrek-admin inférieur à la 2.32 sur un Ubuntu récent.

@amandine-sahl a proposé et testé une autre méthode permettant de faire la migration directement sur une nouvelle installation sur un nouveau serveur.

- On fait un dump de vieille BDD PG Geotrek
- On monte un nouveau serveur Ubuntu récent
- On y installe PostgreSQL et PostGIS (plus récent donc) avec les extensions qui vont bien
- On restaure dans cette BDD l'ancienne BDD Geotrek
- On lance une nouvelle installation de Geotrek-admin sur le serveur récent en le connectant à la BDD restaurée
- Cette installation inclut les migrations de la BDD pour la faire évoluer de la version ancienne (2.2x dans notre contexte) à la version récente installée

Commandes : 

```
-- Création de la nouvelle BDD
CREATE DATABASE geotrekdb_pwetpwet;

-- Création des extensions PostGIS3
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;

-- Restauration de la BDD
pg_restore -h localhost -U geotrek -d geotrekdb_pwetpwet ~/mypath/geotrekdb.backup

-- Installation de Geotrek-admin
curl https://packages.geotrek.fr/install.sh | bash -s - --nodb

-- Dans notre contexte, on a rencontré une erreur de migration de données : django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist
-- Correction de l'erreur : https://github.com/GeotrekCE/Geotrek-admin/issues/1937
sudo geotrek migrate --fake tourism 0004

-- Finalisation de la migration du modèle de données (optionnelle l'étape suivante suffit)
sudo geotrek migrate

-- Finalisation de l'installation
sudo dpkg-reconfigure geotrek-admin
```

**Comment by mviadere-openig** [comment]
Bonjour, je viens de le faire de mon côté, ça fonctionne, je partage aussi mon script : 
[restore_bdd.sh.txt](https://github.com/GeotrekCE/Geotrek-admin/files/7763715/restore_bdd.sh.txt)
