### ISSUE TITLE
Sites et parcours Outdoor - Ajouter filtre "PUBLIE"

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2810]
Actuellement, on ne peut pas pas filtrer les sites et les parcours Outdoor pour identifier ceux qui sont publiés ou non quand on est sur leurs modules.
C'est le cas pour les modules Trek, POI, signage...

Il serait utile et important d'avoir aussi ce filtre dans les modules Sites et pratiques Outdoor.

**Comment by babastienne** [comment]
Développé dans la release [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0).

J'ai testé sur notre demo, c'est ok pour moi.

Par contre j'ai un peu du mal à m'y retrouver dans l'arborescence des sites outdoors dans la vue liste, mais c'est un autre sujet.
