### ISSUE TITLE
Flux Cirkwi - Ajouter filtre par structure et par portail

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2822]
Le flux XML spécifique vers Cirkwi a été mis en place en 2013.
Il permet d'alimenter les plateformes IGNrando' et/ou Cirwi.

Il serait nécessaire d'ajouter la possibilité de filtrer les 2 randos (randos et POI) par structure, pour ne pouvoir envoyer que ses propres données et pas celles des partenaires, ou du moins pouvoir les diffuser dans des flux séparés, donc associés à des comptes différents.

Dans le même temps, ajouter aussi la possibilité de filtrer par "Portail".

**Comment by LePetitTim** [comment]
Il n'y a pas de champ portail pour les randonnées. Je met le filtre sur les portails uniquement pour les randonnées.

**Comment by thomaspnrhj** [comment]
Pour avoir plusieurs portails, ce serait vraiment une belle évolution de pouvoir cibler des portails pour les POIS car là c'est vraiment difficilement gérable la table d'exclusion car à chaque nouveau POI, il faut repasser sur toutes les randos à proximité...

**Comment by camillemonchicourt** [comment]
Oui bien vu.
On n'a pas non plus de filtre "portail" sur la route /poi de l'API v2 : https://geotrekdemo.ecrins-parcnational.fr/api/v2/
Logique donc de ne pas ajouter le filtre par "portail" sur le flux POI de Cirkwi.

Je ne sais pas si c'est problématique, car je ne sais plus comment Cirkwi/IGNrando' récupère les POI.
Par défaut la route des randos inclut aussi les POI associés à chaque rando : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml
Dans ce cas là, si on filtre les randos par portail, alors on n'aura que les POI associés aux randos associés au portail, donc c'est OK.
Par contre si Cirkwi utilise aussi la route https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/pois.xml alors là c'est plus embêtant, car cela va importer plein de POI qui ne sont pas liés à des randos si celles-ci sont filtrées sur un portail. Par exemple des POI d'autres territoires qui n'ont rien à voir...

On pourrait filtrer les POI par portail en ne remontant que les POI associés à des randos qui sont associés au portail demandé mais ça serait assez lourdingue et pas forcément cohérent.

Donc commençons comme ça et on va voir à l'usage.

-----------------------------------------

Plus largement sur la remarque de @thomaspnrhj, je ne sais pas si il faut pouvoir associer des portails aux POI, ça serait assez lourd à saisir et gérer, mais pourquoi pas. En effet le système d'exclusion des POI par rando est assez lourd aussi.

Ça reposerait la question de savoir si pour les contenus qui n'ont pas de portail renseigné on les prend pour tous les portails (comme font les commandes de synchronisation) ou si quand on filtre sur un portail, on ne prend que ceux qui sont explicitement associés au portail (comme pour l'API v2).
Je préfère le comportement explicite, et c'est pour ça qu'on l'a retenu pour l'API v2, mais pour les POI ça pourrait être discuté.
Bref, ça mérite au moins un ticket dédié au sujet des POI et portails. :-)

**Comment by camillemonchicourt** [comment]
OK dans la 2.74.0.
Exemples : 
- Structure PNM uniquement : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?structures=2
- Structure PNE uniquement : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?structures=1
- Structures PNM et PNE : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?structures=1,2
- Structure PNE et portail "Grand tour des Ecrins" : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?structures=1&portals=2
- Portail "Grand tour des Ecrins : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?portals=2

Pour les POIS, comme vu ci-dessus, on ne peut les filtrer que par portail
- POI de la structure "PNM" : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/pois.xml?structures=2
- POI de la structure "PNE" : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/pois.xml?structures=1
