### ISSUE TITLE
[Retour Journée Geotrek] Aggregation Geotrek

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2824]
**Qu'est ce qu'un Aggrégateur**

Un agrégateur c'est un outil, serveur, ... qui permet d'unifier les données de plusieurs Geotrek-admin. 

Le premier projet fut la mise en place d'un aggrégateur à la demande du département des Hautes Alpes.
L'idée initiale était depuis les synchros (rando v2) des différents Geotrek-admin, génerer un nouveau dossier de synchro pour le portail grâce à un fichier de correspondance entre les différentes synchronisations.

![image](https://user-images.githubusercontent.com/26329336/142638422-77f8423b-cb92-4459-b89e-add5d280b189.png)

 **Les limites de cette solution :**
 

- Pas de gestion des potentiels doublons
- Absence de liaison entre les objets issus d’instances différentes
- Modification des données reçues impossible
- Obligation de lancer manuellement l’agrégation
- Configuration complexe, proportionnellement au nombre d’instances agrégées

**Nous avions donc la nécessité de repenser l'aggrégateur :**
- Repenser la problématique pour mieux répondre aux alertes levées avec la première version
- Assurer la compatibilité avec Geotrek-Rando V3 (fonctionnement par API plutôt que par synchronisation)
- Impossible d’utiliser un script pour fusionner les fichiers servis par la plate-forme Geotrek-Rando
- Les données agrégées doivent être servies dynamiquement et en temps réel
- Gestion des données de tourisme uniquement

Nous avons donc pu discuter des solutions possible pour le futur aggrégateur pour Geotrek-admin à partir de ces limites et nouvelles contraintes.

_________
**Valorisation :**
La plus grosse contrainte est l'homogénéisation des données provenant des differents Geotrek-admin. 
- Visuelle (PDF)
- Nomenclature
- Lien entre les différentes randonnées, pois, contenus touristiques
- Doublons entre 2 Geotrek-admin

Certaines de ces contraintes sont déjà répondu par le premier aggrégateur. Cependant, d' autre contraintes peuvent être un frein dans le futur :
- L'accès aux serveurs Geotrek-admin
- La gestion des portails par les autres Geotrek-admin

Pour le moment, le fonctionnement du premier agrégateur ne permet pas de choisir les données que l'on veut ou pas, depuis des Geotrek-admin externes. Dans le cas des Hautes Alpes, ce sont les differents acteurs sur leur territoire qui donne accès à des données pour peupler leur portail. Si des données deviennent invalide, de mauvaise qualité, ils n'ont aucun moyen de les invalider ou de les changer sans faire la demande aux différents acteurs.

Si l'on veut que les données soient modifiables, il faut un flux permettant de récuperer les données sur son Geotrek-admin. 

**Gestion :**
La gestion n'est tout simplement pas gérée avec le premier agrégateur nous avons tout à penser.
La question s'est donc posée : 
Quelles données, comment, devraient elle être disponible pour un autre Geotrek-admin ?

3 axes sont apparus :
- Visualisation
- Supervision
- Coordination

Après réflexion, on a conclut que seul le "propriétaire" de la donnée doit pouvoir la modifier.
C'est lui le responsable de la donnée, c'est lui qui la gère.

On ne veut donc pas de modification de la donnée dans le cadre de la gestion.

**/!\ Un problème se pose : les éléments de gestions sont gérés avec la segmentation dynamique**

*Solution :* 
L'idée serait donc de pouvoir afficher les données des différents Geotrek-admin sur son territoire ( à la demande ?) sans les intégrer en base de donnée.

On aurait donc aucun accès aux tronçons des autres Geotrek-admin.
_______________________________________
Outre ces 2 parties, nous avons également discuté de l'identification des doublons :
Nous avons pour le moment comme identifiants :
- les identifiants externes (apidae, tourinsoft ...).
- les identifiants internes (id) propre au fonctionnement de Geotrek-admin

Il manque pour le moment un identifiant qui permettrait d'éviter les doublons pour les randonnées et les catégories créer par chaque Geotrek-admin.
L'idée d'un identifiant unniversel est apparu.

- uuid

On pourrait alors avoir le même vocabulaire et le même identifiant évitant l'obligation d'utiliser un fichier, paramétrage...  pour faire la correspondance entre les mêmes catégories par exemple.

**Toutes ces solutions, sont a débattre. C'est un sujet qui devient de plus en plus d'actualité, les territoires des Geotrek-admin se chevauchent de plus en plus entre Départements, Communes, Regions, Parcs....**
https://geotrek.fr/utilisateurs.html

**Comment by camillemonchicourt** [comment]
Merci, quelques ressources en complément : 

- La v1 de l'agrégateur avait été présentée lors des rencontres Geotrek 2019 : https://geotrek.ecrins-parcnational.fr/rencontres/2019/presentations/07a-agglo-geotrek-05.pdf

Puis les premières réflexions sur la v2 aux rencontres Geotrek 2021 : https://geotrek.ecrins-parcnational.fr/rencontres/2021/presentations/16-geotrek-agregateur.pdf
Vidéo de cette présentation : https://geotrek.ecrins-parcnational.fr/rencontres/2021/presentations/16-geotrek-agregateur.mp4

**Comment by IdrissaD** [comment]
État des lieux d'avancement du Geotrek-admin aggregator développé par OPenIG :
[2022-05-12_pres_gag_v2.pdf](https://github.com/GeotrekCE/Geotrek-admin/files/8679954/2022-05-12_pres_gag_v2.pdf)

**Comment by camillemonchicourt** [comment]
Le développement d'un agrégateur Geotrek a été développé et intégré dans Geotrek-admin, à partir de sa version 2.87.0, puis enrichi depuis.

Il s'agit d'un nouveau parser, nommé ``GeotrekParser`` et de l'ajout d'un champs ``provider`` (fournisseur).

Travail détaillé sur https://github.com/GeotrekCE/Geotrek-admin/issues/3189 et réalisé principalement dans la PR https://github.com/GeotrekCE/Geotrek-admin/pull/3196

**Comment by camillemonchicourt** [comment]
https://makina-corpus.com/logiciel-libre/fusionner-bases-donnees-geotrek-projet-agregateur
