### ISSUE TITLE
Update DEM and altimetry / geometry 

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2833]
Version Geotrek-Admin : 2.72.0

Bonjour, lors de notre rencontre aux journées Geotrek de septembre j'avais demandé s'il était possible de mettre à jour le profil altimétrique de données géographiques sur un Geotrek où des données ont été entré avant de mettre en place un mnt. Plusieurs parmi vous m'ont répondu que oui, grâce à cette commande en BDD : 

`update public.core_path set geom=geom;`

La commande a bien fonctionné, mais après un redémarrage de Geotrek, voir même un sudo dpkg reconfigure geotrek-admin,

je ne vois aucun changement. Est-ce que ma commande est erronée où j'ai oublié une étape ?

**Comment by camillemonchicourt** [comment]
Oui oui c'est bien ça.
En lançant cette commande, on fait un update des géométries des tronçons, qui relance les triggers de calcul de leur altimétrie puis dans la foulée de l'altimétrie des événements liés aux tronçons (itinéraires, travaux, aménagements...).

Ce calcul peut être très long. Je l'ai fait récemment sur notre Geotrek-admin et cela a pris 6 heures.
Et ça recalcule les longueurs 3D, les dénivelés etc...

Vu que c'est tout dans la BDD, un redémarrage du serveur ou de la configuration n'a rien à voir.

**Comment by mviadere-openig** [comment]
Ok, dans tous le cas quand je fais la commande ça me dit qu'il y a 296 entité qui sont mis à jour, mais je ne vois toujours rien sur le Geotrek-admin. Est-ce que le fait que le MNT soient trop grand puisse causer un souci ? (voir ici : https://openig-geotrek-cd11-prod.ataraxie.fr/tools/extents/)

**Comment by camillemonchicourt** [comment]
Non je ne vois pas pourquoi.
Mais y a t-il vraiment un soucis ?
Es-tu certain que les valeurs ne sont pas bien calculées au regard du MNT existant ?

Ton lien n'est pas accessible sans être authentifié.
