### ISSUE TITLE
Remove tmp_sync_rando, use TmpDirectory in var/tmp/<id_tmp>

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2834]
=> Important to find how to remove <id_tmp> when the command stop without assertion.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.86.0 (https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.86.0) avec l'ajout d'une option dans les commandes de synchronisation.
