### ISSUE TITLE
Paramètre de redimensionnement des images

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#2835]
- Créer un settings pour activer le redimensionnement
- Ne stocker que l'image redimensionnée
- Définir une taille max : en settings

**Comment by camillemonchicourt** [comment]
Je pense qu'il faut que le redimensionnement ne soit pas activé par défaut, mais le documenter pour ceux qui veulent l'activer et le paramétrer.

**Comment by Chatewgne** [comment]
PR https://github.com/GeotrekCE/Geotrek-admin/pull/2841

**Comment by camillemonchicourt** [comment]
L'image va toujours bien garder ses proportions ? 
Même si elle est chargée en format portrait ?

**Comment by Chatewgne** [comment]
D'après mes tests l'image garde ses proportions de sorte à devenir plus petite que 1280x720 (par défaut) 

```
MAX_ATTACHMENT_WIDTH = 1280
MAX_ATTACHMENT_HEIGHT = 720
```

Mais pour les portraits il faudrait peut être créer d'autres settings pour inverser hauteur/largeur

```
MAX_ATTACHMENT_WIDTH = 1280
MAX_ATTACHMENT_HEIGHT = 720
```

Je peux mettre une autre valeur

**Comment by camillemonchicourt** [comment]
Sinon il suffit pas de définir comme paramètres : 

MAX_ATTACHMENT_WIDTH = 1280
MAX_ATTACHMENT_HEIGHT = 1280

???

Si paysage, elle va se caler à 1280px de large max et adapter la hauteur selon ses proportions.
Si portaits, elle va se caler à 1280px de hauteur max et adapter la largeur selon ses proportions, non ?

**Comment by Chatewgne** [comment]
Oui, tout simplement haha
Je met ça !

**Comment by camillemonchicourt** [comment]
Est ce que tous les anciens médias déjà uploades seront automatiquement redimensionne aussi si ils dépassent la taille max définie ?
Ou une commande permettant de redimensionner tous les médias existants dépassant la taille max ?

**Comment by Chatewgne** [comment]
Non, là c'est la procédure de sauvegarde pour les nouveaux fichiers.

Une commande serait envisageable, à tracer dans un autre ticket ?

**Comment by camillemonchicourt** [comment]
Oui en effet, ce serait à gérer par ailleurs et différemment, mais ça pourrait être intéressant.
Oui je vais faire un autre ticket. Merci.
