### ISSUE TITLE
ITINERAIRES / Ajout de champs Accessibilité

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2838]
Compléter le module ITINERAIRES avec des champs plus complets et précis sur l’accessibilité.

Actuellement on n'a que 2 champs sur les randos : 
- Type d'accessibilité
- Aménagements handicapés

Évolutions : 

- Ajout d'un onglet accessibilité dans le formulaire des itinéraires et des sites outdoor
- Niveau d'accessibilité : ajout d'une liste déroulante paramétrable + APIv2 + filtre
- Pente, revêtement, exposition, largeur, signalétique, conseils : ajout d'un champs texte et ajout sur l'APIv2
- Numéro de secours : ajout dans Geotrek-rando
- Photos : s'appuyer sur les fichiers attachés existants, en ajoutant des types de fichiers spécifiques (pente, largeur, signalétique). Ajout du type de fichier dans l'API v2 / CM : Discutable car ce n'est pas générique à tous les modules
- Obstacles : utilisation du module POI. Mise en place d'un booléen "accessibilité" sur les types de POI permettant de faire le tri côté Geotrek-rando. / CM : mauvaise solution selon moi.
- Sanitaires : ajout d'une case à cocher "accessible" dans les aménagements et ajout des aménagements à l'APIv2 avec les filtres type, accessible et near_trek / CM : Discutable car spécifique
- Parking : utilisation du module aménagement : ajout d'une case à cocher "accessible" dans les aménagements et ajout dans l'APIv2 avec les filtres type, accessible et near_trek / CM : Discutable car spécifique
- Lieux d'information : ajout d'un champ texte et ajout sur l'API v2
- Contenus touristiques : ajout des champs d'accessibilité (quelques champs texte/booléen/étiquette) + adaptation du parser APIDAE + APIv2

A voir : Export PDF public ? Module parking ?

> Obstacles : Ne pas utiliser les POI qui sont pour les patrimoines.
Pourquoi pas utiliser le module "Services", à renommer "Informations pratiques". La limite à cela est si on souhaite une description spécifique à chaque obstacle, ou si on peut juste ajouter une description globale par type d'obstacle. Et si on veut une photo par obstacle ? Mais pourquoi pas ajouter cela sur le module "Informations pratiques" (ex-Services)

-------------------------------------------

Champs | Description | Type
-- | -- | --
Niveau d’accessibilité | Débutant (Peu de dénivelé – terrain sans de difficultés) / Expérimenté (Pente importante – Terrain technique, avec obstacles) | Liste
Pente | Description texte précise de la pente : supérieur a 10 % (Nécessite une assistance quand la pente est supérieur à 8%) ; rupture de pente ; | Texte
Revêtement | Description texte des différents revêtement rencontrés sur la totalité d’un itinéraire. Type : Piste, sentier, route  + type de Revêtement : Caillouteux ; présence de pierres , sable ; pavettage , dalle … | Texte
Exposition | Description texte des expositions avec zoom sur certaines zones ombragées. Ombragé – Forte expositions – présence de zone ombragées | Texte
Largeur | Précisé les rétrécissements des sentiers et la largueur minimum Pour les fauteuils : sentier > 0,90 m Joëlette sentier étroit demande une forte technique de conduite | Texte
Signalétique | Description de taille, forme et couleurs. Si plusieurs types. | Texte
Conseils accessibilité | Mettre le focus sur les éléments particuliers permettant d’apprécier le contexte de l’itinéraire pour les PMR (conseils, passages délicats, etc.) | Texte
Obstacles | Exemple :  épingle serrée, passerelle, ressaut, virage en dévers, marches , blocs rocheux, rupture de pente .. | Objet carto
Sanitaires | Localisation des sanitaires les plus proches. Précision du caractère accessible aux personnes porteuses de handicap. Sinon, donner une description | Objet carto
Parking | Localisation, places réservée PMR, type de revêtement, description de la localisation | Objet carto

**Comment by LePetitTim** [comment]
Ajout d'un onglet accessibilité dans le formulaire des itinéraires et des sites outdoor

Il n'y a pas de champ accessibilité dans sites outdoor

**Comment by camillemonchicourt** [comment]
Oui c'est une erreur.
On prévoyait initialement d'ajouter tous les champs ACCESSIBILITE dans les modules ITINERAIRES et OUTDOOR, mais au final on se recentre uniquement sur ITINERAIRES.

**Comment by LePetitTim** [comment]
- Niveau d'accessibilité : ajout d'une liste déroulante paramétrable + APIv2 + filtre

1. Plusieurs valeurs possible générique
2. Une valeur possible générique
3. Relié au champ accessibilité plusieurs possibles par accessibilité
4. Relié au champ accessibilité (un peu comme cotation et echelle de cotation) une seule par accessibilité

**Comment by camillemonchicourt** [comment]
Voir l'usage prévu côté Geotrek-rando-v3 : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/536

![Capture d’écran de 2022-01-19 10-34-22](https://user-images.githubusercontent.com/4418840/150103800-ea171329-c4b4-47fc-b18f-fa883ad11c56.png)

**Comment by camillemonchicourt** [comment]
Pour le niveau d'accessibilité, il y a 2 valeurs par défaut : Débutant ou Expérimenté. Cette typologie est modifiable dans l'Adminsite. Pour un itinéraire on ne peut renseigner qu'un seul niveau d'accessibilité. Le niveau d'accessibilité ne dépend pas du type d'accessibilité.

**Comment by LePetitTim** [comment]
Proposition pour séparer le detail des accessibilités dans les randonnées (réutilisable dans un autre contexte)
![Capture d’écran de 2022-01-19 11-35-19](https://user-images.githubusercontent.com/26329336/150113625-4d063108-a8f3-47d3-a03d-bc6fea8edcab.png)
![Capture d’écran de 2022-01-19 11-35-04](https://user-images.githubusercontent.com/26329336/150113628-54e4066d-b993-4a9e-a25b-2cd46f231368.png)

**Comment by camillemonchicourt** [comment]
Oui des sous-blocs c'est très bien

**Comment by LePetitTim** [comment]
- Ajout d'un onglet accessibilité dans le formulaire des itinéraires et des sites outdoor
- Niveau d'accessibilité : ajout d'une liste déroulante paramétrable + APIv2 + filtre
- Pente, revêtement, exposition, largeur, signalétique, conseils : ajout d'un champs texte et ajout sur l'APIv2
- Numéro de secours : ajout dans Geotrek-rando
- Photos : s'appuyer sur les fichiers attachés existants, en ajoutant des types de fichiers spécifiques (pente, largeur, signalétique). Ajout du type de fichier dans l'API v2 / CM : Discutable car ce n'est pas générique à tous les modules
- Obstacles : utilisation du module POI. Mise en place d'un booléen "accessibilité" sur les types de POI permettant de faire le tri côté Geotrek-rando. / CM : mauvaise solution selon moi.
- Sanitaires : ajout d'une case à cocher "accessible" dans les aménagements et ajout des aménagements à l'APIv2 avec les filtres type, accessible et near_trek / CM : Discutable car spécifique
- Parking : utilisation du module aménagement : ajout d'une case à cocher "accessible" dans les aménagements et ajout dans l'APIv2 avec les filtres type, accessible et near_trek / CM : Discutable car spécifique
- Lieux d'information : ajout d'un champ texte et ajout sur l'API v2
- Contenus touristiques : ajout des champs d'accessibilité (quelques champs texte/booléen/étiquette) + adaptation du parser APIDAE + APIv2

**Comment by camillemonchicourt** [comment]
Compléments d'infos à ajouter pour les autres objets (dans les fiches, formulaires, exports, champs masquables, APIv2...) : 

# Lieux d'informations

- Ajouter un champs texte "Accessibilité" 
- Ajouter un champs multiselect "Label accessibilité" pour pouvoir renseigner correctement le label national "Tourisme & Handicap (https://www.tourisme-handicap.gouv.fr/fr/tourisme-handicap-tourisme-pour-tous)
![image](https://user-images.githubusercontent.com/4418840/151833939-c5e71036-d39a-4097-95d8-bc16d18e6c67.png)
- Ajout d'une table pour les valeurs possibles de "Label accessibilité" avec un label et un picto, contenant par défaut les valeurs : 
  - Marque Tourisme et Handicap - déficience auditive
  - Marque Tourisme et Handicap - déficience mentale
  - Marque Tourisme et Handicap - déficience motrice
  - Marque Tourisme et Handicap - déficience visuelle

# Contenus touristiques

- Idem que pour les lieux d'informations : Un champs texte "Accessibilité" + un champs multiselect "Label accessibilité" avec les mêmes valeurs que pour les lieux d'informations (donc à mettre dans "commons" à priori)
- Adapter le parser Apidae en faisant correspondre le champs "Label accessibilité" au champs "Label Tourisme et Handicap" d'Apidae et les champs de description présents dans Apidae ("Descriptif handicap auditif", "Descriptif handicap mental", "Descriptif handicap moteur" et "Descriptif handicap visuel" - https://aide.apidae-tourisme.com/hc/fr/articles/360000797332-Guide-de-saisie-prestations-pour-les-personnes-handicap%C3%A9es) à faire correspondre et concaténer dans le champs texte "Accessibilité" ajouté dans la table des contenus touristiques
- Adapter le parser "Esprit parc national"

# Événements touristiques

Ajout d'un champs texte "Accessibilité"

# Sites outdoor

- Ajout d'un champs texte "Accessibilité.
- Pas d'ajout sur les "Parcours outdoor"

**Comment by camillemonchicourt** [comment]
Une grosse partie des évolutions a été intégrée dans la version 2.76.0 : 

## 1. Mise en place d'un onglet "Accessibilité" dans le formulaire des itinéraires.
Y ont été basculés les 2 champs déjà existants liés à l'accessibilité ("Type d'accessibilité" et "Aménagements handicapés") et où ont été ajoutés les nouveaux champs pour préciser l'accessibilité d'un itinéraire (Niveau d'accessibilité et plusieurs champs texte : 
![Capture d’écran de 2022-02-02 23-17-38](https://user-images.githubusercontent.com/4418840/152247468-9d6a7c0d-171e-4b59-9d36-37714ebcbf80.png)

Pour ceux qui installent Geotrek-admin pour la première fois en version 2.76.0 ou plus, ils auront les valeurs par défaut des nouveaux champs intégrées automatiquement.
Pour ceux qui avaient déjà un Geotrek-admin dans une version antérieure et font une mise à jour, ils peuvent créer manuellement les valeurs des nouveaux champs depuis l'Adminsite, et notamment pour le champs "Niveau d'accessibilité" : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/fixtures/basic.json#L302-L317

A voir : 
- Je pense qu'il faudrait renommer le label du champs "Accessibilité" en "Type d'accessibilité" pour que cela soit plus clair et moins confusant avec le bloc qui s'appelle déjà globalement "Accessibilité"
- On avait évoqué le fait de renommer le label "Aménagements handicapés" en "Aménagements d'accessibilité" ("Accessibility infrastructure") mais pas dans la BDD ni l'API car trop lourd
- Le champs "Exposition" a "Revêtement" comme label. 
- Le champs "Recommandations" serait à renommer "Conseils" pour éviter les confusions avec le champs "Recommandations" existant par ailleurs dans les infos générales liées à la randonnée.

## 2. Mise en place d'un sous-bloc regroupant les champs liés à l'accessibilité dans la fiche détail des randos
![Capture d’écran de 2022-02-02 23-42-46](https://user-images.githubusercontent.com/4418840/152250171-011460ed-af4a-4854-bc65-ad94be48464b.png)

A voir : 
- Le titre du bloc s'affiche sous les champs et pas au-dessus
- Intégrer le titre du bloc dans l'export ODT/DOC/PDF (pas le PDF grand public qui est un autre sujet)

## 3. Ajout d'un onglet permettant d'associer des photos liées à certaines informations de l'accessibilité (pente, largeur, signalétique) 

![Capture d’écran de 2022-02-02 23-49-32](https://user-images.githubusercontent.com/4418840/152252847-1fb80a21-5624-422d-93c8-d98691435c04.png)

A voir : 
- Renommer l'onglet "Fichiers joint pour l'accessibilité" en "Photos accessibilité" pour raccourcir l'onglet et être plus précis sur son périmètre
- Ajouter un paramètre "ACCESSIBILITY_ATTACHMENTS_ENABLED" (à ``true`` par défaut) permettant de masquer cet onglet pour ceux qui n'en auraient pas du tout l'usage

## 4. Ajout des champs dans les exports et l'API

Dans les exports, les noms de champs ne mentionnant pas "accessibilité" peuvent porter à confusion : 
Accessibilité | Recommandations | Revêtement | Revêtement | Niveau | Signalétique | Pente | Largeur
Ça serait un peu lourd de les préfixer de "accessibilité" et c'est peut-être un soucis de pas avoir les même labels de traduction partout, mais je vois pas trop d'autre solution pour que cela soit plus clair ?

## 5. Ajout des champs d'accessibilité mentionnés plus haut sur les autres objets

Pour ceux qui mettent à jour leur Geotrek-admin depuis une version précédente, les valeurs par défaut des labels d'accessibilité peuvent être ajoutés manuellement depuis l'adminsite : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/tourism/fixtures/basic.json#L28-L59 avec les logos associés disponibles dans https://github.com/GeotrekCE/Geotrek-admin/tree/master/geotrek/tourism/fixtures/upload

A voir : 
- Dans le formulaire "Contenus touristiques", le fait que le champs booléen "Labellisé" soit juste en dessous du champs "Label accessibilité" apporte de la confusion, on peut penser que ces 2 champs sont liés alors qu'ils n'ont rien à voir.
Je propose de déplacer le champs "Labellisé" ailleurs, pourquoi bien plus hait, juste en dessous du champs "Publié" et d'y ajouter le texte d'aide : "Indique si le contenu dispose d'un label ou d'une marque".
- Il manque l'ajout du champs texte "Accessibilité" sur les sites outdoor

**Comment by camillemonchicourt** [comment]
Du coup dans les parcours, on n'avait pas prévu d'ajouter un champs ACCESSIBILITE mais on peut l'y laisser maintenant qu'il a été ajouté.

Mais si possible, j'aimerai qu'on revoit l'ordre des champs dans le formulaire et la fiche détail : 
- Recommandations
- Matériel
- Equipement
- Accessibilité

**Comment by camillemonchicourt** [comment]
Des évolutions ont été apportées dans la 2.76.1, mais : 

- [ ] Le champs "Aménagements handicapés" a bien été renommé dans la BDD, mais dans l'interface il a été renommé "Accessibilité aménagement" au lieu de "Aménagements d'accessibilité"
![Capture d’écran de 2022-02-07 15-01-51](https://user-images.githubusercontent.com/4418840/152802804-2c45f740-e786-4803-b4d6-4c80e25e483d.png)
![Capture d’écran de 2022-02-07 15-02-09](https://user-images.githubusercontent.com/4418840/152802815-1abce1a6-0def-4ef3-94b9-5a377db4030c.png)
- [ ] Le champs "Signalétique" a été renommé "Accessibilité signalétique" au lieu de "Signalétique accessibilité"
- [ ] Il manque un S à "conseil" au niveau du champs "Conseils d'accessibilité"
- [ ] Il manque un "i" à "accessibilité" sur le champs "Exposition accessiblité"
- [ ] L'onglet "Fichiers joint pour l'accessibilité" n'a pas été renommé en "Photos accessibilité"
- [ ] Sur les contenus touristiques, le champs "Labellisé" a bien été remonté plus dans le formulaire, du coup ça serait bien de faire pareil sur la fiche détail d'un contenu touristique pour la cohérence et les mêmes questions de potentielle confusion avec le "label d'accessibilité"
- [ ] Sur les fiches détails des itinéraires, il est important de corriger le point "Le titre du bloc ACCESSIBILITÉ s'affiche sous les champs et pas au-dessus"
- [ ] J'ai passé le paramètre "ACCESSIBILITY_ATTACHMENTS_ENABLED" à ``False`` mais je vois toujours l'onglet des fichiers liés à l'accessibilité

Pour le reste ça me semble OK.

**Comment by camillemonchicourt** [comment]
Avec la 2.76.3, tous les retours ont été pris en compte.
Sauf "Intégrer le titre du bloc dans l'export ODT/DOC/PDF (pas le PDF grand public qui est un autre sujet)" qui serait le dernier petit détail.
Un travail serait aussi à faire au niveau du parser APIDAE.
Le sujet des parkings, sanitaires et obstacles est traité dans un ticket dédié.
Je ferme ce gros ticket.

**Comment by camillemonchicourt** [comment]
Premier retour du PNC qui commence aussi un travail sur l'accessibilité des itinéraires : 

> Ce qu'il manque actuellement, c'est la notion "d'équipement" propres aux différents handicap. Genre main courante, braille, ...
> La notion niveau d'accessibilité est très discutable car subjective.
> 
> J'aurais tendance à remplacer "Niveau d’accessibilité" par "équipement" en multivalué. Comme ça les  personnes concernées pourront directement savoir si c'est ou pas accessible pour leur handicap.
> A voir si on met une table d'orientation en braille dans les aménagements ou juste sous la forme d'une info dans la fiche de l'objet ?
> 
> 2 questions sont ressorties : 
> - Est-ce que les infos peuvent être associé à des POI  comme par exemple les points de vues, belvédères...
> - Et comment outre dans la fiche détail ce sera mis en avant sur Geotrek-rando (filtrable, ...)

Mes retours : 

> - Les équipements je ne sais pas si ce n'est pas à gérer dans les aménagements comme on a commencé à discuter (https://github.com/GeotrekCE/Geotrek-admin/issues/2918). Si on les liste en plus dans un champs, je sais pas. A voir.
> - Pour le "Niveau d'accessibilité", à priori c'est normé avec "Débutant" ou "Confirmé" mais j'en sais pas plus.
> - Rien n'est mis en place au niveau des POI, mais on pourrait ajouter un champs texte "Accessibilité" sur les POI ?
> - Pour le moment on peut juste filtrer sur le champs existant "Type d'accessibilité" dans Geotrek-rando-v3 et rien de plus de prévu. On pourrait imaginer filtrer sur d'autres champs mais ils sont quasiment tous en texte
