### ISSUE TITLE
Generation of pdfs and maps

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#2844]
After some questions and problems on PNRGC we found that generation of pdfs was sometime wrong.
Some pdfs had blank pages :
![Capture d’écran de 2021-12-06 14-59-48](https://user-images.githubusercontent.com/26329336/144859079-1077765c-d16c-4ff8-9a20-7236b257513d.png)
At the beginning, we thought it was a problem with the template of PNRGC. 
**It was not the case.** 

As we can see on the first page :
 ![Capture d’écran de 2021-12-06 15-01-52](https://user-images.githubusercontent.com/26329336/144859407-06cbe70a-a35c-43b2-9c8d-37e8ee5581ef.png), 
The map on the right is not a square, we force it to be a square with pdf's template . It means the generation of the screenshot of the map does not work as intended.

Geotrek generate map's screenshot with screamshotter. 

It uses a viewport representing the range or area currently being viewed on the browser. => [Viewport](https://github.com/makinacorpus/screamshotter/blob/70ca1e4e9e438312b320d643e4cabc014c27d7f1/src/screenshotter/js/index.js#L27)

It uses a special page with a different page's size, additional informations (pois,)... => [Mapsize](https://github.com/makinacorpus/django-mapentity/blob/131ec1610be1ad82e128d7abd8807a33652ca537/mapentity/helpers.py#L203)

It generates a picture. It should be a square => Picture

I found firstly Geotrek-admin don't send any values for the viewport :
[```capture_image(url, fd,
                      selector='.map-panel',
                      waitfor=waitfor)```](https://github.com/makinacorpus/django-mapentity/blob/131ec1610be1ad82e128d7abd8807a33652ca537/mapentity/helpers.py#L212)
We use default screamshotter values (width : 1920, height : 1080). ***
[```width = serializers.IntegerField(required=False, initial=1920)```](https://github.com/makinacorpus/screamshotter/blob/70ca1e4e9e438312b320d643e4cabc014c27d7f1/src/screenshotter/serializer.py#L8)
[```height = serializers.IntegerField(required=False, initial=1080)```](https://github.com/makinacorpus/screamshotter/blob/70ca1e4e9e438312b320d643e4cabc014c27d7f1/src/screenshotter/serializer.py#L9)
Before the next point, I didn't undesrtand why sometime map's picture was well generated and sometimes not. Everything seemed odd.

After I began to use the values calculated in Geotrek-admin, I found some maps was generated with a viewport : width <small_other_value>, height: <calculated_value>, even if i use the same value for width and height (which is what we want).
This was the picture generated :
![Capture d’écran de 2021-12-06 15-20-35](https://user-images.githubusercontent.com/26329336/144862488-af6d7a1f-7da1-4abd-8fe4-bf66521a874c.png)

I found then the generation was wrong when we asked a mapsize's height bigger than the size of the browser. The map was with a scroll bar. Screamshotter was not able to screenshot the map without regenerate a viewport which changed the width of the generated Picture.
![Peek 06-12-2021 16-00](https://user-images.githubusercontent.com/26329336/144868930-14e3f298-aabc-486e-9002-46602f6a809c.gif)

*** Some maps was well generated when the mapsize's height of the map was smaller than the height of the browser. 
Maps could be more or less well generated when the ratio between height and width was the good one :
When the mapsize's height is bigger than the browser height, the viewport is modified during the screenshot, we can still have the same value for width and height after the modification of the viewport.  

We need either :
- find the ratio between width and height which always generate a good screenshot even if height is bigger than the browser
- fix the size of the viewport and mapsize. (smaller than the height of the browser)

**Comment by LePetitTim** [comment]
#2746

**Comment by camillemonchicourt** [comment]
Le format des cartes exporté dans les PDF a été amélioré mais reste à voir si on peut générer une image carrée tout le temps comme proposé dans ce ticket.
On ré-ouvrira ce ticket si besoin.
