### ISSUE TITLE
Modules list responsive / Add scroll

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2849]
On mobile phones, with a lot of modules and a medium screen size, module list can be incomplete.
It would require to add a scroll in the module list to be able to access all modules.

**Comment by babastienne** [comment]
Illustration of the problem :

![image](https://user-images.githubusercontent.com/16348048/215729041-ce8f0f5f-79f4-4a96-b1ff-aaea2bd0d855.png)

**Comment by babastienne** [comment]
Fixé dans la release [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0)
