### ISSUE TITLE
Fiches interventions n'affichent pas les tronçons ni les sentiers

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2851]
Sur la fiche des interventions, dans le bloc GESTION, les tronçons et les sentiers qui intersectent l'intervention ne sont pas affichés, le bloc est toujours vide.

**Comment by JoelAtche** [comment]
C'est la même chose pour les éléments ponctuels "Signalétiques" ou "Aménagements", bloc vide alors que les interventions elles sont bien présente dans la fiche des aménagements ou signalétiques.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.77.
