### ISSUE TITLE
Nouveau django-tinymce

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-admin#2859]
On doit mettre à jour django-tinymce pour cause de probleme de sécurité. https://github.com/GeotrekCE/Geotrek-admin/security/dependabot/requirements.txt/django-tinymce/open

La nouvelle version change completement le theme le style et la disposition par rapport à ce qui existe actuellement à cause du passage à tinymce 5

https://www.tiny.cloud/docs/migration-from-4x/

**Comment by camillemonchicourt** [comment]
Pas de soucis pour mettre à jour si l'interface évolue, mais que les fonctionnalités restent similaires, au contraire.
C'est seulement utilisé pour les champs de texte long dans les différents modules, ou aussi pour le WYSIWYG des pages statiques dans l'AdminSite ?

**Comment by submarcos** [comment]
je pense que c'est utilisé partout. C'est le probleme le plus complexe, définir la liste des fonctionnalités qui sont utilisées par tous pour etre sur qu'on en retire pas avec la nouvelle version car la configuration change complètement. On verra si on fait une version beta pour bien valider tout çà avant modification finale

**Comment by camillemonchicourt** [comment]
OK, en tout cas, un élément que l'on peut avoir en tête est que dans Geotrek-rando-v3 on n'utilise plus du tout la complexité de la mise en forme des pages statiques responsive. Donc l'enjeu est moindre.
Si c'est déployé sur votre serveur de démo, je peux faire un test rapide pour valider les fonctionnalités.
