### ISSUE TITLE
Update apt

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2869]
Bonjour,

J'ai pris un peu de retard dans mes mises à jour de geotrek-admin. J'ai installé Géotrek avec le dépôt Ubuntu bionic. 
Je suis actuellement en version 2.62.0. J'ai lancé la commande d'update (comme d'habitude) mais le serveur m'indique ne pas pouvoir récupérer la version 2.66.0. Et pour cause, l'archive n'est pas présente sur le dépôt.
Comment puis-je faire pour faire la mise à jour simplement ?

**Comment by camillemonchicourt** [comment]
Salut, je ne comprends pas pourquoi tu veux passer par la 2.66.0 ?
Normalement tu passes directement à la dernière version avec ``apt-get update`` puis ``apt-get upgrade``.

Par contre, attention à l'ajout d'une extension PostgreSQL dans la 2.69.0 qui nécessite de l'ajouter manuellement avant la mise à jour : https://geotrek.readthedocs.io/en/master/installation.html#from-geotrek-admin-2-69-0

Cependant, je ne sais pas pourquoi l'archive 2.66.0 n'est plus disponible sur le dépôt.

**Comment by jeromesourdin** [comment]
C'est moi qui fait de la m*** ! J'ai utilisé la commande apt et non apt-get... (l'habitude...)
