### ISSUE TITLE
Update to pillow 9.0.0 - Not available on python3.6

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-admin#2894]
Mise à jour de sécurité High Severity sur Pillow https://github.com/GeotrekCE/Geotrek-admin/security/dependabot/requirements.txt/Pillow/open

Le problème c'est qu'il n'est pas dispo sur python 3.6 que cette version ne supporte plus https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#python-3-6

Python3.6 est utilisé de base sur Ubuntu Bionic 18.04

**Comment by camillemonchicourt** [comment]
Donc pour y passer il faudrait ne plus supporter Ubuntu 18 ?
A priori on est encore pas mal à être sur des serveurs Ubuntu 18, mais il faudra bien migrer un jour.
J'avais pensé ça plutôt quand Ubuntu 22 sortira mais à voir si il faut accélérer l'arrêt du support de la 18.

**Comment by submarcos** [comment]
Il ya plusieurs possibilités.

- Utiliser le python 3.8 de bionic. Ils l'ont rajouté apres sa sortie, mais il est bloqué en 3.8.0 et ne beneficie d'aucune mise à jour de sécurité.
- Embarquer une version de python spécifique dans geotrek. Avantages : on va grandement diminuer la durée des tests. Incovénients : çà sera un peu plus gros à installer
- Ne plus supporter bionic : conséquences pour les utilisateurs. Mais 22.04 sort dans 3mois et il faudra prévoir de le supporter (supporter 3 LTS et autant de versions de python différentes va allonger les tests et les temps de développement)

**Comment by camillemonchicourt** [comment]
> En réalité, je pense que si on embarquait python dans Geotrek il y a des chances que ce soit relativement simple de supporter autant de distributions debian/ubuntu que l'on veut (je ne parle pas du repo mais les paquets Debian seraient installables)

OK on avait évoqué cette solution au préalable lors de la mise en place du package Debian et ne l'avions pas retenu je ne sais plus pour quelle raison. Mais si il y a pas ou peu d'inconvénients, alors ça semble une solution à privilégier.

**Comment by submarcos** [comment]
py 3.6 not maintained anymore
