### ISSUE TITLE
Ajouter deux champs "Label" et "Statut" au module sentiers.

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2900]
CM : A discuter ? On va saisir une info en double ?

**Comment by camillemonchicourt** [comment]
Après discussion avec le CD66, l'idée ne serait finalement pas de créer un second champs "Réseaux" sur le module "Sentiers". 
Il s'agirait bien de laisser ce champs au niveau des tronçons et de créer 2 nouveaux champs sur le module "Sentiers" pour permettre de gérer la labellisation PDIPR au niveau des sentiers, et ainsi de donner plus de sens, d'usage et cohérence à ce module : 
- Un champ "Label" permettrait de renseigner la procédure en question: PDIPR, PDESI, RLESI, PR, VTT-FFC, etc.. (avec possibilité de paramétrer la liste des labels).
- Un champ "Statut" permettrait de renseigner où en est la procédure : Constitution du dossier, En cours d'instruction, Validée, Rejetée (à voir quels seraient les valeurs les plus adaptées et de pouvoir paramétrer la liste)

Mémo technique pour l'ajout de champs : https://geotrek.readthedocs.io/en/latest/development.html#model-modification-definition-of-done-for-new-model-fields

**Comment by camillemonchicourt** [comment]
Le terme "Statut" est peut-être à discuter pour trouver un autre terme, pour ne pas apporter de confusion avec le module "Statuts".

**Comment by numahell** [comment]
Ça donnerait ça 

À l'édition

![image](https://user-images.githubusercontent.com/546686/179778010-29298666-2361-4c1f-a9c6-d4dbce6f52b6.png)

Fiche détail

![image](https://user-images.githubusercontent.com/546686/179778154-126b8187-fa3d-4740-8eac-8a2d2c8e5116.png)

**Comment by camillemonchicourt** [comment]
Attention, cette évolution a été intégrée dans la version 2.86.0, mais n’apparaît pas dans son CHANGELOG.
Il est important de l'indiquer, car elle n'est pas anodine et impacte tous les Geotrek-admin.

**Comment by camillemonchicourt** [comment]
Dans l'adminsite, la gestion des valeurs de ces nouveaux champs est dans le bloc CŒUR : 

![image](https://user-images.githubusercontent.com/4418840/189325375-e622dd4b-2756-4fe3-a764-1c04297b619e.png)

En effet c'est là qu'étaient les sentiers jusqu'à présent.
Mais maintenant qu'ils ont ces champs spécifiques, il faudrait un modèle spécifique SENTIERS, car c'est peu compréhensible et intuitif de trouver "Catégories des sentiers", "Labellisations" et "Statuts de labellisation" dans CŒUR.

**Comment by numahell** [comment]
Pour l'absence dans le changelog, j'ai dû mal faire un rebase à un moment donné. Je fais une PR pour rajouter ça.

**Comment by numahell** [comment]
> Mais maintenant qu'ils ont ces champs spécifiques, il faudrait un modèle spécifique SENTIERS, car c'est peu compréhensible et intuitif de trouver "Catégories des sentiers", "Labellisations" et "Statuts de labellisation" dans CŒUR.

Dans le code on a bien deux modèles distincts, Trail et Path. Django-admin regroupe les contenus d'une même application, en l'occurence CORE ou CŒUR (traduit).
Là ce qu'il faudrait faire c'est : 
- créer une nouvelle app django
- y déplacer le modèle sentiers et ses modèles liés
- déplacer également les vues, tests, formulaires…
- refaire les migrations
- mettre à jour fixtures, import, etc.

Je vais voir si c'est pas possible de faire plus simple.
