### ISSUE TITLE
Respect du nombre de caractères maxi des champs rédactionnels

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2901]
Contrôler le respect du nombre de caractères (espaces compris) maximum sous les champs rédactionnels, et indiquer le nombre max.

CM : Activable ou non et nombre de caractères paramétrable.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.86.0 avec l'ajout d'un paramètre ``MAX_CHARACTERS`` et documenté : https://geotrek.readthedocs.io/en/2.86.0/install/advanced-configuration.html#max-characters-count

Celui-ci s'applique à tous les champs texte de tous les modules.
Cela peut être limitant car on peut vouloir limiter la longueur des descriptions des randos pour une cohérence éditoriale, mais sans aucun intérêt à appliquer les mêmes limites aux descriptions des chantiers, interventions, signalétique... où il n'y a pas d'enjeu éditorial.

Et même pour un même module, on peut vouloir appliquer une limite de 1000 caractères pour la description, mais de 200 caractères pour le chapeau.

A voir à terme si il faut pouvoir préciser ce paramètre par module, voire par champs. Un peu complexe, mais possiblement nécessaire pour rendre cette fonctionnalité pertinente et opérationnelle.

**Comment by camillemonchicourt** [comment]
Ce fonctionnement a été revu et amélioré dans la version 2.102.2 pour être défini champs par champs avec le nouveau paramètre `MAX_CHARACTERS_BY_FIELD` qui remplace le paramètre `MAX_CHARACTERS`. 

Voir https://github.com/GeotrekCE/Geotrek-admin/issues/3844
