### ISSUE TITLE
Contrôler la taille des images téléchargées

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2902]
Refuser le téléversement d'images trop petites (en pixel) ou trop grosses (en poids)

CM : Activable ou non, taille paramétrable

**Comment by LePetitTim** [comment]
Pour info: 
Il existe deja PAPERCLIP_MAX_ATTACHMENT_WIDTH qui reduit la taille de l'image si elle est trop large

**Comment by camillemonchicourt** [comment]
Oui de ce fait, il n'est peut-être pas pertinent ni utile de pouvoir une taille max d'upload

**Comment by numahell** [comment]
PR #3171

**Comment by camillemonchicourt** [comment]
Fait dans la 2.85.0 : 
- Add setting ``PAPERCLIP_MAX_BYTES_SIZE_IMAGE`` unallow usage of huge image
- Add setting ``PAPERCLIP_MIN_IMAGE_UPLOAD_WIDTH`` unallow usage of images with small width
- Add setting ``PAPERCLIP_MIN_IMAGE_UPLOAD_HEIGHT`` unallow usage of images with small height
- These settings will influence the attachments downloaded in parsers
