### ISSUE TITLE
Créer une alerte mail lorsque la case "en attente de publication" est cochée dans un itinéraire ou un POI

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2903]

**Comment by camillemonchicourt** [comment]
Email du destinataire configurable.
Si non renseigné, pas d'alerte email pour ceux qui ne souhaiteraient pas utiliser ce système d'alertes emails.
A documenter.

**Comment by numahell** [comment]
PR #3160

**Comment by camillemonchicourt** [comment]
Fait dans la 2.85.0 : 
Add setting ``ALERT_REVIEW`` (default : True) which send mail whenever an object has been changed to review.

L'email est envoyé à l'adresse définie dans le paramètre ``MAIL_MANAGERS``.
