### ISSUE TITLE
Créer une alerte mail lorsque la case "brouillon" a été cochée pour les tronçons

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#2904]

**Comment by camillemonchicourt** [comment]
Email du destinataire configurable.
Si non renseigné, pas d'alerte email pour ceux qui ne souhaiteraient pas utiliser ce système d'alertes emails.
A documenter.

**Comment by numahell** [comment]
En lien avec la #2903

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain que les notions de GROUPE_GESTION et GROUPE_VALORISATION soient bien compréhensibles.
Déjà car le terme GROUPE est déjà utilisé pour les groupes d'utilisateurs et cela peut donc apporter de la confusion.
Aussi car les notions de GESTION et de VALORISATION sont parfois floues selon les usages de Geotrek.

Mais c'est vrai que ce serait certainement plus pertinent de s'appuyer sur les utilisateurs existants dans Geotrek pour définir à qui envoyer les emails, plutôt que de créer des paramètres avec des emails à chaque fois (comme on a actuellement ``ADMINS`` et ``MANAGERS``). Quoique dans notre cas au PNE, pour ces 2 paramètres ils ne sont pas liés à des emails de personnes, mais à des listes de diffusion générique.

Je n'ai plus en tête comment les emails à notifier dans le mode Workflow de Suricate, mais il y a peut-être une approche globale à clarifier, homogénéiser ?

**Comment by camillemonchicourt** [comment]
Fait dans la 2.86.0 avec l'ajout d'un paramètre ``ALERT_DRAFT`` (à FALSE par défaut).

Par contre, j'ai pas compris à quoi correspond ``MAIL_MANAGERS`` à qui les emails sont envoyés ?
C'est un paramètre où l'on renseigne des emails ?
Je n'en vois pas de trace.

**Comment by numahell** [comment]
C'est un problème dans la doc de Geotrek, c'est en fait `MANAGERS`. Si ce paramètre n'est pas renseigné, c'est `ADMINS` qui est utilisé : https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-MANAGERS
