### ISSUE TITLE
APIv2 should not return HTML content on empty routes

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#2916]
When requesting an endpoint that does not exist on `/api/v2` we still receive some HTML content along with 404 status code

![image](https://user-images.githubusercontent.com/26015573/150383521-7410d2db-2f03-4898-b092-7c27a23abf36.png)

We should get an empty JSON instead

This causes crashes on Rando v3 trying to parse some JSON content from missing routes

**Comment by babastienne** [comment]
Fixed in https://github.com/GeotrekCE/Geotrek-admin/pull/3656

**Comment by babastienne** [comment]
Available in release [2.100.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.100.0)
