### ISSUE TITLE
Question concernant le comportement des étiquettes

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2920]
Gtk-admin : 2.75.0
GTk-Rando-V3 : 3.5.3

Lors de l'assignation d'une étiquette sur Geotrek-Rando, celle-ci remonte dans les recommandations :

<img width="770" alt="Capture d’écran 2022-01-24 à 11 24 14" src="https://user-images.githubusercontent.com/45095227/150765697-f11d97d7-db1e-4cc5-bb82-063a7cf1844e.png">

Voici le résultat sur Geotrek-Rando (voir section Recommandations de l'itinéraire) : https://www.rando-aubrac.fr/trek/44235-Aubrac-au-Coeur,-de-Nasbinals-au-Village-d-Aubrac

Je ne sais plus quelle était l'utilité du champ étiquette, et je n'ai pas trouvé dans la doc d'informations sur ce champ. De plus, on peut y associer un pictogramme, mais celui ne remonte pas sur le rando (le format du pictogramme est conforme à ce que j'ai pu trouver dans la doc).

**Comment by JeanLenormand** [comment]
Bonjour Michael, 

Avec cette config. : GTA: 2.74.1 / GTRv3 3.5.4

J'ai pu charger des image en .png qui s'affichent bien côté GTR.

Par contre, les étiquettes renseignées dans l'admin-site côté GTA n'apparaissent pas dans les filtres de GTR (l'option "Filtre/Voir cette étiquette en tant que filtre sur le portail public" étant bien cochée).

Je note aussi côté GTR que lorsque plusieurs étiquettes sont attribuées à un itinéraire, leurs vignettes sont collées entre elles sans espacement:
![capture etiquette](https://user-images.githubusercontent.com/33653562/150785128-798c9ea1-a785-4e94-a78f-c09e238e7288.png)

Enfin, côté GTA, lorsqu'une ou plusieurs étiquettes sont attribuées à un itinéraire, ces informations n'apparaissent pas dans les données attributaires (volet gauche), sur la fiche de l'itinéraire.

**Comment by camillemonchicourt** [comment]
La mise en place des étiquettes pour pouvoir associer des recommandations ou informations structurées et partagées à des randos mais aussi à des sites outdoor a été discuté et détaillé ici : https://github.com/GeotrekCE/Geotrek-admin/issues/2362

Les icones fonctionnent bien de mon côté, ici en SVG : https://gtr3demo.ecrins-parcnational.fr/trek/771-Une-rando-plus-loin
Ici en PNG pour "En coeur de parc" : https://rando.ecrins-parcnational.fr/trek/903486-Boucle-du-Pigeonnier-dans-le-cirque-du-Gioberney

Dans Geotrek-admin, on peut associer une ou plusieurs étiquettes à un itinéraire ou un site outdoor.
On peut filtrer les itinéraires et sites outdoor par étiquette.

Les étiquettes sont bien affichées dans les fiches des itinéraires ("Chiens en laisse" et "Cœur de parc" dans cet exemple) : 
![Capture d’écran de 2022-01-25 00-36-15](https://user-images.githubusercontent.com/4418840/150883199-d015b2fe-ed4e-4698-87f8-733685fd6537.png)

-----------------------------

En effet pour l'amélioration de leur affichage dans Geotrek-rando-v3, à remonter au niveau du dépôt Geotrek-rando-v3.
Idem pour les filtres par étiquette qui sont à intégrer au niveau de Geotrek-rando-v3 (coming soon) : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/418
