### ISSUE TITLE
Django bug causes missing indexes in database

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-admin#2932]
A django bug cause some indexes are missing in database, even if spatial_index=True is defined in model.

We should add them in Meta.indexes or directly in migrations.

I will prepare a PR as soon as possible

**Comment by camillemonchicourt** [comment]
Oooch thanks for finding this issue.
It will require to reindex the whole database in a next migration/release ?

**Comment by submarcos** [comment]
No need to reindex the whole database, but missing indexes will be added on core_path.geom,  core_path.geom_cadastre,  core_path.geom_3d,  core_topology.geom,  core_topology.geom_3d and some others columns. SO next migration will take some LONG time

**Comment by camillemonchicourt** [comment]
OK thanks. It should improve performances ! :+1:
