### ISSUE TITLE
Parser OpenSystem / IntegrityError : null value in column "reservation_id" violates not-null constraint

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2952]
En 2015, nous avons mis en place la possibilité de renseigner un système de réservation externe pour les itinérances :  https://github.com/GeotrekCE/Geotrek-admin/issues/1478

En 2020, ce système a été repris pour pouvoir se connecter à l'API d'OpenSystem et récupérer pour un trek donné par son identifiant, l'info de savoir si il est réservable sur la plateforme OpenSystem et quel est son ``reservation_id`` dans OpenSystem : https://github.com/GeotrekCE/Geotrek-admin/pull/2299

J'ai un parser qui y correspond dans mon fichier /opt/geotrek-admin/var/conf/parser.py : 

```
######### Import Reservation ################

class ItineranceParser(Parser):
    label = u"Itinerance OpenSystem"
    url = 'https://e-iti-cms.open-system.fr/v2/2.9.6/routes'
    api_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    model = Trek
    eid = 'id'
    update_only = True
    delete = False
    fields = {
        'id': 'id',
        'reservation_id': 'id',
    }
    constant_fields = {
        'reservation_system': "Itinérance",
    }
    natural_keys = {
        'reservation_system': 'name',
    }

    @property
    def items(self):
        return self.root['data']

    def next_row(self):
        response = self.request_or_retry(self.url, headers={'Authorization': self.api_key})
        self.root = response.json()
        self.nb = int(self.root['nb'])
        for row in self.items:
            yield row

    def normalize_field_name(self, name):
        return name

    def filter_id(self, src, val):
        match = re.search(r'ITI-\d+-GEOT-(\d+)', val)
        if not match:
            raise RowImportError("Wrong if format {}".format(val))
        return match.group(1)

    def end(self):
        """Disable reservation for treks no not more in list"""
        treks = Trek.objects.filter(pk__in=self.to_delete)
        treks = treks.exclude(reservation_system=None, reservation_id=None)
        treks.update(reservation_system=None, reservation_id=None)
```

Mais quand je lance cet import, j'ai une erreur :

```
IntegrityError : null value in column "reservation_id" violates not-null constraint DETAIL: Failing row contains (Tour de la Bérarde, , Tour de la Bérarde, , La Bérarde, , La Bérarde, , , , , ,
Le Tour de la Bérarde invite durant 4 jours à l..., ,

Le Tour de la Bérarde invite durant 4 jours à l..., ,

Du hameau de La Bérarde, berceau de l'alpinisme, la pr..., ,

Du hameau de La Bérarde, berceau de l'alpinisme, la pr..., ,

Au cœur du massif des Écrins, l'ambiance est &ag..., ,

Au cœur du massif des Écrins, l'ambiance est &ag..., , 96, Parking de la Bérarde,

Gare routière de Grenoble : 04 76 87 90 31

...,

Su..., ,

Su..., , 6, 4, null, , , , , 952958, f,

Depuis Bourg d'Oisans ou depuis la Grave, emprunter la D1091,..., ,

Depuis Bourg d'Oisans ou depuis la Grave, emprunter la D1091,..., , ,

Gare routière de Grenoble : 04 76 87 90 31

..., , Parking de la Bérarde, null, f, f, , f, , null, 4, 1, f, null, null, null, null).
```

On dirait qu'il essaie d'insérer une valeur nulle dans le champs ``id_reservation``.

Je vois 2 éléments : 

- Il y a potentiellement un soucis et il n'arrive pas à récupérer l'``id_reservation`` au niveau de l'API OpenSystem
- Pourquoi le champs ``id_reservation`` est en NOT NULL alors que ce n'est pas un champs obligatoire de la table ``trekking_trek`` ?

**Comment by camillemonchicourt** [comment]
Voici ce que renvoie l'API : 

```
{
    "data": [
        {
            "id": "ITI-65682-GEOT-958960",
            "href": "https://e-iti-cms.open-system.fr/v2/2.9.6/routes/ITI-65682-GEOT-958960",
            "lastPublished": "2021-12-06T15:19:10.647+01:00"
        },
        {
            "id": "ITI-65682-GEOT-921156",
            "href": "https://e-iti-cms.open-system.fr/v2/2.9.6/routes/ITI-65682-GEOT-921156",
            "lastPublished": "2021-12-06T15:19:11.477+01:00"
        },
        {
            "id": "ITI-65682-GEOT-938574",
            "href": "https://e-iti-cms.open-system.fr/v2/2.9.6/routes/ITI-65682-GEOT-938574",
            "lastPublished": "2021-12-06T15:19:13.57+01:00"
        },
        {
            "id": "ITI-65682-GEOT-940370",
            "href": "https://e-iti-cms.open-system.fr/v2/2.9.6/routes/ITI-65682-GEOT-940370",
            "lastPublished": "2021-12-08T08:17:25.83+01:00"
        },
        {
            "id": "ITI-65682-1028",
            "href": "https://e-iti-cms.open-system.fr/v2/2.9.6/routes/ITI-65682-1028",
            "lastPublished": "2021-12-16T15:46:06.147+01:00"
        }
    ],
    "nb": 5
}
```

**Comment by camillemonchicourt** [comment]
OK je n'avais pas cette habitude de mettre les champs de texte de NOT NULL même quand ils ne sont pas obligatoires et je ne connaissais pas cette pratique.
Mais pourquoi pas, même si cela complique l'intégration de données quand on passe par QGIS ou autre.
J'avais par exemple été étonné (et un peu embêté) de tous les champs non obligatoires mais en NOT NULL quand j'avais importé des données dans la table des contenus touristiques.

Mais OK, je comprends mieux les NOT NULL.

---------------

OK pour le parser, là dans mon cas l'API renvoie bien un ``id`` pour les 5 itinéraires concernés, mais elle doit bloquer sur les autres itinéraires.
La question que je me pose est pourquoi elle cherche à modifier ou insérer des données pour des itinéraires qu'elle ne trouve pas dans l'API, et pourquoi ce parser fonctionnait auparavant.

Je pense en effet qu'il faut revoir un peu ce parser.

Merci.

**Comment by submarcos** [comment]
Effectivement la gestion avec QGis change un peu la donne. Les colonnes varchar doivent etre en NOT NULL, mais avec un DEFAULT ''. il faut s'assurer que c'est le cas car je pense que django ne définit pas les DEFAULT coté BDD mais uniquement pour le code python (à vérifier - çà causerait les problemes avec QGIs mais il y a deja des cas géré dans les scripts SQL de geotrek). Par contre si un parser recupere une valeur NULL/None, elle sera utilisée explicitemment et donc le DEFAULT '' ne sera pas utilisé. D'ou l'erreur. Dans tous les cas il faudra revoir ce parser effectivement et le résultat attendu pour que ce soit fonctionnel tel qu'attendu

**Comment by camillemonchicourt** [comment]
OK oui, avec un un DEFAULT à '' alors ça ferait mon affaire. 
J'avais surtout remarqué cela en voulait intégrer des données dans la table ``tourism_touristiccontent`` qui a pas mal de champs en NOT NULL, donc ça vaudrait le coup de leur ajouter cette valeur par défaut, et même de faire un tour un peu général sur la BDD pour le faire partout où c'est pertinent : 

![Capture d’écran de 2022-02-16 09-48-45](https://user-images.githubusercontent.com/4418840/154228670-d555c027-fec4-491c-b045-c850ce3ec83a.png)

**Comment by camillemonchicourt** [comment]
OK donc pour le soucis du parser, comme indiqué par @submarcos et @LePetitTim, j'ai changé la partie 

```
        treks = treks.exclude(reservation_system=None, reservation_id=None)
        treks.update(reservation_system=None, reservation_id=None)
```

en :

```
        treks = treks.exclude(reservation_system=None, reservation_id='')
        treks.update(reservation_system=None, reservation_id='')
```

Désormais l'import depuis l'API OpenSystem fonctionne bien.
