### ISSUE TITLE
BiodivParser se limite par défaut à la page 1 ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2966]
J'ai mis en place l'import des zones sensibles dans mon Geotrek-admin à partir de l'API de https://biodiv-sports.fr.

Je n'ai pas surcouché le parser, j'utilise celui fourni par défaut (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/sensitivity/parsers.py#L8).
La documentation (https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/import.rst#sensitive-areas-import) indique que si on l'utilise par défaut, cela va filtrer l'API sur la bbox de mon territoire définie dans la configuration de mon Geotrek-admin, ce qui me va très bien.

Mais à chaque fois que le lance l'import "Biodiv'Sports", il m'importe 100 zones sensibles. 
Il me manque des zones sensibles sur mon territoire et j'ai vérifié en interrogeant directement l'API avec la bbox de mon Geotrek-admin : https://biodiv-sports.fr/api/v2/sensitivearea/?in_bbox=5.7626037%2C44.3943995%2C6.6933258%2C45.1782573

Cela renvoie 134 zones sensibles.
On dirait donc que le parser par défaut ne boucle pas sur les différentes pages mais renvoie uniquement celles de la première page, l'API devant limiter à 100 résultat par défaut si on indique pas le paramètre ``page_size`` ?

Je ne sais pas si cela peut être corrigé au niveau du parser par défaut, ou si il faut que je surcouche le parser localement ?

**Comment by thomaspnrhj** [comment]
Hello,
Pour info, de notre côté, le parser est surbcuché dans parsers.py en filtrant sur la structure car il y a pour l'instant pas d'autres contributeurs sur le territoire

from geotrek.sensitivity.parsers import BiodivParser

class PNRHJBiodivParser(BiodivParser):

    url = 'https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4'

    label = "Biodiv'Sports PNRHJ"

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.77.3 où le parser Biodiv'Sports boucle sur les pages suivantes au-delà de la limite par défaut de 100 objets renvoyés par page de l'API v2.
