### ISSUE TITLE
Fermeture modale filtres sur tablette

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2968]
Le bouton de fermeture de la modale des filtres passe sous la fenêtre du navigateur : 
![image](https://user-images.githubusercontent.com/4418840/154332000-2be8c269-91aa-4abf-8558-58d29b585c20.png)

Le bouton reste utilisable en desktop, mais devient quasiment inutilisable sur une tablette avec un écran tactile.

J'ai l'impression qu'en modifiant le ``transform: translate3d(902px, 5px, 0px)`` en ``transform: translate3d(902px, 15px, 0px)`` cela permet de baisser la modale et de rendre le bouton de fermeture plus accessible, mais j'ai l'impression que cette propriété est générée dynamiquement, et cela se joue certainement au niveau de Django-mapentity plutôt que dans Geotrek-admin ?

![Capture d’écran de 2022-02-16 19-32-58](https://user-images.githubusercontent.com/4418840/154332480-1fa42ff8-9ea7-4d57-bfbb-9d520bd7e551.png)

**Comment by babastienne** [comment]
Fixé dans la release [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0)
