### ISSUE TITLE
Erreur de génération de PDF

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2972]
Bonjour,

J'ai une erreur de génération de PDF : 
 ```
INFO 2022-03-04 10:08:26,337 mapentity.helpers Request to: http://localhost:6543/?url=https%3A//geotrek.cotesdarmor.fr/api/fr/treks/276911/profile.svg&from=image/svg%2Bxml&to=image/png
ERROR 2022-03-04 10:08:26,346 mapentity.helpers Request on http://localhost:6543/?url=https%3A//geotrek.cotesdarmor.fr/api/fr/treks/276911/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=400)
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 104, in download_to_stream
    source = get_source(url, headers)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 89, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://localhost:6543/?url=https%3A//geotrek.cotesdarmor.fr/api/fr/treks/276911/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=400)
INFO 2022-03-04 10:08:26,454 mapentity.helpers Headers sent: {'Accept-Language': 'fr'}
```

Auriez-vous une idée ?

**Comment by camillemonchicourt** [comment]
Quelle version de Geotrek-admin ?

Le message semble indiquer que le profil altimétrique de la rando 276911 n'est pas accessible.
As-tu vérifié si cette rando n'est pas cassé ou n'a pas de soucis au niveau de son profil altimétrique ?

Tu peux regarder dans ``/opt/geotrek-admin/var/media/profiles/``.

**Comment by jeromesourdin** [comment]
Version 2.76.3. Le fichier fait 0 Ko... L'itinéraire semble bon. 
Il y a donc un problème de génération du fichier. Comment sont-ils générés ?

**Comment by camillemonchicourt** [comment]
OK dans ce cas, le plus simple à tester est de supprimer le fichier.
Le profil devrait être re-généré lors de la prochaine ouverture de la fiche de la rando et/ou lors de la prochaine synchro.
A voir si il a alors toujours un soucis ?

**Comment by camillemonchicourt** [comment]
Alors là je ne maitrise pas.
Avec ``convertit`` je crois mais je n'en sais pas plus.

**Comment by jeromesourdin** [comment]
J'ai trouvé d'où venait le problème ! Nous avons changé notre certificat, et le serveur ne trouvait pas l'AC...
