### ISSUE TITLE
Extraire le pourcentage de goudron et autres types via un tronçon ou un itinéraire

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#2975]
Bonjour
Je dois calculer la part de goudron sur un secteur donné. Il existe une rubrique "type de voie". Dois-je utiliser cette rubrique ? Est-ce que Geotrek permet d'extraire le linéaire de chaque type de voie d'un tronçon ou d'un itinéraire (fichier Excel ou autre) pour pouvoir calculer le pourcentage ? Faut-il utiliser les tronçons ou les itinéraires ?
Merci d'avance pour votre retour.
Bonne journée.
Audrey Rémy

**Comment by camillemonchicourt** [comment]
Oui cela semble le plus simple et adapté.

Dans le module Statuts / Types de voie, tu verras celles qui sont renseignées : 

![image](https://user-images.githubusercontent.com/4418840/157005149-ce69cd44-b2ae-408f-a74a-2caeb6fc5fba.png)

Tu peux alors filtrer sur un type de voie : 

![image](https://user-images.githubusercontent.com/4418840/157005196-caecb12e-acff-4185-8284-29c55afca076.png)

La carte et la liste seront alors filtrés sur le type choisi : 

![image](https://user-images.githubusercontent.com/4418840/157005285-b7a929cf-f6db-4009-a518-e34e3c3f7018.png)

Tu peux alors exporter le résultat en CSV ou SHP (ou GPX) : 

![image](https://user-images.githubusercontent.com/4418840/157005370-7072aee6-24d2-4694-a36e-374eeb7ce66f.png)
 
Tu auras alors le fichier tableur avec tous les statuts de ta recherche, incluant la longueur de chacun : 

![image](https://user-images.githubusercontent.com/4418840/157005470-d6f80a81-eebe-41cb-b842-26c0a6a4ef33.png)

J'ai juste noter une petite limite qui est qu'actuellement le fichier exporté ne contient que la longueur 3D, mais pas la longueur 2D, et je l'ai noté en évolution souhaitée (https://github.com/GeotrekCE/Geotrek-admin/issues/2976).

Vu que ces données sont aussi dans la BDD PostGIS de Geotrek, il est possible de les exporter directement en SQL dans la BDD.
Il est aussi de calculer des % directement en SQL dans la BDD, mais là il faut un peu rentrer dans la structuration de la BDD.

Exemple de base pour lister tous les statuts "Type de voie" avec leur type, leur longueur et leur géométrie : 

``` SQL
SELECT p.topo_object_id, pt.name, t.length, t.geom FROM land_physicaledge p
JOIN land_physicaltype pt ON pt.id = p.physical_type_id
JOIN core_topology t ON t.id = p.topo_object_id
```

Si tu veux la liste des tronçons utilisés par par des statuts "Type de voie" avec leur segmentation dynamique (PK début et PK fin) : 

``` SQL
SELECT p.topo_object_id, pt.name, pa.path_id, pa.start_position, pa.end_position, t.length, t.geom FROM land_physicaledge p
JOIN land_physicaltype pt ON pt.id = p.physical_type_id
JOIN core_topology t ON t.id = p.topo_object_id
JOIN core_pathaggregation pa ON pa.topo_object_id = t.id
```

**Comment by AudreyRemy** [comment]
Merci Camille
