### ISSUE TITLE
Fichiers liés - Lien d'image externe non fonctionnel

### ISSUE THREAD

**Issue by samuelpriou** [GeotrekCE/Geotrek-admin#3001]
Bonjour,
Nous utilisions la version 2.7.4 de Geotrek admin.
Nous souhaitons utiliser le lien vers une image externe dans le module signalétique. Or il est impossible d'appeler une url. 
![geotrek_signal](https://user-images.githubusercontent.com/9743288/158367002-180769be-d8bc-4da9-b2a4-2f207f1895fb.jpg)

Le mode Lien d'image externe ne s'adapte pa s à une url externe. Ce lien reprend le mode fichier ou URL Youtube.
Est il prévu de corriger ce bug ?

Merci

**Comment by camillemonchicourt** [comment]
En effet.
C'est pas le cas seulement sur la signalétique, mais aussi sur les autres modules.
Vu sur Itinéraires.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.77.3.
Par contre y a un petit effet de bord.
Quand on accède à l'onglet des fichiers liés, par défaut il coche "URL Youtube/Soundcloud" mais en proposant un upload de fichier.

![Capture d’écran de 2022-03-18 16-04-35](https://user-images.githubusercontent.com/4418840/159028526-3ef92f6a-2073-455c-a163-0346f70eb9bf.png)

Ça devrait être l'option "Fichier" qui est cochée par défaut.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.80.0
