### ISSUE TITLE
Renseigner les valeurs par défaut des colonnes avec contrainte `NOT NULL`

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3008]
Comme vu avec le ticket #2952, plusieurs colonnes de la base de données ont une contrainte `NOT NULL`mais pas de valeur par défaut renseignée, ce qui oblige à la renseigner "manuellement" lors d'un import de données automatisé.
Des exemples de colonnes qui me posent problème pour du renseignement automatisé de la BDD et la valeur par défaut que je pense convenir : 
`core_topology.geom_need_update` | False
`core_topology.offset` | 0
`core_topology.deleted` | False
`trekking_poi.review`| False
etc.

Est-ce que ces valeurs par défaut sont présentes dans l'ORM Django ? Si oui à quel endroit, et est-ce que ça ne serait pas pertinent de répliquer cette information directement dans la base de données ?

**Comment by camillemonchicourt** [comment]
Oui, à faire selon moi aussi.

**Comment by camillemonchicourt** [comment]
Des valeurs par défaut ont été ajoutées sur la plupart des champs de la BDD dans la version 2.81.0 : https://github.com/GeotrekCE/Geotrek-admin/pull/3055/files
