### ISSUE TITLE
Contenus touristiques changer statut publié en non publié

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3019]
Bonjour,
Existe-t-il une procédure pour passer tous les éléments d'un contenu touristique (ou POI) de l'état publié à non publié (et inversement) pour éviter de décocher l'élément "publié" un par un en allant sur les fiches ?
Merci pour votre retour.
Bonne journée

**Comment by camillemonchicourt** [comment]
Non, il faut modifier chaque objet un par un pour les publier/depublier.
Sinon cela peut être fait globalement directement en SQL dans la base de données.

On pourrait imaginer pouvoir le faire directement depuis la liste des objets pour les publier par lot, mais attention, la publication se fait par langue.

**Comment by AudreyRemy** [comment]
C'est noté. Merci Camille

**Comment by babastienne** [comment]
L'autre option (similaire à un update SQL), consiste à le faire en python directement.
Si vous avez accès à vote serveur vous pouvez lancer un terminal python via la commande `sudo geotrek shell`
Puis avec les quelques lignes suivantes vous pouvez mettre à jour la status de publication des contenus touristiques : 
```python
from geotrek.tourism.models import TouristicContent

# La méthode 'all' ci-dessous récupère tous les éléments existants mais il est possible de filtrer les contenus touristiques pour n'en sélectionner que certains grâce à la méthode 'filter'

for content in TouristicContent.all(): 
    content.published_fr = False
    # Possible de changer la langue ou de change le status de plusieurs langues d'un coup
    content.save()

```
