### ISSUE TITLE
Fiche pdf et fond de carte

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3025]
Bonjour,
J'ai noté que le fond de carte qui remonte sur les fiches pdf téléchargeables dépend du 1er fond paramétré dans Geotrek-Admin.
Certaines fiches pdf récupèrent bien le 1er fond et d'autres ne remontent qu'un fond noir.
Avez-vous le même problème ?
Ai-je un paramétrage à vérifier ?
Merci et bonne journée.

**Comment by camillemonchicourt** [comment]
Les cartes dans les PDF sont générées par le serveur Geotrek-admin la première fois où elles sont demandées.
Ensuite elles sont stockées dans le dossier ``/opt/geotrek-admin/var/media/maps/``.
Elles sont regénérés si la rando est modifiée.

Si certaines sont OK et d'autres ont un fond de carte noir, alors il est possible que le flux utilisé (IGN ?) n'ait pas répondu au moment où la carte de certaines randos a été générée.
Tu peux tenter de supprimer les cartes des randos qui ont un soucis dans le dossier ``/opt/geotrek-admin/var/media/maps/`` et de redemander leur PDF pour voir si le fond de carte est toujours noir.

**Comment by LePetitTim** [comment]
Il y a eu pas mal de problème ces dernier temps avec les fonds de plan IGN donc c'est clairement une possibilité. 
La solution de supprimer le dossier est la meilleure.

**Comment by AudreyRemy** [comment]
Merci Camille et LePetitTim. Cela fonctionne après suppression des .png qui avaient un soucis.
J'en profite pour vous demander s'il est possible de gérer l'affichage des POI sur le fond de carte de la fiche PDF ? Parfois il y en a beaucoup trop qui remontent et le carte devient illisible. 
Merci à vous et bonne journée.

**Comment by camillemonchicourt** [comment]
OK pour les fonds de carte des PDF, tant mieux.

Pour les POI sur les cartes dans les PDF, il existe des paramètres pour ne pas afficher certains objets sur la carte du PDF : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L571-L575

Pour les POI, il s'agit du paramètre ``SHOW_POIS_ON_MAP_SCREENSHOT = True``, mais si on le passe à ``false``, alors les POI ne seront plus affichés sur aucune carte dans les PDF.

**Comment by AudreyRemy** [comment]
Merci Camille

**Comment by AudreyRemy** [comment]
@camillemonchicourt peux-tu me préciser l'emplacement du fichier base.py à modifier ? J'ai de nombreux fichier base.py mais ne trouve pas le bon. Dois-je modifier directement ce fichier ou fonctionner avec un système de fichier de sur-couche comme pour les pdf ? 
Est-ce que pour la signalétique le paramètre est  SHOW_SIGNAGES_ON_MAP_SCREENSHOT ?
Merci d'avance.

**Comment by camillemonchicourt** [comment]
Il ne faut surtout pas toucher ou modifier le fichier ``base.py``. Et pour le trouver, le lien est plus haut dans mon commentaire.
Ce fichier contient la liste de TOUS les paramètres existants et de leurs valeurs par défaut.

Comme indiqué dans la doc (https://geotrek.readthedocs.io/en/latest/advanced-configuration.html), il est possible de surcoucher tous ces paramètres dans le fichier ``custom.py``.

Oui l'affichage ou non de la signalétique sur la carte des PDF est géré avec le paramètre ``SHOW_SIGNAGES_ON_MAP_SCREENSHOT``.

**Comment by AudreyRemy** [comment]
Bonjour,
J’ai essayé pour la signalétique mais elle remonte sur le pdf alors que je ne la vois pas sur le site (exemples sur ces fiches : https://geotrek-rando-test.le64.fr/trek/11602-Le-sentier-des-contrebandiers---De-Col-d-Ehorrieta-a-St---Martin-d-Arossa---equestre, https://geotrek-rando-test.le64.fr/trek/12096-GR-8-De-Urt-a-Cambo-les-Bains).
Voilà ce que j’ai fait :
J'ai supprimé les fichiers png dans opt/geotrek-admin/var/media/maps
cd /opt/geotrek-admin/var/conf/
sudo nano custom.py
J’ai ajouté la ligne : SHOW_SIGNAGES_ON_MAP_SCREENSHOT = False
sudo service geotrek restart
Si vous avez une idée du problème.
Merci d'avance.
Bonne journée

**Comment by camillemonchicourt** [comment]
Salut, si tu as fait tout ça, il faudrait vérifier si le paramètre ``SHOW_SIGNAGES_ON_MAP_SCREENSHOT `` a un soucis et n'est pas pris en compte ?

Sinon dans tous les cas, je crois que si tu ne publie pas les signalétique, elles ne remontent pas sur les PDF (à tester, vérifier).

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt, comment dois-je faire pour tester le paramètre ?
J'aurais aimé que la signalétique remonte sur le site (données intéressantes si un jour le hors ligne fonctionne) mais pas sur le pdf (carte surchargée) mais en effet en dernier recours je ferais comme tu conseilles.

**Comment by camillemonchicourt** [comment]
> comment dois-je faire pour tester le paramètre ?

Si tu l'as passé à ``False`` et que les signalétiques remontent toujours dans les PDF, alors tu as fait le test et cela indique que le paramètre n'est pas pris en compte. A vérifier avec un développeur quand même je pense.

Concernant l'affichage des signalétiques sur Geotrek-rando-v3, le développement est en cours : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/408

PS : Concernant le OFFLINE, j'ai fait des tests sur d'autres instances de Geotrek-rando-v3 et ça fonctionnait bien. A creuser, analyser et discuter sur les tickets dédiés côté Geotrek-rando-v3
