### ISSUE TITLE
Mise à jour de la clé du package

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3044]
Le clé du package Geotrek-admin sur https://packages.geotrek.fr a expiré le 30 mars 2022.

Ainsi si vous tentez de mettre à jour Geotrek-admin avec la commande ``sudo apt-get update`` puis ``sudo apt-get upgrade`` vous pouvez rencontré un message de ce type : 

```
Err :6 https://packages.geotrek.fr/ubuntu bionic InRelease                                
  Les signatures suivantes ne sont pas valables : EXPKEYSIG F665463098D52B2E Geotrek team <support.geotrek@makina-corpus.com>
15,6 Mo réceptionnés en 3s (5 850 ko/s)               
Lecture des listes de paquets... Fait
W: Une erreur s'est produite lors du contrôle de la signature. Le dépôt n'est pas mis à jour et les fichiers d'index précédents seront utilisés. Erreur de GPG : https://packages.geotrek.fr/ubuntu bionic InRelease : Les signatures suivantes ne sont pas valables : EXPKEYSIG F665463098D52B2E Geotrek team <support.geotrek@makina-corpus.com>
W: Impossible de récupérer https://packages.geotrek.fr/ubuntu/dists/bionic/InRelease  Les signatures suivantes ne sont pas valables : EXPKEYSIG F665463098D52B2E Geotrek team <support.geotrek@makina-corpus.com>
```

La clé a été renouvelée pour 10 ans, mais il faut que vous récupériez cette nouvelle clé sur votre serveur où est installé Geotrek-admin.

Pour cela, il faut lancer une fois la commande ``wget -O- "https://packages.geotrek.fr/geotrek.gpg.key" | sudo apt-key add -`` puis vous pourrez alors lancer la mise à jour avec ``sudo apt-get update`` puis ``sudo apt-get upgrade``.

**Comment by camillemonchicourt** [comment]
Indiqué dans la doc, dans les notes de version de la 2.80.0 et sur la liste de diffusion.

**Comment by AudreyRemy** [comment]
Bonjour
Nous allons faire la mise à jour de notre Geotrek-Admin (actuellement en 2.75) dans les prochains jours.
J'ai transmis l'information ci-dessous à la personne en charge de cette mise à jour mais y a-t-il des pré-requis ou des risques que je devrais également faire remonter ?
Merci d'avance.

**Comment by camillemonchicourt** [comment]
Non rien d'autre.
