### ISSUE TITLE
Taille images

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3059]
Bonjour
Quelle est la taille conseillée des images que nous ajoutons via l'onglet _fichiers liés_ dans Geotrek-Admin pour qu'elles ne soient pas tronquées dans Geotrek-Rando V3 ?
J'ai noté que le format paysage était préférable.
Merci d'avance.
Bonne journée

**Comment by AudreyRemy** [comment]
Je complète ma question en précisant que j'aurais besoin de connaître les dimensions pour que la photo ne soit pas non plus tronquées sur le pdf.
Merci d'avance.

**Comment by camillemonchicourt** [comment]
Dans Geotrek-rando V3 à quel niveau ?
Tu parles des images de la rando sur la fiche rando ?
De leur affichage dans la page ou quand on clique en plein écran ?

Sur les fiches detail, on les affiché dans un bloc qui a un hauteur fixe, mais il faut certainement revoir un peu sa hauteur. 
Donc je ne dimensionnerai pas les images en fonction de leur affichage dans GTR3.
C'est plutôt GTR3 qu'il faut adapter/ajuster selon moi.

On utilise des photos paysages de format classique.

Concernant leur affichage en plein écran, je pense qu'il faut revoir la logique pour ne plus rogner les photos.
Voir https://github.com/GeotrekCE/Geotrek-rando-v3/issues/454

**Comment by AudreyRemy** [comment]
Désolée Camille j'ai oublié de préciser que c'était pour les images des évènements (je pensais que le format était identique que ce soit pour un itinéraire, un évènement ou un autre objet).
J'ai réussi à importer une image non tronquée sur le site mais coupée sur le pdf.
Par exemple : http://geotrek-rando-test.le64.fr/event/7-Allez-les-vers

**Comment by camillemonchicourt** [comment]
Ah OK.
Il vaut mieux rester sur des images avec un format standard et adapter les outils de diffusion (style de GTR et templates des PDF).

Dans ton exemple, sur le PDF c'est pas normal que la petite carte passe sous la photo.

On a fait pas mal d'améliorations des templates PDF dans les versions récentes (2.80 et 2.81), je ne sais pas si ça va corriger ce soucis.

Sinon pour la taille de l'image dans le PDF, on doit l'intégrer dans une zone de taille fixe pour que le rendu soit stable et homogène.
Mais cela peut être ajusté.
Soit dans votre surcouche du template de PDF, soit en faisant évoluer le template par défaut fourni dans Geotrek-admin.

**Comment by AudreyRemy** [comment]
Bonjour,
Ma collègue responsable de la saisi des événements touristiques me demande le format idéal pour que la photo ne soit pas tronquée sur notre site (nous utilisons Geotrek-rando V3). 
Le service communication lui fournit des fichiers format affiche, format réseau sociaux, etc. et elle souhaiterait demander un format Geotrek pour ne pas avoir à redimensionner les fichiers.
J'ai essayé avec la taille 1280 x 720 mais l'image est légèrement tronquée sur notre site (et donc sur le pdf). Je ne sais pas ce qu'est un format standard si ce n'est qu'il faut une image en paysage.
Je ne crois pas que des paramétrages aient été faits sur le template fourni dans notre Geotrek-admin.
Merci d'avance.
Bonne journée.

**Comment by camillemonchicourt** [comment]
J'ai détaillé les pistes côté Geotrek-rando-v3 : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/803
