### ISSUE TITLE
Pages statiques: Lien anglais non pris en compte

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3075]
Si l'on met un lien externe en, il n'est pas pris en compte, c'est le lien spéficié dans le champ fr qui remonte 

![image](https://user-images.githubusercontent.com/3088650/165335871-82035ee4-c27b-404f-9a0e-ccb3d9244ca5.png)
https://geotrek-admin.cevennes-parcnational.net/api/v2/flatpage/?language=en&fields=id,external_url,title,order

```
{
  "count": 5,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 8,
      "title": "The Esprit Parc National brand",
      "external_url": "https://www.espritparcnational.com/destination-parc-national/cevennes",
      "order": 5
    }
  ]
}
```

**Comment by marcantoinedupre** [comment]
Ce bug sera corrigé dans le cadre de la refonte des pages statiques. Voir également #3074 sur ce sujet.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.104.0 (nécessite Geotrek-rando 3.19+) avec le nouveau système d'éléments de menu.
