### ISSUE TITLE
Geotrek-Admin - Ce site est inaccessible ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-admin#3088]
Bonjour,

Je travaille actuellement sur la customisation de la page d'accueil de Geotrek Rando v3 installé sur une VM, donc je joue sans arrêt avec les commandes docker pour identifier le conteneur, le stopper et le relancer. Je ne pense que ce travail ait un impact avec mon problème, mais sait on jamais avec l'informatique...
Sur une autre VM j'ai Geotrek-Admin d'installé. J'y accède via une adresse IP en https ou via un nom de domaine aussi en https.

J'ai l'erreur `Ce site est inaccessible ERR_CONNECTION_REFUSED`

J'ai regardé les causes et les solutions proposées. C'est guère satisfaisant.

C'est la version 2.59.0 qui est installée.
- J'ai rebooté le serveur Ubuntu de Geotrek-Admin = sans succès
- J'ai lancé la commande `sudo supervisorctl status` = commande introuvable. Je voulais lancer la commande `sudo supervisorctl restart all` pour redémarrer l'application Geotrek. Est-ce que cela est toujours valable ? Je ne suis pas sur que ce soit utile et que l'erreur vienne d'un problème applicatif.
- J'ai lancé la commande `sudo service nginx restart` pour redémarrer le serveur web = J'ai un failed. J'ai lancé `systemctl status nginx.service` qui me donne pas plus d'explication sur le failed.

Je ne suis pas sur que le DNS soit aussi la cause du problème, car l'accès via l'IP donne la même erreur.
Est ce que le https pourrait être une piste ?

Je suis preneur pour toute aide pour ré-accéder à mon serveur Geotrek-Admin.

Merci.

**Comment by camillemonchicourt** [comment]
Si j'ai bien compris ton Geotrek-rando-v3 est en docker sur une VM et ton Geotrek-admin est sur une autre VM ?
Dans ce cas-là, il n'y a aucune raison qu'il y ait des conséquences du redémarrage du docker sur la VM de Geotrek-rando-v3 sur la VM qui héberge le Geotrek-admin.

Par contre ton Geotrek-admin est installé classiquement en tant que paquet Debian, ou alors il est installé lui-aussi dans un docker sur sa VM ?

Sinon, depuis la version 2.33 où toute l'architecture de Geotrek-admin a été revue, on utilise désormais ``sudo systemctl restart geotrek`` pour redémarrer Geotrek, qui a remplacé supervisor (car plus robuste notamment).
Mais bon, si tu as déjà redémarré ton serveur, ça ne fera pas mieux.

Par contre, si quand tu redémarres ton NGINX, tu as un failed, cela indique que tu as un soucis au niveau de la conf NGINX de Geotrek-admin. Pas au niveau du Geotrek-admin lui-même.
Le message d'erreur ressemble aussi plus à un soucis au niveau de NGINX qu'au niveau de Geotrek-admin.
Il faudrait que tu ailles voir les logs de NGINX, je pense qu'ils sont dans `/var/log/nginx/errors.log` et là on en saura plus.

Il serait intéressant aussi de savoir ce qui a été modifié entre le moment ou Geotrek-admin fonctionnait et le moment où il n'a plus fonctionné, car ça n'a pas pu se faire tout seul.

PS : C'est hors sujet ici, mais pour ta customisation de Geotrek-rando-v3, pour appliquer les changements, tu n'as pas besoin d'identifier le conteneur, le stopper etc. Il te suffit de lancer la commande `docker-compose restart` (voir https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization.md). En tout cas si tu es bien en version Geotrek-rando-v3 supérieure ou égale à la 3.2.0 avec l'installeur de Geotrek-rando-v3 en version 2.0.

**Comment by Chrispnv** [comment]
Merci Camille !

Je pense que notre Geotrek-Admin vient du paquet Debian, mais j'en suis pas complètement sur. Notre dernier CDD a travaillé principalement sur Geotrek-Rando. Pour info, Geotrek-Admin se trouve dans /opt.

Au niveau de NGINX, a priori l'erreur viendrait du certificat SSL qui a été installé. J'ai le message suivant dans error.log
2022/05/05 06:24:33 [emerg] 34827#34827: invalid number of arguments in "ssl_certificate" directive in /etc/nginx/sites-enabled/geotrek.conf:78
J'ai d'autres fichiers de log qui datent du 14 ou 15 avril. Il est possible que le plantage a commencé à partir de ce moment là.
Le SSL a été installé par notre CDD. Est ce qu'un certificat SSL se périme ?
Aucunes actions de configuration, applicatives... n'ont été effectuées sur le serveur Geotrek-Admin depuis fin 2021.

Donc est ce qu'on a du boulot sur ces certificats ?

PS : Merci pour la commande docker pour la customisation de Geotrek-Rando

**Comment by camillemonchicourt** [comment]
OK, donc si ton Geotrek-admin est dans ``/opt`` alors c'est qu'il est installé classiquement avec le paquet Debian. Tant mieux.
Pour le mettre à jour ``sudo apt-get update`` puis ``sudo apt-get upgrade``.
Si tu veux le mettre à jour (fortement conseillé), attention aux warning de 2 versions qui nécessitent une action préalable spécifique : 
- https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2700-2021-11-02
- https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2800-----2022-04-05

OK tu dois avoir un soucis de certificat SSL en effet, indépendant de Geotrek-admin.
Je ne sais pas comment ton certificat SSL a été mis en place, et comment il était renouvelé.

Pour ma part, on utilise Certbot qui est très simple et automatise aussi le renouvellement du certificat : 

```
## Installer Certbot
sudo apt install certbot
sudo apt install python3-certbot-nginx

## Lancer la commande permettant de mettre en place le certificat sur ce domaine et suivre les instructions
sudo certbot --nginx
```

Attention cependant si tu mets en place le SSL sur ton Geotrek-admin, il faut le répercuter dans le template de conf NGINX qui est utilisé pour créer (et écraser) la conf NGINX de ton Geotrek à chaque mise à jour : https://github.com/GeotrekCE/Geotrek-admin/issues/2170#issuecomment-756784849

Voir aussi : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/install/configuration.rst#activate-ssl--https

**Comment by Chrispnv** [comment]
Bonjour,

Entre tes indications et l'aide de notre ancien CDD Blaise, le problème a été résolu. A priori le certificat SSL s'est désactivé ou a été corrompu ou autre chose.

On a purgé nginx.conf des paramètres concernant le certificat SSL
On a vérifié que Geotrek-Admin fonctionne sans https. Il fonctionnait.
On a relancé le processus d'installation du certificat via certbot : sudo certbot --nginx
On regardé que nginx.conf et nginx.conf.in contiennent bien les paramètres SSL
On a relancé NGINX et Geotrek-Admin en https est à nouveau opérationnel : sudo systemctl restart nginx

Camille merci encore une fois pour ton aide et ta réactivité !

**Comment by camillemonchicourt** [comment]
OK tant mieux. :+1: 
Il ne reste plus qu'à le mettre à jour en version 2.82, car 2.59.0 ça date pas mal et il y a eu beaucoup d'améliorations et corrections depuis. Et aussi pour bien garantir la compatibilité avec les versions récentes de Geotrek-rando-v3 !
