### ISSUE TITLE
Information desk with sites (GRT3 api v2)

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#3095]
La route /informationdesk/ renvoie les lieux associés à des randos, mais pas ceux associés uniquement à des sites outdoor... Cela fait crasher GTR3 dans certains cas...

**Comment by Chatewgne** [comment]
Patch : https://github.com/GeotrekCE/Geotrek-admin/pull/3119/

**Comment by camillemonchicourt** [comment]
OK dans la version 2.83.0.
