### ISSUE TITLE
Geotrek-Admin 2.82.2 : "KeyError: "Key 'draft' not found in 'PathForm"

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3096]
Bonjour, 

il s'agit d'un geotrek de dev cloné à partir d'un geotrek de prod qui est sous version 2.82.1. On a une ERROR 500 dès que l'on tente la création d'un POI ou d'un itinéraire (alors qu'il n'y a pas de problème sur le serveur de prod). Je n'ai jamais rencontré cette erreur avant. Voici les logs en PJ.

[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/8652625/systemd-geotrek-ui.log)
[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/8652635/systemd-geotrek-api.log)
[systemd-geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/8652636/systemd-geotrek-celery.log)

**Comment by camillemonchicourt** [comment]
Je pense que tu as un soucis de cache.
Vide le cache serveur de tes tronçons. Le plus simple est de créer ou modifier un tronçon existant, il va alors régénérer le cache serveur.

Éventuellement vide aussi ton cache navigateur

**Comment by camillemonchicourt** [comment]
Pour vider le cache serveur, tu peux vider le contenu du dossier ``/opt/geotrek-admin/var/cache/``.

**Comment by mviadere-openig** [comment]
C'est fiat, et aucun changements.

**Comment by babastienne** [comment]
Est-ce que ta bdd reflète bien la structure de données correspondante à la version 2.82.1 ?
Tu as tenté de reconfigurer l'appli ? `sudo dpkg-reconfigure geotrek-admin` Ca devrait tenter de relancer les migrations en base de données si besoin.

**Comment by LePetitTim** [comment]
Quelle version de postgis as-tu installé ?

L'erreur importante semble être : 
```psycopg2.errors.InternalError_: Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.```sh

**Comment by mviadere-openig** [comment]
> 

déjà fait plusieurs fois, sans succès.

**Comment by mviadere-openig** [comment]
Ah bien vu pour postgis , je vais regarder ça.

**Comment by mviadere-openig** [comment]
ok la version de postgis sur le serveur est la 2.2, je pense que je ne l'avais pas upgrade à l'époque car il fallait passer à une version supérieure de postgres (qui est en 9.5).
Je suis en train de chercher une méthode efficace pour migrer la BDD sur un postgres plus récent, si vous avez des liens ou commandes pour gagner du temps je suis preneur :)

**Comment by mviadere-openig** [comment]
J'ai fait un dump de la BDD pour mettre à jour postgresql ( de la 9.5 à la 13) et postgis. Voici le détails des commandes : 
[commande_maj_postgres_postgis.log](https://github.com/GeotrekCE/Geotrek-admin/files/8686989/commande_maj_postgres_postgis.log)

Suite à cela on a toujours une erreur 500 lors de la création d'itinéraire, voici les  logs : 
[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/8687052/systemd-geotrek-api.log)
[systemd-geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/8687054/systemd-geotrek-celery.log)
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/8687055/systemd-geotrek-ui.log)

Testé sous différents navigateurs avec le même résultat, Firefox me sort cette erreur : 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/45095227/168283822-f798b1b5-aca1-4e4f-b608-8e2e125e835e.png">

En regardant les logs, je ne vois plsu l'erreur vu précédemment, mais j'en suis toujours au même point.

**Comment by submarcos** [comment]
Ce n'est pas un bug, juste une alerte. en fonction des permissions le champ "draft" est disponible ou pas pour les utilisateurs sur les Path. Or, la disposition définie dans django-crispy-form l'utilise quoi qu'il arrive. Il leve cette alerte juste pour dire que le champ d'existe pas

**Comment by mviadere-openig** [comment]
Merci pour ton retour @submarcos. Notre adhérent nous précise que ce problème est présent depuis le 02 mai.  En faisant la commande `grep -e "ERROR" systemd-geotrek-ui.log > ERROR.log` voici ce que j'ai (le fichier est aussi en PJ) :


`mai 02 14:25:52 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: ERROR 2022-05-02 16:25:52,604 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 02 14:42:19 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: ERROR 2022-05-02 16:42:19,974 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 02 14:44:54 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: ERROR 2022-05-02 16:44:54,331 mapentity.helpers Request on http://localhost:6543/?url=https%3A//admin65-dev.openig.org/document/path-15565.pdf&to=application/pdf failed (status=404)
mai 02 14:48:48 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: ERROR 2022-05-02 16:48:48,618 django.contrib.gis Error creating geometry from value '{'geom': '', 'snap': []}' (Improper geometry input type: <class 'dict'>)
mai 02 14:48:49 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: ERROR 2022-05-02 16:48:49,086 django.contrib.gis Error creating geometry from value '' (String input unrecognized as WKT EWKT, and HEXEWKB.)
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :crispy>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :as_crispy_errors>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :as_crispy_field>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :crispy>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :as_crispy_errors>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :as_crispy_field>:2: (ERROR/3) Error in "default-role" directive:
mai 03 13:39:23 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[29440]: <filtre :tree_info>:2: (ERROR/3) Error in "default-role" directive:
mai 11 13:49:58 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-11 15:49:57,932 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 11 13:50:29 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-11 15:50:29,086 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 12 07:44:51 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 09:44:51,956 fiona._env /tmp/3b63ddf4-39fb-4ec0-8e1b-f1f96f51f96e: Is a directory
mai 12 07:50:58 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 09:50:58,317 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 12 07:51:29 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 09:51:29,495 mapentity.helpers ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
mai 12 08:14:24 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 10:14:24,644 django.contrib.gis Error creating geometry from value '{'geom': '', 'snap': []}' (Improper geometry input type: <class 'dict'>)
mai 12 08:14:25 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 10:14:25,324 django.contrib.gis Error creating geometry from value '' (String input unrecognized as WKT EWKT, and HEXEWKB.)
mai 12 08:26:50 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 10:26:50,276 django.contrib.gis Error creating geometry from value '{'geom': '', 'snap': []}' (Improper geometry input type: <class 'dict'>)
mai 12 08:26:50 openig-geotrek-ccpvg-dev.ataraxie.fr gunicorn[2102]: ERROR 2022-05-12 10:26:50,695 django.contrib.gis Error creating geometry from value '' (String input unrecognized as WKT EWKT, and HEXEWKB.)`
[ERROR.log](https://github.com/GeotrekCE/Geotrek-admin/files/8714511/ERROR.log)


D'ailleurs il y a une chose que je ne comprends pas, lorsque je tente de créer un itinéraire ou un POI qui me crée une erreur 500, et qu'ensuite je récupère les logs, je ne vois rien qui s'affiche à la date où j'ai provoqué l'erreur, est-ce qu'il y a un délai avant de voir les erreurs dans les logs ? Si oui de combien de temps ?

**Comment by Chatewgne** [comment]
Résolu, le problème venait en fait de la synchronisation des colonnes de langues. On a fait une procédure de re-synchronisation entre l'application et la BDD via les commandes SQL générées par `geotrek sync_translation_fields`.
