### ISSUE TITLE
Erreur synchro mobile  

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3097]
Geotrek admin 2.82.1
mon script de synchro de Geotrek-admin pour les données mobiles me fait cette erreur :
[sync_mobile.log](https://github.com/GeotrekCE/Geotrek-admin/files/8659688/sync_mobile.log)

J'ai tenté de supprimer le dossier où sont stockés les données et de relancer une synchro, cela n'a rien changé. 

Mon fichier de synchro : 
[sync_mobile.sh.log](https://github.com/GeotrekCE/Geotrek-admin/files/8659692/sync_mobile.sh.log)

**Comment by LePetitTim** [comment]
Ca a l'air d'etre un problème avec convertit. Regarde les logs de convertit tout d'abord.
sudo systemctl status convertit ou sudo journalctl -eu convertit

**Comment by mviadere-openig** [comment]
Voici les logs : 
[systemd-convertit.log](https://github.com/GeotrekCE/Geotrek-admin/files/8743800/systemd-convertit.log)

**Comment by LePetitTim** [comment]
Désolé, je ne vois pas d'erreur qui peut aider.

**Comment by mviadere-openig** [comment]
Suite au différents contacts avec le support et des recherches de mon côté, voici ce que donne actuellement le message d'erreur :`AssertionError: Request on http://localhost:6543/?url=https%3A//siglr-geotrek-pnrgca.ataraxie.fr/api/en/treks/6106/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=400)`

Une piste de solution pour moi est qu'il n'arrive pas à trouver l'image du profil altimétrique car il va chercher sur une ancienne url du geotrek admin (https://siglr-geotrek-pnrgca.ataraxie.f) alors que l'adresse actuelle est : https://openig-geotrek-pnrgca.ataraxie.fr.

J'ai vérifié dans la conf nginx, je n'ai pas fait d'oubli. dans le fichier /opt/geotrek-admin/var/conf/env le SERVER_NAME à la bonne url aussi. Je ne sais pas où je dois faire le changement. 

Pour info, j'ai aussi le souvenir que Timothée m'avait dit à une époque que certains ports ne devaient pas être utilisés car ils sont utilisés par des outils comme convertit. J'utilise actuellement le port 9000 et 9001 pour les Geotrek-Rando. Est-ce que cela serait un souci aussi ?

**Comment by camillemonchicourt** [comment]
C'est pas tout simplement dans les options de ta commande de synchronisation (sync_mobile) que tu as laissé l'URL de l'ancien serveur ?
https://geotrek.readthedocs.io/en/master/install/synchronization.html#synchronization-options

**Comment by mviadere-openig** [comment]
Ce gaspillage de temps et d'énergies....C'était bien ça Camille, merci beaucoup de me l'avoir rappelé ! Comme on dit par chez moi : " Il n'y a que ceux qui ne font rien qui ne font pas d'erreurs !" Je clos l'issue.
