### ISSUE TITLE
PDF / Gestion des couleurs des tracés des itinéraires

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3116]
Sur l'export public PDF des itinéraires, il semblerait que les couleurs du tracé des randonnées varie en fonction du niveau de zoom ?

Ici en violet (https://openig-geotrek-pnrgca.ataraxie.fr/api/fr/treks/40770/daumont-aubrac-a-la-baume.pdf) : 

![Capture d’écran de 2022-05-25 09-49-32](https://user-images.githubusercontent.com/4418840/170217944-a418cbde-1af9-4f3f-b3f1-f248d8058a4d.png)

Ici en orange (https://openig-geotrek-pnrgca.ataraxie.fr/api/fr/treks/41780/gr-de-pays-tour-des-monts-daubrac.pdf) : 

![Capture d’écran de 2022-05-25 10-29-20](https://user-images.githubusercontent.com/4418840/170217998-e9b52dc9-efc7-45ee-ad52-ecf4ea7638ec.png)

On ne comprend pas bien pourquoi la couleur varie d'un itinéraire à l'autre, si c'est vraiment lié au niveau de zoom ou autre ?

Et surtout si il serait possible de configurer la couleur du tracé sur les exports PDF, quitte à utiliser les paramètres ``MAP_STYLE`` existants (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L392) pour ne pas ajouter de paramètre spécifique aux exports PDF ?

**Comment by juggler31** [comment]
Bonjour Camille,

Est ce que cette issue est toujours d'actualité ?
De mon côté je n'arrive pas a reproduire.

**Comment by camillemonchicourt** [comment]
En effet c'est OK sur les exemples qui avaient été fournis et on peut fermé si non reproduit.
