### ISSUE TITLE
Recommended installation method ? (native or docker)

### ISSUE THREAD

**Issue by yleduc** [GeotrekCE/Geotrek-admin#3120]
Hi Geotrek team,

For a complete new Geotrek-admin instance (on a new clean server, Focal Fossa 20.04 LTS for ex), which is the recommended installation method ? "Classic" install or docker ?

I have the technical skills to install it in the 2 methods.

Are there specific pros/cons before choosing between the 2 methods regarding Geotrek-admin requirements ? (updates, potential future changes, etc...)

Thanks for the advice,

Yannick

**Comment by camillemonchicourt** [comment]
Hi, the classic installation method is the most used by Geotrek community for production.
The docker method is used by some developpers and some mainteners that have several instances to manage, but has less documentation.

**Comment by yleduc** [comment]
Merci @camillemonchicourt 
Il vaut peut-être mieux que je reste en Français dans les échanges 😉

**Comment by camillemonchicourt** [comment]
OK, oui en français ou en anglais, les 2 sont possibles. :-)
