### ISSUE TITLE
Erreur synchro mobile : No such file or directory

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#3122]
Bonjour,

(GTA v2.82.2)
j'ai un pblme similaire à ce ticket (https://github.com/GeotrekCE/Geotrek-admin/issues/2758) lors du lancement d'une synchro mobile avec le message d'erreur suivant :
** nolang/media/upload/practice-foot.svg/media/upload/practice-foot.png copied
Traceback (most recent call last):
File "/usr/lib/python3.6/urllib/request.py", line 1481, in open_local_file
stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/geotrek-admin/var/media/Downloads/poi-pastoral-blanc.svg'

J'ai tout mes medias qui sont répartit dans l'arborescence "classique" du dossier media (convertit / maps / paperclip / profiles / upload) et j'ai ce dossier Download avec seulement le fichier poi-pastoral-blanc.svg

Dans /opt/geotrek-admin/var/media/upload j'ai le fichier poi-pastoral-blanc.png qui correspond bien à l'icone de cette typologie de POI.

Si je supprime le dossier en question cela ne change rien et dans la bdd ce fichier est introuvable.

J'ai récupéré cette install de GTA, donc difficile de savoir le pkoi de ce dossier ..

Merci pour votre aide.

**Comment by submarcos** [comment]
en base de données, un fichier est référencé à l'emplacement '/opt/geotrek-admin/var/media/Downloads/poi-pastoral-blanc.svg'
(surement un picto de type de POI)

Or, il n'existe pas dans le dossier media, le script de synchro ne peut donc pas le copier.
Deux possibilité : soit le chemin a été créé ou modifié manuellement en base de données sans passer par l'interface, soit le fichier a été supprimé de son emplacement dans le dossier var/media après son ajout dans l'interface
