### ISSUE TITLE
[API v2] Les événements sans date de fin ne sont pas présents dans les résultats de l'API

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3127]
Lorsqu'une animation n'a pas de date de fin, elle n'est pas retournée par l'api. Hors ce champ n'est pas obligatoire. 

Il faudrait soit : 
 * rendre le champ obligatoire
 * peupler automatiquement la date de fin par la date de début
 * retourner les événements sans date de fin dans l'api

**Comment by camillemonchicourt** [comment]
Je pense qu'il faut retenir l'option 3.
A voir si ça pose des soucis quand on filtre par date de fin...

**Comment by camillemonchicourt** [comment]
Fixé dans la version 2.88.0
