### ISSUE TITLE
Module sentiers pas de lien sur le nom du sentier dans la liste

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3131]
Bonjour, 
Dans notre module sentiers, nous pouvons ouvrir une "fiche" via la carte en passant la main sur le sentier en question mais pas via le nom dans la liste à gauche comme pour le module itinéraires.
Est-ce normal ?
Nous utilisons la version 2.82.2

**Comment by submarcos** [comment]
Bonjour,

ce problème a été corrigé dans la version [2.83.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.83.0)

**Comment by AudreyRemy** [comment]
Je confirme ça fonctionne bien en cliquant sur la carte.
Merci pour votre retour.
