### ISSUE TITLE
Mise à jour Geotrek-Admin en 2.83

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-admin#3133]
Bonjour,

Afin que la dernière version de Geotrek-Rando fonctionne correctement, je mets à jour Geotrek-Admin en 2.59 vers 2.83.
J'ai installé l'extension postgres comme stipulé pour la 2.70.
J'ai lancé la commande sudo apt-get update. J'ai l'erreur suivante qui fait planter l'upgrade et le apt-get install de geotrek

Err:1 https://packages.geotrek.fr/ubuntu focal/main amd64 geotrek-admin amd64 2.79.0.ubuntu20.04
  404  Not Found [IP: 152.228.156.81 443]
E: Failed to fetch https://packages.geotrek.fr/ubuntu/pool/main/g/geotrek-admin/geotrek-admin_2.79.0.ubuntu20.04_amd64.deb  404  Not Found [IP: 152.228.156.81 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Merci de votre aide.

**Comment by camillemonchicourt** [comment]
Je t'avais indiqué que la clé du package avait été mise à jour.
As-tu fait ce qui est indiqué dans les notes de version ainsi qu'ici : [--fix-missing](https://github.com/GeotrekCE/Geotrek-admin/issues/3044).

Je ne comprends pas pourquoi il cherche l'archive de la version 2.79.0, mais je maitrise pas bien ces histoires de paquet.

Sinon essaie ce qui t'est indiqué dans l'erreur : ``apt-get update --fix-missing``

**Comment by Chrispnv** [comment]
Salut,
J'avais regardé toutes les versions, mais je suis passé à travers le warning de la 2.80.
Tout est OK. L'upgrade s'est bien passé. Mon Geotrek-Admin est bien en 2.83.0.
On croise les doigts !
Merci Camille.

**Comment by camillemonchicourt** [comment]
Super, beaucoup d'évolutions et d'améliorations depuis la 2.59.
Les principales sont présentées ici : https://groups.google.com/g/geotrek-fr/c/AfltUdq2P9Q
