### ISSUE TITLE
Ajout d'un champ Categorie au module Sentier

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#3152]
Ajout d'un champ Categorie (liste déroulante) au module Sentier. Champ non obligatoire

**Comment by camillemonchicourt** [comment]
Quel serait les valeurs par défaut de ce champs, pour comprendre à quoi il correspondrait ?

**Comment by camillemonchicourt** [comment]
Attention, cette évolution a été intégrée dans la version 2.86.0, mais n’apparaît pas dans son CHANGELOG.
Il est important de l'indiquer, car elle n'est pas anodine et impacte tous les Geotrek-admin.
