### ISSUE TITLE
Flux cirkwi.xml : Ajouter les labels

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3164]
Il serait interréssant, dans notre contexte tout du moins, d'ajouter les labels aux informations complémentaires dans le flux circuit. 

Nous nous en servons pour communiquer sur le fait que la randonnée est en coeur de parc et qu'elle fait l'objet d'une reglementation particulière.

**Comment by camillemonchicourt** [comment]
OK en effet ça serait une bonne chose.
Là il faudrait les remettre à plat dans <information_complementaire>. 
A voir si https://github.com/GeotrekCE/Geotrek-admin/pull/3166 est OK ?

**Comment by Chatewgne** [comment]
Ok intégré les labels de la même manière que dans https://github.com/GeotrekCE/Geotrek-admin/pull/3166

**Comment by camillemonchicourt** [comment]
Fait dans la 2.86.0, comme on peut voir ici : https://geotrekdemo.ecrins-parcnational.fr/api/cirkwi/circuits.xml?structures=1

```XML
<informations_complementaires>
   .....
   <information_complementaire>
      <titre>Chiens en laisse</titre>
      <description>La divagation est interdite, pour protéger la faune sauvage. Les chiens doivent être tenus en laisse.</description>
   </information_complementaire>
   <information_complementaire>
      <titre>En coeur de parc</titre>
      <description>Le Parc national est un territoire naturel, ouvert à tous, mais soumis à une réglementation qu’il est nécessaire de connaître pour préparer son séjour. </description>
   </information_complementaire>
</informations_complementaires>
```
