### ISSUE TITLE
Migration 2.84.1

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#3173]
Bonjour,

Mon serveur étant en 18.04, j'ai décidé de repartir sur un serveur "neuf" en 20.04 pour migrer Geotrek de la 2.82.2 en 2.84.1. (le do-release-update me retournait une erreur)

Quelles seraient les commande à passer pour migrer la DBB ?

J'ai fait plusieurs manip, mais je bloque sur une erreur quand j'enregistre un trek :  
```
relation "altimetry_dem" does not exist
LINE 1: SELECT NOT EXISTS (SELECT 1 FROM altimetry_dem)
                                         ^
QUERY:  SELECT NOT EXISTS (SELECT 1 FROM altimetry_dem)
CONTEXT:  PL/pgSQL function ft_elevation_infos(geometry,double precision) line 12 at IF
SQL statement "SELECT * FROM ft_elevation_infos(egeom_3d, 1)"
PL/pgSQL function update_geometry_of_topology(integer) line 91 at SQL statement
SQL statement "SELECT update_geometry_of_topology(rec.id)"
PL/pgSQL function ft_topologies_paths_geometry_statement() line 6 at PERFORM
```
Ce qui me fait dire que j'ai du rater quelques choses à l'import... Ou à l'export... Ou ailleurs...

Merci d'avance de votre aide !

**Comment by camillemonchicourt** [comment]
Salut, peux-tu préciser ce que tu as fait et les commandes réalisées ?

Tu as monté un nouveau serveur en Ubuntu 20, installé un Geotrek-admin tout neuf, et migré ta BDD de ton ancien Geotrek-admin sur ton nouveau serveur ?

Ubuntu 18 fonctionnait avec PostgreSQL 10 et PostGIS 2.
Ubuntu 20 doit fonctionner avec PostgreSQL 12 ou 13 et PostGIS 3.

Dans PostGIS 3, la gestion des rasters a été amélioré et isolé dans une extension à part, non installée par défaut.
Le MNT de Geotrek-admin est un raster dans la BDD PostGIS.

Si tu as créé une nouvelle BDD manuellement dans PostGIS 3 et migré ta BDD Geotrek qui était sur du PostGIS 2, tu as du avoir des erreurs, car en effet, il faut installer explicitement l'extension raster dans la BDD PostGIS 3 pour pouvoir gérer ceux-ci.

Voir https://github.com/GeotrekCE/Geotrek-admin/issues/2642.

Mais si tu laisses Geotrek créer la BDD il va bien installer les extensions dont il a besoin : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2412-2020-11-27
Il y a aussi une autre extensions à ajouter manuellement si tu créées une BDD vierge, car on l'a ajouté depuis (``pgcrypto``) : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst#2700-2021-11-02

Voir aussi les commandes de migration partagées ici : https://github.com/GeotrekCE/Geotrek-admin/issues/3096#issuecomment-1126008515
Ainsi que https://github.com/GeotrekCE/Geotrek-admin/issues/2321

**Comment by jeromesourdin** [comment]
J'ai suivi les commandes passées, et tout a fonctionné Nickel !
Merci beaucoup pour les lien !
