### ISSUE TITLE
Signalétique - Direction sur lignes sur lames directionnelles

### ISSUE THREAD

**Issue by Chrispnv** [GeotrekCE/Geotrek-admin#3178]
Bonjour,

Actuellement dans le module Signalétique dans GTA, la direction du chemin est à préciser sur les lames posées sur les poteaux via le champ obligatoire Direction.
Nous au parc de la Vanoise, la direction du parcours est spécifiée au niveau des lignes qui constituent les lames. Donc un champ Direction serait utile à rajouter dans le bloc de chaque ligne dans l'interface.
Nous souhaiterions prendre une prestation pour le développement pour 
  - faire ajouter ce champ et tout le processus jusqu'en BDD.
  - Rendre le champ Direction sur les lames facultatif.

Nous sommes bien sur ok pour que ce développement profite à tous, mais est ce que la communauté a besoin de ce dev.
Donc ma question est surtout de savoir quelle est la meilleure solution. Est ce qu'on garde ce dev pour nous pour le moment ? Est ce que cela peut être ajouté dans une branche spécifique ? Est ce que cela doit être mis dans une nouvelle release ?

Merci.

**Comment by camillemonchicourt** [comment]
OK merci pour ces éléments clairs et précis. 
Ça m'embête qu'un même champs se retrouve à 2 niveaux dans la BDD et soit rempli dans une table ou une autre, selon un paramètre applicatif, mais je ne vois pas de meilleure solution.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.89.0, avec l'ajout du paramètre ``DIRECTION_ON_LINES_ENABLED`` permettant de passer le champs DIRECTION sur les LIGNES au lieu des LAMES.

Mais si on passe ce paramètre à ``True``, le champs DIRECTION reste quand même affiché au niveau de la liste des lames d'une signalétique : 

![image](https://user-images.githubusercontent.com/4418840/196968165-a8b1a8c2-70f5-4b73-97c2-d8b748010af6.png)

Je me demande si le filtre des lames par DIRECTION ne fonctionne pas seulement sur le champs DIRECTION de la table LAME ?

![image](https://user-images.githubusercontent.com/4418840/196969609-efa36d80-c4d7-4d73-b2c8-3ca55afd422c.png)

Pour les exports CSV des lames, ça me semble OK que celui-ci prend bien en compte si le champs DIRECTION est au niveau des lames ou des lignes. Tu confirmes @marcantoinedupre ?

**Comment by marcantoinedupre** [comment]
Bien vu @camillemonchicourt, c'est une erreur de ma part.

Les valeurs des directions des lames (supposément nulles si le paramètre DIRECTION_ON_LINES_ENABLED est True) sont bien cachées. Mais pas le titre **"Direction"** de la colonne.

En l'état actuel la liste des lames sur la page détail d'une signalétique est incohérente. Toutes les valeurs des colonnes sont décalées par rapport à leur titre à partir de la 3ème. Je corrige rapidement.

À part ça, le fonctionnement est simple : les directions sont cachées pour les lames et affichées pour les lignes (ou inversement) à tous les emplacements possibles. Y compris pour l'export CSV comme tu l'as remarqué.

**Comment by marcantoinedupre** [comment]
Erreur corrigée  #3312 et livrée en v2.89.1

**Comment by camillemonchicourt** [comment]
OK, testé et confirmé.
