### ISSUE TITLE
erreur 404 sur itinéraires après modifications tronçons

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3188]
Bonjour,

Après avoir modifié certains tronçons en passant par Qgis, certains itinéraires utilisant ces tronçons sont désormais inaccessibles via l'admin (erreur 404). Je les vois bien dans la base de données par contre donc il n'ont, semble t-il, pas été complètement supprimés.

Y a t-il un moyen de les rendre de nouveau accessible dans l'admin et éviter de perdre les données?

**Comment by camillemonchicourt** [comment]
Vérifie si leur champs "brouillon" n'a pas été mis à False

**Comment by camillemonchicourt** [comment]
Ah non pardon, les itinéraires...
Leur champs "deleted" a du être passé True, dans la table topology, j'ai plus le nom de la table sous la main.
Ça veut dire que ta modification de tronçon a cassé ces itinéraires car tu as du créer un trou dans leur tracé et du coup ça a cassé leur géométrie et du coup ils sont passés à deleted=true.

**Comment by pnrma** [comment]
Effectivement, c'est bien dans la table `core_topology` qu'on trouve le champs `deleted`.
Merci Camille !
