### ISSUE TITLE
Parser Geotrek

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#3189]
- Add uuid InformationDesk
- Add filetype api v2
- Add a new record Source for Geotrek (data's origin) **

- Add uuid structure ?

**Comment by camillemonchicourt** [comment]
En cours sur https://github.com/GeotrekCE/Geotrek-admin/pull/3196
On retient l'idée de bien transmettre les UUID pour la traçabilité des données et éviter les doublons quand les données sont baladées de BDD en BDD.
Mais on se base sur les ID et EID pour comparer et mettre à jour les données.

On envisage à terme un mécanisme permettant de ne proposer qu'en lecture seule (sans modification possible) les données qui sont importées et mises à jour régulièrement par un parser (donc les données disposant d'un EID).
A minima, pour commencer, on afficherait un message alertant l'utilisateur quand il modifie un objet disposant d'un EID (qu'il vienne d'un autre Geotrek, d'Apidae ou tout autre import).

Les champs EID et UUID ne doivent pas être éditables depuis l'interface de saisie de Geotrek-admin.

En plus du champs SOURCE actuel qui indique le PRODUCTEUR d'une donnée, on ajouterait un champs FOURNISSEUR qui indique la plateforme qui a transmis l'information. Cela pour la traçabilité des données, mais aussi potentiellement pour pouvoir comparer les données importées par EID+FOURNISSEUR, et non seulement par EID comme actuellement.

**Comment by camillemonchicourt** [comment]
Première version fonctionnelle intégrée dans la version 2.87.0.
Ce nouveau parser permet d'importer des données (InformationDesk, TouristicContent, TouristicEvent, POI, Trek, Service, Signage, Infrastructure) depuis un (ou plusieurs) autre(s) Geotrek-admin en interrogeant son API v2.

Il manque sa documentation qui serait bien utile dans docs/install/import.rst.
Peut-être aussi préciser dans la doc d'import globale, que l'on peut maintenant définir un provider pour chaque parser et ainsi garder l'info de la plateforme ayant fourni les données, et utiliser cette info pour comparer et supprimer les objets importés par provider, en plus de leur EID.

La première PR a été complétée avec la PR https://github.com/GeotrekCE/Geotrek-admin/pull/3226 qui fait notamment : 
- Ajout du champs ``provider`` au niveau des objets Trek, POI, Service, Signage, Infrastructure, TouristicContent, TouristicEvent, InformationDesk, Path, Trail, Course, Site et SensitiveArea
- Supprimer les objets de différents Parsers en fonction du champ ``provider`` (générique à tous les parsers)
- Utiliser les UUID en tant que EID pour retrouver les objets dans les flux Geotrek (et stocker la même valeur dans UUID local)
- Utiliser l'endpoint ``/tour`` de l'API pour recréer les itinérances

Le parser Geotrek récupère donc l'UUID du Geotrek source pour l'insérer dans le Geotrek de destination, et il l'utilise aussi pour renseigner l'EID du Geotrek de destination (utilisé pour les comparaisons d'objet et leur mise à jour notamment), plutôt que l'ID du Geotrek source.

Cela est surchargeable dans n'importe quel parser avec cette configuration : 
```python
replace_fields = {
        "eid": "XXXX"
}
```

Le nouveau champs ``provider`` ajouté peut être renseigné explicitement au niveau de chaque parser.

PS : J'ai un doute sur la pertinence d'utiliser la route ``tour`` pour récupérer les itinérances.
Cette route avait fait au début de l'API V2 quand il n'y avait aucune autre route (comme /trek et toutes les autres), spécifiquement pour le widget OpenSystem de réservation de l'itinérance.
Depuis cette route n'a pas été enrichie et je ne sais quelle est sa pertinence et son avenir, maintenant qu'on a les routes génériques et plus complètes comme ``/trek``.
Par exemple la route ``/tour`` n'est pas filtrable par ``portal`` ce qui est un problème important si on s'appuie dessus pour le GeotrekParser.

**Comment by camillemonchicourt** [comment]
Testé et vu avec @Chatewgne : 
J'ai voulu tester l'ajout d'un fournisseur (provider) sur un parser Apidae existant, en ajoutant ``provider = 'Apidae'`` dans sa définition. J'ai lancé l'import lié à ce parser. Il m'a supprime tous les contenu existants précédemment importés avec ce parser, et me les a tous réimportés en leur attribuant "Apidae" dans le nouveau champs "provider".

Comme expliqué par @Chatewgne, c'est normal, mais pas forcément souhaitable (modification des ID des objets qui vont changer leurs URL sur Geotrek-rando-v3 et donc pénaliser leur référencement) : 

> Le provider doit en effet être configuré avant le premier import, sinon on demande au parser de trouver des contenus ayant pour provider "Apidae" mais il n'y en a pas donc ça donne un comportement où les recrée avec la bonne valeur.
> Et pour éviter ça il faut mettre la valeur "Apidae" directement dans la BDD pour tous les contenus concernés manuellement avant de lancer le parsing où a été ajouté un provider.

Donc attention, si vous ajoutez un "provider" sur un parser que vous avez déjà utilisé sans "provider" défini.

**Comment by camillemonchicourt** [comment]
L'agrégateur (GeotrekParser) a été amélioré depuis et documenté (https://geotrek.readthedocs.io/en/latest/install/import.html#import-data-from-a-remote-geotrek-instance).

**Comment by camillemonchicourt** [comment]
https://makina-corpus.com/logiciel-libre/fusionner-bases-donnees-geotrek-projet-agregateur
