### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3203]
Geotrek-admin 2.85

Lorsque que l'on sélectionne le module sites outdoor, ceci apparait. 

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/45095227/182624229-d9deca5f-b189-479b-8f32-770fed7340af.png">

Est-ce que quelqu'un a déjà une erreur similaire ?

**Comment by camillemonchicourt** [comment]
Pas de soucis de notre côté en production et test/démo.
As-tu bien vidé ton cache serveur (comme indiqué dans les notes de version de la 2.84.0), voire ton cache navigateur ?

En effet, dans la cadre des améliorations des performances, l'utilisation de datatable a été revu pour pagoner les listes côté serveur, mais cela nécessitait de bien vider les caches.

**Comment by mviadere-openig** [comment]
Merci pour l'information Camille, je ne sais plus sur quel Geotrek je travaillais mais je prends en compte tes recommandations si l'erreur se représente. 
Merci, je clos l'issue.
