### ISSUE TITLE
Médias PDF attachés à un itinéraire

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3235]
Lorsqu'un média avec l'extension PDF est attaché à un itinéraire, le lien apparait bien dans la fiche rando dans la partie `Media` côté Geotrek-rando mais le fichier en lui-même ne semble pas pris en compte dans la synchronisation et est absent du dossier `/media/paperclip/...`
Le lien présent dans la fiche dirige donc vers un fichier introuvable.

**Comment by camillemonchicourt** [comment]
Cela concerne la V2 de Geotrek-rando et potentiel le mécanisme de synchronisation des données associé à la V2 de Geotrek-rando.

**Comment by pnrma** [comment]
Ok, j'imagine que la v2 de Geotrek-rando n'est plus maintenue donc nous passerons en v3 dès que possible.

Merci.
