### ISSUE TITLE
Evolution du module ÉVÉNEMENTS - Compléments et évaluation

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3237]
Le module ÉVÉNEMENTS de Geotrek permet déjà de saisir, gérer et diffuser des événements touristiques (sortie, conférence, atelier, expositions, visites...) sur Geotrek-rando ou autre.

Il est actuellement composé de ces champs : 

- id	(integer)
- accessibility	(string)
- approved	(boolean)
- attachments
- begin_date	(string($date))
- end_date	(string($date))
- booking	(string)
- cities	(string)
- contact	(string)
- create_datetime	(string($date-time))
- update_datetime	(string($date-time))
- description	(string)
- description_teaser	(string)
- duration	(string)
- email	(string($email))
- external_id	(string)
- geometry	(string)
- meeting_point	(string)
- meeting_time	(string)
- name	(string)
- organizer	(string)
- participant_number	(string)
- pdf - auto-generated	(string)
- portals
- practical_info	(string)
- published	(boolean)
- sources
- speaker	(string)
- target_audience	(string)
- themes
- url	(string($uri))
- uuid	(string($uuid))
- website	(string($uri))

L'objectif de ces évolutions est : 
- de mieux structurer certains de ces champs
- d'ajouter quelques champs pour mieux décrire les événements
- d'ajouter quelques champs nécessaires au suivi et à l'évaluation des événements touristiques
- de permettre de gérer les réservations des événements touristiques

**ÉVOLUTIONS PRÉVUES :** 

- Organisateur >> Basculer de texte à Liste (n-n), attention aux migrations de données
- Contact >> Basculer de texte à Liste avec nom, adresse, téléphone, email, URL, Actif (booléen), attention aux migration données
- Intervenant : En faire une liste ou on garde un champs libre ?
- Ajouter un champs "Contact de l'intervenant" non diffusé (au niveau des événements ou des intervenants, selon le point précédent)
- Ajouter une "Catégorie" en plus du type ? Plus large que le type (Animation pédagogique, animation pédagogique, formation). Lier les types aux catégories >> Réserves sur le sujet, car complexifierai la compréhension et la saisie. Les types suffisent.
- Remplir date fin automatiquement avec date début (javascript)
- Liste de lieux avec XY prédéfinis permettant de localiser correctement des événements sans les pointer sur la carte ?
- Ajouter "Heure fin" - Supprimer champs durée ?
- Formater les champs horaires
- Réorganiser formulaire (type en haut par exemple)
- "Nombre de places" à basculer en INTEGER
- Réservation : Ajouter BOOL + Texte
- Annulation : Ajouter BOOL + Liste de causes + Texte
- Public visé : en faire une liste / Quel lien avec champs "Accessibilité" ?
- Évaluation : Ajouter les champs "Temps préparation", "Temps d'intervention", "Nombre participants" (par classe d'age avec liste adaptable) / "Provenance du public" ?
- Pouvoir créer des groupes d’événements (= temps fort + projets pédagogiques ou autre)
- Réservations : Tables dédiées avec les inscrits
- Limiter le nombre de caractères du champs "Chapeau" (description_teaser), différemment des autres champs ?
- Finaliser la duplication d'objets depuis l'interface

Ces évolutions devront être réalisées au niveau de la BDD, des formulaires, des fiches détails, des filtres, des exports, de l'API V2, de la synchronisation, et éventuellement reportés sur Geotrek-rando-v3 pour certains champs.

**Comment by Chatewgne** [comment]
Basculer les Types en Catégories 
Créer une liste 1-N de Types (décorelés de Catégorie) + breaking change
Tout est renommé 
Attention aux parsers 

Rendre obligatoire les dates de début et de fin 
Si date de début mais pas de fin : fin := début et vice versa
Si pas de dates : 1970
End date rempli automatiquement

Ajouter heure de fin end_time
TimePicker dans le formulaire pour heure de rdv et heure de début

Renommer meeting_time en start_time
Créer des lieux et avoir un lien avec FK + copier la geom dans le formulaire

Nombre de place : devient "description du nombre de places" et un nouveau en integer
réservable : bool +  texte

Annulation : bool + liste de causes + description

Public visé : convertir les valeurs actuelles en liste (fonctionnalité de fusion ?)

Nombre de participants *effectifs* par classe d'âge (avec liste adaptable dans l'admin) (dans un autre onglet ?) Ca va marcher comme les mandays (attention aux exports)

Pour faire des groupes d'évènements : labels ? (Projet pédagogique : un garde fait plusieurs évènements avec une classe sur l'année)

Le chapeau doit avoir une limite de charactère plus courte que celle en oeuvre sur tout le reste et dépendante du module (comment faire la configuration ?) 


(pour les listes penser à faire des fixtures / attention à pas de supression en cascade pour les nouvelles listes)

**Comment by camillemonchicourt** [comment]
Les champs "Temps de préparation" et "Temps d'intervention" ont été ajoutés dans l'onglet "Evaluation" dans la version 2.89.0 : 

![image](https://user-images.githubusercontent.com/4418840/196959726-1b4e309b-8b63-4b62-b633-d9526495eece.png)

**Comment by camillemonchicourt** [comment]
La deuxième partie est discutée dans un autre ticket - https://github.com/GeotrekCE/Geotrek-admin/issues/3587
