### ISSUE TITLE
Impression des pdfs dans une autre langue retourne automatiquement un pdf en Fr

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3245]
Version Geotrek-admin : 2.87.1

Pour faire suite à ce ticket : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/782

Il semblerait que le souci vient de Geotrek-Admin au niveau de la génération du PDF.

Voici les logs : 
[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/9634039/systemd-geotrek-api.log)
[systemd-geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/9634041/systemd-geotrek-celery.log)
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/9634054/systemd-geotrek-ui.log)

**Comment by babastienne** [comment]
@mviadere-openig en testant à l'instant j'ai l'impression que le problème est corrigé. Peux-tu expliqué comment tu as résolu l'incident et fermer le ticket stp ?

**Comment by mviadere-openig** [comment]
De mémoire,  des fautes de syntaxe dans le fichier de traduction allemand. Le problème a été corrigé, je clos le ticket.
