### ISSUE TITLE
Mise à jour 

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3267]
Bonjour
Nous avons mis à jour Geotrek-admin de la 2.82.2 à la 2.87.2.
Est-ce que l a commande _apt upgrade_ est suffisante ou le warning mentionné pour la 2.84.0 doit être pris en compte également c'est-à-dire que ces commandes doivent être passées pour toute mise à jour supérieure à la 2.84.0 ?
Merci d'avance pour votre retour.
Bonne journée.

**Comment by submarcos** [comment]
Bonjour,
cette version change le système de cache afin d'augmenter les performances, vous devez donc manuellement le supprimer pour garder un comportement fonctionnel.
Après la mise à jour effectuez les commandes pour remettre le cache à 0.

**Comment by camillemonchicourt** [comment]
Oui, quand vous mettez à jour Geotrek-admin, vous passez directement à la dernière version (à moins de spécifier une version préciser explicitement), donc vous sautez potentiellement plusieurs versions, selon votre version actuelle.
Mais en effet, il faut quand même vérifier et appliquer toutes les éventuelles notes des versions intermédiaires.

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt
