### ISSUE TITLE
Taille dossier maps

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3290]
Le dossier` /opt/geotrek-admin/var/media/maps `de notre installation de Geotrek-admin affiche un poids conséquent de `150G` et je me demandais s'il existait une commande permettant de nettoyer ce dossier, à l'image de ce qui existe pour nettoyer les fichiers images avec  la commande `clean_attachments`.

**Comment by camillemonchicourt** [comment]
De mémoire, ce dossier contient toutes les images des cartes des objets générés par le serveur, pour les PDF public, mais aussi métier, ainsi que quand un utilisable demande un export image d'une carte directement depuis Geotrek-admin. 

Je suis étonné que ton dossier fasse 150 Go, c'est bien moins chez nous. Mais tu dois avoir plein d'objets dont la carte a été exporté. 

Tu peux vider manuellement ce dossier.
Les prochains exports de PDF seront un peu plus longs la première fois car ils devront régénérer les cartes, mais ça te fera du ménage, si jamais tu as plein d'exports de carte qui ne sont plus utilisés.

**Comment by pnrma** [comment]
Ok, bien noté. Merci Camille.
