### ISSUE TITLE
Création d'un secteur du module zonage dans l'administration de Django

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-admin#3293]
Bonjour,
Une collectivité me demande un export de la signalétique sur son territoire.
J'aimerais créer un secteur par communauté de communes ou communauté d'agglo de notre département.
Est-il possible de créer ce secteur en important une couche QGIS ou faut-il obligatoirement tracer les secteurs à la main ?
Dois-je utiliser la table "zoning_district" ?
Merci d'avance.

**Comment by camillemonchicourt** [comment]
Je ne sais pas si la notion de secteur est bien adaptée pour y intégrer les ComCom.
C'est plutôt pour des grands secteurs géographiques, comme des massifs, ou autres.
Pour les autres zonages réglementaires ou administratifs, je suggérerai plutôt d'utiliser le concept plus général et générique des "zonages".
C'est une couche de zonage globale et générique, dans laquelle chacun peut ajouter tous les types de zonages qu'il veut.

Exemple sur notre Geotrek-admin : 

![image](https://user-images.githubusercontent.com/4418840/195621974-7e166b26-dc3e-4fb1-992c-11b547ff8ce8.png)

Tu ajoutes un nouveau type de zonage (Communautés de communes) dans la table ``zoning_restrictedareatype`` (directement dans la BDD ou depuis l'AdminSite.

![image](https://user-images.githubusercontent.com/4418840/195623040-6bc37c87-3dd6-403c-ad2a-6ccea9191f5d.png)

Puis tu ajoutes tes ComCom dans la table ``zoning_restrictedarea`` en faisant référence à l'ID du type de zonage que tu viens de créer dans la colonne ``zoning_restrictedarea.area_type_id``.

Tu peux en effet importer les ComCom dans la table ``zoning_restrictedarea`` directement avec QGIS, moi je fais comme ça en tout cas.

**Comment by AudreyRemy** [comment]
Merci @camillemonchicourt je vais tester tout ça.

**Comment by AudreyRemy** [comment]
@camillemonchicourt ça a fonctionné à merveille. Merci encore.
Bonne journée
