### ISSUE TITLE
Can't see the published pictogram on Treks when the list view is reduced

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3300]
When resizing the list view to the minimum length in the trek list, we display an icon to allow the user to display more information. This icon overlap with the "published / waiting for publication" pictogram.

This is purely an UX/UI improvement to do.

![image](https://user-images.githubusercontent.com/16348048/196147277-a0cec94c-3211-41c0-9977-9daf1d57644d.png)

**Comment by submarcos** [comment]
duplicated with https://github.com/GeotrekCE/Geotrek-admin/issues/3136
