### ISSUE TITLE
Error migration: 0033_auto_20220929_0840

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3307]
Lors de la migration 0033_auto_20220929_0840 une erreur est levée quand il y a une simple quote dans le champ participant number

```py
psycopg2.errors.SyntaxError: syntax error at or near "après"
LINE 1: ... 'Participants: 50 max le matin, 15 par atelier l'après midi...
```

Peut être que se serait plus simple de laisser le sql faire tout seul
```py
"UPDATE tourism_touristicevent SET practical_info_{} = CONCAT(practical_info_{} , " Participants: ", participant_number)  WHERE id='{}';".format(lang, lang, id)
```

**Comment by camillemonchicourt** [comment]
Ah mince, il faut revoir cette migration ? Ou en ajouter une nouvelle ?

**Comment by Chatewgne** [comment]
Corrigé ici en échappant le contenu de `participant_number` dans la query :

https://github.com/GeotrekCE/Geotrek-admin/pull/3311

en cours de publication dans la release 2.89.1

**Comment by camillemonchicourt** [comment]
Merci.
