### ISSUE TITLE
Import zone sensible

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3314]
Je tente d'importer des zones sensibles au format shp avec la commande : 
`sudo geotrek  import geotrek.sensitivity.parsers.RegulatorySensitiveAreaShapeParser <file.shp>`

mais j'obtiens l'erreur :
`CommandError: Failed to import parser file 'geotrek/sensitivity/parsers.py'`

Version de Geotrek-admin : 2.89.1

**Comment by camillemonchicourt** [comment]
Il faudrait plus d'infos, notamment des logs.
As-tu des éléments dans les logs de Geotrek (/opt/geotrek-admin/var/log/) ?

**Comment by pnrma** [comment]
Pas d'information dans les logs (/opt/geotrek-admin/var/log/geotrek.log) et fichier shp contenant les champs "name", "periode" et "pratiques".

J'ai également remarqué que lorsque je passe par le module d'import en ligne, le champs d'upload du fichier local a disparu. Je ne sais pas si c'est lié à cette erreur.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/44799642/199503067-0321283f-2065-49e9-bd8c-d9cfc088297b.png">

**Comment by pnrma** [comment]
Je suis revenu sur ce problème et je ne pense pas que cela soit lié à une question de paramétrage mais je n'ai pas la possibilité de tester sur une autre instance de Geotrek-admin pour en être certain.
Du coup je me demande si c'est un problème général ou localisé sur notre instance.
Si quelqu'un a la réponse...

**Comment by pnrma** [comment]
Finalement j'ai réussi à faire fonctionner l'import en ajoutant une classe héritant de la classe `RegulatorySensitiveAreaShapeParser` dans le fichier `/opt/geotrek-admin/var/conf/parsers.py`.
Du coup il y a peut-être une modification à apporter à la documentation pour le préciser si c'est le fonctionnement normal.

**Comment by camillemonchicourt** [comment]
Non ce n'est pas normal à ma connaissance, le parser d'import intégré à Geotrek-admin est censé fonctionner directement.

Voir https://geotrek.readthedocs.io/en/2.90.1/install/sensitivity.html#import-from-shapefile

**Comment by babastienne** [comment]
Testé à plusieurs reprises sur des instances différentes. En conservant la configuration initiale (pas de modification du fichier `parsers.py`) je n'arrive pas à reproduire l'erreur obtenue dans ce ticket. 

Je clôture donc le ticket mais si le problème persiste sur une instance ne pas hésiter à le ré-ouvrir en ajoutant des éléments de contexte pour nous permettre de reproduire le bug.
