### ISSUE TITLE
Upgrade 2.90.1 : Erreur gunicorn Temporary failure in name resolution

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-admin#3319]
Bonjour,
Je rencontre une erreur 500 après upgrade 2.85.0 vers 2.90.1. J'ai "Erreur interne" sur page de login et "_journalctl -eu geotrek-ui_" retourne :  
```
...
Nov 07 14:51:03 gtkadm gunicorn[3853]:   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
Nov 07 14:51:03 gtkadm gunicorn[3853]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Nov 07 14:51:03 gtkadm gunicorn[3853]: socket.gaierror: [Errno -3] Temporary failure in name resolution

```
Rien de changé en effectuant les commandes suivantes : 
```
rm -r /opt/geotrek-admin/var/cache/*
dpkg-reconfigure geotrek-admin
systemctl restart nginx
```
Le saut d'une dizaine de versions est peut-être la cause mais je n'ai pas trouvé comment passer chaque version simplement (comme par exemple `apt install geotrekadmin=2.86.0`) et éviter des `git checkout tags/2.86.0`, etc.

**Comment by camillemonchicourt** [comment]
Non c'est souhaitable de sauter directement à la dernière version.

Il peut y avoir des spécificités indiquées dans les notes de versions intermédiaires mais elles ne nécessitent pas de passer par ces versions en questions.
Comme le fait de vider le cache dans la version 2.87.0 que tu as fait après la mise à jour en 2.90 et c'est la bonne méthode.

Je n'ai jamais rencontré le soucis que tu remontes.

Est ce que des erreurs ont été remontées lors de la mise à jour ?

On dirait que le service gunicorn qui fait tourner Geotrek a un soucis. Mais ça ne me dit rien.

**Comment by noelmartinon** [comment]
Merci de cette prompt réponse Camille !

Pas d'erreur particulière non. Je joins la sortie de commande "`apt upgrade`" au cas où.
[geotrek-admin-upgrade-2.90.1.txt](https://github.com/GeotrekCE/Geotrek-admin/files/9955267/geotrek-admin-upgrade-2.90.1.txt)

**Comment by camillemonchicourt** [comment]
OK je vois une piste.
Lors de la mise à jour il t'a été demandé : 

```
Configuration file '/opt/geotrek-admin/var/conf/env.in'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** env.in (Y/I/N/O/D/Z) [default=N] ? 
```

En effet dans la version 2.87.0, le fichier ``env.in`` a été modifié : https://github.com/GeotrekCE/Geotrek-admin/commit/fd46846a4bdaa7ebfad2cfd537cc8ac4141fb63c

Je n'y connais rien, mais ton message d'erreur semble un problème pour récupérer une adresse, un host, un port ou je ne sais pas très bien. Mais du coup, ça me laisse pensé que c'est lié.

Qu'as-tu répondu à cette question ?
Il faut dire OUI.

Ton fichier ``/opt/geotrek-admin/var/conf/env.in`` est bien similaire à celui par défaut : https://github.com/GeotrekCE/Geotrek-admin/blob/master/conf/env.in ?

Sinon écrase ton fichier local ``/opt/geotrek-admin/var/conf/env.in``, pour le remplacer par celui-ci puis relance un ``dpkg-reconfigure geotrek-admin``.

**Comment by noelmartinon** [comment]
C'était bien ça, merci !
