### ISSUE TITLE
The API should convert relative media path to absolute 

### ISSUE THREAD

**Issue by dtrucs** [GeotrekCE/Geotrek-admin#3321]
From the description fields, it is possible to attach media. The `src` attribute is filled with a relative path instead of an absolute path.  
Whatever service connects to the API should not parse the content to add the base path of the admin URL.

For example: 
A description given by a trek endpoint https://admin-pyrenees-orientales.fr/api/v2/trek/254789/?fields=description
And below the UI for the user ⬇️ 
![image](https://user-images.githubusercontent.com/1926041/201939755-3b383ccf-2851-47cd-96fa-e0a5e214dd28.png)

**Comment by Chatewgne** [comment]
The relative path in question when displaying the source code for this description :

![image](https://user-images.githubusercontent.com/26015573/201954826-c601fcb0-8271-42f5-8a0d-94049e8e9cad.png)

- [ ] This pictogram insertion tool should insert an absolute URL in the `src` tag
- [ ] It would be useful to write a migration for the old data, converting fields with relative paths to absolute paths, or at least a command that helps finding all fields that need an update

**Comment by camillemonchicourt** [comment]
Hum, what about if we change the Geotrek-admin URL.
Not sure storing an absolute path is the good solution...

**Comment by dtrucs** [comment]
> Hum, what about if we change the Geotrek-admin URL. Not sure storing an absolute path is the good solution...

Totally agree 👍  
Ideally, I think the conversion should be done by the API looking at its basePath. However parsing the content with a regexp could go wrong (false positive).

Anyway, it is not flexible to work with stored HTML. Maybe in the future storing the content in markdown would make the manipulation more flexible.

**Comment by bastyen** [comment]
Geotrek mobile handle this case here : https://github.com/GeotrekCE/Geotrek-mobile/blob/main/src/app/services/settings/settings.service.ts#L290

**Comment by camillemonchicourt** [comment]
Fait dans la 2.95.0, mais je ne vois pas le résultat quand j'affiche une description avec un service intégré dans celle-ci : 

![image](https://user-images.githubusercontent.com/4418840/215331656-694e9c77-9999-4e85-8b16-b686d4cd156d.png)

Le chemin du picto du service est relatif : ``<img src=\"/media/upload/descent-icon.svg\" alt=\"Descente\" />``

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.98.1
