### ISSUE TITLE
Signalétique - afficher le type de lame dans la fiche d'une signalétique

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3325]
Pour l'instant le type de chaque lame n'est pas affiché lorsqu'on visualise les informations d'une signalétique. Ce serait utile de l'avoir, entre `code` et `couleur` par exemple. Cela éviterait d'avoir à déduire le type de lame à partir du texte ou du picto, et faciliterait la vue d'ensemble. 

![image](https://user-images.githubusercontent.com/73114156/202437997-0b05577d-20e2-479a-b9be-c07ceecf8df5.png)

**Comment by camillemonchicourt** [comment]
Oui le type est une information de premier niveau à afficher dans la liste, plus importante que d'autres infos affichées actuellement.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.95.0
