### ISSUE TITLE
Signalétique - Champ `texte` obligatoire pour les lignes

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3326]
Actuellement le champ `texte` est obligatoire pour les lignes, ce qui oblige à le renseigner même lorsqu'il n'y a qu'un pictogramme sur une ligne. S'il n'y a pas de texte, il faudrait pouvoir ne pas renseigner le champ.

**Comment by babastienne** [comment]
Oui, ok à condition de conserver le numéro comme champ obligatoire afin d'être sur qu'on ne peut pas créer d'objet vide.

**Comment by babastienne** [comment]
Ok, testé sur notre démo, je confirme qu'à présent depuis la release [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0) il est possible de créer des lames sans texte.
