### ISSUE TITLE
Erreur interne (500)

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-admin#3384]
Bonjour,
Je viens de mettre à jour une instance de GTA (Ubuntu 20.04 / v. 2.85 vers 2.94) en effectuant les cmd suivantes :
sudo apt-get update
sudo apt-get upgrade
(2.87.0 -> You will need to delete your cache after this release upgrade)
sudo rm -r /opt/geotrek-admin/var/cache/*
sudo dpkg-reconfigure geotrek-admin

Depuis j'ai une erreur interne (500), renvoyée par le navigateur.

Le log suivant sudo journalctl -eu geotrek-ui renvoie cette erreur :
 django.core.exceptions.ImproperlyConfigured: The session storage path '/opt/geotrek-admin/var/cache/sessions' doesn't exist. Please set your SESSION_FILE_PATH 
ERROR 2022-12-20 11:06:49,971 django.request Internal Server Error: /login/

Des idées ? ...
Merci!

**Comment by camillemonchicourt** [comment]
L'erreur indique qu'il faut renseigner ``SESSION_FILE_PATH`` qui est défini par défaut ici : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L866

Cela semble en lien avec les évolutions récentes du cache ?
En tout cas, on n'est pas censé surcoucher la valeur de ce paramètre.

**Comment by camillemonchicourt** [comment]
Le soucis  été identifié.
Dans la version 2.92.0 (https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.92.0) un système de cache a été mis en place sur l'API v2 de Geotrek-admin pour améliorer ses performances (notamment pour Geotrek-rando-v3 qui l'interroge à chaque recherche ou page affichée).

En même temps que cela, le cache a été séparé en 3 sous-dossiers dans le dossier /opt/geotrek-admin/var/cache : https://github.com/GeotrekCE/Geotrek-admin/commit/702feaf0bcdadbc4b0436c9212724f3001b6ba6a

Pour créer ces 3 sous-dossiers une migration a été appliquée lors du passage à la version 2.92.0 : https://github.com/GeotrekCE/Geotrek-admin/blob/2.92.0/geotrek/common/migrations/0027_flush_cache_1234.py#L11

Mais dans les notes de versions précédentes, on indiquait de vider tout le contenu du dossier var/cache (``sudo rm -r /opt/geotrek-admin/var/cache/*``). Cela a ainsi supprimé tes 3 sous-dossiers et posé le soucis que tu as remonté.
Ces commandes de vidage du cache étaient bien à faire à l'époque mais plus à partir de la version 2.92.0.

Ces indications ont été supprimés des notes de versions et le soucis ne pourra plus se reproduire désormais si on supprime ces dossiers, car ils seront recréés automatiquement lors de chaque mise à jour de Geotrek-admin si ils ont été supprimés (https://github.com/GeotrekCE/Geotrek-admin/pull/3385)

**Comment by JeanLenormand** [comment]
Merci pour ton retour. En effet, le problème a été résolu en rajouter le dossier sessions dans opt/geotrek-admin/var/cache/ puis en exécutant : sudo dpkg-reconfigure geotrek-admin
