### ISSUE TITLE
[SENSITIVITY] Adding labels to sensitive areas

### ISSUE THREAD

**Issue by lpofredc** [GeotrekCE/Geotrek-admin#3387]
For the BiodivSports instance, it is expected to be able to associate pictograms to sensitive areas. 

For this purpose, I am thinking of supporting the development of this new feature on the [`Labels` model from the `common`](https://github.com/GeotrekCE/Geotrek-admin/blob/8ae8ba0f5e536de54057af568bc3d30a5cc56ef3/geotrek/common/models.py#L228-L240) module with a many-to-many relationship (Draft PR here #3386).

These developments raise some questions:

- Given the current context application current structure, is it still relevant to develop the autonomous APIs of the sensitivity module (are they really used) or is it better to develop only the APIs of the APIV2 module?

- Which good practice for the labels integration into the API:

  - Since the tags are commons, should we just provide the IDs and the items will have to be retrieved by a separate API call (like for sports practices, `/api/v2/label/`)

  - Or include the detailed list of labels as proposed with the LabelSeralizer in API response ?

**Comment by camillemonchicourt** [comment]
See https://github.com/GeotrekCE/Geotrek-admin/issues/3470 for details.
It has been decided a dedicated "rule" table in the SensitiveArea module.
