### ISSUE TITLE
Photos accessibilité / Droits nécessaires ?

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3396]
Dans la version 2.76.0, un onglet a été ajouté sur les itinéraires pour pouvoir ajouter des photos spécifiques aux informations liées à l'accessibilité d'un itinéraire (https://github.com/GeotrekCE/Geotrek-admin/issues/2838).

Celui-ci fonctionne bien avec un utilisateur super-administrateur.
Mais là je l'ai testé avec un utilisateur classique qui a tous les droits sur les itinéraires et les fichiers liés, mais impossible d'ajouter une photo d'accessibilité.

Une fois que l'on valide l'envoi de la photo, on est dirigé sur la page de login sans message d'erreur, et celle-ci tente d'aller sur https://geotrekdemo.ecrins-parcnational.fr/login/?next=/trekking/add-accessibility-for/trekking/trek/771/

Une fois authentifié à nouveau, si je vais sur cette URL, j'ai une page vide.

Est-ce qu'il faut une permission particulière pour pouvoir ajouter des photos d'accessibilité ?
Ou un autre soucis qui fait que seulement les super-administrateurs peuvent en ajouter ?

**Comment by LePetitTim** [comment]
Bonjour,
ce sont bien les droits sur les fichiers liés qui permettent ou non d'ajouter un fichier attaché meme pour l'accéssibilité.

Je regarde pourquoi il y a un soucis lors de l'ajout des photos d'accessibilité.
Je vais également regarder si les permissions fonctionnent comme prévu.

**Comment by camillemonchicourt** [comment]
OK il y avait bien un soucis et il fallait avoir les droits "bypass_structure" pour pouvoir ajouter une photo d'accessibilité.

Corrigé dans la 2.98.0.
