### ISSUE TITLE
Zones sensibles réglementaires - Ajout des réglementations

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3470]
Il est souhaité pouvoir associer le détail des réglementations de chaque zone sensible réglementaire.

Pour cela, il a d'abord été envisagé de s'appuyer sur le mécanisme générique et partagé des étiquettes, utilisé dans les itinéraires et les sites Outdoor.

Il a finalement été préféré de faire une table dédiée aux réglementations, pour ne pas les mélanger avec les infos et recommandations très générales et génériques des étiquettes.

Il s'agit donc d'ajouter une table RÈGLES (rules) dans la module Zones sensibles, et de pouvoir associer une ou plusieurs règles aux zones réglementaires.

Cette table contiendra : 
- Un identifiant automatique
- Un code (pour faciliter la standardisation et le partage de règles au niveau national et européen)
- Un titre (multilingue)
- Un description (multilingue)
- Une URL (multilingue)
- Un pictogramme

Une liste par défaut sera proposée avec les différentes règles d'un parc national (https://www.ecrins-parcnational.fr/reglementation).

---------------------------

Au niveau européen, il y a notamment un enjeu à pouvoir échanger et partager les réglementations avec Digitize the planet (https://digitizetheplanet.org) qui propose un outil et plateforme de gestion et de diffusion des réglementations des espaces protégés.
Exemple : https://content.digitizetheplanet.org/rules/show_protectedarea/412e67c8-7541-4118-98a3-e02738843ceb

Au niveau national, il y a un enjeu à pouvoir ajouter des réglementations au référentiel des zonages des espaces protégés de l'INPN (https://inpn.mnhn.fr/telechargement/cartes-et-information-geographique) et à leur diffusion dans l'API IGN qui se base dessus : https://apicarto.ign.fr/api/doc/nature

Pour info, au niveau de DIGITIZE THE PLANET, on voit dans son API (https://content.digitizetheplanet.org/rules/api/) qu'il peut y avoir beaucoup d'infos sur chaque réglementation, mais de notre côté, il semble plus pertinent de commencer simple comme évoqué ci-dessus : 

```json
{
  "id": 2,
  "activity": {
    "id": 9,
    "code": 6000,
    "activity": "Motor vehicle",
    "activity_en": "Motor vehicle",
    "activity_de": "Kraftfahrzeug",
    "category": {
      "id": 4,
      "code": 6000,
      "category": "Motorized activities",
      "category_en": "Motorized activities",
      "category_de": "Motorisierte Aktivitäten"
    }
  },
  "activityplace": {
    "id": 3,
    "code": null,
    "place": "Designated paths/places",
    "place_en": "Designated paths/places",
    "place_de": "Ausgewiesene Wege/Plätze"
  },
  "activitypermission": {
    "id": 1,
    "code": 1000,
    "permission": "allowed",
    "permission_en": "allowed",
    "permission_de": "erlaubt"
  },
  "weathercondition": null,
  "season": null,
  "daytime": null,
  "legaldoc": null,
  "user": {
    "id": 17,
    "organization": "Nationalpark Sächsische Schweiz",
    "division": "Gebietsentwicklung",
    "homepage": "https://www.nationalpark-saechsische-schweiz.de/",
    "address1": "An der Elbe 4",
    "address2": null,
    "zip_code": "01814",
    "city": "Bad Schandau",
    "state": "Sachsen",
    "country": "DE"
  },
  "icons": [
    {
      "id": 208,
      "general": null,
      "style": "regular",
      "name": "dtp_motorvehicle_allowed_regular",
      "file": "https://content.digitizetheplanet.org/archives/icons/dtp_motorvehicle_allowed_regular.svg",
      "activity": 9,
      "activityplace": null,
      "weathercondition": null,
      "daytime": null,
      "season": null,
      "activitypermission": 1
    },
    {
      "id": 24,
      "general": null,
      "style": "regular",
      "name": "dtp_designatedpathsplaces_allowed_regular",
      "file": "https://content.digitizetheplanet.org/archives/icons/dtp_designatedpathsplaces_allowed_regular.svg",
      "activity": null,
      "activityplace": 3,
      "weathercondition": null,
      "daytime": null,
      "season": null,
      "activitypermission": 1
    }
  ],
  "minimum_path_width": null,
  "season_start": null,
  "season_end": null,
  "season_repeats_yearly": false,
  "daytime_start": null,
  "daytime_end": null,
  "comment": null,
  "comment_en": null,
  "comment_de": null,
  "comment_sl": null,
  "comment_fr": null,
  "comment_it": null,
  "comment_hu": null,
  "comment_ro": null,
  "comment_fi": null,
  "comment_pt": null,
  "legal_paragraph": null,
  "legal_section": null,
  "legal_clause": null,
  "created_at": "2022-01-26T11:34:23.663078Z",
  "updated_at": "2022-01-26T11:34:23.663092Z",
  "park": "3b939037-9328-4cce-aaa5-a4665693dff3"
}
```

**Comment by lpofredc** [comment]
cf. PR #3386

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.97.0

**Comment by camillemonchicourt** [comment]
On peut donc désormais ajouter une ou plusieurs réglementations à chaque zone réglementaire.

![image](https://user-images.githubusercontent.com/4418840/230339110-a6577e1f-f0cc-48b8-9fce-a937c7066028.png)

La liste des règles est gérable dans l'Adminsite.
Un travail est en cours pour fournir une liste de règles par défaut lors de l'installation du module.

![image](https://user-images.githubusercontent.com/4418840/230339379-98c0d510-2e79-4d56-8988-42964350f9df.png)

Dans l'API renvoyant les zones sensibles, une propriété `rules` a été ajouté avec pour chaque règle ces éléments : 

```
rules	[Rule{
               id	integer
               code	string
               name	string
               pictogram	string($uri)
               description	string
               url	string($uri)
}]
```

**Comment by amandine-sahl** [comment]
Ci joint une première proposition de fixtures

[fixture.zip](https://github.com/GeotrekCE/Geotrek-admin/files/12262497/fixture.zip)
[rules.csv](https://github.com/GeotrekCE/Geotrek-admin/files/12262498/rules.csv)

**Comment by camillemonchicourt** [comment]
OK super, merci.
OK pour moi, on l'a relue ensemble.

Il faudra faire une fixture dédiée (installée par défaut avec le module Zones sensibles) pour que ceux qui ont déjà le module installé puissent la déployer, comme on avait fait pour les licences des médias :

INSTALL : https://github.com/GeotrekCE/Geotrek-admin/pull/3411/files
DOCKER : https://github.com/GeotrekCE/Geotrek-admin/pull/3073/files#diff-319e63514131952f552094688daaf195c2335c7f55489f4167ff4901d2b1632a
INSERTION : https://github.com/GeotrekCE/Geotrek-admin/pull/3073/files#diff-1b6fbc4383defa69c5d9936250dd3f87e2f7e14c7750ba0149d3e71b3c470c88

**Comment by lpofredc** [comment]
Merci @amandine-sahl  & @camillemonchicourt pour ces éléments !

**Comment by camillemonchicourt** [comment]
Dans la fixture proposée, le picto `VTT-FORBIDDEN_053.svg` n'est pas utilisé car c'est un doublon de `BIKES-FORBIDDEN_053.svg`.

**Comment by camillemonchicourt** [comment]
Ressource intéressante pour éventuel complément, si les pictos et règles sont partagées par un nombre conséquent de structures : https://quietudeattitude.fr/ballons-vosges/je-localise-les-zones-sensibles/#cartographie

**Comment by camillemonchicourt** [comment]
Pour intégrer la réglementation des zonages réglementaires dans Geotrek, nous avons retenu d'ajouter une table de règles et de pouvoir les associer une par une aux espaces protégés.

Mais en regardant à nouveau ce qui est fait dans Digitize the Planet, mais aussi ce qui est discuté au niveau du standard CNIG national sur les espaces protégés et leur réglementation, l'approche est un peu différente.
Ce ne sont pas des règles génériques qui sont associées à chaque zonage réglementaire, mais bien des réglementations, en associant une activité et un type de permissions.
Exemple sur un espace protégé allemand : https://content.digitizetheplanet.org/en/protected_area/berchtesgaden/

L'API est disponible sur https://content.digitizetheplanet.org/en/api/docs/.
Avec notamment : 
- les types de permission (https://content.digitizetheplanet.org/api/activitypermission/)
- les catégories d'activité (https://content.digitizetheplanet.org/api/activitycategory/)
- les activités (https://content.digitizetheplanet.org/api/activity/)

Pour illustrer, dans Geotrek nous avons par exemple ces 2 règles : 
- Chiens autorisés, tenus en laisse (DOGS-LEASH)
- Chiens interdits, même tenus en laisse (DOGS-FORBIDDEN)

Dans DTP, cela correspond à 2 activités : 
```
{
            "id": 24,
            "code": 11020,
            "category": {
                "id": 7,
                "code": 11000,
                "category": "General behavior",
                "category_en": "General behavior",
                "category_de": "Generelles Verhalten"
            },
            "activity": "Dogs",
            "activity_de": "Hunde",
            "activity_en": "Dogs"
        },
        {
            "id": 25,
            "code": 11021,
            "category": {
                "id": 7,
                "code": 11000,
                "category": "General behavior",
                "category_en": "General behavior",
                "category_de": "Generelles Verhalten"
            },
            "activity": "Dogs with leash",
            "activity_de": "Hunde mit Leine",
            "activity_en": "Dogs with leash"
        },
```
Et différentes permissions que l'on peut associer à chaque activité : 
- allowed
- forbidden
- allowed with official permission only
- allowed with owner permission only
- discouraged
En plus du type de permission, il est aussi possible de renseigner une période ou saison, une limite géographique... à une réglementation (=activité/permission/espace_protégé)
