### ISSUE TITLE
Versions PostgreSQL/PostGIS compatible Geotrek-admin

### ISSUE THREAD

**Issue by mougetann** [GeotrekCE/Geotrek-admin#3493]
Bonjour,
Une installation de Geotrek-admin via docker est-elle compatible avec PostgreSQL 13 et PostGIS 3.1 ?

**Comment by marcantoinedupre** [comment]
Bonjour, oui geotrek-admin est compatible avec postgresql 13 et postgis 3.1.

La compatibilité suit celle de la version de django utilisée (actuellement django 3.2), geotrek-admin est compatible postgresql 9.6+ et postgis 2.3+.

Par contre si vous utilisez l'image docker `postgis/postgis` l'extension `postgis_raster` n'est plus activée par défaut pour postgis 3.0+ et vous devrez prévoir de l'activer sur votre BD.
