### ISSUE TITLE
2.97.2 : Liste des interventions qui ne s'affiche pas

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3499]
Geotrek version : 2.97.2

Bonjour, pour information depuis quelques versions antérieures à GTK-admin. Il y a un bug au niveau de l'affichage du module interventions, avant la 2.97.1 c'était les données sur la carte qui ne s'affichaient pas, maintenant c'est les données dans la liste des interventions : 
![image](https://user-images.githubusercontent.com/45095227/220947315-e0248dbe-74dc-4565-8104-c8da13ddc76a.png)

Si on reste un petit moment sur la page ce message s'affiche : 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/45095227/220947456-2bd43cdd-71e3-4760-b400-516b9d172ba3.png">

Voici les logs : 
[systemd-geotrek-api.log](https://github.com/GeotrekCE/Geotrek-admin/files/10815113/systemd-geotrek-api.log)
[systemd-geotrek-celery.log](https://github.com/GeotrekCE/Geotrek-admin/files/10815114/systemd-geotrek-celery.log)
[systemd-geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/10815115/systemd-geotrek-ui.log)

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas le soucis sur https://geotrekdemo.ecrins-parcnational.fr/intervention/list/ (admin / admin)

Dans le fichier ``systemd-geotrek-api.log``, tu as pas mal d'erreurs qui semblent correspondre au soucis indiquant : 

```
ERROR 2023-02-22 16:29:43,276 django.request Internal Server Error: /api/intervention/drf/interventions
File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/decorators.py", line 82, in _wrapped_view
kwargs.pop('format')
KeyError: 'format'
```

Dans la 2.97.0, il y a ce fix qui semble sur un sujet similaire, à voir si c'est lié : "Fix interventions api geom - https://github.com/GeotrekCE/Geotrek-admin/pull/3469" ?

**Comment by camillemonchicourt** [comment]
Je reproduis le soucis sur notre serveur de production.

La carte affiche les interventions, mais pas la liste, et au bout d'un moment j'ai ce message : 

![image](https://user-images.githubusercontent.com/4418840/221522255-0bac9675-d505-4e17-bdd8-b36832d5842d.png)

En retestant plusieurs fois, ça a finalement fonctionné, mais ce que je comprends, c'est que ça tombe en TIMEOUT la plupart du temps.

Surement car la requête est trop longue depuis les évolutions de la 2.97.0 ?

![image](https://user-images.githubusercontent.com/4418840/221534611-73d4bc1b-cfce-4635-9d0e-88a906228091.png)

**Comment by camillemonchicourt** [comment]
Depuis le passage en 2.97.2, j'ai aussi reçu des erreurs liées à l'affiche de chantiers : 

```
Internal Server Error: /api/intervention/drf/interventions

KeyError at /api/intervention/drf/interventions
'format'

Request Method: GET
Request URL: https://geotrek-admin.ecrins-parcnational.fr/api/intervention/drf/interventions?project=258
Django Version: 3.2.18
Python Executable: /opt/geotrek-admin/bin/python
Python Version: 3.8.16
Python Path: ['/', '/', '/opt/geotrek-admin/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/geotrek-admin/lib/python3.8/site-packages']
Server time: Mon, 27 Feb 2023 11:27:10 +0100
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'clearcache',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.gis',
 'crispy_forms',
 'compressor',
 'django_filters',
 'tinymce',
 'easy_thumbnails',
 'mapentity',
 'paperclip',
 'leaflet',
 'rest_framework',
 'rest_framework_gis',
 'embed_video',
 'django_celery_results',
 'django_large_image',
 'colorfield',
 'mptt',
 'geotrek.cirkwi',
 'geotrek.authent',
 'geotrek.common',
 'geotrek.altimetry',
 'geotrek.core',
 'geotrek.infrastructure',
 'geotrek.signage',
 'geotrek.maintenance',
 'geotrek.zoning',
 'geotrek.land',
 'geotrek.trekking',
 'geotrek.tourism',
 'geotrek.flatpages',
 'geotrek.feedback',
 'geotrek.api',
 'geotrek.outdoor',
 'geotrek.sensitivity',
 'drf_yasg')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'geotrek.authent.middleware.LocaleForcedMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'geotrek.common.middleware.APILocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'geotrek.authent.middleware.CorsMiddleware',
 'mapentity.middleware.AutoLoginMiddleware')


Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/geotrek-admin/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/decorators.py", line 82, in _wrapped_view
    kwargs.pop('format')

Exception Type: KeyError at /api/intervention/drf/interventions
Exception Value: 'format'
```

**Comment by mviadere-openig** [comment]
Ce problème ne tombe vraiment pas au bon moment, car c'est la période de gestion des interventions avant l'été.

Je propose donc d'utiliser des heures de TMA à notre disposition si cela peut aider à résoudre le problème plus vite.

**Comment by camillemonchicourt** [comment]
Correction en cours côté Django-mapentity - https://github.com/makinacorpus/django-mapentity/pull/265

**Comment by camillemonchicourt** [comment]
La version 2.97.3 règle le problème chez moi, mais l'affichage de la liste met plus de 3 minutes : 

![image](https://user-images.githubusercontent.com/4418840/221917014-0f81203b-bf92-41b1-ae9e-0f239e088eaf.png)

**Comment by mviadere-openig** [comment]
Idem ici, sur deux geotrek-admin en prod et en 2.97.3 les données finissent par s'afficher au bout d'environ 5 minutes.

**Comment by LePetitTim** [comment]
Bonjour,

Nous avons regardé le problème sur la démo Geotrek admin, cela reste utilisable mais il y a en effet avec beaucoup d'élément, un soucis de lenteur. Ce n'est pas lié aux signalements.
La correction de la récupération des données géographiques (geojson) a mis en lumière le problème de performance pour la récuperation des données tabulaires. Auparavant, les données étaient mis en cache, ce qui n'était pas la situation normale. Pour les autres modules, la recherche par filtre n'est jamais mis en cache. 

Le problème est général aux Interventions / Projets. Pour éviter la création de nouveaux trigger sql, nous avions choisi de ne pas stocker la géométrie des interventions lors de l'ajout de la fonctionnalité des interventions sur n'importe quel objet. La géométrie est récupéré depuis l'élément associé.
Lorsque Geotrek-admin récupere les  géometries des interventions dans la liste, cela  récupere la géométrie de tous les élements associés à ces interventions.
Lorsque nous filtrons sur la carte, cela récupere les interventions en fonctions des géométrie de chaque éléments.

Ce sont des requêtes sql complexes. 
Pour réduire le temps de calcul, il faudrait repenser entierement le module intervention pour stocker la geometrie directement sur chaque interventions, avec un systeme de mise a jour des géométries lorsque l'objet associé est modifié.
L'écriture sera plus longue qu'actuellement pour n'importe quel objet relié à une intervention mais l'affichage des interventions sera beaucoup plus rapide.

**Comment by camillemonchicourt** [comment]
Ce que je ne comprends pas c'est que ça fonctionnait très bien en 2.96.
Et que le chargement des objets sur la carte est toujours rapide.
C'est uniquement le chargement de la liste qui galère et met plusieurs minutes.

Je vois pas pourquoi il faudrait stocker la géométrie des interventions liées à des objets.

**Comment by alexandreaubron** [comment]
Bonjour, j'apporte un témoignage en complément pour confirmer que les interventions ne s'affichent pas non plus sur le Geotrek du parc national des Cévennes, dans lequel j'ai commencé à planifier l'entretien pluriannuelle pour notre communauté de communes (Cévennes au Mont Lozère). Depuis mon récent accès à Geotrek il y a quelques semaines, la liste des interventions s'est toujours mise à jour rapidement (en fonction du zoom et de l'emprise sur la carte), ce qui me permet de déduire l'intervention que je souhaite éditer. Par contre je n'ai jamais vu le linéaire des interventions s'afficher sur la carte depuis la liste et ce même après plusieurs minutes. Merci à vous et bonne journée

**Comment by camillemonchicourt** [comment]
Corrigé avec la 2.97.4.
La liste des interventions charge en 3 secondes ! 

![image](https://user-images.githubusercontent.com/4418840/224286417-9915b543-fb92-4527-a326-898871cb5f26.png)

Le soucis a été corrigé et non pas revenu en arrière ! Donc encore mieux. 🎉
Merci.

**Comment by alexandreaubron** [comment]
Cela fonctionne aussi dans le Geotrek du PN des Cévennes, merci à vous


Bonne journée,


Alexandre Aubron

Chef de Projet Avenir Montagne

Communauté de Communes

des Cévennes au Mont Lozère

Rn106-le village

48160 Le Collet-de-Dèze

TEL: 06 38 24 65 07


[1661867540426]

________________________________
De : Camille Monchicourt ***@***.***>
Envoyé : vendredi 10 mars 2023 11:03:41
À : GeotrekCE/Geotrek-admin
Cc : Alexandre Aubron; Comment
Objet : Re: [GeotrekCE/Geotrek-admin] 2.97.2 : Liste des interventions qui ne s'affiche pas (Issue #3499)


Closed #3499<https://github.com/GeotrekCE/Geotrek-admin/issues/3499> as completed.

**Comment by JoelAtche** [comment]
Génial ça fonctionne aussi au Grands Causses à la suite de la mise à jour par OpenIG, merci à tous!!!
