### ISSUE TITLE
Ajout parser Itinéraires APIDAE

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3516]
Un nouveau parser a été ajouté ces derniers mois pour importer des Itinéraires depuis APIDAE. La première version date de décembre 2022 et a été suivi de plusieurs améliorations et corrections. Le développement de ce parser a été financé par Auvergne-Rhône-Alpes Tourisme.

[Documentation sur readthedocs.io](https://geotrek.readthedocs.io/en/2.97.4/install/import.html#import-treks-from-apidae)

PRs :

- [Add Trek parser from APIDAE #3315 (inclut une description du fonctionnement)](https://github.com/GeotrekCE/Geotrek-admin/pull/3315)
- [Feat apidae poi parser #3353](https://github.com/GeotrekCE/Geotrek-admin/pull/3353)

Ci-joint le tableau de correspondance entre les propriétés APIDAE importées et leurs champs destination dans Geotrek.

[Mapping Itinéraires APIDAE -> Geotrek Admin.ods](https://github.com/GeotrekCE/Geotrek-admin/files/10978511/Mapping.Itineraires.APIDAE.-.Geotrek.Admin.ods)

**Comment by camillemonchicourt** [comment]
Merci pour le partage de ces éléments intéressants et importants.
A noter, si j'ai bien suivi, que ce parser d'import d'itinéraires (et de POI) depuis Apidae vers Geotrek ne fonctionne qu'avec une version sans segmentation dynamique de Gotrek-admin (Geotrek-admin-light) car on importe le tracé GPX fourni par Apidae directement comme tracé linéaire de l'itinéraire, donc sans pouvoir s'appuyer sur des tronçons.

En plus de ce parser `ApidaeTrekParser` pour importer des itinéraires, un parser `ApidaePOIParser` a été créé pour importer des POI. Ils peuvent être utilisés indépendamment. 
On peut donc ainsi aussi uniquement importer des POI depuis Apidae vers Geotrek.

**Comment by camillemonchicourt** [comment]
En complément, un article sur le sujet - https://pro.auvergnerhonealpes-tourisme.com/passerelle-apidae-geotrek-pour-diffuser-des-itineraires/

Utilisé pour déployer alimenter https://www.laregionduvelo.fr.
