### ISSUE TITLE
Bug : impossible de rechercher dans une liste de services

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3521]
**Démo :** 

![geotrek-bug-service$](https://user-images.githubusercontent.com/16348048/226392007-5cb2e614-66d4-417d-b7e8-200f9fd62e6a.gif)

Piste de résolution : 
- il faut fixer cette ligne https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/views.py#L458 (Elle référence une colonne "name" qui n'existe pas sur ce modèle)
- il faut changer aussi mandatory_columns

**Comment by Huquette** [comment]
Vu qu'il n'y a pas de fonctionnalité de recherche sur ce module, est-ce qu'il serait préférable de masquer la barre de recherche ? (js + css) car sûrement pas possible via MapEntity view.

**Comment by babastienne** [comment]
> Vu qu'il n'y a pas de fonctionnalité de recherche sur ce module, est-ce qu'il serait préférable de masquer la barre de recherche ? (js + css) car sûrement pas possible via MapEntity view.

Si en effet tu as raison, on pourrait carrément cacher la barre de recherche car ça n'a pas de sens dans ce module.

**Comment by babastienne** [comment]
Fixed in release [2.100.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.100.0)

It is now possible to filter the list by searching directly for the id of an object.
