### ISSUE TITLE
Minimal data Outdoor

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3524]
Lorsque je tente de charger les données minimum pour le module Outdoor avec la commande prévue :
`sudo geotrek loaddata /opt/geotrek-admin/lib/python*/site-packages/geotrek/outdoor/fixtures/basic.json`

J'obtiens l'erreur suivante :
```
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "date_insert" violates not-null constraint
DETAIL:  Failing row contains (1, Eau vive, Eau vive, White water, null, null).
```

Version de Geotrek-admin : 2.97.4

**Comment by babastienne** [comment]
Le problème est en cours de correction dans cette PR : https://github.com/GeotrekCE/Geotrek-admin/pull/3520

J'ai fait le commit il y a plusieurs mois mais il n'a encore jamais été intégré ... Ca sera probablement corrigé dans une prochaine version de Geotrek-Admin

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.98.0.
@pnrma, peux-tu mettre à jour ton Geotrek et relancer la commande et nous dire si c'est OK de ton côté ?

**Comment by pnrma** [comment]
C'est ok pour la commande.
Par contre bizarrement ça a supprimé un groupe utilisateur qui avait été créé et a attribué le groupe "outdoor" aux utilisateurs de ce groupe.
Je n'ai pas remarqué d'autres effets indésirables pour le moment.

**Comment by camillemonchicourt** [comment]
Ah mince, ça c'est pas vraiment souhaitable :-/

Mais si je comprends bien, c'est lié au fait que le fichier qui intègre les données de base pour le module Outdoor contient l'ajout d'un groupe d'utilisateur, en plus des pratiques et cotations : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/outdoor/fixtures/basic.json#L3-L15

Peut-être que tu avais déjà un groupe avec l'ID 8 et que donc l'intégration des données de base du module Outdoor (incluant ce groupe) ait remplacé ton groupe d'utilisateurs ayant l'ID 8 par ce groupe.

Je pense en effet que c'est un fonctionnement dangereux qui devrait être bloqué.

Par ailleurs, je pense que la création par défaut d'un groupe nommé "Outdoor" n'a pas vraiment de sens.

Dans un premier temps, je propose de supprimer ce groupe d'utilisateur "Outdoor" des fixtures du module Outdoor car cela est dangereux si ça écrase un groupe existant comme dans ton cas.

Dans un second temps, peut-être revoir plus globalement le fonctionnement de l'intégration des fixtures dans le cas où un objet est déjà présent. 
Peut-être aussi que les fixtures ne devraient pas inclure les ID (PK) des objets dans le cas où des objets existent déjà dans la BDD.
Et laisser les serial des champs de la BDD créer les ID auto-incrémentés lors de l'insertion des fixtures dans la BDD.

@babastienne, un avis sur le sujet ?

**Comment by AudreyRemy** [comment]
> C'est ok pour la commande. Par contre bizarrement ça a supprimé un groupe utilisateur qui avait été créé et a attribué le groupe "outdoor" aux utilisateurs de ce groupe. Je n'ai pas remarqué d'autres effets indésirables pour le moment.

Bien vu,  j'ai eu le même problème mais je ne m'en étais pas encore aperçu. Merci @pnrma

**Comment by babastienne** [comment]
@camillemonchicourt  tu as très bien résumé le problème. 

Une fixture n'est pas capable de détecter qu'un objet avec cet identifiant existe déjà, ça va donc l'écraser sans même générer d'alerte ... Il me semble que les fixtures obligent à intégrer un id (PK) malheureusement. Il faut aussi le voir comme une sécurité, car ainsi si l'utilisateur appelle plusieurs fois la commande alors des objets identiques ne seront pas multipliés.

En fait le mécanisme de fixture dans Django sert à charger des données à l'installation. Dans le cas d'une instance "neuve" de Geotrek qui vient d'être installée, dans laquelle on active le module Outdoor directement et on installe la fixture ça ne pose donc pas de problèmes.
En revanche, on est confronté au cas d'usage de territoires qui active le module alors que ça fait plusieurs années qu'ils utilisent Geotrek (et donc il y a surement eu de nouveaux groupes créés, ou d'autres objets, avec les même identifiants que dans les fixtures identifiants). 

Ce qu'il faut c'est que quand on active un module dans Geotrek, on installe immédiatement la fixture associée (comme ce qui est décrit dans la doc), ou alors plus jamais. Il faut par contre que la fixture n'altère que des objets associés à ce nouveau module et en ça il est vrai que le fait d'ajouter un groupe via la fixture Outdoor est dangereux, ca devrait être retiré.

Donc pour résumer selon moi :
- Il faut retirer de la fixture les lignes relatives à d'autres objets n'appartenant pas au module outdoor
- Il ne faut pas toucher au reste de la fixture et aux identifiants

**Comment by camillemonchicourt** [comment]
OK pour moi pour enlever la création du groupe d'utilisateurs "Outdoor" de la fixture.
En plus avoir un groupe nommé comme ça est pas vraiment cohérent avec ce que l'on fait par ailleurs.
