### ISSUE TITLE
Erreur import parser Biodiv'Sport

### ISSUE THREAD

**Issue by thomasmagninfeysot** [GeotrekCE/Geotrek-admin#3538]
Bonjour à tous,
J'ai une erreur d'import avec le parser Biodiv'Sport : 
![image](https://user-images.githubusercontent.com/19687397/229106667-d8dc2966-5457-4f4c-b496-7011323f9552.png)

Voici le log associé : 
ERROR 2023-03-31 11:03:36,510 django.request Internal Server Error: /commands/import
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/views.py", line 224, in import_view
    choices, choices_url, classes = discover_available_parsers(request)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/utils/import_celery.py", line 46, in discover_available_parsers
    spec.loader.exec_module(parsers_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geotrek-admin/var/conf/parsers.py", line 1
    from geotrek.sensitivity.parsers import BiodivParser
    ^
IndentationError: unexpected indent

Erreur en 2.97.3 et en 2.98. Ca fonctionnait bien avant. D'autres personnes ont ce problème ? une idée d'où ça peut venir ? Merci pour vos retours !

**Comment by camillemonchicourt** [comment]
Je viens de tester un import Biodiv'Sports en 2.98.0 sans soucis.

Le message d'erreur parle d'un soucis d'indentation dans ton fichier `parsers.py`

**Comment by thomaspnrhj** [comment]
Merci du retour Camille,
Alors j'utilises le parser par défaut, j'ai plus aucun parser surcouché pour biodiv'sport dans mon var/conf/parser.py
Jai lancé sudo service geotrek restart et sudo dpkg-reconfigure -u geotrek-admin mais on dirait qu'il ne recharge pas et qu'il prend en compte l'ancien parsers surcouché... une autre commande à envoyer ?

**Comment by camillemonchicourt** [comment]
Non rien d'autre à lancer.

Je ne suis pas certain qu'il utilise encore ton ancien parser, mais surement un soucis qui subsiste dans ton fichier `parsers.py`, dans les imports au début du fichier, ou autre ?

**Comment by submarcos** [comment]
Bonjour l'erreur indique clairement un probleme dans ton fichier parsers.py

File "/opt/geotrek-admin/var/conf/parsers.py", line 1
from geotrek.sensitivity.parsers import BiodivParser
^
IndentationError: unexpected indent

**Comment by xavyeah39** [comment]
Bonjour,
Après vérification avec Thomas, je confirme qu'il ne semble pas y avoir  de problème d'indentation dans le fichier parser.py dont voici le contenu :
```py
# -*- coding: utf8 -*-

from geotrek.tourism.parsers import TouristicContentApidaeParser

class HebergementParser(TouristicContentApidaeParser):
    label = "Hébergements & restaurants VPNR"
    api_key = '*******'
    project_id = ****
    selection_id = ******
    category = "Valeurs Parc"
    type1 = ["Hébergement et restaurants"]
```
On a essayé de désactiver complétement var/conf/parser.py mais nous avons toujours la même erreur au bout de 9% d’exécution de l'import BiodivSport
Pensez-vous que cela puisse venir des données importées depuis BiodivSport ? (de nouvelles zones sensibles ont été ajoutées dans BiodivSport sur l'emprise du Parc du Haut-Jura).
Merci,

**Comment by camillemonchicourt** [comment]
On dirait qu'il manque un ID je ne sais pas où, certainement dans les données, vu que j'ai testé un import de mon côté aujourd'hui sans soucis.

Mais je ne vois pas où.

J'ai regardé les données que renvoie Biodiv'Sports pour votre structure et toutes les zones sensibiles ont logiquement un ID : 
https://biodiv-sports.fr/api/v2/sensitivearea/?format=json&bubble&period=ignore&structure=4&fields=practices,species_id,id&page_size=1000

Peut-être que si vous lancez la commande du parser en ligne de commande, vous aurez plus de logs ?

J'ai tenté la commande indiquée dans la documentation (https://geotrek.readthedocs.io/en/2.98.0/install/sensitivity.html#import-from-https-biodiv-sports-fr) pour lancer cet import : `sudo geotrek import -v2 geotrek.sensitivity.parsers.BiodivParser` (`-v2` permettant d'avoir des logs détaillés de l'exécution de la commande), mais la commande est en erreur (`CommandError: Failed to import parser class 'BiodivParser'`).

Je ne vois pas si quelque chose aurait changé dans la commande à exécuter pour lancer cet import en ligne de commande... 🤔

**Comment by thomaspnrhj** [comment]
Je voulais regarder le numéro de structure de la LPO pour vérifier les ID des zones ajoutées sur notre périmètre comme tu as fais Camille, mais c'est bizarre sur l'API Biodiv'Sport, on a aucune structure qui remonte, je sais si il peut y avoir un lien : https://biodiv-sports.fr/api/v2/structure/

**Comment by xavyeah39** [comment]
Je confirme aussi que nous avons la même erreur que toi Camille à l'exécution de la commande `geotrek import` en 2.98.
Pas trouvé plus de log que celui en interface cité plus haut...

**Comment by camillemonchicourt** [comment]
Oui j'avais testé aussi la route https://biodiv-sports.fr/api/v2/structure/ hier et j'ai pas compris non plus pourquoi elle ne renvoie rien. Mais c'est un autre sujet je pense.

**Comment by xavyeah39** [comment]
On y voit plus clair après investigation + échanges sur Matrix (Geotrek-DEV) 👍 

Dans la première erreur soulevée par @thomaspnrhj, le backlog concernait en fait une autre erreur lié à la suppression de la suppression de la déclaration d'encodage dans notre parsers.py (`# -- coding: utf8 --`).
Retours de @submarcos sur ce point : 

> alors çà c'est étrange car l'encoding n'est plus necessaire depuis python3. à moins que çà pose des pb si on edite le fichier avec windows ?
j'ai l'impression que l'outil qu'on utilise pour creer le paquet debian a changé (dh-virtualenv), et le dossier geotrek n'est plus au meme endroit, ce pourquoi çà ne marche plus

On a tenté aussi de supprimer toutes les données des zones sensibles des tables sensitivity_* puis de relancer un import : 
malgré l'erreur l'import fonctionne quand même et on récupère bien les données de BiodivSport... 

En exécutant l'import avec la commande, j'ai effectivement plus de logs merci JEC pour ton retour que je remet ici : 

> De ce que je vois : çà marche en docker et en mode dev / test, çà marche pas en debian. la manière utilisée pour charger la classe de parser est un peu tordue, ce qui fait qu'en install debian il ne trouve pas le fichier
si on se place dans le bon dossier çà marche
cd /opt/geotrek-admin/lib/python3.8/site-packages && sudo geotrek import xxx
du coup çà vaudrait le coup de fixer çà pour que çà marche à tous les coups (utiliser directement le path python plutot que de recomposer le path du fichier lui meme comme c'est fait)

 
 `cd /opt/geotrek-admin/lib/python3.8/site-packages && sudo geotrek import -v2 geotrek.sensitivity.parsers.BiodivParser`

L'erreur laisse penser à un soucis de données côté BiodivSport.

```
Traceback (most recent call last):
 File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/management/commands/import.py", line 55, in handle
    parser.parse(options['filename'], limit=limit)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 538, in parse
    self.parse_row(row)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 400, in parse_row
    self.parse_obj(row, operation)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 322, in parse_obj
    update_fields = self.parse_fields(row, self.fields)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 311, in parse_fields
    self.parse_field(row, dst, src, updated, non_field)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 300, in parse_field
    modified = self.parse_real_field(dst, src, val)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 224, in parse_real_field
    val = getattr(self, 'filter_{0}'.format(dst))(src, val)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/sensitivity/parsers.py", line 124, in filter_species
    if set(practices) != set(species.practices.all()):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 536, in __get__
    return self.related_manager_cls(instance)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 851, in __init__
    raise ValueError('"%r" needs to have a value for field "%s" before '
ValueError: "<Species: >" needs to have a value for field "id" before this many-to-many relationship can be used.
```
Par contre si on l'on réduit notre SPATIAL_EXTENT dans custom.py (notre emprise etait très large et on récupérait bien trop de zones sensibles), cette erreur n'est plus levée et l'import atteint les 100%.
Il ne nous reste plus qu'une autre erreur non bloquante qui indique un soucis de géométrie sur une ZS : 
```
[...]
189/190 lignes importées.
148 enregistrements créés.
25 enregistrements supprimés.
41 enregistrements non modifiés.
1 avertissement :
# Line 64:
- null value in column "geom" violates not-null constraint
DETAIL:  Failing row contains (408, 2023-04-05 10:32:19.612278+00, 2023-04-05 10:32:19.612293+00, f, t, 2023-04-05, null, 195, 40, La R&eacute;serve naturelle r&eacute;gionale des Tourbi&egrave;r..., Conservateur : hidden<br /><a href="mailto:hidden..., 1335, , La R&eacute;serve naturelle r&eacute;gionale des Tourbi&egrave;r..., , null).
```

Des erreurs qui semblent donc plutôt liées à des données incorrectes côté BiodivSport. 
On regarde si on peut les identifier et faire remonter.

Merci pour votre réactivité et vos retours !
