### ISSUE TITLE
Erreur PostgreSQL en installation Docker

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3548]
J'essaie d'installer Geotrek-admin en Docker sur Ubuntu 22 en suivant la procédure décrite ici (https://geotrek.readthedocs.io/en/2.98.0/install/docker.html), mais la commande `docker-compose run --rm web update.sh` renvoie toujours les erreurs suivantes en boucle semblant infinie : 
```
psql: error: could not connect to server: Connection refused
	Is the server running on host "172.18.0.1" and accepting
	TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
```
J'ai tenté plusieurs solutions trouvées sur internet comme modifier `docker-compose.yml` pour forcer l'attente du lancement de PostgreSQL mais sans succès.

Quelqu'un aurait une solution ?

**Comment by babastienne** [comment]
Oui on dirait que le server postgresql n'est pas lancé, ne tourne pas.

**Comment by IdrissaD** [comment]
A priori il n'y avait pas d'autre serveur qui tournait. On a trouvé une solution qui fonctionne pour ma situation (dev en local) mais pas idéale dans d'autres contextes : modifier le pg_hba.conf et le postgresql.conf pour écouter toutes les adresses IP. C'est plutôt comme si l'adresse Docker était considérée comme extérieure et donc bloquée par PostgreSQL ?

**Comment by babastienne** [comment]
Oui, étonnant en effet que ça n'ai pas fonctionné nativement. Il faudrait voir aussi comment était ton environnement sur ton poste au moment de l'installation pour mieux comprendre l'origine du problème.

Il faudrait voir aussi si en installant en local en mode dev avec docker sur une machine vierge on reproduit le problème, auquel cas ce serait à investiguer plus en détail, ou pas, et alors il s'agit d'un cas isolé.

En tout cas tant mieux si le problème est désormais résolu.

**Comment by raphaeldoisy** [comment]
J'ai eu le même soucis qu'Idrissa avec ma machine vierge. J'ai donc fait les changements et il s'est bien lancé jusqu'à s'arrêter en cours de route sur le conteneur celery car il a dû freezer. 
J'ai eu quelques galères et ai dû réinstaller pas mal de choses et je suis enfin revenu à ce soucis de connexion. Cependant, le changement dans les 2 fichiers pg ne fonctionnent plus du tout malgré le restart de postgres. J'ai toujours le même message.
J'ai certainement raté quelque chose mais quoi? Avez-vous une idée? 

Ubuntu 24
postgresql 16

**Comment by babastienne** [comment]
Je confirme que depuis quelques temps j'ai aussi le même problème sur mon poste sur une installation en mode dev qui fonctionnait pourtant auparavant. 

Je n'ai pas pris le temps de creuser le sujet, il faudrait éventuellement qu'on regarde ensemble un jour @submarcos car je ne semble pas être le seul.

**Comment by submarcos** [comment]
Ne pas confondre l'install en mode dev (postgresql inclus par defaut dans le docker compose), et en mode prod (pour l'instant, en mode prod, il n'est pas dans le docker compose, aussi il necessite des regles pour autoriser les connexions depuis un container docker (postgresql.conf et pg_hba.conf à configurer pour autoriser les interfaces réseau et les mecanismes d'authent par plage IP).

En mode dev, une erreur alors que 'ca marchait avant', vient probablement du fait que la version de la BDD a changé.
On fixe généralement la version minimale de postgresql / postgis supportée (avant pg10, depuis peu PG12).
Aussi l'erreur vient probablement que le volume a été initié en pg10 et est maintenant lancé e npg12.
Il faut don le migrer ou le détruire et le reconstruire.
