### ISSUE TITLE
Attach files on flatpages

### ISSUE THREAD

**Issue by numahell** [GeotrekCE/Geotrek-admin#3552]
It would be useful to attach files (images, pdf, etc.) to flatpages.

To do this we may use paperclip attachments field already configured for cover_image, and update form to add attached files formset.

URL image should be available and easily copyable to add in text afterwards.

A bonus may be to configure TinyMCE insert / image but it would be much longer to do so.

To insert image or any file into text, here is the how-to :

- go to insert image or link
- set source for an image, or url for a link

![image](https://user-images.githubusercontent.com/546686/231184492-7d5232ef-b7e0-4e5f-8cc7-e3fb652c7396.png)

![image](https://user-images.githubusercontent.com/546686/231184528-9ea5246d-b4ed-4f92-a534-a0cf989d0795.png)

**Comment by camillemonchicourt** [comment]
I think we should rather enable to  upload and insert images in the WYSIWYG editor which is native.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.104.0 (nécessite Geotrek-rando 3.19+) : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/fa0557d6-dcbc-46bf-a174-865424b5382a)

Discussion dans la PR pour améliorer dans un second temps le système de stockage des médias et l'étendre à d'autres modules que les pages statiques.
