### ISSUE TITLE
Chantiers - la date de fin peut être antérieure à la date de début

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3567]
Quand on crée un chantier, l'année de fin peut être antérieure à l'année de début. Au-delà du fait que cela n'a pas de sens, une erreur de ce type empêche le chantier de remonter dans les filtres temporels de la liste des chantiers.

![image](https://user-images.githubusercontent.com/73114156/231781681-f8e88ac0-1494-4fe2-a8c0-57d4a36a6c0d.png)

**Comment by babastienne** [comment]
Ce ticket est résolu depuis la dernière version de Geotrek-Admin [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0).

Testé et validé sur notre demo :

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/de8e32bd-7345-491b-b064-b92a7212dd6d)
