### ISSUE TITLE
[Sensitivity] Template publication by languages (detail) does not allow to change language directly

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#3577]
**In the sensitivity module**, normally, if we click on a language  :
![Capture d’écran du 2023-04-24 15-07-47](https://user-images.githubusercontent.com/26329336/234005534-cc65b8f3-724b-4e24-a1f3-5b6142308544.png)
we should change the language of the page.

It was working before the changement of language management.

**Comment by submarcos** [comment]
fixed
