### ISSUE TITLE
Statuts - ajout d'un modèle `Circulation`

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3578]
Nous voudrions utiliser le module statuts pour la gestion interne des autorisations de circulation sur les voies en cœur de Parc. Nous pensons que c'est le module tout indiqué pour associer à nos tronçons des statuts tels que "Interdit aux VTT", "Interdit à toute circulation motorisée", etc. Actuellement aucun modèle n'est vraiment adapté à ce besoin, les modèles `PhysicalEdge` et `LandEdge` ne correspondant pas au besoin. 

Plusieurs points de réflexion :
 - trouver un nom pour le modèle (circulation ? autorisations ? accès ?)
 - création d'un modèle `CirculationType` pour gérer les types de circulation (nom et description, picto ?)
 - déterminer si un statut circulation ne peut avoir qu'un type ou bien plusieurs types (exemple d'un tronçon à la fois interdit aux VTT et à la circulation motorisée : deux statuts dont un pour chaque type, ou un statut avec deux types ?)
 - déterminer les champs nécessaires au modèle Circulation (description, ...)

**Comment by camillemonchicourt** [comment]
Oui, ajouter un nouveau type de statuts semble pertinent.
Le nommer CIRCULATION me parait le plus adapté.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.101.5.

**Comment by camillemonchicourt** [comment]
Soucis : Type d'intervention est affiché en double : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/e592bac0-1357-4909-8620-a3ef5bfc4972)

**Comment by babastienne** [comment]
@camillemonchicourt pas sur de bien comprendre ton retour ? Le fonctionnement semble cohérent par rapport à ce qui était spécifié : on ajoute un type de circulation et l'autorisation associée.

Où vois-tu "Type d'intervention" ?

**Comment by camillemonchicourt** [comment]
Ah pardon j'avais pas vu que c'étaient 2 champs différents, je pensais que c'était un doublon.
