### ISSUE TITLE
Affichage des communes en vue liste

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3585]
Dans le module Aménagement, on affiche dans une vue liste les communes parcourues par les aménagements. 

![image](https://user-images.githubusercontent.com/16348048/235629751-802b21d9-3190-47f4-bbe4-a5f025973d74.png)

L'affichage est "brut", sous forme de liste de string python, et devrait être formaté pour pouvoir afficher de manière plus propre les donnée.

**Comment by camillemonchicourt** [comment]
OK dans la 2.101.0 : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/80af8b0f-2a5a-4eee-8f9e-f16198633b2b)
