### ISSUE TITLE
Docker réseau interne - timeout export descriptif itinéraire

### ISSUE THREAD

**Issue by mougetann** [GeotrekCE/Geotrek-admin#3588]
Bonjour,

Nous avons installé Geotrek via docker sur une Debian 11.6.

Lors d'un clic sur un export PDF, ODT ou DOC d'un itinéraire, une page qui reste blanche s'affiche.

Un timeout apparait dans les logs du container screamshotter:
```
ERROR:root:TimeoutError: Navigation timeout of 60000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /app/src/screenshotter/js/index.js:57:5

ERROR:django.request:Internal Server Error: /
ERROR:root:TimeoutError: Navigation timeout of 60000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111

ERROR:django.request:Internal Server Error: /
```

Ce qui semble faire planter le container convertit:
```
[2023-05-03 15:37:55 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:19)
[2023-05-03 15:37:55 +0000] [19] [INFO] Worker exiting (pid: 19)
[2023-05-03 15:37:56 +0000] [22] [INFO] Booting worker with pid: 22
[2023-05-03 15:39:01 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:22)
[2023-05-03 15:39:01 +0000] [22] [INFO] Worker exiting (pid: 22)
[2023-05-03 15:39:01 +0000] [25] [INFO] Booting worker with pid: 25
```

Le log d'erreur reçu par mail indique lui :
```
Request on http://convertit:6543/?url=https%3A//randoapn-admin-test.doubs.fr/document/trek-66.odt&to=application/msword
 failed (status=400)
```
et
```
Internal Server Error: /document/trek-66.odt
AssertionError at /document/trek-66.odt
Request on http://screamshotter:8000/?url=https%3A//randoapn-admin-test.doubs.fr/trek/66/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520731%252C%2520%2522height%2522%253A%2520731.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522CD25%2520-%2520IGN%2520Plan%2520V2%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded failed (status=500)
```

Notre conf NGINX est tirée de https://github.com/GeotrekCE/Geotrek-admin/blob/master/conf/nginx.conf.in,
Notre .env contient :
```
GEOTREK_VERSION=latest
SERVER_NAME=randoapn-admin-test.doubs.fr
POSTGRES_HOST=###.doubs.fr
POSTGRES_PORT=5432
POSTGRES_USER=geotrek
POSTGRES_DB=geotrek
POSTGRES_PASSWORD=#####
WEB_PORT=8001
API_PORT=8002
```

Et le docker-compose :
```
version: "3"
services:
  memcached:
    image: memcached:1.5-alpine
    restart: always

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    restart: always

  convertit:
    image: makinacorpus/convertit:latest
    restart: always

  screamshotter:
    image: makinacorpus/screamshotter:v2
    restart: always

  celery:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - ./geotrek-admin_var-data:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}
    command: celery -A geotrek worker -c 1
    restart: always

  web:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8001}:8000"
    volumes:
      - ./geotrek-admin_var-data:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
      - screamshotter
      - convertit
    user: ${UID:-0}:${GID:-0}
    restart: always

  api:
    image: geotrekce/admin:${GEOTREK_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "${API_PORT:-8002}:8000"
    volumes:
      - ./geotrek-admin_var-data:/opt/geotrek-admin/var
    depends_on:
      - memcached
      - redis
    user: ${UID:-0}:${GID:-0}
    restart: always

volumes:
  redis:
```
Auriez-vous une idée de l'origine du problème ?

**Comment by babastienne** [comment]
En fait screamshotter essaye de faire une requête vers https://randoapn-admin-test.doubs.fr/ pour pouvoir faire des captures d'écran de carte.

Il semble que le problème soit le suivant : le conteneur screamshotter dans docker n'arrive pas à accéder à internet et donc à l'URL sur laquelle effectuer la capture. 

C'est très probablement quelque chose à corriger côté configuration docker, mais là ca dépasse mes compétences. @LePetitTim peut-être ?

**Comment by submarcos** [comment]
C'est çà, d'ici non plus https://randoapn-admin-test.doubs.fr/ n'est pas accessible. Du à la particularité de docker, les containers ne peuvent acceder aux domaines specifiques à l'hote ou à son infra reseau. Il faut soit utiliser des domaines public, soit ajuster le docker-compose pour specifier des [extra_hosts](https://docs.docker.com/compose/compose-file/compose-file-v3/#extra_hosts) sur les containers screamshotter et convertit

**Comment by franckyx88** [comment]
Bonjour,

Même après ajout des extra_hosts, j'ai toujours le pb.
Pourtant, j'ai testé en me connectant directement aux containers, et les curl passent bien, donc pour moi les containers peuvent communiquer.

Y-a-t-il moyen de passer les containers en mode debug? (que ce soit le web, screamshotter ou convertit)

A priori le problème vient vraiment de l'uri "/document/path-x.odt": Qu'est-ce qui se passe lors de l'appel à cette dernière concrètement? Est-ce que ça lance screamshotter directement?

D'avance merci pour votre aide!

**Comment by franckG88** [comment]
Bonjour,

Pour info, j'ai remonté une infra sous ubuntu 20.04 avec la même conf DNS et les exports fonctionnent correctement. J'en déduis donc qu'il y a un pb avec la stack docker. Je continue à creuser. Je reste à l'écoute si jamais vous avez une idée de débug :)

**Comment by franckG88** [comment]
Re-bonjour,

Je viens de m'apercevoir que les requêtes issues de screamshotter ou de convertit sont bloquées par une erreur 302 "Access to the requested resource is restricted. You have been redirected".
Ce qui n'arrive pas sur l'install ubuntu.

Comment faire pour que les requêtes soient autorisées?

**Comment by franckG88** [comment]
Pb solved: des requêtes sur des fonds de carte en interne n'étaient pas autorisés, et de fait bloquaient screamshotter.
