### ISSUE TITLE
Tri des évènements touristiques dans l'API

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3597]
Par défaut les évènement ne sont pas triés par date de départ, ce qui implique qu'ils apparaissent dans le désordre dans Geotrek-Rando.

Il faut modifier l'API pour changer cela.

https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/api/v2/views/tourism.py#LL103C30-L103C30

**Comment by camillemonchicourt** [comment]
La question des événements et des dates pose souvent question. 
La plupart des événements ont une date de début égale à la date de fin.
Mais il y a aussi des événements longs sur plusieurs mois, notamment les expositions, dont la date de début est souvent passée.
Pour bien gérer ce cas, on s'appuie plutôt sur la date de fin et non pas la date de début pour remonter ou non des évenements et pour les trier par défaut.

**Comment by babastienne** [comment]
Fixed in release [2.100.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.100.0)

**Comment by camillemonchicourt** [comment]
Je ne vois pas trop pourquoi.
C'est bien d'avoir en premier les évènements du jour, de demain, après-demain puis ensuite les évènements en cours mais durant plus longtemps.
Avoir toujours en premier les longs événements (expos,...) puis après les évènements du jour, de demain, après-demain, c'est dommage.

**Comment by babastienne** [comment]
En fait l'utilisateur qui va arriver sur l'interface des évènements va se retrouver avec les évènement triés mais sans parfois se rendre compte qu'il y a des choses en cours qui peuvent l'intéresser.

**Exemple** : je suis un visiteur, nous sommes le 20 septembre et j'ai envie dans les deux prochains jours de faire quelque chose dans le territoire. Quand je vais sur la liste des évènements j'ai ça comme résultat : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/ee17bf4e-cdd8-463c-8d52-dd2e62e2571c)

Le fait que les résultats soient triés comme ça me laisse croire qu'il n'y a rien pendant les jours où je suis présent. Je ne vais pas scroller pour aller voir les évènements suivants vu que logiquement ils doivent être après le 24. 

Sauf que :

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/a2686b5d-0589-402a-b8a6-84e9a580c763)

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/bbd2b3c3-0165-4912-9bd2-a5fafb95b6e4)


Toute l'interface me laisse pourtant croire que je n'ai pas d'interet de scroller vu que les premiers qui s'affichent ont lieu après mon départ et sont triés. Or ce faisant je rate des évènement qui ont lieu en ce moment mais que je ne vois pas en premier. Ce n'est pas logique d'un point de vue de l'usage.

**Comment by camillemonchicourt** [comment]
Ouais je comprends avec l'exemple. En effet pas idéal.
Mais si tu as 10 expos elles prennent tout le temps le dessus. A voir.

Voir aussi la discussions sur les 5 prochains événements remontés sur la Home : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/876#issuecomment-1466456922
Dans ce cas, ça sera tout le temps que des expos les 5 prochains...

Dans tous les cas, modifier le tri dans l'API ne changera pas le comportement dans Geotrek-rando où on a implémenté volontairement le tri par `end_date`, dans la page de recherche mais aussi sur le composant de la Home.

**Comment by babastienne** [comment]
Pour la page d'accueil c'est assez logique en effet d'afficher les évènement par `end_date` pour éviter d'avoir que les évènements longs en permanence.

Par contre je crois pas que le tri par `end_date` ai été effectué sur la page de recherche dans GTR3 ? Il me semble que ça affiche le résultat de l'API par défaut.

En fait l'idéal serait de trier par date de début sauf pour les évènements au-delà d'une certaine durée. Mais bon ça rajoute une logique un peu tordu et donc de la complexité au code ...

**Comment by camillemonchicourt** [comment]
Oui si le tri dépend de la durée, ça devient complexe techniquement, mais aussi pour l'utilisateur.

**Comment by camillemonchicourt** [comment]
Les événements touristiques sont désormais triés par date de début dans l'API et non plus par date de fin dans la version 2.101.0
