### ISSUE TITLE
Outdoor vue qgis n'extrait que les points

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3603]
Les vues qgis v_outdoor_sites ou v_outdoor_courses, représentenet le champ géométrique sous forme de point (via ST_CollectionExtract(a.geom, 1)) ce qui à pour conséquence d'avoir des geométries null si la collection géométrique ne contient aucun point.

**Comment by amandine-sahl** [comment]
une solution serait de séparer les géométrie par type à l'intérieur de la vue. Qgis permet ensuite de charger les couches en fonction de leur type de geométrie. 

L'avantage est de n'avoir qu'une seul vue, l'inconvénient est la duplication potentielle des sites (ou courses) s'ils ont des types de géométrie hétérogènes.

**Comment by camillemonchicourt** [comment]
Oui c'est bien, et les sites avec des géométries hétérogènes, je pense pas que ça court les rues.

**Comment by camillemonchicourt** [comment]
Ajouté dans la 2.101.5.
