### ISSUE TITLE
Ajout d'un modèle `InfrastructureAccess`

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3605]
La notion d'accès semble essentielle en termes de gestion pour les signalétiques, chantiers, aménagements, interventions...

Pour l'instant seuls les aménagements disposent d'un champ textuel "accessibilité", mais je ne suis pas sûr que ce soit le même type d'accessibilité dont je parle ici.

Un modèle `InfrastructureAccess`, créé sur le même principe que `InfrastructureCondition`, permettrait d'associer une liste de valeurs de moyens d'accès pour les gestionnaires aux modèles `Signage`, `Infrastructure`, `Intervention` et `Project`.

Exemple de valeurs que nous stockons actuellement dans le champ `description` des signalétiques : "à pied, "4x4", "véhicule léger", "quad".

**Comment by camillemonchicourt** [comment]
En effet le champs "Accessibilité" sur les aménagements correspond aux éventuels spécificités d'aménagement pour les PMR.

Pourquoi ajouter un champs "accès" basé sur une liste de valeurs.

**Comment by Chatewgne** [comment]
En cours ici : https://github.com/GeotrekCE/Geotrek-admin/pull/3618

**Comment by IdrissaD** [comment]
Intégré dans la 2.99.0 : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0
