### ISSUE TITLE
Création d'une commande de fusion itérative de tronçons

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3607]
Un travail de fusion des tronçons morcelés à été réalisé sur la base de données des Hautes-Alpes afin d'améliorer la qualité du réseau de tronçons. Les tronçons morcelés augmentent le volume des données, la complexité du réseau et les temps de calcul. L'objectif est de trouver un compromis permettant de nettoyer le réseau tout en limitant l'impact sur les objets topologiques existant.

A cette fin, un prototype d'algorithme permettant d'identifier des tronçons à fusionner à été développé. **Il conviendrait de reprendre ces prototypes et les industrialiser dans une commande Geotrek afin que cette procédure soit accessible à la communauté.**

Voici un exemple ci-dessous. Cette procédure pourrait être lancée plusieurs fois d'affilée afin d'alléger progressivement le réseau.

Tronçons avant :
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/26015573/604bb26d-3be7-4b0b-bae8-d465ad2270db)

Identification des couples de tronçons à fusionner :
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/26015573/2481dfd7-b208-458a-a65f-349a803b7408)

Tronçons après :
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/26015573/712e42cf-c0df-4b80-bb7d-92eb4f06bd52)

Cet résultat nécessite
 - un travail préliminaire d'identification des couples : prototypes PostGis et Python ci-dessous
 - un script lançant la méthode `merge_path` sur les couples identifiés

PostGis : trouver les voisins pour chaque tronçon
Il faut ensuite créer un mapping : `{'id1': ['id_voisin1', "id_voisin2']} `
Il faut conserver uniquement les tronçons qui ont 2 voisins (variable `mergeables`) ci après
```sql
select id1, array_agg(id2) from
(select
	p1.id as id1,
	p2.id as id2
from core_path p1, core_path p2
where st_touches(p1.geom, p2.geom) and (p1.id < p2.id)
group by p1.id, p2.id
order by p1.id
) a
group by id1;

```

Python : à partir de la liste  des voisins pour chaque tronçon, identifier des couples fusionnables et les lancer `merge_paths` dessus

```python
import copy
import csv
from geotrek.core.models import Path
from time import sleep
from django.db import connection, transaction

neighbours = dict()  # turn csv into dict
mergeables = []  # paths can be merged if they have 2 neighbours

with transaction.atomic():  # Here
    with connection.cursor() as cursor:
        cursor.execute('''select id1, array_agg(id2) from
                     (select p1.id as id1, p2.id as id2
                     from core_path p1, core_path p2
                     where st_touches(p1.geom, p2.geom) and (p1.id < p2.id)
                     group by p1.id, p2.id
                     order by p1.id) a
                     group by id1;''')

        for path_id, path_neighbours_ids in cursor.fetchall():
            if len(path_neighbours_ids) == 2:
                mergeables.append(path_id)
                neighbours[path_id] = path_neighbours_ids


still_mergeables = copy.deepcopy(mergeables)
merges = 0
merges_couples = []
merges_in = []
merges_out = []
merges_flat = []
for i in mergeables:
    if i in still_mergeables:
        neighbour = neighbours.get(i, None)
        if neighbour:
            first_neighbour = neighbour[0]
            if first_neighbour in still_mergeables:
                merges += 1
                merges_couples.append((i, first_neighbour))
                merges_flat.append(i)
                merges_flat.append(first_neighbour)
                merges_in.append(i)
                merges_out.append(first_neighbour)
                still_mergeables.remove(i)
                still_mergeables.remove(first_neighbour)

#print(merges_couples)
# print(f"{len(merges_in)=}")
# print(f"{len(merges_out)=}")
# print(f"{len(set(merges_in))=}")
# print(f"{len(set(merges_out))=}")

algo_ok = set(merges_in).isdisjoint(set(merges_out))

print(algo_ok)

if algo_ok:
    successes = 0
    fails = 0
    for (a, b) in merges_couples:
        patha = Path.include_invisible.get(pk=int(a))
        pathb = Path.include_invisible.get(pk=int(b))
        success = patha.merge_path(pathb)
        if success == 2:
            print(f"3rd path in intersection of {a} and {b}")
            fails += 1
        elif success == 0:
            print(f"No matching points to merge paths {a} and {b} found")
            fails += 1
        else:
            print(f"OK {a} {b}")
            successes += 1
        sleep(0.5)

    print(f"\n {successes} succesful merges - {fails} failed merges")


```

:)

**Comment by camillemonchicourt** [comment]
OK très intéressant.
En effet il n'y a pas de raison d'avoir 2 tronçons qui n'ont pas d'intersection entre eux (c'est-à-dire un nœud avec au moins 3 tronçons).
Le PNC et OPenIG avait partagé tout un travail d'intégration et de nettoyage préalable des tronçons existants avec pas mal de SQL et il serait intéressant en effet d'en disposer en tant que commande Geotrek - https://geotrek.ecrins-parcnational.fr/ressources/technique/2022-08-OPenIG-integration_reseau_dans_BDD_geotrek.pdf

**Comment by camillemonchicourt** [comment]
Commande `merge_segmented_paths` intégrée dans la 2.101.5.
Avec la doc qui va avec : https://geotrek.readthedocs.io/en/latest/install/import.html#merge-segmented-paths
