### ISSUE TITLE
Ajout d'un champ "accès" sur les signalétiques - Valeurs pour formulaire

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3617]
Bonjour,

afin de spécifier comment accéder aux signalétiques pour les interventions, un champ "accès" va être rajouté sur les Signalétiques.

Les valeurs envisagées sont les suivantes :

- VL
- 4*4
- Quad
- Pédestre

Y aurait-il d'autres options intéressantes à ajouter dans les fixtures de base ?

Merci !

https://github.com/GeotrekCE/Geotrek-admin/pull/3618

**Comment by Chatewgne** [comment]
Merci Camille pour ton retour et pour les tickets que je n'avais pas vus, je pars sur "Moyen d'accès" avec un texte de précision.

**Comment by IdrissaD** [comment]
Intégré dans la 2.99.0 : https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0
