### ISSUE TITLE
Ajouter l'attribut "district" sur les vues qui contiennent l'attribut "cities" dans l'API V2

### ISSUE THREAD

**Issue by Huquette** [GeotrekCE/Geotrek-admin#3632]
Ajouter l'attribut "district" aux vues de l'API V2 qui exposent déjà un attribut "cities" (
- /outdoor_course/
- /outdoor_site/
- /tour/
- /touristiccontent/
- /touristicevent/
- /trek/), 
afin d'inclure des informations sur les secteurs.

**Comment by babastienne** [comment]
Ok testé sur notre démo et validé.

Développé dans la release [2.99.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.99.0).
