### ISSUE TITLE
Publier/dépublier une étiquette

### ISSUE THREAD

**Issue by Huquette** [GeotrekCE/Geotrek-admin#3640]
Le but étant de permettre la publication/dépublication d'une étiquette ce qui permet de l'inclure ou non dans l'API v2. Permet de gérer des informations ponctuelles plus aisément.

**Plus de précision** : Voir la discussion suivante :  https://github.com/GeotrekCE/Geotrek-admin/discussions/3529

**Comment by camillemonchicourt** [comment]
Si une étiquette n'est pas publiée, alors on ne l'a remonte pas dans l'API v2. Ni sur la route qui liste les étiquettes, ni sur les objets (treks et sites Outdoor) à laquelle elle est associée.

Attention au cache de l'API et GTR3 qui peut entraîner du temps avant qu'une étiquette re-publiée remonte sur GTR3.

Si une étiquette n'est pas publiée, est-ce qu'on l'a propose à la saisie dans les treks et sites Outdoor ? Je dirai oui, mais faire afficher quand l'étiquette n'est pas publiée je pense.
Pas forcément à la saisie, mais dans la fiche détail d'un trek ou site outdoor.

**Comment by Huquette** [comment]
Côté Sites, j'ai fait cela, est-ce ok ? les étiquettes publiées sont affichées avec un badge vert.

![image (1)](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/d201517f-8b04-4802-a9aa-2e42f9129f6f)

Côté Treks, les étiquettes sont affichées comme cela, avec une ligne pour chaque : 

![trek](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/f793a480-1784-4314-ac51-ab03c151d7e7)

Est-ce nécessaire d'uniformiser les deux affichages afin de mettre une liste comme pour les Sites ? Ou doit-on laisser "oui/non" avec les étiquettes et mettre le badge devant le nom de l'étiquette ? :)

**Comment by camillemonchicourt** [comment]
Oui très bien pour les sites.
Et c'est vrai que pour les treks, on avait fait un peu compliqué pour les afficher comme des champs.
Mais comme ce ne sont pas des champs, au final ce qui est fait pour les sites Outdoor est plus simple, plus clair.

Donc je ferai sur le treks comme sur les sites, juste la liste des étiquettes associées à celui-ci, avec le picto indiquant si chaque étiquette est publiée ou non.

**Comment by Huquette** [comment]
J'ai fait de même pour les Treks :

![trekmodified](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/3ced1e30-0cd6-4a05-b270-4b65282bd661)

**Comment by camillemonchicourt** [comment]
OK dans la 2.100.0.
Par contre, comme Geotrek-rando-v3 garde les infos en cache, cela n'est pas répercuté de suite.
Pour qu'une étiquette soit supprimée des filtres des randos et des fiches randos sur lequel il est associé, il faut vider le cacher de GTR3, donc redémarrer le docker.

Donc la fonctionnalité reste partiellement effective, car la plupart des structures n'ont pas la main pour redémarrer GTR3. 
Et pour ceux qui ont la main, ça reste un peu lourd.

**Comment by babastienne** [comment]
Ce problème de cache est valable pour de nombreux objets dans Geotrek-Rando-V3, c'est pour ça qu'il existe le paramètre permettant de le désactiver complètement. C'est assez genant ce cache au quotidien, en particulier pour les territoires qui démarrent avec leur Geotrek car ça peut poser des problème lorsqu'ils créé de nouveau objets (lieu d'information touristique par exemple), ceux-ci n'étant pas mis à jour automatiquement. Je dirai que pour le coup le problème maintenant est plutôt dans la stratégie d'invalidation du cache.

**Comment by camillemonchicourt** [comment]
Ouais ça peut être gênant mais c'est tellement essentiel aussi de ne pas requêter des centaines de fois par jour des choses qui ne changent que quelques fois par an (et encore).
Et cela permet aussi de gagner en temps de chargement des pages ce qui est crucial pour les visiteurs, mais aussi pour le référencement.
Donc le gain du cache est beaucoup beaucoup plus important que la gêne occasionnée dans quelques cas.

Mais je dirai que le soucis est particulièrement important pour les étiquettes car la fonctionnalité de publier/dépublier a été mise en place pour pouvoir faire remonter ou non des infos temporaires, donc dans ce cas, il y a plus de risques que cela bouge et que l'on souhaite que ça se répercute rapidement.
