### ISSUE TITLE
Allow to filter by multiple organisms on Blades list

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3646]
Pour la cohérence globale avec les Signalétiques où c'est déjà le cas changer le type de filtre pour permettre de sélectionner plusieurs structures au niveau de la liste des Lames.

Il manque également un placeholder qui indique de quel champ il s'agit pour ce filtre.

Filtres liste des lames :

![Capture d’écran du 2023-07-21 14-28-59](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/ec3b7d12-949b-491a-abe5-57ebed8545aa)

Filtres liste des signalétiques (pour exemple) :

![Peek 21-07-2023 14-50](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/ae87e080-e635-42c1-a49d-6130166458cf)

Testé en 2.99.0.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.100.0
