### ISSUE TITLE
Signalétiques | Ajout d'un champ "État du scellement"

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3654]
Développement : Identifier les besoins d'intervention sur les scellements liés aux signalétiques.

Création un nouveau modèle "état du scellement", qui contiendra un champ texte.
Dans le module Signalétique, ajouter un sélecteur d'état (menu déroulant).

Valeurs prédéfinies pour ce modèle :

- À créer
- À refaire
- Bon état
- Platine à resserrer
- Poteau à resserrer sur platine
- Poteau à resserrer sur fourreau

Y - a-t-il d'autres valeurs par défaut à ajouter ?

**Comment by camillemonchicourt** [comment]
Bon pourquoi pas.
On a déjà un état de la signalétique, donc j'ai l'impression que ça fait un peu beaucoup d'avoir un état de la signalétique et un état du scellement. 
Mais pourquoi pas, si c'est un besoin un minimum partagé.
Mais il faut veiller à ne pas ajouter des champs sans fin, à chaque besoin de chaque structure.

Mais dans ce cas, peut-être que c'est utile et pertinent, je n'ai pas d'avis précis sur le sujet.

Par contre, avoir un champ ETAT et un champs ETAT_SCELLEMENT apporte un peu de confusion il me semble.

A minima il faudrait renommer et préciser le champs ETAT en ETAT_SIGNALETIQUE pour bien le distinguer de l'autre champs ETAT_SCELLEMENT.

**Comment by IdrissaD** [comment]
Qu'est-ce qu'un scellement "à créer" exactement ? Si une signalétique est en place, alors elle a forcément un scellement, non ? Même s'il est direct ou en plein sol.

Je suis d'accord avec Camille sur la possible redondance avec le champ déjà existant : est-ce que les valeurs comme "Platine à resserrer" ou "Poteau à resserrer sur platine" n'auraient-elles pas déjà leur place dans la liste de valeurs du champ `etat` pour les structures souhaitant les utiliser ? Ou bien dans la description de la signalétique ?

Si une liste de valeurs est créée pour les scellements, la question d'un champ `ETAT_LAME` se posera bientôt.

Si ce besoin est partagé par plusieurs structures, est-ce qu'une solution ne pourrait pas être de décorréler l'état des signalétiques de l'état des aménagements ?

Un modèle `InfrastructureCondition` strictement réservé aux aménagements, et un modèle `SignageCondition` réservé aux signalétiques. Éventuellement ce dernier modèle pourrait avoir une relation de plusieurs à plusieurs avec les modèles `SignageSignage` et `SignageBlade`, ce qui permettrait de renseigner plusieurs valeurs si besoin.

**Comment by camillemonchicourt** [comment]
Oui je pense aussi qu'il vaudrait mieux enrichir le champs état existant avec des éléments concernant le scellement plutôt que d'ajouter un second champs d'état du scellement uniquement.

**Comment by Chatewgne** [comment]
Transformer le champ "état" des signalétiques en sélection multiple me semble être une piste intéressante, afin d'associer plusieurs états ("Lame à remplacer" + "Poteau en bon état" + "Scellement à refaire")  à une même signalétique.

Côté modèle, pour un `SignageCondition`, quels seraient les champs intéressants en plus du label ? Un sélecteur qui permettrait de préciser si cet état concerne les lames, les poteaux ou les scellements ? Ca permettrait notamment de filtrer ou grouper dans les listes d'états.

**Comment by IdrissaD** [comment]
Un autre avantage de permettre cette sélection multiple serait de pouvoir mettre l'information "Lame à remplacer" tant au niveau de la lame que de la signalétique. Alors oui, ça fait une information redondante, mais ça permettrait de filtrer toutes les signalétiques ayant au moins une lame à remplacer, au lieu de devoir forcément passer par le module "Lames".

Un désavantage serait par contre qu'on pourrait attribuer l'état "Scellement à refaire" à une lame, ce qui devrait être évité.

**Comment by camillemonchicourt** [comment]
La solution de basculer le champs "Etat" en multiple est retenue.
Par contre, ça implique d'avoir des listes d'état distincts entre signalétique, aménagements et lames. 
Un peu plus lourd, mais cela évite d'avoir des états incohérents proposés sur les différents objets.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.101.5
