### ISSUE TITLE
Problème de duplication des sites outdoor

### ISSUE THREAD

**Issue by Huquette** [GeotrekCE/Geotrek-admin#3665]
Imaginons qu'on ait un site outdoor parent avec deux enfants sites comme ceci : 

![liste](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/832a780d-ffd4-46c5-8e5c-eaca6c580a5d)

![listedetail](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/861f6406-8734-476c-9461-d96391003885)

Lorsqu'on duplique le site outdoor parent, on s'attend à avoir un site outdoor parent dupliqué possédant deux enfants sites dupliqués également.
Le problème est que le site outdoor parent dupliqué ne possède pas d'enfant, et les enfants dupliqués sont rattachés au site outdoor parent non dupliqué.
Voici la démo :

[bug.webm](https://github.com/GeotrekCE/Geotrek-admin/assets/92665273/4be25ec1-cbc5-4fc3-aed2-d58c42eba087)

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain que si on duplique un site parent, on souhaite forcément dupliquer ses sites enfants.
Je dirai même plutôt que non.

**Comment by camillemonchicourt** [comment]
Je pense que ça peut être problématique de dupliquer les sous-sites et va la plupart du temps générer des doublons non souhaités.

Donc je partirai sur le fait d'uniquement dupliquer le site, mais peut-être garder les mêmes eventuels sous-sites que le site dont il est une duplication.

**Comment by babastienne** [comment]
Un sous-site ne peut pas avoir plusieurs parents, donc on ne pourrait pas garder le site parent dupliqué ne pourra pas conserver les mêmes enfants.

Mais ok, je note que les sous-sites ne doivent pas être dupliqués.

**Comment by camillemonchicourt** [comment]
Ah oui OK, c'est vrai !

**Comment by babastienne** [comment]
Fixed in release [2.100.0](https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.100.0). An outdoor site is now duplicated without the associated children. Is the Outdoor Site has a parent the duplicate keeps the link with the parent.
