### ISSUE TITLE
Utilisation du dossier "bulkimport" ?

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3673]
Est-ce que le dossier "bulkimport" à la racine du projet est toujours utilisé et utile ?

Si non peut-on le supprimer ?

**Comment by camillemonchicourt** [comment]
A ma connaissance on l'utilisait pour y mettre son fichier `parser.py` customisé (https://github.com/GeotrekCE/Geotrek-admin/blob/2.32.0/docs/import.rst) jusqu'à la version 2.33 quand toute l'architecture du projet a été revue et qu'un fichier `migrate.sh` a été créé pour passer de l'ancienne structure à la nouvelle.
D'ailleurs cette migration bascule bien le fichier vers la nouvelle structure de fichiers : https://github.com/GeotrekCE/Geotrek-admin/blob/master/tools/migrate.sh#L49

Donc plus utile depuis la version 2.33.0 de ce que j'en comprends.

**Comment by babastienne** [comment]
Oui c'est ce que j'ai compris également. Je propose donc de le supprimer
