### ISSUE TITLE
Problème de mémoire (screamshotter)

### ISSUE THREAD

**Issue by vprunet** [GeotrekCE/Geotrek-admin#3707]
Bonjour,
Mon instance de geotrek admin (2.100) sur ubuntu 20.04 a un problème de consommation mémoire.
Le souci semble provenir des sous-process lancés par screamshotter (2.0.19) qui ne terminent pas.

Qu'est ce que je peux faire à part relancer constamment le service screamshotter?

Merci

systemctl status screamshotter.service 
● screamshotter.service - Screamshotter
     Loaded: loaded (/lib/systemd/system/screamshotter.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-09-08 09:31:40 CEST; 1h 13min ago
   Main PID: 730 (gunicorn)
      Tasks: 94 (limit: 14249)
     Memory: 728.5M
     CGroup: /system.slice/screamshotter.service
             ├─ 730 /opt/screamshotter/bin/python /opt/screamshotter/bin/gunicorn --config=/opt/screamshotter/conf/gunicorn-screamshotter.conf.py screamshotter.wsgi:application
             ├─2621 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess ->
             ├─2634 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --disable-breakpad --headless --oz>
             ├─2641 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=renderer --headless --lang=fr --no-sandbox --disable-dev-shm-usage --disable-backgr>
             ├─2647 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=renderer --headless --lang=fr --no-sandbox --disable-dev-shm-usage --disable-backgr>
             ├─2771 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess ->
             ├─2788 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --disable-breakpad --headless --oz>
             ├─2792 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=renderer --headless --lang=fr --no-sandbox --disable-dev-shm-usage --disable-backgr>
             ├─2805 /opt/screamshotter/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome --type=renderer --headless --lang=fr --no-sandbox --disable-dev-shm-usage --disable-backgr>
             └─2918 /opt/screamshotter/bin/python /opt/screamshotter/bin/gunicorn --config=/opt/screamshotter/conf/gunicorn-screamshotter.conf.py screamshotter.wsgi:application

**Comment by camillemonchicourt** [comment]
Oui soucis identifié ici - https://github.com/GeotrekCE/Geotrek-admin/issues/3214

Qui aurait dû être réglé par la nouvelle version de screamshotter.

Mais j'ai aussi toujours le soucis.
Je redémarre régulièrement le serveur en attendant, mais ce n'est pas idéal.

**Comment by vprunet** [comment]
Merci Camille. J'ai cherché une issue "scream" avant de poster mais je me rends compte que github veut des mots entiers dans les recherches ... Je le saurai pour la prochaine fois :-)

**Comment by babastienne** [comment]
Hello. De notre côté on relance le service screamshotter une fois par jour, en général avant de faire les synchronisations de contenus avec les SIT (ou sync_mobile). Depuis qu'on fait ça on a plus de problèmes sur nos serveurs.

**Comment by babastienne** [comment]
duplicate of #3214
