### ISSUE TITLE
Problème d'affichage des img de l'admin

### ISSUE THREAD

**Issue by franckG88** [GeotrekCE/Geotrek-admin#3735]
Bonjour,

Je rencontre un problème d'affichage au niveau de mon site public (geotrek-rando-v3).

Sur l'accueil, ce dernier va charger des img provenant du serveur d'admin (geotrek-admin) en http (exemple: http://url/media/upload/practice-foot.svg)

Le souci est que geotrek-rando-v3 est publié en https, et l'affichage de ressources en http sur une page publiée en https est bloquée par le navigateur.

Comment forcer le site à afficher les ressources de geotrek-admin en https uniquement?

D'avance merci !

Franck

**Comment by marcantoinedupre** [comment]
Pourriez-vous indiquer votre procédure d'installation et votre architecture svp ? Si vous utilisez nginx avez-vous modifié la configuration nginx fournie ?

**Comment by franckG88** [comment]
Bonjour,

Problème réglé, c'était bien dû à une coquille dans la conf nginx.

Merci pour les pistes :)
