### ISSUE TITLE
GAG 2.100.2 : Erreur de chargement PDF

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3739]
(EDIT) Geotrek-admin : 2.100.2

Nous avons un problème de chargement des PDFs  (chargement à l'infini => error 404 lorsque l'on veut télécharger le PDF d'un itinéraire) de la part de nos utilisateurs en Lozère pour ce site : https://rando.lozere.fr/search?practices=8. Cela est récurrent à une heure précise de la journée (à partir de 22H00). 

Après avoir regardé avec notre hébergeur nous avons confirmé que nous n'avons pas de problème de performance serveur, mais bien inhérent à Geotrek. 

En regardant les logs nous avons vu beaucoup d'erreur lié à Gunicorn. Apparemment Gunicorn ne répondant pas à la demande d'URL Nginx ne peut faire passer l'url du pdf à l'utilisateur qui est à l'origine de la requête. 

Voici les logs trouvés dans var/log/nginx : 
[geotrek_error.log](https://github.com/GeotrekCE/Geotrek-admin/files/12701481/geotrek_error.log)

Et les logs trouvés dans /opt/geotrek-admin/var/log : 
[geotrek.log](https://github.com/GeotrekCE/Geotrek-admin/files/12701493/geotrek.log)

J'ai vu dans les log un lien avec l'appel des touristicevent par l'API. Est-ce que cela correspond au fix fait dans la maj 2.100 ? 

Si jamais le problème est trop long à détecter je peux utiliser les heures de TMA à notre disposition. 

Merci à vous.

**Comment by babastienne** [comment]
@mviadere-openig à priori je dirais que ton problème n'a rien à voir avec les développements de la 2.100.

Au feeling je dirai qu'il faudrait programmer un redémarrage régulier de tes instances (rando / admin / screamshotter), une fois par jour par exemple, pour essayer de décharger un peu le serveur.

En tout cas actuellement je n'arrive pas à tester ton problème car j'ai une erreur 504 (timeout) pour accéder au site rando.

**Comment by mviadere-openig** [comment]
Le site est de nouveau rétabli, je vais contacter votre service commercial pour demander l'utilisation de TMA pour régler le problème.

**Comment by mviadere-openig** [comment]
Informations supplémentaire le temps de mise en place de solution : 

 - Mon interface de monitoring me prévient tous les jours que l'url correspondant au Geotrek-Admin n'est pas accessible. Je dois chaque matin refaire un reboot serveur + dpkg-reconfigure geotrek-admin, pour que le site fonctionne à nouveau. 
 
 Concernant le redémarrage régulier des instances, je rebootais Geotrek toutes les 4 heures et screamshotter toutes les 30 minutes. Je vais rajouter un reboot serveur et et j'ai mis le  redémarrage de screamshotter et de geotrek à une fois par jour.

**Comment by camillemonchicourt** [comment]
OK bizarre tous ces redémarrages.
On ne fait pas ça sur notre Geotrek-admin et je ne pense pas que ce soit souhaitable/acceptable.

On a encore un soucis des tâches screamshotter qui s'empilent et nécessitent de redémarrer screamshotter de temps en temps.
Voir le ticket sur le sujet, qui est un soucis qu'il faut corriger dès qu'on aura les moyens de s'y pencher.

**Comment by mviadere-openig** [comment]
@camillemonchicourt ces redémarrages dataient  de la période du bug de screamshotter, comme j'avais dû régler cela en urgence pendant mes congés, j'avais mis un temps de redémarrage des services très courts.

**Comment by camillemonchicourt** [comment]
Oui car redémarrer aussi fortement et régulièrement, mais aussi relancer des dpkg-reconfigure ne sont pas censés être faits.

**Comment by mviadere-openig** [comment]
Je ne lançais pas régulièrement dpkg-reconfigure geotrek-admin à l'époque, je ne le fais que depuis trois jours pour rétablir le site.

**Comment by mviadere-openig** [comment]
Nouvelles informations concernant l'issue : nous avons fait un rollback du serveur datant du 6 septembre 2023, où la version de Geotrek-Admin est la 2.99.0. Le problème était déjà présent, avec un autre comportement découvert il y a peu de temps : Geotrek-Admin se charge...aléatoirement. 

Je m'explique : Certains utilisateurs se connectant aux GTK-Admin vers 8h30 du matin n'auront aucun soucis, mais à partir de 10h et jusqu'uà midi l'application chargera à l'infini, empêchant la disposition de l'api et rendant Le GTK-Rando inutilisable. 

Erreurs les plus fréquentes : 

/opt/geotrek-admin/var/log/geotrek.log :

ERROR 2023-09-27 10:00:01,932 mapentity.helpers Request on http://localhost:8000/?url=https%3A//openig-gag-cd48.ataraxie.fr/trek/5052/%3Flang%3Dfr%26context%3D%257B%2522mapsize%2
522%253A%2520%257B%2522width%2522%253A%2520702%252C%2520%2522height%2522%253A%2520702.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%25
22OpenTopoMap%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520
%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded failed (status=500)


/var/log/nginx/geotrek_error.log : 

2023/09/27 12:00:32 [crit] 860#860: *428 connect() to unix:/tmp/gunicorn-geotrek_api.sock failed (2: No such file or directory) while connecting to upstream, client: 91.206.199.171, server: openig-gag-cd48.ataraxie.fr, request: "GET /api/v2/touristicevent_type/?language=fr&fields=id,type,pictogram HTTP/1.1", upstream: "http://unix:/tmp/gunicorn-geotrek_api.sock:/api/v2/touristicevent_type/?language=fr&fields=id,type,pictogram", host: "openig-gag-cd48.ataraxie.fr"

**Comment by submarcos** [comment]
@mviadere-openig : 

connect() to unix:/tmp/gunicorn-geotrek_api.sock failed (2: No such file or directory) while connecting to upstream,

çà signifie que, pour une raison ou une autre, les workers gunicorn dédiés à l'api sont indisponibles. çà arrive lorsqu'ils prennent trop de RAM et sont "killed" par ta machine.

et le dpkg-reconfigure ne sert a rien, si pb il y a, au reboot le serveur redemmare, et au pire un ```sudo systemctl restart geotrek``` devrait faire l'affaire. (çà stoppe les services et les relance sans reboot / rejouer les migrations etc)

maintenant il te reste a determiner ce qui provoque çà. Pour le paliatif, tu peux regarder au niveau de la doc de gunicorn pour configurer tes workers pour reboot tout seuls lorsqu'ils quittent. Ensuite, et surtout, monitorer ton API endpoint par endpoint, peut etre avec sentry, pour savoir à quel niveau çà pete. J'ai deja vu des trucs pareils à cause de calculs d'intersections geographiques trop complexes

**Comment by babastienne** [comment]
@mviadere-openig problème toujours d'actualité ?

**Comment by mviadere-openig** [comment]
Bonjour, 

le problème des chargements des PDF est toujours d'actualité, cela fait maintenant plus d'un mois que les utilisateurs de ce Geotrek obtiennent une erreur 500 lorsque l'on souhaite charger un PDF.  (Geotrek est en version 2.101.5)

Nous avons mis en place Sentry de notre côté depuis hier, et l'erreur qui remonte lorsque l'on clique sur un PDF est toujours liés au mapentity/helpers.py : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/45095227/bb0adfb7-33c8-4d5c-bafb-6bbc397ddc68)
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/45095227/30802ef8-8016-4223-b4a1-2f4c552ecfc4)
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/45095227/06d61588-6db5-4c79-8b69-6c816e07deee)

J'ai fait des captures d'écrans mais je suis preneur si vous avez des meilleurs moyens de partages d'informations.

**Comment by Chatewgne** [comment]
Bonjour @mviadere-openig 

il y a des nouvelles au sujet de screamshotter ici : https://github.com/GeotrekCE/Geotrek-admin/issues/3866#issuecomment-1898692946

@submarcos a également rajouté des informations dans la doc pour le troubleshooting : 
https://geotrek.readthedocs.io/en/master/troubleshooting.html#error-500-with-document-generation-or-map-capture

**Comment by mviadere-openig** [comment]
Oui, j'ai vu le sujet ce matin, merci à toi, je regarderai cela de plus près dès que possible et vous ferai un retour.

**Comment by mviadere-openig** [comment]
J'ai procédé aux recommandations de la doc et de ticket,  (screamshotter et ajout de l’en-tête X-Forwarded-Proto https). 

Dans un premier temps aucune image ne s'affichait par la suite sur le Geotrek-Rando (problèmes de CORS) mais cela a fini par se régler tout seul. Je considère donc que c'est bon pour moi. Je ferme le ticket, merci pour ton retour @Chatewgne !
