### ISSUE TITLE
Préparation màj Django 4.2

### ISSUE THREAD

**Issue by submarcos** [GeotrekCE/Geotrek-admin#3754]
Geotrek est toujours en django 3.2, LTS encore supportée jusqu'au 30/04/2024.

Il va falloir préparer la màj en django 4.2

Fait notable dans cette version de django, la version de ```postgresql``` devra être **supérieure ou égale** à la **12**

Actuellement, le support de Ubuntu 18.04 bionic, et l'installation par défaut de postgresql-server sur ce serveur, des versions postgresql 10 sont déployées.

Il faudrait dans la mesure du possible "préparer" cette migration en incitant les utilisateurs à mettre à jour leur serveur postgres aux versions 15 et postgis 3.3 (postgresql 16 et postgis 3.4 sont sortis mais je ne sais pas à ce jour si ils sont 100% compatibles avec django 3.2)

La problématique, c'est qu'avec le paquet debian, rien ne bloquera l'installation si une version trop ancienne de postgres est utilisée, car à cause de l'utilisation externe d'une BDD, postgres n'est pas une dependance de geotrek-admin.

Un simple docker pull ou apt-upgrade vers la future version de geotrek-admin avec django 4.2 pourrait déclencher un problème par forcement visible au premier abord, mais avec au final un admin non fonctionnel (impossible à démarrer)

Donc que ce soit debian ou docker, il faudrait des à present sensibiliser à la mise à jour des BDD.

Du côté des dépdendances à mettre à jour, on est sensiblement à jour, mapentity supporte déjà django 4.2 donc une grosse partie du travail est faite. Il restera quelques dépendances à fixer qui causent des breaking changes aujourd'hui

- [x] https://github.com/GeotrekCE/Geotrek-admin/pull/3734
- [x] https://github.com/GeotrekCE/Geotrek-admin/pull/3641
- [x] https://github.com/GeotrekCE/Geotrek-admin/pull/3502

mais elles ne seront pas forcément bloquantes

**Comment by submarcos** [comment]
On pourrait être tenté de se dire qu'il faudrait au passage assurer la compatibilité avec [Ubuntu 22.04 Jammy](https://github.com/GeotrekCE/Geotrek-admin/issues/3295)

Mais comme indiqué dans le ticket çà va rajouter de la complexité car rien n'a été tranché à ce sujet pour le moment

**Comment by camillemonchicourt** [comment]
Oui pour moi ce sujet était corrélé avec l'ajout du support Ubuntu 22 et en même temps l'arrêt du support Ubuntu 18, mais OK si c'est traitable indépendamment.

**Comment by babastienne** [comment]
> Il faudrait dans la mesure du possible "préparer" cette migration en incitant les utilisateurs à mettre à jour leur serveur postgres aux versions 15 et postgis 3.3

@submarcos peux-tu préciser la procédure à suivre pour que les utilisateurs puissent mettre à jour leur postgres ?
