### ISSUE TITLE
Mise à jour de l'ordre des étapes d'itinérance dans l'agrégateur

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3793]
Le parseur d'agrégation des itinéraires ne gère pas correctement la mise à jour de l'ordre des étapes d'itinérances.

Dans cet exemple, l'étape 3 a été importée comme première étape (car c'était la première a être créée et publiée ?) mais elle doit désormais passer en 3ème position. L'agrégation échoue avec une exception qui empêche le ré-ordonnancement de ces étapes mais également la mise à jour de toutes les itinérances suivantes.

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/26015573/a2a4aef1-c887-48f1-84d9-4e0dc2cdf03c)

```
trek_parent_instance=<MultilingualNoDeleteQuerySet [<Trek: GR® 93>]>
trek_child_instance=<Trek: [GR® 93] Etape 1 : Lus-la-Croix-Haute - Lachaup>
trek_child_instance=<Trek: [GR® 93] Etape 2 : Lachaup - Saint-Etienne en Dévoluy>
trek_child_instance=<Trek: [GR® 93] Etape 3 : St-Etienne en Dévoluy - Chaudun>
An error occured in children generation : IntegrityError('duplicate key value violates unique constraint "o_r_itineraire_itineraire2_parent_id_child_id_af89cf9e_uniq"\nDETAIL:  Key (parent_id, child_id)=(17833, 19165) already exists.\n')
```

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.101.2.
