### ISSUE TITLE
Erreur sur l'onglet service

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#3795]
Bonjour, 
Suite au passage à la version 2.101, nous avons un message d'erreur sur l'onglet service.
Est-ce que ça vous parle ?

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/33490969/066a3600-6ca5-4fa6-b52d-d0921b2c63d4)

```
Internal Server Error: /api/service/drf/services.datatables

AttributeError at /api/service/drf/services.datatables
Got AttributeError when attempting to get a value for field `name` on serializer `DatatablesSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Service` instance.
Original exception text was: 'ServiceType' object has no attribute 'review'.
```

**Comment by babastienne** [comment]
Bonjour,

C'est assez étrange, je ne reproduit pas ce problème. 
La 2.101.1 corrige un bug mais ce n'est pas celui-ci.

Il y n'y a pas eu de modification particulière liée au services dans la 2.101. Par contre dans la 2.100 on a corrigé un bug justement lié à datatables et aux Services : https://github.com/GeotrekCE/Geotrek-admin/issues/3521

Ton erreur me fait un peu penser à ce bug, mais vu qu'il a été corrigé justement ça m'étonne.


Est-ce que sur votre instance il y a un paramétrage particulier (dans le custom.py) lié aux colonnes affichées dans la vue liste ou à datatable ?

**Comment by camillemonchicourt** [comment]
Sinon ça peut justement être un problème de cache du navigateur ou du serveur ?

**Comment by jeromesourdin** [comment]
Bonjour,
J'ai vidé tout les caches et ça ne résout pas le problème. Il y avait bien une config pour les colonnes dans le custom.py : 
```
COLUMNS_LISTS['trek_view'] = ['structure', 'practice', 'length_2d']
```
Je l'ai commenté et restart géotrek, et idem...

**Comment by jeromesourdin** [comment]
Après de multiple tests, j'ai réussi à résoudre le problème par la modification de la ligne https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/views.py#L456 en supprimant le 'name', et en ajoutant la ligne suivante au custom.py : 
```
COLUMNS_LISTS["service_view"] = ["type"]
```
Ce n'est surement pas la bonne méthode, mais je n'ai plus d'erreur. Si ça peut aider a résoudre le problème...

**Comment by camillemonchicourt** [comment]
OK, en effet les services n'ont pas de champs NAME, mais seulement un id et un type.
Donc peut-etre un truc à revoir car ça a en effet été modifié récemment : https://github.com/GeotrekCE/Geotrek-admin/commit/6c9b8f8c7d2cfc9daf99237dd641721a5fa56b8a

**Comment by babastienne** [comment]
Oui en effet j'ai l'impression qu'il y a un lien avec ce commit. Mais ce qui est bizarre c'est que le problème ne survienne pas sur d'autres instances ... :thinking:

**Comment by jeromesourdin** [comment]
Est-ce que cela peu venir du fait d'avoir sauté plusieurs versions ?

**Comment by babastienne** [comment]
Non. Lorsqu'on passe d'une ancienne version à une nouvelle la mise à jour repasse chaque migration de base une à une, comme si faisait chaque mise à jour l'une après l'autre, donc normalement ça n'engendre pas de problèmes.

**Comment by submarcos** [comment]
Ce n'est pas le champ '[name](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/serializers.py#L390)' qui pose probleme en temps que tel. Le serializer de la liste se sert de la proprieté [name_display](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/models.py#L914), qui affiche un lien et une icone en fonction de plusieurs attributs. le nom, le statut publié etc. dans le cas ou le service n'est pas publié, il va regarder la propriété self.type.review, Or un type de service n'a pas d'attribut review (différence entre PublishableMixin et BasePublishableMixin). Donc çà ne marche pas pour les instances ayant des services non publiés.

**Comment by babastienne** [comment]
Oups, si je comprends bien c'est donc mon code qui a tout cassé ... :grimacing: 

L'idée du ticket #1669  c'était justement d'enlever cet attribut `review` qui n'avait pas de sens sur le model `servicetype`. Par contre ce que je réalise c'est que j'ai fais le travail à moitié, j'ai oublié de supprimer le code que tu as pointé dans ton commentaire @submarcos .

**Comment by Chatewgne** [comment]
Bonjour, un fix est publié dans la version 2.101.2, merci d'avoir remonté le problème
