### ISSUE TITLE
Effet de bord de la customisation des couleurs

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3800]
La customisation suivante : 
`MAP_STYLES['intervention'] = {'color': '#001bc0'}`
ou
`MAPENTITY_CONFIG['MAP_STYLES']['intervention'] = {'color': '#001bc0'}`

a pour effet de casser les liens cliquables (on ne peut plus cliquer sur l'intervention sur la carte pour afficher sa page détail)

Ca n'a pas l'air de poser problème si on fait la même chose sur les tronçons (linéaires vs points ?)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.101.4

**Comment by DepartementGard** [comment]
Semble bien fonctionner sur tous les modules. Validé par CD30
