### ISSUE TITLE
How to manage "complex" language code

### ISSUE THREAD

**Issue by geobrun** [GeotrekCE/Geotrek-admin#3801]
HI everybody,

I'm trying to use GeoTrek to create a website listing hiking trails in Taiwan (which is a beautiful country to hike!). Everything worked fine on a virtualbox with my first tests (DEM, path management, etc.).

Unfortunately, I'm stuck with the language management. I don't want to have the admin interface in Chinese: I only want to be able to 
manage the content in Chinese (descriptions, titles, etc.).

I understood that I have to configure the languages during the installation process. For my tests, I filled in these information: ('fr', 'en', 'zh-hant'). Unfortunately, the dash character produces an error while a column is created in the PostgreSQL database (in the query: ADD COLUMN name_zh-hant). The only way I managed to get the installation without having an error was to fill in the language setting with an underscore (zh_hant). But in this configuration, the GeoTrek application doesn't show the Chinese language when I create an object (only French and English).

I don't know what exactly happens here but my guess is that the GeoTrek interface needs the official Django code for Chinese (zh-hant) while the database use a wrong language code (zh_hant). So both probably doesn't match.

I found a solution by keeping the usual language code in the settings (zh-hant) and then modifying every SQL script from `ADD COLUMN name_{{lang}}` to `ADD COLUMN \"name_{{lang}}\"`. But there is a lot of files to modify if I want the column name to accept the dash character! Maybe is there a trick to have the 'zh_hant' suffix in the database matching with the app language code 'zh-hant'? Has anyone an idea how I can solve this problem?

**Comment by submarcos** [comment]
Thank you for your report. It's a bug, we will fix that in a next release

**Comment by geobrun** [comment]
Thank you for your support! In exchange, I will provide Traditional Chinese translation for the GeoTrek-rando website and the mobile app if you are interested in.

**Comment by camillemonchicourt** [comment]
Of course we are interested ! 👍️

**Comment by geobrun** [comment]
I took a look at the PR you are working on. I applied the modifications you made into my installation. That's great, it's working: the fields in the database are now created with the Chinese code. But then, I faced some other problems with the admin interface and the API service.

So I spent a bit of time looking at the code to understand how GeoTrek-admin works. At the end, I found which files I had to modify and how to modify them in order to fully implement Chinese (as well as other sub-languages).

Here is a summary of what I did:
* Add some others `replace('-', '_')` functions in others Python files as you did in your PR
* Add a new "replace" filter in `/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/templatetags/mapentity_tags.py`
* Use this filter in the HTML code of `/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/forms.py` in order to link the Chinese HTML inputs to the database fields
* Add a parameter `LANGUAGE_CODE` in `/opt/geotrek-admin/var/conf/env.in` (which is currently forced to `fr` causing a problem in the treks form)
* Modify the Regex in `/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/url.py` in order to extend the numbers of characters in the language code from 2 to 7 (the maximum I found in Django language codes)

At the end, here is what I did to test that the basic functions of GeoTrek-admin are working in Chinese:
* Set the `LANGUAGES` parameter in the `env` file to `en zh-hant`
* Create an object in each GeoTrek category (Path, Trek, Poi, Infrastructure, etc.)
* Fill in every text field in these objects with Chinese language (even the English fields)
* Create an object in each GeoTrek category of the Django Administration website (niveaux de difficulté, parcours, pratique, etc.)
* Fill in every text field in these objects with Chinese language (even the English fields)
* Open every link of the API v2

With the modifications I suggest, I finally got no error. But I noticed that in some files, there are some language variables that have not the `replace('-', '_')` function. At this moment, I don't know if these variables are unused or if they are used in some "hidden" functions of the Geotrek-admin interface.

Until now, I have only worked on the main API, not on the mobile one. I think the modifications I suggest will have no impact on others GeoTrek users because they only affect the management of the `zh-hant` language code (mainly with the `replace('-', '_')`) function.

If it's all right for you, I can send you a PR to complete the one you started to write. Or I can send a PR which includes the modifications that you made in your PR? I don't know what's the best practice in this case!

In the future, I think I will be able to provide others PR for the mobile API, as well as to complete some other python files I didn't modify with the `replace('-', '_')` function if needed. Of course, I think I will also have to modify the Geotrek-rando code to manage Chinese! For this part, I have already translated half of the texts to Chinese.

**Comment by camillemonchicourt** [comment]
OK thanks for these tests.
The best I think is to do a new PR based on the branch of this PR, to make a PR adding your things to this PR.

**Comment by geobrun** [comment]
Ok, thanks for the advice! I committed these modifications in the PR [3830](https://github.com/GeotrekCE/Geotrek-admin/pull/3830) and [281](https://github.com/makinacorpus/django-mapentity/pull/281) (this last one in the Mapentity repository).

I'm not aware of all the best practices so let me know if I did something the wrong way.

**Comment by geobrun** [comment]
Hi @submarcos,

Do you have any idea about when the PR could be integrated into a future release? Before the end of the year? At the beginning of the next year? Is there something I can do to help?

**Comment by Chatewgne** [comment]
> Hi @submarcos,
> 
> Do you have any idea about when the PR could be integrated into a future release? Before the end of the year? At the beginning of the next year? Is there something I can do to help?

Hi @geobrun, sorry for the delay, we're working on it and I'm hoping to release it in early January.

Thank you for contributing to Geotrek !

**Comment by geobrun** [comment]
Thanks for this information, let me know if I can help somehow!

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.101.5.

**Comment by Chatewgne** [comment]
Further work on the matter is to be done on Geotrek-Rando-v3 : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1011

**Comment by geobrun** [comment]
Thanks for this great work, it seems to work fine on my VM! :)

I came across an other language error during the installation (but not critical). It comes out when the French language is not specified in the languages settings. I will open an other issue for this small thing after some more tests.

**Comment by camillemonchicourt** [comment]
De mémoire, on peut ajouter autant de langues que l'on souhaite mais on ne peut pas enlever EN et FR qui sont présentes de base et présentes en dur dans le code.
Mais je dis ça sans maîtrise technique et de mémoire.
A discuter dans un ticket dédié en effet, car c'est un sujet intéressant qu'il peut être bon de préciser/clarifier.
