### ISSUE TITLE
#35 - Ajouter un champs "Moyen d'accès" sur les interventions

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3819]
scope: Dev

Rajouter un champ libre “Accès”  dans module"Iinterventions" comme dans le module "Signalétiques"

Modèle différent de signage_access

**Comment by Chatewgne** [comment]
S'inspirer de `InfrastructureAccessMean`

**Comment by camillemonchicourt** [comment]
Dans la version 2.99.0, un champs "Moyen d'accès" a été ajouté sur les signalétiques et les aménagements : https://github.com/GeotrekCE/Geotrek-admin/pull/3618
A nommer de la même manière par cohérence.
Et j'aurai garder la même liste de valeurs, car je vois pas pourquoi les moyens d'accès seraient différents pour les interventions.

La seule réserve que j'ai sur le sujet, est que les interventions sont souvent associées à des signalétiques et des aménagements, où on a déjà un champs "Moyen d'accès". Donc ajouter la saisie de cette info aussi au niveau de l'intervention peut amener à une saisie redondante d'une même info à 2 endroits différents (ce qu'on évite toujours dans une BDD), voire incohérente.

Mais si on considère qu'il y a aussi beaucoup d'interventions qui ne sont associées à aucune signalétique ou aménagement, alors ce champs a du sens.

**Comment by camillemonchicourt** [comment]
> Est-ce que par contre si on a une intervention liée à une signalétique avec accès on doit pouvoir éditer l'accès de l'intervention ou alors on considère que l'info n'est pas éditable car déjà existante sur l'objet associé ?

C'est la question que je me suis posé.
Ça aurait du sens, mais un peu complexe, et pas forcément compréhensible pour l'utilisateur.
Je dirai que si on ajoute ce champs, il fonctionne comme un champs classique dans tous les cas, et à chacun de le remplir ou non selon son intervention...

**Comment by babastienne** [comment]
Ok ça me va, en effet je pense que sinon ça ajoute une logique un peu complexe à comprendre au premier abord et à maintenir.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.101.5.

**Comment by DepartementGard** [comment]
Intégration validée par le CD30, nous utilisons principalement le module intervention pour les travaux liés aux tronçons (débroussaillage, débitage d'arbre, réfection d'assise, réfection de murs...).
