### ISSUE TITLE
#8bis - Pouvoir filtrer les listes par structure par défaut

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3822]
scope: Dev

Cela veut dire filtrer par structure ? oui

**Comportement actuel**
Le filtre par structure reste d'une session à l'autre. Lorsqu'un utilisateur filtre par sa structure, ensuite il n'a plus besoin de remettre ce filtre lorsqu'il change de module ou ré-ouvre Geotrek plusieurs jours après.

**Comportement attendu**

Avoir un paramètre de configuration Geotrek (désactivé par défaut), qui permet de filtrer les données par structure automatiquement.

Cela signifie que lorsque l'utilisateur est connecté par défaut il n'aura accès qu'aux données de sa structure.

**Question / limite**

- Les données actuelles sont intégralement chargées puis filtrées. Il est peu probable que cela accélère la chargement des données
- Sachant le comportement actuel, est-ce nécessaire de développer le comportement attendu ?

**Comment by camillemonchicourt** [comment]
Vu qu'on charge tout par défaut dans tous les cas, je ne vois pas trop l'intérêt de filtrer par défaut par Structure.

Les filtres par défaut ont souvent pour conséquence que les utilisateurs ne comprennent pas pourquoi ils ne voient que certaines choses et passent à côté des autres données, ne sachant pas qu'elles existent.

Mais si cela reste un paramètre désactivé par défaut, OK pour moi.

**Comment by DepartementGard** [comment]
Besoin pas prioritaire. Si cela ne permet pas de gagner en amélioration de performance, on peut classer ce suite cette proposition de développement.
