### ISSUE TITLE
#36 - Ajouter un champs “Coût main d'oeuvre" sur les interventions

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3824]
scope: Dev

- Ajouter un champ “Coût main d'oeuvre" dans le module "Intervention" (similaire à "cout sous-traitance")
- “Coût total intervention” faisant la somme “Coût main d’oeuvre” + ”Coût matériel” + “Coût héliportage” + “Coût journalier” x “Jour” + "Coût sous-traitance"

Dans le module “Chantiers” le “coût total interventions” recensera la somme des champs “Coût total intervention” des interventions affectées au chantier listé (déjà le cas, à vérifier)

Penser à l'export du champ dans les listes

**Comment by babastienne** [comment]
Pour les chantiers oui c'est  le cas. Le "à vérifier" était surtout pour penser à prendre en compte cette vérification si on ajoute un champ en plus.

Pour le coût main d'oeuvr,e à priori il s'agit d'un nouveau champ en plus des jours/hommes. Ce serait un autre champ, similaire au champ "sous-traitance" (à savoir un montant libre en saisie). 

Peut-être que le département peu apporter une précision sur ce qui différencie la main d'oeuvre des jours/hommes ?

**Comment by camillemonchicourt** [comment]
Oui car là nommer comme ça, ça semble la même chose et donc porter à confusion.

**Comment by DepartementGard** [comment]
Le besoin est d'identifier le coût de main d’œuvre de l'intervention d'un prestataire (différent du coût de main d’œuvre en régie directe et différent du coût de sous-traitance ou le prestataire peut faire appel à d'autre entreprise pour réaliser certaines missions de la prestation).
Pour éviter la confusion, peut être nommer ce nouveau champ "coût de prestation"?

**Comment by babastienne** [comment]
Renommer le champ "Coût sous-traitance" en "Coût prestataire"

**Comment by camillemonchicourt** [comment]
La solution retenue est uniquement de renommer un champs existant "Coût sous-traitance" en "Coût prestataire", pour qu'il soit plus clair qu'il englobe tous les couts de la prestation, incluant la main d'oeuvre du prestataire.
Mais sans ajouter un champs "Coût main d'œuvre" qui apporte de la confusion avec les champs existants de jours/hommes, comme discuté plus haut.

**Comment by DepartementGard** [comment]
Reprise de la dénomination Coût de sous-traitance en Coût Prestataire validée par le CD30
