### ISSUE TITLE
#34 - Interventions - Séparer la date en 2 champs - Date début et Date fin

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3825]
scope: Dev

**Besoin initial**
 
Intégrer champs “Date d’ouverture” et “Date de réception” au format JJ/MM/AAAA pour filtre “Année” car aujourd’hui année automatiquement renseignée sur date de saisie de l’intervention (un chantier de 2021 saisi aujourd’hui est comptabilisé comme chantier 2022 !)

--

**Spécifications plus complètes**

Certaines interventions sont remontées une année, et réalisées une autre année. Il y a besoin de distinguer deux dates : la date de remontée d'intervention (création) et la date de réception (réalisation). Cela permettrait dans l'export / filtre d'avoir les interventions sur des années glissantes.

Pour être plus générique, création de champ : 
- Date de début
- Date de fin

Que faire des données existantes ? Migré dans le champ "Date de début"

Quel champ obligatoire ? ▶ Date de début

Dans la vue liste on affiche la date de début.

Il faut pouvoir filtrer les interventions qui n'ont pas de date de fin.

Pas d'impact sur le(s) chantier(s) associé(s).

Impact sur le workflow Suricate : la date de résolution (fin) du signalement devra être ce champ "Date de fin" de l'intervention associée.

**Comment by camillemonchicourt** [comment]
Je m'interroge sur le fait de séparer la date en fin / début. 
Je vois 2 manières de l'interpréter (début et fin des travaux ou date de lancement des travaux et date de validation/réception). 
Et cela va alourdir la saisie. 
Mais peut-être que c'est plus clair, utile et plus précis que de renseigner le début et la fin quand les travaux ont lieu sur plusieurs jours ?

Là aussi, à voir comment migrer les anciennes données, certainement en lançant le champs "Date de fin" vide car le renseigner automatiquement avec la date actuelle serait faux pour les interventions qui ont duré plusieurs jours.

**Comment by camillemonchicourt** [comment]
Retour de mon collègue qui gère les travaux sentiers au PNE : "Pour les champs Date, c'est pertinent car on sait jamais si on doit saisir la fin ou le début."

Donc OK pour nous.

**Comment by juggler31** [comment]
Pour le filtre, j'envisage d'avoir un intervalle de date pour pouvoir filtrer finement sur les interventions.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.101.5.

**Comment by camillemonchicourt** [comment]
Le champs "Date de fin" ne semble pas traduit : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/cbb06c9c-26f9-47d9-9b28-f2f555502430)

**Comment by babastienne** [comment]
Les filtres par date ne sont plus distinguables (on ne sait pas lequel correspond à la date de début et lequel correspond à la date de fin)

Il faudrait avoir des tooltips pour mieux comprendre à quel champ correspond quel filtre. 

![Image](https://github.com/GeotrekCE/Geotrek-admin/assets/16348048/92700faf-a7dc-41a6-873f-37fc29c40827)

Vérifier les cas d'usage des filtres pour s'assurer que tout fonctionne correctement. Documenter ces cas.

Voir pour ajouter un filtre "année" qui filtre par période (remonter toute intervention qui est sur l'année saisie, y compris si l'évènement n'est pas terminé sur l'année saisie).

Fixer l'oubli de traduction.

**Comment by camillemonchicourt** [comment]
Je ne sais pas si des tooltips suffisent car pas tout le monde les voit. A voir si on peut voir en permanence à quoi correspond chaque champs (comme c'est le cas pour les autres champs) plutôt que d'afficher "jj/mm/aaaa" ? Quitte à avoir un tooltip pour indiquer des compléments d'info sur le fonctionnement si c'est complexe ?

Voir aussi le filtre de date sur le module ÉVÉNEMENTS pour homogénéiser ?
Il est intéressant car plus simple avec seulement 2 dates à renseigner, mais à un soucis de fonctionnement : https://github.com/GeotrekCE/Geotrek-admin/issues/3895

**Comment by babastienne** [comment]
A terme il faudrait harmoniser les filtres dates de début / fin avec le module évènements (ticket dédié à créer).

**Comment by camillemonchicourt** [comment]
OK dans la 2.102.2
