### ISSUE TITLE
Erreur sur api v2 lorsqu'on utilise les pictogrammes sur les signaletiques

### ISSUE THREAD

**Issue by juggler31** [GeotrekCE/Geotrek-admin#3839]
# Resumé

Lorsqu'on utilise les pictogrammes sur les signalétiques, on se retrouve avec une erreur 500.

Cela vient du LineSerializer (https://github.com/GeotrekCE/Geotrek-admin/blob/1aa50fa3b179c74f187046c800fe26a9992bd789/geotrek/api/v2/serializers.py#L1395-L1400)
# Reproduction

- Créer une Signalétique avec une lame qui possède un pictogramme
- Puis aller su api/v2/signage/

**Comment by bruhnild** [comment]
Problème reproduit avec cet appel API : `https://geotrek-admin.cevennes-parcnational.net/api/v2/signage/`
