### ISSUE TITLE
# 23 - Possibilité de sélectionner plusieurs états sur les signalétiques et lames

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3847]
Dans l'objectif de pouvoir associer autant d'états que nécessaire (par exemple : "poteau en bon état + scellement à refaire")

On fait diverger les états d'infrastructures et de signalétiques / lames qui jusqu'ici étaient stockés dans le même modèle

https://github.com/GeotrekCE/Geotrek-admin/issues/3654

**Comment by camillemonchicourt** [comment]
Fait dans la 2.101.5.

**Comment by babastienne** [comment]
- Manque la traduction FR dans l'admin pour "Signage condition" (à corriger)
- Les structures associées aux états d'aménagements ne sont plus associées aux dupliquas sur les signalétiques

**Comment by DepartementGard** [comment]
Le fait de pouvoir affecter plusieurs état à la signalétique répond au besoin. En effet, dans le champ liste, nous avons rajouté l'état du scellement ce qui permet par le filtre de faire ressortir les scellements défectueux.

Par contre, sur le module aménagement, on ne peut affecter qu'un seul Etat. Il faudrait pouvoir en mettre plusieurs ce qui permettre sur l'exemple d'un platelage d'avoir l'info sur l'état des lattes et l'état d'un scellement différent ou sur un portillon avoir un bon état, mais un scellement défectueux. Le fait que les champs listes aménagements et signalétiques soient déconnectés permet à chacun d'adapter le champ liste états aux spécificités.
