### ISSUE TITLE
Problème de thumbnail avec les SVG

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-admin#3860]
Bug détecté à partir de la version 2.101.4 de Geotrek Admin.  

Celui est déclenché par l'ajout d'un SVG comme pictogramme sur un lieu de renseignement. 

Explication : la dernière version de easy_thumbnail n'accepte pas de faire le thumbnail d'un SVG. -> l'api V2 plante

**Comment by submarcos** [comment]
Il faudrait utiliser la sous-dep [easy-thumbnails[svg]](https://github.com/SmileyChris/easy-thumbnails#breaking-news)
