### ISSUE TITLE
Erreur 500 génération PDF pour certaines randos en 2.101.4

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-admin#3866]
Ubuntu 20.04.6 LTS
Geotrek-admin 2.101.4

Bonjour,

Depuis quelques temps, sur plusieurs randos, l'export pdf conduit à une erreur interne 500. Je ne trouve pas quelles sont les différences avec les randos qui fonctionnent. En remontant dans les logs, le problème ne semble exister que depuis la version 2.101.4.

Je pense avoir parcouru toutes les issues, dont #2358 et #3739 , mais je ne trouve pas de solution. Voici ce que j'ai vu dans logs : 

```
$ sudo tail -f /opt/geotrek-admin/var/log/geotrek.log

ERROR 2023-12-22 10:11:00,504 mapentity.helpers Request on http://localhost:8000/?url=https%3A//geotrek.guadeloupe-parcnational.fr/trek/3603/%3Flang%3Dfr%26auth_token%3DW7TDC_f15j9NKMLP6YhLTx-tK_SlorMKFWlYbE3AnS4%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520901%252C%2520%2522height%2522%253A%2520901.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522Scan%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded failed (status=500)
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 103, in download_to_stream
    source = get_source(url, headers)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 89, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://localhost:8000/?url=https%3A//geotrek.guadeloupe-parcnational.fr/trek/3603/%3Flang%3Dfr%26auth_token%3DW7TDC_f15j9NKMLP6YhLTx-tK_SlorMKFWlYbE3AnS4%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520901%252C%2520%2522height%2522%253A%2520901.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522Scan%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded failed (status=500)
ERROR 2023-12-22 10:11:01,112 django.request Internal Server Error: /api/fr/treks/3603/bains-chauds-du-matouba.pdf
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/mixins/views.py", line 212, in dispatch
    return super(mapentity_views.MapEntityDocumentBase, self).dispatch(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/mixins/views.py", line 222, in get
    return super().get(request, pk, slug, lang)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/trekking/views.py", line 153, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/mixins/views.py", line 203, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/mixins/views.py", line 237, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/views/generic.py", line 224, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/views/generic.py", line 195, in get_context_data
    self.get_object().prepare_map_image(rooturl)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/mixins/models.py", line 404, in prepare_map_image
    super().prepare_map_image(rooturl)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/models.py", line 302, in prepare_map_image
    capture_map_image(url, path, size=size, waitfor=self.capture_map_image_waitfor, printcontext=printcontext)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 210, in capture_map_image
    capture_image(url, fd,
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 186, in capture_image
    download_to_stream(url, stream)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 103, in download_to_stream
    source = get_source(url, headers)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/helpers.py", line 89, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://localhost:8000/?url=https%3A//geotrek.guadeloupe-parcnational.fr/trek/3603/%3Flang%3Dfr%26auth_token%3DW7TDC_f15j9NKMLP6YhLTx-tK_SlorMKFWlYbE3AnS4%26context%3D%257B%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520901%252C%2520%2522height%2522%253A%2520901.0%257D%252C%2520%2522print%2522%253A%2520true%252C%2520%2522maplayers%2522%253A%2520%255B%2522Scan%2522%252C%2520%2522Zone%2520de%2520sensibilit%255Cu00e9%2522%252C%2520%2522POIs%2522%252C%2520%2522Services%2522%252C%2520%2522Signal%255Cu00e9tiques%2522%252C%2520%2522Am%255Cu00e9nagements%2522%255D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded failed (status=500)
```

```
$ sudo journalctl -eu screamshotter
...
gunicorn[6425]: ERROR:root:/opt/screamshotter/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271
gunicorn[6425]:                 reject(new Error([
gunicorn[6425]:                        ^
gunicorn[6425]: Error: Failed to launch the browser process!
gunicorn[6425]: chrome_crashpad_handler: --database is required
gunicorn[6425]: Try 'chrome_crashpad_handler --help' for more information.
gunicorn[6425]: [6529:6529:1222/140620.200821:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
gunicorn[6425]: TROUBLESHOOTING: https://pptr.dev/troubleshooting
gunicorn[6425]:     at Interface.onClose (/opt/screamshotter/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271:24)
gunicorn[6425]:     at Interface.emit (node:events:526:35)
gunicorn[6425]:     at Interface.emit (node:domain:488:12)
gunicorn[6425]:     at Interface.close (node:internal/readline/interface:527:10)
gunicorn[6425]:     at Socket.onend (node:internal/readline/interface:253:10)
gunicorn[6425]:     at Socket.emit (node:events:526:35)
gunicorn[6425]:     at Socket.emit (node:domain:488:12)
gunicorn[6425]:     at endReadableNT (node:internal/streams/readable:1408:12)
gunicorn[6425]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gunicorn[6425]: Node.js v20.9.0
gunicorn[6425]: ERROR:django.request:Internal Server Error: /
```

Merci d'avance si vous avez au moins des pistes à explorer,
Noël (et bonnes fêtes !)

**Comment by JulesGrillot** [comment]
Je possède la même erreur, les anciens trajets qui étaient fonctionnels, si ils sont modifiés (sans réaliser de modification) et enregistrés produisent l'erreur 500 après enregistrement.

**Comment by amandine-sahl** [comment]
idem de mon coté

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas.
J'ai essayé en production puis sur le serveur de DÉMO.

Le PDF public de cette rando (https://geotrekdemo.ecrins-parcnational.fr/trek/2/) fonctionne.
Je la modifie et enregistre sans rien modifier, son PDF fonctionne toujours.
Je suis aussi en version 2.101.4.

Pouvez-vous préciser le cas où cela se produit ou d'autres logs ?

**Comment by JulesGrillot** [comment]
`Screamshotter` à été mis-à-jour puis j'ai essayé de lancer la commande qui semblait causer l'erreur, `sudo /opt/screamshotter/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-field-trial-config --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold --enable-features=NetworkServiceInProcess2 --headless=new --hide-scrollbars --mute-audio about:blank --no-sandbox --no-zygote --disable-setuid-sandbox --disable-dev-shm-usage --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-pE5OOq`

Voici les erreurs que j'obtiens : 

> [43692:43704:0111/151535.130932:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [43692:43704:0111/151535.131322:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [43692:43704:0111/151535.131504:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [43692:43704:0111/151535.131765:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [43692:43692:0111/151535.260331:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
> [43692:43704:0111/151535.281086:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> [43692:43704:0111/151535.281202:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> 
> DevTools listening on ws://127.0.0.1:33783/devtools/browser/23f88c02-4a04-452b-85cd-471f09b8e932
> [43692:43780:0111/151535.943051:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [43692:43780:0111/151535.943383:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [43692:43780:0111/151535.943646:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [43739:43755:0111/151546.898577:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
> Warning: loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
> Warning: loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so supports Vulkan 1.1, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
> Warning: loader_scanned_icd_add: Driver /usr/lib/x86_64-linux-gnu/libvulkan_intel.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
> Warning: Layer VK_LAYER_MESA_device_select uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
> error: XDG_RUNTIME_DIR not set in the environment.
> error: XDG_RUNTIME_DIR not set in the environment.
> Warning: eglChooseConfig returned zero configs
>     at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:52)
>     at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:97)

**Comment by submarcos** [comment]
Bonjour,
merci pour les logs détaillés
Il y a bien un problème avec la dernière version de screamshotter, l'outil qui génère les cartes pour les documents/ pdf etc.
Dans un certain cas uniquement (mise à jour depuis une ancienne version sur ubuntu focal 20.04) il n'arrive plus à fonctionner et lève ces erreurs.

Les versions ubuntu bionic 18.04 / docker et les installations "fraiches" directement sur la dernère version ne sont pas concernées.

En attendant un correctif de screamshotter, vous pouvez procéder comme suit : 

- faites un backup de vos données
- assurez-vous d'utiliser les dernières version
- supprimer geotrek-admin (la BDD et les fichiers de conf / medias ne seront pas touchés, sauf si vous avec touché les fichiers nginx.conf / nginx.conf.in
```
sudo apt remove geotrek-admin
```
Supprimez screamshotter en purgeant ses fichiers de confguration
```
sudo apt remove --purge screamshotter
```
Réinstallez geotrek-admin (et par dépendence screamshotter
```
sudo apt install geotrek-admin
```

J'ai reproduis et corrigé le problème comme suit sans perte de données. Attention quand même je vous conseille encore de faire un backup de votre dossier /opt/geotrek-admin + BDD juste au cas ou.

Je vous préviendra isur ce ticket lorsqu'on aura réussi à sortir une nouvelle version de screamshotter qui arrive à corriger le problème tout seul

**Comment by submarcos** [comment]
Bonjour,

j'avais proposé une solution un peil complexe,
mais il semble que j'ai trouvé bien plus simple et moins risqué.

Donc, pour corriger le problème en attendant une màj de screamshotter : 

```
sudo systemctl stop screamshotter
sudo usermod -d /opt/screamshotter screamshotter
sudo systemctl start screamshotter
```

Une section de documentation pour les probèmes courant de capture de carte va être rajouté

**Comment by noelmartinon** [comment]
Nickel pour moi aussi, merci !

**Comment by submarcos** [comment]
Normalement, la nouvelle version de [screamshotter](https://github.com/makinacorpus/screamshotter/releases/tag/2.2.2) corrige ça.

```bash
sudo apt update
sudo apt install screamshotter
```
