### ISSUE TITLE
Error 500 - OGC WKT expected, EWKT provided

### ISSUE THREAD

**Issue by JulesGrillot** [GeotrekCE/Geotrek-admin#3875]
Bonjour,

J'ai réalisé l'upgrade de Ubuntu, Geotrek-Admin, PostgreSQL et Postgis.
Tout semble fonctionner sauf lorsque j'essaie de sauvegarder un tronçon, j'obtiens une erreur 500.
Si je refresh la page sur cette erreur, la modification est bien sauvegardée. L'étape se font donc en 2 temps.

Dans les logs PostgreSQL une erreur apparaît : 

> 2024-01-03 14:48:03.067 CET [277910] geotrek@geotrekdb ATTENTION:  OGC WKT expected, EWKT provided - use GeomFromEWKT() for this double free or corruption (out) 

Voici le log que j'obtiens avec la commande `sudo journalctl -eu geotrek-ui` :
[geotrek-ui.log](https://github.com/GeotrekCE/Geotrek-admin/files/13821451/geotrek-ui.log.txt)

Et voici mes logs PostgreSQL : 
[postgresql-15-main.log](https://github.com/GeotrekCE/Geotrek-admin/files/13821456/postgresql-15-main.log.txt)

Avant upgrade :
- Ubuntu : 18.04
- PostgreSQL : 10.23
- Postgis : 2.5.5
- geonetwork-admin : 2.97.2

Après l'upgrade :
- Ubuntu : 20.04
- PostgreSQL : 15.5
- Postgis : 3.4.1
- geonetwork-admin : 2.101.4

**Comment by marcantoinedupre** [comment]
La compatibilité de Geotrek-Admin avec ces versions de Postgresql et Postgis n'est pas assurée. Le logiciel est testé pour fonctionner avec les paquets par défaut sur Ubuntu 20.04 :

- postgresql 12
- postgis 3.3

**Comment by submarcos** [comment]
Je ne pense pas que OGC WKT expected, EWKT provided soit l'origine du problème, car c'est une alerte qui existe depuis relativement longtemps sans poser de soucis.

Par contre, les logs indiquant l'état anormal de la base de données, l'impossibilité d'établir une connexion SSL 

Est-ce que la migration de la version de postgis a bie nété effectuée (ALTER POSTGIS VERSION etc)
Est-ce que l'extension postgis_raster a bie nété installée ? (Postgis : 3 a extrait la gestion des rasteurs dans une nvlle extension)

**Comment by JulesGrillot** [comment]
Bonjour,

Je refais une montée en niveau clean :
    Ubuntu : 20.04
    PostgreSQL : 12.17
    Postgis : 3.4.1
    geonetwork-admin : 2.101.4

Je n'ai plus le bug décrit précédemment avec l'erreur 500.
Par contre le message d'erreur du log postgre à été modifié pour :

> 2024-01-11 13:30:29.965 CET [32224] geotrek@geotrekdb ATTENTION:  OGC WKT expected, EWKT provided - use GeomFromEWKT() for this
