### ISSUE TITLE
Régression - Fiche chantier - Affichage de toutes les interventions et Error console

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#3878]
Quand on accède à la fiche d'un chantier, il n'affichait avant que les interventions du chantier concerné sur la carte.

Désormais il affiche TOUTES les interventions présentes dans la BDD et charge indéfiniment : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/8f36d3c0-5e73-4bb9-9077-024cf6c7d3e5)

Avec une erreur dans la console (même après avoir vidé le cache) : 

```
Uncaught TypeError: e is undefined
    grep jQuery
    jsonLoad https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:588
    bind https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:11
    jQuery 8
    load https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:588
    initialize https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:587
    e https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:11
    <anonymous> https://geotrekdemo.ecrins-parcnational.fr/project/2/:1822
    jQuery 7
    <anonymous> https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:438
    jQuery 7
    <anonymous> https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:438
    jQuery 7
    <anonymous> https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:235
    jQuery 2
    triggerEvent https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:406
    djangoMap https://geotrekdemo.ecrins-parcnational.fr/static/CACHE/js/output.fa05dce93b66.js:405
    loadmap https://geotrekdemo.ecrins-parcnational.fr/project/2/:1585
    EventListener.handleEvent* https://geotrekdemo.ecrins-parcnational.fr/project/2/:1589
    <anonymous> https://geotrekdemo.ecrins-parcnational.fr/project/2/:1595
```

Reproduit en production et sur le serveur de DEMO : https://geotrekdemo.ecrins-parcnational.fr/project/2/

**Comment by babastienne** [comment]
Même problème que #3571 ?

**Comment by camillemonchicourt** [comment]
Oui ça semble le même soucis en effet.
Sauf que cet autre ticket (que j'avais zappé) n'indique pas que la carte affiche TOUTES les interventions présentes dans la BDD, alors qu'elle ne devrait afficher que celles du chantier.

Enfin on doit pouvoir afficher la couche de TOUTES les interventions en l'activant dans le contrôle des couches, mais par défaut on avait initialement que les interventions du chantier, avec une interaction carte-liste quand on arrive au niveau de la liste des interventions du chantier.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.101.5
