### ISSUE TITLE
#1 - Intégration de données - P1

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3894]
scope:  Intégration de données

Intégration / mise à jour de données APN et premier niv de zonage envtal:
- Nouveaux RLESI (Côtes du Rhône gardoises (attention : une partie à attribuer à la “Structure liée CA Gard Rhodanien / l’autre à CA Grand Avignon) ; Viganais Nord ; Pôle nature Aigoual phase 2 et complément phase 1 ; Piémont Cévenol ; Remplacement données Pôle nature Mont Lozère ; Remplacement Nîmes Métropole, bornes course d’orientation PN Aigoual / Rochefort du Gard / PN Mont Lozère).;
- Véloroutes - Voies vertes (couche serv. Routes) ;
- Zones de récurrence d'interventions
- Page web: intégrer la donnée “Destinations” différente de la donnée “Secteurs” (contour EPCI) 
- Données naturalistes:
      - Distinction zone coeur PNC et zone adhésion (mettre zone adhésion en orange et zone coeur en orange foncé)
      - Revoir colorimétrie des zones naturelles (ex: Inverser les couleurs Arrêté Préfectoral de Protection de Biotope (à mettre en rouge) ZNIEFF2 (en rose) --> pouvoir nous ouvrir l'accès sur colorimétrie de ces zonages 
      - Intégrer la Réserve Naturelle Nationale de l’Ardèche.
      - Intégrer les Réserves Naturelles Régionales
      - Mise à jour de la couche Espaces Naturels Sensibles Départementaux
     - Intégrer les Réserve de Chasse et de Faune Sauvage
     - Intégrer les Réserves de Biosphères
     - Intégrer les Sites Inscrits et classés
     - Intégrer les Opérations Grands Sites

Distinguer les zones réglementaires des autres zonages

**Comment by DepartementGard** [comment]
Manque des intégrations:
 **Signalétique** des RLESI Aigoual Phase2 + Vallée Borgne existant + bornes course d’orientation / RLESI PN Mont Lozère / Bornes course orientation CA Grand Avignon
**Equipements** du PN Mont Lozère
**POI** Mont Lozère / POI Piémont Cévenol
Restera les zones de récurrences en lien avec le développement du module intervention #30
