### ISSUE TITLE
[Question]Version de postgresql et postgis à utiliser pour GTK-Admin sur Ubuntu 20.04

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#3901]
Geotrek versions 2.101.5

Bonjour,suite à la mise à jour de l'OS d'un VM de ubuntu 18.04 vers 20.04, la BDD de Geotrek est passé sous postgresql 14 et la version de postgis utilisée est la 3.4.1 (qui sont compatibles). 

Depuis cette mise jour Geotrek semble avoir de gros soucis dès que l'on souhaite travailler sur un itinéraire faisant plus de 100 km (ou travailler sur la modification/creation/suppression d'objets). 
Voici l'erreur que me reporte Sentry : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/45095227/cf785e4f-5f36-44f7-bac0-09dfa01ba601)

J'ai pensé au début à un soucis en lien avec la BDD et j'ai voulu lancer la commande `update public.core_path set geom = geom;` qui a donné cette erreur : 
```
Query 1 ERROR at Line 1: : FATAL:  failed to load summary "/usr/lib/postgresql/14/lib/bitcode/postgis-3.index.bc": Invalid summary version 8, 1, 2, 3 or 4 expected
CONTEXT:  instruction SQL « WITH -- Get endings of each segment of the line
                 r1 AS (SELECT ST_PointN(linegeom, generate_series(1, ST_NPoints(linegeom)-1)) as p1,
                               ST_PointN(linegeom, generate_series(2, ST_NPoints(linegeom))) as p2,
                               generate_series(2, ST_NPoints(linegeom)) = ST_NPoints(linegeom) as is_last),
                 -- Get the number of sub-segments
                 r2 AS (SELECT p1, p2, is_last, trunc(ST_Distance(p1, p2) / step)::integer + 1 AS n FROM r1),
                 -- Get relative positions of new points along the segment (without last point, except for last segment)
                 r3 AS (SELECT p1, p2, generate_series(0, CASE WHEN is_last THEN n ELSE n - 1 END)/n::double precision AS f FROM r2),
                 -- Create new points
                 r4 AS (SELECT ST_MakePoint(ST_X(p1) + (ST_X(p2) - ST_X(p1)) * f,
                                            ST_Y(p1) + (ST_Y(p2) - ST_Y(p1)) * f) as p,
                               ST_SRID(p1) AS srid FROM r3),
                 -- Set SRID of new points
                 r5 AS (SELECT ST_SetSRID(p, srid) as p FROM r4)
            SELECT add_point_elevation(p) FROM r5 »
fonction PL/pgSQL ft_drape_line(geometry,integer), ligne 17 à RETURN QUERY
fonction PL/pgSQL ft_elevation_infos(geometry,double precision), ligne 46 à FOR sur des lignes de SELECT
instruction SQL « SELECT * FROM ft_elevation_infos(NEW.geom, 1) »
fonction PL/pgSQL elevation_path_iu(), ligne 5 à instruction SQL
```

Selon mes recherches, ce problème est dû a une incompatibilité de version. Ma question est donc de savoir quelles sont les versions supportées par Geotrek pour Postgres et Postgis sous ubuntu 20.04

**Comment by submarcos** [comment]
Hello. Ce n'est pas ubuntu 20.04 qui installe postgres 14, mais l'utilisation du repo apt postgresql, requis depuis un moment sur ubuntu bionic pour pouvoir utiliser postgis >= 2.5. https://geotrek.readthedocs.io/en/latest/install/installation.html#ubuntu-bionic-postgis-2-5-upgrade

Ubuntu focal lui vient avec [postgres 12](https://packages.ubuntu.com/focal/postgresql)

Si tu as simplement "full-ugrade", alors, comme indiqué dans les commentaires de la doc, le meta paquet ```postgresql-server``` a du installer  postgresql 14 et la derniere version de postgis.

D'apres https://gis.stackexchange.com/questions/377833/postgis-wont-update-geometry-when-importing-csv-file-with-psql il semblerait que to nseveur s'emmele les pinceaux entre des libs provenant de ton postgres et des libs venant du repo postgres. En mettant à jour un seveur, il arrive qu'ubuntu desactive les repos APT tierces

De plus, en passant à postgis  > 3, tu as besoin d'installer l'extension postgis_raster, l'as-tu fais ?

Je pense que le soucis (et le nom de cette issue) sont plus liés à des ises à jour qu'a des versions de postgres compatibles. J'a idéjà utilisé geotrek avec des postgres 15 et postgis 3.3 sans problème

**Comment by mviadere-openig** [comment]
Merci pour les informations, j'ai déjà fait une demande de TMA, je vais en profiter pour regarder en attendant la réponse.

**Comment by mviadere-openig** [comment]
Après avoir purgé correctement postgresql et postgis, j'ai tout réinstallé et cela semble bien tourner sous postgresql16. Dernière question avant de clôre le ticket : est-ce que c'est OK d'utiliser Postgres 16 ou il vaut mieux retourner sous Postgres 14 ?

**Comment by mviadere-openig** [comment]
Merci d'avoir pris le temps de répondre à ma question ! Beaucoup d'informations intéressantes, j'espère que cela pourra servir aussi à d'autres utilisateurs. Je clos le ticket.
