### ISSUE TITLE
Migration PostgreSQL

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-admin#3909]
Lien avec #3754 

Détailler la procédure à suivre pour migrer vers une version plus récente de postgres

**Comment by marcantoinedupre** [comment]
- fournir l'info dans la doc
- communiquer et inciter les utilisateurs à anticiper cette mise à jour
- vérifier compat GTA avec postgres16 pour permettre que la màj soit long-terme pour les utilisateurs
