### ISSUE TITLE
[PageStatiqueV2] Proposer des styles prédéfinis

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3921]
Proposer des styles pré-définis pour le contenu WYSIWYG des Pages Statiques (champ contenu TinyMCE). La solution identifiée est d'utiliser la configuration de Custom Formats (voir [la doc TinyMCE](https://www.tiny.cloud/docs/demo/format-custom/)), ces styles custom seraient attendus et affichés correctement sur les portails Geotrek Rando.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.104.0 (nécessite Geotrek-rando 3.19+) avec les styles "citation", "information", "lien bouton", en plus des classiques taille de titre, italique, etc...

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/9fdea38b-4f63-49c2-ad19-6fb6400fe596)
