### ISSUE TITLE
[PageStatiqueV2] Alignement des images

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3922]
En lien avec #3921

**Comment by marcantoinedupre** [comment]
J'ai fait des tests avec TinyMCE pour comprendre ce le fonctionnement des formats sur des blocs (`<p>`, `<div>`, ...), sur des images.

J'ai utilisé [l'exemple interactif de la doc des Custom Formats](https://www.tiny.cloud/docs/demo/format-custom/#). Pour insérer des images et visualiser les changements dans le code HTML généré il faut ajouter cette ligne dans la configuration (onglet « JS ») :

```
width: 800,
plugins: 'table wordcount code image',
```

En appliquant le custom format « Image left » sur une image inline au début d'un paragraphe :

(Menus `Format` > `Formats` > `Image left`)

![Image](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/8a5a9b72-5191-4c67-879e-f81999829aac)

J'ajoute l'option du plugin `image` pour saisir une légende :

```
width: 800,
plugins: 'table wordcount code image',
image_caption: true,
```

Mais le résultat entre en conflit avec le positionnement.

![Image](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/5a9606f7-0fd9-4500-b411-e132b2a2ed8d)

**Comment by camillemonchicourt** [comment]
La possibilité d'alignement des images à gauche ou à droite est nécessaire.
Mais elle doit aussi permettre un fonctionnement responsive où sur un petit écran l'image passe en 100% de largeur de l'écran.

**Comment by camillemonchicourt** [comment]
Il est possible d'aligner les images à gauche ou à droite.
Cela fonctionne aussi si on active et renseigne une légende à l'image en cochant "Activer le sous-titrage".
Il faut bien appliquer l'alignement à tout le bloc comme on voit ici : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/310372ca-793c-4169-b160-8a2210476dbd)

Le résultat est bien mis en forme ensuite côté Geotrek-rando.

En version Desktop : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/9a32fbf5-5ea0-4282-8845-4c5e912509e3)

En version Mobile : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/c6b1711b-ee86-4f52-8e70-61c8ec8e79fd)

**Comment by camillemonchicourt** [comment]
Dans la version 2.109.2, la possibilité d'intégrer des galeries photos a été ajoutée : https://github.com/GeotrekCE/Geotrek-admin/pull/4257
