### ISSUE TITLE
[Page Statique v2] Exposition arborescence menus dans API

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3936]
Ajout d'un nouveau endpoint, il y aura donc 2 endpoints :

- `/api/v2/pages/`
- `/api/v2/menu-items/`

## Remarques :

- le nom des propriétés sera en snake_case pour cohérence avec les endpoints déjà existants.

**nommage (non définitif)**

- `open_in_new_tab` : parlant de lui-même (autres noms possibles : `target_blank`, `external`, `internal`, ...)
- `link_type` : c'est le type de lien embarqué par l'élément de menu, soit vers une page statique, soit vers une URL (valeurs possibles : null, "page", "link" (ou "url")).
- j'aurais préféré nommer `target_type` la propriété précédente (`link_type`). Mais le concept de cible/target est déjà utilisé pour désigner la plateforme cible ("All", "Web", "Mobile"). Éventuellement on pourrait renommer la propriété 'target' actuelle en 'plateform' ou un autre nom (app, app_type, platform, medium, ...).

**présence conditionnelle des propriétés en fonction du type ?**

2 pistes :

1. afficher toutes les propriétés avec leurs valeurs par défaut ? (par exemple `open_in_new_tab` est présent à false même si le `link_type` est "page")
2. Ou bien placer dans l'objet uniquement les propriétés qui correspondent au `link_type` ? (car la seconde option est moins verbeuse elle est utilisée pour l'exemple ci-dessous)

**filtre par portail(s)**

- l'exemple suppose que le endpoint `/api/v2/menu-items/` ne retourne les éléments de menu que pour un unique portail (spécifié dans les paramètres ou par défaut). Si on conserve le paramètres `portals` par cohérence avec le reste de l'API il faut ajouter la propriété `portal_id` sur les objets (au moins au 1er niveau).
- possibilité d'ajouter une marque "par défaut" sur les Portails : si le paramètre API "portal" n'est pas fourni c'est l'arborescence du portail par défaut qui est retournée.
- actuellement Geotrek Rando peut être configuré avec une liste de portails, mais il ne pourra pas afficher plusieurs arborescences simultanément. Il faudra prévoir un mécanisme côté Geotrek Rando pour requêter les éléments de menu d'un unique portail (proposition naïve : le 1er portail de la liste `portalsId` est celui dont on affiche l'arborescence).
- on n'a pas prévu de développements sur l'appli mobile pour gérer l'arborescence de menus, pour conserver la rétro-compatibilité il faudra que la migration django + une refonte de sync_mobile rende la nouvelle fonctionnalité invisible pour les applis mobiles.

**Rétro-compatibilité**

- les portails utilisant actuellement le menu « En savoir plus » doivent rester tel quels -> configuration à prévoir côté Geotrek Rando pour basculer de mode.
- l'ajout du nouveau modèle MenuItem et la création des objets depuis les pages statiques existantes sera faite dans la migration Django.

## Exemple de réponse de l'API pour les MenuItems

Pour l'arborescence de menus suivante pour le portail 1 :

```
"La destination" (pas de cible)
	> "Venez découvrir le parc national" (cible: page)
	> "Mobilité" (cible: page)
"La randonnée à la journée" (pas de cible)
	> "Partages autour de nos randonnées" (cible: page)
	> "Itinéraires" (cible: lien interne)
"Infos et bonnes pratiques" (cible: page)
```

`GET /api/v2/menu-items/?portal=1`

```
[
  {
    "label": "La destination",
    "link_type": null,
    "children": [
      {
        "label": "Venez découvrir le parc national",
        "link_type": "page",
        "page_id": 42
      },
      {
        "label": "Mobilité",
        "link_type": "page",
        "page_id": 43
      }
    ]
  },
  {
    "label": "La randonnée à la journée",
    "link_type": null,
    "children": [
      {
        "label": "Partages autour de nos randonnées",
        "link_type": "page",
        "page_id": 56
      },
      {
        "label": "Itinéraires",
        "link_type": "url"
        "url": "/search?practices=4&difficulty=3&duration=1"
        "open_in_new_tab": false
      }
    ]
  },
  {
    "label": "Les bonnes pratiques dans le Parc",
    "link_type": "url",
    "url": "https://le-parc.fr/bonnes-pratiques/"
    "open_in_new_tab": true
  }
}
```

**Comment by camillemonchicourt** [comment]
- Selon moi, il faut abandonner la notion de cible (all, web, mobile). C'était un truc un peu tordu pour avoir certaines pages statiques uniquement sur l'application mobile, ou seulement sur le portail web, mais selon moi ce n'est pas pertinent ni utile et donc à supprimer.
- Je pense qu'il faut toujours renvoyer les mêmes propriétés peu importe le type d'objet
- Pour les filtres par portail, je ne vois pas bien tout le fonctionnement et ne comprend pas la notion de "par défaut", mais à discuter. Il y a aussi des instances de Geotrek qui fonctionnent sans aucune notion de portail
- Il y a peut-être une solution pour ne pas devoir prévoir 2 modes de menus côté Geotrek-rando. Créer automatiquement un item "En savoir plus" et y intégrer les pages statiques à partir de la 4° ?

**Comment by marcantoinedupre** [comment]
Pour détailler le point filtre par portail :

- Actuellement tous les endpoints acceptent une liste d'ID de portails comme paramètre d'API pour filtrer les entités retournées.
- Geotrek Rando prend une liste d'ID dans sa configuration et la passe telle quelle à ses appels à l'API (`portalsId`)
- La question se pose de conserver ce fonctionnement pour les endpoints `menu-items` et `flatpages` car Geotrek Rando ne pourra pas afficher un "mix" de 2 arborescences s'il est configuré avec plusieurs portails.

Possibilités :

1. les endpoints `menu-items` et `flatpages` ont un paramètre API `portal` (et pas `portals` comme pour les autres). Le frontend a une stratégie pour passer un unique ID de portail (par exemple le premier de sa configuration).
2. les endpoints ont un paramètre `portals`. Le frontend passe plusieurs IDs de portails et reçoit plusieurs arborescences. Le frontend n'en affiche qu'une ?

Dans le cas de la possibilité 1. il faudrait idéalement que le paramètre API ne soit pas obligatoire et qu'une arborescence soit retournée pour un appel sans portail spécifié. D'où l'idée d'avoir un portail « par défaut ».

**Comment by camillemonchicourt** [comment]
OK OK, je n'avais pas en tête qu'on pouvait renseigner plusieurs portails au niveau de Geotrek-rando, et je ne vois pas trop l'usage. On avait certainement fait ça pour une raison identifiée mais je ne me souviens plus.
Pour moi, un Geotrek-rando appelle soit aucun portail, soit un seul portails, mais plusieurs portails, je ne vois pas trop...

Dans tous les cas, je pense qu'il faut trouver un fonctionnement homogène. A discuter.

**Comment by marcantoinedupre** [comment]
**champ `Cible` (_target_) avec les valeurs possibles : `all`, `web`, `mobile`**

- proposition de supprimer pour simplifier l'interface (voir issue https://github.com/GeotrekCE/Geotrek-admin/issues/3940 pour suivre ce point)
- en attente de retours : je vais inclure ce champ dans les MenuItems sauf si ça soulève des problèmes d'implémentation, auquel cas on réévaluera la situation.

**Comment by marcantoinedupre** [comment]
**Filtre par portail sur la page liste des MenuItems et dans l'API**

Suite discussion je confirme que c'est OK de permettre de lister les éléments de menus sans filtre (de tous les portails) ou de plusieurs portails spécifiés (filtre `portals` de l'API). C'est simple du point de vue du développement, au prix je pense d'une interface et d'un modèle mental un peu moins clair pour les utilisateurs.

Pour l'API on garde le filtre `portals` avec le même fonctionnement que pour les autres endpoints (`/api/v2/trek/`, `/api/v2/theme/`, etc). Dans le cas d'une instance Geotrek Rando configurée pour récupérer les données de plusieurs portails l'affichage des menus sera fait tel quel dans l'ordre donné par la réponse de l'API Geotrek Admin. Charge à l'utilisateur d'associer les menus aux portails judicieusement pour obtenir l'arborescence souhaitée.

Je pars là-dessus pour le développement.

Côté page liste des menus dans l'admin le filtre par portail aura les valeurs suivantes :

- « Tous » : tous les éléments de menus sont affichés (associés à n'importe quel portail ou non-associés). Les éléments apparaissent mélangés, il n'y a pas de tri par portail.
- « Portail 1 » : affiche uniquement les éléments associés au Portail 1.
- « - » : affiche uniquement les éléments qui ne sont pas associés à un portail.

Côté API :

- `/api/v2/menu_items/` : retourne tous les éléments (associés à n'importe quel portail ou non-associés). Les éléments sont mélangés. L'ordre est le même que sur la page admin.
- `/api/v2/menu_items/?portals=1` : retourne tous les éléments associés au Portail 1.
- `/api/v2/menu_items/?portals=1,2` : retourne tous les éléments associés au Portail 1 ou au Portail 2.

**Attention : le filtre de la page admin et le filtre de l'API ne sont pas identiques !**

**Comment by marcantoinedupre** [comment]
**format des pages dans l'API**

Correspond aux pages ciblées par l'arborescence de menus donnée en exemple ci-dessus. Il y a également 3 pages enfants qui seront accessibles sur le portail rando via leur page parente. (Les pages ci-dessous sont simplifiées pour mettre en avant l'arborescence, voir plus loin pour l'ensemble des propriétés)

`GET /api/v2/flatpage/?language=fr&portals=1,2`

```
[
  {
    "title": "Venez découvrir le parc national",
    "id": 42,
    "content": "...HTML content...",
    "portals": [1, 2],
    "children": []
  },
  {
    "id": 43,
    "title": "Comment se déplacer dans le parc national",
    "content": "...HTML content...",
    "portals": [1, 2],
    "children": []
  },
  {
    "title": "Partages autour de nos randonnées",
    "id": 56,
    "content": "...HTML content...",
    "portals": [1, 2],
    "children": [
      {
        "title": "Balade dans le Trifouillois",
        "id": 788,
        "content": "...",
        "portals": [1, 2],
        "children": []
      },
      {
        "title": "Autour des lacs",
        "id": 798,
        "content": "...",
        "portals": [1, 2],
        "children": []
      },
      {
        "title": "La chaîne des monts",
        "id": 699,
        "content": "...",
        "portals": [1, 2],
        "children": []
      }
    ]
  }
]
```



<details><summary>Exemple de page avec toutes les propriétés :</summary>
<p>

```
{
  "title": {
    "fr": "Venez découvrir le parc national",
    "en": ""
  },
  "id": 42,
  "content": {
    "fr": "HTML content",
    "en": "..."
  },
  "children": [],
  "sources": [
    22,
    23
  ],
  "portals": [
    1,
    2
  ],
  "published": {
    "fr": true,
    "en": false,
  },
  "attachments": [
    {
      "backend": "",
      "type": "image",
      "filetype": {
        "id": 32,
        "structure": null,
        "type": "Photographie"
      },
      "author": "",
      "license": null,
      "thumbnail": "https://demo-admin.geotrek.fr/media/paperclip/flatpages_flatpage/1/troglodyte_mignon-i42yi9jhe6x8_yne8unq.jpg.400x0_q85.jpg",
      "legend": "",
      "title": "",
      "url": "https://demo-admin.geotrek.fr/media/paperclip/flatpages_flatpage/1/troglodyte_mignon-i42yi9jhe6x8_yne8unq.jpg",
      "uuid": "b62bf91c-e682-4412-aed7-202f38a97932"
    }
  ]
}
```

</p>
</details> 

On peut aussi envisager un format liste à plat comme déjà utilisé et ce serait au frontend de reconstituer l'arborescence.

**Comment by marcantoinedupre** [comment]
**Notes pour filtrage par portails et par publication selon la langue**

Je pense que ces 3 règles sont pertinentes pour comment l'API expose les entités si filtrage par portails et par langue (càd l'usage actuel de Geotrek Rando) :

`GET /api/v2/menu_item/?language=F&portals=A`

- (base) pour un portail A et une langue F un objet Menu/Page est retourné si lui-même et ses parents sont associés à A et publiés pour F
- (pour facilitation) une Page est considérée associée à A si un Menu la ciblant est associé à A
- (protection contre 404 NOT FOUND) un Menu publié pour F mais ciblant une Page non-publiée pour F n'est pas retourné

**Comment by camillemonchicourt** [comment]
Fait dans la 2.104.0 (nécessite Geotrek-rando 3.19+) avec la création d'un objet "Elément de menu" complémentaire aux pages statiques, et qui pilote donc le menu désormais.
Voir doc : https://geotrek.readthedocs.io/en/latest/usage/static-pages.html
