### ISSUE TITLE
[Cirkwi] Pouvoir exclure les itinéraires ayant un identifiant externe de l'API Cirkwi

### ISSUE THREAD

**Issue by Chatewgne** [GeotrekCE/Geotrek-admin#3957]
- [ ] Ajout dans l'API Cirkwi (le flux Geotrek qui envoi des données vers Cirkwi) un filtre pour ne pas renvoyer les itinéraires qui possèdent un eid (afin d'éviter d'envoyer à Cirkwi les itinéraires qu'il nous a lui-même envoyé). 
- [ ] MAJ de la documentation associée.

**Comment by babastienne** [comment]
Duplicate of #3947  ?

**Comment by Chatewgne** [comment]
> Duplicate of #3947 ?

Ah oui pardon, je ferme
