### ISSUE TITLE
Intégration composant "Suggestions"

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4019]
> Pouvoir intégrer dans les pages statiques un composant assez similaire avec les actuelles suggestions de la Home, en fournissant une liste d’ID ou une catégorie d’objets avec des filtres.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.104.0 (nécessite Geotrek-rando 3.19+).

Dans l'éditeur de pages statiques, un bouton a été ajouté permettant d'intégrer facilement des suggestions de contenus en renseignant leur identifiant : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/d6977fde-e8a7-45e6-8f13-ff1e6f94ddc3)

Cela créé automatiquement un bloc de suggestion dans la page : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/cd03a47e-791c-447d-ab7c-332a4ddd05ad)

Qui est ensuite automatiquement interprété et mis en forme au niveau de Geotrek-rando : 

![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/ff100e46-01e6-4766-9675-ee205d8bf389)

Documenté sur https://geotrek.readthedocs.io/en/2.104.1/usage/static-pages.html#inserer-des-suggestions-de-contenu-geotrek
