### ISSUE TITLE
Ajouter une icone pour les MenuItems

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4027]
Permettre d'ajouter une image pictogramme pour enrichir le visuel des éléments de menu.

![Image](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/b80c2a5c-4b42-4113-8749-9497d8806d69)

Le wireframe montre des MenuItems avec une icone uniquement sur les éléments de droite mais cette fonctionnalité serait ajoutée pour l'ensemble des MenuItems. Charge à l'utilisateur composant les menus de produire un contenu cohérent et équilibré.

**Étapes :**

- ajout champ image sur le type MenuItem
- l'URL de l'image est exposée comme une nouvelle propriété de MenuItem dans l'API
- quand un pictogramme existe pour un EM le frontend l'affiche avant le label

**Complexité :** cet ajout semble relativement facile.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.104.0 (nécessite Geotrek-rando 3.19+) au niveau des éléments de menu : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/1934705d-19b8-4500-96a5-0be8723d8835)

Optionnel. Affiché avant le nom de l'élément de menu au niveau de Geotrek-rando : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/cf586f47-3f8d-4e4d-b33a-4b2330c92f4b)
