### ISSUE TITLE
Ajouter thumbnail pour MenuItems

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4028]
Ajouter un attribut image aux MenuItems pour une présentation avec un thumbnail (vignette) et le label en surimpression dans les menus.

![Image](https://github.com/GeotrekCE/Geotrek-admin/assets/15977920/c2de4120-417a-4bf3-8e7e-c659066673af)

**Étapes :**

- ajout d'un attribut `thumbnail` au modèle `MenuItem`
- attribut `thumbnail` est optionnel
- selon qu'un thumbnail est fourni ou non le frontend sait quel est le mode d'affichage adéquat pour une élément de menu (sur l'exemple du wireframe : placement dans la colonne dédiée)

**Complexité :** cet ajout semble plutôt facile.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.104.0 (nécessite Geotrek-rando 3.19+) au niveau des éléments de menu.

Optionnel, affiché sur les éléments de menu de niveau 2 côté Geotrek-rando : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/56f01786-65ba-4c65-b67c-1b0a7031cf2f)
