### ISSUE TITLE
Clarifier formulaire page statique avec affichage conditionnel des champs

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4029]
Qqsoit le chemin technique (avec ou sans MenuItem) il serait intéressant d'afficher/cacher des champs du formulaire en fonction du type d'entité ciblé par un Élément de menu : une page, un lien, la page des actualités ?

Par exemple si la cible est un lien : on veut afficher le champ "URL du lien" mais cacher la sélection d'une Page Statique.

Il y a ce qu'il faut avec Django pour réaliser cet affichage conditionnel. Un code très spécifique pour les champs des modèles FlatPage/MenuItem serait assez rapide à mettre en place.

- utiliser la customization des widgets pour afficher/cacher certains champs en fonction des valeurs d'autres champs.
- utiliser les Form Assets pour charger les JS/CSS supportant cette fonctionnalité.
- surcharger méthode `clean` pour ajuster la validation des champs requis en fonction de s'ils étaient affichés ou non.

Ressources :

- [customiser les attributs des widgets](https://docs.djangoproject.com/en/3.2/ref/forms/widgets/#customizing-widget-instances)
- [charger du JS/CSS additionnel pour des widgets](https://docs.djangoproject.com/en/3.2/ref/forms/widgets/#styling-widget-classes)
- [Conditional logic in Django forms](https://codeinthehole.com/tips/conditional-logic-in-django-forms/)
- [Creating Conditionally Required Fields in Django Forms](https://www.fusionbox.com/blog/detail/creating-conditionally-required-fields-in-django-forms/577/)
- [using jquery](https://stackoverflow.com/questions/10200498/jquery-conditional-show-an-element-based-on-drop-down-box-selection)
- [django-formset (starting with django>4)](https://django-formset.readthedocs.io/en/latest/conditionals.html)

**Comment by marcantoinedupre** [comment]
Finalement ressorti du backlog car plutôt facile à mettre en place pour en résultat une clarification du formulaire admin (ce qui était une des raisons derrière l'introduction des MenuItems).

**Comment by camillemonchicourt** [comment]
Si je choisis un élément de menu de type "page", j'ai ce formulaire : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/c1b1f44b-f593-485f-8e39-58a65d568bb0)

Si je choisis un élément de menu de type "lien", j'ai ce formulaire : 
![image](https://github.com/GeotrekCE/Geotrek-admin/assets/4418840/a21d2f9f-d124-4f37-9a4f-a3a51e7308e8)

**Comment by camillemonchicourt** [comment]
Fait dans la 2.104.0 (nécessite Geotrek-rando 3.19+) au niveau des éléments de menu.
