### ISSUE TITLE
API v2 signalétique en ERREUR

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#4052]
Constaté sur plusieurs instances : https://geotrekdemo.ecrins-parcnational.fr/api/v2/signage/

https://demo-admin.geotrek.fr/api/v2/signage/

Je ne sais pas depuis quelle version, mais cela peut poser soucis à Geotrek-rando qui utilise cette route.

**Comment by amandine-sahl** [comment]
en lien avec #3839

**Comment by babastienne** [comment]
Bien vu, merci @amandine-sahl 

Je clôture car doublon
