### ISSUE TITLE
Migration des "Pages Statiques" : Éléments menu de type lien non reporté

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#4083]
Lors de la migration des pages statiques avec un lien externe, les éléments de menus sont bien créés mais le type de cible est "page" et non pas lien.

**Comment by camillemonchicourt** [comment]
OK, étonnant car j'avais testé les migrations, dont le cas des liens externes et ça avait été OK, ça m'avait supprimé la page statique et créé un item de menu de cible LIEN avec l'URL externe.
Je pense que c'est dans cette migration : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/flatpages/migrations/0011_migrate_flatpage_data.py

Est-ce que cette page statique n'avait qu'un lien vers une URL ?

**Comment by marcantoinedupre** [comment]
Je confirme que la migration d'une ancienne page statique comportant uniquement un lien externe est couvert.

Dans le cas où un lien externe et du contenu auraient été simultanément saisis sur la page (dans n'importe quelle langue) un élément de menu ciblant la page est créé. Le but est de conserver toutes les infos.

Voir :

- [fonction `get_page_type`](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/flatpages/migrations/0011_migrate_flatpage_data.py#L33)
- [et les différents traitements selon le type de page](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/flatpages/migrations/0011_migrate_flatpage_data.py#L146)
