### ISSUE TITLE
Menu Items without target should have `open_in_new_tab` field to false

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4093]
Les éléments de menus sans cible devraient avoir leur champ `open_in_new_tab` à False (sinon les portails basés sur l'API peuvent afficher des infos fausses - par exemple geotrek-rando-v3 affiche une icone "lien externe" alors que le menu n'est pas un lien).

**Comment by camillemonchicourt** [comment]
On n'aurait vraiment pas du mettre ce champs `open_in_new_tab` à `true` par défaut, trop d'effets de bord ! 😀
Et c'est vraiment un cas trop particulier quand on veut un lien du menu s'ouvre dans un autre onglet.

**Comment by camillemonchicourt** [comment]
Done in 2.105.0.

**Comment by marcantoinedupre** [comment]
## Résolution

Après màj de geotrek-admin, pour corriger les éléments de menus existants, les éditer et ré-enregistrer (sans modifications).

**Comment by marcantoinedupre** [comment]
> On n'aurait vraiment pas du mettre ce champs `open_in_new_tab` à `true` par défaut, trop d'effets de bord ! 😀 

En effet, ça fait beaucoup de correctifs pour une valeur par défaut. :)

> Et c'est vraiment un cas trop particulier quand on veut un lien du menu s'ouvre dans un autre onglet.

Je pense que le lien externe est vraiment le cas d'usage le plus courant. Mais j'aurais pu/dû inverser le sens du champ booléen pour éviter ces problèmes : « Ouvrir dans le même onglet » non coché par défaut.

**Comment by camillemonchicourt** [comment]
De manière globale, sur tous les items de menu qui sont principalement associés à des pages statiques, on est sur `open_in_new_tab` = `false`. Donc déjà dans ce cas principal, la valeur par défaut pose un peu soucis.

Ensuite pour les cas moins fréquent où un item de manu pointe vers un lien, est-ce qu'on aura plus souvent des liens externes ou des liens internes (lien vers des recherches pré-filtrées notamment), faudra voir. Pas certain de l'usage qui sera le plus fréquent de manière générale. Pour nous en tout cas, ça sera plus de liens internes. Donc là aussi `open_in_new_tab` = `false`.

Pour ces différentes raisons ma solution privilégiée reste de passer le champs le champs `open_in_new_tab` à `false` par défaut et ne pas faire du JS qui coche et décoche selon les cas, mais si on n'a plus d'effet de bord, c'est un détail. 😀
