### ISSUE TITLE
Error with migration to MenuItem: value too long for type character varying(50)

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4095]
La migration de données pour créer les nouveaux éléments de menus à partir des pages statiques existantes échoue avec l'erreur ci-dessous dans le cas d'une montée de version vers les version suivantes `2.104.0`, `2.104.1`, `2.104.2` avec des pages statiques dont les titres dépassent 50 caractères.

```
django.db.utils.DataError: value too long for type character varying(50)
```

**Comment by camillemonchicourt** [comment]
Done in 2.105.0.

**Comment by marcantoinedupre** [comment]
## Résolution

1. revenir à la version de GTA 2.103.2
2. annuler la 1ère migration de GTA 2.104.0 (voir ci-dessous)
3. refaire la montée de version

**1. revenir à la version de GTA 2.103.2**

package .deb

```
wget https://github.com/GeotrekCE/Geotrek-admin/releases/download/2.103.2/geotrek-admin_2.103.2.ubuntu20.04_amd64.deb
sudo apt install geotrek-admin_2.103.2.ubuntu20.04_amd64.deb
```

docker image : `geotrekce/admin:2.103.2`

**2. annuler la 1ère migration de GTA 2.104.0**

```
sudo geotrek migrate flatpages 0009
```

ou

```
docker-compose run --rm web ./manage.py migrate flatpages 0009
```

La commande devrait échouer avec l'erreur ci-dessous mais c'est OK la migration 0010 a bien été renversée.

```
psycopg2.errors.UndefinedTable: relation "flatpages_menuitem" does not exist
LINE 1: SELECT * FROM "flatpages_menuitem" LIMIT 1
```

**3. recommencer la montée de version vers geotrek-admin>=2.105.0**
