### ISSUE TITLE
Arbitrage sur la suppression ou correction du paramètre SHOW_SENSITIVE_AREAS_ON_MAP_SCREENSHOT

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-admin#4113]
Actuellement ce paramètre est présent dans code de Geotrek-admin, mais n'est plus opérationnel : 

- https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/models.py#L495
- https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L609

La manière de l'utiliser se trouve dans la documentation : https://geotrek.readthedocs.io/en/2.106.0/install/advanced-configuration.html#map-screenshots

**Question** : faut il le supprimer définitivement du code ou le refaire fonctionner ?

Une PR est actuellement ouverte pour remettre le setting dans la documentation (précédemment supprimé dans une [PR](https://github.com/GeotrekCE/Geotrek-admin/pull/4108)): https://github.com/GeotrekCE/Geotrek-admin/pull/4112

**Comment by camillemonchicourt** [comment]
Étant donné qu'il y a d'autres paramètres similaires pour d'autres objets, et que les zones sensibles peuvent venir complexifier la lecture et la compréhension de la carte dans les exports, je pense qu'il est pertinent de garder ce paramètre.
