### ISSUE TITLE
[Question] Chargement des données minimum

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-admin#4220]
Bonjour, 

Arrivé dans une nouvelle structure je souhaites étudier la possibilité d'utiliser geotrek-admin comme passerelle entre notre outils de gestion des randonnée déployé dans une centaine de communes et geotrek-rando. 

J'ai déjà utilisé geotrek mais en version 2.29. 

L'installation est toujours aussi simple ce qui est vraiment agréable. Par contre je ne trouve pas la commande pour ajouter les données minimum. Auriez vous la commande ?

Bonne journée,

**Comment by camillemonchicourt** [comment]
Oui ça s'est même pas mal amélioré au niveau installation depuis la version 2.33 avec la mise en place d'un package Debian. Cela permet un installation mais aussi une mise à jour très simple en une ligne de commande (https://geotrek.readthedocs.io/en/latest/install/installation.html). 😀
Et il y a aussi un Docker pour ceux qui préfèrent.

Pour les données minimales, pouvez-vous préciser à quoi vous faites référence ? 

Car lors d'une installation classique, cela installe bien les différents modules et les données de bases (typologies diverses par défaut, etc...).

Ensuite il faut que vous chargiez les données de votre territoire (communes, zonages, MNT) puis votre référentiel de tronçons de base (idéalement depuis la BD topo, OSM ou autre référentiel) : https://geotrek.readthedocs.io/en/latest/install/loading-data.html

**Comment by eprouteau** [comment]
Merci pour votre retour rapide comme à chaque fois.

Oui j'ai halluciné :) sur la simplicité d'installation après avoir pris un petit VPS dans un premier temps (n'étant pas du tout admin system).

J'ai enlevé "en" dans les langues lors de l'Install ce qui qui a surement fait planter l'intégration des données de base (typologies diverses par défaut, etc...).

Afin d'utiliser geotrek admin comme passerelle, je vais désactiver la segmentation dynamique. Est ce que cela concerne également l'association des POI aux itinéraires ?

**Comment by camillemonchicourt** [comment]
Ah oui les langues FR et EN sont obligatoires, les autres sont optionnelles et on peut en ajouter d'autres.
Il faudrait qu'on l'indique dans la doc si ce n'est pas déjà le cas.

OK pour la version Light (sans segmentation dynamique, sans tronçons, sans modules de gestion), je ne sais pas si on peut modifier après installation, je n'ai jamais testé ce mode.

Les POI fonctionnent en mode Light, mais sont rattachés à l'itinéraire le plus proche par buffer (zone tampon) et intersection géographique et non pas par les tronçons communs entre POIs et itinéraires.

**Comment by eprouteau** [comment]
Après installation j'ai indiqué dans le custom.py la ligne `TREKKING_TOPOLOGY_ENABLED = True en False 

Ce qui me donne un menu plus light.
![image](https://github.com/user-attachments/assets/22991d74-0505-4ca5-9574-270cf43784ca)

Ce mode est top du coup pour créer une routine entre notre outil de gestion communal et geotrek-admin

**Comment by camillemonchicourt** [comment]
OK super.
Et ensuite les contenus seront diffusés dans un Geotrek-rando ou autre ?

**Comment by eprouteau** [comment]
L'idée effectivement serait d'utiliser geotrek-rando pour proposer ce mode de valorisation aux communes et EPCI.

**Comment by eprouteau** [comment]
Problème résolu merci

**Comment by camillemonchicourt** [comment]
Résolu comment ?

**Comment by eprouteau** [comment]
Les données minimum se chargent automatiquement dès lors que FR et EN sont renseignés. J'avais enlevé EN ce qui n'avait pas chargé les données.

**Comment by camillemonchicourt** [comment]
OK donc on peut le faire après coup, même si l'installation n'a pas été faite initialement avec les langues minimales si j'ai bien compris ?
Vous avez juste relancé une commande (laquelle ?) ou du refaire une installation complète ?

**Comment by eprouteau** [comment]
J'ai refait une installation car j'en étais qu'au début. J'ai tenté de cherché dans le code des commandes qui m'aurais permis de m'en sortir mais sans succès.

Peux être que lors de l'installation le champs des langues pourrait ne contenir que des langes optionnelle et que finalement le FR et EN soit réalisé par default sans que cela soit possible de les supprimer
