### ISSUE TITLE
Erreur api sur touristiccontent : ZeroDivisionError  float division by zero

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#4231]
Geotrek-admin : 2.108.0

Geotrek-rando : latest 

Certains itinéraires de ce Geotrek-rando n'arrivent pas à afficher leur contenus  (exemple): [https://rando-pnrgc-dev.openig.org/trek/7059-Le-Viaduc-de-Millau](https://rando-pnrgc-dev.openig.org/trek/7059-Le-Viaduc-de-Millau)

erreur console du navigateur : Impossible de charger « https://openig-geotrek-pnrgca.ataraxie.fr/api/v2/touristiccontent/?language=fr&near_trek=7059&page_size=50&fields=id,attachments,name,category,description_teaser,geometry&portals=2 ». Un ServiceWorker a transmis un objet « Error Response » à FetchEvent.respondWith(). Cela signifie généralement que le ServiceWorker a effectué un appel fetch() invalide. [workbox-71de1fb1.js:1:822](https://rando-pnrgc-dev.openig.org/workbox-71de1fb1.js)

Je poste ici car il semblerait que ce soit un problème en provenance de l'api du Geotrek-admin. 

Lien Sentry : [https://sentry.openig.org/share/issue/05784db1d370444f90652ea57d4731c9/](https://sentry.openig.org/share/issue/05784db1d370444f90652ea57d4731c9/)

Devant l'urgence de la situation pour ce territoire, nous sommes prêt à utiliser une heure de TMA pour identifier/régler le problème avec Makina Corpus.

**Comment by Chatewgne** [comment]
Bonjour Mickaël,

cette erreur remonte ces derniers temps sur des objets pour lesquels il y a des fichiers attachés problématiques, parfois l'API vient à essayer de générer une miniature pour un fichier attaché qui n'est pas une image, et ça cause cette exception

Il doit y avoir un ou des Contenus Touristiques dont les identifiants sont listés ici qui ont pour fichier lié quelque chose qui n'est pas une image : 

[https://openig-geotrek-pnrgca.ataraxie.fr/api/v2/touristiccontent/?language=fr&near_trek=7059&page_size=50&fields=id&portals=2](https://openig-geotrek-pnrgca.ataraxie.fr/api/v2/touristiccontent/?language=fr&near_trek=7059&page_size=50&fields=id&portals=2)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.109.0.
