### ISSUE TITLE
Affichage "photos accessibilité"

### ISSUE THREAD

**Issue by julienchaudet** [GeotrekCE/Geotrek-admin#4336]
Bonjour,
Nous sommes en train de compléter les infos sur l'accessibilité de nos fiches itinéraires, quand je charge une photo dans l'onglet "Photos accessibilité", elle n'apparait pas dans la fiche publiée. Comment l'utilisateur peut-il la consulter ?

**Comment by camillemonchicourt** [comment]
Salut.

En effet, on a pas mal enrichi les infos liées à l'accessibilité dans 2.76.0 de Geotrek-admin (février 2022) : https://github.com/GeotrekCE/Geotrek-admin/issues/2838

Si tu ajoutes des images liées à l'accessibilité, elles apparaitront sur Geotrek-rando dans le bloc ACCESSIBILITÉ comme dans cet exemple : https://gtr3demo.ecrins-parcnational.fr/trek/2-Col-de-Font-Froide#details_accessibility
Cette partie affichage sur GTR3 est détaillée ici : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/536

**Comment by julienchaudet** [comment]
Top, merci Camille pour ta réactivité.
Je vais regarder comment tout ça fonctionne et je reviens vers toi si besoin.
