### ISSUE TITLE
Switch from tinymce to bootstrap-wysiwyg

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#691]
Looks nice and mature now http://mindmup.github.io/bootstrap-wysiwyg/

**Comment by babastienne** [comment]
The project bootstrap-wysiwyg is not updated anymore.
However an alternative could be https://alex-d.github.io/Trumbowyg/ which seems lighter than tinyMCE and easy to use. In addition it embed native browser features (like spellcheck) which seems way easier than tinyMCE which is freemium and requires to pay for spellcheck. I think we should look into it.

**Comment by babastienne** [comment]
After looking more deeply into TinyMCE, it appears browser spell checking is not activated in mapentity. The PR https://github.com/makinacorpus/django-mapentity/pull/276 fix this problem.

I doubt it is usefull to switch from TineMCE to another tool. There is still some issues with TinyMCE (paid plugins, weight of the tool), but they are not major and in my opinion it would be unnecessary to replace with another wysiwyg editor now.

In any case bootstrap-wysiwyg is out of the table.
