### ISSUE TITLE
Navigation is globally slow if paths table is huge

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#814]

**Comment by camillemonchicourt** [comment]
Des premières évolutions ont été apportées sur les performances de chargement des contenus et de navigation dans l'interface (cache, compression, pagination serveur...) et intégrées dans la version 2.84.0.
D'autres évolutions sont possibles et sont détaillées sur https://github.com/GeotrekCE/Geotrek-admin/issues/2967.
