### ISSUE TITLE
Path name field length too short

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#837]
Augmenter la limite du nombre de caractères. 20 caractères ne suffit pas tout le temps. 50 caractères.

**Comment by camillemonchicourt** [comment]
Fixed by https://github.com/GeotrekCE/Geotrek-admin/pull/2066

**Comment by gutard** [comment]
Attention à ne pas clore trop rapidement les tickets. Tant que la PR n'est pas mergée dans master et que la release n'est pas faite, le problème n'est vraiment résolu. La PR peut être fermée sans être mergée et la release peut attendre un certain temps.

**Comment by camillemonchicourt** [comment]
Exact, j'ai hésité, j'aurai du commenter uniquement.
