### ISSUE TITLE
Intervention stake should not be mandatory

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#905]
Rendre ce champ NON obligatoire car son utilisation n'est pas encore bien identifiée et du coup cela pose de nombreuses interrogations lors de la saisie selon les utilisateurs.

**Comment by submarcos** [comment]
already [done](https://github.com/GeotrekCE/Geotrek-admin/commit/4da4dff1358977bbe20698ec9e23692ee37d7e4c)
